### ISSUE TITLE
'ddev config' should default to existing config values unless overridden with flags

### ISSUE THREAD

**Issue by wizonesolutions** [ddev/ddev#1919]
**Describe the bug**
Some complex projects, like multisite Drupal projects, use `type: php` in order to manage settings themselves. However, ddev detects them at `drupal7` or `drupal8` every time it is run. This includes when it is run non-interactively! Thus, developers can get blindsided and have ddev files or file content added to their hand-crafted settings files if they aren't very careful.

**To Reproduce**
1. Run `ddev config` with a Drupal 8 project. Select `php` as the project type.
2. Run `ddev config` again. Notice how it defaults to 'drupal8'.
3. Run `ddev config --use-dns-when-possible=false`. Notice how it **automatically generates Drupal 8 settings and changes the project type without asking**.

**Expected behavior**
The only time project type should be auto-detected is when `.ddev/config.yaml` does not exist at all, and perhaps even when no `.ddev/config.*.ya?ml` files exist.

**Version and configuration information (please complete the following information):**
 - Host computer OS and Version: Manjaro Linux
 - Docker version information (use `docker version`) and insert it here.
```
Client:
 Version:           19.03.4-ce
 API version:       1.40
 Go version:        go1.13.1
 Git commit:        9013bf583a
 Built:             Sat Oct 19 04:40:07 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.4-ce
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.1
  Git commit:       9013bf583a
  Built:            Sat Oct 19 04:39:38 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.3.0.m
  GitCommit:        d50db0a42053864a270f648048f9a8b4f24eced3.m
 runc:
  Version:          1.0.0-rc9
  GitCommit:        d736ef14f0288d6993a1845745d6756cfc9ddd5a
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

 - ddev version information (use `ddev version`)
```
DDEV-Local version	v1.11.2                        
commit            	v1.11.2                        
db                	drud/ddev-dbserver:v1.11.0-10.2
dba               	drud/phpmyadmin:v1.11.0        
ddev-ssh-agent    	drud/ddev-ssh-agent:v1.11.0    
docker            	19.03.4-ce                     
docker-compose    	1.24.1                         
os                	linux                          
router            	drud/ddev-router:v1.11.0       
web               	drud/ddev-webserver:v1.11.0    
```

 - config.yaml contents for the misbehaving project

Can sanitize and include if needed. It has `type: php`.

 - Do you have any custom configuration (nginx, php, mysql) in the .ddev folder? If so, have you tried without them?

N/A

**Additional context**

N/A

**Comment by rfay** [comment]
Thanks for this! Definitely true. I changed the title to "default to existing values"

**Comment by rfay** [comment]
So @wizonesolutions could you mention why you run `ddev config` after first time? Just to get rid of the nag about version?

**Comment by wizonesolutions** [comment]
Yep, to get rid of the nag about version. And in new ddev versions where
it's necessary to generate some of the new files as features get added.

**Comment by rfay** [comment]
FYI, new files get generated on Start, I think, not necessary for config. And of course you could manually update the config.yaml with version. Not suggesting that, just trying to learn the context. I definitely think `ddev config` should default to existing values.

**Comment by wizonesolutions** [comment]
One good example though is when the docs say to use ddev config to change
one specific value (see steps to reproduce). This behavior is also there
then.

**Comment by rfay** [comment]
Closing this in favor of 
* #4403 

Pretty sure it's the same, speak up if not.
