### ISSUE TITLE
Add Windows ddev bash completion capability to installer

### ISSUE THREAD

**Issue by rfay** [ddev/ddev#1934]
**Is your feature request related to a problem? Please describe.**

Bash completion is a standard thing in any shell environment. Everybody depends on it. homebrew/Linuxbrew installs set this up automatically (except people have to configure their profile to make sure it's included).

However, we've never provided this explicitly for Windows... mostly because I didn't know if could work. But it works fine. There's just not a global technique to bring in the completions (that I know of). 

**Describe the solution you'd like**

* ddev generates a ddev_bash_completion.sh for each release. It's bundled with each tarball. 
* That can actually be placed anywhere, but probably the best place is /etc/bash_completion.d/ddev, (/etc/bash_completion.d may have to be created). (This assumes the use of git-bash)
* The user has to load it in their .profile or .bash_profile or wherever. `source /etc/bash_completion.d/ddev` - so we'd have to prompt them to do that. 

I think the installer could do this pretty easily. It's conceivable that the installer could go looking for the .profile or .bash_profile, but IMO it's best to prompt people to do this.

I think this would be a big step forward for ddev on Windows.

**Comment by rfay** [comment]
Note that the ddev release process now also adds completion scripts for PowerShell and Zsh, so there may be even more possiblities.

**Comment by luenemam** [comment]
I think git-for-windows has a default location for bash completion.

When I do a grep I see:
```
$ grep bash_completion.d /etc/ -R
/etc/profile.d/git-prompt.sh:   for c in "$HOME"/bash_completion.d/*.bash
```
So I placed a ddev.bash file there and it works...

I failed to find documentation for this...

**Comment by rfay** [comment]
So you put it in a directory named ~/bash_completion.d ? Interesting, thanks!

**Comment by rfay** [comment]
I did find that git-bash as a login shell would load ddev.bash from ~/bash_completion.d

In cmder I had to re-run `bash -l` - I haven't explored why that happens.

**Comment by rfay** [comment]
I think what we have is good enough, and we're likely to discontinue the installer anyway.
