### ISSUE TITLE
Windows Installer/Uninstaller should stop running processes (winnfsd service) before trying to manipulate nfsd

### ISSUE THREAD

**Issue by gilbertsoft** [ddev/ddev#1945]
**Is your feature request related to a problem? Please describe.**
Some processes may be running on starting the uninstaller as nssm or nfsd. The common problem is the service named "nfsd" which is running winnfsd.exe, and is installed by a script provided with ddev.

**Describe the solution you'd like**
The uninstaller should stop these processes/services before starting the removal of this files.

**Comment by rfay** [comment]
This is also a problem on upgrade. One option is just to skip installing winnfsd if it already exists (on install). 

From @David Menzel in slack

> Hi,
> I updated from 1.17.2 -> 1.17.7 via choco and nearly at the end this error pops up. There is no error in the shell as far as I can see.

![grafik](https://user-images.githubusercontent.com/112444/124659090-cef09780-de61-11eb-907c-9bec00931f86.png)
