### ISSUE TITLE
Add command 'export-files'

### ISSUE THREAD

**Issue by andy-blum** [ddev/ddev#2440]
**Is your feature request related to a problem? Please describe.**
When starting a new project, I do a fair amount of site building & file additions locally and would love a simple ddev-based way to export my files similar to how I can export my db

**Describe the solution you'd like**
I don't know if it's feasible or not, but something similar to `ddev export-files > ~/Desktop/files.tar.gz` would be great

**Comment by rfay** [comment]
`cd web/sites/default/files && tar -czf ~/Desktop/files.tar.gz .`

I guess it would be easy to make a custom command too.

**Comment by rfay** [comment]
A contribution would be welcome, but closing this for now.
