### ISSUE TITLE
Improve `ddev launch` to detect DISPLAY and use wslview if not set

### ISSUE THREAD

**Issue by rfay** [ddev/ddev#2623]
**Describe the bug**

On WSL2:

The `ddev launch` shell script uses xdg-open by default. But if $DISPLAY is set, it tries to access the browser via X11, which will hang if the X server is not running

**To Reproduce**

0. Windows WSL2
1. Don't run X410
2. DO set DISPLAY, for example `export DISPLAY=172.21.64.1:0.0`
3. `ddev launch` or just `xdg-open <URL>` - it will likely hang.

**Expected behavior**

`ddev launch` should open browser.

**Proposed Solution**

* Docs should require installing wslu *and* xdg-utils
* If on WSL2, and $DISPLAY is set, consider using wslview instead of xdg-open

**Version and configuration information (please complete the following information):**

- Host computer OS and Version: WIndows 10 WSL2, Ubuntu 20.04

**Additional context**
Add any other context about the problem here. Thanks!

**Comment by Morgy93** [comment]
Is this related to:

```
$ ddev launch -m
.ddev/commands/host/launch: line 61: xdg-open: command not found
Failed to run launch -m; error=exit status 127
```
?

I could swear this one worked fine some time ago.

By the way `$DISPLAY` is `:0` for me for whatever reason.

**Comment by rfay** [comment]
Just install xdg-utils and it will work.

**Comment by rfay** [comment]
With the maturing of WSL2 I don't think this is too relevant any more, as a separate X server is no longer required. Closing for now, happy to continue the conversation.
