### ISSUE TITLE
Priority of config.yml over global_config.yml

### ISSUE THREAD

**Issue by managume** [ddev/ddev#2630]
Right now if we define in `global_config.yml` the array `omit_containers=['dba']` the omission of the dba service applies to all projects. Even if I don't want to apply that rule to a particular project and I define `omit_containers=[]` in its `config.yml`.

It would be nice if in a project we defined something different, it would take priority over the global one, especially in this case.

**Comment by rfay** [comment]
Yes, it's additive. For now I'd suggest that if you want separate configuration for each project, don't put things like that in your global config.

**Comment by managume** [comment]
Well.. Now we have a different scenario with DDEV in a VPS where we want to omit `dba` by default in all projects, but with the possibility of enabling it in specific projects.

Ok @rfay, thanks as always for you effort :)

**Comment by rfay** [comment]
omit_containers[dba] is now obsolete everywhere.

Everywhere things are being worked on, overriding global with project is a priority. For example, `performance_mode` and `router_http_port` in v1.22.0 both allow global config and project override. C.losing.
