### ISSUE TITLE
Host shell commands (custom commands) should not auto-start a project

### ISSUE THREAD

**Issue by rfay** [ddev/ddev#2688]
**Describe the bug**

Custom shell commands currently start the project they're in if it's not already started. This makes sense for web commands, but not so much for host commands.

**To Reproduce**

With a project stopped, issue a command that is a host command. It will start the project.

**Expected behavior**

**Screenshots**

**Version and configuration information (please complete the following information):**

- Host computer OS and Version: [e.g. Windows 10, macOS Catalina]
- Docker Desktop version if on macOS or Windows (from "About Docker Desktop")
- ddev version information (use `ddev version`)
- config.yaml contents for the misbehaving project
- Do you have any custom configuration (nginx, php, mysql) in the .ddev folder? If so, have you tried without them?

**Additional context**
Add any other context about the problem here. Thanks!

**Comment by chellman** [comment]
You mentioned `ddev launch` is a host command, and it does make sense that it would start the project. So presumably the solution there is to have `ddev start` as part of the implementation thereof?  Basically any host command that should start the project, should have `ddev start` in it?

**Comment by rfay** [comment]
No, `ddev list` doesn't, `ddev stop` doesn't. `ddev config` doesn't. Any script-based command (custom command) will trigger start if it the project is not running. It does not do so if the project is already running. 

It's just a feature of script-based commands that they do the `ddev start` - it's not that they trigger the pre-start hook. It's that they do a *start* and that triggers the pre-start hook.

**Comment by dkd-kaehm** [comment]
> No, `ddev list` doesn't, `ddev stop` doesn't. `ddev config` doesn't. Any script-based command (custom command) will trigger start if it the project is not running. It does not do so if the project is already running.
> 
> It's just a feature of script-based commands that they do the `ddev start` - it's not that they trigger the pre-start hook. It's that they do a _start_ and that triggers the pre-start hook.

I mean each custom command triggering start/pre-start hook, even ddev is up and running!

**Comment by PeterSchuhmannNetflow** [comment]
any news on that topic? I am also very interested in a solution. i want to use to generate ddev config upfront before starting the project and do some validation.
