### ISSUE TITLE
Add `ddev config global --check-latest-ddev` to let user know when a new ddev version is released

### ISSUE THREAD

**Issue by shaal** [ddev/ddev#2753]
**Is your feature request related to a problem? Please describe.**
There's a new stable release of ddev version, and I missed it.

**Describe the solution you'd like**
Add `ddev config global --check-latest-ddev` to let user know when a new ddev version is released.

**Comment by rfay** [comment]
DDEV-Local already checks once a week and pesters, https://github.com/drud/ddev/blob/24b45750f7c9dfa1b9be9ea3b84eb3248a07ce49/cmd/ddev/cmd/root.go#L23. 

I wonder if somehow that isn't working for people. It checks for current stable release. 

It wouldn't be hard to make it pester more often (or less often) but I'm surprised that you find this need if it's working right.

You can test this by setting the modified time on ~/.ddev/.update: `touch -a -m -t 202012180130.09 ~/.ddev/.update` for example. Then issue a ddev command. It will get updated to current time, showing that the check happened. If you aren't current, it will pester you.

**Comment by rfay** [comment]
Looking at the code, the pester only happens on `ddev start` and `ddev restart`

https://github.com/drud/ddev/blob/37826a483b91faa90d347c68d02fe60f632841d5/cmd/ddev/cmd/root.go#L37-L98

**Comment by rfay** [comment]
I'd be interested to know if the regular pester has been inadequate for people, if an extra command is needed. Closing this for now. 

Note that DDEV v1.22.4 just introduced `ddev_version_constraint` which is another way to look at this problem.

Closing this for now, happy to continue the conversation here or elsewhere, and happy to reopen if people think it's important.
