### ISSUE TITLE
FR: Global timezone configuration (with per-project override)

### ISSUE THREAD

**Issue by tyler36** [ddev/ddev#3109]
# Is your feature request related to a problem? Please describe
I recently discovered the `timezone` setting while browsing though the config file. I develop apps for and in Japan which has a single timezone.  It therefore makes sense to me to have this configured to 'Asia/Tokyo'. However, I have to remember to do this  and it seems like it should be a `default` somewhere.  

# Describe the solution you'd like
It would be nice to set a default in the `global_config.yaml` which is then used for all new `ddev config`.

**Comment by rfay** [comment]
This isn't very hard to do, and there have been many recent PRs adding global config that was previously project-only. Hoping for a contribution!

**Comment by tyler36** [comment]
Closing. Deferring to #6458 

#6458 , while not the same request, has the same desired results; projects get my preferred timezone instead of manually setting. 

In my case, I would set projects to `Asia/Tokyo` (my local/system time). 
#6468 automatically sets the time to my system (local) time. 

IIRC, there was movement to sync all project settings to global settings, which include this original request. Unable to find that issue now though.
