### ISSUE TITLE
Implement Amazee.io lagoon provider integration

### ISSUE THREAD

**Issue by rfay** [ddev/ddev#3188]
Thanks to Amazee.io we now have an account to use to implement and test amazee.io lagoon integration.

**Comment by rfay** [comment]
Unfortunately this account no longer seems to be valid, so we'll need to get a new one.

**Comment by tobybellwood** [comment]
I can reorganise that!

**Comment by rfay** [comment]
Or if you prefer to reactivate the previous one, `randy[@]randyfay.com`

**Comment by rfay** [comment]
We have the go-ahead on this, and an invoice issued and agreed to be paid to support it, thanks Amazee!

- [ ] Include the [lagoon-sync](https://github.com/uselagoon/lagoon-sync) tool in ddev-webserver
- [ ]  Implement database pull
- [ ] Implement files pull
- [ ] Implement database push
- [ ] Implement files push
- [ ] Create testing environments
- [ ] Add test coverage that uses the live testing environments
