### ISSUE TITLE
Add global router_http(s)_port setting (can be overridden by project)

### ISSUE THREAD

**Issue by gilbertsoft** [ddev/ddev#3240]
**Is your feature request related to a problem? Please describe.**
Imho it absolutely would make sense to change the router ports on the machine instead of the project. It looks like this is missing currently see https://ddev.readthedocs.io/en/stable/users/extend/config_yaml/#global_configyaml-options, maybe just the docs leaking here.

**Describe the solution you'd like**
Add the options router_http(s)_port to the global configuration and apply it to every project which is started.

**Describe alternatives you've considered**
Using the project's configuration which already works.

**Additional context**

**Comment by rfay** [comment]
The reality is that this should be *only* global... but it predated global config.

**Comment by hanoii** [comment]
I am also very interested in this.

**Comment by miromichalicka** [comment]
I'm working on this one.

**Comment by rfay** [comment]
Hoping to target this for v1.22.0, coming soon @miromichalicka , hope you're doing better!

**Comment by rfay** [comment]
Yippee!
