### ISSUE TITLE
Add `ddev get --installed` to show what's installed as add-ons

### ISSUE THREAD

**Issue by rpkoller** [ddev/ddev#3555]
**Is your feature request related to a problem? Please describe.**

Currently you dont have an option to see which services are installed for a project. 

**Describe the solution you'd like**

add a list option to `ddev service` -> `ddev service list` so the user has a way to see which services are a) installed b) enabled/disabled and c) it would provide the opportunity to see which version of the service is installed ( and an option to display the version of the formula upstream - that way the user would be enabled to easily check if there is a new version of the formula and in case there is manually check if it is desirable and safe to upgrade).

**Comment by rfay** [comment]
So the services installed for a project are listed in `ddev describe`, This is something else?

**Comment by rpkoller** [comment]
`ddev describe` describes the whole project with ddev containers as well as all containers of the additional services installed. it already contains much informational weight and provides all available necessary information to interact with those containers. 

my first thought was also to put those informations into `ddev describe` but on second thought it would a separation of concern and `ddev service list` would be one consistent with the pattern `ddev get list` and on the other hand enable the governance and management which formulas are installed/enabled/disabled and also would provide version information. therefor i thought it might be the better decision to create that list option for the service command?

**Comment by rfay** [comment]
Right now there's no difference between a service installed with `ddev get` and one installed manually. I don't actually see there ever being a difference, but maybe some distant day there would be a way.

Also note that `ddev get` can get providers, custom commands, global custom commands, etc.

**Comment by rpkoller** [comment]
hmmmm okay. semantically i have different expectations with `get` than with `service` . the former is about something remote i try to pull in while `service` is something local . and `ddev service` with the current option of `enable` and `disable` sounded like the right fit for the `list` functionality to have an overview about the current state of a project in regards of services pulled in by `ddev get` ( and would also leave the option to display services manually added to the project locally as well).

**Comment by rfay** [comment]
Upcoming PR will put this functionality in `ddev get --installed`
