### ISSUE TITLE
Tidy up order of "Project Type"  and mariadb version suggestions

### ISSUE THREAD

**Issue by tyler36** [ddev/ddev#3561]
Recently, I spun a new project and noticed the following long line:

```shell
Project Type [backdrop, drupal10, drupal6, drupal7, drupal8, drupal9, laravel, magento, magento2, php, shopware6, typo3, wordpress] (laravel): 
```

2 things came to mind:
- "drupal10" should appear after "drupal9"
It reads better.  Is there another sort option that will do this?

- do we need to include "drupal6, drupal7"?
Since these project types are EOL, it don't think we need to _display_ them here. Yes, keep support in DDEV and the documentation; I think the line is too long and removing these will shorten it.

```shell
$ ddev --version
ddev version v1.19.0-alpha3
``

**Comment by rfay** [comment]
Thanks for the good eye and the suggestion. Currently it's sorted alpha, as you see, and I don't think there's any kind of sort that could do what you want. But there could be a manual sorting I guess.

**Comment by rfay** [comment]
And yes, people need old versions all the time. They do upgrades, they revive them, etc.

**Comment by tyler36** [comment]
I'm not familiar with go but you need a "natural sort" method like:

https://github.com/facette/natsort
https://github.com/skarademir/naturalsort

**Comment by tyler36** [comment]
Just noticed in `ddev version v1.19.0-alpha4` , database error messages (postgres:10 ... postgres:9)

```shell
Incorrect database value: postgres - use something like 'mariadb:10.3 or mysql:8.0. Options are [mariadb:10.0 mariadb:10.1 mariadb:10.2 mariadb:10.3 mariadb:10.4 mariadb:10.5 mariadb:10.6 mariadb:5.5 mysql:5.5 mysql:5.6 mysql:5.7 mysql:8.0 postgres:10 postgres:11 postgres:12 postgres:13 postgres:14 postgres:9]
```

**Comment by rfay** [comment]
This is also true of the mariadb versions:
`Options are [mariadb:10.1 mariadb:10.11 mariadb:10.2 mariadb:10.3 mariadb:10.4 mariadb:10.5 mariadb:10.6 mariadb:10.7 mariadb:10.8 mysql:5.7 mysql:8.0 postgres:10 postgres:11 postgres:12 postgres:13 postgres:14 postgres:15 postgres:9]`

Both the mariadb versions (10.11 immediately after 10.1) and postgresql versions (9 at the end) are messy.

**Comment by tyler36** [comment]
Also checked the supported databases.

## Test

```
$ ddev config --database mariadb:50
...
failed to validate config: the laravel project has an unsupported database type/version: 'mariadb:50', DDEV amd64 only supports the following database types and versions: mariadb: [5.5 10.0 10.1 10.2 10.3 10.4 10.5 10.6 10.7 10.8 10.11], mysql: [5.5 5.6 5.7 8.0], postgres: [9 10 11 12 13 14 15 16]
```
