### ISSUE TITLE
Changing the project name on `ddev config` leaves the old name and `approot` in the `global_config.yml` `project_info` list

### ISSUE THREAD

**Issue by rpkoller** [ddev/ddev#3665]
## Describe the bug
if you run `ddev config` in the same directory more than once and change the project name at one point there will be another project entry in global_config.yml. over time the "skeletons in the closet" might pile up if that for what ever reason happens more often.

## To Reproduce
- go to `~/Sites` or wherever your projects are stored
- `mkdir test`
- `ddev config`
- enter project name wordpress, leave docroot empty and select wordpress as project type
- execute `ddev config` again, enter project name `drupal9`, enter `web` as docroot and select `drupal9` as project type
- `pico ~/.ddev/global_config.yml` you'll notice one project `wordpress` and one project `drupal9` both with the same `approot`
- `ddev list` you will only find `drupal9` in the list of available projects the `wordpress` one isnt listed. 

## Expected behavior
there shouldnt be more than one project with the same `approot` in the `project_info` list in `~/.ddev/global_config,yml`. so instead of adding a new entry to the `project_info`list the name of the existing one with that `approot` should be updated instead. 

## Version and configuration information (please complete the following information)

- Host computer OS and Version: MacOS 10.13.6
- Docker Desktop version if on macOS or Windows (from "About Docker Desktop") 2.4.0.0
- ddev version information (use `ddev version`) 1.19.0-rc1

**Comment by stasadev** [comment]
This was fixed in:

- #6208
