### ISSUE TITLE
Improve `ddev debug test`

### ISSUE THREAD

**Issue by rpkoller** [ddev/ddev#3679]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Multiple requests:

Add these things to test_ddev.sh:

- [ ]  Show whether mutagen.yml has been changed (Is that possible?) (Can we show some info about the existing project?)
- [x]  Should show what dir it’s executing and then trying to create in.
- [x]  Add cleanup option
- [x]  Less output showing mutagen - maybe just the one project we’re interested in?
- [x]  Add a little wait before outside curl to let traefik catch up. Maybe a while loop?
- [x] Give an automatic way to post to a gist or capture the output
- [x] Add `colima status` and `colima --version` if they're using colima
- [x] Doesn't work when global  `router_http_port` is set to nonstandard (tries port 80)
- [x] Output the filename both to the script (top) and at bottom, and in browser.
- [x] Check to make sure name resolution of ddev.site works
- [x] Check https/cert
- [ ] See if we can limit exposure of project names or other security-sensitive items

When `ddev debug test` is run (tested with 1.9.0-rc1) you currently get at the end of the test the following recommendation in the browser: 
```
ddev is working. You will want to delete this project with "ddev delete -Oy tryddevproject-13959"
```
by applying that line the test project is removed from ddev and its docker assets are removed again. but noticed today that the test creates some artifacts in the user folder. a tmp folder is created (~/tmp) and for each test run a new directory with a index.php is created. it looks like that at the moment
![Bildschirmfoto 2022-03-08 um 01 38 26](https://user-images.githubusercontent.com/1665422/157142515-d94929d6-c3ac-4941-916a-463969473c91.png)
the clutter might increase over time if the tmp folder is unnoticed by the user. 

### Describe the solution you'd like

the easiest fix would be a note along: 

```
ddev is working. You will want to delete this project with "ddev delete -Oy tryddevproject-13959"
```
that there is a temp folder in the user folder being created containing test assets. just inform the user about the folder.  the cleaner and more convenient variant might be in case of those test files on `ddev delete` also to remove them?

**Comment by rfay** [comment]
It would be nice to have an auto-cleanup like `ddev debug test cleanup`
