### ISSUE TITLE
Provide the ability to update and manage add-ons

### ISSUE THREAD

**Issue by rpkoller** [ddev/ddev#3696]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

After the download of an add-on with `ddev get` there is currently no way to check within ddev that an update with fixes, improvements including even a new required version of the image is available. at the moment you manually have to visit https://github.com/drud/ddev-contrib to check if there are any updates. 
additionally you are currently able to install the same version several times within minutes. the user is able to perform `ddev get drud/ddev-drupal9-solr` three times in a row or more often without an indication that the add-on is already installed with the identical version. 
there is also no indication for `ddev get --list` which add-ons are already downloaded (enabled/disabled for a project) nor which version ( i suppose an explicit version number for  an add-on doesnt exist yet). 
 

### Describe the solution you'd like

- when `ddev get --list`or ddev get --list --all` is run it would be helpful if on one hand it is shown if one of the listed add-ons is already installed. 
- for the installed versions the add-version number could be shown as well as the version available upstream -> if a newer version is available ask if the add-on should be updated. for not yet installed add-ons only the upstream version number could be shown. 
- if for example  `ddev get drud/ddev-redis` is executed and redis is already downloaded then ddev should note that the requested version is already downloaded for the current project. and in case a newer version is there then suggested an update. 
- aside in the context of `ddev get` ddev might also check on `ddev start` once if any of the enabled or disabled add-ons of the project have an update available. 
- that way there wouldn't be any need for a dedicated update command like `ddev service update` necessarily

**Comment by rfay** [comment]
Long-term hopes:

* ddev would say if a change were going to be made to an existing file
* ddev would say if a named service is already there. (This would require an enhanced versioning strategy, since currently all ddev knows is that it has some files)
* ddev should probably track the release version of a downloaded add-on
*

**Comment by rfay** [comment]
With #3898 files created by `ddev get` are marked with #ddev-generated, so that's a step forward. So if people modify the files and remove the marker, they won't be overwritten by a future invocation of `ddev get`.

Related:
* 3919

**Comment by rfay** [comment]
Another way to mature these things would be versioning of the add-ons.

**Comment by rfay** [comment]
`ddev get --version` should do the job for this request. 
`ddev get --installed` shows current status

I think this is probably good, but would love to have your feedback on this on HEAD @rpkoller

**Comment by stasadev** [comment]
Follow-up issue:

- #4979
