### ISSUE TITLE
Linux/Github build of DB images can leave Charset of mariadb/mysql images as latin1 instead of utf8mb4

### ISSUE THREAD

**Issue by josefglatz** [ddev/ddev#3748]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

MariaDB [db]> SELECT @@character_set_database, @@collation_database;
+--------------------------+----------------------+
| @@character_set_database | @@collation_database |
+--------------------------+----------------------+
| latin1                   | latin1_swedish_ci    |
+--------------------------+----------------------+

### Expected Behavior

MariaDB [db]> SELECT @@character_set_database, @@collation_database;
+--------------------------+----------------------+
| @@character_set_database | @@collation_database |
+--------------------------+----------------------+
| utf8mb4                  | utf8mb4_general_ci   |
+--------------------------+----------------------+

### Steps To Reproduce

DDEV 1.18: utf8mb4 charset
DDEV 1.19: latin1 charset

**Comment by rfay** [comment]
Thanks!

**Comment by jonaseberle** [comment]
I can't confirm.

I have 
```
MariaDB [db]> SELECT @@character_set_database, @@collation_database;
+--------------------------+----------------------+
| @@character_set_database | @@collation_database |
+--------------------------+----------------------+
| utf8mb4                  | utf8mb4_general_ci   |
+--------------------------+----------------------+
```
on `v1.19.1-1-gb28856aa` (so basically a v1.19.1)

**Comment by tyler36** [comment]
I _can_ confirm

## TEST

### Win10

```
$ ddev -v
ddev version v1.19.1
```

- Start new project and accept all defaults

```shell
mkdir mariadb
cd mariadb
ddev config
```

- Connect to MariaDB CLI

```
$ ddev mysql

Server version: 10.3.34-MariaDB-1:10.3.34+maria~focal-log mariadb.org binary distribution
...
MariaDB [db]> SELECT @@character_set_database, @@collation_database;
+--------------------------+----------------------+
| @@character_set_database | @@collation_database |
+--------------------------+----------------------+
| latin1                   | latin1_swedish_ci    |
+--------------------------+----------------------+
1 row in set (0.000 sec)
```

### WSL

```
$ ddev -v
ddev version v1.19.1
```

- Start new project and accept all defaults

```shell
mkdir mariadb
cd mariadb
ddev config
```

- Connect to MariaDB CLI

```
$ ddev mysql

Server version: 10.3.34-MariaDB-1:10.3.34+maria~focal-log mariadb.org binary distribution
...

MariaDB [db]> SELECT @@character_set_database, @@collation_database;
+--------------------------+----------------------+
| @@character_set_database | @@collation_database |
+--------------------------+----------------------+
| latin1                   | latin1_swedish_ci    |
+--------------------------+----------------------+
1 row in set (0.000 sec)
```

**Comment by jonaseberle** [comment]
I tested with 
```
database:
  type: mariadb
  version: "10.5"
```
and that is correctly `utf8mb4` / `utf8mb4_general_ci`

I see mariadb 10.3 (our default) and 10.4 affected. I haven't tested others.

**Comment by rfay** [comment]
The regression seems to have happened in cd2edafc5f6821ea11acb32891c3e96bb7aeb55e

**Comment by rfay** [comment]
It's only the mariadb:10.3 database that is affected here, and the reason has to be that the prebuild is broken. DDEV builds a default empty database to begin with so that the initial startup is super fast and a db doesn't have to be created... but somehow this one is not being created with the correct charset.

**Comment by rfay** [comment]
`ddev mysql -e "DROP DATABASE db; CREATE DATABASE db;"`

fixes this.

**Comment by rfay** [comment]
I think that probably this happened when doing the gzipped snapshots and we're not looking for the correct prebuilt gzipped snapshot on startup, so it just doesn't use one.

**Comment by rfay** [comment]
The problem is here: https://github.com/drud/ddev/blob/04b054319849e57d4ceb297e12c3be24dbf32f59/containers/ddev-dbserver/files/docker-entrypoint.sh#L81-L103

The `db_mariadb_version.txt` file is no longer used with gzipped snapshots, so this stanza doesn't get executed.

**Comment by rfay** [comment]
AFAICT this was just a build problem, affecting only the 10.3 image. Not sure how that can happen, but I added a test for it. 

* #3753

**Comment by rfay** [comment]
I'm seeing this in all mariadb/mysql databases after building new images for v1.19.4 in 
* https://github.com/drud/ddev/pull/4010

I can't see any relevant changes between v1.19.3 and v1.19.4, and inspection of the my.cnf seems to indicate things are fine.

But the base problem is the creation of the base database I think, not the behavior after the container is up.

**Comment by rfay** [comment]
For the v1.19.4 mariadb/mysql images, when I created them using either of the github workflows, they came out with the wrong default charset. When I pushed all from my arm64 mac, they were all functional. So is it doing it on linux? Doing it on amd64 linux?

- [ ] We need a test in the container build/test section that looks for this problem as well, perhaps that will help sort it.

**Comment by tyler36** [comment]
#4012 (Bump default php to 8.0, MariaDB to 10.4, add Maria 10.8) via gitpod shows `utf8mb4_general_ci` encoding.

```shell
gitpod /workspace/d9simple (main) $ ddev -v
ddev version 2fa59af3

gitpod /workspace/d9simple (main) $ ddev mysql
...
Server version: 10.3.35-MariaDB-1:10.3.35+maria~focal-log mariadb.org binary distribution
...
MariaDB [db]> SELECT @@character_set_database, @@collation_database;
+--------------------------+----------------------+
| @@character_set_database | @@collation_database |
+--------------------------+----------------------+
| utf8mb4                  | utf8mb4_general_ci   |
```

**Comment by rfay** [comment]
I think this means you're happy @tyler36 - but the reason this is open is that some image build techniques leave the default broken.

**Comment by rfay** [comment]
Updated title.

**Comment by rfay** [comment]
I think the basic way to start exploring this is just to 
- [ ] do a build on linux and see if this happens
- [ ] Do a build using github actions and see if it happens every time.

**Comment by rfay** [comment]
This problem remains; I tried using the github push of the ddev-dbserver containers for v1.21.2 (#4261 ) and got the same failures in https://github.com/drud/ddev/actions/runs/3192616865/jobs/5210297578

**Comment by rfay** [comment]
I tried to see if this is still a problem in https://github.com/ddev/ddev/pull/4934 and sure enough, it still is, tests failed with same error.
