### ISSUE TITLE
Create custom message/poll on ddev execution  - similar to the new version warning - for use on user feedback

### ISSUE THREAD

**Issue by jcnventura** [ddev/ddev#3799]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

We currently have very limited means to get feedback from the user base. We want to have a way to engage a lot more people, specifically the end-users, and not only the team leaders.

### Describe the solution you'd like

Similar to how we are warning users that there's a new version of ddev available, we should be able to have a mechanism to inject a custom message announcing something like:

"Please help improve DDEV, click on the following link to provide simple feedback on feature X: http://example.com/quiz"

### Describe alternatives you've considered

We can continue with Discord and Twitter, but that only reaches those that actually care enough about DDEV to sign in to Discord or to follow DDEV in Twitter.

**Comment by rfay** [comment]
Congratulations!
