### ISSUE TITLE
`ddev get` should have a removal technique and versioning

### ISSUE THREAD

**Issue by tyler36** [ddev/ddev#3919]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

DDEV makes it really easy to install an addon.
How do I remove an addon though?

### Describe the solution you'd like

I want to do something like:

```shell
ddev get drud/ddev-redis -d
ddev get drud/ddev-redis --delete
```

This would read the install.yaml and _remove_ the files; well, the ones that have  `#ddev-generated`.

This would make it easy to test in existing projects or "clean up" un-wanted addons.

### Additional context

EG. 
I recently tried to remove redis from a project.
But there are several files scattered across directories
- docker-compose.redis.yaml
- redis/scripts/settings.ddev.redis.php
- redis/scripts/setup-drupal-settings.sh
- redis/redis.conf
- commands/redis/redis-cli

Newer users would be unaware of the structure or even where to look.

**Comment by rfay** [comment]
Great thinking.

Earlier issue: https://github.com/drud/ddev/issues/3696

Files added directly could be removed using the list (if #ddev-generated was still in the file). This would possibly require keeping the install.yaml around.

**Comment by tyler36** [comment]
Thinking out loud here:

Eg. 
Installing ddev-redis:  ddev get drud/ddev-redis
- move `install.yaml` => `.ddev/addons/ddev-redis.yaml`

Uninstall: ddev remove drud/ddev-redis
- check for `.ddev/addons/ddev-redis.yaml`
- foreach file under project_files, delete if it contains #ddev-generated
- delete `.ddev/addons/ddev-redis.yaml`

If we kept the install.yaml, we could also
- `ddev get --installed` to list currently

**Comment by rfay** [comment]
It's good thinking. I was thinking we'd have to have a list of things done to undo the things.... An approach like this could work.

**Comment by proimage** [comment]
Aside from deleting the files listed in the OP, is there anything else needed to remove Redis (specifically, in this case) from a project?

**Comment by rfay** [comment]
@proimage that's basically it, but you'll likely want to remove the stanza it added to the settings.php (that includes settings.ddev.redis.php) in this case. Although if you don't remove the stanza, but do remove the file, it won't cause any trouble, because the file's not there so it doesn't get included.

**Comment by proimage** [comment]
Err, where's settings.php? 🥴

**Comment by rfay** [comment]
It only matters if it's a Drupal site. On a drupal site it would be in `<docroot>/sites/default/settings.php`.

**Comment by proimage** [comment]
Drupal? Why would it be a Drupal site? Oh, wait, lemme guess... DDEV = Drupal Dev?

**Comment by rfay** [comment]
No, DDEV is probably "docker dev", but name is lost in history.

But the contributor who created drud/ddev-redis added special handling for Drupal projects, so the configuration would be done automatically. Obviously they were working with Drupal mostly. But people use this plenty on all the many CMSs DDEV supports explicitly (and lots that it doesn't). Since you obviously aren't working with Drupal... you didn't ever have to have this conversation, because drud/ddev-redis didn't create the files in the first place.

**Comment by tyler36** [comment]
> Aside from deleting the files listed in the OP, is there anything else needed to remove Redis (specifically, in this case) from a project?

Maybe a 2 prong approach is good
- Remove all files listed in `install.yaml` under `project_files`
- And check if `install.yaml` contains a `post_delete_actions` section; if so, execute it

This way, uninstall processes could be handled by the each addon. And it would not break existing addons that haven't implement the feature yet.

**Comment by bserem** [comment]
Thinking out loud here: a verbose message with extra uninstallation actions would be good, at least for addons that have extras (like redis)

**Comment by rfay** [comment]
This is something we can already do, just add info like that to the README and an `echo` in the install.yaml. Thanks for pointing that out.

**Comment by lolautruche** [comment]
Relates to #3696

**Comment by ultimike** [comment]
I think adding some way to un-get/remove add-ons is a great idea.

-mike
