### ISSUE TITLE
Initiative: Share secrets and recovery procedures with trusted community members

### ISSUE THREAD

**Issue by rfay** [ddev/ddev#3962]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Currently @rfay has mostly all the keys to the kingdom for testing, external access, GitHub, etc, and is also the only one who knows how to use the keys. This was discussed at length in [2022-07-06 Advisory Group Meeting](https://github.com/drud/ddev/discussions/3800)

### Describe the solution you'd like

We can do at least some battling out of this with:

1. An emergency plan in general that would explain how access and secrets could be recovered if @rfay weren't available.
2. A clear list of actors with privileges like @fabpot (who is also owner of the GitHub repo).
3. Sharing important secrets with trusted community members, along with information about what their meaning and use is.

To be continued...

**Comment by rfay** [comment]
I made @gilbertsoft an owner of the GitHub drud org along with @fabpot, so both of those folks have full privs on all repos in that org.

**Comment by rfay** [comment]
Here's what I think I'll do for starters:

- [ ] Create a private repo and add access to it for some trusted folks. The private repo will be for 
    - [ ] sensitive procedures and people's names (not secrets)
    - [ ] Emergency plan if Randy weren't available
- [ ] Link from [developer docs](https://ddev.readthedocs.io/en/latest/developers/) to the private repo, with suggestions about who has access. 
- [ ] In lastpass, create a set of secrets that are necessary for keeping things running
- [ ] Share those secrets with folks who volunteered for the role in https://github.com/drud/ddev/discussions/3800

**Comment by andy-blum** [comment]
Github accounts have a "successor" setting so that in the event of a github user's death, the account can be taken over by a designated successor

<img width="493" alt="Screen Shot 2022-09-07 at 11 38 57 AM" src="https://user-images.githubusercontent.com/25532785/188920483-7ef8cc47-9a65-46b0-af38-cdab11d9c7bb.png">

**Comment by rfay** [comment]
Great idea, I nominated @gilbertsoft as successor. 

However, I don't think it does exactly what we'd hope. It gives all of the rfay user's content, but not privileges. Anyway, if it's useful it's done. 

Docs: https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-access-to-your-personal-repositories/maintaining-ownership-continuity-of-your-personal-accounts-repositories

**Comment by rfay** [comment]
Added @gilbertsoft to Chocolatey.org and Apple developer account.

**Comment by rfay** [comment]
Applied for an open-source team license for 1Password, where some secrets can be shared.

**Comment by rfay** [comment]
We now have open-source license for 1Password. They recommend a recovery plan:
https://support.1password.com/team-recovery-plan/

**Comment by rfay** [comment]
As a result of the CircleCI breach, I had to rework nearly every secret yesterday, 
* https://github.com/drud/ddev/pull/4525

So in the process I tried to put secrets into our new 1Password account, and @gilbertsoft has access to them.

**Comment by rfay** [comment]
Added @gilbertsoft and @mattstein to the 1password account.

**Comment by rfay** [comment]
@mattstein is a trusted maintainer and also has lots of experience with 1password, so made him an owner, which means we now have a recovery plan. https://github.com/drud/ddev/issues/3962#issuecomment-1371326677

**Comment by rfay** [comment]
Added @gilbertsoft ('gilbertsoft') and @mattstein ('mattstein') to both the 'ddev' and 'drud' orgs on hub.docker.com

**Comment by rfay** [comment]
I think this is completed. Both @gilbertsoft and @mattstein have all access, and @gilbertsoft has used most of his access.
