### ISSUE TITLE
[output] Make the output on the first start more streamlined in the root.go 

### ISSUE THREAD

**Issue by rpkoller** [ddev/ddev#4181]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

At the moment the output after the installation of a new version of DDEV is the following `/cmd/ddev/cmd/root.go`
```
Congratulations, you seem to have a new DDEV version.
Please note that the global ~/.mutagen folder is no longer used by DDEV so you can delete it if it's no longer used by other applications.
It looks like you have a new DDEV version. During an upgrade it's important to `ddev poweroff`. May I do `ddev poweroff` before continuing? This does no harm and loses no data.
```
Problem is for one that you have "congratulations you have a new version of DDEV" in the first sentence and in the third sentence you have more or less the same again. the second sentence could be removed imho. 
the second sentence could be broken up into two. the first part should be a plain explanatory statement that `~/.mutagen` isn't used by DDEV any longer. the second part is changed into a clear actionable item in case the folder isn't used by any other application. 

### Describe the solution you'd like

I would suggest the following draft: 
```
Congratulations, you seem to have a new DDEV version.
Please note that the global ~/.mutagen folder is no longer used by DDEV. Delete the folder if it is no longer used by any other application.
During an upgrade DDEV has to be shut down. May I do `ddev poweroff` to be on the safe side before continuing? This causes no harm or data loss.
```
I'll try to open up a pull request later today to test the fork/branch process via the terminal.

**Comment by rfay** [comment]
If you're still interested in this, a new PR is welcome. Otherwise, let's close it about 1 August 2023.

**Comment by rfay** [comment]
Closing, almost a year late :)
