### ISSUE TITLE
Single upload_dir is too limiting, doesn't work for lots of CMSs, make it upload_dirs

### ISSUE THREAD

**Issue by ursbraem** [ddev/ddev#4190]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

It is recommended to exclude the assets directory from mutagen and replace it with a docker bind-mount via `upload_dir`. Alas, this allows only one directory, but quite a few sites have multiple asset directories / file storages. 

Also, the current upload_dir must be in a subdirectory of the docroot; it should not be constrained like that. For example, Drupal's private files should be outside the docroot.

### Describe your solution

Add a new parameter 

```
# upload_dirs list with paths relative to project root
upload_dirs:
- this
- that
- those
```

and deprecate `upload_dir`

### Describe alternatives

I've tried the manual method, but fear it's not cross-platform (I had to hardwire paths from my system for it to work, and I don't know what happens if you're on linux and don't use mutagen). 

Also, it's a quite complex and ddev can't manage `mutagen.yml` anymore by itself.

### Additional context

https://discord.com/channels/664580571770388500/1014794399009476658

**Comment by rfay** [comment]
This is a good idea, and would solve the private_files problem for drupal, and the multiple upload_dir problem of craft cms as well, and I think TYPO3 for some setups. 

It would require adding a flag and logic to `ddev import-files` to specify where you're importing to, and also the logic to completely change a config value.

**Comment by mikesnoeren** [comment]
Are there any plans to add this feature in the future? Would be really convenient for a lot of folks.

**Comment by johndwells** [comment]
I've stumbled upon this ticket while researching switching from Mac Docker For Desktop to Colima, which recommends Mutagen support. I work with Craft CMS, and @rfay as you rightly said, Craft can be configured with multiple local user-generated directories. So it would indeed be great to be able to configure multiple upload directories to run Mutagen & Colima optimally.

**Comment by riconeitzel** [comment]
I noticed that it's only possible to create this inside docroot. For many applications it makes sense to have that outside of docroot. Should I create a separate ticket for it?

**Comment by rfay** [comment]
@riconeitzel Your comment here is adequate, I'll add to the OP as well.

**Comment by gilbertsoft** [comment]
> I noticed that it's only possible to create this inside docroot. For many applications it makes sense to have that outside of docroot. Should I create a separate ticket for it?

@riconeitzel you should already be able to configure a upload dir outside the docroot like this `ddev config --upload-dir=../myfiles`

I did not test it so far but will add a test to be sure it works while adding multi upload dir support.

**Comment by rfay** [comment]
It's definitely critical to be able to do an upload_dir outside the docroot BUT still in the project root. Drupal's private_files, for example, would almost always be a directory above the docroot, or in the project root itself if that's not the same place.

**Comment by rfay** [comment]
We'd appreciate it if all of you in this issue could test https://github.com/ddev/ddev/pull/5005#issuecomment-1600423316 and see how it does for your use-case. @ursbraem @mikesnoeren @riconeitzel @johndwells @mikehayesuk

**Comment by riconeitzel** [comment]
Creating the directories worked just fine here.
