### ISSUE TITLE
Implement mutagen fanotify feature with sidecar container

### ISSUE THREAD

**Issue by rfay** [ddev/ddev#4211]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

mutagen v0.14 implemented fanotify support, https://github.com/mutagen-io/mutagen/releases/tag/v0.14.0

This should make scanning even faster.

### Describe your solution

Implement the sidecar approach as described in the release

**Comment by jkabat** [comment]
How about docker-desktop mutagen extension - https://mutagen.io/documentation/docker-desktop-extension
Would it be possible?

**Comment by rfay** [comment]
I've tested the mutagen extension with DDEV and it's fine. Of course it uses more disk space. If you used that you would turn off DDEV's mutagen feature and use the docker desktop extension. I don't think it's likely to add value for you. And it's unrelated to the topic of this issue.

**Comment by rfay** [comment]
I don't expect to do this.
