### ISSUE TITLE
ddev-get: When installing directory, only check #ddev-generated in files that exist in the add-on

### ISSUE THREAD

**Issue by hanoii** [ddev/ddev#4253]
The best way to explain this is this commit/project:

https://github.com/hanoii/ddev-z/commit/4dba742c56e00ced4629fdd0d083a6723d575828

I have this add-on where I specified `homeaddtions/` on `project_files`. It worked just fine until I had a project where I had other unrelated stuff in `homeaddtions/` and `ddev get hanoii/ddev-z` was **NOT** installing the file because there was another file on the directory:

```
NOT overwriting file/directory /Users/ariel/Sites/..../.ddev/homeadditions. 
The #ddev-generated signature was not found  in the file, so it will not be overwritten. 
You can just remove the file and use ddev get again if you 
want it to be replaced: signature was not found in file 
/Users/ariel/Sites/..../.ddev/homeadditions/.bashrc.d/path.sh 
```

On the above, `path.sh` is something specific to the ddev project and not present in the above. 

### Expected Behavior

I would expect that when one specifies a directory on `project_files`, only the files present on the whole tree are checked for the `#ddev-generated` signature and not any other potential files in there.

**Comment by rfay** [comment]
The key to this is to list the path of the *file* in the install section, not the directory. And of course, put #ddev-generated in it. For me, that approach has been adequate.

**Comment by hanoii** [comment]
Right, from https://github.com/drud/ddev-addon-template/blob/11d1e60088fc7df1661003a56fe78c143f188041/install.yaml#L48-L55 I got the impression directories were supported (and they kind of are) I jus think if one decide to use a directory, the checking for the signature should be constrained to all of the files in the directory (recursively) of the addon, and not any other.

I'll sure be using files for now.

**Comment by rfay** [comment]
Can you see a straightforward fix for this? It would certainly be easier to be able to specify a directory. But remembering the `#ddev-generated` is still definitely a gotcha. 
I guess we'd have to walk the directory in the add-on getting a list of files, then check those files on installation.

**Comment by hanoii** [comment]
> I guess we'd have to walk the directory in the add-on getting a list of files, then check those files on installation.

This is likely the best solution.
