### ISSUE TITLE
Add a `--help-create-project` flag to `ddev composer create` subcommand

### ISSUE THREAD

**Issue by hanoii** [ddev/ddev#4288]
While working on #4283, as `ddev composer create` is really a wrapper, we are keeping the `--help` functionality of outputting the `ddev` part of the help. By doing this there's currently no way to to get the help output of `composer create-project --help`.

**Comment by rfay** [comment]
No plans to pursue this, but a PR is welcome.

**Comment by stasadev** [comment]
Alternative working command:

```
ddev help composer create
```
