### ISSUE TITLE
Add compatibility between symfony mailer and php sendmail_path configuration for mailhog

### ISSUE THREAD

**Issue by rodrigoaguilera** [ddev/ddev#4363]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

When I configure symfony mailer and set its configuration to "native", trying to send a test email results in an exception from `symfony/mailer`
```
Unsupported sendmail command flags "/usr/local/bin/mailhog sendmail test@example.org --smtp-addr 127.0.0.1:1025"; must be one of "-bs" or "-t" but can include additional flags. 
```
Coming from https://github.com/symfony/mailer/blob/6.1/Transport/SendmailTransport.php#L58

I know there is overrides I can do in settings.php so symfony mailer uses the smtp transport on port 1025 but I would like for this to work out of the box without config overrides.

### Describe your solution

Add a `-t` non-functional flag to the command in the php.ini configurations so the exception is not raised.

**Comment by rfay** [comment]
You don't say what CMS or framework you're using this with.

For Drupal, Latest HEAD has config for symfony mailer built into settings.ddev.php. Could you please try it? It will be in next release, see https://github.com/drud/ddev/pull/4214/files - If you're using Drupal, please try it out (or use those settings).  For homebrew, `brew unlink ddev && brew install --HEAD --fetch-head ddev`, or grab binaries from https://github.com/drud/ddev/actions/runs/3379877735

**Comment by rodrigoaguilera** [comment]
Oh sorry. I'm using it with Drupal and the `symfony_mailer` module. I'm aware that there is settings provided for the `sendmail` transport but I want to set `native` as default as it is the setting that also works on the production environment (different sendmail_path there).

Since symfony mailer reads the command configured as sendmail_path I think the native transport will not also fail for Drupal but any project that tries to use `symfony/mailer`.

It can be fixed at many levels by overriding configuration but I think adding the `-bs` flag in ddev can be one of the cleanest.

**Comment by rfay** [comment]
* Please provide more background on this. 
* Please give links to what "native" is, why it's useful, preferred configuration, etc.  
* Please say what you think needs to be added to https://ddev.readthedocs.io/en/latest/users/basics/developer-tools/ as well.

**Comment by rodrigoaguilera** [comment]
Ok let me try to explain better with some steps to reproduce.

Latest ddev version works out of the box with the drupal module symfony mailer indeed. The steps:
- `composer create-project drupal/recommended-project mysite`
- `ddev config` with drupal9 options
- `composer req drupal/symfony_mailer:^1@beta`

Enabling `symfony_mailer` and sending the test email works. Further steps where I found the issue:
- go to transports for the symfony mailer modules `/admin/config/system/mailer/transport` 
- Add the "Native" transport. It requires no configuration, it picks up the `sendmail_path` from the php configuration, in the case of ddev this is `/usr/local/bin/mailhog sendmail test@example.org --smtp-addr 127.0.0.1:1025`
- Set the newly native transport as default and try to send a test email
A Drupal error message appears
```
Unsupported sendmail command flags "/usr/local/bin/mailhog sendmail test@example.org --smtp-addr 127.0.0.1:1025"; must be one of "-bs" or "-t" but can include additional flags. 
```
the message is not received. That error comes from `symfony/mailer`.

When I wrote this issue I though that the flag that needed to be added to the `sendmail_path` command was `-bs` but `-t` works just the same and has no effect on mailhog behaviour. From the output of `mailhog sendmail -bs` (non-relevant parts removed):
```
unknown shorthand flag: 'b' in -bs
Usage of mailhog:
 ...
  -i, --long-i             Ignored. This flag exists for sendmail compatibility. (default true)
  -t, --long-t             Ignored. This flag exists for sendmail compatibility. (default true)
...
```

So I think setting the sendmail_path in ddev to `/usr/local/bin/mailhog sendmail -t test@example.org --smtp-addr 127.0.0.1:1025` (with the `-t` added). 
will have no side effects and will make `symfony/mailer` happy. I modified my original proposed solution.

Thank you for all the effort you put into ddev, it is really awesome.

**Comment by luenemam** [comment]
This week was full. Next week will be better.

It looks like a good solution for the `native` transport option. Problem is that `symfony_mailer` uses different configs for each transport option.
Maybe there is a solution in here to remove the config override in `settings.ddev.php`. But by default `symfony_mailer` uses `-bs`: https://github.com/symfony/mailer/blob/6.1/Transport/SendmailTransport.php#L36.

**Comment by tyler36** [comment]
Just test with [1.1.0-beta2](https://www.drupal.org/project/symfony_mailer/releases/1.1.0-beta2) which has a "[HTML not found issue](https://www.drupal.org/project/symfony_mailer/issues/3318852)" (fixed)

Following @rodrigoaguilera [steps above](https://github.com/drud/ddev/issues/4363#issuecomment-1305989737)

- Works with "Sendmail" transport
- Confirming error meesage using "native" transport
```
Unsupported sendmail command flags "/usr/local/bin/mailhog sendmail test@example.org --smtp-addr 127.0.0.1:1025"; must be one of "-bs" or "-t" but can include additional flags.
```

DDEV `HEAD-078e1c0`

**Comment by josefglatz** [comment]
This problem also affects TYPO3: When changing the MAIL\transport_sendmail_command to `/usr/local/bin/mailhog sendmail -t test@example.org --smtp-addr 127.0.0.1:1025` it works without throwing errors.

> I've added the `-t` option

**Comment by rfay** [comment]
I'm interested in where this landed - do we need to do a general config change?

**Comment by rodrigoaguilera** [comment]
I'm still in favor of adding the harmless `-t` flag to the sendmail call by default.
Mailpit also ignores it 
https://github.com/axllent/mailpit/wiki/Configuring-sendmail

**Comment by tyler36** [comment]
@rodrigoaguilera If you're interest in Mailpit, checkout https://github.com/tyler36/ddev-mailpit 

Once the addon matures a bit, I hope we can replace the default Mailhog with that. See https://github.com/ddev/ddev/issues/4827
Feel free to submit PRs if you see things can be improved.

**Comment by rodrigoaguilera** [comment]
@tyler36 Great addon. Thanks!

As I understand the path forward is the addon that requires configuration of the thing that sends mail to use smtp and there is no out-of-the-box experience aka relaying email to mailpit when the sendmail defined in php.ini is used. 
This issue is not relevant in that scenario so I'll keep an eye on #4827 in case a strategy that relies on `sendmail_path` is implemented to relay emails to mailpit. I think this issue can be closed in favor of #4827  

I'll start using mailpit in the meantime.

**Comment by tyler36** [comment]
Yes, my comment was more informative than relating to this issue directly.

We should probably still try and sort _this_ issue out. Are you confirming the `-t` causes no harm and resolves the issue at hand?

**Comment by rfay** [comment]
PR is welcome to add the `-t`

**Comment by rfay** [comment]
Please test the artifacts at https://github.com/ddev/ddev/pull/5151#issuecomment-1637295110

Make sure to test not only with the situation that has frustrated you but also with the normal usage that people have been using for years without trouble.
