### ISSUE TITLE
Custom Certs are not working with v1.21.4 and traditional ddev-router

### ISSUE THREAD

**Issue by mdance** [ddev/ddev#4467]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Run a Diagnostic and Paste Link Here

For my custom lets encrypt certificate to work

### Expected Behavior

My custom lets encrypt certificates are used

### Actual Behavior

The mkcert self signed certs are being used instead of my custom certs

**Comment by rfay** [comment]
Hi @mdance - Because you didn't do the requested `ddev debug test` and put it in a gist and give the link here I don't have much I can say. Could you please do that? Also, please note that the instructions for custom certs when using the traefik router are different (if you have traefik enabled). See #4 in https://ddev.readthedocs.io/en/latest/users/extend/custom-tls-certificates/ - you may want to try out traefik anyway, as it's the future of this feature.

**Comment by mdance** [comment]
I checked the link, tried copying the .ddev/custom_certs/[fqdn].{crt|key} to .ddev/custom_certs/[projectname].{crt|key} and tried restarting the project, that didn't seem to make a difference.

I was able to get things working again by enabling the global traefik option.

**Comment by rfay** [comment]
Thanks, I'll take a look. It seems that the automated test TestCustomCerts is working with either router.

**Comment by rfay** [comment]
I'm not having any trouble, maybe you can give more details about your setup.

* I have a project named "d9".
* I created a cert for that project that match only "ddev.d9.site":
```
$ ls -l .ddev/custom_certs
total 16
-rw-r--r--  1 rfay  staff  1493 Dec 19 16:28 d9.ddev.site.crt
-rw-------  1 rfay  staff  1704 Dec 19 16:28 d9.ddev.site.key
```
* With `ddev config global --use-traefik=false && ddev poweroff && ddev restart` I get that cert delivered just fine (you can tell because it only has one alternative name)

**Comment by mdance** [comment]
% ls -la .ddev/custom_certs

total 32
drwxr-xr-x  2 md md 4096 Dec 20 08:52 .
drwxr-xr-x 21 md md 4096 Dec 20 08:54 ..
-rw-r--r--  1 md md 5628 Dec 19 07:30 projectname.crt
-rw-------  1 md md 1708 Dec 19 07:31 projectname.key
-rw-r--r--  1 md md 5628 Dec 20 08:52 projectname.domain.com.crt
-rw-------  1 md md 1708 Dec 20 08:52 projectname.domain.com.key

% ddev poweroff                                                                                                         

Container ddev-projectname-dba  Removed 
Container ddev-projectname-db  Removed 
Container ddev-projectname-web  Removed 
Container ddev-projectname-redis  Removed 
Container ddev-projectname-elasticsearch  Removed 
Network ddev-projectname_default  Removed 
Project projectname has been stopped. 
The ddev-ssh-agent container has been removed. When you start it again you will have to use 'ddev auth ssh' to provide key authentication again. 

% ddev config global --use-traefik=false

Global configuration: 
instrumentation-opt-in=true 
omit-containers=[] 
web-environment=[] 
mutagen-enabled=false 
nfs-mount-enabled=false 
router-bind-all-interfaces=true 
internet-detection-timeout-ms=3000 
disable-http2=false 
use-letsencrypt=false 
letsencrypt-email=email@domain.com
table-style=default 
simple-formatting=false 
auto-restart-containers=false 
use-hardened-images=false 
fail-on-hook-fail=false 
required-docker-compose-version= 
use-docker-compose-from-path=false 
project-tld= 
xdebug-ide-location= 
no-bind-mounts=false 
use-traefik=false 

% ddev start

Network ddev_default created 
Starting projectname... 
User-managed /var/www/projectname/.ddev/.gitignore will not be managed/overwritten by ddev 
Container ddev-ssh-agent  Started 
ssh-agent container is running: If you want to add authentication to the ssh-agent container, run 'ddev auth ssh' to enable your keys. 
Using custom PHP configuration: [/var/www/projectname/.ddev/php/custom.ini /var/www/projectname/.ddev/php/xdebug_client_port.ini] 
Custom configuration takes effect when the container is created.
Use 'ddev restart' for force it to take effect. 
Network ddev-projectname_default  Created 
Container ddev-projectname-redis  Started 
Container ddev-projectname-dba  Started 
Container ddev-projectname-elasticsearch  Started 
Container ddev-projectname-db  Started 
Container ddev-projectname-web  Started 
mkcert may not be properly installed, we suggest installing it for trusted https support, `brew install mkcert nss`, `choco install -y mkcert`, etc. and then `mkcert -install` 
Container ddev-router  Started 
User-managed /var/www/projectname/.ddev/.gitignore will not be managed/overwritten by ddev 
Not creating CMS settings files because disable_settings_management=true 
Successfully started projectname 
Project can be reached at http://projectname.domain.com http://127.0.0.1:49274

**Comment by rfay** [comment]
Please look at the actual content of the certificate that is being shown as invalid.

Only `projectname.domain.com.crt` should be there, please remove `projectname.crt`

If you can share the cert and key with me, please do.

**Comment by mdance** [comment]
I have the projectname.crt one there for when I enable traefik so it works, the cert and key is a wildcard cert issued by lets encrypt

**Comment by rfay** [comment]
The nginx-proxy "traditional" router is deprecated in v1.22.0+, so closing this.
