### ISSUE TITLE
Provide a better scripting language for add-ons

### ISSUE THREAD

**Issue by lolautruche** [ddev/ddev#4478]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

Current extension mechanism allows add-on developers to use [Go templates notation to generate their `install.yaml` file](https://ddev.readthedocs.io/en/stable/users/extend/additional-services/#running-extra-daemons-in-the-web-container).
While this is useful, it is quite limited and complex (Go templates are notoriously known for this), especially when one needs to implement advanced use cases (see [`ddev-platformsh` add-on for reference](https://github.com/drud/ddev-platformsh)).

### Describe your solution

A solution would be to propose a real scripting language that would be launched an interpreted from Go.

Several solutions exist in the Go world, including:
- Lua, using [`go-lua` (Lua 5.2)](https://github.com/Shopify/go-lua) or [`gopher-lua` (Lua 5.1)](https://github.com/yuin/gopher-lua) ([using `gopher-luar` to simplify data passing](https://github.com/layeh/gopher-luar))
- JavaScript, using [`goja` (ECMAScript 5.1)](https://github.com/dop251/goja)
- [Tengo](https://github.com/d5/tengo)

My preference would go for Lua as it's universal.

**Comment by rfay** [comment]
Followups from slack:
* gopher-lua has https://github.com/layeh/gopher-luar which does the data injection.

**Comment by lolautruche** [comment]
[An example of embedding a scripting language](https://www.domoticz.com/wiki/DzVents:_next_generation_Lua_scripting) for extensions in a very different system (Domoticz, home automation system).
The main codebase here is C++, but the idea is the same. You can easily extend the system using Lua. You get a limited context (mainly the `domoticz` object) to interact with the system, and triggers.

I think we could get inspired by this :)

**Comment by cweagans** [comment]
I've been down this road with a work project. I don't want to rain on your parade here, but I would caution against doing this. Embedding a scripting language is not a small thing. In addition to all of the various configurations of ddev that exist today, do you really want to _also_ take on support of whatever random thing somebody cooks up in a programming language running inside of ddev?

If a real plugin system is something that you definitely want to move forward with, have you considered something like https://github.com/hashicorp/go-plugin ? It's very easy to use in Go (plugins are essentially just interface implementations). It's also possible to write plugins in any other language that speaks grpc. Going this route forces you to narrowly define how plugins can/can't extend the core system (which is a feature, not a bug), which limits the potential for supporting strange things.

**Comment by rfay** [comment]
I don't expect this to be a reasonable option any time soon. @cweagans 's suggestion of a go plugin is a nice one, but I don't expect that to happen soon either. Most DDEV add-ons are simple and don't need any fancy go templating, and wouldn't need a fancier language.
