### ISSUE TITLE
Providing DDEV configuration yaml schema dynamically for PHPStorm (ddev-intellij-plugin)

### ISSUE THREAD

**Issue by jamesmacwhite** [ddev/ddev#4511]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

I recently noticed that the configuration yaml schema within the PHPStorm plugin was identifying certain valid configuration values as not recognised or invalid, in my case the project value of `craftcms` https://github.com/drud/ddev/issues/4507 https://github.com/php-perfect/ddev-intellij-plugin/issues/141

It has been determined that the PHPStorm plugin currently has a [static JSON schema definition based on DDEV version 1.19](https://github.com/php-perfect/ddev-intellij-plugin/blob/main/src/main/resources/schema/ddev-config-1.19.schema.json) which predates the addition of this value. Because the schema definition is out of date, this would be why it triggers the PHPStorm IDE to flag values, because it doesn't know they exist. The solution is to update the schema, but it probably goes a bit further on making this dynamic and less fragile going forward.

Speaking with @nico-loeber, it's become apparent that static JSON schemas are problematic for several reasons:

1. They'll likely be out of date often if remaining static in the current implementation.
2. It would require publishing plugin updates for each schema version change.
3. Sometimes, configuration option changes have occurred in incremental releases e.g. the `craftcms` project value was added in 1.21.2, rather than a major release, so if the schema remained static, you'd also have to create schema definitions for incremental releases too, which adds more schema files to be maintained.

Because of the highlighted areas, it would seem more appropriate if the schema lived in the main DDEV repository which the PHPStorm plugin would then pick up on each release.

@nico-loeber has already outlined a potential plan around this: https://github.com/php-perfect/ddev-intellij-plugin/issues/141#issuecomment-1368792258. However the main requirement for this to work would be for a schema definition to exist in the main DDEV repository and be maintained on any changes.

Therefore, I wanted to open up the discussion again on agreeing a potential implementation that works between the two projects while being dynamic.

### Describe your solution

A configuration schema definition to be added and maintained within the main DDEV project which the PHPStorm plugin can be configured to parse the correct release package from GitHub to match against the currently installed DDEV version to pull in the schema to load in the PHPStorm IDE in order provide the correct configuration options, without static schema references or out of date information.

How this is done, I think is important to discuss. Moving the schema into the main project, is part of the solution, but how the schema file is maintained or generated is another. Perhaps this can be generated based off the configuration values within the main DDEV code somehow with an internal command like `ddev schema` to then output the JSON definition format (just as an example).

**Comment by rfay** [comment]
That would be awesome, and the schema needs to be published as well, so IDE's can use it. I think the standard place is https://www.schemastore.org/json/ - it looks like maybe schemastore just points to a published schema. 

Would you be interested in undertaking this? It shouldn't be huge, and of course, we'd have to remember to maintain the schema, but this would be a great step forward. /cc @nico-loeber .

**Comment by jamesmacwhite** [comment]
@rfay I can certainly look at helping bring the schema up to date. We have a basis with the 1.19 version, but it needs updating. It looks like Schema Store supports PHPStorm, so it might be a good fit.

The main thoughts based on speaking with @nico-loeber is the fact that the schema needs to match the DDEV version installed exactly. While the current static schema in the PHPStorm plugin is 1.19 and quite old, say if I had DDEV 1.21 but tried to use the project type `craftcms` that's invalid until 1.21.2, so we are going to need to provide versioned schema files and also versioned for incremental releases too if there are such changes. I don't know if PHPStorm is intelligent enough to match the DDEV version to the exact release i.e. 1.21.4 but fallback to 1.21 if one doesn't exist?

The other issue is if the schema isn't directly with the DDEV repository, how can we assure that the schema can be updated in time for a release? Could that cause issues regarding DDEV releases?

The fact that PHPStorm automatically picks up schemas from Schema Store by the sounds of it, sort if removes reliance on the PHPStorm plugin having to pull a schema from a release in the plugin itself, but it then potentially shifts the problem to an outside repository, which needs to be maintained, which isn't in the DDEV repository and therefore needs separate management.

Certainly happy to help implement the solution, just wanting to explore the implementation before starting to work on it. Happy for comments.

**Comment by rfay** [comment]
The way this would work (I think) is that SchemaStore gives a pointer to the actual schema stored in our repo. I'm sure it could be part of a URL that had a tag, could be a release file.  So on every release, we would have a schema file.

PhpStorm and vscode definitely use SchemaStore for validating yaml, but that doesn't mean that the plugin will be using that feature directly.

**Comment by jamesmacwhite** [comment]
@rfay Ah OK, so that would be the best option, if it's more of a signpost to where the schema is but ultimately lives here in the DDEV repository, but allows PHPStorm to go find it through Schema Store that's the best outcome for control and accuracy.

Based on the above then, are these the next steps?

- [ ] Create schema for DDEV in https://github.com/drud/ddev
- [ ] Add schema reference to JSON Schema Store with appropriate URL that links to DDEV release to be used by PHPStorm automatically
- [ ] Remove old 1.19 schema from PHPStorm plugin?

I guess the issue is what about older DDEV versions? We can't really backport the schema into old releases I don't think?

**Comment by rfay** [comment]
I sure would appreciate you taking the initiative on this @jamesmacwhite - any progress?

There's no need to think about older versions. Just current. Pretty sure that's how all the schemas in SchemaStore work.

**Comment by jamesmacwhite** [comment]
@rfay Hello. Sorry for the lack of reply, if we are going to implement the latest version of the schema per the latest stable release using: https://www.schemastore.org/json/ then I'll look at doing it.

**Comment by nico-loeber** [comment]
> I sure would appreciate you taking the initiative on this @jamesmacwhite - any progress?
> 
> There's no need to think about older versions. Just current. Pretty sure that's how all the schemas in SchemaStore work.

I was about to suggest versioning of the configuration like docker compose does but then I found this part in the documentation:

> The top-level version property is defined by the Compose Specification for backward compatibility. It is only informative.
>
> Compose doesn’t use version to select an exact schema to validate the Compose file, but prefers the most recent schema 
> when it’s implemented.

So I'm fine with that. :)

The current schema the plugin is using can be found here: https://github.com/php-perfect/ddev-intellij-plugin/blob/main/src/main/resources/schema/ddev-config-1.22.schema.json

**Comment by rfay** [comment]
This is also not about the compose yaml files (which are already supported in schemastore) but about the DDEV config.yaml.

**Comment by jamesmacwhite** [comment]
OK, so just recapping all of this as it has been a while!

It looks like @nico-loeber has done a fair bit of the work already with the existing specification within the DDEV PHPStorm plugin. It does however need cross referencing against the latest https://ddev.readthedocs.io/en/latest/users/configuration/config/ to update as it was written for 1.19, so there's newer options not covered, looping back around to my initial report given I use the craftcms type which was only included more recently.

Just working through the setup, where will the JSON schema live, will it be part of the DDEV repository or will is be in: https://github.com/SchemaStore/schemastore/tree/master/src/schemas/json.

**Comment by rfay** [comment]
Seems to me they want it to be maintained in https://github.com/SchemaStore/schemastore right?

**Comment by rfay** [comment]
Note that there would be (at least?) two things to put there, the ddev project config (config.yaml) and the global config (global_config.yaml)

**Comment by jamesmacwhite** [comment]
@rfay I got the impression it needs to be committed into `src/schemas` in the appropriate format with tests based on the contributing guidelines, so I'll have to look through the specification in more detail and form a pull request.

**Comment by jamesmacwhite** [comment]
I'm working on this now, sorry for the delay. I've staged a branch to view progress before sending as a PR: https://github.com/jamesmacwhite/schemastore/tree/ddev-schema

So in terms of the DDEV config, there's global and project specific, does that mean we need two JSON Schemas? ddev-global.json and ddev-project.json?

I'm assuming for tests we'll need to do this?

**Comment by rfay** [comment]
This is so great. It's always so great to work on a file that has a schema, the IDE presents it so well. Looking forward to it.

Yes, I'm sure we'll need two schemas. 

> I'm assuming for tests we'll need to do this?

Not sure what you mean here.

**Comment by jamesmacwhite** [comment]
With two schemas, this would mean we'd also need two test files one for the global config the other for project specific config?

The existing one from @nico-loeber I believe is just the project config schema (with some missing options which can be added with this work)

But another separate one is needed for the global options. So would it looks like:

`src/schemas/json/ddev-global.json`
`src/schemas/json/ddev-project.json`

Followed by matching test files for the two?

**Comment by rfay** [comment]
Sounds great to me.

**Comment by jamesmacwhite** [comment]
Here's an updated 1.22 version synced against the docs:

https://github.com/jamesmacwhite/schemastore/blob/609074c61a23eb70878552eb5ec9f03fb08c5783/src/schemas/json/ddev-project.json

I'll look at the global config version and then the tests.

**Comment by rfay** [comment]
Looking fantastic

**Comment by jamesmacwhite** [comment]
OK looks like the tests support yaml so that makes it easier porting an existing config.yaml or global_config.yaml for the unit tests. I'll work on those very soon. I've got things up and running with schema test, it looks like the original schema used with the Intellij plugin has some values and properties which aren't valid to the spec, so it needs cleaning up a bit, but getting there. should hopefully have this sorted in the next few days.

**Comment by jamesmacwhite** [comment]
OK, I've now created validated tests for the global and project config, which pass strict validation when tested. I've squashed the commits. I had a bit of fun understanding the array/object syntax relative to YAML to JSON spec, but got there in the end.

https://github.com/jamesmacwhite/schemastore/tree/ddev-schema

The original project schema from @nico-loeber had a lot of the work alread done, just a few validation issues and updates to config options, given it was originally written for 1.19.

Feedback welcome, before I submit a PR to the schemastore repository.

**Comment by jamesmacwhite** [comment]
I am wondering if however we shouldn't just commit the schema into the main ddev repository, because otherwise maintaining it is going to be PRs to a third party repository which is going to be slower for new release. It looks like you can specify URL values in the catalog including https://raw.githubusercontent.com links.

**Comment by rfay** [comment]
Self-hosted is far better, thanks for noting this! 

Maybe a schema in pkg/ddevapp and a schema in pkg/globalconfig?

**Comment by jamesmacwhite** [comment]
Yeah, happy to PR the current work done on schemastore and then amend that so it points to DDEV hosted version. I think the path can be anything provided the right URL reference is used in schemastore and API catalog data.

So something like this?

`pkg/ddevapp/schema.json`
`pkg/globalconfig/schema.json`

I believe we lose the ability to run tests against the spec with schemastore with the config.yaml and global_config.yaml test cases, but I could keep that branch around to test on, with the tests.

**Comment by rfay** [comment]
> I believe we lose the ability to run tests against the spec with schemastore with the config.yaml and global_config.yaml test cases, but I could keep that branch around to test on, with the tests

That would be a great thing to find out about. As you know so well, these things can drift accidentally quite easily.

**Comment by jamesmacwhite** [comment]
It would seem based on the contributing notes, when using the external/self hosted option, it is a requirement to add the files into the skip test file, as I'd imagine it can't function without being local.

https://github.com/schemastore/schemastore/blob/master/CONTRIBUTING.md#how-to-move-a-schema-from-schemastore-to-somewhere-thats-self-hosted

By self hosting, the reference within schemastore is like a stub pointing to the external file. so I don't think the unit tests are able to be used, which is a shame.

A local version on a branch may need to be kept for testing/verification with the tests.

**Comment by rfay** [comment]
> By self hosting, the reference within schemastore is like a stub pointing to the external file. so I don't think the unit tests are able to be used, which is a shame.

We can just run unit tests in DDEV?

**Comment by jamesmacwhite** [comment]
From schemastore? I don't think so the npm command is local within that repository `npm run grunt -- --SchemaName=<schemaName.json>`. A unit test would have to be developed within ddev as part of the build process I'd imagine?

[I did create two test files which passed under strict rules](https://github.com/jamesmacwhite/schemastore/commit/1a2202e71b0bfa39fbba6e54908c1ca3851b81f2), so maybe we need to move them into the ddev repository and implement an additional CI check? The JSON schema stuff is all very new, so I'm not entirely sure on the more advanced areas.

**Comment by rfay** [comment]
The test can be added to github actions probably the same way as it's done in schemastore? A separate test would probably be the most efficient.
