### ISSUE TITLE
Competitor feature analysis

### ISSUE THREAD

**Issue by mayankguptadotcom** [ddev/ddev#4521]
By conducting a competitive analysis, we can understand the products DDEV competitors have created; compare the functions, strengths, and weaknesses of your product against theirs; and understand how other local development tools are solving the problems of their target audience.

Competitive analysis will allow us to see how local development solutions have fully or partially solved similar problems for our target audience.

I've created a Google sheet which has [feature analysis of DDEV's Competitors](https://docs.google.com/spreadsheets/d/1SVlONYOdqFEobsGFh3vjb8EhMrMCrh4AIbDfoSKPZ-o/edit?usp=sharing) and will be happy to share the edit rights with anyone who is interested in participating. Please ask for access in Discord (mayankg) by reaching out to me.

**Comment by rfay** [comment]
Please make sure to fill in the detail, rather than just the title, thanks. You can just edit your initial comment here. You'll want to say things about what you're doing, why you're doing it, how we'll know when it's done, etc.

**Comment by rfay** [comment]
Issues without an explanation or body are not allowed in this issue queue, sorry. When you create an issue, please make sure to put full details of what you're up to, what you want, what you expect to do.

**Comment by mayankguptadotcom** [comment]
Agreed, and apologies for that. I'll follow this process from now on ->

1. Create a draft issue in project.
2. Expand on it to convey the idea/issue
3. Once it has sufficient information, create it as an issue so that it can be worked upon.

**Comment by rfay** [comment]
Closing, no progress, happy to see this initiative in the future.
