### ISSUE TITLE
Define user personas

### ISSUE THREAD

**Issue by mayankguptadotcom** [ddev/ddev#4533]
As a product team, it's important to have defined user personas that we are targeting or to better understand the kind of users that users' needs and their goals. 

## Benefits of Personas

-   Project wide shared understanding of who the users are, their behavior and needs
-   Stop everyone from thinking about themselves, their friends and family as the only user(s)
-   More effective, focused conversations on where the project should head
-   Clearer and better decision making – focused on user needs and goals
-   Greater empathy with the users who may have started their journey as developers and may feel overwhelmed with the influx of new terminologies and knowledge that comes with DDEV

### Long answer ->

Please note - this my observation and would love for others to chip in with their thoughts, ideas, disagreements.

I'd recommend building personas of the following developer profiles:

1. Newbie Developer (1-2 years of development experience)
2. Seasoned Developer
3. Expert Developer (Tech Leads/Technical Managers/And likes)

And of course, we could go in to understanding developers from various CMSes (like WP Devs, Drupal Devs, CraftCMS Devs) to further understand granular needs - however, it's wise to stick to 3 personas - as the above suggested personas' needs should satisfy the needs of various CMS specific developers, however as we dive deeper, we may investigate these granular segmentations.

## What needs to be done

1. Identify users who fit in the above-mentioned segmentation
2. Interview them, to learn about their pain points, their biggest challenges, their job responsibilities etc.
3. Build the personas
4. Share their stories with everyone through the website, and encourage issue reporters, feature requests to start utilizing user stories to describe the requirements. 
5. Tweak the docs, support, and content to help users find the content that resonates with them.

**Comment by rfay** [comment]
Closing, no progress, happy to see this initiative in the future.
