### ISSUE TITLE
TYPO3-project in subfolder leads to wrong configuration path

### ISSUE THREAD

**Issue by rtoenjes** [ddev/ddev#4545]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Run a Diagnostic and Paste Link Here

Diagnostic shows no errors.

### Expected Behavior

When setting up a TYPO3-project in a subfolder `/src` everything should run normal.

### Actual Behavior

When setting up a project in a subfolder `/src` and defining `docroot: src/public` and `composer_root: src` in `config.yaml` there is an additional `/src/src/public/typo3conf/AdditionalConfiguration.php` generated. 

### Steps To Reproduce

Setting up a fresh&clean project with
```
ddev config --project-type=typo3 --docroot=src/public --create-docroot --composer-root=src
ddev composer create --no-install "typo3/cms-base-distribution:^11.5"
ddev composer install
```
Until now, everything is fine. But when doing a
```
ddev start
```
the additional `/src/src/public/typo3conf/AdditionalConfiguration.php` is generated. 

### Anything else?

Only TYPO3 v9-11 are affected. With v12 it seems to behave well.

**Comment by rfay** [comment]
Thanks for this! And thanks for the extra troubleshooting. 

Do I understand correctly that this does not cause any operational problem when it appears in TYPO3 v9-11?

**Comment by rtoenjes** [comment]
As long as there are no config changes which result in an adapted DDEV-controlled `AdditionConfiguration.php` there should be no problem. Until now I had no problemes in two projects.

**Comment by woemar** [comment]
I can confirm this problem using TYPO3 11 and a setup with `docroot: src/projectname` results in an `AdditionalConfiguration.php` being created at `src/projectname/src/projectname`.

**Comment by rfay** [comment]
@woemar that's the opposite of what @rtoenjes said...

**Comment by steffenf14** [comment]
i have the same problem with several projects with various php versions. the problem only occurs when composer_root is set.
@rfay what @woemar is the same problem, the composer_root gets somehow attached/used for the creation of the AdditionalConfiguration.php 
ddev version v1.21.6

**Comment by gilbertsoft** [comment]
Can confirm the bug and it's only related to v11 or lower. Bugfix is on the way...
