### ISSUE TITLE
Get a fundraising "ask" script together

### ISSUE THREAD

**Issue by rfay** [ddev/ddev#4555]
We'd love to continue funding a co-maintainer and docs maintainer longer than the next few months, but that will require significantly increased support from the community. It's time to be explicit in our asking.

- [x] Ask on Twitter and Mastodon if somebody can help with this
- [ ] Build the fundraising script/ask
- [ ] Get a list of possible large donors together
- [ ] Begin contacting donors large and small

**Comment by rfay** [comment]
Asked for help on https://fosstodon.org/@ddev/109739670716612445 and twitter.

**Comment by rfay** [comment]
Ideas:
* Informally calculate the financial value of DDEV and its maintenance and support to your team(s). Consider committing to 10% of that.

**Comment by rfay** [comment]
Comments from community:

- [ ] Make a support contract available. Many companies do not know how to do a donation, but they do know how to do a support contract. 
- [ ] Target organizations: Large CMS/framework associations like TYPO3 Association may want to support DDEV at a higher level, or encourage agencies that work with their framework to contribute. A special script may help these orgs to frame the problem to agencies.
- [ ] DDEV needs a newsletter! The newsletter needs to include funding news and links to funding possibilities. 
- [ ] DDEV origin story on ddev.com, history, current usage, current donors may help people to understand why to support (@mattstein has this in progress)
- [ ] Current DDEV users in larger orgs can be prompted to provide contact info and introduction to decisionmakers who could do support contract, etc.
- [ ] After a meeting with possible donor, leave them with a 1-page written "What we do, what’s the impact, how you can participate"
- [ ] Name-drop the current sponsors better, not just have them on github page, but also ddev.com, etc

**Comment by mattstein** [comment]
May also want to consider designating a community advocate for each major company or framework, so there’s a clear line of communication and a person to absolutely keep in the loop for fundraising, development, etc.

**Comment by mattstein** [comment]
> DDEV needs a newsletter! The newsletter needs to include funding news and links to funding possibilities.

My experience has been that these take considerable overhead, and a lower-commitment step in that direction would be clearly identifying announcements (on the blog or in their own place) and promoting them from Discord, Twitter, Mastodon, etc. Ideally an email newsletter would promote publicly-visible things anyway.

**Comment by rfay** [comment]
I already do a newsletter every month, aimed only at donors on github sponsors. That's very modest work (the way I do it) but it should have a broader audience.

**Comment by xenoscopic** [comment]
[This interview](https://corecursive.com/066-sqlite-with-richard-hipp/) with SQLite's D. Richard Hipp, which popped up again on [Hacker News](https://news.ycombinator.com/item?id=34559075) today, provides some interesting data points (as well as a fun overall narrative):

Hipp claims that he charged Motorola somewhere in the neighborhood of $80,000 in 2002 for a support contract to integrate SQLite into their products (just two years into SQLite's existence). Adjusted for inflation, that's in the neighborhood of $134,000 today. Even he concedes that this was, in reality, a relatively small amount of money given the scale of operations at these businesses.

He talks later about the SQLite Consortium, which in his case formed somewhat serendipitously, but which became an important revenue driver for the project. Trying to find information on early pricing is difficult, but, looking at the Wayback Machine, membership in the consortium was listed at $75K/year in September 2016, $85K/year in August 2018, and $120K/year in February 2022.  He also makes some critical points about which rights consortium members should (or should **_not_**) be afforded.

I think it's important that FOSS projects, especially those critical to medium-to-large companies (including post-Series A startups) with employee salaries in the $150-300K/year<sup>1</sup>, tell those companies that they're going to need to pay high-5 or low-6 figure yearly amounts if they want to **_depend_** on these critical projects. Donations of a few hundred or a few thousand dollars are not going to be sufficient to support any reasonable standard of living in 2023, especially if those companies expect a near monopoly on the FOSS developer's time.

These are just my thoughts. I don't mean to imply that more modest means of living aren't possible (of course they are!), but I think the market should and will (if forced) support more reasonable and sustainable amounts of funding.

---

<sup>1</sup> Many jurisdictions (including the several tech-heavy counties in Colorado) now force companies to disclose salary ranges for positions offered in those locations (which, via remote work, many now are).  This data is an excellent source of information on what those companies might pay an engineer, support staff, or a product manager, of which DDEV's developer is all three.

**Comment by rfay** [comment]
Thanks to @xenoscopic for pointing out excellent [blog by Filippo Valsorda](https://words.filippo.io/full-time-maintainer) about his strategy for making open-source maintainership work.

**Comment by rfay** [comment]
Excellent podcast with Filippo Valsorda, https://changelog.com/podcast/533

**Comment by rfay** [comment]
I'd appreciate anybody's input on https://docs.google.com/document/d/1S93iD9GgfSoH_QGyKoQ6OQa7u1KeDKKQ-yqP7jbXs6Y/edit?usp=sharing

**Comment by rfay** [comment]
We have made quite a lot of progress on this front, and this issue is now obsolete, but we have plenty to learn still, and plenty of communication to do. Closing, new initiatives need new issues.
