### ISSUE TITLE
Add "file" as alias for import-db flag "src"

### ISSUE THREAD

**Issue by DaleTrexel** [ddev/ddev#4593]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

Export-db uses `--file` to specify the file being exported. Import-db uses `--src` to identify the _file_ being imported. (In fact, the shortcut for `--src` is `-f`!) It would be nice to not have to remember which flag goes with which operation, and it would be especially nice not to have the command simply fail when you accidentally use the wrong one.

The safest way to do this is probably to add `--file` as an alias, rather than renaming it.

### Describe your solution

Add `--file` as an alias for `--src` for the import-db command.

### Describe alternatives

You could probably rename `--src` to `--file` for consistency, but that would probably make a lot of people sad who are used to the way things are now. I think we can avoid that with an alias.

**Comment by rfay** [comment]
Somebody earlier wanted to change export-db to use --src, but your idea is probably better. Want to try a PR?

**Comment by DaleTrexel** [comment]
It's probably an easy thing if you know what you're doing, but I have no experience with Go, and especially not with developing command line tools. I'd be happy to let someone else run with this one.
