### ISSUE TITLE
Use XHGui as front-end for xhprof

### ISSUE THREAD

**Issue by Firesphere** [ddev/ddev#4606]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

The XHProf interface is frustratingly un-informational, and does not provide a clear way of knowing which call I'm looking at.

### Describe your solution

The interface of XHGUI is more readable and user friendly (e.g. includes which URL was called, etc.).

Therefore, I'd like to have a simple way of swapping out XHProf for XHGUI

**Comment by rfay** [comment]
Take a look at https://github.com/drud/ddev-contrib/pull/128, and your contribution would be welcome. Could be done as a ddev add-on probably.

**Comment by rfay** [comment]
Definitely not completed.

**Comment by Firesphere** [comment]
I was closing old open issues, I thought this one was done, as you suggested it be done via an addon instead of part of ddev itself.

**Comment by rfay** [comment]
I think this might have a great start as an add-on, although it probably belongs in core as well.

**Comment by rfay** [comment]
@tyler36 has pioneered this in https://github.com/tyler36/ddev-xhgui, yay!

**Comment by tyler36** [comment]
Thanks to @deviantintegral , there is now a working `tyler36/ddev-xhgui` is now working and an (early) release is available.
There's still some work to do (docs and tests) but hopefully, it will be promoted soon.

**Comment by rfay** [comment]
@LionsAd we'd love it if you'd take a try with https://github.com/tyler36/ddev-xhgui

**Comment by rfay** [comment]
I think the add-on is looking so good that we should not yet prioritize this. It's maturing and moving toward using the project db server as well.

**Comment by tyler36** [comment]
https://github.com/tyler36/ddev-xhgui/pull/22 adds support for using DDEV default database. Not sure best way to handle Postgres DB, removing MongoDB completely. 

Any thoughts?

**Comment by rfay** [comment]
Per https://github.com/ddev/ddev/issues/5777 let's add the link to `ddev describe` when we do this work.

**Comment by rfay** [comment]
I'm going to close this in favor of work in https://github.com/ddev/ddev-xhgui. We'll use the add-on technique for xhgui and try to make it as good as it can get. It does need to be added to the main DDEV docs.
