### ISSUE TITLE
DDEV v1.21.5 Test Plan

### ISSUE THREAD

**Issue by rfay** [ddev/ddev#4625]
It's testing time again here in the DDEV factory. We love community help with every item that is interesting or relevant to you, and just *using* the release candidates is hugely helpful, because you may stumble across something in your regular workflow. Please use DDEV HEAD for your testing (or `brew unlink ddev && brew install --HEAD --fetch-head ddev/ddev/ddev`) or other techniques at [Testing Latest Commits](https://ddev.readthedocs.io/en/latest/developers/building-contributing/#testing-latest-commits).

I don't think in general you'll have trouble using this in your daily workflow, so would love you do do that. You can switch back and forth , see [How can I install a specific version of DDEV in the FAQ](https://ddev.readthedocs.io/en/latest/users/basics/faq/).

If you find a bug that you're pretty sure is a bug, then [just open an issue for it](https://github.com/drud/ddev/issues/new?assignees=&labels=&template=Bug_report.md&title=).

To give feedback or ask questions, please just reply on this issue or discuss in [discord](https://discord.gg/hCZFfAMc5k) or any other support channel.

I am maintaining the [provisional release notes for v1.21.5](https://www.notion.so/Provisional-v1-21-5-Release-notes-b42d8d5939ed46f0998d3e5f5ec26805) and would love any comments on those.

See [commits since v1.21.4](https://github.com/drud/ddev/compare/v1.21.4...master) and [PRs merged since Dec 15, 2022](https://github.com/drud/ddev/pulls?q=is%3Apr+is%3Aclosed+merged%3A%3E2022-12-15)

1. `ddev composer create` should respect composer_root [#4611](https://github.com/drud/ddev/pull/4611); Use the instructions there to set `composer_root` and verify that `ddev composer create` creates composer.json and vendor in that directory.
2. `ddev start` should work even with `nodejs_version: 18`, [#4610](https://github.com/drud/ddev/pull/4610)
3. `ddev get --list` should show official add-ons, [#4609](https://github.com/drud/ddev/pull/4609)
4. xdebug should not be enabled by default in ddev-webserver, [#4599](https://github.com/drud/ddev/pull/4599). This just means running latest ddev-webserver, for example `docker run -it --rm drud/ddev-webserver:20230207_fix_nvm php --version` should not show xdebug. (Get latest version of ddev-webserver with `ddev version`)
5. Traefik should handle $VIRTUAL_HOST, [#4582](https://github.com/drud/ddev/pull/4582). Follow the instructions in the issue to recreate.
6. Fix ‘n’ panic in ddev-platformsh, [#4581](https://github.com/drud/ddev/pull/4581)
7. `ddev ssh` should not useless exit status, [#4569](https://github.com/drud/ddev/pull/4569). Just `ddev ssh` and do something and `exit`. It shouldn't output anything, but the exit code (`$?`) will be the exit code of the last-executed item.
8. WSL2 hosts management, [#4553](https://github.com/drud/ddev/pull/4553). Use non-ddev.site hosts in WSL2 and verify behavior. Also check `ddev delete`.
9. Container start hooks, [#4549](https://github.com/drud/ddev/pull/4549). Use example in issue.
10. .env files should be in correct app-specific directory, [#4526](https://github.com/drud/ddev/pull/4526)
11. GitHub Codespaces support, [#4476](https://github.com/drud/ddev/pull/4476). Try it out.
12. DDEV_PHP_VERSION provided at Dockerfile build time [#4463](https://github.com/drud/ddev/pull/4463) (check docs on this; are they properly updated to show this technique?)
13. `ddev nvm` should work properly; see problem and repro techniques in https://github.com/drud/ddev/issues/4499
    * Make sure that there isn't the "unary operator failed", https://github.com/drud/ddev/issues/4499#issuecomment-1367478779
15. Test mysql:8.0 and mysql:5.7, including with snapshots; version should be 8.0.31 and 5.7.42.

**Comment by rfay** [comment]
1. ✅ `ddev composer create` with composer_root

**Comment by rpkoller** [comment]
1. ✅ i've used the steps from the linked issue summary. the vendor dir and composer json is in `app` while the docroot is under `app/web`. and did run a subsequent `ddev composer install` and get `Nothing to install, update or remove`. so it looks correct?
2. ✅ i get v18.4.2
3. ✅  official  add-ons are shown
4. ❓  not sure ran `ddev version` in a running project and the webserver is ` drud/ddev-webserver:v1.21.5 ` if i run then `docker run -it --rm drud/ddev-webserver:v1.21.5 php --version` what @rfay did i get 
```
PHP 8.0.28 (cli) (built: Feb 14 2023 18:26:48) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.28, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.28, Copyright (c), by Zend Technologies
```
but when i enter `ddev xdebug on` it remains the same. should xdebug shown there as well then? cuz `enabled xdebug` was shown?
5.❓ couldn't find virtual_host nor anything traefik related in the config.yaml of the ddev project and as noted in the testing protocol by @rfay the testing instructions aren't very helpful and my technical understanding is way less advanced than randys. i've also looks into .ddev/.traefik/[my project name].yaml but also no string with virtual_host. no idea how to test. 
6. -  i have no plattform.sh account
7. ✅
8.  - no wsl2/windows computer

**Comment by rfay** [comment]
Thanks @rpkoller - in number 4, the test is running the raw container, which you did. `ddev xdebug on` only affects a running DDEV project, not the raw container, as you ran it. But you got the right results (xdebug not enabled).

VIRTUAL_HOST is absolutely a very arcane and unusual thing that most people will never come into contact with. In fact, it's not even described properly in https://ddev.readthedocs.io/en/latest/users/extend/custom-compose-files/#conventions-for-defining-additional-services; it's only used by one add-on that I know of (ddev-varnish). In almost all cases it is set to $DDEV_HOSTNAME, but it can be changed in a docker-compose.*.yaml.

**Comment by rpkoller** [comment]
isn't updating the project_tld setting in ddev's config files the proper approach anyway?

**Comment by rfay** [comment]
That's unrelated to VIRTUAL_HOST, which is used when you need a *second* hostname. Super obscure possibility, used by very few folks.

**Comment by rpkoller** [comment]
ohhhh for a second hostname. thanks for the clarification!

**Comment by rfay** [comment]
Calling this good. Any additional testing is obviously welcome still!
