### ISSUE TITLE
Verify the events used to trigger a release

### ISSUE THREAD

**Issue by gilbertsoft** [ddev/ddev#4629]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected Behavior

Publishing a release should trigger the release workflow, no matter if it's directly published or published from a draft. See https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#release

### Actual Behavior

Creating a draft release and publish it afterwards does not trigger the release workflow.

**Comment by rfay** [comment]
The context here is that in releasing v1.21.5-alpha1 @gilbertsoft first created a draft, then saved the draft, then returned to the draft and clicked "publish" but the release workflow didn't happen. It's possible it was a GitHub bug or glitch, not sure. Should be easy to recreate on a fork.

**Comment by rfay** [comment]
If you get interested in this again, feel free to reopen.
