### ISSUE TITLE
Allow setting a minimum ddev version in config.yaml

### ISSUE THREAD

**Issue by deviantintegral** [ddev/ddev#4630]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

Sometimes ddev adds a feature or fixes a bug that is critical for a project team. It would be great if a minimum (or semver style?) version could be set in a project configuration.

### Describe your solution

When ddev is run, and it's older than the version in config.yaml, ddev should show an error and prompt the user to upgrade.

**Comment by rfay** [comment]
I like that. Previous suggestions along this line have been about a configuration version (which DDEV used to have, but was never useful, so was removed). But a suggested or required DDEV version in the config.*.yaml could really be useful.

**Comment by rfay** [comment]
Can you give an example of a situation you or your team ran into @deviantintegral ?

**Comment by deviantintegral** [comment]
The more common is when a team member is having difficulty and it turns out they are running a very old version of ddev. I recently fixed a colleague’s issue after discovering they were on 1.17.

However, we would also use this when we go back to using node 18 after the March release.

**Comment by oheinemann** [comment]
For me, this would also be a useful feature. I had a similar problem with the config parameter web_environment which was introduced in version 1.19.2. We use it in a current project and every new teammate - who is one version below - has problems because they don't have the appropriate environment variables.

If you get a hint at startup or the project won't even start because you don't meet the minimal requirement and should update your DDEV version, that would be quite helpful.

**Comment by hanoii** [comment]
I think this is a useful idea, specially thinking about major version changes where you might prepare your project for it and although it could be backward compatible you want your teammates to update. This will also just help keeping all team with updated ddev versions.

**Comment by rfay** [comment]
It would also be possible to give a version constraint rather than just minimum version. None of this would help with people using ddev versions from before this feature got added, of course.

**Comment by hanoii** [comment]
and adding it to the `config.yaml` file makes sense, as it can perfectly be overridden by yaml local files

**Comment by hanoii** [comment]
I think a minimum is enough, what kind of constrains you can think of other than always setting up a >=?

**Comment by deviantintegral** [comment]
For the future, declaring that it's not compatible with a theoretical ddev 2? Or, if there's a regression or compatibility issue and and capping a maximum version.

**Comment by mglaman** [comment]
We just hit an issue on macOS amd64 vs arm64 which was fixed with DDEV 1.22, so this would be handy to enforce a minimum DDEV version.

(Drupal's automate test was writing `/sites/simpletest/SITE_ID` and missing write permissions. No idea why. But arm64 was fixed on 1.22, maybe due to Mutagen.)

**Comment by hanoii** [comment]
I came back to this, I wanted to enforce 1.22.1 on a project. For now I will try to do an exec-host pre start script, question.. is it OK to assume bash is present on every platform? I'd assume native windows it won't be, but I can live with that for now.

On a the go front, I found https://github.com/Masterminds/semver to be a suitable candidate for adding this to ddev. 

I also found https://github.com/hashicorp/go-version but the former has more support of constraints from what I could tell.

**Comment by rfay** [comment]
> is it OK to assume bash is present on every platform

If you're doing something on the host, you probably can't assume that, but you can assume sh is there. 

DDEV already includes and uses semver.

**Comment by rfay** [comment]
BTW, the classic way to do this is with `ddev debug capabilities | grep <needed-capability>` - there are also version checks in a number of tests etc. Somewhere we have a bash version check library. Didn't fine it with quick look.

**Comment by jonaseberle** [comment]
> Somewhere we have a bash version check library

I think I've found it:
https://github.com/ddev/ddev/blob/master/.buildkite/sanetestbot.sh#L13

Running it in the container we do not  have `pre-start` so this just outputs the error but continues trying to start:
```yaml
hooks:
  post-start:
    - exec: |
      minVersion=v1.23
      test "$minVersion" == "$(sort --version-sort <<< "$DDEV_VERSION"$'\n'"$minVersion" | head -n 1)" || \
        (
          echo -e "\033[1;31m[error] This project requires ddev version $minVersion+, please update ddev.\033[0m"
          exit 1
        )
```

It would really be nice to be able to define a minimum version in the project's `config.yaml`.

**Comment by hanoii** [comment]
Implementing is probably not too hard, but It will likely require tests, I'll try looking at this at some point.

**Comment by hanoii** [comment]
I give this a crack in #5379, seems to work nice :) Probably needs some work

**Comment by rfay** [comment]
Those of you that asked for this, @deviantintegral @mglaman @oheinemann could you please review and manually test
* https://github.com/ddev/ddev/pull/5379 ?

Artifacts are at https://github.com/ddev/ddev/pull/5379#issuecomment-1734741797

**Comment by deviantintegral** [comment]
Is this just broken with dev builds?

```
$ grep version_constraint .ddev/config.yaml
ddev_version_constraint: '>=1.22'
$ ~/Downloads/ddev status
Failed to describe project(s): ddev version v1.22.3-24-g3d90d5eeb is not supported by this project (>=1.22), use a supported version or update your project config.yaml's `ddev_version_constraint`
```

**Comment by rfay** [comment]
Thanks for testing!

No, unfortunately, the go library used just works that way, which is annoying. It works fine with "normal" versioning.

See
* https://github.com/ddev/ddev/pull/5379#issuecomment-1755701990

**Comment by deviantintegral** [comment]
Ah. I know you link to the upstream docs, but I think it may be worth some duplication. If it doesn't closely match semver parsing as used in composer or npm, I think you'll get lots of support requests on this.

**Comment by rfay** [comment]
It's annoying. And especially when people download an intermediate build like you have. I tested by building locally with `make VERSION=<someversion-without-all-the-weird-stuff-on-it>`

@hanoii any thoughts on how to can do better with this?

**Comment by hanoii** [comment]
@deviantintegral @rfay my reasoning with this issue in particular is that this will only an issue with people trying out these dev builds on a project with a ddev constraint.

In thinking for a potential improvement, which is tricking the comparison a bit by thinking of ddev usage, and always accept-prereleases.

In reading https://github.com/Masterminds/semver#working-with-prerelease-versions in detail, and in particular:

> SemVer comparisons using constraints without a prerelease comparator will skip prerelease versions. For example, >=1.2.3 will skip prereleases when looking at a list of releases while >=1.2.3-0 will evaluate and find prereleases.
>
>The reason for the 0 as a pre-release version in the example comparison is because pre-releases can only contain ASCII alphanumerics and hyphens (along with . separators), per the spec. Sorting happens in ASCII sort order, again per the spec. The lowest character is a 0 in ASCII sort order (see an [ASCII Table](http://www.asciitable.com/))
>
>Understanding ASCII sort ordering is important because A-Z comes before a-z. That means >=1.2.3-BETA will return 1.2.3-alpha. What you might expect from case sensitivity doesn't apply here. This is due to ASCII sort ordering which is what the spec specifies.

I can maybe suggest the following:

- after the version is considered semver-valid
  - look for a hyphen, 
    - if present, strlower it (this is to avoid the ascii isue mentioned above, so that `-BETA` is always above `-alpha`.
    - if not present, append `-0` the the configured ddev-version-constraint. I think this will avoid most issues.

**Comment by hanoii** [comment]
@deviantintegral I just added #5424, if you can test, that's good.

**Comment by hanoii** [comment]
Closing this one again as per #5424
