### ISSUE TITLE
Outdated example at https://ddev.com/ddev-local/customizing-ddev-local-images-with-a-custom-dockerfile/

### ISSUE THREAD

**Issue by gilbertsoft** [ddev/ddev#4648]
### Expected Behavior

Docs / blogs have to be updated properly.

### Actual Behavior

The example to add files (https://ddev.com/ddev-local/customizing-ddev-local-images-with-a-custom-dockerfile/) is outdated. In the meantime, context was added to the docker-compose.yaml pointing to the root so the ADD directive is relative to the project root and not longer relative to the Dockerfile. Therefor `.ddev/web-build/` must be prepended.

**Comment by rfay** [comment]
Thanks for catching that!

**Comment by rfay** [comment]
Oh, I see, didn't realize this was ddev.com. @mattstein I imagine this is in your court at this moment? Or it's possible that the ddev.com article should just point to docs.

**Comment by mattstein** [comment]
Only sort of @rfay: the [article exists in that form](https://ddev.m7n.io/blog/customizing-ddev-local-images-with-a-custom-dockerfile/) with minor changes to its formatting. If it’s harmful to keep that old post around, I can delete it and redirect to https://ddev.readthedocs.io/en/latest/users/extend/customizing-images/.

That also [begs the question](https://github.com/orgs/ddev/projects/3?pane=issue&itemId=19458667) of what older posts should be pruned, vs. preserved for historical value. I’m not in the best position to decide, so I’ve only migrated posts unless we’ve explicitly agreed to remove them.

**Comment by rfay** [comment]
If you think there's value in that article (different approach) then we can keep it. Otherwise, we should drop it. I also replied in https://github.com/orgs/ddev/projects/3?pane=issue&itemId=19458667

**Comment by mattstein** [comment]
@gilbertsoft Am I correct if I think it’s this specific line that needs updating?

```
ADD mailhog.conf /etc/supervisor/conf.d
```

And that it should be:

```
ADD .ddev/web-build/mailhog.conf /etc/supervisor/conf.d
```

?

**Comment by rfay** [comment]
Yes, that is correct @mattstein - And I think that's likely one of the articles that got moved into the docs...

And the same error exists in https://ddev.readthedocs.io/en/latest/users/extend/customization-extendibility/#explicit-supervisord-configuration-for-additional-daemons

I expected to see the same error on https://ddev.readthedocs.io/en/latest/users/extend/customizing-images/#extending-configyaml-with-custom-configyaml-files but it must have gotten migrated out of there maybe into the above error.

**Comment by mattstein** [comment]
Sorry for the wait on this!

I’ve [submitted a PR](https://github.com/drud/ddev/pull/4666) for the docs to fix the example @rfay pointed out, updated the referenced WordPress post, and [updated that same post](https://github.com/ddev/ddev.com-front-end/commit/65bb831b19317f6d864f8a851759effce03570ff) on the in-development site and used the built-in update note to call out the change:

![Screen Shot 2023-02-21 at 02 19 20 PM@2x](https://user-images.githubusercontent.com/2488775/220471711-5bd8db09-911e-4a8f-b562-5104210ea048.png)

Let me know if I missed anything, otherwise this is safe to close when the docs PR is merged.

**Comment by rfay** [comment]
I believe this was fixed in @mattstein 's PR and the new ddev.com.

**Comment by mattstein** [comment]
Yep! The [PR was merged](https://github.com/ddev/ddev/pull/4666) and the updated post [is live on the new site](https://ddev.com/blog/customizing-ddev-local-images-with-a-custom-dockerfile/).
