### ISSUE TITLE
Laravel 10 requires PHP 8.1

### ISSUE THREAD

**Issue by tyler36** [ddev/ddev#4651]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Run a Diagnostic and Paste Link Here

Laravel 10 was released today.

When trying to follow the quick start guide, I recieved the following warning:

```shell
$ ddev composer create --prefer-dist --no-install --no-scripts laravel/laravel
...
Cannot use laravel/laravel's latest version v10.0.0 as it requires php ^8.1 which is not satisfied by your platform.
Installing laravel/laravel (v9.5.2)
  - Downloading laravel/laravel (v9.5.2)
  - Installing laravel/laravel (v9.5.2): Extracting archive
```

### Expected Behavior

- Latest Laravel version is installed
- DDEV project sets PHP `8.1`

### Actual Behavior

Laravel `9.5.2` is install because DDEV defaults to PHP `8.0` for `laravel` project.

### Steps To Reproduce

1. Create project folder

```shell
mkdir my-laravel-app
cd my-laravel-app
```

2. Configure DDEV

```shell
ddev config --project-type=laravel --docroot=public --create-docroot
```

3. Install Laravel
```shell
$ ddev composer create --prefer-dist --no-install --no-scripts laravel/laravel
...
Cannot use laravel/laravel's latest version v10.0.0 as it requires php ^8.1 which is not satisfied by your platform.
Installing laravel/laravel (v9.5.2)
  - Downloading laravel/laravel (v9.5.2)
``` 

### Anything else?

The following is the corrrect `ddev config` command to create a Laravel 10 project.

```shell
$ ddev config --project-type=laravel --docroot=public --create-docroot --php-version=8.1
```

How would you prefer to handle this:

- Different project types similar to Drupal. IE. `laravel9`,  `laravel10`
- Update default PHP to `8.1` for Laravel projects and update docs to specify lower PHP versions for lower Laravel versions

Other than this single PHP change, the quickstart guide results in a successful DDEV / laravel 10 project.

**Comment by rfay** [comment]
We can fix the quickstart, but also can change the default PHP for laravel,

**Comment by rfay** [comment]
Please see what you think of 
* #4653

Related: 
* #4652

**Comment by Abusayedpiash** [comment]
Cannot use laravel/laravel's latest version v10.2.6 as it requires php ^8.1 which is not satisfied by your platform.

**Comment by rfay** [comment]
@Abusayedpiash if you're using DDEV...

You need to change your project's PHP ersion to 8.1. `ddev config --php-version=8.1`

The current recipe does automatically provide 8.1

**Comment by mohammadrezaordooni** [comment]
Hi, if you have this error : Cannot use laravel/laravel latest version v10.2.6 as it requires php ^8.1 which is not satisfied by your platform.
and you intalled php version properly 
you must set php version in your phpstorm
when you set php version in phpstorm settings you must close the program and then open it and try composer create-project laravel/laravel again
good luck.

**Comment by rfay** [comment]
Hi @mohammadrezaordooni - I think you're leading people astray. This is the DDEV issue queue, where all you have to do is change the PHP version in the DDEV config, for example, `ddev config --php-version=8.1`. You're also way off topic, as this issue was about changing the Laravel Quickstart for DDEV.
