### ISSUE TITLE
Change PHP Default version to 8.1 in v1.22.0

### ISSUE THREAD

**Issue by rfay** [ddev/ddev#4652]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

PHP 8.1 should probably be the default PHP version when next major version (v1.22) comes out.

**Comment by rogoit** [comment]
I also want this. Now its 8.0.

**Comment by rfay** [comment]
I know you know @rogoit that DDEV supports 8.1 and 8.2 already and has for 6 months or more. `ddev config --php-version=8.1` is all it takes for any project. This issue is only about the default for project types that don't have a project type override.

**Comment by rogoit** [comment]
...default 8.2 ;) for open source passion. Keep strong my friend.
