### ISSUE TITLE
Traefik router should become default router in v1.22

### ISSUE THREAD

**Issue by rfay** [ddev/ddev#4679]
### Expected Behavior

In DDEV v1.22, traefik should become the default router.

- [ ] Make it the default
- [ ] Move it out of the experimental section of ddev docs
- [ ] Explain how to use the traditional router
- [ ] Perhaps explain about casual hosting not supported directly by traefik. It's already explained, but will likely have to be reworded.
- [ ] We probably have to change (and migrate) the configuration of `use_traefik: true` and instead use something like `router_type: traefik` or `router_type: traditional`

**Comment by rfay** [comment]
This one is a lot easier than the other one. It's probably a one-liner.

**Comment by allanlaal** [comment]
why did a breaking change get a minor release number? :|

**Comment by rfay** [comment]
Well @allanlaal that stings.

* If the change to Traefik broke you, please open an issue explaining how so it can be addressed.
* Traefik was available as an option for 8 months and was widely tested.
* If you'd like to use the legacy router, `ddev config global --router=nginx-proxy`
* v1.22.0 is a major release, with the changes widely announced.

**Comment by allanlaal** [comment]
sorry for expecting everyone is using Semantic Versioning :)

..you should though :D
