### ISSUE TITLE
Feature request: config allow override for local setup

### ISSUE THREAD

**Issue by calien666** [ddev/ddev#4702]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

For set up a local test via phpunit it's needed to adjust the php version for different test cases.

Doing this in a script would be nice, but for this, it's useful to adjust the config.local.yaml for changing parameters without changing the default ddev setup.

Currently no possibility exists to override this file via command but doing manually, which is a blocker on testing automatic inside ddev.

### Describe your solution

Analogous to `ddev config global`, there should be the possibility to manipulate `config.local.yaml` by means of `ddev config local` in order to be able to display various scenarios automatically in scripts.

### Describe alternatives

Current workaround is setting `ddev config --php-version x.x` and after testing `git reset` on .ddev/config.yaml.

### Additional context

Working with ddev for developing TYPO3 and TYPO3 extensions is great. In the case of TYPO3 extensions, it is necessary to be able to test several TYPO3 versions in different PHP versions. In order to run the tests automatically within ddev, it is currently necessary to adjust the PHP version manually in `config.local.yaml`.

Working with latest TYPO3 versions means following PHP versions to test:

| PHP | TYPO3 v11 | TYPO3 v12 |
|-----|------------|------------|
| 7.4 |  x | - |
| 8.0 | x | - |
| 8.1 | x | x |
| 8.2 | x | x |

Changing the PHP version in config.yaml can cause the change to be incorrectly checked into the versioning.

**Comment by rfay** [comment]
Did you know that all the various php versions are in there, and that you can change the default with `update-alternatives --set php /usr/bin/php<version>`

And that /usr/bin/php7.4, /usr/bin/php8.0, etc are just sitting there?

Here's what DDEV does on startup based on the version declared. Could you do this in your tests?

https://github.com/drud/ddev/blob/2ac9c5a47ed6fb10fa81328432f6f4c16e56c5e6/containers/ddev-webserver/ddev-webserver-base-scripts/start.sh#L23-L27
