### ISSUE TITLE
Allow add-ons to declare other add-ons as dependencies

### ISSUE THREAD

**Issue by hanoii** [ddev/ddev#4717]
I created a few addons (and sometimes I used others) and I thought it might be good to have a way to bundle add-ons so one can do ddev get xxx/add-ons and get a bunch at once.

One potentially nice way of doing it is with the ability of an addon to declare dependencies, so one would do the usual ddev get and if more dependencies are included, ddev could run ddev get on each. All GH, https and local add-ons can be supported, namely the same as running ddev get locally? I just thought that it can now maybe be done using post actions, but this is declaratively better.

Just an idea.

**Comment by rfay** [comment]
It's a good idea. ddev-redis-commander requires ddev-redis. Added the label to group it with the other items in this class. https://github.com/ddev/ddev/labels/addon%20mechanism

**Comment by rfay** [comment]
I don't agree that this was fixed in #4724 , reopening.

**Comment by rfay** [comment]
I think a strategy here might be to *declare* dependencies without actually managing them. So for example, if ddev-redis-commander has a dependency on ddev-redis, when you `ddev get ddev/ddev-redis-commander` it looks for `ddev-redis` and if it doesn't find it already installed, it gives an error message.
