### ISSUE TITLE
ddev/ddev migration cleanup items

### ISSUE THREAD

**Issue by rfay** [ddev/ddev#4718]
List things we need to check to confirm all phases are complete and we’re totally done with the `drud` to `ddev` migration.

@rfay should probably list out the tasks ahead of time so that several of us can run through them when it’s time.

- [x] completed transition [has been announced](https://github.com/orgs/ddev/projects/1/views/2?pane=issue&itemId=19457771)

## Repository Inventory

All non-archived repositories, including forks:

| Repository | Status |
| -- | -- |
| `drud/awesome-ddev` | part of [this task](https://github.com/orgs/ddev/projects/1/views/1?itemId=19457714&pane=issue) ✅ |
| `drud/build-tools` | archived 🔒 |
| `drud/d9simple-artifacts` | migrated ✅ |
| `drud/d9simple` | migrated ✅ |
| `drud/ddev-addon-template` | part of [this task](https://github.com/orgs/ddev/projects/1/views/1?pane=issue&itemId=19457699) ✅ |
| `drud/ddev-adminer` | part of [this task](https://github.com/orgs/ddev/projects/1/views/1?pane=issue&itemId=19457699) ✅ |
| `drud/ddev-beanstalkd` | part of [this task](https://github.com/orgs/ddev/projects/1/views/1?pane=issue&itemId=19457699) ✅ |
| `drud/ddev-browsersync` | part of [this task](https://github.com/orgs/ddev/projects/1/views/1?pane=issue&itemId=19457699) ✅ |
| `drud/ddev-contrib` | part of [this task](https://github.com/orgs/ddev/projects/1/views/1?itemId=19457714&pane=issue) ✅ |
| `drud/ddev-cron` | part of [this task](https://github.com/orgs/ddev/projects/1/views/1?pane=issue&itemId=19457699) ✅ |
| `drud/ddev-drupal9-solr` | part of [this task](https://github.com/orgs/ddev/projects/1/views/1?pane=issue&itemId=19457699) ✅ |
| `drud/ddev-elasticsearch` | part of [this task](https://github.com/orgs/ddev/projects/1/views/1?pane=issue&itemId=19457699) ✅ |
| `drud/ddev-gitpod-launcher` | migrated ✅ |
| `drud/ddev-management` | migrated ✅ |
| `drud/ddev-memcached` | part of [this task](https://github.com/orgs/ddev/projects/1/views/1?pane=issue&itemId=19457699) ✅ |
| `drud/ddev-mongo` | part of [this task](https://github.com/orgs/ddev/projects/1/views/1?pane=issue&itemId=19457699) ✅ |
| `drud/ddev-pdfreactor` | part of [this task](https://github.com/orgs/ddev/projects/1/views/1?pane=issue&itemId=19457699) ✅ |
| `drud/ddev-platformsh` | part of [this task](https://github.com/orgs/ddev/projects/1/views/1?pane=issue&itemId=19457699) ✅ |
| `drud/ddev-proxy-support` | part of [this task](https://github.com/orgs/ddev/projects/1/views/1?pane=issue&itemId=19457699) |
| `drud/ddev-pull-git-test-repo` | migrated ✅ |
| `drud/ddev-puppeteer` | migrated ✅ |
| `drud/ddev-redis-commander` | part of [this task](https://github.com/orgs/ddev/projects/1/views/1?pane=issue&itemId=19457699) ✅ |
| `drud/ddev-redis` | part of [this task](https://github.com/orgs/ddev/projects/1/views/1?pane=issue&itemId=19457699) ✅ |
| `drud/ddev-selenium-standalone-chrome` | part of [this task](https://github.com/orgs/ddev/projects/1/views/1?pane=issue&itemId=19457699) ✅ |
| `drud/ddev-test-php-repo` | migrated ✅ |
| `drud/ddev-ui` | migrated with Drud references ⚠️ |
| `drud/ddev-varnish` | part of [this task](https://github.com/orgs/ddev/projects/1/views/1?pane=issue&itemId=19457699) ✅ |
| `drud/ddev.com-build` | part of [this task](https://github.com/orgs/drud/projects/56/views/1?pane=issue&itemId=19452802) ✅ |
| `drud/ddev.com-front-end` | part of [this task](https://github.com/orgs/drud/projects/56/views/1?pane=issue&itemId=19452802) ✅ |
| `drud/ddev_test_tarballs` | migrated ✅ |
| `drud/ddev` | part of [this task](https://github.com/orgs/ddev/projects/1?pane=issue&itemId=19457730) ✅ |
| `drud/ddevdotcom` | To be retired. |
| `drud/docker-gen` | part of [this task](https://github.com/ddev/ddev/issues/4701) |
| `drud/forego` | part of [this task](https://github.com/ddev/ddev/issues/4701) |
| `drud/golang-build-container` | archived 🔒 |
| `drud/gsudo` | part of [this task](https://github.com/ddev/ddev/issues/4701) |
| `drud/homebrew-ddev-edge` | part of [this task](https://github.com/orgs/ddev/projects/1?pane=issue&itemId=19457728) ✅ |
| `drud/homebrew-ddev` | part of [this task](https://github.com/orgs/ddev/projects/1/views/1?pane=issue&itemId=19457728) ✅ |
| `drud/junk-test-pr-comment` | deleted 🗑️ |
| `drud/junk-test-workflows` | deleted 🗑️ |
| `drud/linuxbrew-ddev` | archived 🔒 |
| `drud/localdev.foundation` | migrated ✅ |
| `drud/MailHog` | part of [this task](https://github.com/ddev/ddev/issues/4701) |
| `drud/makensis` | archived 🔒 |
| `drud/mysql-arm64-images` | migrated with Drud references ⚠️ |
| `drud/nssm` | part of [this task](https://github.com/ddev/ddev/issues/4701) |
| `drud/quicksprint` | archived 🔒 |
| `drud/signing_tools` | migrated ✅ |
| `drud/style.ddev.com` | archived 🔒 |
| `drud/sudo` | archived 🔒 |
| `drud/temp-selfhostedrunner-test` | deleted 🗑️ |
| `drud/test-private-composer-repo` | deleted 🗑️ |
| `drud/toc` | deleted 🗑️ |
| `drud/typo3-v9-test` | archived 🔒|
| `drud/vault_migrate` | deleted 🗑️ |
| `drud/vault_token_lister` | deleted 🗑️ |
| `drud/wordpress` | migrated ✅ |
| `drud/xtrabackup-build` | migrated with Drud references ⚠️ |
| `drud/xtradb-arm64` | migrated ✅ |

**Comment by rfay** [comment]
Added ddev/wordpress to 
* https://github.com/ddev/ddev/issues/4701

**Comment by tyler36** [comment]
Apologies if this is not the right issue. Are the container names part of the migration?
Eg. `drud/ddev-webserver:v1.21.5-....build`

![drud-containers](https://user-images.githubusercontent.com/7234392/223884726-a589c336-3e2b-48f6-8f8a-04827afdece1.png)

**Comment by rfay** [comment]
@tyler36 when a project starts, it adds a few things to an image, like the username inside the image, possibly extra packages, etc. Those are bundled into an image named <basename>-<projectname>-built.  That's what you're seeing. And no, it has nothing to do with this issue if I understand your question.

In your image, you seem to have a bunch of dead containers that would be worth cleaning up, either via Docker Desktop UI, or `docker rm -f $(docker ps -aq)`

**Comment by tyler36** [comment]
They are not dead containers, just projects thats aren't up at the moment. 

I thought we were migrating from `drud/...` namespace to `ddev/...` so my expectation was the contains should also be rename. 
Eg. `drud/ddev-dbserver-mariadb-10.4:v1.21.5`  =>  `ddev/ddev-dbserver-mariadb-10.4:v1.21.5`

**Comment by rfay** [comment]
TODO SUMMARY:

- [x] xtrabackup-build drud->ddev https://github.com/ddev/xtrabackup-build/pull/5
- [x] drud/mysql-arm64-images https://github.com/ddev/mysql-arm64-images/pull/5

Other things are handled in 
* https://github.com/ddev/ddev/issues/4262 (in progress)
* https://github.com/ddev/ddev/issues/4701

I think we're good here.
