### ISSUE TITLE
Custom container with VIRTUAL_HOST set to a *.localhost domain blocks ddev_router from starting

### ISSUE THREAD

**Issue by stefanospetrakis** [ddev/ddev#4725]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Run a Diagnostic and Paste Link Here

https://gist.github.com/stefanospetrakis/c182419fc951e20b2d5e15867a43cd9c

### Expected Behavior

That the ddev_router would start, unobstructed by a custom container that runs independently of ddev.

### Actual Behavior

ddev_router did not start.

### Steps To Reproduce

1. `docker run -it -p8123 -e VIRTUAL_HOST=sth.localhost alpine sh` (in a different terminal, that will give us the running blocking container)
2. Create a new project, as in `mkdir -p /tmp/d10blockedrouter && cd /tmp/d10blockedrouter && ddev config --project-type=drupal10 && ddev start`

The `ddev start` step will fail due to ddev_router being blocked. By removing the blocking container or even more precisely by removing the VIRTUAL_HOST definition, the ddev_router can start normally.
 
0. `ddev poweroff`
1. `docker run -it -p8123 alpine sh`
2. `mkdir -p /tmp/d10blockedroutersuccess && cd /tmp/d10blockedroutersuccess && ddev config --project-type=drupal10 && ddev start`

This time things work as expected and ddev_router starts.

### Anything else?

Tried this with different wildcard subdomains that resolve to 127.0.0.1 (e.g. sth.lvh.me), the simplest case was sth.localhost

**Comment by stefanospetrakis** [comment]
May be distantly related to #1237

**Comment by rfay** [comment]
Thanks so much for including the `ddev debug test`.

I have no idea what you're trying to accomplish. Could you say? Are you trying to use VIRTUAL_HOST for something? I think the traditional router will listen for all container starts and try to act on them, and look at VIRTUAL_HOST and HTTP_EXPOSE. Not sure. Probably it should only listen to containers that have the com.ddev.site-name label.

Could you please try the Traefik router and see if it gives you this trouble? It will be default in DDEV v1.22.0. `ddev config global --use-traefik`

Your title implies that this has something to do with VIRTUAL_HOST=*.localhost, but I don't see anything of the type in your repro steps.

**Comment by stefanospetrakis** [comment]
Appreciate the eyes on this!

I was not trying to do anything fancy, I swear. :-)
I had a running custom container that was supposed to be talking with a custom router (off of jwilder/nginx-proxy) at times, but also was using without a localhost domain.
Then I simply started a new ddev project and the ddev_router never started as reported.

I updated the issue a little bit, you are right, I used different localhost-resolving domains, including *.localhost. This should be consistent now, including the repro steps.

I can confirm that switching to using traefik allows for starting my ddev project without any issues. Solved I guess?

**Comment by rfay** [comment]
Yeah, ddev-router is a derivative of jwilder/nginx-proxy, and it works by listening to all docker activity (mounting the docker socket into the container). That is a pretty horrible security problem, because it means that any attack on that container owns the host machine. That's one of many reasons that the traefik router will be ddev-router by default. And of course, the ddev-router fork being unmaintainable and hard to understand. 

But yes, since this is so obscure, and since the future path has it solved, let's go with closing this if you're OK with that.

**Comment by rteijeiro** [comment]
Same issue here due to having another project (not ddev) in docker and ddev_router added it as part of the virtual hosts config. Switching to Traefik `ddev config global --use-traefik` did the job but now I must create the ssl certificates myself I guess. Thanks for the tip!

**Comment by rfay** [comment]
What SSL certs to you have to create @rteijeiro ?

**Comment by rteijeiro** [comment]
The ones for the ddev-webserver host so I can use https with a drupal project. I assume I must create them manually using certbot, right? I found this doc page mentioning Traefik but maybe there is more info somewhere else: https://ddev.readthedocs.io/en/latest/users/extend/custom-tls-certificates/

**Comment by rfay** [comment]
@rteijeiro for local development everything works as it always has using traefik. I use it all the time. The mkcert certs are used automatically, there are no changes. If you are doing actual live casual hosting and you want to use traefik, then yes, you need real certs and you'll need to install them.

**Comment by rteijeiro** [comment]
Perfect! I run `mkcert -install` and after `ddev poweroff` and `ddev start` everything works like a charm. Thanks a lot @rfay :)
