### ISSUE TITLE
v1.21.5: Large projects with many mounted files take way too long to start

### ISSUE THREAD

**Issue by rfay** [ddev/ddev#4727]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected Behavior

`ddev start` shouldn't be slower than it was in v1.21.4

### Actual Behavior

With huge projects, particularly with projects that have mounted components as @mkalkbrenner and @cspitzlay have, the `ddev start` time can degenerate to an hour and a half startup time. 

We studied this and found that the `~/.ddev/bin/docker-compose -f .ddev/.ddev-docker-compose-full.yaml up --build -d` step hung for the 90 minutes. Without the `--build -d` it did not. 

Our analysis said that what's happening is that the docker context is being built there for the build. And in v1.21.5, the docker build context includes the entire project. Which in their case includes more thousands of files than even an ordinary modern PHP project. And many thousands of them are mounted on remote filesystems. The result is that the docker build stage is going through the entire mess and copying them into the docker context.

This change was made in 
* https://github.com/ddev/ddev/pull/4549

but that PR did two different changes, so the custom Dockerfile thing will have to be redone to go back to the previous behavior.

**Comment by mkalkbrenner** [comment]
After a lot of debugging, it turned out that #4728 doesn't fix the issue.
The problem is caused by the new version of docker-compose 2.16.0 which used by ddev 1.21.5.

ddev 1.21.5 works fine with docker-compose versions from 2.14.0 to 2.15.1.

So the workaround for us is
`ddev config global --required-docker-compose-version=v2.15.1`

**Comment by tkieslich** [comment]
Another reason to revert this is that in large Projects without .dockerignore in. root folder the build Process is very long.
If a .dockerignore File in root in most cases the .ddev Folder is excluded. You can allow the ddev web-build folder. But this is not a clean Solution.

**Comment by tkieslich** [comment]
I don't check the long build Process, but in two Projects the ddev build process failed. Because .ddev was in the .dockerignore in root for Live Deployment. Add !.ddev/web-build to this File is not a Clean Solution.
But it works.

**Comment by rfay** [comment]
@mkalkbrenner I assume that v1.21.6 fixed your problem right? Do please spend some time figuring out a repro case so we can solve the docker-compose problem.

**Comment by deviantintegral** [comment]
For anyone who had started to use the ability to copy in files from anywhere in your project in 1.21.5, you can still do this in 1.21.6 via a pre-start hook:

For example, in `config.yaml`:

```yaml
hooks:
  pre-start:
    - exec-host: |
        if [[ -f .ddev/web-build/Dockerfile.playwright ]]
        then
          rm -rf .ddev/web-build/playwright
          cp -r test/playwright .ddev/web-build/
        fi
```

And then any files in web-build can be used as the source in COPY commands or `--mount=type=bind` like:

```
RUN --mount=type=bind,source=./playwright,target=/playwright \
  && cp -a /playwright ...
```

**Comment by rfay** [comment]
That looks like a good technique, and leaves the whole thing in the hands of the user, thanks for sharing it.

**Comment by rfay** [comment]
@mkalkbrenner Here's hoping that you have caught up and got a launch done. I really would like to have this solved, will have to give up on the problem if we can't recreate it at some point. Now we're getting within a month or two of major release, and so it's getting late to figure out how to solve this in docker-compose land.

**Comment by rfay** [comment]
After many months I guess it's time to go ahead and catch up with docker-compose 2.18.0, done in 
* #4917

If you want to participate in getting your issue solved @mkalkbrenner this will be a good time.

**Comment by rfay** [comment]
This hasn't ever been demonstrated or any option provided to demonstrate it, so closing for now. Happy to continue the conversation here or elsewhere. v1.22.0 will have the newer docker-compose.
