### ISSUE TITLE
Move sponsorship from "rfay" to the "ddev" org on GitHub

### ISSUE THREAD

**Issue by rfay** [ddev/ddev#4748]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

Sponsorship is currently done via the "rfay" user. But now that we've landed at github.com/ddev/ddev, it's time to set up sponsorship on the org, so it's not so confusing. And of course, sponsorship funds don't go to rfay, they go to the Localdev Foundation for funding work outside rfay's work.

### Describe your solution

- [x] Open up sponsorship on ddev/ddev. This requires a new application on GitHub
- [x] Change the "sponsor this project" to point to it
- [x] Update the sponsorship details
- [x] Send an email to existing sponsors asking them to move (and consider increasing their sponsorship)
- [x] Mention that invoiced support contracts are also available

**Comment by rfay** [comment]
I have submitted the request to GitHub to enable sponsorships on ddev org.

Next steps:
- [ ] Change "Sponsor this project" to ddev org
- [ ] Email to current sponsors asking them to move to ddev org
- [ ] Email needs to explain that we can do ACH and can also bill them.
- [ ] Help them understand if they're sponsoring at the right level.

**Comment by rfay** [comment]
Sponsorship is live, although not announced. It's at https://github.com/sponsors/ddev

We can follow the instructions at https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository to do a funding.yml that shows for all repos.

@mattstein there's a little complex thing that's going to happen here. We're going to have sponsors on both rfay and ddev, and we'd prefer to show both of them (the sum of them). That sounds complicated on the https://ddev.com/support-ddev/ "Sponsor development" section.

**Comment by mattstein** [comment]
If it’s a matter of querying a second set of sponsorships and merging the results, it should be a straightforward thing to do [here](https://github.com/ddev/ddev.com-front-end/blob/main/src/lib/api.ts#L58-L95). That’s where the [landing](https://ddev.com/#supporters) and [Support DDEV](https://ddev.com/support-ddev/) pages both get their sponsor data.

**Comment by rfay** [comment]
I think we're close enough now with this, so I'm going to close it.

But @mattstein could you please review https://github.com/sponsors/ddev and make your suggestions about how to improve it?

**Comment by rfay** [comment]
Reopening for suggestions from anyone including @mattstein

**Comment by mattstein** [comment]
> But @mattstein could you please review https://github.com/sponsors/ddev and make your suggestions about how to improve it?

Sure! I’d probably make a bunch of small edits to sharpen what’s there into something more brief. To me, though, it feels like the page describes where funds go but not necessarily where DDEV is going. As a potential sponsor, I might be more motivated to contribute if I know I can help the organization or product toward specific goals.

Happy to suggest edits, but we surely don’t want me making up higher-level goals.

**Comment by rfay** [comment]
Why don't you suggest edits on https://gist.github.com/rfay/2772ea8209896b169ef9ddb2f0db6374#file-sponsors-md - 

I appreciate the suggestion about specific goals, it's a worthy conversation but like you say probably needs a different starting point.

**Comment by rfay** [comment]
Thanks for the great edit/writing @mattstein . I put that in place and also updated https://github.com/sponsors/rfay to point people there. Let me know if you would like anything better there.

I think we have this one.
