### ISSUE TITLE
FATA[0000] unable to read global config: use-letsencrypt is not directly supported with traefik. but can be configured with custom config, see https://doc.traefik.io/traefik/https/acme/

### ISSUE THREAD

**Issue by mdance** [ddev/ddev#4749]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Run a Diagnostic and Paste Link Here

FATA[0000] unable to read global config: use-letsencrypt is not directly supported with traefik. but can be configured with custom config, see https://doc.traefik.io/traefik/https/acme/

### Expected Behavior

I just updated ddev and now I can't run anything or start any projects, all it is reporting is:

FATA[0000] unable to read global config: use-letsencrypt is not directly supported with traefik. but can be configured with custom config, see https://doc.traefik.io/traefik/https/acme/

### Actual Behavior

FATA[0000] unable to read global config: use-letsencrypt is not directly supported with traefik. but can be configured with custom config, see https://doc.traefik.io/traefik/https/acme/

### Steps To Reproduce

Even running ddev from my home directory is reporting this error

**Comment by mdance** [comment]
Looks like I've got ddev-edge-bin 1.21.6-1 http://aur.archlinux.org/packages/ddev-edge-bin

**Comment by rfay** [comment]
Please turn off Let's Encrypt. `ddev config global --use-letsencrypt=false --letsencrypt-email="". 

Or turn off Traefik, `ddev config global --use-traefik=false`

They're mutually incompatible. If you can't figure out how to do it just go into your ~/.ddev/global_config.yaml and remove all the settings for letsencrypt or traefik. Or just `ddev poweroff` and delete your ~/.ddev/global_config.yaml

**Comment by rfay** [comment]
No response from @mdance but the comment explains what to do. https://github.com/ddev/ddev/issues/4749#issuecomment-1467297655

I'd love to have you explore how to do this with the traefik router.  And I'd love to hear what you were doing. Were you using DDEV's Casual Hosting? 

Closing, happy to continue the conversation here or elsewhere.

**Comment by peni4142** [comment]
The command `ddev config global --router=nginx-proxy` fixed it for me. I need "Let's Encrypt" because I do not know Traefik,

**Comment by rfay** [comment]
The current HEAD of DDEV works fine with the traefik router. It just arrived in v1.23.4, but there was a bug in 1.23.4, now fixed in head. I'm running my let's encrypt with HEAD at this point. 

To use HEAD: https://ddev.readthedocs.io/en/stable/developers/building-contributing/#testing-latest-commits-on-head

To configure, docs in "latest": https://ddev.readthedocs.io/en/latest/users/topics/hosting/

**Comment by peni4142** [comment]
The command `ddev config global --router=nginx-proxy` fixed it for me. I need "Let's Encrypt" because I do not know Traefik.
