### ISSUE TITLE
Erorr ddev start after update 1.2.6

### ISSUE THREAD

**Issue by elrokket** [ddev/ddev#4755]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Run a Diagnostic and Paste Link Here

Hello, i updated ddev to last version but now i cant start projects, when i execute **ddev start** fire this message:

`The docker version currently installed does not seem to meet ddev's requirements: 19.3.12 is less than 20.10.0-alpha1
`
`failed to RunSimpleContainer to inspect database version/type: failed to create/start docker container ({GetExistingDBType-myproject-lRzWqX 0xc00025a1e0 0xc0000d8000 <nil> <nil>}):API error (400): invalid IP address in add-host: "host-gateway", output=`

### Expected Behavior

Start de project.

### Actual Behavior

start the project

### Steps To Reproduce

Update ddev to 1.2.6 with apt-get (ubuntu)
go to any project and execute **ddev start**

Fire this error

failed to RunSimpleContainer to inspect database version/type: failed to create/start docker container ({GetExistingDBType-myproject-lRzWqX 0xc00025a1e0 0xc0000d8000 <nil> <nil>}):API error (400): invalid IP address in add-host: "host-gateway", output=

**Comment by rfay** [comment]
Hi @elrokket - Could you please edit to include the output of `ddev debug test` as was requested?

It looks like this is probably a Docker problem rather than ddev, so please make sure you've restarted docker itself and even rebooted your computer. 

Following the [troubleshooting docs](https://ddev.readthedocs.io/en/latest/users/usage/troubleshooting/) may help you as well. Things like this are often firewall, vpn, etc.

**Comment by rfay** [comment]
Please share the .ddev/.ddev-docker-compose-full.yaml in tryddevproject-25256 - it would be a lot better as a gist or other pastebin, or as a textfile please.

**Comment by elrokket** [comment]
> 

Not exists

**Comment by rfay** [comment]
It's in the .ddev directory of every project. It's created on `ddev start`. You may not see it because you're on linux and dotfiles are hidden by default. `ls -a .ddev/.ddev*` will show it to you. Or just get me .ddev/.ddev-docker-compose-base.yaml.

**Comment by elrokket** [comment]
> It's in the .ddev directory of every project. It's created on `ddev start`. You may not see it because you're on linux and dotfiles are hidden by default. `ls -a .ddev/.ddev*` will show it to you. Or just get me .ddev/.ddev-docker-compose-base.yaml.

i cant start because is the error fired, only create /web folder

**Comment by elrokket** [comment]
Fixed, the problem is with 19 of docker, i updated with this command:

` sudo apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin`

and now are working, thanks and sorry for your time.

**Comment by rfay** [comment]
Glad it's working for you!
