### ISSUE TITLE
Traefik plugins breaking dynamic configuration loading

### ISSUE THREAD

**Issue by titouanmathis** [ddev/ddev#4758]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Run a Diagnostic and Paste Link Here

**Context:**

- ddev v1.21.5
- Traefik router enabled

### Expected Behavior

Adding a [plugin](https://plugins.traefik.io) to Traefik works.

### Actual Behavior

Adding a plugin to Traefik's static configuration results in the plugin files being downloaded in the `/mnt/ddev-global-cache/traefik/config` folder. If the plugin contains any YAML file, Traefik will try to load it as a dynamic configuration. 

As mentioned briefly in the [Traefik plugin docs](https://plugins.traefik.io/install), the plugins are downloaded in the current working directory, which is `/mnt/ddev-global-cache/traefik/config` for the Traefik based router.

### Steps To Reproduce

1. Add a plugin to Traefik in its static configuration `~/.ddev/traefik/static_config.yaml`: 

```yaml
experimental:
  plugins:
    htransformation:
      moduleName: "github.com/tomMoulard/htransformation"
      version: "v0.2.7"
```

2. Restart the ddev-router container
3. Traefik tries to load YAML files from the plugin as dynamic configuration

### Anything else?

I was able to fix this issue locally by editing the `~/.ddev/router-build/Dockerfile`:

```diff
  RUN apk add bash vim curl htop
- WORKDIR /mnt/ddev-global-cache/traefik/config
+ WORKDIR /mnt/ddev-global-cache/traefik
  
```

**Comment by rfay** [comment]
Impressive stuff! 

I see in your PR that you were trying to use github.com/tomMoulard/htransformation

Could you please use that as an example and explain what it was you were trying to do?

**Comment by titouanmathis** [comment]
Thanks :) 

I am using ddev for casual hosting to easily deploy preview environments for some projects. I use the `basic-auth` middleware which is available by default with Traefik and wanted to test passing a second `Authorization` header with the `Bearer` scheme. 

The objective was to switch the value of the `Authorization` header to pass the `Basic` scheme set up by the `basic-auth` middleware and then to restore the bearer token, so my application could read it from the `Authorization` header.

I ended up not using this solution as it was not working really well, but I figured I could send a PR as I had already fixed the issue while trying to implement it.

**Comment by rfay** [comment]
> Cloudflare's Flexible SSL configuration

Wow, could you say more about that? We're off-topic, but you've been exploring things that can be useful to lots of people.

**Comment by rfay** [comment]
Oh, you tried a wildcard in ~/.ddev/traefik/certs? 

The normal place (and tested place) would be in the project.

If you can reproduce that it's likely a bug, and another one of your careful issue reports would be welcome.

So you're using cloudflare to front your casual-hosted sites, and thus running http between the casual-hosted site and cloudflare? That's a great approach. A PR about that approach would be super welcome on https://ddev.readthedocs.io/en/latest/users/topics/hosting/

**Comment by titouanmathis** [comment]
> Oh, you tried a wildcard in ~/.ddev/traefik/certs?
> The normal place (and tested place) would be in the project.

I tried in the following places with no success:

-  `~/.ddev/traefik/certs` 
- `<PROJECT_PATH>/.ddev/traefik/certs/<PROJECT_NAME>.{crt,key}`
- `<PROJECT_PATH>/.ddev/custom_certs/<PROJECT_NAME>.{crt,key}`

I would need to find some time to re-test each option to open a detailed bug report. 

> A PR about that approach would be super welcome

Good idea, I'll try to open one in the next weeks.

**Comment by titouanmathis** [comment]
> Love to have you exploring this terrain. Not many people go there.

It turns out this is the fastest way for us to have working dev environments on a server without having to configure Traefik or docker-compose files. I'll be happy to send PR to the docs with my findings.
