### ISSUE TITLE
[docs] Magento 2 Quickstart doesn't work "couldn't validate opensearch"

### ISSUE THREAD

**Issue by bharatk101-dckap** [ddev/ddev#4762]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Run a Diagnostic and Paste Link Here

DDev Debug test file -  https://gist.github.com/bharatk101-dckap/1e66df93732d1da9f7722e2fbfacc437

### Expected Behavior

I installed ddev on my machine and used Magento 2 Quickstart steps to install latest Magento version but I got the error while setting up the magento. Magento setup should complete without any error

### Actual Behavior

![image](https://user-images.githubusercontent.com/49195030/225951296-ff151902-08ef-4991-b952-016bcc3d2663.png)

### Steps To Reproduce

1. Go to ['Magento 2 Quickstart'](https://ddev.readthedocs.io/en/latest/users/quickstart/#magento-2)
2. Run commands step by step
3. Run ddev magento setup command bin/magento setup:install  --db-host=db --db-name=db --db-user=db --db-password=db  --admin-firstname=Magento --admin-lastname=User --admin-email=user@example.com  --admin-user=admin --admin-password=admin123 --language=en_US

**Comment by rfay** [comment]
Thanks! It's too hard to look at your output as a screenshot, please edit to show the full output of the problem command, thanks! You could add it as a separate file in your gist if you want to as well.

**Comment by rfay** [comment]
I don't get as far as you got:
```
$ ddev magento setup:install --base-url='https://junk.ddev.site/' --cleanup-database --db-host=db --db-name=db --db-user=db --db-password=db --elasticsearch-host=elasticsearch --admin-firstname=Magento --admin-lastname=User --admin-email=user@example.com --admin-user=admin --admin-password=admin123 --language=en_US
Warning: require(/var/www/html/setup/config/application.config.php): Failed to open stream: No such file or directory in /var/www/html/vendor/magento/framework/Console/Cli.php on line 79
Failed to run magento setup:install --base-url=https://junk.ddev.site/ --cleanup-database --db-host=db --db-name=db --db-user=db --db-password=db --elasticsearch-host=elasticsearch --admin-firstname=Magento --admin-lastname=User --admin-email=user@example.com --admin-user=admin --admin-password=admin123 --language=en_US: exit status 1
```

**Comment by rfay** [comment]
@cmuench could you validate the quickstart and give us a little guidance here? Seems some things have shifted in Magento 2.4.6?

**Comment by rfay** [comment]
OK, I removed vendor dir and then did `ddev composer install` again, and now can get your error @bharatk101-dckap 

`  Could not validate a connection to the OpenSearch. No alive nodes found in your cluster`

**Comment by bharatk101-dckap** [comment]
<img width="1072" alt="image" src="https://user-images.githubusercontent.com/49195030/225974617-18474603-0b03-4ffb-bc89-ca992c2d6f3b.png">

Here's the error 
`[Progress: 663 / 1332]
[Progress: 664 / 1332]
Installing search configuration...

In SearchConfig.php line 81:
                                                                               
  Could not validate a connection to the OpenSearch. No alive nodes found in   
  your cluster       

Failed to run magento setup:install --base-url=https://docker.magento.com/ --cleanup-database --db-host=db --db-name=db --db-user=db --db-password=db --elasticsearch-host=elasticsearch --admin-firstname=Magento --admin-lastname=User --admin-email=bharatkulkarni@dckap.com --admin-user=admin --admin-password=admin@123 --language=en_US: exit status 1

 `

**Comment by cmuench** [comment]
@bharatk101-dckap Can you try to add the option `--search-engine=elasticsearch7`

**Comment by rfay** [comment]
I confirm that changing the quickstart to
`ddev magento setup:install --base-url='https://ddev-magento2.ddev.site/' --cleanup-database --db-host=db --db-name=db --db-user=db --db-password=db --elasticsearch-host=elasticsearch --admin-firstname=Magento --admin-lastname=User --admin-email=user@example.com --admin-user=admin --admin-password=admin123 --language=en_US --search-engine=elasticsearch7` 

makes it succeed.

**Comment by rfay** [comment]
However, then we get one step farther and 

```
$ ddev magento module:disable Magento_TwoFactorAuth
Unable to change status of modules because of the following constraints:
Cannot disable Magento_TwoFactorAuth because modules depend on it:
Magento_AdminAdobeImsTwoFactorAuth: Magento_AdminAdobeImsTwoFactorAuth->Magento_TwoFactorAuth
Failed to run magento module:disable Magento_TwoFactorAuth: exit status 1
```

What do we have to do to fix that @cmuench ? Thanks!

**Comment by cmuench** [comment]
The Magento_AdminAdobeImsTwoFactorAuth module was introduced in 2.4.6.
The following script work on my machine.

```bash
mkdir ddev-magento2 && cd ddev-magento2
ddev config --project-type=magento2 --php-version=8.1 --docroot=pub --create-docroot --disable-settings-management
ddev get ddev/ddev-elasticsearch
ddev start
ddev composer create --repository=https://repo.magento.com/ magento/project-community-edition -y
rm -f app/etc/env.php

# Change the base-url below to your project's URL
ddev magento setup:install --base-url='https://ddev-magento2.ddev.site/' --cleanup-database --db-host=db --db-name=db --db-user=db --db-password=db --elasticsearch-host=elasticsearch --search-engine=elasticsearch7 --elasticsearch-port=9200 --admin-firstname=Magento --admin-lastname=User --admin-email=user@example.com --admin-user=admin --admin-password=admin123 --language=en_US

ddev magento deploy:mode:set developer
ddev magento module:disable Magento_TwoFactorAuth Magento_AdminAdobeImsTwoFactorAuth
ddev config --disable-settings-management=false
```

I will create a pull request for the docs.
