### ISSUE TITLE
Missing folder setup during the Magento 2 quick install

### ISSUE THREAD

**Issue by SilinMykola** [ddev/ddev#4776]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Run a Diagnostic and Paste Link Here
The debug test file is [here](https://gist.github.com/SilinMykola/172a9e0e59be4c0916170cee9a820c16).
My Environment: 
1.  OS: Ventura 13.2.1
2.  Docker Desktop 4.17.0 (99724)

Hello for everyone! I tried to install Magento 2. After I ran the command `ddev composer create --repository=https://repo.magento.com/ magento/project-community-edition -y` I found out that not all nessesary files were downloaded. 
![image](https://user-images.githubusercontent.com/15772032/226680638-23435e28-3ad6-4eb2-b28f-bca5e341da86.png)
There is Setup folder is missing.
To check this I ran the command `composer create --repository=https://repo.magento.com/ magento/project-community-edition ./` in separate folder and got all needed files: 
![image](https://user-images.githubusercontent.com/15772032/226681020-b6c58e2d-c528-46a7-973d-163888439685.png)

### Expected Behavior

All needed files downloaded.

### Actual Behavior

The folder `setup` is messing.

### Steps To Reproduce

I tried to install by this instruction https://github.com/ddev/ddev/issues/4762#issuecomment-1474933594

1. `mkdir magento-246 && cd magento-246`
4. `ddev config --project-type=magento2 --php-version=8.1 --docroot=pub --create-docroot --disable-settings-management`
5. `ddev get ddev/ddev-elasticsearch`
6. `ddev start`
7. `ddev composer create --repository=https://repo.magento.com/ magento/project-community-edition -y`

**Comment by rfay** [comment]
You didn't tell us what environment you're in or any of that information. Could you please update and do the requested `ddev debug test` and provide the results as a gist on gist.github.com?

If you're using colima.. please enable mutagen.

Also, once you get past the composer failure, you'll want to see

* https://github.com/ddev/ddev/pull/4767

**Comment by SilinMykola** [comment]
@rfay Hello! Thank you for your response. I added the [file](https://gist.github.com/SilinMykola/172a9e0e59be4c0916170cee9a820c16) with debug test response and added the environment.
If I can help with something, please tell me.

**Comment by rfay** [comment]
Thanks so much for running the diagnostic. It helps so much.

Two things are likely to get you with `ddev composer install` in your situation:

1. You have enabled the experimental Virtiofs feature in Docker Desktop. I recommend disabling it.
2. With large `ddev composer install` having mutagen enabled helps loads. So `ddev config global --use-mutagen` and `ddev restart` may help.

And again, once you get past the composer failure, check the PR linked above to fix new problems introduced by magento 2.4.6.

**Comment by SilinMykola** [comment]
@rfay thanks for your help!
I changed the docker settings : 
![image](https://user-images.githubusercontent.com/15772032/227859509-82da876c-c336-4f7e-8928-b08bca138f02.png)
ran `ddev config global --mutagen-enabled`
after running the command `ddev composer create --repository=https://repo.magento.com/ magento/project-community-edition -y` I got an error 
![image](https://user-images.githubusercontent.com/15772032/227859736-788f0ba4-2940-4dd9-a8ef-8b9468e09368.png)
Sure, I can create this folder manually, but the folder setup still missing.
![image](https://user-images.githubusercontent.com/15772032/227860001-5d35d411-19a5-4694-bf65-a68bd9c2c97e.png)

**Comment by rfay** [comment]
I think you forgot to `ddev restart` after turning on mutagen.

**Comment by SilinMykola** [comment]
I made ddev restart after the config change. I deleted the folder and tried again. All commands that I ran:
1. `mkdir magento-246-ddev && cd magento-246-ddev`
2. `ddev config --project-type=magento2 --php-version=8.1 --docroot=pub --create-docroot --disable-settings-management`
3. `ddev get ddev/ddev-elasticsearch`
4. `ddev start`
5. `ddev config global --mutagen-enabled`
6. `ddev restart`
7. `ddev composer create --repository=https://repo.magento.com/ magento/project-community-edition -y`
![image](https://user-images.githubusercontent.com/15772032/228011509-a59844b8-ef89-4574-81ec-a984a33ca830.png)
8. `ddev ssh`
9.` ls -la pub`
![image](https://user-images.githubusercontent.com/15772032/228012230-43e556cd-45a0-4787-afbe-e159111b6a4f.png)

**Comment by rfay** [comment]
(Note that the `ddev config global --mutagen-enabled` only has to be done once. The issue is that after you do it projects have to be restarted for it to take effect. You didn't need to start-config-restart. )

**Comment by rfay** [comment]
I'm unable to recreate your results. Here's what I see with a Docker Desktop + Mutagen install:

https://gist.github.com/rfay/d4bffea09bc65d66e06d093ed2f8e4e2

However, you don't mention giving it the required credentials, but I think it would fail differently.

**Comment by rfay** [comment]
Did you figure out what the problem was?

**Comment by SilinMykola** [comment]
Not yet, I'll try to install the existing project.

**Comment by mihaimatei** [comment]
@SilinMykola, I've had missing setup folder from time to time, on other environments like warden or swiftotter/den, so it is not ddev specific. It is mostly due to a specific state of files in the folder in a combination with host/guest/mutagen/docker versions, which can be hard to debug. You can see more details about my encounter with this situation here: https://www.mihaimatei.com/magento-2-missing-setup-folder/

**Comment by rfay** [comment]
I think the discussion in https://github.com/ddev/ddev/pull/4767 may also explain this.
