### ISSUE TITLE
Docs for restoring snapshots incorrect

### ISSUE THREAD

**Issue by rintisch** [ddev/ddev#4778]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Run a Diagnostic and Paste Link Here

The docs about [restoring a snapshot](https://ddev.readthedocs.io/en/stable/users/usage/cli/#snapshotting-and-restoring-a-database) seem to be wrong.

It's said that 
```
ddev snapshot restore d9_20220107124831-mariadb_10.3.gz
```
would restore the snapshot. But that throws an error. I needs to be 
```
ddev snapshot restore d9_20220107124831 //without the database type, database number and file extension
```

Found the solution because ```ddev snapshot --list``` returns the correct pattern.

### Expected Behavior

Instruction to restore a snapshot like described should work

### Actual Behavior

The descriptions is wrong

### Steps To Reproduce

1. Create a snapshot
2. Input the full file name
3. See the error
4. Input file name without db type, db version and file extension
5. See that it works.

### Anything else?

By searching the docs in a rush i could not find them in the repository. If you confirm the error and give me a hint how to find the docs I could create a PR.

**Comment by rfay** [comment]
Thanks for pointing this out! If you want, you can click the pencil in the upper right of that page and fix this.

**Comment by rintisch** [comment]
@rfay Thanks for the hint, there you got the PR.
