### ISSUE TITLE
When importing a Craft database, I get `ERROR 3546 (HY000) at line 24: @@GLOBAL.GTID_PURGED cannot be changed: the added gtid set must not overlap with @@GLOBAL.GTID_EXECUTED`

### ISSUE THREAD

**Issue by Michael-Paragonn** [ddev/ddev#4780]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Run a Diagnostic and Paste Link Here

https://gist.github.com/Michael-Paragonn/e066db99a9500112032e43ceec519edd

### Expected Behavior

I expect to be able to export the Craft database from the live server, and import it into DDEV locally (WSL2 / Ubuntu).

### Actual Behavior

I get this error:

```bash
$ ddev import-db < ../craft-site-db-export--2023-03-22-153808--v3.7.53.1.sql 
mysql: [Warning] Using a password on the command line interface can be insecure. 
ERROR 3546 (HY000) at line 24: @@GLOBAL.GTID_PURGED cannot be changed: the added gtid set must not overlap with @@GLOBAL.GTID_EXECUTED 
Failed to import database db for ijmde: failed to import database: ComposeCmd failed to run 'COMPOSE_PROJECT_NAME=ddev-ijmde docker-compose -f /home/michael/projects/ijm/ijmde/ijmde-www-craft3/.ddev/.ddev-docker-compose-full.yaml exec -T db bash -c set -eu -o pipefail && mysql -uroot -proot -e "DROP DATABASE IF EXISTS db; CREATE DATABASE IF NOT EXISTS db; GRANT ALL ON db.* TO 'db'@'%';" && perl -p -e 's/^(CREATE DATABASE \/\*|USE `)[^;]*;//' | mysql db', action='[exec -T db bash -c set -eu -o pipefail && mysql -uroot -proot -e "DROP DATABASE IF EXISTS db; CREATE DATABASE IF NOT EXISTS db; GRANT ALL ON db.* TO 'db'@'%';" && perl -p -e 's/^(CREATE DATABASE \/\*|USE `)[^;]*;//' | mysql db]', err='exit status 1', stdout='', stderr='mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 3546 (HY000) at line 24: @@GLOBAL.GTID_PURGED cannot be changed: the added gtid set must not overlap with @@GLOBAL.GTID_EXECUTED'
stdout: 
stderr: mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 3546 (HY000) at line 24: @@GLOBAL.GTID_PURGED cannot be changed: the added gtid set must not overlap with @@GLOBAL.GTID_EXECUTED 
```

### Steps To Reproduce

1. Be me.
2. Have my issues.
3. Seriously, this normally would work perfectly. Not sure why it's borked now.

### Anything else?

The only other thing I can think of is that recently the site in question was moved to a bigger, better server. If that might be related to this issue, I can try to get exact details on the differences.

**Comment by rfay** [comment]
Could you please say what kind of database you're importing to, and the database type you're importing it to?  mariadb? mysql? What version? What is the source of your DB dump? It seems like this is an error in your dump.

Google says this might help you: https://stackoverflow.com/questions/38123263/cloud-sql-database-export-import-issue

**Comment by Michael-Paragonn** [comment]
Sorry, thought that info would be in the diagnostic data.

Exporting from MySQL 8.0.30 (according to Craft's internal System Report), or `mysql  Ver 8.0.32-0ubuntu0.22.04.2 for Linux on x86_64 ((Ubuntu))` (according to `$ mysql --version`).

Importing to MySQL 8.0 (according to the `.ddev/config.yaml`), or `mysql  Ver 8.0.26-0ubuntu0.20.04.3 for Linux on x86_64 ((Ubuntu))` (according to `$ ddev mysql --version`).

The source of the dump is the exact same process I always go through:
1. I SSH into the live server
2. Navigate to the directory where Craft is installed
3. Run `php craft db/backup --zip`
4. Download the file via WinSCP (because I can't be bothered to figure out curl) to my Windows machine. 
5. Open it in 7Zip
6. Extract the .sql file inside into the WSL2 directory where I have DDEV set up for this site's dev environment.
7. Open a terminal to the directory from step 6.
8. Run `ddev import-db < ../path-to-filename.sql`

**Comment by rfay** [comment]
That sounds pretty complex. I guess what you'll have to do is use the `root` user to do the import. Or you can grant the 'db' user the RELOAD privilege. Maybe that's the easiest. `ddev mysql -uroot -proot` and grant the privilege to `db@%`

**Comment by rfay** [comment]
And note that you don't have to ungzip the file; ddev import-db will happily do that for you. 

Oh, and maybe you can do the `RESET MASTER` with `ddev mysql -uroot -proot` and maybe that will get you farther?

**Comment by Michael-Paragonn** [comment]
Well, that allowed me to run a `RESET MASTER`, but the result was `Query OK, 0 rows affected (0.07 sec)`, and when trying the import again, it doesn't look like anything's changed.

It's perhaps worth noting that the exact error I'm getting is not the same as reported in that SO post.

> And note that you don't have to ungzip the file; ddev import-db will happily do that for you.

Good to know, thanks!

**Comment by rfay** [comment]
Since your dump requires unusual privileges to restore:

```
ddev mysql -uroot -proot
GRANT ALL ON *.* TO 'db'@'%';
FLUSH PRIVILEGES;
```

**Comment by Michael-Paragonn** [comment]
That seems to have fixed the issue, thanks!

My sysadmin will be making some modifications to the server to try and prevent this from recurring; to that end, what would I run to reverse these MySQL permission changes?

> And note that you don't have to ungzip the file; ddev import-db will happily do that for you.

I should have read this more carefully; the Craft GUI uses ZIP, not GZIP. No wonder I was getting an error when trying to import from the archive directly.
