### ISSUE TITLE
ddev pull doesn't store dumps anymore

### ISSUE THREAD

**Issue by bserem** [ddev/ddev#4782]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Run a Diagnostic and Paste Link Here

https://gist.github.com/bserem/115e563df4c1743ef49d3ad3ddb9b8bf

### Expected Behavior

Running `ddev pull platform --skip-files` I would expect the DB to imported **and** and gzipped dump to be saved under `.ddev/.downloads/db.sql.gz`

### Actual Behavior

Starting with v1.21.6 (might have happened earlier and I haven't noticed it)

Running `ddev pull platform --skip-files
- DB is downloaded:
  > Obtaining databases...
  > Creating gzipped SQL dump file: /var/www/html/.ddev/.downloads/db.sql.gz
 
- DB is imported
- Dump file is nowhere to be found

### Steps To Reproduce

1. Set a provider (I can verify it happens with platform and pantheon)
2. Run `ddev pull`
3. Check if file exists under `.ddev/.downloads`

**Comment by rfay** [comment]
It's true this was changed in v1.21.6, but the early removal (at end of the import) was unintentional. 

What happened was that people using mutagen were pulling huge databases, and then the database was left in .ddev/.downloads, so they were suffering super long `ddev start` times.

It was deliberate to remove it on `ddev start`, but unintentional to remove right after the pull. 

app.ImportDB() calls CreateSettingsFiles() at the end:

https://github.com/ddev/ddev/blob/f3b995c3591e479d57ddf3b47a159f2874505d2e/pkg/ddevapp/ddevapp.go#L675

And CreateSettingsFiles() calls PrepDdevDirectory(), which checks to see if the .downloads dir is there, and if so, deletes it.

**Comment by bserem** [comment]
Ah, that would explain why files that were downloaded and saved are suddenly gone :-)

To be honest, I am not using mutagen so I don't know of how big a problem we are talking about here.

It was a handy feature, I always liked having a DB that's one-two weeks old stored locally. I know we have revisions and such, but that dump over has been proven useful from time to time.

Can it be something that gets triggered if mutagen is enabled?
Or a setting/flag somehow on ddev config, whether to keep it or delete it?

In any case, it's easy to use `platform db:dump` instead of `ddev pull` so it's not a big deal. Feel free to close this as you see fit.

Thanks

**Comment by bserem** [comment]
Thanks for the tarballs tip.

The dumps were deleted when another `pull` was made. I am never pulling files so I never got into the scenario of ddev deleting the dumps (I've scripted stage_file_proxy with post-hooks to save the time and space).

**Comment by rfay** [comment]
Since `ddev pull` never did persist backups except in the case you are talking about (using --skip-files) I think I'll close this, but it may be worth helping people to understand how to get db backups in various situations with various hosting situations? I think you just relied on the particular behavior your experienced, but you know how to use `ddev platform db:dump`, so should be fine.
