### ISSUE TITLE
Persist ~/.composer/auth.json

### ISSUE THREAD

**Issue by jigarius** [ddev/ddev#4785]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected Behavior

If you have Composer packages that require an auth token, say, packages hosted on Gitlab, you need to run this following command to authenticate:

    ddev composer config --global --auth gitlab-token.gitlab.com {token}

With this, composer generates `~/.composer/auth.json`. Preferably, there should be a way to persist this file.

### Actual Behavior

Every time a Ddev container is restarted, this file is lost, so one has to repeatedly do the authentication.

As an alternatively, I tried creating `.homeadditions/.composer/auth.json` but the entire `.composer` directory is removed when I do `ddev restart`.

### Steps To Reproduce

1. Create an `auth.json` file in the `~/.composer` directory inside the `web` container.
2. Restart Ddev
3. The file is now lost.

**Comment by rfay** [comment]
Hi @jigarius - The directory you want to add things to is either the project homeadditions (`.ddev/homeadditions`) or the global homeadditions (`~/.ddev/homeadditions`). Not anyting called `.homeadditions`. 

Please try putting your auth.json in the project or global homeadditions/.composer/auth.json. 

This exact example is shown in https://ddev.readthedocs.io/en/latest/users/extend/in-container-configuration/

Please give that a try.

**Comment by rfay** [comment]
I hope that helps. Haven't heard a response from you but happy to continue the conversation here or elsewhere. Closing.

**Comment by jigarius** [comment]
I finally got back to this issue this morning. You're right. I put it in the wrong directory, i.e. the `.homeadditions`. Creating a `.ddev/homeadditions/.composer/auth.json` solved the issue. It was a code 18.
