### ISSUE TITLE
Improve environment variable handling

### ISSUE THREAD

**Issue by AronNovak** [ddev/ddev#4791]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected Behavior

Have a syntactically correct YAML configfile

### Actual Behavior

```
 aaron  ~  ddev
FATA[0000] unable to read global config: yaml: line 13: did not find expected '-' indicator
```

### Steps To Reproduce

```bash
echo 'text with , comma inside
and multiline' > message.txt
VAR=`cat message.txt`
/tmp/ddev config global --web-environment-add="TRAVIS_COMMIT_MESSAGE=$VAR"
```

### Anything else?

The YAML file would look like this:
```yaml
web_environment:
    - |4-
       comma inside
      and multiline
    - 'TRAVIS_COMMIT_MESSAGE=text with '
....

```

**Comment by AronNovak** [comment]
@rfay I am happy to touch some Go code if you have some hints on where to start to tackle it correctly.

**Comment by rfay** [comment]
Could you please test this with current HEAD, and please give a practical example? I'm quite sure you had something happen that made you bring this up, but if you could give a more real-world example, like what happened to you, it would be easier to understand what we're up against.

It looks like you're talking about global environment variables. Does the problem also happen with project environment variables? 

Maybe you can give an example of an invalid config file? Or a simple way to get the invalid config file?

Please edit the OP to give simpler and more direct details, thanks!

**Comment by AronNovak** [comment]
@rfay 
So we use Travis to deploy to QA, TEST and LIVE. We also would like to post an issue comment when something gets deployed to QA, see this in action: https://github.com/Gizra/drupal-starter/issues/427#issuecomment-1433189754
Everything happens inside DDEV for us inside the CI.
We need to pass the `TRAVIS_COMMIT_MESSAGE` to DDEV properly, we imagined we use environment variables for this, as we get it in this form from Travis. The commit message is needed to detect the issue number.

I'll test it with HEAD and simplify the instructions a bit soon.

**Comment by AronNovak** [comment]
```
 aaron  /  tmp  ./ddev --version
ddev version v1.21.6-30-g4a9cc3c1
```

Then:
```
 aaron  ~  /tmp/ddev 
FATA[0000] unable to read global config: yaml: line 13: did not find expected '-' indicator 
 aaron  ~  1  /tmp/ddev config global --web-environment-add="TRAVIS_COMMIT_MESSAGE=$VAR"
```

I have the same error.
Simplifying the instructions in OP now.

**Comment by AronNovak** [comment]
https://github.com/ddev/ddev/blob/master/cmd/ddev/cmd/config-global.go#L68
https://github.com/ddev/ddev/blob/master/cmd/ddev/cmd/config.go#L553

That's why commas are problematic in environment variables.

**Comment by AronNovak** [comment]
The documentation at https://ddev.readthedocs.io/en/latest/users/extend/customization-extendibility/ does not talk about commas, what if we support only adding one environment variable at once?
However it would change the behavior, that others might rely on already...

**Comment by AronNovak** [comment]
The other way could be to properly handle double quotes for specifying the content of the variable.

**Comment by rfay** [comment]
There's still nowhere near enough context here to solve this. 

Please note that there are dozens of ways to do yaml multiline strings, https://yaml-multiline.info/

I recommend that we start with a discussion about how you can accomplish your objective, which is still unclear. I know you want to do commit messages in travis, but you have dozens of ways to do that. Why don't you come over to Discord and let's have a conversation about what you're trying to accomplish?  

In the meantime, if you can update this issue to make it actionable that will be good. You'll have to edit the title to explain what it is that's your problem (I think you're complaining about `ddev config --web-environment-add` or `ddev config global --web-environment-add` where the content contains commas or newlines, but I'm not sure. I'm not sure whether you've tried to escape the commas, etc, and not sure why you haven't done it with two commands to add two environment variables.)

**Comment by rfay** [comment]
You should know that you could use `yq` to add content to any yaml file as well...

**Comment by AronNovak** [comment]
@rfay I'll open another issue later on with much more specific report, actually multi-line value is not part of the problem at all. Sorry for the noise.
