### ISSUE TITLE
Add ddev-grafana addon, that provides Grafana Stack, to the DDEV add-ons list

### ISSUE THREAD

**Issue by MurzNN** [ddev/ddev#4793]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

Missing Grafana Stack addon for DDEV.

### Describe your solution

I've created a new addon, that adds Grafana Stack to the DDEV: Grafana (GUI), Prometheus (metrics), Tempo (tracing, OpenTelemetry), Loki (logs, promtail).

It is very useful for our projects to test OpenTelemetry tracing and integration with logs and metrics locally.

Here is my repo: https://github.com/MurzNN/ddev-grafana

Please review it and move to the list of the official add-ons, if all is okay.

**Comment by tyler36** [comment]
Thanks for creating an addon @MurzNN 

First, you need to add `ddev-get` as a topic to the github repo. See https://github.com/mandrasch/ddev-addon-statamic-please/issues/1 for screenshots. 

You addon will be detected as "un-official" and will be discover-able by anyone by typing `ddev get --list --all`.

To get "official" status (`ddev get --list`), you will need to transfer the repo to the DDEV domain.

I see you have some basic tests that check installation. Great job! 
Could you update the test to check that each of the services are running? You could trying a `curl` command to check for a response, or maybe verify log files are written. Check other "offical" addons for help and hints.

These kind of tests will be run against stable and head versions of DDEV and are vital to catch breaking changes and bugs.

**Comment by tyler36** [comment]
Confirming that it's now available `ddev get --list --all`.

**Comment by MurzNN** [comment]
I've added health checks to the addon: https://github.com/MurzNN/ddev-grafana/commit/75a55eb0c7af4104b4e1e689b297bc19bfb60438 and also created a MR to improve this in the template: https://github.com/ddev/ddev-addon-template/pull/24

**Comment by rfay** [comment]
Thanks for the great contribution! I was able to run through installation and get to the main page. You will want to add to the README links for people to learn how to use these.

But this must have automated tests to be official, please do some good automated tests. The whole idea of "official" add-ons is that they're maintained and tested.

**Comment by rfay** [comment]
(It is OK to keep this unofficial if you want some time to let it get stable, etc.)

**Comment by rfay** [comment]
It shows now, if it gains usage and people want it to be official we can revisit. Thanks for this contribution!
