### ISSUE TITLE
Router fails to configure when several services use the same port but different protocol (HTTP and HTTPS)

### ISSUE THREAD

**Issue by MurzNN** [ddev/ddev#4794]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Run a Diagnostic and Paste Link Here

When I've configured the same port number on different projects with different protocols (HTTP and HTTPS), the router restarts without errors, but starts to show "503: No ddev back-end site available" errors on the projects URLs (80 and 443 ports too).

### Expected Behavior

I guess that this is not possible to make this work well, but it's better to throw some error with the explanation than just restarting without errors.

### Actual Behavior

The ddev-router stops working well.

### Steps To Reproduce

1. Configure a port, eg `3000` on one project to use HTTPS protocol:
```yaml
    environment:
      - VIRTUAL_HOST=$DDEV_HOSTNAME
      - HTTPS_EXPOSE=3000:3000
```
2. Configure the same port on another project to use HTTP protocol:
```yaml
    environment:
      - VIRTUAL_HOST=$DDEV_HOSTNAME
      - HTTP_EXPOSE=3000:3000
```
3. Restart projects - they should restart without any errors.
4. Try to open that port, or even web interface ports (80, 443) of that projects - you will see the "503: No ddev back-end site available" errors.

**Comment by tyler36** [comment]
Hi @MurzNN 

I believe you need to set both `HTTP_EXPOSE` and `HTTPS_EXPOSE` for this to work.
See `ddev/ddev-browsersync`'s [docker-compose.browsersync.yaml](https://github.com/ddev/ddev-browsersync/blob/main/docker-compose.browsersync.yaml) for an example of exposing port `3000`.

Note, the addon is only interested in sharing over HTTPS but we used a "fake" port for HTTP to keep DDEV happy.

**Comment by MurzNN** [comment]
> See `ddev/ddev-browsersync`'s [docker-compose.browsersync.yaml](https://github.com/ddev/ddev-browsersync/blob/main/docker-compose.browsersync.yaml) for an example of exposing port `3000`.

@tyler36 But they're using different ports for HTTP (3001)  and HTTPS (3000), isn't it?
```
      - HTTP_EXPOSE=...,3001:3000
      - HTTPS_EXPOSE=...,3000:3000
```

**Comment by rfay** [comment]
Due to a quirk in the (old) ddev-router, you *have* to have HTTP_EXPOSE for HTTPS_EXPOSE to work.

But please test using the upcoming traefik router, which will be the default in v1.22.0.

**Comment by MurzNN** [comment]
> Due to a quirk in the (old) ddev-router, you have to have HTTP_EXPOSE for HTTPS_EXPOSE to work.

Thanks, but still using different port numbers like 3001 (shim) for HTTP and 3000 (desired) for HTTPS?

**Comment by rfay** [comment]
People do this everywhere. If the hostname is different for the two projects, it should work. You can easily test it with one of the many add-ons available. Set them up in two projects, they'll work.

However, if you have a `ports` statement in either of your projects, that will mess everything up; you need `expose`, not ports.

If you want to go forward with this, please create a demonstration repo. It can be a trivial repo based on just a simple PHP file. And add your docker-compose.demo.yaml to it. Then run it in two different projects. 

DDEV itself does exactly this all the time, has http and https ports all on 80 and 443, and as you know you can run many DDEV projects at the same time.

**Comment by rfay** [comment]
If you're saying that you want one project or service to be able to expose port 3000 via HTTP_EXPOSE as HTTP and another project or service to expose port 3000 the same router port via HTTPS_EXPOSE, no, it could never work.

**Comment by rfay** [comment]
I don't think what you want is possible if I understand it right. You can't serve both HTTP and HTTPS on the same port. Happy to continue the conversation here or elsewhere.

**Comment by MurzNN** [comment]
> You can't serve both HTTP and HTTPS on the same port.

I know, but I'm talking about different projects that unintentionally reuse the same port.

For example, Grafana uses by default the 3000 port, and it's better to use HTTPS to get rid of warnings in browsers when submitting forms with passwords.

But many React apps by default use 3000 port, and pretty often without HTTPS.

So, if someone starts a ddev project "my-react-app" that uses `HTTP_EXPOSE=3000:3000`  - it will start ok and works well at http://my-react-app.ddev.site:3000/

But then when they try to start another project "not-my-react-app" that uses `HTTPS_EXPOSE=3000:3000`  (with keeping "my-react-app" running) - it will start successfully, but with broken routing with the error: "503: No ddev back-end site available" at the url https://not-my-react-app.ddev.site:3000/

So, my suggestion is to check these conflicts and display an error or at least a warning on startup.

**Comment by MurzNN** [comment]
And the same when the single project tries to configure both on the same port like this:
```
      - HTTP_EXPOSE=3000:3000
      - HTTPS_EXPOSE=3000:3000
```
because now it start without any errors.

**Comment by rfay** [comment]
Hi @MurzNN - What you're doing could never work, because you're using https and http on port 3000.  The router can't serve both HTTP and HTTPS on the same port. 

That's the same answer I've given several times. You have to use different router ports for http and https.

**Comment by MurzNN** [comment]
> Hi @MurzNN - What you're doing could never work, because you're using https and http on port 3000. The router can't serve both HTTP and HTTPS on the same port.
> 
> That's the same answer I've given several times. You have to use different router ports for http and https.

I totally understand that this will not work, and don't ask to make this work.

I'm asking only to throw an error or a warning, if the such broken configuration is detected on a project startup process!

And this improvement is mostly not for me, but for all other users to eliminate the time to find the source of the problem, because I spent a lot of time when first time tried to find the source of the "503: No ddev back-end site available" error!

So, to get into this trouble, the user can just clone two different projects, that reuse the same port (eg 3000) with different schemes (HTTP and HTTPS) and start them, and as result - will get just the 503 error and no clue how to fix it.

So, the warning will be much helpful!

**Comment by rfay** [comment]
Sorry, I didn't realize you were just asking for an error. Unfortunately, this all happens at a very low level. If DDEV were to try to figure out all the things you could do wrong in a docker-compose.*.yaml it would be pretty interesting. `docker-compose.*.yaml` is definitely an advanced use case. 

One thing we could do is tell people "Please, please, never use port 3000". I'm not sure why every node app in the world thinks it's OK to re-use port 3000.

**Comment by MurzNN** [comment]
Thank you for the explanation, I'm not a go programmer, but have looked into the code, and seems here:
https://github.com/ddev/ddev/blob/bd1a05e258d645f699c171dc16a933ed49ddf7df/pkg/ddevapp/router.go#L263-L273
we're collecting all http and https ports, right?
So, maybe add here a check for intersections (at least the same port for HTTP and HTTPS inside a single project) and throw an error? 

And, if it possible, collect port numbers for all running projects and do the intersections check too.

**Comment by MurzNN** [comment]
With the ddev 1.22 release and Traefic - seems the issue is resolved, now I can configure HTTP and HTTPS for the same port! Example with sharing port 3000:
```yaml
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: ${DDEV_APPROOT}
    environment:
      - VIRTUAL_HOST=$DDEV_HOSTNAME
      - HTTP_EXPOSE=3000:3000
      - HTTPS_EXPOSE=3000:3000
```

**Comment by MurzNN** [comment]
I didn't believe too ;) But it somehow works!!! At the same time - HTTP and HTTPS opens well! Seems some Traefik magic here! Here is a proof:
![image](https://github.com/ddev/ddev/assets/336662/2807e614-c92f-404a-b52d-747092a2a29e)
![image](https://github.com/ddev/ddev/assets/336662/481625b2-fb4e-4b89-819a-8defaf2287ee)

**Comment by rfay** [comment]
I tested this with ddev/ddev-phpmyadmin and I confirm your results, at least with Chrome/macOS and curl. I don't think it's a very good idea though. It must be something super special about Traefik, but I found nothing with the searches I tried.

But what are you going to do if somebody's not using traefik? How will they understand the breakage? Maybe you have to add something to your install.yaml that tests to see if they're using traefik?
