### ISSUE TITLE
`ddev get --list --all` is not returning all available unofficial add-ons

### ISSUE THREAD

**Issue by rfay** [ddev/ddev#4795]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected Behavior

`ddev get --list --all` should return all available add-ons

### Actual Behavior

It turns out the query response is paged, so we're only getting the first page. Currently there are 42 out there, and only 30 are being returned in the first page of results.

**Comment by tyler36** [comment]
More out of curiosity, but if it is paging the results, what is the current "sort" order?

**Comment by rfay** [comment]
I'm unable to make sense of it. `ddev-viteserve` first, `ddev-browsersync` second.  `julienloizelet/ddev-portainer` 21st. `ddev-laravel-queue` 30th.

**Comment by rfay** [comment]
@tyler36 current sort order is alphabetic. Can do something else a number of ways.

And currently 46 in `ddev get --list --all`, which you can do if you install HEAD version.

**Comment by tyler36** [comment]
Yes, justed tested #4819 (`1.22.0-alpha2-2-gdd8236a8` ) ... and now seeing all (currently) 46 addons. Thanks.
