### ISSUE TITLE
`upload_dir` should be able to be set to empty to prevent bind-mounting

### ISSUE THREAD

**Issue by rfay** [ddev/ddev#4796]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected Behavior

If you set `upload_dir: ""` you'd expect it to then ignore the idea of upload_dir, but right now "empty" is considered "no upload_dir configured"

### Actual Behavior

`upload_dir: ""` will result in warnings about upload_dir under mutagen, and no bind-mount set up. 

### Related 

* https://github.com/ddev/ddev/issues/4190

**Comment by rfay** [comment]
No @gilbertsoft I would expect
```
upload_dirs: []
```

But I do agree that there's no way to distinguish between that and not specifying the item in the first place.

Since upload_dir is currently relative to docroot, your suggestion would mean "upload_dir" is "docroot" I think.

**Comment by gilbertsoft** [comment]
fyi @rfay , solved by letting users set the `upload_dirs` to `false`.

```
You have mutagen enabled and your 'php' project type doesn't have an upload_dirs set. 
For faster startup and less disk usage, set upload_dirs to where your user-generated files are stored. 
If this is intended you can disable this warning by running `ddev config --upload-dir=false`. 
```
