### ISSUE TITLE
Addons can have tags, `ddev get` can filter by them.

### ISSUE THREAD

**Issue by tyler36** [ddev/ddev#4799]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

#4795 states that we currently have 42+ addons. Thats a lot of addons!

It would be nice if we could filter by addon tags. 

### Describe your solution

Tags could be anyting the author/maintainer chooses, but I think we should encourage 2 types:

- Framework (Drupal, Laraval, Typo3 etc...)
- Function (search, database, development)

``` shell
ddev get --list --all --tag drupal
// display all available addons that support Drupal
```

```shell 
ddev get --list --search
// display all available addons related to search
```

**Comment by rfay** [comment]
It's a good idea. Not sure how we could get people to use the tags in a reasonable and consistent way?

**Comment by tyler36** [comment]
For official addons, it should be easy.

Unofficial might be harder for scratch-my-own-itch addons, but I think other might be OK with it.

**Comment by rfay** [comment]
I think this will happen when we build the add-on registry, which hopefully will be this year.

**Comment by GuySartorelli** [comment]
Is it worth opening this again, with the registry just around the corner?

> Not sure how we could get people to use the tags in a reasonable and consistent way?

I don't think you can, and I don't think it's worth worrying too much about that. 

I thought I remembered Packagist used to have a list of all tags, with how frequently they were used, but I can't find that anymore so either they removed it or my memory is playing tricks.
In any case, having a list of all current tags and recommending people use existing tags if they are appropriate is probably the best that anyone can do as far as encouraging consistency. Probably not much value in moderating the tags except in the case where someone points out something that's clearly inappropriate or offensive.
