### ISSUE TITLE
`ddev debug migrate-database` is broken (v1.21.6)

### ISSUE THREAD

**Issue by pasqual-artif** [ddev/ddev#4800]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected Behavior

accomplish migration/conversion of database

### Actual Behavior

with "watch -n 1 ls -lisah ./" in the folder .ddev/.downloads/ I figured out, that the folder .ddev/.downloads/ gets deleted before the error occurs.

Every 1.0s: ls -lisah ./                                                                                                                                                 

sh: 0: getcwd() failed: No such file or directory
total 0

### Steps To Reproduce

Create a Project in mariadb 10.4 or mysql 5.7 and run a debug migrate to the other db

### Anything else?

changed actual project name to "projectname" and user to "user"...

$ ddev debug migrate-database mysql:5.7
Is it OK to attempt conversion from mariadb:10.4 to mysql:5.7?
This will export your database, create a snapshot,
then destroy your current database and import into the new database type.
It only migrates the 'db' database [Y/n] (yes): Y
Wrote database dump from project 'projectname' database 'db' to file /home/user/project/.ddev/.downloads/db.sql.gz in gzip format.
Creating database snapshot projectname_remove_data_snapshot_20230403124527
Container ddev-projectname-db  Removed
Container ddev-projectname-dba  Removed
Container ddev-projectname-web  Removed
Network ddev-projectname_default  Removed
Volume projectname-mariadb for project projectname was deleted
Volume projectname-postgres for project projectname was deleted
Volume projectname_project_mutagen for project projectname was deleted
Project projectname was deleted. Your code and configuration are unchanged.
Network ddev-projectname_default  Created
Container ddev-projectname-db  Started
Container ddev-projectname-dba  Started
Container ddev-projectname-web  Started
Container ddev-router  Started
failed to import-db /home/user/project/.ddev/.downloads/db.sql.gz: Unable to validate import asset /home/user/project/.ddev/.downloads/db.sql.gz: invalid asset: file not found

**Comment by rfay** [comment]
You didn't do the `ddev debug test` and put in a gist and give a link, so I don't know much about your environment or even what version of DDEV you're using. Could you please do that and edit? You can put it on any pastbin, or attach as a file if you want.

**Comment by pasqual-artif** [comment]
[ddev debug test.txt](https://github.com/ddev/ddev/files/11140499/ddev.debug.test.txt)

**Comment by rfay** [comment]
Thanks for doing that; It looks like you're not able to resolve `*.ddev.site` or something? Anyway, failed on external access, but that wouldn't affect the database conversion.

BTW, the `ddev debug migrate-database mysql:5.7` is not expected to be something you'd ordinarily use. Why don't you just use `ddev config --database=mysql:5.7` ?

**Comment by pasqual-artif** [comment]
> Thanks for doing that; It looks like you're not able to resolve `*.ddev.site` or something? Anyway, failed on external access, but that wouldn't affect the database conversion.
> 
> BTW, the `ddev debug migrate-database mysql:5.7` is not expected to be something you'd ordinarily use. Why don't you just use `ddev config --database=mysql:5.7` ?

yeah... i cannot reach it from my local network... but on my local machine.

 because I already have a mariadb-dump from my local env, which is also mariadb but the live system has mysql 5.7. so im forced to convert it to mysql.
