### ISSUE TITLE
`ddev auth ssh` should support RSA keys in PKCS 8 format

### ISSUE THREAD

**Issue by andriokha** [ddev/ddev#4802]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

Certain keys aren't recognized by the `file` command.
```
$ mkdir ~/test.ssh
$ ssh-keygen -m PKCS8 -t rsa -f ~/test.ssh/test_key_pkcs8 -qN ''
$ ssh-keygen -t rsa -f ~/test.ssh/test_key -qN ''
$ file ~/test.ssh/*
~/test.ssh/test_key:           OpenSSH private key
~/test.ssh/test_key_pkcs8:     ASCII text
~/test.ssh/test_key_pkcs8.pub: OpenSSH RSA public key
~/test.ssh/test_key.pub:       OpenSSH RSA public key
```
This means that they don't get picked up by DDEV. Eg.
```
$ mkdir ~/test2.ssh
$ ssh-keygen -m PKCS8 -t rsa -f ~/test2.ssh/test_key_pkcs8 -qN ''
$ ddev auth ssh -d ~/test2.ssh
Docker command 'docker [run -it --rm --volumes-from=ddev-ssh-agent --user=1000 --entrypoint= --mount=type=bind,src=/home/andy/test2.ssh,dst=/tmp/sshtmp drud/ddev-ssh-agent:v1.21.5-built bash -c cp -r /tmp/sshtmp ~/.ssh && chmod -R go-rwx ~/.ssh && cd ~/.ssh && ssh-add $(file * | awk -F: "/private key/ { print \$1 }")]' failed: exit status 1
```

Although note that if you have 0 recognized private keys in the folder, then at the end of the following line:
https://github.com/ddev/ddev/blob/0e25778fa81f73cadec80e05a4838e9ca0ee3fd3/cmd/ddev/cmd/auth-ssh.go#L73
this bit
```sh
ssh-add $(file * | awk -F: "/private key/ { print \$1 }")
```
expands to just
```sh
ssh-add
```
which explicitly looks for `~/.ssh/id_rsa`, `~/.ssh/id_ecdsa`, `~/.ssh/id_ecdsa_sk`, `~/.ssh/id_ed25519`, `~/.ssh/id_ed25519_sk`, and `~/.ssh/id_dsa`). So it turns out you can add a PKCS#8 RSA key by calling it `id_rsa` and having it the sole key in the directory:
```
$ mkdir ~/test3.ssh
$ ssh-keygen -m PKCS8 -t rsa -f ~/test3.ssh/id_rsa -qN ''
$ ddev auth ssh -d ~/test3.ssh
Identity added: /home/andy/.ssh/id_rsa (/home/andy/.ssh/id_rsa)
```

### Describe your solution

I was thinking it would be nice to specify a particular key.

### Additional context
An example failing key pair:
[test_key_pkcs8.txt](https://github.com/ddev/ddev/files/11150318/test_key_pkcs8.txt)
[test_key_pkcs8.pub.txt](https://github.com/ddev/ddev/files/11150321/test_key_pkcs8.pub.txt)

**Comment by andriokha** [comment]
While it might still be useful for similar edge cases to be able to specify a particular key, [the bug's been fixed upstream](https://bugs.astron.com/view.php?id=443) and should be in `file` 5.45. Thanks!

**Comment by rfay** [comment]
Thanks @andriokha - Can you say a little about that bug and how it's related to this issue? I don't even understand how bugs.astron.com is related to PKCS 8 format in RSA keys.

**Comment by andriokha** [comment]
Hi @rfay, sorry yeah it's not super obvious but that's the bug tracker for `file` (see `man file`). You can see [the code change in the github mirror](https://github.com/file/file/commit/c577678e5b711d335c359ca997f61751c1bd9ac2) and [the changelog shows it's unreleased](https://bugs.astron.com/changelog_page.php).

The bug fixed is the one shown in the first comment of this issue, where the `file` command doesn't correctly recognize a PKCS8 private key and instead reports it as ASCII text.

It might be worth closing the issue as I did find a rough workaround, and a proper fix should be coming down the pipeline.

(Btw congrats on a well-deserved award!)

**Comment by rfay** [comment]
Oh, I didn't understand that this was actually about `file` in the first place. I'll go ahead and close this for now, will appreciate it if you keep me up-to-date with whether this gets a release, and then we can see when it lands in the proper images. The ddev-ssh-agent will move to bookworm before too long, we can hope that the new `file` will make it there as well.

**Comment by rfay** [comment]
Closed but not forgotten, thanks so much for tracking!

**Comment by andriokha** [comment]
[5.45 was released July 27.](https://bugs.astron.com/changelog_page.php?version_id=31)

**Comment by rfay** [comment]
Thanks so much. Next question is when it will land in Debian.

**Comment by andriokha** [comment]
[Looks like Trixie's using 5.46](https://packages.debian.org/trixie/file).

**Comment by rfay** [comment]
I'll try a PR and we'll see if we can get it updated.

**Comment by rfay** [comment]
@andriokha please test the artifacts in https://github.com/ddev/ddev/pull/7933#issuecomment-3638583257 and review the PR, thanks!

**Comment by andriokha** [comment]
Thanks @rfay you're a star.

## Existing behavior
```sh
mkdir test2.ssh
ssh-keygen -m PKCS8 -t rsa -f test2.ssh/test_key_pkcs8 -qN ''
ddev --version
ddev auth ssh -d test2.ssh/
```
yields
```
ddev version v1.24.10
Adding 1 SSH private key(s)... 
No SSH private keys found.
Failed to execute command `ddev auth ssh`: container run failed with exit code 1  
```

## Test artefact
```sh
./ddev --version
./ddev auth ssh -d test2.ssh/
```
yields
```
ddev version v1.24.10-79-g8d460e031
Network ddev_default created 
[+] Pulling 7/7
 ✔ ddev-ddev-ssh-agent-20251210_ssh_agent_trixie Pulled                                                                                                                                                       12.7s 
   ✔ 1733a4cd5954 Pull complete                                                                                                                                                                                7.4s 
   ✔ 9ef8ea07eac1 Pull complete                                                                                                                                                                               10.7s 
   ✔ 8bc146fa401c Pull complete                                                                                                                                                                               10.7s 
   ✔ 4f4fb700ef54 Pull complete                                                                                                                                                                               10.8s 
   ✔ 8aa9cfd79d85 Pull complete                                                                                                                                                                               10.8s 
   ✔ 5245ba916ce9 Pull complete                                                                                                                                                                               10.9s 
time="2025-12-12T15:29:10Z" level=warning msg="Docker Compose is configured to build using Bake, but buildx isn't installed" 
 Container ddev-ssh-agent  Created 
 Container ddev-ssh-agent  Started 
ssh-agent container is running: If you want to add authentication to the ssh-agent container, run 'ddev auth ssh' to enable your keys. 
Adding 1 SSH private key(s)... 
Adding key test_key_pkcs8
Identity added: test_key_pkcs8 (test_key_pkcs8)
Successfully added 1 SSH private key(s). 
```

I'm afraid I can't really say anything intelligent regarding the MR, except to say I was a little surprised it's searching for specific text in the key file (`grep -l '^-----BEGIN .*PRIVATE KEY-----' *`) - I would've imagined you'd either completely delegate to `file` or use entirely your own logic, but currently it feels like it might be a mixture. But I've just cast an eye over the MR for a second and I don't know what I don't know (: Ahhhh, I was just about to mention that my workaround in the first comment (referencing line 73 of auth-ssh.go) is arguably a bug and might be worth looking at. I then tried to find that line in the current version and couldn't... it seems the offending line was updated in 67237978a558ae895384a4c083de290e98e0dc66 to no longer use the `file` command! So actually I'm not sure why it wasn't working with 1.24.10 and as far as I know it doesn't matter what version of file we have!

**Comment by andriokha** [comment]
> So actually I'm not sure why it wasn't working with 1.24.10

Ah, that'll be the regex change that makes it work, looks like...
