### ISSUE TITLE
Git "dubious ownership" error triggered when using VirtioFS

### ISSUE THREAD

**Issue by byrond** [ddev/ddev#4829]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Run a Diagnostic and Paste Link Here
```
 % ddev debug test
Running bash [-c /var/folders/dl/dt68qt3s27v_mc80vfh2lwvw0000gn/T/test_ddev.sh] 
======= Existing project config =========
These config files were loaded for project ddev-test: [/Volumes/Dev/ddev-test/.ddev/config.yaml]
name: ddev-test
type: php
php_version: 8.0
webserver_type: nginx-fpm
webimage: drud/ddev-webserver:v1.21.5
router_http_port: 80
router_https_port: 443
additional_hostnames: []
additional_fqdns: []
database: {mariadb 10.4}
mailhog_port: 8025
mailhog_https_port: 8026
phpmyadmin_port: 8036
phpmyadmin_https_port: 8037
project_tld: ddev.site
use_dns_when_possible: true
composer_version: 2
nodejs_version: 16
default_container_timeout: 120
======= Creating dummy project named  tryddevproject-11217 in ../tryddevproject-11217 =========
OS Information: Darwin LenasAppleWatch.localdomain 22.4.0 Darwin Kernel Version 22.4.0: Mon Mar  6 20:59:28 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T6000 arm64
ProductName:		macOS
ProductVersion:		13.3.1
BuildVersion:		22E261
User information: uid=501(byron) gid=20(staff) groups=20(staff),12(everyone),61(localaccounts),79(_appserverusr),80(admin),81(_appserveradm),98(_lpadmin),701(com.apple.sharepoint.group.1),33(_appstore),100(_lpoperator),204(_developer),250(_analyticsusers),395(com.apple.access_ftp),398(com.apple.access_screensharing),399(com.apple.access_ssh),400(com.apple.access_remote_ae)
DDEV version:  ITEM             VALUE                                   
 DDEV version     v1.21.6                                 
 architecture     arm64                                   
 db               drud/ddev-dbserver-mariadb-10.4:v1.21.5 
 dba              phpmyadmin:5                            
 ddev-ssh-agent   drud/ddev-ssh-agent:v1.21.5             
 docker           20.10.22                                
 docker-compose   v2.15.1                                 
 docker-platform  docker-desktop                          
 mutagen          0.16.0                                  
 os               darwin                                  
 router           drud/ddev-router:v1.21.5                
 web              drud/ddev-webserver:v1.21.5             
PROXY settings: HTTP_PROXY='' HTTPS_PROXY='' http_proxy='' NO_PROXY=''
======= DDEV global info =========
Global configuration:
instrumentation-opt-in=true
omit-containers=[]
mutagen-enabled=false
nfs-mount-enabled=false
router-bind-all-interfaces=false
internet-detection-timeout-ms=3000
disable-http2=false
use-letsencrypt=false
letsencrypt-email=
table-style=default
simple-formatting=false
auto-restart-containers=false
use-hardened-images=false
fail-on-hook-fail=false
required-docker-compose-version=
use-docker-compose-from-path=false
project-tld=
xdebug-ide-location=
no-bind-mounts=false
use-traefik=false
wsl2-no-windows-hosts-mgt=false

======= DOCKER info =========
docker location: lrwxr-xr-x@ 1 root  wheel  61 Apr 17 15:55 /usr/local/bin/docker -> /Applications/Docker 4.16.2.app/Contents/Resources/bin/docker
Docker Desktop Version: Docker Desktop for Mac 4.18.0 build 104112
docker version: 
Client:
 Cloud integration: v1.0.29
 Version:           20.10.22
 API version:       1.41
 Go version:        go1.18.9
 Git commit:        3a2c30b
 Built:             Thu Dec 15 22:28:41 2022
 OS/Arch:           darwin/arm64
 Context:           default
 Experimental:      true

Server: Docker Desktop 4.16.2 (95914)
 Engine:
  Version:          20.10.22
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.9
  Git commit:       42c8b31
  Built:            Thu Dec 15 22:25:43 2022
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.14
  GitCommit:        9ba4b250366a5ddde94bb7c9d1def331423aa323
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
DOCKER_DEFAULT_PLATFORM=notset
======= Mutagen Info =========
======= Docker Info =========
Docker platform: docker-desktop 
Using docker context: default (unix:///Users/byron/.docker/run/docker.sock) 
docker-compose: v2.15.1 
Using DOCKER_HOST=unix:///Users/byron/.docker/run/docker.sock 
Docker version: 20.10.22 
Able to run simple container that mounts a volume. 
Able to use internet inside container. 
Docker disk space:
Filesystem                Size      Used Available Use% Mounted on
overlay                  58.4G     23.5G     31.9G  42% /

Container ddev-ddev-test-db  Removed 
Container ddev-ddev-test-dba  Removed 
Container ddev-ddev-test-web  Removed 
Network ddev-ddev-test_default  Removed 
Project ddev-test has been stopped. 
The ddev-ssh-agent container has been removed. When you start it again you will have to use 'ddev auth ssh' to provide key authentication again. 
Existing docker containers: 
CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES
Creating a new ddev project config in the current directory (/Volumes/Dev/tryddevproject-11217) 
Once completed, your configuration will be written to /Volumes/Dev/tryddevproject-11217/.ddev/config.yaml
 
Configuring unrecognized codebase as project type 'php' at /Volumes/Dev/tryddevproject-11217/web 
Configuration complete. You may now run 'ddev start'. 
Network ddev_default created 
Starting tryddevproject-11217... 
Container ddev-ssh-agent  Started 
ssh-agent container is running: If you want to add authentication to the ssh-agent container, run 'ddev auth ssh' to enable your keys. 
Network ddev-tryddevproject-11217_default  Created 
Container ddev-tryddevproject-11217-dba  Started 
Container ddev-tryddevproject-11217-web  Started 
Container ddev-tryddevproject-11217-db  Started 
Container ddev-router  Started 
Successfully started tryddevproject-11217 
Project can be reached at https://tryddevproject-11217.ddev.site https://127.0.0.1:55923 
======== Curl of site from inside container:
HTTP/1.1 200 OK
Server: nginx
Date: Mon, 17 Apr 2023 20:43:06 GMT
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
Vary: Accept-Encoding

======== curl -I of http://tryddevproject-11217.ddev.site from outside:
HTTP/1.1 200 OK
Server: nginx/1.20.1
Date: Mon, 17 Apr 2023 20:43:06 GMT
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
Vary: Accept-Encoding

======== full curl of http://tryddevproject-11217.ddev.site from outside:
Success accessing database... db via TCP/IP
ddev is working. You will want to delete this project with 'ddev delete -Oy tryddevproject-11217'
======== Project ownership on host:
drwxr-xr-x  4 byron  staff  128 Apr 17 16:42 ../tryddevproject-11217
======== Project ownership in container:
drwxr-xr-x 4 root root 128 Apr 17 20:42 /var/www/html
======== In-container filesystem:
Filesystem         Type      1K-blocks      Used Available Use% Mounted on
/host_mark/Volumes fakeowner 971350180 539727052 431623128  56% /var/www/html
======== curl again of tryddevproject-11217 from host:
Success accessing database... db via TCP/IP
ddev is working. You will want to delete this project with 'ddev delete -Oy tryddevproject-11217'
Thanks for running the diagnostic. It was successful.
Please provide the output of this script in a new gist at gist.github.com
Running ddev launch in 5 seconds
If you're brave and you have jq you can delete all tryddevproject instances with this one-liner:
    ddev delete -Oy $(ddev list -j |jq -r .raw[].name | grep tryddevproject)
In the future ddev debug test will also provide this option.

Please delete this project after debugging with 'ddev delete -Oy tryddevproject-11217'
byron@Byrons-M1-MacBook-Pro ddev-test % ddev delete -Oy tryddevproject-11217
Container ddev-tryddevproject-11217-dba  Removed 
Container ddev-tryddevproject-11217-db  Removed 
Container ddev-tryddevproject-11217-web  Removed 
Network ddev-tryddevproject-11217_default  Removed 
Volume tryddevproject-11217-mariadb for project tryddevproject-11217 was deleted 
Volume tryddevproject-11217-postgres for project tryddevproject-11217 was deleted 
Volume tryddevproject-11217_project_mutagen for project tryddevproject-11217 was deleted 
Project tryddevproject-11217 was deleted. Your code and configuration are unchanged. 
```

### Expected Behavior

Git commands will run inside the DDEV container when using the VirtioFS file sharing implementation of Docker.

### Actual Behavior

When running any Git command inside the DDEV container, the following message is returned:
```
fatal: detected dubious ownership in repository at '/var/www/html'
To add an exception for this directory, call:

	git config --global --add safe.directory /var/www/html
```

### Steps To Reproduce

1. `ddev poweroff`
2. Change Docker settings to use VirtioFS.
3. Create an empty project directory.
4. `git init`
5. `ddev config`
6. Complete the DDEV config with defaults.
7. `ddev start`
8. `ddev . git status`

### Anything else?

This issue is likely happening because VirtioFS shares the project directory into the container as being owned by `root:root`. This is a mismatch to the ownership of other files within the project directory or the user running `git`. See also https://www.kenmuse.com/blog/avoiding-dubious-ownership-in-dev-containers/.

I'm not sure whether this issue needs to be addressed by Docker in the file sharing ownership or if a workaround should be implemented in DDEV.

**Comment by rfay** [comment]
Please don't use VirtioFS, it breaks lots of things, as mentioned in https://ddev.readthedocs.io/en/latest/users/install/docker-installation/#docker-desktop-for-mac

DDEV doesn't have control of the filesharing setup.

**Comment by byrond** [comment]
I have had good luck with VirtioFS and DDEV over the last year without experiencing any of the issues or caveats introduced by using Mutagen. Adding a post-start hook to run `git config --global --add safe.directory /var/www/html` fixes the issue for us, in case others are interested in a workaround.

**Comment by rfay** [comment]
When using mutagen, these problems are masked; /var/www/html is not even a mount. If you're using mutagen, /var/www/html is not mounted. Take a look at your config. `ddev exec df -T /var/www/html` should show something like this - it's a volume mount, not a bind mount.

```
$ ddev exec df -T /var/www/html
Filesystem                     Type 1K-blocks      Used Available Use% Mounted on
/dev/disk/by-label/data-volume ext4 205837988 185131152  10204752  95% /var/www
```

What do you see?

**Comment by byrond** [comment]
```
% ddev exec df -T /var/www/html
Filesystem         Type      1K-blocks      Used Available Use% Mounted on
/host_mark/Volumes fakeowner 971350180 540244264 431105916  56% /var/www/html
```

**Comment by rfay** [comment]
Wow, that's not the way DDEV mounts mutagen volumes. DDEV mounts mutagen on /var/www.

I suspect you think you're using mutagen but actually have it turned off. Or you have a very, very old DDEV version.

Please provide `ddev describe` for this project.

It would help if you could do the requested `ddev debug test` and put the results as a file or a gist (gist.github.com) so I'd know more about your situation.

**Comment by byrond** [comment]
No, I'm using VirtioFS:
> I have had good luck with VirtioFS and DDEV over the last year without experiencing any of the issues or caveats introduced by using Mutagen.

I don't know if there is anything that can be done in DDEV about this. It seems like just a side-effect of the way Docker shares directories when using VirtioFS. We have a workaround, which I shared here, so this can probably be closed.

**Comment by rfay** [comment]
I'm sure you've been following the many long-running Virtiofs issues over the years, https://github.com/docker/for-mac/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+virtiofs

The most important one for you is 
* https://github.com/docker/for-mac/issues/6243

But there are oh-so-many. They do seem to be whittling away at some of them.

**Comment by byrond** [comment]
Thanks! I had run into this issue earlier this year:
https://github.com/docker/for-mac/issues/6614

So far, I haven't experienced any of the others. I wonder if the fact that I have created a separate, case-sensitive volume for my development project directories has mitigated any of those issues. I mainly did that for the rare instances where we have two files that only vary in case in a repository, but maybe there are other benefits I'm not even aware of yet.

The issue you linked to above seems most relevant to this case, and maybe I can post over there. However, all I am experiencing is the parent directory is owned by `root`, but the rest of the directories and files inside have the correct ownership and permissions.

**Comment by rfay** [comment]
Actually, I wonder if there's a way we can mount a directory higher for regular mounts in order to deal with this, just like we do for mutagen. (With mutagen it's for completely different reasons.).  I don't think it would be possible because the directory above absolutely shouldn't be inside the container, but maybe there's some way to think about this that will get us there.

Could you say why you use git inside the container?

**Comment by byrond** [comment]
We have a couple of build commands that use Git to check for a "clean" Drupal config directory. One of them can be run outside the container, but the other one cannot at the moment. We are working on refactoring that so we can run it outside the container, and it will run `mysql` with `ddev exec`. We already do that for commands that need to run Drush or Behat.

**Comment by MoritzLost** [comment]
@rfay I also just encountered this error, while doing `ddev composer install` (not sure why git is invoked at all here?):

![Image](https://github.com/user-attachments/assets/712ce2e0-d391-42f4-96f1-5e9290300f4c)

We already have multiple projects running on ddev with the exact same config where I didn't get this warning – the only difference is this project runs on PHP 8.2, while the others run on 8.3. Not sure if that's related.

We use Docker Desktop and have so far left the file sharing implementation at VirtioFS (since it is the default on Docker Desktop). You mentioned it's not supported and not recommended, but I can't find anything on this in the docs – did I miss that? What's recommended instead, gRPC fuse?

**Comment by rfay** [comment]
You apparently have a git checkout in your composer.json I imagine.  Anyway, your composer build is using git. 

VirtioFS works fine in Docker Desktop these days (on macOS). However, most people on macOS use Mutagen, so they never even see VirtioFS.

I guess maybe a post-start exec hook that does `git config global --add safe.directory '*'`  ?

Happy to discuss further, and feel free to join us for conversation in Discord, https://discord.com/invite/5wjP76mBJD

I haven't heard of this problem before, although this feature/check was added to git a year or two ago.

**Comment by rfay** [comment]
It would help if you'd do a `ddev debug test` so we could see what's going on. You can do that and give a link to a gist, or give it in #support in Discord, or whatever.

**Comment by MoritzLost** [comment]
@rfay Thanks for the reply! We'll stick with VirtioFS for now then. Haven't seen any performance problems yet, and the list of caveats with Mutagen was a bit too long for my taste 😬 

Very curious – git is definitely not being invoked by us. We only have one  `post-install-cmd` hook in the `composer.json` to create the `.env` file if it doesn't exist, that doesn't involve git. And our `.ddev/config.yaml` doesn't have _any_ hooks defined. Any other place that might invoke git accidentally? Maybe Craft or another PHP dependency is checking something with git for some reason?

Also curious why this permissions issue would crop up in this project, but not any of the others with identical configuration …

Don't have a lot of time right now, I'll run a `debug test` and report back once I can reproduce the issue reliably!

**Comment by rfay** [comment]
> the list of caveats with Mutagen was a bit too long for my taste

Those are very old caveats. Almost everybody on macOS and Windows uses Mutagen all the time. (And you wouldn't have this problem with mutagen)

I imagine that the problem is this, which I didn't understand before:

* You're using Docker Desktop
* You're not using mutagen, which would solve this
* DD mounts bind-mount points as owned by root/root. This is a longstanding issue, as in https://github.com/docker/for-mac/issues/6243 - it's mostly probably solved by Docker VMM below.
* However, DD just introduced "Docker VMM", which mounts bind-mount points with the right ownership. You should try it. https://docs.docker.com/desktop/release-notes/#4350

Please give that a try. Alternately, OrbStack would work perfectly for you, and every other Docker provider would also I think. Mutagen with any of them would work for you.

**Comment by MoritzLost** [comment]
@rfay Thanks for the explanation, and sorry for the late reply! A lot of good options. I'm still on Intel, so I can't try the Docker VMM mode yet, as it only supports Apple Silicon. We'll give Mutagen a try, if that doesn't pan out we'll check out the Docker VMM once we're all on Apple Silicon early next year.
