### ISSUE TITLE
Optimize performance Drupal settings inclusion

### ISSUE THREAD

**Issue by Novitsh** [ddev/ddev#4838]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

I believe we can optimize the speed by avoiding disk check every request for non-ddev environments.
In most cases you will add the settings.php file to your GIT repo and thus deploying to acceptance/production environments, introducing an extra operation.

Current code in settings.php file:
```
// Automatically generated include for settings managed by ddev.
if (file_exists(__DIR__ . '/settings.ddev.php') && getenv('IS_DDEV_PROJECT') == 'true') {
  include __DIR__ . '/settings.ddev.php';
}
```

### Describe your solution

Turn it around:

```
// Automatically generated include for settings managed by ddev.
if (getenv('IS_DDEV_PROJECT') == 'true' && file_exists(__DIR__ . '/settings.ddev.php')) {
  include __DIR__ . '/settings.ddev.php';
}
```

This will avoid disk reading if the env doesn't exist.

**Comment by Novitsh** [comment]
Maybe I didn't explain it well enough, I'm not referring to DDEV's performance, but your actual Drupal application when it lands in an acceptance or production environment.

**Comment by rfay** [comment]
It won't take you any time. Just do a PR that edits the various settings files, https://github.com/search?q=repo%3Addev%2Fddev%20IS_DDEV_PROJECT&type=code

**Comment by rfay** [comment]
This was fixed in 
* https://github.com/ddev/ddev/pull/4843
