### ISSUE TITLE
`printenv` lists environment variable; `echo $SOMEVAR` shows that it's blank

### ISSUE THREAD

**Issue by vegantriathlete** [ddev/ddev#4842]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected Behavior

Setting an environment variable through .ddev/config.yaml

web_environment:
- MYVAR = something

should create a variable that PHP can access

### Actual Behavior

When I `ddev ssh` into the container, a `printenv` shows the variables I have set as well as their values. But if I `echo` any one of those variables they come up blank. Instead of using the .ddev/config.yaml I ended up using .ddev/web-build/Dockerfile and added the lines to `ENV MYVAR=something` and then all worked as desired.

### Steps To Reproduce

1. Edit the .ddev/config.yaml and make sure you have the lines similar to
```
web_environment:
- MYVAR = someting
```
2. `ddev ssh` into the container
3. `printenv`
4. Notice that your variable is there and has the value you set
5. `echo $MYVAR` and notice that it comes up blank

### Anything else?

I am running MacOS and I have mutagen enabled

**Comment by rfay** [comment]
Hi @vegantriathlete - long time no see!

The correct syntax will be 
```
web_environment:
  - MYVAR=something
```

Please try that. 

More details with the other ways you can do environment variables at https://ddev.readthedocs.io/en/latest/users/extend/customization-extendibility/#providing-custom-environment-variables-to-a-container

**Comment by rfay** [comment]
I hope that gave you what you need. Happy to continue the conversation here or elsewhere. Closing for now.
