### ISSUE TITLE
typo3 is getting wrong mail configuration

### ISSUE THREAD

**Issue by DavidBruchmann** [ddev/ddev#4844]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Run a Diagnostic and Paste Link Here

https://gist.github.com/DavidBruchmann/392bfea3ecfade01afb51abcffdc906f

### Expected Behavior

A fresh installed (minimal) TYPO3 v12 in ddev should have a working Mail configuration for mailhog.

### Actual Behavior

Currently the settings produce a blocking error 503 message in frontend and backend:

> Unsupported sendmail command flags "/usr/local/bin/mailhog sendmail test@example.org --smtp-addr 127.0.0.1:1025"; must be one of "-bs" or "-t" but can include additional flags.

```

    'MAIL' => [
        'transport' => 'sendmail',
        'transport_sendmail_command' => '/usr/local/bin/mailhog sendmail test@example.org --smtp-addr 127.0.0.1:1025',
        'transport_smtp_encrypt' => '',
        'transport_smtp_password' => '',
        'transport_smtp_server' => '',
        'transport_smtp_username' => '',
    ],
```

### Steps To Reproduce

ddev config --project-type=typo3 --docroot=public --create-docroot --php-version 8.1
ddev composer req "typo3/minimal:^12"
ddev composer req helhum/typo3-console
ddev typo3 install:setup
ddev launch

### Anything else?

No additional.php was created.
But while restarting after debugging the file additional.php was created with this mail configuration:
```
            // This mail configuration sends all emails to mailhog
            'MAIL' => [
                'transport' => 'smtp',
                'transport_smtp_encrypt' => false,
                'transport_smtp_server' => 'localhost:1025',
            ],
```
So actually I'm not sure where the wrong configuration is coming from.

**Comment by rfay** [comment]
Hi @DavidBruchmann - It looks to me like you've never done a `ddev restart` after installing TYPO3, so DDEV didn't know to add your settings. 

Could you please see if you can recreate this problem with the TYPO3 quickstart, https://ddev.readthedocs.io/en/latest/users/quickstart/#typo3 ?

**Comment by DavidBruchmann** [comment]
yes @rfay I did try that and it's working with restart.
I'm still curious where the wrong configuration is coming from, but that's certainly no direct ddev issue.

the quickstart is working, there the mail configuration is missing completely in settings.php.
