### ISSUE TITLE
Add docs and automated testing for Orbstack

### ISSUE THREAD

**Issue by rfay** [ddev/ddev#4858]
Casual users have reported good results with Orbstack as an alternative to Docker Desktop or Colima on macOS, https://orbstack.dev/

See https://discord.com/channels/664580571770388500/1090234521091309648/1090234521091309648

We should probably try it out, maybe add automated testing, add it as an option for a docker provider.

**Comment by highermath** [comment]
Is this something that we need to do? With both Colima and Orbstack, we expect them to do what  Docker does, and presumably they test for compatibility. Don't misunderstand, I think that it is awesome that we give this level of support, as long as we can afford the resources to do it.

I've only had one compatibility issue using Colima, and that was on a non-ddev project. It was reported and resolved.

Also, we should not lose site of the fact that Orbstack is a bit of a pig in a poke. They are specific when they say that the beta is free. We don't know what they plan once they get out of beta, but it is clear that they plan to monetize it. Maybe they'll have a free version for devs, and maybe not.

**Comment by rfay** [comment]
Docker Desktop is also not free and hasn't been for some time. Monetizing projects is fine. The goal with DDEV is to make things as useful as possible, and this may be useful.

**Comment by highermath** [comment]
FWIW, they are proposing $8/mo. for devs. I made a counterproposal of $10/yr. We'll see what happens.

**Comment by rfay** [comment]
I just tried out Orbstack on mac Apple Silicon and it passed my trivial tests with DDEV with flying colors, and was really, really fast. I had mutagen turned on... We should support it. 

* #5113

**Comment by cmuench** [comment]
We test it on several Mac's (Intel and M1/M2) for weeks now. It's super stable and we had zero crashes. Docker for Mac is much more unstable.

**Comment by thamas** [comment]
Someone who knows these environments using/switching to OrbStack could be trivial. But for us others it would be nice to have a _step-by-step guide_ in DDEV's documentation about what should be done if we want to try/use it (with existing projects). Thanks!

**Comment by cmuench** [comment]
@thamas 
In my case I did snapshots of the DB in my project.
Then I installed OrbStack (Docker for Mac can still be installed but should be stopped).
The I did a `ddev snapshot restore` in my project which "imports" the DB again.
As I know the OrbStack team works on a way to import existing docker volumes.

You are right. It's trivial but we should document it.

**Comment by rfay** [comment]
Migration is actually there... but just in the context of Docker Desktop to Colima, https://ddev--5156.org.readthedocs.build/en/5156/users/install/docker-installation/#migrating-projects-from-docker-desktop-to-colima

I guess that basic topic should be moved someplace more general.

**Comment by thamas** [comment]
Thanks @cmuench @rfay!

**Comment by rfay** [comment]
* https://github.com/ddev/ddev/pull/5158

**Comment by rfay** [comment]
Actually, I'm going to close that and instead use it as an example for today's contributor training, https://ddev.com/blog/contributor-training/

**Comment by rfay** [comment]
Discussed licensing for test runners in their Discord, https://discord.com/channels/1106380155536035840/1106380156030959648/1131278402314318044

**Comment by rfay** [comment]
Related: 
* https://github.com/ddev/ddev/pull/5293

**Comment by rfay** [comment]
Buildkite info about locking between two runner agents: https://buildkite.com/docs/tutorials/parallel-builds

**Comment by rfay** [comment]
DDEV Foundation ordered 3 Apple Silicon 16GB Mac Minis today. We'll get them set up when they arrive.

**Comment by froboy** [comment]
ObrStack has a pricing page now (not sure how new this is) https://orbstack.dev/pricing.

**Comment by GaelPQCQ** [comment]
It is similar to what Docker is proposing, the only free alternative is Colima.
On another note, I upgraded Orbstack to 1.1.0 today and so far nothing broke (with DDEV).
