### ISSUE TITLE
Make ddev-drupal-contrib add-on official

### ISSUE THREAD

**Issue by weitzman** [ddev/ddev#4860]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

- Standardize local development of contrib modules
- Align local development approach with what the DA is using in its CI of these projects

### Describe your solution

It lives at [ddev-drupal-contrib](https://github.com/weitzman/ddev-drupal-contrib). Lets make it official once folks are happy with the docs and tests.

**Comment by rfay** [comment]
Say the word when you think it has enough traction to move it over.

**Comment by rfay** [comment]
Saw your note in Discord, will get to it!

**Comment by rfay** [comment]
@weitzman you're invited as admin to the ddevlocal org, please transfer the add-on there when you're ready, then I'll move it to ddev org.

**Comment by rfay** [comment]
Moved, now time to change all the names :) Thanks for the great contribution and for maintaining it.
