### ISSUE TITLE
Job description needed for a co-maintainer for the DDEV Project

### ISSUE THREAD

**Issue by selwynpolit** [ddev/ddev#4867]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

Yes, We need to have a backup person to Randy

### Describe your solution

Go developer who knows Linux, Bash, Drupal, Docker

**Comment by rfay** [comment]
Your review requested @selwynpolit - https://36860f41.ddev-com-front-end.pages.dev/blog/maintainer-job-description/ - thanks for the issue.
