### ISSUE TITLE
WSL2: Xdebug may not work with Docker Desktop 4.18.0+ due to change to *.docker.internal

### ISSUE THREAD

**Issue by rfay** [ddev/ddev#4879]
In Docker Desktop 4.19.0 they made adding `*.docker.internal` to the hosts file an option, when it had been standard for years.

As a result, xdebug, at least on DD 4.19.0 Windows/WSL2, seems to be broken. 

We may be able to work around this in DDEV. 

Opened 
* https://github.com/docker/for-win/issues/13463

Enabling the addition to /etc/hosts may fix this.

**Comment by kdgeorgiev** [comment]
Hey rfay,

What error do you get on the xdebug ?

It seems the xdebug issue may affect MacOS.If we downgrade to 4.18 then the xdebug works just fine.

**Comment by rfay** [comment]
I didn't think it would affect macOS! Thanks for your report. This is going to be a bit of work to sort out. 

Our macOS test runners are updated to 4.19.0 Docker Desktop and they're passing the tests OK.  WSL2 runners are also OK now that I clicked the checkboxes.

**Comment by kdgeorgiev** [comment]
Hey rfay,

This is the macОs issue https://github.com/docker/for-mac/issues/6833 I've created for now. I will do more logs tomorrow including the DDEV HEAD and it won't be a problem as I will be doing test tomorrow on 4.19.

If you wish you can take a look at some of the output. This issue appeared from 4.18 to 4.19 DD update.

**Comment by rfay** [comment]
Do you have Colima installed as well? Is it possible you have some confusion going between the two? 192.168.65.2 is the host.docker.internal that one would expect to see with Colima.

**Comment by rfay** [comment]
I just tested xdebug with PhpStorm and Docker Desktop 4.19.0 on macOS and had no trouble. For me, 

```
$ ddev exec ping -c 1 host.docker.internal
PING host.docker.internal (192.168.65.254) 56(84) bytes of data.
64 bytes from 192.168.65.254 (192.168.65.254): icmp_seq=1 ttl=62 time=2.55 ms
```

I think it would be best for you to open a new issue or come on over to [Discord](https://discord.gg/hCZFfAMc5k) to discuss the problem you're having, I'd love to get to the bottom of it, but don't think it's related to this issue. Please do check to see if there's confusion about colima being installed/used, and when you come to discord, please come with the output of `ddev debug test` as a gist on gist.github.com, or as a file.

**Comment by kdgeorgiev** [comment]
Thanks!
I did create a issue about this in the macos github page. Let me check the Colima conflict.After I've tried the Colima confusion I will collect the ddev debug test before coming to the Discord.

**Comment by kdgeorgiev** [comment]
Ups.. wrong GitHub issue opened. I got confused yesterday with repos. Closing the issue. It's not relevant to the product.

**Comment by rfay** [comment]
I'm not sure where you are at with this @kdgeorgiev , but again, happy to help, probably in Discord or another issue. The issue you opened in the docker/for-mac repo (https://github.com/docker/for-mac/issues/6833) has not been closed, you'll want to close it if it's irrelevant.

**Comment by rfay** [comment]
I just manually tested TestDdevXdebugEnabled on an WSL2/Ubuntu 20.04 WSL2 instance and DD 4.19.0. It succeeded just fine. It may be that this is a more powerful machine. This test was done without requiring the `*.docker.internal` to be enabled.

**Comment by morvy** [comment]
Sorry for silly question, but what is this issue about? I have Docker Desktop 4.20.1 on Win11 and I had no issues with xdebug. I see there is a config in Docker Desktop right in General tab under WSL2:

**Add the \*.docker.internal names to the host's etc/hosts file (Requires password)**
`Lets you resolve *.docker.internal DNS names from both the host and your containers.`

I don't have it checked but I have those 3 hostnames in my hosts file. It was added by previous version of DD, and I remember I reinstalled OS recently and I had DD 4.19

**Comment by rfay** [comment]
Yes, Docker Desktop doesn't clean up what it's done in the past with the hosts file.

You do *not* need to check that box

As you see, I had your same experience in https://github.com/ddev/ddev/issues/4879#issuecomment-1555451233, everything working fine. 

I'll close this now; as explained in https://github.com/docker/for-win/issues/13463#issuecomment-1545994035 this wasn't as big an issue as thought. There have been random reports of trouble, we'll just have to sort them out.
