### ISSUE TITLE
ADD autocomplete project names #completion

### ISSUE THREAD

**Issue by allanlaal** [ddev/ddev#4880]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

there are lots of projects in `ddev list` with long names and common prefixes on my pc

### Describe your solution

I type `ddev command` and type a letter and hit Tab
I get a list of project names that match

### Describe alternatives

using the mouse -- oh the humanity!

### Additional context

not to be confused with `ddev completion`, which works well

**Comment by rfay** [comment]
I don't think this is easy to do, but a contribution is welcome. It sure would be nice!

**Comment by GuySartorelli** [comment]
I've raised https://github.com/ddev/ddev/pull/5732 to address this. Not sure where to put tests and there's an open question there for what (if anything) to do with the `--select` flag. Details in PR description.
