### ISSUE TITLE
Pantheon provider example: "Please 'ddev auth ssh' before running this command" should only be checked when pushing

### ISSUE THREAD

**Issue by stephencapellic** [ddev/ddev#4882]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

I was having a discussion with @rfay about Pantheon authentication. Due to this requirement in the pantheon.yaml provider file I was under the impression that I needed SSH authentication.

### Describe your solution

Randy suggested that this requirement may be obsolete. He suggested I remove the following line from pantheon.yaml:

`ssh-add -l >/dev/null || ( echo "Please 'ddev auth ssh' before running this command." && exit 1 )`

I remove the above line and then I did:

`ddev pull pantheon`

I was logged in via the machine token and the provider script completed without issue! Yay, SSH auth is no longer needed!

The script and the help text for https://github.com/ddev/ddev/blob/master/docs/content/users/providers/pantheon.md should be updated accordingly.

**Comment by rfay** [comment]
It seems that `terminus remote:drush ddev-pantheon-push.dev -- sql-drop -y` in the *push* part does in fact require ssh auth. 

But that means we ought to check only on the *push* part, instead of the general auth part.

**Comment by stephencapellic** [comment]
@rfay Yeah, I only tested the "pull" to be clear. Thanks!!

**Comment by rfay** [comment]
Looks like it can work!
* https://github.com/ddev/ddev/pull/4883
