### ISSUE TITLE
`mkcert` not found on Arch

### ISSUE THREAD

**Issue by Data5tream** [ddev/ddev#4884]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Output of `ddev debug test`

<details><summary>Expand `ddev debug test` diagnostic information</summary>

```
[COPY-PASTE HERE THE OUTPUT OF `ddev debug test`]
```
</details>         

### Expected Behavior

The [install guide for arch linux](https://ddev.readthedocs.io/en/stable/users/install/ddev-installation/#linux) can be followed as-is.

### Actual Behavior

The guide tells the user that they should run `mkcert -install` as a one-time initialization when installing on arch linux. The guide never tells the user to explicitly install `mkcert` and the `ddev-bin` package doesn't include `mkcert` as dependency:
```
paru -Si ddev-bin                       
Repository      : aur
Name            : ddev-bin
Version         : 1.21.6-1
Description     : DDEV: a local web development environment
URL             : https://github.com/ddev/ddev
AUR URL         : https://aur.archlinux.org/packages/ddev-bin
Groups          : None
Licenses        : Apache 2
Provides        : ddev
Depends On      : docker
Make Deps       : None
Check Deps      : None
Optional Deps   : bash-completion
Conflicts With  : ddev
Maintainer      : cweagans
Votes           : 11
Popularity      : 0.868024
First Submitted : Mon, 30 Apr 2018 19:42:17 +0000
Last Modified   : Fri, 10 Mar 2023 19:37:59 +0000
Out Of Date     : No
```

### Steps To Reproduce

On a arch install without `mkcert` follow the [install guide](https://ddev.readthedocs.io/en/stable/users/install/ddev-installation/#linux):

1. `paru/yay/whatever ddev-bin`
2. `mkcert -install`

**Comment by rfay** [comment]
A docs PR would be welcome. You can just click the pencil icon in the upper right of https://ddev.readthedocs.io/en/latest/users/install/ddev-installation/ - or do a PR to add mkcert as a dependency of ddev-bin. Maybe the dependency got lost a year or two ago when we started using goreleaser for arch packages. https://github.com/ddev/ddev/blob/cd8d78a5d6244f4029774f5e134c4ef9cb64b6c4/.goreleaser.yml#L280-L297
