### ISSUE TITLE
`config.*yaml` files are gitignored, possibly breaking add-ons

### ISSUE THREAD

**Issue by tyler36** [ddev/ddev#4893]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Output of `ddev debug test`

By default, DDEV ignores config files with `/config.*.y*ml` in `./.ddev/.gitignore`.

However, some recent addons require the config file to function correctly. 2 recent examples are:

- [ddev-selenium-standalone-chrome](https://github.com/ddev/ddev-selenium-standalone-chrome) sets required ENVs
- [ddev-drupal-contrib](https://github.com/weitzman/ddev-drupal-contrib) symlinks a folder on `post-start`

Developers that clone these projects using these addons must remember the addon's name and re-install the addons to restore functionality. 

### Expected Behavior

Addon functionality should be maintained OOTB from cloning. Failing that, DDEV should suggest reinstalling the addons.

### Actual Behavior

Config files are missing so functionality is lost.
I'm required to type `ddev get list` to remember how to spell `ddev/ddev-selenium-standalone-chrome`

### Anything else?

I know DDEV `1.22` includes lots of addon-specific things so perhaps this is already address.

**Comment by rfay** [comment]
Thanks for the good thinking here. I'm not sure what the right answer is. Originally `config.*.yaml` were mostly added for local additions, but obviously that changed with add-ons. This affects ddev-platformsh rather significantly also. 

Perhaps add-ons that introduce a specific `config.*.yaml` could have a particular pattern, or perhaps we should have an `addon-config.yaml` ?

**Comment by tyler36** [comment]
> Originally config.*.yaml were mostly added for local additions, but obviously that changed with add-ons. This affects ddev-platformsh rather significantly also.

Cloud services such as Gitpod and Codespaces would also be affected.

**Comment by rfay** [comment]
We don't usually use `config.*.yaml` for those, but interested in hearing more.

**Comment by tyler36** [comment]
Sorry, I mean when using projects in cloud environments. 
Last week I was out of office, so I used Gitpod for some projects which also happened to be using the addons mentioned above.

**Comment by rfay** [comment]
OK, understood. I don't think gitpod is any different from local in this case. Thanks for the suggestions here.

**Comment by rfay** [comment]
@tyler36 what do you think about changing the .gitignore so that `config.local.yaml` is gitignored but nothing else? It seems like a super-simple approach that shouldn't affect most people. A bit of docs maintenance to do.

**Comment by tyler36** [comment]
> what do you think about changing the .gitignore so that config.local.yaml is gitignored but nothing else?

Is there a reason to rename the file? Why not target only the current file?

```diff
- /config.*.y*ml
+ /config.yml
```

... and announce DDEV now "supports commiting config files to help keep your projects in sync across platforms and teams."

**Comment by rfay** [comment]
I wasn't talking about renaming any files. I was suggesting that instead of gitignoring /config.*.yaml we gitignore *only* /config.local.yaml.

**Comment by rfay** [comment]
@tyler36 I'd love it if you could review 
* https://github.com/ddev/ddev/pull/4923

and see if it accomplishes what you were hoping.

**Comment by tyler36** [comment]
@rfay  Thank you. Resolves my original issue for new projects I start.

**Comment by tyler36** [comment]
Oh, it's `#ddev-generated` managed.
So it updates all my projects when using post- #4923 DDEV . Thats so cool!

**Comment by jcandan** [comment]
@tyler36, I'm surprised to find that these files marked `#ddev-generated` are not git-ignored, _nor_ are they regenerated on `ddev config --auto` or `ddev restart` or something.

```
.ddev/commands/host/core-version
.ddev/docker-compose.selenium-chrome.yaml
.ddev/docker-compose.selenium-chrome_extras.yaml
```

Seems I can safely ignore `.ddev/xhprof/xhprof_prepend.php` at the project `.gitignore` as it _does_ get generated.

Thoughts on this? Should we consider a DDEV ticket to support ensuring add-on-provided files get generated and are git-ignored?

**Comment by rfay** [comment]
Hi @jcandan - `core-version` is not provided by ddev and docker-compose.selenium-chorme* is not provided by DDEV. I'm sure they're provided by [ddev/ddev-selenium-chrome.](https://github.com/ddev/ddev-selenium-standalone-chrome)

They are intended to be checked in. Add-ons are intended to be checked in. But please don't comment on an ancient issue that is intended to be about `config.*.yaml`, instead open a new one or come over to the Discord to discuss.

Here the `#ddev-generated` tells `ddev-selenium-chrome` that it can replace those files on upgrade.
