### ISSUE TITLE
Set custom permissions on mounted volumes in web container

### ISSUE THREAD

**Issue by MurzNN** [ddev/ddev#4899]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

I have to mount `/var/log` directory to the "web" container, to share the logs with another container.
But Docker has no way to specify an owner and permissions of a mounted volume.

So, the mounted volume by default has "root:root" ownership and "755" permissions, that leads to failed start of "supervisord" daemon:
```
   Server started
   Loading custom entrypoint config from /mnt/ddev_config/web-entrypoint.d
   + echo 'Server started'
   + unset PHP_IDE_CONFIG
   + ddev_python_setup
   + set -e
   + '[' nginx-fpm = nginx-gunicorn ']'
   + set +e
   + ddev_custom_init_scripts
   + echo 'Loading custom entrypoint config from /mnt/ddev_config/web-entrypoint.d'
   + ls '/mnt/ddev_config/web-entrypoint.d/*.sh'
   + exec /usr/bin/supervisord -n -c /etc/supervisor/supervisord-nginx-fpm.conf
   Traceback (most recent call last):
     File "/usr/bin/supervisord", line 33, in <module>
       sys.exit(load_entry_point('supervisor==4.2.2', 'console_scripts', 'supervisord')())
     File "/usr/lib/python3/dist-packages/supervisor/supervisord.py", line 359, in main
       go(options)
     File "/usr/lib/python3/dist-packages/supervisor/supervisord.py", line 369, in go
       d.main()
     File "/usr/lib/python3/dist-packages/supervisor/supervisord.py", line 72, in main
       self.options.make_logger()
     File "/usr/lib/python3/dist-packages/supervisor/options.py", line 1494, in make_logger
       loggers.handle_file(
     File "/usr/lib/python3/dist-packages/supervisor/loggers.py", line 419, in handle_file
       handler = RotatingFileHandler(filename, 'a', maxbytes, backups)
     File "/usr/lib/python3/dist-packages/supervisor/loggers.py", line 213, in __init__
       FileHandler.__init__(self, filename, mode)
     File "/usr/lib/python3/dist-packages/supervisor/loggers.py", line 160, in __init__
       self.stream = open(filename, mode)
   PermissionError: [Errno 13] Permission denied: '/var/log/supervisord.log'
```

### Describe your solution

Would be good to add an option to enforce the permission of a directory before the startup of the supervisord (and other services).
Something like:
```yaml
web_enforce_directory_ownership:
  - "/var/log": "${USER}:root"
web_enforce_directory_permissions:
  - "/var/log": "777"
```

**Comment by MurzNN** [comment]
I've workarounded this problem via creating a custom startup script:
```
services:
  web:
    volumes:
      - type: bind
        source: ./grafana/syslog-ng/syslog-startup.sh
        target: /syslog-startup.sh
      - web-logs-data:/var/log
    command: 'bash /syslog-startup.sh'
```
and the script:
```
#!/bin/bash

sudo chmod 757 /var/log
sleep infinity
```

**Comment by MurzNN** [comment]
> I don't recommend that you use a bind mount. A docker volume would be better.
I do use a docker volume:
```yaml
services:
  web:
    volumes:
#      - type: bind
#      source: ./syslog-ng/syslog-startup.sh
#        target: /syslog-startup.sh
      - web-logs-data:/var/log
```

> I don't recommend that you use the explicit /var/log in your container, but instead use a directory that is used only for your purposes (/var/log is used by many applications, so you could have some interesting problems)

I need to capture all system log files, not only my custom ones, including `nginx` and `apache2` logs. So it's easier to mount the entire `/var/log` than altering the `nginx` and `apache2` config files, right?

> DDEV has to do this with some mounted Docker volumes, so does it before mounting the volume, see 

This doesn't make any sense, because the mounted directory permission is stored inside the mounted volume (and kept after unmounting, like the owner and permissions of a "root" directory of the mounting volume) not inside the parent filesystem.

**Comment by rfay** [comment]
I don't foresee DDEV adding a feature to solve this challenge for your particular situation. As you have already discovered, you have an enormous number of resources available, including all the docker-compose can do, and all that you can do with hooks.

**Comment by MurzNN** [comment]
> You may not be aware that DDEV does not run syslogd, and that all important logs (like nginx/apache/php-fpm) actually go to the container logs (stdout on process 1, or /proc/1/fd/1). So your goal of capturing all logs may not be viable.

`php-fpm` - yes, but I don't see `nginx` logs in the container logs.

**Comment by MurzNN** [comment]
And I found a more better solution - just put the script into the `.ddev/web-entrypoint.d`:
```bash
#!/bin/bash

# A workaround to make mounted `/var/log` volume writable for supervisord.
sudo chmod 777 /var/log
[ -d /var/log/nginx ] || sudo mkdir /var/log/nginx
sudo chmod 777 /var/log/nginx
[ -d /var/log/apache2 ] || sudo mkdir /var/log/apache2
sudo chmod 777 /var/log/apache2
```

**Comment by rfay** [comment]
There you go!

**Comment by rfay** [comment]
IIRC the nginx *access* logs are in fact dumped into /var/log, but not the error logs, not sure. Access logs would make a huge mess of `ddev logs`.

**Comment by MurzNN** [comment]
So, the approach with `.ddev/web-entrypoint.d/ddev-grafana-fix-log-directory-permissions.sh` works well, let's close the issue.

**Comment by ylynfatt** [comment]
This was helpful and worked for me also. Thanks @MurzNN
