### ISSUE TITLE
Executing Mutagen Sync from Inside the DDEV Container

### ISSUE THREAD

**Issue by XjSv** [ddev/ddev#4918]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

According to the recommendations we should use all binaries and libraries from inside the container to ensure consistency in versions. e.g composer, yarn, node, etc.

It is also recommended that after a heavy operation, `ddev mutagen sync` should be executed to ensure that all files are up to date. 

I have implemented .git/hooks/post-checkout using:
```
#!/bin/bash
ddev mutagen sync || true
```
Which works great because git operations happen on the host machine and `ddev mutagen` is available.

Unfortunately when attempting to automate this process when running `ddev composer install` or `ddev npm install` his does not work as expected. The mutagen binary does not seem to be available from inside the ddev container.

This is my setup:

Composer.json
```
"scripts": {
  "post-install-cmd": [
      "./scripts/mutagen-sync.sh"
  ],
  "post-update-cmd": [
      "./scripts/mutagen-sync.sh"
  ],
},
```

Package.json
```
"scripts": {
   "postinstall": "./scripts/mutagen-sync.sh"
},
```

mutagen-sync.sh
```
#!/bin/bash
mutagen sync || true
```

When executing `ddev composer install` or `ddev npm install` I get a command not found error.

```
/scripts/mutagen-sync.sh: line 9: mutagen: command not found
```

### Describe your solution

The solution right now would be to just run `ddev mutagen sync` manually after running `ddev composer install` or `ddev npm install`.

### Describe alternatives

It would be nice to have a way to execute mutagen sync from inside the container in order to automate the process using post-install hooks in composer, npm, etc.

### Additional context

[Node.js, npm, nvm, and Yarn](https://ddev.readthedocs.io/en/latest/users/usage/cli/#nodejs-npm-nvm-and-yarn)
[Syncing After yarn, npm, and pnpm Actions](https://ddev.readthedocs.io/en/latest/users/install/performance/#syncing-after-yarn-npm-and-pnpm-actions)

**Comment by rfay** [comment]
For composer, don't you just want a post-composer hook? https://ddev.readthedocs.io/en/latest/users/configuration/hooks/#supported-command-hooks

There aren't post-npm hooks, but they'd probably not be hard to add. 

There is a mutagen agent running inside the container, but I don't think it has a UI. 

It would be super easy to add a `ddev mutagen sync` to the `npm` shell command, https://github.com/ddev/ddev/blob/1862f2b9fe65083f72ed7cc90dc6b03d11afa7cb/pkg/ddevapp/global_dotddev_assets/commands/web/npm#L4

**Comment by XjSv** [comment]
Perfect, thank you for clarifying that, I must have missed the `post-composer` hook.
Also I have no issues with adding `ddev mutagen sync` to the npm shell command, I was stuck in tunnel vision and did not consider this option.

I will implement and test now. 

If you want to add the post-npm hooks, in order to make getting started easier, that would be great too but consider my problem solved. Thanks again!

**Comment by XjSv** [comment]
@rfay I think I misunderstood your last point about adding `ddev mutagen sync` to the npm shell command. I thought you recommended I do that myself in my own custom npm command. 
After testing, it's obvious that any `ddev mutagen sync` there will not work. Or maybe I'm not executing it correctly.

**Comment by rfay** [comment]
I guess you're right since `ddev npm` is a *web* command, it can't do that. However, you could create a *host* command that did the `ddev npm` and then the `ddev mutagen sync`.

One thing to note is that you don't normally care about the state of your host-side npm stuff - it's used only inside the container, so perhaps mutagen sync can take its own sweet time (which is usually not much) and you don't have to worry about it.

**Comment by XjSv** [comment]
You are right since we I am not running npm from the host, there seems no need to manually run `mutagen sync`. The operation is already happening inside the container. 

Additionally the host command also did the trick although as you pointed out it seems redundant now.

My NPM host command just for reference: 
```bash
#!/usr/bin/env bash

## Description: Run npm inside the web container
## Usage: npm [flags] [args]
## Example: "ddev npm install" or "ddev npm update"
## ExecRaw: true
## HostWorkingDir: true

npm "$@"

ddev mutagen sync || true
```

**Comment by rfay** [comment]
Thanks, I'll go ahead and close this for now, but happy to continue the conversation. I do think the caveats about mutagen may still be a little too strong given most people's experience. The one that can make a huge difference is changing git branch on the host with a massive change, because the container version doesn't work right until the change is fully synced. But composer stuff normally only matters inside the container, same with npm/yarn. So if those take 5 seconds to sync it's no big deal.
