### ISSUE TITLE
`ddev snapshot restore` subcommand is not available if not in project context

### ISSUE THREAD

**Issue by rpkoller** [ddev/ddev#4940]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

I ran into that yesterday. I tried to call `ddev snapshot restore --latest` and the output was the following: 

```
$> ddev snapshot restore --latest 
Error: unknown flag: --latest
Usage:
  ddev snapshot [projectname projectname...] [flags]

Examples:
ddev snapshot
ddev snapshot --name some_descriptive_name
ddev snapshot --cleanup
ddev snapshot --cleanup -y
ddev snapshot --list
ddev snapshot --all

Flags:
  -a, --all           Snapshot all projects. Will start the project if it is stopped or paused
  -C, --cleanup       Cleanup snapshots
  -h, --help          help for snapshot
  -l, --list          List snapshots
  -n, --name string   provide a name for the snapshot
  -y, --yes           Yes - skip confirmation prompt

Global Flags:
  -j, --json-output   If true, user-oriented output will be in JSON format.
```

it looked like `restore --latest`. @rfay had the suspicion i might have updated to an outdated version of head even though i've upgraded to the latest. but turned out in another step `.ddev/config.yml` git removed on a git operation so there was no registered project. 

### Describe your solution

I would suggest the output for a command, no matter if it is a command (for example ddev snapshot) or a subcommand (for example ddev snapshot restore --latest)  should be the same 

`Unable to get project(s) []: could not find a project in /Users/rkoller/Sites/test. Have you run 'ddev config'? Please specify a project name or change directories: no .ddev/config.yaml file was found in this directory or any parent`

**Comment by rfay** [comment]
Here's the problem, https://github.com/ddev/ddev/blob/bbb2caca961784aa68d0511848823464a009f14b/cmd/ddev/cmd/snapshot_restore.go#L71-L77

The "restore" command is added only if we have an app that doesn't have database disabled. 

This isn't a general problem, and `ddev snapshot restore` shouldn't work when not in project context anyway. OTOH, neither should `ddev snapshot`. 

In general I don't currently think this is worth putting too much effort into, although it sure was confusing!

**Comment by rfay** [comment]
it would probably be easy to provide a warning like `ddev snapshot`'s warning with a one-line change. But not sure it's worth messing with.

**Comment by rfay** [comment]
Maybe we'll pick this up someday but it doesn't seem like a very big issue right now. Thanks for pointing it out!
