### ISSUE TITLE
Add a `ddev dbeaver` command

### ISSUE THREAD

**Issue by MakerTim** [ddev/ddev#4947]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

Just like `ddev heidisql` but then for dbeaver.
dbeaver is multi OS, linux/mac/win & has really nice features.

### Describe your solution

New file in the `ddev/pkg/ddevapp/global_dotddev_assets/commands/host/` directory.
Where it will start dbeaver whenever possible.

Win
* /mnt/c/Program\ Files/DBeaver/dbeaver.exe
* /c/Program Files/DBeaver/dbeaver.exe
Linux
* dbeaver-ce
Mac:
?

**Comment by rfay** [comment]
A contribution is welcome. Please take a look at the other database browser commands in your global .ddev/commands/host directory, and model on those. The details about the annotations you'll want to add are at https://ddev.readthedocs.io/en/latest/users/extend/custom-commands/

**Comment by rfay** [comment]
As discussed in #4947 we'd love to see you create an add-on that will be able to mature in a faster-moving place. Since this requires support in so many places, and add-on is a better place for it to mature.

**Comment by gitressa** [comment]
Thanks! It looks like this been released, but I don't see it under https://github.com/ddev/ddev/releases ...

**Comment by stasadev** [comment]
@gitressa currently only in master, and the next DDEV v1.22.4 will likely be released this week.

**Comment by gitressa** [comment]
Thanks for a fast answer @stasadev. The reason I asked is that I am trying to override DDEV 1.22.3 with a DDEV in `.local/bin`, but the standard 1.22.3 gives med `ddev dbeaver` ... I'll continue in #5451.

**Comment by stasadev** [comment]
There is no harm in replacing `/usr/bin/ddev` with another binary in Ubuntu.
And in the next release of ddev, when you do `sudo apt update`, it will be automatically replaced with the new one.
This way you don't have to worry if you forget to change the binary.

**Comment by gitressa** [comment]
Thanks, let's find the best method in #5451.

`ddev dbeaver` is included in https://ddev.readthedocs.io/en/latest/users/usage/database-management/#database-guis, I suppose because it follows dev-version (which is called `master` in DDEV?).

**Comment by stasadev** [comment]
Answered in another thread. that's because `ddev dbeaver` is a custom command, it doesn't look up for ddev itself.
