### ISSUE TITLE
Expose database type as variable for use in scripts

### ISSUE THREAD

**Issue by tyler36** [ddev/ddev#4954]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

DDEV supports MySQL/Maria and Postgres databases.

However, DDEV does not directly expose the database type (mysql, postgres) for use in scripts and addons.
This prevents developers from easily generating database URLs programatically: EG. `mysql://db:db@db/db`

I noticed a recent [update ](https://github.com/ddev/ddev-drupal-contrib/blob/main/config.contrib.yaml) to [ddev/ddev-drupal-contrib](https://github.com/ddev/ddev-drupal-contrib) sets a variable for testing:

```yaml
SIMPLETEST_DB=mysql://db:db@db/db
```
 
My company has standardized on postgres and I would like match the testing env to production env.

### Describe your solution

I would like to be able to re-write the code to the following:

```diff
-  - SIMPLETEST_DB=mysql://db:db@db/db
+  - SIMPLETEST_DB=${DDEV_DATABASE_TYPE}://db:db@db/db
```

`DDEV_DATABASE_TYPE` should be either:
- `mysql` for MySql and Maria dbs
- `postgres` for [Postgres dbs](https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-CONNSTRING)

### Describe alternatives

I am aware that I can remove the `ddev_generated` text and make the changes myself to the file. 
But this prevents me getting the latest changes and must be done manually for each project.

### Additional context

If this feature request is accepted, it would be nice if addons could overrite the setting somehow.
There is also a [Mongo database addon](https://github.com/ddev/ddev-mongo) so it should be able to set `mongo` as a valid type.

**Comment by rfay** [comment]
DDEV_DATABASE is already set inside the container, for example, `DDEV_DATABASE=mariadb:10.4`

**Comment by tyler36** [comment]
Yes, its set as a database type and version string. 

I think it is more useful for addon/script developers to have this exposed as 2 variables:

- DDEV_DATABASE_TYPE
- DDEV_DATABASE_VERSION

EG. `SIMPLETEST_DB=mysql://db:db@db/db`

In `ddev-drupal-contrib` the value is set in [`config.contrib.yaml`](https://github.com/ddev/ddev-drupal-contrib/blob/main/config.contrib.yaml)
In `ddev-selenium-standalone-chrome` the value is set in [`config.selenium-standalone-chrome.yaml`](https://github.com/ddev/ddev-selenium-standalone-chrome/blob/main/config.selenium-standalone-chrome.yaml)

**Comment by rfay** [comment]
Would using `${DDEV_DATABASE%%:*}` work for you? That's fine if you're using it in bash context. 

Your direct request would be a pretty easy PR though, just adding what you want to https://github.com/ddev/ddev/blob/f4acf1e2b93d547cf2461fcd5b82ea87b5687dab/pkg/ddevapp/ddevapp.go#L1931-L1975
