### ISSUE TITLE
Remove `processor_path_lzw` from TYPO3 v12 additional.php

### ISSUE THREAD

**Issue by peter-neumann-dev** [ddev/ddev#4955]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected Behavior

Consider removing `processor_path_lzw` from the [additional configuration](https://github.com/ddev/ddev/blob/master/pkg/ddevapp/typo3/AdditionalConfiguration.php#L29) TYPO3 template for v12 and higher. 

The setting was removed for TYPO3 v12: https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.0/Breaking-97797-GFXSettingProcessor_path_lzwRemoved.html

I guess the setting does not harm anything in TYPO2 v12 if it will stay there, but maybe there is an easy way to use different templates per TYPO3 version.

### Actual Behavior

In TYPO3 v12 setups the option exisits in `config/system/additional.php`

**Comment by rfay** [comment]
@gilbertsoft what do you think about this?

**Comment by gilbertsoft** [comment]
> @gilbertsoft what do you think about this?

Yeah, valid of course. Will take care, but does not harm at the moment. Thanks for the hint @peter-neumann-dev .

**Comment by rfay** [comment]
Per above:
> I guess the setting does not harm anything in TYPO2 v12 if it will stay there, but maybe there is an easy way to use different templates per TYPO3 version.

I'm going to go ahead and close this for now, happy to continue the conversation here or elsewhere.
