### ISSUE TITLE
Add new project type `drupal` for drupal8+ (and support drupal11)

### ISSUE THREAD

**Issue by gitressa** [ddev/ddev#4957]
## Problem

You cannot create a new Drupal 11 project:

```
$ ddev config --docroot=web --project-type=drupal11
apptype must be one of backdrop, craftcms, drupal10, drupal6, drupal7, drupal8, drupal9, laravel, magento, magento2, php, shopware6, typo3, wordpress
```

## Solution

- Unify Drupal 8+ under a `drupal` project type, following the recommended PHP version for the current release (Drupal 10 and PHP 8.1)  

OR

- Add Drupal 11 as a project type option, requiring a [minimum PHP version of 8.2](https://www.drupal.org/project/drupal/issues/3330874).

### Describe alternatives

Use Drupal 10 config.

**Comment by gitressa** [comment]
Drupal 11 is really 10.2, so this task can wait, see [Clarify that current version 11 is 10.2](https://www.drupal.org/project/drupal/issues/3363770).

**Comment by rfay** [comment]
I'd really like to just change drupal8+ to "drupal"

**Comment by gitressa** [comment]
Yes, that would simplify things. There are different [PHP requirements](https://www.drupal.org/docs/getting-started/system-requirements/php-requirements) though ... [Databases](https://www.drupal.org/docs/system-requirements/database-server-requirements) are more straightforward, only PostgreSQL with D9/10+ and D10/12+ differ.

With a single `drupal` config for Drupal 8/9/10/11, the default PHP could follow the current official release, currently Drupal 10 on PHP 8.1.

Then, the individual DDEV project can always bump up or down the PHP version. Also, `drupal6`could stay as a config option, but not get exposed as an option after running `ddev config`?

## With Drupal 11 added
`Project Type [backdrop, craftcms, drupal11, drupal6, drupal7, drupal8, drupal9, drupal10, laravel, magento, magento2, php, shopware6, typo3, wordpress]`

Less config options:

## Drupal 8/9/10/11 unified, `drupal6` not shown
`Project Type [backdrop, craftcms, drupal, drupal7, laravel, magento, magento2, php, shopware6, typo3, wordpress]` 

What do you think?

**Comment by Slsharma** [comment]
use project type drupal10 and then ddev composer create drupal/recommended-project:^11@dev it will install drupal 11 on local.

ddev config --project-type=drupal10 --docroot=web --create-docroot
ddev start
ddev composer create drupal/recommended-project:^11@dev
ddev composer require drush/drush
ddev drush site:install --account-name=admin --account-pass=admin -y
ddev drush uli
ddev launch

**Comment by gitressa** [comment]
Thanks, but I know that the `drupal10` type works.

**Comment by rpkoller** [comment]
referring to @gitressa 's comment with the comparison between `d11 added` and `drupal 8/9/10/11 unified` (is there a way here on github to refer to comment with something like a comment number like in the d.o issue queue to make the referral more explicit? )

the first option `Drupal 11 added` has the downside that drupal  occupies 6 out of 15 available options. on the plus side that way things are explicit and it is possible to have specific php and database settings for the drupal version in question. not sure to what degree settings differ in between major versions. 

the second option `Drupal 8/9/10/11 unified, drupal6` not shown. i am not sure if it is a good idea hiding drupal6. for one there are still quite a few sites that need to be migrated to drupal 9+ and people might have the need to have a drupal 6 site locally and removing the drupal6 option would take away that convenience. plus from a usability perspective having only the option drupal and drupal7 would make me think. what does drupal refer to? 

there might be a third option. i am not sure if it would be an over complication of things but would it make sense to add another configuration step to `ddev config` instead? that each cms has  a single option for the project type step. and in case the cms has several different sub types like drupal has, have another step after setting the project type where the user is able to choose in between the different available version numbers? that way the general project type list would be concise in case one of the options has more than a single sub option. but i am uncertain if drupal alone would justify introducing another configuration step?

**Comment by gitressa** [comment]
I usually copy the [date link](https://github.com/ddev/ddev/issues/4957#issuecomment-1570046955) and use that. But yes, a number would be nice :) 

> i am not sure if it is a good idea hiding drupal6. for one there are still quite a few sites that need to be migrated to drupal 9+ and people might have the need to have a drupal 6 site locally and removing the drupal6 option would take away that convenience

I get your point, but from my perspective, out of the many, many Drupal projects being started every day, a very small fraction is Drupal 6. And this minority can probably quickly verify that DDEV supports D6 by searching for "Drupal 6 DDEV", and after that use `--project-type=drupal6`.

About the granular config method, I like to keep things simple (I just discovered `ddev config --auto`, yay!) and adding another step doesn't sound too appealing ...

**Comment by tyler36** [comment]
> And this minority can probably quickly verify that DDEV supports D6 by searching for "Drupal 6 DDEV", and after that use --project-type=drupal6.

FWIW, Drupal 6 was end of life [2016-02-24](https://www.drupal.org/project/d6lts). My vote would be to remove it from the list but keep the "project-type" code untouched. The quickstart guides can show it's available.

**Comment by rfay** [comment]
The reason we keep things like drupal6 around is so people can rescue unmaintained websites. For example, we still have support for PHP 5.6, MySQL 5.5, MariaDB 5.5, all incredibly old and gone, but they're super valuable to folks who inherit an unmaintained site. 

Your point that it could be removed from `ddev config --project-type` is valid though, but to date, almost anything that is supported in config.yaml has an equivalent representation in `ddev config`.

**Comment by gitressa** [comment]
I agree, and never suggested removal of `drupal6`, so removing Drupal 6 configuration is not up for debate:

> Also, `drupal6` could stay as a config option, but not get exposed as an option after running `ddev config`?

I do understand that up until now, all available projects were listed. But the list is ballooning, and I think slimming down the options would be an improvement.

**Comment by rfay** [comment]
Thanks!

**Comment by rfay** [comment]
Removed from v1.23 milestone, but please let us know when D11 starts to get explicit usage, and we'll add it in, probably with project type 'drupal'.

**Comment by rpkoller** [comment]
i was just curious tonight and created a drupal11 project type locally and ran `make`. work out well. 

one thought about having a single project type drupal. having just `drupal`covering 8+ might be problematic. the minimum php version as well the settings.php file differs across versions. not sure if that would work out well. for people on the latest version no problem at all but for those trying to set up a drupal 8 or 9 site for migrations it might have some surprises ready.

but how about use `drupal`for all supported versions of drupal 8+ which is equal to drupal 10 and 11. that way it might work and all the discontinued versions could have dedicated project types (drupal6, drupal7, drupal8, drupal9)

**Comment by gitressa** [comment]
That makes sense @rpkoller, something like this?

`drupal` = For Drupal 10 and Drupal 11, until their PHP/DB requirements diverge.

Keep `drupal6`, `drupal7`, `drupal8`, `drupal9`, `drupal10` as options, but only show `drupal7` and `drupal` after running `ddev config`:

`Project Type [backdrop, craftcms, django4, drupal, drupal7, laravel, magento, magento2, php, python, shopware6, silverstripe, typo3, wordpress] (php):`

**Comment by rpkoller** [comment]
> Keep drupal6, drupal7, drupal8, drupal9, drupal10 as options, but only show drupal7 and drupal after running ddev config:
i am not sure if i would keep the drupal10 project type. that would be inconsistent having `drupal` and `drupal10`where `drupal`covers version 10 and 11. if `drupal`and `drupal7` would be the way forward i would only provide a dedicated project types that are not supported anymore and discontinued. 

and how about something like: 

`ddev config`: 
Project Type [backdrop, craftcms, django4, drupal, drupal7, laravel, magento, magento2, php, python, shopware6, silverstripe, typo3, wordpress] (php):

`ddev config --all`
Project Project Type [backdrop, craftcms, django4, drupal, drupal 6, drupal7, , drupal8, drupal9, laravel, magento, magento2, php, python, shopware6, silverstripe, typo3, wordpress] (php):

that the `--all flag shows all the deprecated legacy project types? and when `ddev config` is run an informal line could be added right before the list of available project types that by entering `ddev config --all` (or however it is called) you could get all the additional legacy project types could be listed?

**Comment by gitressa** [comment]
Sure, let's wait with `drupal10`, until its requirements diverges from Drupal 11. And great idea with the `--all` parameter.

**Comment by gitressa** [comment]
> Drupal 11 will be released in mid-June, late July or early December 2024.

https://www.drupal.org/project/drupal/issues/3265677

Perhaps `drupal` can be an option at some point, since Drupal 11 support will soon be relevant?

**Comment by rfay** [comment]
Saw those timelines go by, thanks. That's a pretty wide swath of time. I wasn't convinced that that announcement helped any of us!

I will put this on the "right after v1.23.0" milestone. Thanks for watching it!

**Comment by rpkoller** [comment]
or would it make sense to have a two step process. create a drupal 11 project type just now ( i've already built a version locally a few weeks back, it should be easy to reproduce and I could create a PR for) and do the suggestion distinguishing supported (ddev config) and discontinued  versions (for example ddev config --all) in a follow up to reduce the sheer number of in particular different drupal versions you see on every execution of ddev config?

**Comment by tyler36** [comment]
Since modern Drupal (8+) are composer-based projects, I wonder if DDEV could read the version from `composer.json` and set PHP and DB version appropriately?

**Comment by rfay** [comment]
A minor difficulty here is that unless people explicitly set the php version and database version to match the variant of Drupal, we can't really detect it. In our normal workflows people do a `ddev config` before they do a `ddev composer create`. We've used the project type at `ddev config` time to detect the proper requirements for the project type. 

One way around this is basically how every other CMS is set up... Just use the current highest version's defaults.

**Comment by rfay** [comment]
I would really appreciate if all you Drupal 11 folk could test and review https://github.com/ddev/ddev/pull/5991#issuecomment-2008555360
