### ISSUE TITLE
Promote ddev config --auto, which simplifies all the way

### ISSUE THREAD

**Issue by gitressa** [ddev/ddev#4963]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

I really like how minimal the DDEV start project command `ddev config` is. When I started using DDEV I found the [excellent documentation](https://ddev.readthedocs.io/en/latest/users/usage/commands/#config), where the example almost cannot be any simpler:

```
ddev config --docroot=web --project-type=drupal8
```

### Describe your solution

The final improvements would be:

- Allow omitting `docroot`: Check if a folder named  _web_ is present and if yes, assume `--docroot=web`
- Allow omitting `project-type`: Scan _composer.json_ file if present, and if found with Drupal content assume `--project-type=drupal8`

I was extremely impressed, when I realized that this is already possible with the `--auto` parameter:

```
$ ddev config --auto
Creating a new ddev project config in the current directory (/home/user/test) 
Once completed, your configuration will be written to /home/user/test/.ddev/config.yaml
 
Configuring a drupal10 codebase with docroot 'web' at /home/user/test/web 
Configuration complete. You may now run 'ddev start'. 
```

### Remaining tasks

Update the documentation.

**Comment by rfay** [comment]
Thanks, but I think people just get too confused when things aren't already in place. If you're configuring a project where the docroot doesn't yet exist, everything goes wrong. Closing for now, appreciate the suggestion, happy to continue the conversation here or elsewhere.
