### ISSUE TITLE
ddev installation completed, error running command (docker not installed)

### ISSUE THREAD

**Issue by ScarlettDefender** [ddev/ddev#4966]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Output of `ddev debug test`

<details><summary>Expand `ddev debug test` diagnostic information</summary>

```
[COPY-PASTE HERE THE OUTPUT OF `ddev debug test`]
```
</details>         
![image](https://github.com/ddev/ddev/assets/130278941/cb236447-e893-4050-9cf4-3186c291cb26)

### Expected Behavior

After the installation of ddev is complete, the run ddev normally, run ddev followed by parameters error, for example, ddev -v

### Actual Behavior

After the installation of ddev is complete, the run ddev normally, run ddev followed by parameters error, for example, ddev -v
![Uploading image.png…]()

**Comment by rfay** [comment]
Hi @ScarlettDefender - You have to have a docker provider to use DDEV, as it's telling you.  Please see https://ddev.readthedocs.io/en/latest/users/install/docker-installation/

**Comment by rfay** [comment]
Happy to talk more. I'm sure you'll be fine when you get a docker provider going.
