### ISSUE TITLE
Drupal 10.1 nginx configuration change

### ISSUE THREAD

**Issue by rfay** [ddev/ddev#4972]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

Per https://www.drupal.org/node/2888767#nginx-php-fpm there's a potential change required for Drupal 10.1 nginx config. 

### Describe your solution

Change the config.

It would be nice if we could make it completely compatible with 10.0 as well.

**Comment by catch56** [comment]
The ddev config looks fine for Drupal 10.1

```
# js and css always loaded
    location ~* \.(js|css)$ {
        try_files $uri @rewrite;
        expires -1;
        log_not_found off;
    }
    ```
    
    This passes through all js and css - so it catches core aggregates, including with https://www.drupal.org/project/drupal/issues/3027639
    
 I also tested locally with ddev and 10.1.0, and aggregation is working, files created on disk etc.
 
 If there was a stricter directory pattern, it might have needed a change, but the blanket rule for me at least seems fine.

**Comment by rfay** [comment]
Based on @catch56 report I'm going to close this for now, thanks!
