### ISSUE TITLE
Add the ability to assign a single-character flag to `ddev launch` for a service added by an addon

### ISSUE THREAD

**Issue by rpkoller** [ddev/ddev#4976]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

At the moment only the services  shipped  per default with DDEV (PHPMyAdmin and Mailhog) have a launch command  available: 
![Screen Shot 2023-06-13 at 22 32 27](https://github.com/ddev/ddev/assets/1665422/add902db-881f-4850-bfb5-c71893e8a43a)
Services added via an addon are missing that option (ArangoDB in that case). But for services that have a webui it would be a very helpful and handy addition 

### Describe your solution

As discussed with @rfay on discord one option would be to either add the setting to the services docker-compose file or to the config.[addon name].yaml. with the hotkey being a single character the list of available 24 characters is already run out with ddev official and contrib addons. the easiest approach might be leave the choice which hotkey to pick up to the addon maintainer. in case a user downloads an addon that has the same hotkey like an already installed addon and its provided service then an error message could be shown on startup pointing the user to the yaml file to update. that way the choice would be up to the user. every other solution would complicate things unnecessarily. and a certain technical expertise for updating a yaml file could be expected from the user.

**Comment by rfay** [comment]
This would be nice!

**Comment by GuySartorelli** [comment]
One thing to consider with this: How are collisions handled? If community addon A and B both use `ddev launch -z`, do I get an error when installing whichever is installed second? Does whichever one was installed first get to keep the flag? Or is it whichever is first alphabetically? etc

**Comment by tyler36** [comment]
I've created a few addons, offical and not yet-offical, and this is something I would like to see. But I'm not sure of the best solution.

One potential solution is PR #5525 . 
This would allow develper to launch a specific port (if known), and addon maintainer to write commands that launch the port.

**Comment by stasadev** [comment]
We already have `ddev launch :port`, and use it successfully in add-ons with if-else condition.

https://github.com/ddev/ddev-phpmyadmin/blob/main/commands/host/phpmyadmin

Another thing to make it better is to have ability to launch service like this:

```
ddev launch -s phpmyadmin
```

So it will pick up the port automatically, and you won't need if-else.

Closing this issue in favor of:

- #6394
