### ISSUE TITLE
Add a ddev remove ddev/my-add-on command, or document manual method

### ISSUE THREAD

**Issue by gitressa** [ddev/ddev#4980]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

After installing an add-on, for example with `ddev get ddev/ddev-drupal9-solr` you might want to remove it again, but there is no `ddev remove` command or a documented method on how to remove an add-on manually.

### Describe your solution

Add a `ddev remove` command for add-ons, or document how to do it manually.

### Describe alternatives

In the meantime, is the best method to create another project, check it in with Git, `ddev get` the add-on, do a diff to spot the changes, and manually remove it from the project in question?

**Comment by tyler36** [comment]
This is covered in #4891 which includes the new command `ddev get --remove <addonname>`.
I've been using this DDEV for the last month and its super useful.

**Comment by tyler36** [comment]
Please close the issue if #4891 covers it, or add a comment expanding on the issue if not. 😄

**Comment by gitressa** [comment]
Thanks for clearing that up @tyler36! That's exactly what I was looking for, so closing this issue as it is a duplicate.
