### ISSUE TITLE
[docs] Don't use third-party fonts from fonts.googleapis.com on ddev.readthedocs.io

### ISSUE THREAD

**Issue by gitressa** [ddev/ddev#4982]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem

Respecting user privacy have been getting a lot of well deserved attention during the last few years. It is recommended to not use third-party fonts, to respect user privacy, and not hand over personal data to third-parties.

### Steps To Reproduce

1. Visit https://ddev.readthedocs.io/
1. Open uBlock Origin
1. See that the third-party font provider fonts.googleapis.com is used

### Solution

- Check if the [Privacy plugin](https://squidfunk.github.io/mkdocs-material/setup/ensuring-data-privacy/) (The heart icon = "Sponsors only") has been released, after [reaching the target of $14,000](https://squidfunk.github.io/mkdocs-material/insiders/)
- [Enable the Privacy plugin](https://github.com/ddev/ddev/pull/5463), and  embed fonts in the theme, phasing out third-party fonts, respecting user privacy

**Comment by rfay** [comment]
@gitressa would you mind poking around to figure out how the fonts are being pulled in?

**Comment by gitressa** [comment]
Sure @rfay, I found this:

> [squidfunk](https://github.com/squidfunk) commented [Nov 12, 2022](https://github.com/mkdocs/mkdocs/issues/2171#issuecomment-1312447974)
> 
> If you're a user of [Material for MkDocs](https://squidfunk.github.io/mkdocs-material/), enabling the [built-in privacy plugin](https://squidfunk.github.io/mkdocs-material/setup/ensuring-data-privacy/#built-in-privacy-plugin) will automatically download and replace all [external assets](https://squidfunk.github.io/mkdocs-material/setup/ensuring-data-privacy/#external-assets) that are found in the resulting HTML with local versions. This means that https://github.com/mkdocs/mkdocs/issues/2171#issuecomment-871565889 is also solved, since all external files found in the HTML are handled - no additional vendoring necessary.

This is the Material for MkDocs setting: [Built-in privacy plugin](https://squidfunk.github.io/mkdocs-material/setup/ensuring-data-privacy/#built-in-privacy-plugin).

I see `mkdocs-material>=9` in https://github.com/alexbogias/ddev/blob/master/docs/mkdocs-pip-requirements, so maybe possible?

**Comment by rfay** [comment]
Want to try a PR?

**Comment by gitressa** [comment]
Great that you're open for this @rfay. I don't have time to look at it right now, but anyone else should feel free to create a PR in the meantime.

**Comment by rfay** [comment]
OK @gitressa please reopen when you have time to look into it, thanks!

**Comment by gitressa** [comment]
I finally took stab at this @rfay. It ought to be as easy as adding two lines, which should install the privacy plug-in.

> The privacy plugin is built into Material for MkDocs and doesn't need to be installed.

https://squidfunk.github.io/mkdocs-material/plugins/privacy/#configuration

The test fails, though:

```
ERROR   -  Config value 'plugins': The "privacy" plugin is not installed

Aborted with 1 configuration errors!i
```

But ... you need to be a sponsor for this feature: https://squidfunk.github.io/mkdocs-material/insiders/

It's the heart icon, right below the title, which I understood after I found this: https://github.com/squidfunk/mkdocs-material/issues/5317#issuecomment-1494374819

**Comment by rfay** [comment]
We'd be happy to sponsor, but can't use something that requires one person's ssh key to be able to do a build.

**Comment by gitressa** [comment]
Thanks for clarifying @rfay. The next step in their fund raising is [$14,000 – Goat's Horn](https://squidfunk.github.io/mkdocs-material/insiders/#14000-goats-horn) where Privacy plugin will become available for everyone.

Current funding is at $13,860 a month, perhaps one more reason to considering sponsoring?

**Comment by rfay** [comment]
I need to review our upstream contributions, so will remember this. We can sponsor without using their too-hard-to-manage private build setup. Thanks!

**Comment by gitressa** [comment]
Sounds great, funding open source projects is important, as we all know :-)

**Comment by rfay** [comment]
DDEV is once again a sponsor of mkdocs-material

<img width="1045" alt="image" src="https://github.com/ddev/ddev/assets/112444/589efca5-5538-4c4d-a473-3608fd163f0e">

**Comment by gitressa** [comment]
Great, thanks @rfay! If the key thing is still a problem, and since I don't know the details, would you consider creating an issue about it at https://github.com/squidfunk/mkdocs-material/issues?

It might also help other projects to get this sorted out.

**Comment by rfay** [comment]
The issue was discussed in
* https://github.com/squidfunk/mkdocs-material/issues/4104

**Comment by gitressa** [comment]
Thanks, I have subscribed to that issue, and hope Insiders' workflow will be improved, or the goal of 14,000 reached, whatever comes first.

**Comment by gitressa** [comment]
I just checked, and the current funding is $14,720 a month (congratulations!) which should mean that the Built-in privacy plugin is now available to be enabled.

> ... those features were part of Insiders, but are now generally available and can be used by all users.

https://squidfunk.github.io/mkdocs-material/insiders/#14000-goats-horn

**Comment by gitressa** [comment]
Sure! It's here, and just reopening: https://github.com/ddev/ddev/pull/5463.
