### ISSUE TITLE
ddev bootstraps Drupal for chrome developer .map requests

### ISSUE THREAD

**Issue by mdance** [ddev/ddev#4989]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Output of `ddev debug test`

<details><summary>Expand `ddev debug test` diagnostic information</summary>

```
[COPY-PASTE HERE THE OUTPUT OF `ddev debug test`]
```
</details>         

### Expected Behavior

When you have chrome developer tools open, it will make requests for .map files for css/js assets (https://blog.praveen.science/avoiding-http-404-for-map-files-when-using-minified-css/)

These 404s are all bootstrapping drupal and should be ignored

### Actual Behavior

These requests are bootstrapping drupal only to return a 404

### Anything else?

Adding the following to .ddev/nginx_full/nginx-site.conf resolves the issue:

location ~* \.(map)$ {
       try_files $uri =404;
       expires -1;
       log_not_found off;
   }

**Comment by rfay** [comment]
DDEV has nothing to do with "bootstrapping" Drupal. 

If you have a link to describe why we should change that stanza in the config, the various configs are in https://github.com/ddev/ddev/tree/3c8bd593b9eded8223d3b7647e7f3e056b4c47d8/pkg/ddevapp/webserver_config_assets

A PR with the suggestion you make is welcome (to the right Drupal versions) if you have justifications for the change. The existing nginx config has been stable and used by many thousands of devs for years.

**Comment by mdance** [comment]
Yes, I apologize for having the Drupal blinders on, but should def be addressed, right when I'm trying to debug a high priority bugfix, my debugger gets bombarded with garbage .map requests that should never cause a full Drupal bootstrap

**Comment by rfay** [comment]
DDEV has separate nginx configs for Drupal, so it's an easy fix. 

Related:
* https://github.com/ddev/ddev/issues/4972

**Comment by rfay** [comment]
A simple PR would be great. probably just add map files to the nginx configs (and apache) in https://github.com/ddev/ddev/tree/3c8bd593b9eded8223d3b7647e7f3e056b4c47d8/pkg/ddevapp/webserver_config_assets

As @chrisfromredfin says about https://github.com/ddev/ddev/blob/3c8bd593b9eded8223d3b7647e7f3e056b4c47d8/pkg/ddevapp/webserver_config_assets/nginx-site-drupal10.conf#L93-L98

I imagine we can just add map there. You can test all this without a PR by just adding the updated nginx config to .ddev/nginx_full, see https://ddev.readthedocs.io/en/latest/users/extend/customization-extendibility/#custom-nginx-configuration

If you like what you get, we can go from there.

**Comment by rfay** [comment]
I'm happy to have a contribution for this, and happy to continue the conversation here or elsewhere, but closing this for now.
