### ISSUE TITLE
Suggestion: Alternate "Flags" annotation

### ISSUE THREAD

**Issue by jigarius** [ddev/ddev#5001]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

Currently, if you have 5 flags, the `Flags` annotation becomes extremely long and difficult to read.

### Describe your solution

It would be great if we could have 1 flag per annotation. For example:

## Suggestion 1

```
## Flags: [
##   {"Name":"flag1","Shorthand":"f1","Usage":"flag1 usage"}
##   {"Name":"flag2","Usage":"flag2 usage"}
## ]
```

## Suggestion 2

```
## Flag: {"Name":"flag1","Shorthand":"f1","Usage":"flag1 usage"}
## Flag: {"Name":"flag2","Usage":"flag2 usage"}
```

## Suggestion 3

```
## Flag:foo: {"Shorthand":"f1", "Usage":"flag1 usage"}
## Flag:bar: {"Usage":"flag2 usage"}
```

**Comment by rfay** [comment]
@jigarius can I ask why you're reading it? I personally don't think it would help most people to make this change, and the number of people who have read this annotation anywhere ever is probably less than 10?

**Comment by jigarius** [comment]
I was reading it for maintaining the lines that were added by my colleague. Next, I added 3 flags, the line became extremely long.

**Comment by gilbertsoft** [comment]
I suggest to finish my work on the YAML support which will increase readability.

**Comment by rfay** [comment]
I don't expect to pursue this.
