### ISSUE TITLE
promote mkalkbrenner/ddev-solr to official add-on

### ISSUE THREAD

**Issue by mkalkbrenner** [ddev/ddev#5002]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

I finished https://github.com/mkalkbrenner/ddev-solr
Should we promote it to be the official add-on? 

### Describe your solution

it is easier to use ;-)

**Comment by rfay** [comment]
Fantastic thanks! I'll try this out in coming days and I'm sure it will be great promoted to DDEV. I think we'll want to rename ddev-drupal9-solr or something. Casually looking through the add-on (but not testing it) I have some minor suggestions but the key thing is your willingness to maintain this. Thanks!

**Comment by mkalkbrenner** [comment]
The ddev service here has nothing special fur Drupal, except the corresponding section in the README.
That's why I now put the solarium part above, which is generic PHP and which is the library used by all frameworks (including Drupal):
https://github.com/solariumphp/solarium

So from my point, this add-on should become the default for Solr for any use with PHP.
I can offer to extend the README to show how to upload a configset using solarium.
And how to leverege DDEV could be added to https://solarium.readthedocs.io/en/stable/

**Comment by rfay** [comment]
Closing in favor of 
* https://github.com/mkalkbrenner/ddev-solr/issues/17
