### ISSUE TITLE
Feature Request: Disable internet access from containers

### ISSUE THREAD

**Issue by ashermiddleton** [ddev/ddev#5009]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

I'm trying to figure out the best way to go about blocking a ddev project from public internet for outbound and inbound traffic. I'm working with a large legacy codebase and I want to avoid any side effects with hardcoded information. In essence I want the project to run completely offline and have access to the local network only, with all outbound requests to public FQDNs/IPs failing/being dropped.

I've researched ways to make this happen with docker-compose but I don't understand how to do this cleanly without interfering with ddev's functionality. Is this something that is possible? I feel like I'm missing something easy. I still want to be able to access the internet on Windows and in WSL.

### Describe your solution

Having an easily reproducible/configurable ddev way to do this would be useful, for example with: `ddev config --force-offline=true`

### Additional context

I'm on:
- Windows 11
- WSL 2
- DDEV v1.21.6 running docker inside WSL2

**Comment by rfay** [comment]
DDEV doesn't care whether the containers have access to the internet at all, I assume that's what you mean here. It will break some features but you already know that (like `ddev composer install` or such things). But I think after initial `ddev start` of a project you should normally be able to work fine. You can test this very easily by just turning off your wifi or other networking. See https://ddev.readthedocs.io/en/latest/users/usage/offline/

What were the techniques that you researched to cut off the docker-compose networking?

**Comment by ashermiddleton** [comment]
I think the problem comes down to a lack of (my) understanding with how the Docker networking works. I've tried for example creating `.ddev/docker-compose.networks.yaml`:
```networks:
  ddev_default:
    internal: true
    name: ddev_default
```
Which seemingly has no effect.
To try and be more concise - my aim is for `ddev exec ping google.com` to timeout but `ddev exec ping db` to work. I've combed through the ddev and docker-compose docs to try and figure out how to configure this but keep coming up empty-handed.

**Comment by rfay** [comment]
I don't think that the internal docker networks are related to what you want. What OS and Docker Provider are you using?

**Comment by rfay** [comment]
I changed the title to "Feature Request: Disable internet access from containers". Is that what you want?

**Comment by ashermiddleton** [comment]
I believe that's more inline with what I'm after, yes.

I'm on:
 - Windows 11 `10.0.22621.1848`
 - WSL 2 `1.2.5.0`
 - DDEV `1.21.6` running docker inside WSL2 (Ubuntu)

**Comment by rfay** [comment]
I tried the CAP_DROP technique from https://threatpicture.com/blog/restrict-internet-access-docker-container/ with 
```yaml
services:
  web:
    cap_drop:
      - NET_RAW
      - NET_ADMIN
```

and it doesn't seem to get what you want. I'm still able to curl google.com.

**Comment by rfay** [comment]
I tried `ddev poweroff && docker network create ddev_default --internal && ddev start` but the network is *really* internal then; the host can't get to it so you can't use a web browser.

**Comment by rfay** [comment]
I tried the cheap `dns` option in https://stackoverflow.com/questions/39913757/restrict-internet-access-docker-container

docker-compose.nointernet.yaml:
``yaml
services:
  web:
    dns: 127.0.0.5
```

That's a pretty silly point-to-no-working-dns option. But it only prevents name lookup, not actual access.

**Comment by rfay** [comment]
I'm sure you could install iptables inside the web container and do an exact formula that would work for you, but it's going to require some work. https://stackoverflow.com/a/75835572/215713

Easier would be `ufw`, `webimage_extra_packages: [ufw]` and then do some configuration for it in a post-start hook. https://wiki.ubuntu.com/UncomplicatedFirewall

**Comment by rfay** [comment]
If your simple goal is just 
> To try and be more concise - my aim is for ddev exec ping google.com to timeout but ddev exec ping db to work. I've combed through the ddev and docker-compose docs to try and figure out how to configure this but keep coming up empty-handed.

Then https://github.com/ddev/ddev/issues/5009#issuecomment-1601937440 will work

**Comment by ashermiddleton** [comment]
I got a little bit further with
```
# docker-compose.blockinternet.yaml
services:
    web:
        cap_add:
            -   NET_ADMIN
```
and
```
# config.yaml
webimage_extra_packages: [ufw, rsyslog]
hooks:
    post-start:
        - exec: "sudo ufw enable"
        - exec: "sudo ufw default deny outgoing"
        - exec: "sudo ufw allow out to 10.0.0.0/8"
        - exec: "sudo ufw allow out to 192.168.0.0/16"
        - exec: "sudo ufw allow out to 172.16.0.0/12"
        - exec: "sudo ufw allow out to 127.0.0.0/8"
```

However couldn't get the webserver to work and would always get a 504 timeout with nginx.

The cheap DNS trick will have to do for now, thanks for the help. This would still be a useful built-in feature I feel, but doesn't seem easy enough to implement for its priority.

**Comment by rfay** [comment]
Closing for now, happy to continue the conversation here or elsewhere.

**Comment by ollyollyollyltd** [comment]
> I got a little bit further with
> 
> ```
> # docker-compose.blockinternet.yaml
> services:
>     web:
>         cap_add:
>             -   NET_ADMIN
> ```
> 
> and
> 
> ```
> # config.yaml
> webimage_extra_packages: [ufw]
> hooks:
>     post-start:
>         - exec: "sudo ufw enable"
>         - exec: "sudo ufw default deny outgoing"
>         - exec: "sudo ufw allow out to 10.0.0.0/8"
>         - exec: "sudo ufw allow out to 192.168.0.0/16"
>         - exec: "sudo ufw allow out to 172.16.0.0/12"
>         - exec: "sudo ufw allow out to 127.0.0.0/8"
> ```
> 
> However couldn't get the webserver to work and would always get a 504 timeout with nginx.
> 
> The cheap DNS trick will have to do for now, thanks for the help. This would still be a useful built-in feature I feel, but doesn't seem easy enough to implement for its priority.

I got this working by adding `- exec: "sudo ufw default deny outgoing"` to the `post-start` commands.  I can now access from my browser on the host.  SSHing into the container allows me to ping / curl the host and the DB container, but won't let me `curl google.com`.

**Comment by mjot** [comment]
The solution by @ollyollyollyltd worked fine, until I installed ddev 1.23.4 today.

Since the update to 1.23.4 I get the following errors:

```
ERROR: problem running ufw-init
iptables-restore v1.8.9 (nf_tables): Could not fetch rule set generation id: Permission denied (you must be root)
iptables-restore v1.8.9 (nf_tables): Could not fetch rule set generation id: Permission denied (you must be root)
iptables-restore v1.8.9 (nf_tables): Could not fetch rule set generation id: Permission denied (you must be root)
iptables-restore v1.8.9 (nf_tables): Could not fetch rule set generation id: Permission denied (you must be root)
iptables-restore v1.8.9 (nf_tables): Could not fetch rule set generation id: Permission denied (you must be root)
iptables-restore v1.8.9 (nf_tables): Could not fetch rule set generation id: Permission denied (you must be root)
iptables-restore v1.8.9 (nf_tables): Could not fetch rule set generation id: Permission denied (you must be root)
iptables-restore v1.8.9 (nf_tables): Could not fetch rule set generation id: Permission denied (you must be root)
iptables-restore v1.8.9 (nf_tables): Could not fetch rule set generation id: Permission denied (you must be root)
iptables-restore v1.8.9 (nf_tables): Could not fetch rule set generation id: Permission denied (you must be root)
sysctl: permission denied on key "net.ipv4.conf.all.accept_redirects"
sysctl: permission denied on key "net.ipv4.conf.default.accept_redirects"
sysctl: permission denied on key "net.ipv6.conf.all.accept_redirects"
sysctl: permission denied on key "net.ipv6.conf.default.accept_redirects"
sysctl: permission denied on key "net.ipv4.icmp_echo_ignore_broadcasts"
sysctl: permission denied on key "net.ipv4.icmp_ignore_bogus_error_responses"
sysctl: permission denied on key "net.ipv4.icmp_echo_ignore_all"
sysctl: permission denied on key "net.ipv4.conf.all.log_martians"
sysctl: permission denied on key "net.ipv4.conf.default.log_martians"

Problem loading ipv6 (skipping)
Problem running '/etc/ufw/before.rules'
Problem running '/etc/ufw/after.rules'
Problem running '/etc/ufw/user.rules'

Task failed: Exec command 'sudo ufw enable' in container/service 'web': exit status 1
A task failure does not mean that DDEV failed, but your hook configuration has a command that failed.
WARN: /usr/sbin is world writable!
Default incoming policy changed to 'allow'
(be sure to update your rules accordingly)
WARN: /usr/sbin is world writable!
Default outgoing policy changed to 'deny'
(be sure to update your rules accordingly)
WARN: /usr/sbin is world writable!
WARN: initcaps
[Errno 2] iptables v1.8.9 (nf_tables): Could not fetch rule set generation id: Permission denied (you must be root)

Rules updated
WARN: /usr/sbin is world writable!
WARN: initcaps
[Errno 2] iptables v1.8.9 (nf_tables): Could not fetch rule set generation id: Permission denied (you must be root)

Rules updated
WARN: /usr/sbin is world writable!
WARN: initcaps
[Errno 2] iptables v1.8.9 (nf_tables): Could not fetch rule set generation id: Permission denied (you must be root)

Rules updated
WARN: /usr/sbin is world writable!
WARN: initcaps
[Errno 2] iptables v1.8.9 (nf_tables): Could not fetch rule set generation id: Permission denied (you must be root)

Rules updated
Starting periodic command scheduler: cron.
Restarted test
Your project can be reached at https://test.ddev.site https://127.0.0.1:32860
```

Maybe @rfay has an idea what changed. We use this ufw configuration to scan websites that are probably infected. This feature is very helpful for us.

**Comment by rfay** [comment]
It looks like you need an extra capability for the web service. You can do this by adding a `.ddev/docker-compose.capabilities.yaml` that looks like this:
```
services:
  web:
    cap_add:
      - NET_ADMIN
```

With that I see `sudo ufw enable` working (with the complaint about /usr/sbin, but it's just a warning)

BTW, it would be better to put the hooks like this, it's more performant, easier to read, and easier to write:
```yaml
hooks:
  post-start:
    - exec: |
        sudo ufw enable
        sudo ufw default allow incoming
        sudo ufw default deny outgoing
        sudo ufw allow out to 10.0.0.0/8
        sudo ufw allow out to 192.168.0.0/16
        sudo ufw allow out to 172.16.0.0/12
        sudo ufw allow out to 127.0.0.0/8
```

It would probably be even better if you put those in a script and executed in one place, or used one sudo for the whole thing.

I'd be interested in knowing what version of DDEV you were upgrading *from*, perhaps v1.22.*?

**Comment by mjot** [comment]
Thanks @rfay for your comment.

I have to apologize, it was my mistake. I was already working with the `docker-compose.capabilities.yaml` you mentioned in my other ddev projects. However, I had not yet created this file in the new project I created today after updating.
So that was ultimately the difference as to why it still worked in the old containers and not in the new ones.

So it was not due to the update. I don't think you need the information about the previous version in this case, do you? I wouldn't know if I could get this information anywhere.

I shouldn't work until midnight. Good night. ;-)

BTW: Thanks also for the hint with the different spelling of the commands under exec. :)

**Comment by rfay** [comment]
Oh I hadn't noticed that those instructions for the docker-compose extra were right there in front of both of us :)
