### ISSUE TITLE
`nodejs_version: 14` fails to build on `ddev start` and `/bin/sh: 1: npm: not found`

### ISSUE THREAD

**Issue by finnlewis** [ddev/ddev#5010]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected Behavior

Trying to install node 14 

In .ddev/config.yml setting: 
```
nodejs_version: "14"
```
fails to build.
With: 
```
nodejs_version: "16"
```
it builds fine.

https://ddev.readthedocs.io/en/latest/users/configuration/config/#nodejs_version suggests 14 should be OK, no? 

### Actual Behavior
```


#19 [drud/ddev-webserver:v1.21.5-gcd-drupal-built 7/8] RUN bash /tmp/setup_node.sh >/dev/null && apt-get install -y nodejs >/dev/null
#19 3.480 E: Failed to fetch https://deb.nodesource.com/node_16.x/dists/bullseye/main/binary-amd64/Packages.gz  File has unexpected size (775 != 776). Mirror sync in progress? [IP: 86.189.96.72 443]
#19 3.480    Hashes of expected file:
#19 3.480     - Filesize:776 [weak]
#19 3.480     - SHA256:e5d3c880cdb1ec15f193329e5a3abe68056c59f6026144de4d4b52fcce2131e6
#19 3.480     - SHA1:87f1583949354fe006bc0137a84d8cfe90b0229d [weak]
#19 3.480     - MD5Sum:c881892f3a46cc943e7ff44162cbee62 [weak]
#19 3.480    Release file created at: Wed, 19 Apr 2023 16:10:35 +0000
#19 3.480 E: Some index files failed to download. They have been ignored, or old ones used instead.
#19 ERROR: executor failed running [/bin/sh -c bash /tmp/setup_node.sh >/dev/null && apt-get install -y nodejs >/dev/null]: exit code: 1
------
 > [drud/ddev-webserver:v1.21.5-gcd-drupal-built 7/8] RUN bash /tmp/setup_node.sh >/dev/null && apt-get install -y nodejs >/dev/null:
#19 3.480 E: Failed to fetch https://deb.nodesource.com/node_16.x/dists/bullseye/main/binary-amd64/Packages.gz  File has unexpected size (775 != 776). Mirror sync in progress? [IP: 86.189.96.72 443]
#19 3.480    Hashes of expected file:
#19 3.480     - Filesize:776 [weak]
#19 3.480     - SHA256:e5d3c880cdb1ec15f193329e5a3abe68056c59f6026144de4d4b52fcce2131e6
#19 3.480     - SHA1:87f1583949354fe006bc0137a84d8cfe90b0229d [weak]
#19 3.480     - MD5Sum:c881892f3a46cc943e7ff44162cbee62 [weak]
#19 3.480    Release file created at: Wed, 19 Apr 2023 16:10:35 +0000
#19 3.480 E: Some index files failed to download. They have been ignored, or old ones used instead.
------
', stderr='failed to solve: executor failed running [/bin/sh -c bash /tmp/setup_node.sh >/dev/null && apt-get install -y nodejs >/dev/null]: exit code: 1' 
```

Is this because 14 is no longer in LTS? https://nodejs.dev/en/about/releases/

**Comment by rfay** [comment]
No response, so closing. Feel free to continue the conversation here or elsewhere.

**Comment by finnlewis** [comment]
Hi @rfay , sorry, missed your initial reply. 

I will test again, but odd that I was asking for v 14 and it was trying to download 16, no? 

Failed to fetch https://deb.nodesource.com/node_16.x/dists/bullseye/main/binary-amd64/Packages.gz

We've actually managed to get the things that need node working with a more recent version now (18) which is nice. 

But I will test again to check on a fresh build.

Thanks again!

**Comment by rfay** [comment]
Hmm, you showed actual behavior with it failing on 16 I guess. I only read the failure, and it's as described. 

I just tested again with 

```
ddev config --nodejs-version=14
ddev restart
ddev exec node --version
v14.21.3
```
and it did fine, showing 14.21.3

**Comment by BramDriesen** [comment]
Actually also running into this with a different error.

> ddev config --nodejs-version=14 && ddev restart && ddev exec node --version

Gave me the following

```
#16 DONE 0.0s

#17 [drud/ddev-webserver:v1.21.5-tp-eu-built 8/8] RUN npm install --unsafe-perm=true --global gulp-cli yarn || ( npm config set unsafe-perm true && npm install --global gulp-cli yarn )
#17 0.279 /bin/sh: 1: npm: not found
#17 0.280 /bin/sh: 1: npm: not found
#17 ERROR: executor failed running [/bin/sh -c npm install --unsafe-perm=true --global gulp-cli yarn || ( npm config set unsafe-perm true && npm install --global gulp-cli yarn )]: exit code: 127
------
 > [drud/ddev-webserver:v1.21.5-tp-eu-built 8/8] RUN npm install --unsafe-perm=true --global gulp-cli yarn || ( npm config set unsafe-perm true && npm install --global gulp-cli yarn ):
#17 0.279 /bin/sh: 1: npm: not found
#17 0.280 /bin/sh: 1: npm: not found
------
', stderr='failed to solve: executor failed running [/bin/sh -c npm install --unsafe-perm=true --global gulp-cli yarn || ( npm config set unsafe-perm true && npm install --global gulp-cli yarn )]: exit code: 127'
```

**Comment by rfay** [comment]
Could you please do a `ddev debug refresh` to get back to a sane setup? Or try this on a fresh project, or both? People are using all of the above all the time, and they're tested in automated tests every day.

**Comment by BramDriesen** [comment]
This was on a clean project. I also did a `ddev debug refresh` but no difference.

I ended up using `ddev nvm` for now

**Comment by rfay** [comment]
Would you be willing to do a screenshare call with me so we could see if we can understand this? If so, please come over to Discord and let's do it. https://discord.gg/hCZFfAMc5k 

Also, please clarify what your current problem is. It seems that you changed symptoms along the way?

**Comment by rfay** [comment]
Fixed with `docker buildx prune -a` to clear the docker build cache. 

Apparently this was fallout from your original error, `Failed to fetch https://deb.nodesource.com/node_16.x/dists/bullseye/main/binary-amd64/Packages.gz  File has unexpected size (775 != 776). Mirror sync in progress` and somehow got cached in the build cache.

Please let me know your results.

**Comment by rfay** [comment]
No response, so closing for now. Happy to continue the conversation here or elsewhere, and happy it happened to happen to me.

The answer was cleaning the docker build cache with `docker buildx prune -a`.

**Comment by rmcveigh** [comment]
Hi @rfay, for me, `-a` returns an "unknown shorthand". Do you know what the "longhand" for that param is? I'm on `Docker version 24.0.4, build 3713ee1eea` on a Mac.

**Comment by rmcveigh** [comment]
> Hi @rfay, for me, `-a` returns an "unknown shorthand". Do you know what the "longhand" for that param is? I'm on `Docker version 24.0.4, build 3713ee1eea` on a Mac.

Maybe you meant `docker-buildx`?

**Comment by rmcveigh** [comment]
Note - I'm seeing the issue when attempting to use nodejs version 18. The `/tmp/setup_node.sh` is failing to run with the error:
```
#16 [drud/ddev-webserver:v1.21.5-grls-built 7/8] RUN bash /tmp/setup_node.sh >/dev/null && apt-get install -y nodejs >/dev/null
#16 4.093 W: GPG error: https://packages.sury.org/php bullseye InRelease: Splitting up /var/lib/apt/lists/packages.sury.org_php_dists_bullseye_InRelease into data and signature failed
#16 4.093 E: The repository 'https://packages.sury.org/php bullseye InRelease' is not signed.
#16 ERROR: process "/bin/sh -c bash /tmp/setup_node.sh >/dev/null && apt-get install -y nodejs >/dev/null" did not complete successfully: exit code: 1
------
 > [drud/ddev-webserver:v1.21.5-grls-built 7/8] RUN bash /tmp/setup_node.sh >/dev/null && apt-get install -y nodejs >/dev/null:
#16 4.093 W: GPG error: https://packages.sury.org/php bullseye InRelease: Splitting up /var/lib/apt/lists/packages.sury.org_php_dists_bullseye_InRelease into data and signature failed
#16 4.093 E: The repository 'https://packages.sury.org/php bullseye InRelease' is not signed.
------
', stderr='failed to solve: process "/bin/sh -c bash /tmp/setup_node.sh >/dev/null && apt-get install -y nodejs >/dev/null" did not complete successfully: exit code: 1'
```

**Comment by rfay** [comment]
If you don't have buildx installed, you probably want to install it. If using Docker Desktop, it comes bundled. If not using DD and using homebrew, `brew install docker-buildx`, which will install the plugin. 

There's also an old-school `docker builder prune` command. But I'm not 100% sure it handles the same cache.  Happy to chase this with you over on [Discord](https://[discord](https://discord.gg/hCZFfAMc5k).gg/hCZFfAMc5k) if that helps.

**Comment by rmcveigh** [comment]
> If you don't have buildx installed, you probably want to install it. If using Docker Desktop, it comes bundled. If not using DD and using homebrew, brew install docker-buildx, which will install the plugin.

> There's also an old-school docker builder prune command. But I'm not 100% sure it handles the same cache. Happy to chase this with you over on [Discord](https://%5Bdiscord%5D(https://discord.gg/hCZFfAMc5k).gg/hCZFfAMc5k) if that helps.

I'm using Colima and installed buildx via homebrew. Using `docker-buildx` resolved the `-a` error. The command you suggested was `docker buildx prune -a` rather than `docker-buildx prune -a` FWIW.

> However, your error is something completely different to begin with, `#16 4.093 W: GPG error: https://packages.sury.org/php bullseye InRelease: Splitting up /var/lib/apt/lists/packages.sury.org_php_dists_bullseye_InRelease into data and signature failed`
> 
> There are some upstream issues about this kind of thing in https://github.com/oerdnj/deb.sury.org/issues - but they should all be resolved. But it could be your build cache.

I cleared my cache and followed the troubleshooting guide in the docs with no success. I would like to know if it has something to do with a recent docker image build because I built fresh images this morning using `ddev start` after having deleted my images, cleared colima and removed my `~/.lima `directory.

I could get the build to work once I changed the node version in my config from 18 to 16.

**Comment by rfay** [comment]
> I'm using Colima and installed buildx via homebrew. Using docker-buildx resolved the -a error. The command you suggested was docker buildx prune -a rather than docker-buildx prune -a FWIW.

You must not have the buildx plugin installed correctly; but doesn't matter that you ran it by directly running the binary.

Happy to help, but it would be easier to do it somewhere easier than a probably-unrelated issue in the issue queue. We can do a live debugging event in Discord if you want to and can do screenshare.

**Comment by rfay** [comment]
Plenty of people using colima end up with trouble like this, but https://github.com/abiosoft/colima/discussions/273#discussioncomment-6453101

**Comment by rmcveigh** [comment]
I'll give that a shot. Thanks, @rfay. Sorry that this turned into a conversation that took us down a slightly different road from the original issue. Hopefully, other folks find it helpful, though.
