### ISSUE TITLE
v1.22.0 Test Plan

### ISSUE THREAD

**Issue by rfay** [ddev/ddev#5015]
It's testing time again here in the DDEV factory. We love community help with every item that is interesting or relevant to you, and just *using* the release candidates is hugely helpful, because you may stumble across something in your regular workflow. Please use the latest pre-release for your testing, https://github.com/ddev/ddev/releases

I don't think in general you'll have trouble using this in your daily workflow, so would love you do do that. You can switch back and forth , see [How can I install a specific version of DDEV in the FAQ](https://ddev.readthedocs.io/en/latest/users/basics/faq/).

If you find a bug that you're pretty sure is a bug, then [just open an issue for it](https://github.com/drud/ddev/issues/new?assignees=&labels=&template=Bug_report.md&title=).

To give feedback or ask questions, please just reply on this issue or discuss in [discord](https://discord.gg/hCZFfAMc5k) or any other support channel.

I am maintaining the [provisional release notes for v1.22.0](https://randyfay.notion.site/v1-22-0-Release-notes-0e9d1254f2c04281b4d1f7c6c35ac764) and would love any comments on those.

See [commits since v1.21.6](https://github.com/drud/ddev/compare/v1.21.6...master) and [PRs merged since March 10, 2023](https://github.com/drud/ddev/pulls?q=is%3Apr+is%3Aclosed+merged%3A%3E2023-03-10)

1. Make sure that the DDEV PhpStorm Extension is working fine - There's a [docker-compose bug about COMPOSE_PROJECT_NAME](https://github.com/docker/compose/issues/10593) that might affect our current usage of compose 2.18.1 (and 2.19.1 has other major problems): 
    - [ ] Test Xdebug
    - [ ]  PhpUnit tests. 
2. Verify that upgrading a project from v1.21.6 to v1.22.0 works OK. Especially test with mutagen enabled. It will definitely show recreation of a new mutagen session.
    - [ ] With NFS enabled
    - [ ] With Traefik enabled
    - [ ] With mutagen enabled
    - [ ] With `omit_containers[dba]` globally
    - [ ] With `omit_containers[dba]` in project
4. PhpMyAdmin/dba removal: 
    - [x] Make sure no phpmyadmin images are downloaded or containers are run when using DDEV
    - [x] `ddev launch -p` should give a helpful tip about the phpstorm add-on.
    - [x] Using `ddev get ddev/ddev-phpmyadmin` should provide useful phpmyadmin and `ddev phpmyadmin` command
5. Gitpod: Ordinary manual testing
6. Codespaces: Ordinary manual testing
7. Multiple upload_dirs:
    - [ ] `ddev config --upload-dir` should work as in the past, with deprecation warning
    - [ ] `ddev config --docroot=web --upload-dirs=one,two,../private` should result in 3 upload_dirs in config.yaml; with mutagen all three should be bind-mounted. (`ddev ssh df -T <mountdir>` should show bind-mount)
    - [ ] You should be able to disable the warning about upload_dirs on a project type that doesn't default any and where none are shown
    - [ ] Check especially `ddev config --upload-dirs=cpresources --docroot=web` and `ddev config --upload-dir=cpresources --docroot=web` with craft install, see https://github.com/ddev/ddev/issues/5076
    - [ ] Use of a ` config.*.yaml` which does not change upload_dirs should not result in them being reset
    - [ ] Using `mutagen` with upload_dirs: cpresources should work fine with `ddev composer create` and craftcms
8. Verify amplitude behavior. We should be seeing reasonable amplitude data coming in on production.
10. Mutagen should be enabled by default on macOS and Windows. 
    - [x] Verify that it is enabled globally by default (`ddev config global`) - `performance-mode`
    - [x] Verify that it can be turned off per project (`ddev config --performance-mode=mutagen` or `none`)
    - [x] Verify that it can be disabled globally (`ddev config global --performance-mode=none`)
    - [x] Verify that NFS can be enabled globally (`ddev config global --performance-mode=nfs`)
11. `ddev import-db` and `ddev export-db` should prefer `--file` rather than `--src`, but `--src` should still work. `ddev import-files` now prefers `--source`. Verify that `ddev import-db --help`, `ddev export-db --help`, and `ddev import-files --help` all show correct content with the now-preferred flags.
12.  Python and Django support, see docs
13. post-stop hooks shouldn't be called if a project is already stopped and you do `ddev stop`
15. Versioning and removal of add-ons
    - [ ] `ddev get <whatever>` 
    - [ ] `ddev get <whatever>` should update versioning for that add-on
    - [ ] `ddev get --installed` should show versioning
    - [ ] `ddev get --remove <add-on>`
    - [ ] `ddev get --version <version> <some-add-on>` should get the named add-on, then `ddev get --installed` should show it.
    - [ ] Removal actions for an add-on should be executed
    - [ ] 
16. `ddev list --type=<projecttype>`
17. If project type is set to `php` but another project type is detected, `ddev config` or `ddev config --php-version`  doesn't automatically switch to the other project type. https://github.com/ddev/ddev/issues/1919
18. nodejs_version defaults to 18, should not affect existing projects where it's already configured to something else. Make sure `nodejs_version: 14` and `nodejs_version: 20` work fine.
19. `config.*.yaml` are no longer gitignored in .ddev/.gitignore, but `config.local.yaml` is still gitignored
20. Global setting for router_http_port and router_https_port, can be overridden in project. If you have it in a project though (it was there by default) the project setting overrides it.
21. Upgrading to v1.22.0 should terminate all mutagen sessions, `ddev debug mutagen sync list` should show all terminated.
22. Fresh install: Completely fresh install should work predictably. Remove ~/.ddev/global_config.yaml and create a new project from scratch. Nice to do on clean machine, but not necessary.
23. `ddev heidisql` should work on platforms it supports
24. `ddev delete images` should work without a panic.
25. Message of the day should work and not be annoying. You can edit ~/.ddev/.state.yaml to force changes. Or delete the file.
26. `ddev get --list --all` should show all available repos .There are many.
27. `ddev debug download-images` should work in any directory
28. Tip of the day: 
    - [ ] Make sure it can be disabled `ticker_interval: -1` (fiddle with ~/.ddev/.state.yaml` to force new behavior)
    - [ ] Make sure that other ticker intervals work
29. `default_container_timeout` should work correctly, for example with a snapshot restore, see #5133

**Comment by rfay** [comment]
@deviantintegral sorry, I think something might have changed about sharing out of notion, here you go, https://randyfay.notion.site/v1-22-0-Release-notes-0e9d1254f2c04281b4d1f7c6c35ac764

@gilbertsoft we should consider restoring --use-traefik and --mutagen-enabled either as no-ops or something. @deviantintegral an issue with the specific things that worry you would be great, thanks!

**Comment by deviantintegral** [comment]
I had to update tests to `|| true` configuring traefik to pass on both 1.21 and HEAD: https://github.com/deviantintegral/ddev-playwright/pull/4/files#diff-a2bb1b04da80b87de17520a6aac3664b1cafdec2b6431697f15968522708a47cR28-R29

As well, on a project we have `ddev config global --use-traefik` in the README to support KasmVNC.

**Comment by rfay** [comment]
@deviantintegral added to
* https://github.com/ddev/ddev/issues/5095

**Comment by agviu** [comment]
I tried version v1.22.0-beta3 and noticed that the command `ddev start` does not work if the dba service is in the omit_containers setting. This can be disturbing for several users that are used to use DDEV as-it-is and they will have to do changes in the configuration.
Can this be replaced with just a warning and really make it enforced in a later DDEV version?

**Comment by rfay** [comment]
Thanks for testing @agviu! - This was fixed yesterday in 
* https://github.com/ddev/ddev/pull/5109 and will be in the next beta. It's also discussed right above here :)

**Comment by rfay** [comment]
1. PhpStorm integration
   ✅  XDebug integration worked perfectly OOTB, nothing required at all
    👎  I wasn't able to get PhpUnit or (any remote execution) working using WSL2 on Windows (PhpStorm on Windows side, docker-ce). I'm not actually sure PhpStorm knows how to do this at all. It tries to use docker-compose on the WIndows side, etc.
2. upgrading a project from v1.21.6 to v1.22.0
3. PhpMyAdmin/dba removal:
4. Gitpod usage
5. Codespaces usage
6. Multiple upload_dirs

**Comment by rfay** [comment]
Encountered https://github.com/ddev/ddev/issues/5168 in testing, fixed in https://github.com/ddev/ddev/pull/5175

**Comment by rfay** [comment]
I think this is all done. We can release on Monday if no problems show up.
