### ISSUE TITLE
xdebug breakpoint not breaking/missed/not hit in vscode wsl2 w10 (has worked for me on other machines)

### ISSUE THREAD

**Issue by therobyouknow** [ddev/ddev#5032]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Output of `ddev debug test`

<details><summary>Expand `ddev debug test` diagnostic information</summary>

```
robdavis@UOS-214251:~/clients/defra/rpa/dev/sites/debra-local$ ddev start
Network ddev_default created
Starting debra-local...
Container ddev-ssh-agent  Started
ssh-agent container is running: If you want to add authentication to the ssh-agent container, run 'ddev auth ssh' to enable your keys.
Network ddev-debra-local_default  Created
Container ddev-debra-local-web  Started
Container ddev-debra-local-db  Started
Container ddev-debra-local-dba  Started
Container ddev-router  Started
Successfully started debra-local
Project can be reached at https://debra-local.ddev.site https://127.0.0.1:32772
robdavis@UOS-214251:~/clients/defra/rpa/dev/sites/debra-local$ code
robdavis@UOS-214251:~/clients/defra/rpa/dev/sites/debra-local$ ddev debug test
Running bash [-c /tmp/test_ddev.sh]
======= Existing project config =========
These config files were loaded for project debra-local: [/home/robdavis/clients/defra/rpa/dev/sites/debra-local/.ddev/config.yaml]
name: debra-local
type: php
docroot: html
php_version: 8.0
webserver_type: nginx-fpm
webimage: drud/ddev-webserver:v1.21.5
router_http_port: 80
router_https_port: 443
additional_hostnames: []
additional_fqdns: []
database: {mariadb 10.4}
mailhog_port: 8025
mailhog_https_port: 8026
phpmyadmin_port: 8036
phpmyadmin_https_port: 8037
project_tld: ddev.site
use_dns_when_possible: true
composer_version: 2
nodejs_version: 16
default_container_timeout: 120
======= Creating dummy project named  tryddevproject-19951 in ../tryddevproject-19951 =========
OS Information: Linux UOS-214251 5.15.90.1-microsoft-standard-WSL2 #1 SMP Fri Jan 27 02:56:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
User information: uid=1000(robdavis) gid=1000(robdavis) groups=1000(robdavis),4(adm),20(dialout),24(cdrom),25(floppy),27(sudo),29(audio),30(dip),44(video),46(plugdev),116(netdev),999(docker)
DDEV version:  ITEM             VALUE
 DDEV version     v1.21.6
 architecture     amd64
 db               drud/ddev-dbserver-mariadb-10.4:v1.21.5
 dba              phpmyadmin:5
 ddev-ssh-agent   drud/ddev-ssh-agent:v1.21.5
 docker           24.0.2
 docker-compose   v2.15.1
 docker-platform  UOS-214251
 mutagen          0.16.0
 os               linux
 router           drud/ddev-router:v1.21.5
 web              drud/ddev-webserver:v1.21.5
PROXY settings: HTTP_PROXY='' HTTPS_PROXY='' http_proxy='' NO_PROXY=''
======= DDEV global info =========
Global configuration:
instrumentation-opt-in=true
omit-containers=[]
mutagen-enabled=false
nfs-mount-enabled=false
router-bind-all-interfaces=false
internet-detection-timeout-ms=3000
disable-http2=false
use-letsencrypt=false
letsencrypt-email=
table-style=default
simple-formatting=false
auto-restart-containers=false
use-hardened-images=false
fail-on-hook-fail=false
required-docker-compose-version=
use-docker-compose-from-path=false
project-tld=
xdebug-ide-location=
no-bind-mounts=false
use-traefik=false
wsl2-no-windows-hosts-mgt=false

======= DOCKER info =========
docker location: -rwxr-xr-x 1 root root 35921656 May 25 22:51 /usr/bin/docker
docker version:
Client: Docker Engine - Community
 Version:           24.0.2
 API version:       1.43
 Go version:        go1.20.4
 Git commit:        cb74dfc
 Built:             Thu May 25 21:51:00 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          24.0.2
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.4
  Git commit:       659604f
  Built:            Thu May 25 21:51:00 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.21
  GitCommit:        3dce8eb055cbb6872793272b4f20ed16117344f8
 runc:
  Version:          1.1.7
  GitCommit:        v1.1.7-0-g860f061
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
DOCKER_DEFAULT_PLATFORM=notset
======= Mutagen Info =========
======= Docker Info =========
Docker platform: UOS-214251
Using docker context: default (unix:///var/run/docker.sock)
docker-compose: v2.15.1
Using DOCKER_HOST=unix:///var/run/docker.sock
Docker version: 24.0.2
Able to run simple container that mounts a volume.
Able to use internet inside container.
Docker disk space:
Filesystem                Size      Used Available Use% Mounted on
overlay                1006.9G      9.9G    945.7G   1% /

Container ddev-debra-local-dba  Removed
Container ddev-debra-local-db  Removed
Container ddev-debra-local-web  Removed
Network ddev-debra-local_default  Removed
Project debra-local has been stopped.
The ddev-ssh-agent container has been removed. When you start it again you will have to use 'ddev auth ssh' to provide key authentication again.
Existing docker containers:
CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES
Creating a new ddev project config in the current directory (/home/robdavis/clients/defra/rpa/dev/sites/tryddevproject-19951)
Once completed, your configuration will be written to /home/robdavis/clients/defra/rpa/dev/sites/tryddevproject-19951/.ddev/config.yaml

Configuring unrecognized codebase as project type 'php' at /home/robdavis/clients/defra/rpa/dev/sites/tryddevproject-19951/web
Configuration complete. You may now run 'ddev start'.
Network ddev_default created
Starting tryddevproject-19951...
Container ddev-ssh-agent  Started
ssh-agent container is running: If you want to add authentication to the ssh-agent container, run 'ddev auth ssh' to enable your keys.
Network ddev-tryddevproject-19951_default  Created
Container ddev-tryddevproject-19951-dba  Started
Container ddev-tryddevproject-19951-web  Started
Container ddev-tryddevproject-19951-db  Started
Container ddev-router  Started
Successfully started tryddevproject-19951
Project can be reached at https://tryddevproject-19951.ddev.site https://127.0.0.1:32779
======== Curl of site from inside container:
HTTP/1.1 200 OK
Server: nginx
Date: Tue, 27 Jun 2023 16:17:20 GMT
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
Vary: Accept-Encoding

======== curl -I of http://tryddevproject-19951.ddev.site from outside:
HTTP/1.1 200 OK
Server: nginx/1.20.1
Date: Tue, 27 Jun 2023 16:17:20 GMT
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
Vary: Accept-Encoding

======== full curl of http://tryddevproject-19951.ddev.site from outside:
Success accessing database... db via TCP/IP
ddev is working. You will want to delete this project with 'ddev delete -Oy tryddevproject-19951'
======== Project ownership on host:
drwxr-xr-x 4 robdavis robdavis 4096 Jun 27 17:16 ../tryddevproject-19951
======== Project ownership in container:
drwxr-xr-x 4 robdavis robdavis 4096 Jun 27 16:16 /var/www/html
======== In-container filesystem:
Filesystem     Type  1K-blocks     Used Available Use% Mounted on
/dev/sdc       ext4 1055762868 10578028 991481368   2% /var/www/html
======== curl again of tryddevproject-19951 from host:
Success accessing database... db via TCP/IP
ddev is working. You will want to delete this project with 'ddev delete -Oy tryddevproject-19951'
Thanks for running the diagnostic. It was successful.
Please provide the output of this script in a new gist at gist.github.com
Running ddev launch in 5 seconds
If you're brave and you have jq you can delete all tryddevproject instances with this one-liner:
    ddev delete -Oy $(ddev list -j |jq -r .raw[].name | grep tryddevproject)
In the future ddev debug test will also provide this option.

Please delete this project after debugging with 'ddev delete -Oy tryddevproject-19951'
robdavis@UOS-214251:~/clients/defra/rpa/dev/sites/debra-local$
```
</details>         

### Expected Behavior

xdebug to hot breakpoint

### Actual Behavior

xdebug does not hit breakpoint.   

This has worked fine on other machines in the past.

### Steps To Reproduce

Follow xdebug setup steps and attempt to set breakpoint.

### Anything else?

Using Visual Studio Code v1.79.2 with Ubuntu WSL2 on Windows 10.

> Version: 1.79.2 (user setup)
> Commit: 695af097c7bd098fbf017ce3ac85e09bbc5dda06
> Date: 2023-06-14T08:57:04.379Z
> Electron: 22.5.7
> Chromium: 108.0.5359.215
> Node.js: 16.17.1
> V8: 10.8.168.25-electron.0
> OS: Windows_NT x64 10.0.19044

Have used xdebug with ddev successfully on other machines (W10 WSL2, W11 WSL2, macOS, Ubuntu Linux). 

Would you be able to advise please?

I have searched the existing issues:

- Looked through github: https://github.com/ddev/ddev/issues?q=is%3Aissue+xdebug+vscode
- and https://stackoverflow.com/search?q=%5Bddev%5D+xdebug

In troubleshooting https://ddev.readthedocs.io/en/latest/users/debugging-profiling/step-debugging/#troubleshooting-xdebug the step to telnet inside ddev php container: `ddev ssh`  then ` telnet host.docker.internal 9003 shows telnet _not_ connecting

phpinfo output here (in text form, can't paste image output from GoFullPage screengrabber) : https://gist.github.com/therobyouknow/5c62211f7e1a16b495fa871e7bab0b6a

Looking at the phpinfo output in the browser, I note that:

![image](https://github.com/ddev/ddev/assets/1080646/473e42b4-ab4b-4cef-9524-ac43ead0643e)

`DDEV_XDEBUG_ENABLED | false`

even though I've done:

```
$ ddev xdebug on
Enabled xdebug
$ ddev xdebug status
xdebug enabled
$
```

Re-booted machine as well tried.

Checking for interference of other processes as troubleshooting advisees:

Nothing listening on host: `sudo lsof -i :9003 -sTCP:LISTEN` returns nothing.

Set firewall rule as advised `sudo ufw allow 9003/tcp`

vscode is listening for xdebug, all looks normal:

![image](https://github.com/ddev/ddev/assets/1080646/98df41ee-3b25-4ddb-aa09-87e7edb84714)

`.vscode/launch.json` looks like:

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Listen for Xdebug",
            "type": "php",
            "request": "launch",
            "hostname": "0.0.0.0",
            "port": 9003,
            "pathMappings": {
                "/var/www/html": "${workspaceFolder}"
            }
        }
    ]
}
```

`settings.json` on vscode looks like:
![image](https://github.com/ddev/ddev/assets/1080646/02ded6d8-519d-4f71-8d3d-95a25b9fc33c)

> {
>     "php.validate.executablePath": "/usr/bin/php"
> }

Thanks for your help and also in the past.

**Comment by rfay** [comment]
If you don't see vscode listening on 9003 on the host (windows side), perhaps you haven't started it listening?

**Comment by therobyouknow** [comment]
It seems to be listening given the screenshot  but a blue bar not an orange one as stated in documentation. (Could vscode recent release color scheme changed after docs written?)

Clicking listen button or menu item gives pop up message to say already listening and asking if wanting to start néw listening or something like that.

Phpinfo shows ddev_xdebug_enabled value false as aforementioned. Thanks for getting back to me so far.

**Comment by rfay** [comment]
Could you please come over to Discord and let's make a plan for debugging this? We'll step through the instructions one by one and see if we can sort it out.  I'd like to do it as a public event if that works for you. https://discord.gg/hCZFfAMc5k

**Comment by therobyouknow** [comment]
Thanks @rfay will be there approximately 0045 BST - just over 45mins from when this comment made.

**Comment by therobyouknow** [comment]
on Discord now.

**Comment by therobyouknow** [comment]
Will look forward to discord chat at 8am Colorado, US time, 1pm UK time.

New information:  xdebug with same code base works on my personal machine.  So on that basis my guess is it could be  something about the office machine or the way I set it up (perhaps as a result of initial deviations in https://github.com/ddev/ddev/issues/5026#issuecomment-1609489160 )

![MicrosoftTeams-image](https://github.com/ddev/ddev/assets/1080646/38261cd1-f21a-4711-89e2-191824de3e3d)

**Comment by therobyouknow** [comment]
Wondering if the timeout value is too small for the setup on my office machine:

```
$ ddev logs
2023/06/28 12:17:16 [error] 1892#1892: *89 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Time-out connecting to debugging client, waited: 200 ms. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port)" while reading response header from upstream, client: 172.18.0.6, server: , request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://unix:/run/php-fpm.sock:", host: "debra-local.ddev.site", referrer: "https://debra-local.ddev.site/"
robdavis@UOS-214251:~/clients/defra/rpa/dev/sites/debra-local$
```

(found this `ddev logs` in https://ddev.readthedocs.io/en/latest/users/debugging-profiling/step-debugging/#troubleshooting-xdebug )

Answers here based on a search of the above error:

https://stackoverflow.com/questions/67556940/xdebug-step-debug-time-out-connecting-to-debugging-client-waited-200-ms-tr

**Comment by therobyouknow** [comment]
Good news, kind of. It's working now.

I say kind of, because I don't know why it's working: would like to know. But good news still!

Only things I can think of:
- leaving the machine on for a while, things "settled" whereby settings "caught up with each other" - vague guess
- general housekeeping of git branches: Merging: I caught up a dev branch with another branch containing my more recent ddev settings

![image](https://github.com/ddev/ddev/assets/1080646/4b258d5a-03e6-44eb-a019-99fab856b7de)

**Comment by rfay** [comment]
Well, I'm glad it's working. I imagine you restarted WSL2 or the machine and it regenerated the /etc/resolv.conf in there... but that was I'm sure something you did earlier. I imagine that host.docker.internal is now a different value than yesterday, right?

**Comment by therobyouknow** [comment]
>  I imagine that host.docker.internal is now a different value than yesterday, right?

How do I check the value?

Also by the way thanks for all your help. Happy to close.

**Comment by rfay** [comment]
`ddev exec ping host.docker.internal`
or `ddev ssh` and `ping host.docker.internal`
Or look at the results of `ddev ssh` and `telnet host.docker.internal`
Or look at the results of `export DDEV_DEBUG=true && ddev start` 

The things we did yesterday.

**Comment by therobyouknow** [comment]
Thank you @rfay with your advice above I can get the IP address.

To compare this with the previous IP address when xdebug wasn't working, I would have to see if I have some saved terminal logs to look at or I will see if there is anything in the discourse chat. Thanks again.

**Comment by rfay** [comment]
Not to worry, I'm just glad it's working for you.
