### ISSUE TITLE
Use standardized PR titles, resulting in standardized master-branch commit messages

### ISSUE THREAD

**Issue by gilbertsoft** [ddev/ddev#5037]
DDEV should also use some standards in PR titles and resulting merged commit messages. The commit message is generated from the PR title so the PR title has to follow the convention, we do not care about commit messages in a PR itself as it gets squash merged anyway. This has various advantages, e.g. we can find bugfixes to be back ported to a previous minor release. There is the widely used standard <https://www.conventionalcommits.org> which we can relay on.

This opens also new abillities e.g. automatically adding labels to PRs which later can be used to group the change log in the release by type.

## Definition of the commit message

`<type>[optional !]: <description>[, fixes #<issue>]`

This corresponds to the *Conventional Commits* and in addition the following rules must appy:

### Type
Must be one of the following:

* **build**: Changes that affect the build system or external dependencies
* **ci**: Changes to our CI configuration files and scripts (example scopes: Travis, Circle, BrowserStack, SauceLabs)
* **docs**: Documentation only changes
* **feat**: A new feature
* **fix**: A bug fix
* ***perf**: A code change that improves performance* (not sure if this has a value and is needed for DDEV at all)
* **refactor**: A code change that neither fixes a bug nor adds a feature
* **style**: Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc)
* **test**: Adding missing tests or correcting existing tests

Regarding SemVer, all types above except `feat` increase the patch version, `feat` increases the minor version.

### Scope
No scope must be used.

### Breaking Changes
Breaking changes must have a `!` appended after type/scope.

Regarding SemVer, breaking changes increase the major version.

### Subject / Description
The subject contains a succinct description of the change:

* use the imperative, present tense: "change" not "changed" nor "changes"
* don't capitalize the first letter
* no dot (.) at the end

If an issue exists for the change, `, fixes #<issue number>` must be appended to the subject.

### Revert
If the commit reverts a previous commit, it should begin with `revert: `, followed by the header of the reverted commit. In the body it should say: `This reverts commit <hash>.`, where the hash is the SHA of the commit being reverted.

## Enforce the convention

The final definition will be enforced using https://github.com/marketplace/actions/gs-commit-message-checker, here is a prepared RegEx https://regex101.com/r/Dq4iGI/1

**Comment by gilbertsoft** [comment]
Like discussed yesterday I've prepared a first draft for a commit message convetion for DDEV repos @rfay . @mattstein please also have a look.

**Comment by tyler36** [comment]
Are PRs covered by this?

Can we add something to Github actions to validate the message? Maybe https://github.com/marketplace/actions/gs-commit-message-checker

**Comment by gilbertsoft** [comment]
> Are PRs covered by this?
> 
> Can we add something to Github actions to validate the message? Maybe https://github.com/marketplace/actions/gs-commit-message-checker

Yes, that's the plan.

**Comment by gilbertsoft** [comment]
I've renamed some PRs according these rules, imho looks good!

**Comment by gilbertsoft** [comment]
Prepared RegEx https://regex101.com/r/Dq4iGI/1

**Comment by rfay** [comment]
> The GitHub Action is great, and I expect some mention in [the contributing guide](https://github.com/ddev/ddev/blob/master/CONTRIBUTING.md) and the [other contributing guide](https://ddev.readthedocs.io/en/stable/developers/building-contributing/) would be necessary for people that bother to read them.

@gilbertsoft not sure how the github action is going to work, but we don't want it to interfere with regular contributors, maybe just block merging until the title of the PR matches the standard? 

> What happens for serial tiny-thought committers (like me) that might treat commits more like atomic clumps of changes than entire features? (Is the answer to prefix every commit message accordingly, adopt a different way of thinking about commits, or something else I’m not thinking of?)

@mattstein the individual commit titles don't matter, only the PR title (which later becomes the squashed commit on master)

**Comment by gilbertsoft** [comment]
> I didn’t realize this was a thing, and I like the potential clarity it could bring! Like any kind of standard, I’d be inclined to take great care that it’s not a barrier to contribution:
> 
>     1. The GitHub Action is great, and I expect some mention in [the contributing guide](https://github.com/ddev/ddev/blob/master/CONTRIBUTING.md) and the [other contributing guide](https://ddev.readthedocs.io/en/stable/developers/building-contributing/) would be necessary for people that bother to read them.

Already added a `tbd` to the contribution guide. Will add more once we agree on the convention to use.

> 
>     2. What happens for serial tiny-thought committers (like me) that might treat commits more like atomic clumps of changes than entire features? (Is the answer to prefix _every_ commit message accordingly, adopt a different way of thinking about commits, or something else I’m not thinking of?)

You are talking about the commits of a PR? That's not the topic, it's only about the final commit message which gets pulled to master means the PR title. We do not care about single commits of PRs as they get squashed anyway.

> 
>     3. What do you see as the disadvantages to this, and are the benefits more important?

Conventions like this are used for most projects and I never saw any disadvantages so far.

**Comment by rfay** [comment]
> 3. What do you see as the disadvantages to this, and are the benefits more important?

It forces me to change!

**Comment by gilbertsoft** [comment]
> > The GitHub Action is great, and I expect some mention in [the contributing guide](https://github.com/ddev/ddev/blob/master/CONTRIBUTING.md) and the [other contributing guide](https://ddev.readthedocs.io/en/stable/developers/building-contributing/) would be necessary for people that bother to read them.
> 
> @gilbertsoft not sure how the github action is going to work, but we don't want it to interfere with regular contributors, maybe just block merging until the title of the PR matches the standard?

The action fails like other tests and the issue in the title must be fixed before merging. Maybe the contributor fixes the title or we do.

**Comment by mattstein** [comment]
> You are talking about the commits of a PR? That's not the topic, it's only about the final commit message which gets pulled to master means the PR title. We do not care about single commits of PRs as they get squashed anyway.

I am, and I misunderstood. Thanks for clarifying!

**Comment by gilbertsoft** [comment]
Will clarify the issue, it's not clear at the moment we are only talking about PR titles.

**Comment by gilbertsoft** [comment]
Here is an example of a failed one https://github.com/benjaminkott/bootstrap_package/pull/1159
![grafik](https://github.com/ddev/ddev/assets/25326036/b44bf979-2347-49a6-874b-52ff74414d75)
