### ISSUE TITLE
WSL2 + Docker CE Inside Install Script: (after several attempts) Temporary failure resolving   'download.docker.com', 'archive.ubuntu.com' but ping works but not for 'pkg.ddev.com'

### ISSUE THREAD

**Issue by therobyouknow** [ddev/ddev#5050]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Output of `ddev debug test`

Can't provide this because the issue is before ddev is installed, i.e. a problem with the ddev installation script, see details below.

### Expected Behavior

To be able to run the installation script successfully at:
https://ddev.readthedocs.io/en/latest/users/install/ddev-installation/#windows

### Actual Behavior

The installation script at: https://ddev.readthedocs.io/en/latest/users/install/ddev-installation/#windows
Failed due to "Temporary failure resolving  'download.docker.com', 'archive.ubuntu.com'" and "pkg.ddev.com" - after several attempts.

I am giving the output of install script ( https://ddev.readthedocs.io/en/latest/users/install/ddev-installation/#windows ) - i.e. the output of the 2nd command:

```
iex ((New-Object System.Net.WebClient).DownloadString('https://raw.githubusercontent.com/ddev/ddev/master/scripts/install_ddev_wsl2_docker_inside.ps1'))
```

The output is here: https://gist.github.com/therobyouknow/4b9094983bedeccc1b6ccb1d298aa140

Because this install seems to fail, I don't get as far as ddev to show the output of the usual diagnostics requested.  The problem is installing ddev itself, with the install script.

I ran the `iex` command as part of the steps.  It failed with the "temporary failure resolving  'download.docker.com', 'archive.ubuntu.com'  'pkg.ddev.com' " as per title of this issue.

I did a ping of the above failed addresses and this failed.

But then I connected to my organisation's VPN using GlobalProtect app.

The ping then worked for  'download.docker.com', 'archive.ubuntu.com' but not for 'pkg.ddev.com'

Also, I can visit all of these addresses in my web browser.

But the script still failed with the same issue.

So given that,  why would connecting to those addresses not work in the install script?

Is there a specific firewall rule I can set on Windows to resolve this issue? Or something else?

### Steps To Reproduce

Attempt to follow the steps at: https://ddev.readthedocs.io/en/latest/users/install/ddev-installation/#windows

"I have searched the existing issues": https://github.com/ddev/ddev/issues?q=is%3Aissue+is%3Aopen+temporary

**Comment by therobyouknow** [comment]
I have looked at trying changing nameservers / DNS of my machine:
https://stackoverflow.com/questions/60269422/windows10-wsl2-ubuntu-debian-no-network
and here: https://www.tenforums.com/tutorials/77444-change-ipv4-ipv6-dns-server-address-windows.html but this didn't resolve the issue.  But it did mean I was changing some IP addresses set by my organisation so not an ideal solution as I am thinking this might cause issues elsewhere. So I have now set them back to what they were.

**Comment by therobyouknow** [comment]
I think this is a WSL2 issue rather than ddev. Therefore I will look for advice on their github and if necessary raise an issue there.

**Comment by rfay** [comment]
This is in fact an issue with your network or your computer, has nothing to do with DDEV. Closing for now, happy to continue the conversation.

I recommend using 1.1.1.1 as your DNS server on your computer or your local network.

**Comment by therobyouknow** [comment]
Given that it is related to networking and wsl2, I've seen something similar before whereby wsl2 can't connect out to anything:
https://stackoverflow.com/questions/66444822/wsl-2-dns-is-not-working-with-vpn-connection-on-win-10 which relates to https://github.com/microsoft/WSL/issues/1350
So I will look at that solution.
