### ISSUE TITLE
Panic when `instrumentation-opt-in` enabled

### ISSUE THREAD

**Issue by stasadev** [ddev/ddev#5065]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected Behavior

Don't throw an error.

### Actual Behavior

```bash
$ ddev version
 ITEM             VALUE                                         
 DDEV version     v1.22.0-alpha3-29-g9b3b0d9b                   
 architecture     amd64                                         
 db               ddev/ddev-dbserver-mariadb-10.4:v1.22.0-beta1 
 ddev-ssh-agent   ddev/ddev-ssh-agent:v1.22.0-beta1             
 docker           24.0.2                                        
 docker-compose   v2.18.1                                       
 docker-platform  dev                                           
 mutagen          0.17.1                                        
 os               linux                                         
 router           traefik:v2.10                                 
 web              ddev/ddev-webserver:v1.22.0-beta1             
 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x1d8 pc=0x91d79b]

goroutine 1 [running]:
github.com/ddev/ddev/pkg/ddevapp.(*DdevApp).GetOmittedContainers(...)
        /home/runner/work/ddev/ddev/pkg/ddevapp/ddevapp.go:371
github.com/ddev/ddev/pkg/ddevapp.(*DdevApp).TrackProject(0x0)
        /home/runner/work/ddev/ddev/pkg/ddevapp/amplitude_project.go:36 +0x7b
github.com/ddev/ddev/cmd/ddev/cmd.glob..func48(0x10e72c0, {0x112cda0?, 0x0?, 0x0?})
        /home/runner/work/ddev/ddev/cmd/ddev/cmd/root.go:98 +0x86
github.com/spf13/cobra.(*Command).execute(0x10e72c0, {0x112cda0, 0x0, 0x0})
        /home/runner/work/ddev/ddev/vendor/github.com/spf13/cobra/command.go:876 +0x770
github.com/spf13/cobra.(*Command).ExecuteC(0x10ea4c0)
        /home/runner/work/ddev/ddev/vendor/github.com/spf13/cobra/command.go:974 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/work/ddev/ddev/vendor/github.com/spf13/cobra/command.go:902
github.com/ddev/ddev/cmd/ddev/cmd.Execute()
        /home/runner/work/ddev/ddev/cmd/ddev/cmd/root.go:152 +0x25
main.main()
        /home/runner/work/ddev/ddev/cmd/ddev/main.go:28 +0xc5
```

### Steps To Reproduce

1. Use the latest `ddev` binary.
2. `ddev config global --instrumentation-opt-in=true`
3. Run `ddev version` or `ddev config global`.

**Comment by rfay** [comment]
Thanks for testing this path!

**Comment by gilbertsoft** [comment]
Thanks for the report @stasadev ! New binaries fixing this issue are available at https://github.com/ddev/ddev/pull/5066#issuecomment-1618958866

**Comment by rfay** [comment]
And thanks so much @stasadev for using/testing HEAD! Helps so much.

**Comment by stasadev** [comment]
Glad to help!

**Comment by stasadev** [comment]
In fact, the error occurred all the time with analytics enabled.
I don't know why I emphasized the disabled internet.
Anyway, the fix from @gilbertsoft works as it should.

**Comment by rfay** [comment]
That's weird @stasadev . I wonder why it didn't show up for others then. I'm sure we can completely prevent it, but surprised that it was happening to you all the time.

**Comment by stasadev** [comment]
Maybe because I'm on HEAD, and the env variables for analytics are empty there.

**Comment by rfay** [comment]
That's an interesting theory. You must be installing HEAD by building yourself?

**Comment by stasadev** [comment]
No, I used [nighly.link](https://nightly.link/ddev/ddev/workflows/master-build/master).

**Comment by rfay** [comment]
OK, those should have the AmplitudeAPIKey in them. They don't? They warn you about not having it?

**Comment by stasadev** [comment]
I've only seen this warning about `AmplitudeAPIKey` in PR that solves this problem. 

> Instrumentation is opted in, but AmplitudeAPIKey is not available. This usually means you have a locally-built ddev binary or one from a PR build. It's not an error. Please report it if you're using an official release build.

I just assumed that maybe there was no `AmplitudeAPIKey` on HEAD and DDEV was trying to connect with an empty key, the `instrumentationApp` was not initialized, and there was a panic error. But I could be wrong.

**Comment by rfay** [comment]
Ah thanks. Yeah, the PR doesn't get built with it (because built from a fork) but the HEAD build has it.
