### ISSUE TITLE
There seems to be an error with upload_dir false in mutagen

### ISSUE THREAD

**Issue by sfroemkenjw** [ddev/ddev#5069]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected Behavior

If I set

```
upload_dirs: false
```

in config.yaml I expect mutagen sync status in green letters. But following letters are red:

```
Mutagen sync completed with problems in 3s.
For details on sync status 'ddev mutagen st account-elo-com -l' 
```

If I remove that config, mutagen sync status is green again, but warning about upload_dir is there again.

### Actual Behavior

With upload_dir: false something went wrong while syncing with mutagen

```
ddev mutagen status
Mutagen: problems: watching 
```

```
ddev mutagen logs
Stopped mutagen daemon 
Error: unable to acquire daemon lock: resource temporarily unavailable
mutagen daemon run failed with exit status 1 
Completed mutagen logs, now restarting normal mutagen daemon 
```

### Anything else?

Seems that the "false" value was taken over to mutagen 1 to 1 instead of prevent interpreting that value as directory

DDEV: 1.21.6
MacBook Pro intel
DockerForMac: 4.19.0 (106363)
Engine: 23.0.5
Compose: v2.17.3

**Comment by rfay** [comment]
Hi @sfroemkenjw - Same as the answer in https://github.com/ddev/ddev/issues/5070#issuecomment-1620574217

Again, sorry for the confusion and happy to continue the conversation here or elsewhere. And would love to have you test the latest beta.
