### ISSUE TITLE
DOCS: wrong option: upload_dirs

### ISSUE THREAD

**Issue by sfroemkenjw** [ddev/ddev#5070]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected Behavior

Use `upload_dir`

### Actual Behavior

In docs there is an option called `upload_dirs` which does not exists in config.yaml

https://ddev.readthedocs.io/en/latest/users/configuration/config/#upload_dirs

**Comment by rfay** [comment]
Hi @sfroemkenjw - 

`upload_dirs` is in the current pre-releases. It's definitely confusing, but we have two sets of docs.

* https://ddev.readthedocs.io/en/latest/ refers to the absolute latest committed changes
* https://ddev.readthedocs.io/en/stable/ (stable) refers to the most recent stable release (right now v1.21.6, which I imagine you have)

We'd love to have you testing [v1.22.0-beta1](https://github.com/ddev/ddev/releases) though, where you'll find upload_dirs.

Closing, sorry for the misunderstanding, and happy to continue the conversation here or elsewhere.
