### ISSUE TITLE
docs: codespaces - provide official postCreateCommand script for ddev projects?

### ISSUE THREAD

**Issue by mandrasch** [ddev/ddev#5071]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

The current docs (https://ddev.readthedocs.io/en/stable/users/install/ddev-installation/#github-codespaces) for codespaces install just state the following:

```bash
    "postCreateCommand": "bash -c 'ddev config global --omit-containers=ddev-router && ddev config --auto && ddev debug download-images'"
```

On my first tests with codespaces + ddev I noticed that some docker containers are kept during rebuilds. https://github.com/ddev/ddev/issues/5033

Codespaces has two rebuild options:

![image](https://github.com/ddev/ddev/assets/777278/bd246ebf-9844-403b-a266-edfa6cf0851c)

The internally used start script is more sophisticated and seems to take rebuilds into account (?):
https://github.com/ddev/ddev/blob/master/.devcontainer/setup_test_project.sh

I wondered if `ddev debug download-images` needs on rebuilds as well.

Guess it would be helpful for ddev users if they have a solid starter template for the `postCreateCommand` script. :-) 

### Describe your solution

Develop a starter script which can handle rebuilds.

**The big question: Should ddev containers be completely swept on a regular (not full) rebuild? What would be the  expected result of rebuilds on codespaces? 🤔**

Happy to participate in solving this!

### Describe alternatives

- There are other hooks which can be used, haven't explored them https://containers.dev/implementors/json_reference/#lifecycle-scripts

### Additional context

https://github.com/ddev/ddev/pull/5061

**Comment by rfay** [comment]
Images shouldn't be part of the equation here. I think containers are. But maybe we can add a `docker rm -f $(docker images -q)` or a `ddev poweroff`? I think the `ddev poweroff` would do everything.

**Comment by mandrasch** [comment]
Thanks so much for suggestion / guidance! 

I implemented `ddev poweroff` for now in https://github.com/mandrasch/ddev-craftcms-vite. 

Closing this. :-)
