### ISSUE TITLE
choose a folder name other than html under /var/www/ for where site code resides

### ISSUE THREAD

**Issue by therobyouknow** [ddev/ddev#5081]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

Problem as described here:

https://stackoverflow.com/questions/76603421/how-to-change-ddev-php-container-docroot-path-from-var-www-html

> I need to change the docroot path that ddev sets up in the php container because I have some code that has already had an html folder in its source and bespoke include path determination is not working.
> 
> The code looks for the first occurrence of html to set a path to include files at another location. But because both the code and ddev php container have html, there are 2 occurrences of html in the path and the code now forms the path incorrectly. It's legacy code and the routine is done many times in the code so I'd rather not change each file to avoid larger pull request diffs.

I tried @rfay's suggestion on that link: 
- created a `docker-compose.mounts.yaml` directly under `.ddev`.  
- contents:
```
services:
  web:
    volumes:
    - ../:/var/www/docroot
```
- deleted my project
- `ddev config`
- ddev said that the folder wasn't created (which is what I'd expect) but that it would create it
- `ddev start`
- `ddev ssh` and observed folder `/var/www/docroot` exists
- But on visiting the site I get "Forbidden".

### Describe your solution

Not known.

### Describe alternatives

change the code but there are a lot of instances of the reliance on `html` and this would affect our live code as well.

**Comment by rfay** [comment]
In general we don't try to add enhancements to support one project's misbehaving old code :)
