### ISSUE TITLE
Stop cron so it doesn't change database while doing a database pull

### ISSUE THREAD

**Issue by mediaessenz** [ddev/ddev#5082]
In projects with large databases, where syncing a local development system against a remote system it could be nessecary to pause the web container to prevent inconsitences in the database.

In my case, a cron job running in the web container of my development system changes data in the database every minute.
If the import of the database from a remote system during a live-dev-sync  takes more than a minute, I get in troubles.

In the past, before I started to use ddev, I just paused the web container of my docker environment, did the sync (rsync + mysqldump + import) and unpaused the web container afterwards. This worked perfect.

Unfortunately there is currently no "ddev pause web" command to do this.
I already tried to use the "native" docker commands `docker pause ddev-project-web` and `docker unpause ddev-project-web` to do this, which works in general, but after fireing the commands, ddev seems to loose the connection to the running containers and every following ddev command produces an error. `ddev describe` shows no running services.

`docker compose -f .ddev/.ddev-docker-compose-full.yaml pause web` ends with the same problem.

`ddev service disable web` is also not working, since this command can only handle "Additional Services".

### Describe your solution

Enhance `ddev service disable` command to disable/enable the web service as well.

### Describe alternatives

Adding a command `ddev pause web` and `ddev unpause web` to pause/unpause containers managed by ddev.

**Comment by rfay** [comment]
`ddev stop` does what you want I think. Why would you want to "pause"?

DDEV containers keep no state (any state is kept in volumes) so you can just `ddev stop` when you don't want your local project accessing the database.

**Comment by rfay** [comment]
Then you have to `ddev start` when you want to use it again.

**Comment by rfay** [comment]
I'll be happy to work with you to figure out why stopping all containers is a problem.

DDEV does have a `pause` command in v1.21.6, but that has been removed for upcoming v1.22.0. It was never useful.

I think we need to work on the actual problem you have, rather than visualizing the solution to the problem as a feature request. If you're able to share the project or the architecture and talk about what's going on, we can try to figure out how to solve it.

Note that DDEV is built for local development, so when you use it for other things you do end up getting out into strange places sometimes.

**Comment by mediaessenz** [comment]
I use ddev only for development.
To get the current state of e.g. the live system to my local environment, I use gosync.

This cli tool made by webdevops, uses a yml-configuration file which holds remote ssh hosts and remote/local database settings and how to sync/deploy databases and files between local and remote systems.

Under the hood it uses rsync, mysqldump and mysql to do the job.

For each job configuration it is possible to define the execution of local/remote shell commands which should be done before and after the db/file sync.

To get the sync done so, I need at least the db container running, otherwise gosync is not able to transfer the data from the remote system into it.

So, stopping all by doing „ddev stop“ is not a option.

But if all containers are running during the sync, which take more than one minute in my case, a running cron job inside the web container writes data into the database as well. That‘s the problem.

**Comment by rfay** [comment]
The normal way to do this is with a `ddev pull` implementation. You can wrap your gosync tool in `ddev pull <something>`. Please take a look at https://ddev.readthedocs.io/en/latest/users/providers/ - people use it for things like this all the time.

Why don't you disable your cron when running the job? (Note that DDEV doesn't by default have anything going with cron, nor is the cron daemon even installed). 

There are two things we can work on. I think disabling cron during your sync is the first step.

**Comment by mediaessenz** [comment]
I'm currently programming a synfony command to disable/enable the critical scheduler task inside my TYPO3 system.
This should do the job in the end.

But I also will have a look in the `ddev pull` command later. Maybe it's usefull for other things later ...

**Comment by mediaessenz** [comment]
After deleting my local db and doing a fresh sync the `ddev sudo service cron stop` way seems to work now.

**Comment by mediaessenz** [comment]
Sorry, but my problem is back.

It seems it was more or less random that it worked last time.

Now I really have not idea what I can do anymore, beside to do the sync with the mentions pull command, which I really don't want to do since my cli tool works perfect since years now and the other (ddev pull) looks a kind of a downgrade, comparing to it :-(

**Comment by rfay** [comment]
If I understand correctly, you just want to prevent the ddev-webserver from executing cron jobs during your download, right?

You should be able to do that using the techniques you're already using. And you can do those things manually to test it. `sudo service stop cron` ought to do the job in the web container. Take a look after you do it.

You should also be able to do what you want with `docker pause ddev-<projectname>-web` and then `ddev restart`

**Comment by mediaessenz** [comment]
Maybe the problem is, that at the moment when I stop the cron by starting the sync, there's a already running task in the background, which writes the "last run" timestamp into the mentioned database table in the end.

I will try to do a `ddev restart` after sync, which should (hopefully) work, but will for sure slow down the sync process a lot.

Why ddev looses the containers after `docker pause ...`?

**Comment by rfay** [comment]
> Why ddev looses the containers after docker pause ...?

I'm not sure what the question is here (what "loses the containers" means), but DDEV is designed to stop/start rather than use `pause`, which is a fairly unsafe issue. Since DDEV doesn't ever save state inside containers, the preference is to stop (destroy) and recreate. But `docker pause` should work for you.

**Comment by mediaessenz** [comment]
To reproduce, just start a system with `ddev start` and fire `docker pause ddev-projectname-web && docker unpause ddev-projectname-web` after.
Then do a `ddev describe`

**Comment by mediaessenz** [comment]
As prediced, my sync needs several minute now :-(

**Comment by rfay** [comment]
It sounds like you have a problem with Colima. What colima version are you using? 

I'd be happy to study this with you in a live screenshare. If you'd like to do that come on over to Discord and we'll arrange it. https://discord.gg/hCZFfAMc5k

**Comment by mediaessenz** [comment]
I'm using colima 0.5.5.

Meanwhile I added a `sleep 10` command after stopping the cron service as a workaround for the upper mentioned problem (see https://github.com/ddev/ddev/issues/5082#issuecomment-1622188561).

This seems to do the job.

My sync looks approximately like so now:
1. Stop cron service: `ddev exec sudo service cron stop`
2. Wait 10 seconds `sleep 10`
3. Do rsync (remote > local) and mysqldump (remote) > mysql (ddev) to transfer specific files and database tables from the remote system to the local system (managed by gosync)
4. Do some other stuff (database compare, cache clearing/warmup ...)
5. Start cron service again `ddev exec sudo service cron start`

I testet it several time and it always worked.

If I have the same problem again, I will be very happy to use your offer.
