### ISSUE TITLE
Set correct serialize_precision for most PHP versions

### ISSUE THREAD

**Issue by Kent-N** [ddev/ddev#5092]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

I recently encountered an issue with an ini setting that wasn't set to the expected default for that PHP version. After digging a bit more and talking to @rfay on Discord, the conclusion was that the default config(s) probably haven't been updated for a long time.

Specifically it was the ini "serialize_precision" on PHP 8.0.24, that should default to "-1" from 7.1.0 onwards. DDEV sets that to 17 by default. https://www.php.net/manual/en/ini.core.php

A lot of subtle unexpected behavior can occur, if your production environment uses the current defaults while your local dev with DDEV has outdated settings.

### Describe your solution

The solution would be to go through all the configs and updated them to the latest defaults.

Maybe there is a way to automatically pull the defaults from the PHP repo? For example parsing https://github.com/php/php-src/blob/PHP-8.0.24/php.ini-production to generate the config file for 8.0.24 in DDEV.

**Comment by rfay** [comment]
We should probably use the default configs for every PHP version, the ones created by the package install.

**Comment by hanoii** [comment]
I just stumbled upon a super odd floating point precision issue that shouldn't really be there:

```
# php -r "var_dump(0.6);"
float(0.59999999999999998)
```

In talking with @rfay on Discord he pointed me to this issue.

Adding a `.ddev/php/fix.ini`

witdh

```
serialize_precision=-1
```

Fixed it

```
php -r "var_dump(0.6);"
float(0.6)
```

I agree that we should use the defaults, the only thing I might set n top of the defaults no memory limit and a biggish post_max_size  as it is now and maybe increase most other limits normally increased for local dev.

**Comment by hanoii** [comment]
I'd say this one is overall pretty critical

**Comment by rfay** [comment]
I think the right answer is to remove most of the overrides for most versions of PHP, and use the defaults for that version. Not exactly sure why we added overrides way back in the day.
