### ISSUE TITLE
Gentler handling of removed directives and commands (omit_containers, --mutagen-enabled, --use-traefik)

### ISSUE THREAD

**Issue by gilbertsoft** [ddev/ddev#5095]
### Expected Behavior

People expect old commands and directives to still work in v1.22.0:

- [x] `omit_containers[dba]` shouldn't create an error even if it's ignored. (project only, could give a message about deprecation)
- [x] `--mutagen-enabled` (global and project) could just set `performance_mode: mutagen`, maybe explain deprecated
- [x] `--nfs-mount-enabled` (global and project)
- [x] `--use-traefik` (global) can make sure that `router: traefik`

There may be a couple other things we should handle more gracefully

### Actual Behavior

When using these currently users get errorrs. 

```
ddev config --auto
You are reconfiguring the project at /home/simon/development/GsActions/commit-message-checker.
The existing configuration will be updated and replaced.
Configuring unrecognized codebase as project of type 'php' at /home/simon/development/GsActions/commit-message-checker
failed to validate config: unsupported omit_containers: [db dba ddev-ssh-agent], ddev (amd64) only supports the following for omit_containers: [db ddev-ssh-agent]
```

or

```
ddev start
Failed to get project(s): unsupported omit_containers: [db dba ddev-ssh-agent], ddev (amd64) only supports the following for omit_containers: [db ddev-ssh-agent]
```

**Comment by rfay** [comment]
I wonder if we could just accept `dba` but remove it after loading.
