### ISSUE TITLE
Enable instrumentation question on gitpod and codespaces

### ISSUE THREAD

**Issue by rfay** [ddev/ddev#5100]
Even though gitpod and codespaces are transient, we'd rather have some information about them, so enable asking permission to do instrumentation on them.

### Actual Behavior

We don't ask, because they do `ddev start -y`, which doesn't ask

**Comment by gilbertsoft** [comment]
No sure how this is disabled on these platforms.

**Comment by rfay** [comment]
Here's why it's disabled on gitpod/codespaces; we use `ddev start -y`, which skips the question. And of course everywhere it's disabled by default. And we don't ask again until they upgrade.

gitpod:
https://github.com/ddev/ddev/blob/55c2ab8eee35679b531914029346873f9425dfbd/.gitpod.yml#L25

codespaces:
https://github.com/ddev/ddev/blob/56afe4bee4170688435510c79135d32d63b7d824/.devcontainer/setup_test_project.sh#L26

**Comment by rfay** [comment]
I don't think I'm willing to make this change. It's quite intrusive, makes it stop everything when you're building a new gitpod instance, waiting for your input. I think we just need to live without this instrumentation.
