### ISSUE TITLE
Replace go-amplitude fork with upstream now that blocking issue is resolved

### ISSUE THREAD

**Issue by marklabrecque** [ddev/ddev#5101]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

See: https://github.com/amplitude/analytics-go/pull/56 for a resolution.

It looks like we need to simply pull in v1.0.1 to shed the tech debt of the fork.

### Describe your solution

Pull in the new version of the package, and remove the fork.

**Comment by rfay** [comment]
Awesome, go for it, thanks.

Followup is to archive the fork.
