### ISSUE TITLE
Update the settings.php in pkg/ddevapp/drupal/drupal10 to adjust to the changes in drupal 10.1 

### ISSUE THREAD

**Issue by rpkoller** [ddev/ddev#5121]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

In todays Lean coffee table call we've discussed a feature that got introduced in Drupal 10.1 and is set in the settings.php only. I was a bit confused when I was unable to find it in my fresh Drupal 10.1 install until i realized i've used `ddev config` to set up the project. When i compared the settings.php with the default.settings.php i actually found the changes introduced by that feature (https://www.drupal.org/project/drupal/issues/3027639). on a diff between the settings.php and the default.settings.php there are a few more changes 

on top `// @codingStandardsIgnoreFile` changed to `// phpcs:ignoreFile` , transaction support section got removed, anything in relation to databases got changed significantly, a fallback to http for update manager got added and so on. there are quite a few changes that got in 10.1, since 10.0 was about deprecation and updating versions mainly. 

### Describe your solution

adjust the current settings.php for the drupal 10 project type to the changes introduced with 10.1.x

**Comment by rfay** [comment]
I'm fine with just updating the default settings.php 

It's verbatim here, https://github.com/ddev/ddev/blob/master/pkg/ddevapp/drupal/drupal10/settings.php
