### ISSUE TITLE
Settings for django4 project need to import os

### ISSUE THREAD

**Issue by chellman** [ddev/ddev#5123]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Output of `ddev debug test`

(Will add later if needed, I think it's not needed yet)

### Expected Behavior

After running `ddev start`, I expect loading the site to work.

### Actual Behavior

The site was inaccessible, with the following error in the web container logs:

```
  File "/var/www/html/simple/settings.py", line 127, in <module>
    if os.environ.get('IS_DDEV_PROJECT') == 'true':
NameError: name 'os' is not defined
```

### Steps To Reproduce

This assumes you have a virtualenv or other way to access the django package.

1. `python3 -m django startproject example .`
2. `cd example`
3. `ddev config`
4. `ddev start`
5. `ddev launch`

If you're like me, you'll see a 502 error.

To fix it, this would work:

Instead of this:

```python
if os.environ.get('IS_DDEV_PROJECT') == 'true':
```

This:

```python
import os
if os.environ.get('IS_DDEV_PROJECT') == 'true':
```

`ddev restart` the project, `ddev launch`, and you'll have a starter site to look at.

### Anything else?

It's possible, depending on the project, that the settings file referenced will already import `os`, so that would need to be checked for first.

**Comment by rfay** [comment]
Interested in doing a PR for this? It's just here:
https://github.com/ddev/ddev/blob/5a9730f2291c6093c26954ce13596de392ac486e/pkg/ddevapp/django.go#L79-L83
