### ISSUE TITLE
References to M1 Mac in code should be changed to Apple Silicon

### ISSUE THREAD

**Issue by marklabrecque** [ddev/ddev#5125]
### Is there an existing issue for this?

- [X] I have searched the existing issues

Small code update to change references to M1 Macs to include M2 and subsequent generations. The reason for this is to prevent future confusion about whether this affects just the first generation of M1 Macs or all future versions (more likely the latter is the intention here)

### Expected Behavior

No behavior changes should exhibited after this change.

### Actual Behavior

No behavior changes should exhibited after this change.

### Steps To Reproduce

No behavior changes should exhibited after this change.

**Comment by marklabrecque** [comment]
I will take this on, but I seem to have the ability to assign it to myself at the moment.

**Comment by rfay** [comment]
Fixed in 
* #5129 

Thanks!
