### ISSUE TITLE
`ddev import-files` should work any time upload_dirs are implied or specified

### ISSUE THREAD

**Issue by stasadev** [ddev/ddev#5127]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

- https://github.com/ddev/ddev/issues/4190
- https://github.com/ddev/ddev/pull/5005

### Describe your solution

I noticed that not every project type supports `ddev import-files`:

https://github.com/ddev/ddev/blob/42969991212ff2c71fb91d7651d2ea17f8d1d749/pkg/ddevapp/apptypes.go#L75-L218

`nodeps.AppTypeDjango4`, `nodeps.AppTypeLaravel` and `nodeps.AppTypePython` are missing `importFilesAction`.

I guess it was just missed in the massive #5005.

Not sure about the specific actions for Django and Python, but Laravel should be the same as the generic PHP type.

**Comment by rfay** [comment]
Not all project types have an explicit location for user-generated files. For example, with Craft CMS and Laravel it's completely a developer choice. Same with `php`.

However, if `upload_dirs` is specified, `ddev import-files` should still work.

**Comment by stasadev** [comment]
> However, if `upload_dirs` is specified, `ddev import-files` should still work.

Unfortunately, it doesn't work:

```
# prepare a test folder with a test file
mkdir test && cd test && mkdir test_folder && touch test_folder/file.txt

# try to import files for PHP project type
ddev config --auto --upload-dirs=test_folder2 --project-type=php
ddev import-files --source=test_folder
Successfully imported files for test

# try to import files for Laravel project type
ddev config --auto --upload-dirs=test_folder2 --project-type=laravel
ddev import-files --source=test_folder
Error: failed to import files for test: this project type (laravel) does not support import-files
```

> `nodeps.AppTypeDjango4`, `nodeps.AppTypeLaravel` and `nodeps.AppTypePython` are missing `importFilesAction`.

**Comment by rfay** [comment]
I intended to fix this with a separate PR but looks like I'll need it to get tests to pass for the panic PR, https://github.com/ddev/ddev/issues/5126
