### ISSUE TITLE
The project cache in `ddev-global-cache` should always be removed when running `ddev delete`

### ISSUE THREAD

**Issue by stasadev** [ddev/ddev#5135]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Output of `ddev debug test`

```
$ ddev version
 ITEM             VALUE                                               
 DDEV version     v1.22.0-beta3-12-g735effcb                          
 architecture     amd64                                               
 db               ddev/ddev-dbserver-mariadb-10.4:v1.22.0-beta1       
 ddev-ssh-agent   ddev/ddev-ssh-agent:v1.22.0-beta1                   
 docker           24.0.2                                              
 docker-compose   v2.20.0                                             
 docker-platform  dev                                                 
 mutagen          0.17.2                                              
 os               linux                                               
 router           traefik:v2.10                                       
 web              ddev/ddev-webserver:20230707_fix_process_group_kill
``` 

### Expected Behavior

`ddev-global-cache` volume is mounted at `/mnt/ddev-global-cache` and has special project folders  `/mnt/ddev-global-cache/{bashhistory/${HOSTNAME},mysqlhistory/${HOSTNAME},nvm_dir/${HOSTNAME}}`.

For a project named `test-project`, `${HOSTNAME}` can be `test-project-web` and `test-project-db`.

These folders should always be removed, when I delete a project.

### Actual Behavior

There is a case, where you run `ddev delete --omit-snapshot` (the project is not started to take a snapshot with this flag), and the project is already stopped, `ddev-global-cache` is not cleared.

### Steps To Reproduce

```
$ mkdir test-project && cd test-project
$ ddev config --auto --omit-containers=db
$ ddev start
$ ddev stop
$ ddev delete test-project --omit-snapshot --yes

$ HOSTNAME=test-project-web; docker run --rm -i -v=ddev-global-cache:/mnt/ddev-global-cache busybox ls /mnt/ddev-global-cache/{bashhistory/${HOSTNAME},mysqlhistory/${HOSTNAME},nvm_dir/${HOSTNAME}}
/mnt/ddev-global-cache/bashhistory/test-project-web:

/mnt/ddev-global-cache/mysqlhistory/test-project-web:

/mnt/ddev-global-cache/nvm_dir/test-project-web:
CODE_OF_CONDUCT.md
CONTRIBUTING.md
Dockerfile
GOVERNANCE.md
LICENSE.md
Makefile
PROJECT_CHARTER.md
README.md
ROADMAP.md
bash_completion
install.sh
nvm-exec
nvm.sh
package.json
rename_test.sh
test
update_test_mocks.sh
```

If I run the same commands but use `ddev stop --remove-data --omit-snapshot` instead of `ddev stop`, or do not call `ddev stop` at all, the cache is deleted:

```
HOSTNAME=test-project-web; docker run --rm -i -v=ddev-global-cache:/mnt/ddev-global-cache busybox:stable ls /mnt/ddev-global-cache/{bashhistory/${HOSTNAME},mysqlhistory/${HOSTNAME},nvm_dir/${HOSTNAME}}
ls: /mnt/ddev-global-cache/bashhistory/test-project-web: No such file or directory
ls: /mnt/ddev-global-cache/mysqlhistory/test-project-web: No such file or directory
ls: /mnt/ddev-global-cache/nvm_dir/test-project-web: No such file or directory
```

### Anything else?

How I noticed this:

I was playing around with `ddev nvm install`, then decided to use `nodejs_version` from `.ddev/config.yaml`.
To do this, I deleted the project and started it again, but was surprised to see the same `node` that I installed manually.

I can just run `ddev stop --remove-data` to do this, but if people delete a project, they expect everything related to the project to be deleted.

Related:

- https://github.com/ddev/ddev/issues/3666

**Comment by stasadev** [comment]
I can see that there is no easy way to remove this cache without running the project.

https://github.com/ddev/ddev/blob/735effcbf5a87b8f65cee76b5f59ab276bd58322/pkg/ddevapp/ddevapp.go#L2372-L2380

I don't want it to be complicated, so I'm closing this issue.

As a workaround, I created a bash function:

```
function clean-ddev-global-cache() {
    project_name=${1}
    
    if [[ "$(ddev status ${project_name} --json-output | jq -r '.raw.status')" != "stopped" ]]; then
        ddev stop --remove-data --omit-snapshot
    else
        docker run -t --rm -v ddev-global-cache:/mnt/ddev-global-cache busybox:stable \
            sh -c "rm -rf /mnt/ddev-global-cache/*/${project_name}* /mnt/ddev-global-cache/traefik/*/${project_name}*"
    fi
}
```

I use my own aliases and bash functions for things like `ddev delete`, so I just include that in my workflow.

**Comment by rfay** [comment]
Thanks for exploring this.  There are definitely some interesting side-effects. It wouldn't be hard to use RunSimpleContainer instead of doing this using the existing mount, like in https://github.com/ddev/ddev/blob/735effcbf5a87b8f65cee76b5f59ab276bd58322/pkg/ddevapp/ddevapp.go#L1135

If you think it's worth solving, that would be a super-simple replacement if you want to do a PR.

**Comment by stasadev** [comment]
I think it's worth solving, I will prepare a PR.
