### ISSUE TITLE
Add global commands for pip and pip3

### ISSUE THREAD

**Issue by rpkoller** [ddev/ddev#5161]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

DDEV 1.22 adds projects types for django4 and python as well as ships with pip and pip3 installed. On the other hand DDEV already provides for package managers in php and javascript global commands. it would be a reasonable reasonable to add global commands for the python based package manager as well.  

### Describe your solution
see https://github.com/ddev/ddev/pull/5162

**Comment by rfay** [comment]
In 
* #5162 

decided not to accept this improvement, but thanks as always for suggesting (and implementing) it. When we get some more momentum with the Python community it will be time to look at it again.
