### ISSUE TITLE
Tests are explicitly excluded on some environments, how to test them anyway

### ISSUE THREAD

**Issue by Firesphere** [ddev/ddev#5164]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Output of `ddev debug test`

When running the tests for DDEV, MacOS M1/2 on Colima are skipped at certain places.
It would be useful to allow these to run with a flag (e.g. RUN_COLIMA or RUN_MACOS), so that I don't have to comment them out manually in multiple places

### Expected Behavior

Not applicable

### Actual Behavior

Tests are skipped

### Steps To Reproduce

1. Use MacOS
2. Run the tests
3. Observe multiple times a message about MacOS not being tested for various reasons.

### Anything else?

Example from `testDdevFullSiteSetup()`:
```
	if runtime.GOOS == "windows" || dockerutil.IsColima() {
		t.Skip("Skipping on Windows and Colima as this is tested adequately elsewhere")
	}
```

**Comment by rfay** [comment]
I usually comment those out when running Colima. It would be nice to do something better. We test DDEV with colima on Github Actions and their macOS VMs are SO SLOW that we just have to try to cut things out.

**Comment by rfay** [comment]
I've been thinking about a more general way to limit tests, 
* https://github.com/ddev/ddev/issues/5113

Would be open to suggestions. It's important to maximize our test capabilities without doing things that require a lot of restarts or stress fragile test environments like Docker Desktop.

**Comment by rfay** [comment]
IMO the current strategies are good enough for the existing situation. Temporarily remove the t.Skip(), or add code that allows for overriding with an env var, etc. Closing for now, happy to continue the conversation here or elsewhere.
