### ISSUE TITLE
Do not regenerate example commands/providers

### ISSUE THREAD

**Issue by ateufel** [ddev/ddev#5174]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

I want to create custom commands and providers and I have removed all the example folders/files to keep things clean. The examples get regenerated, for example, if I use "ddev yarn install" or some other command. Or course I can create a subfolder for my custom code, but I would rather have all the examples not visible in my project, even though they are excluded in GIT.

### Describe your solution

Do not regenerate example folders/files if once removed. An easier solution would be to just add a link to examples in the readme files (for example, in the command/web/README.txt - this would not pollute the project, but you can still copy the examples from some repo.

### Describe alternatives

create subfolder for custom commands/providers, to at least keep them separated - if that is even possible

**Comment by rfay** [comment]
> Do not regenerate example folders/files if once removed.

How can DDEV know if the files were removed or just didn't exist?

**Comment by ateufel** [comment]
good question, but why include all those examples anyway? an easier solution would be to just add a link to examples in the readme files (for example, in the command/web/README.txt - this would not pollute the project, but you can still copy the examples from some repo.

**Comment by rfay** [comment]
It's an attempt to make it easy for users. It's worked well. I'm sorry they bother you. Please note that they're gitignored.

**Comment by rfay** [comment]
We don't plan to take action on this, but if others chime in, or if you can propose a concrete plan of action, it's welcome and we can reopen this.
