### ISSUE TITLE
Database import fails: pv: /mnt/ddev_config/.../*.*sql: No such file or directory

### ISSUE THREAD

**Issue by supdake** [ddev/ddev#5182]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Output of `ddev debug test`

<details><summary>Expand `ddev debug test` diagnostic information</summary>

ben@PF3DHS3K:~/dev/academymortgage$ ddev debug test
Running bash [-c /tmp/test_ddev.sh]
======= Existing project config =========
These config files were loaded for project academymortgage: [/home/ben/dev/academymortgage/.ddev/config.yaml]
name: academymortgage
type: drupal9
php_version: 8.0
webserver_type: nginx-fpm
webimage: drud/ddev-webserver:v1.21.5
router_http_port: 80
router_https_port: 443
additional_hostnames: []
additional_fqdns: []
database: {mariadb 10.4}
mailhog_port: 8025
mailhog_https_port: 8026
phpmyadmin_port: 8036
phpmyadmin_https_port: 8037
project_tld: ddev.site
use_dns_when_possible: true
composer_version: 2
nodejs_version: 16
default_container_timeout: 120
======= Creating dummy project named tryddevproject-16909 in ../tryddevproject-16909 =========
OS Information: Linux PF3DHS3K 5.15.90.1-microsoft-standard-WSL2 https://github.com/ddev/ddev/issues/1 SMP Fri Jan 27 02:56:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
User information: uid=1000(ben) gid=1000(ben) groups=1000(ben),4(adm),20(dialout),24(cdrom),25(floppy),27(sudo),29(audio),30(dip),44(video),46(plugdev),116(netdev),999(docker)
DDEV version: ITEM VALUE
DDEV version v1.21.6
architecture amd64
db drud/ddev-dbserver-mariadb-10.4:v1.21.5
dba phpmyadmin:5
ddev-ssh-agent drud/ddev-ssh-agent:v1.21.5
docker 24.0.4
docker-compose v2.15.1
docker-platform PF3DHS3K
mutagen 0.16.0
os linux
router drud/ddev-router:v1.21.5
web drud/ddev-webserver:v1.21.5
PROXY settings: HTTP_PROXY='' HTTPS_PROXY='' http_proxy='' NO_PROXY=''
======= DDEV global info =========
Global configuration:
instrumentation-opt-in=true
omit-containers=[]
mutagen-enabled=false
nfs-mount-enabled=false
router-bind-all-interfaces=false
internet-detection-timeout-ms=3000
disable-http2=false
use-letsencrypt=false
letsencrypt-email=
table-style=default
simple-formatting=false
auto-restart-containers=false
use-hardened-images=false
fail-on-hook-fail=false
required-docker-compose-version=
use-docker-compose-from-path=false
project-tld=
xdebug-ide-location=
no-bind-mounts=false
use-traefik=false
wsl2-no-windows-hosts-mgt=false

======= DOCKER info =========
docker location: -rwxr-xr-x 1 root root 35922416 Jul 7 08:50 /usr/bin/docker
docker version:
Client: Docker Engine - Community
Version: 24.0.4
API version: 1.43
Go version: go1.20.5
Git commit: 3713ee1
Built: Fri Jul 7 14:50:55 2023
OS/Arch: linux/amd64
Context: default

Server: Docker Engine - Community
Engine:
Version: 24.0.4
API version: 1.43 (minimum version 1.12)
Go version: go1.20.5
Git commit: 4ffc614
Built: Fri Jul 7 14:50:55 2023
OS/Arch: linux/amd64
Experimental: false
containerd:
Version: 1.6.21
GitCommit: 3dce8eb055cbb6872793272b4f20ed16117344f8
runc:
Version: 1.1.7
GitCommit: v1.1.7-0-g860f061
docker-init:
Version: 0.19.0
GitCommit: de40ad0
DOCKER_DEFAULT_PLATFORM=notset
======= Mutagen Info =========
======= Docker Info =========
Docker platform: PF3DHS3K
Using docker context: default (unix:///var/run/docker.sock)
docker-compose: v2.15.1
Using DOCKER_HOST=unix:///var/run/docker.sock
Docker version: 24.0.4
Able to run simple container that mounts a volume.
Able to use internet inside container.
Docker disk space:
Filesystem Size Used Available Use% Mounted on
overlay 1006.9G 5.7G 949.9G 1% /

Container ddev-academymortgage-dba Removed
Container ddev-academymortgage-db Removed
Container ddev-academymortgage-web Removed
Network ddev-academymortgage_default Removed
Project academymortgage has been stopped.
The ddev-ssh-agent container has been removed. When you start it again you will have to use 'ddev auth ssh' to provide key authentication again.
Existing docker containers:
CONTAINER ID IMAGE COMMAND CREATED STATUS PORTS NAMES
Creating a new ddev project config in the current directory (/home/ben/dev/tryddevproject-16909)
Once completed, your configuration will be written to /home/ben/dev/tryddevproject-16909/.ddev/config.yaml

Configuring unrecognized codebase as project type 'php' at /home/ben/dev/tryddevproject-16909/web
Configuration complete. You may now run 'ddev start'.
Network ddev_default created
Starting tryddevproject-16909...
Container ddev-ssh-agent Started
ssh-agent container is running: If you want to add authentication to the ssh-agent container, run 'ddev auth ssh' to enable your keys.
Network ddev-tryddevproject-16909_default Created
Container ddev-tryddevproject-16909-dba Started
Container ddev-tryddevproject-16909-web Started
Container ddev-tryddevproject-16909-db Started
Container ddev-router Started
Successfully started tryddevproject-16909
Project can be reached at https://tryddevproject-16909.ddev.site/ https://127.0.0.1:32819/
======== Curl of site from inside container:
HTTP/1.1 200 OK
Server: nginx
Date: Fri, 21 Jul 2023 16:11:44 GMT
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
Vary: Accept-Encoding

======== curl -I of http://tryddevproject-16909.ddev.site/ from outside:
HTTP/1.1 200 OK
Server: nginx/1.20.1
Date: Fri, 21 Jul 2023 16:11:44 GMT
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
Vary: Accept-Encoding

======== full curl of http://tryddevproject-16909.ddev.site/ from outside:
Success accessing database... db via TCP/IP
ddev is working. You will want to delete this project with 'ddev delete -Oy tryddevproject-16909'
======== Project ownership on host:
drwxr-xr-x 4 ben ben 4096 Jul 21 10:11 ../tryddevproject-16909
======== Project ownership in container:
drwxr-xr-x 4 ben ben 4096 Jul 21 16:11 /var/www/html
======== In-container filesystem:
Filesystem Type 1K-blocks Used Available Use% Mounted on
/dev/sdc ext4 1055762868 6181008 995878388 1% /var/www/html
======== curl again of tryddevproject-16909 from host:
Success accessing database... db via TCP/IP
ddev is working. You will want to delete this project with 'ddev delete -Oy tryddevproject-16909'
Thanks for running the diagnostic. It was successful.
Please provide the output of this script in a new gist at gist.github.com
Running ddev launch in 5 seconds
If you're brave and you have jq you can delete all tryddevproject instances with this one-liner:
ddev delete -Oy $(ddev list -j |jq -r .raw[].name | grep tryddevproject)
In the future ddev debug test will also provide this option.

</details>         

### Expected Behavior

Database would import

### Actual Behavior

pv: /mnt/ddev_config/.importdb3672667186/*.*sql: No such file or directory
Failed to import database db for academymortgage: failed to import database: exit status 10
stdout:
stderr:

### Steps To Reproduce

1.  Windows 10, wcl2, ubuntu, DDEV v1.21.6
2.
3. run 'ddev import-db'
4. get this error: 'pv: /mnt/ddev_config/.importdb3672667186/*.*sql: No such file or directory
Failed to import database db for academymortgage: failed to import database: exit status 10
stdout:
stderr:'

### Anything else?

 Drive space is not a problem, ddev ssh -s db gets me to the db prompt, df /mnt/ddev_config returns 'df: /mnt/ddev_config: No such file or directory' did a poweroff and start no errors, but didn't fix it, I don't see a /mnt/ddev-config warning on ddev start.

**Comment by rfay** [comment]
Is it possible you could share the database dump you're trying to import? What is the name of the file? 

Please show the output of `ddev exec -s db df /mnt/ddev_config` and `ddev exec -s db ls -l /mnt/ddev_config`

If you have custom configuration, like in config.yaml or docker-compose.*.yaml, please temporarily disable it.

**Comment by supdake** [comment]
The filename is src=academymortgage_1689933605.sql.gz

'ddev exec -s db df /mnt/ddev_config'  returns:

Filesystem      1K-blocks    Used Available Use% Mounted on
/dev/sdc       1055762868 6257312 995802084   1% /mnt/ddev_config


'ddev exec -s db ls -l /mnt/ddev_config' returns:

total 52
drwxr-xr-x 2 ben ben  4096 Jul 21 14:14 apache
drwxr-xr-x 6 ben ben  4096 Jul 21 13:58 commands
-rw-r--r-- 1 ben ben 10111 Jul 21 13:58 config.yaml
drwxr-xr-x 2 ben ben  4096 Jul 21 13:58 db-build
drwxrwxrwx 2 ben ben  4096 Jul 21 14:14 db_snapshots
drwxr-xr-x 2 ben ben  4096 Jul 21 13:58 homeadditions
drwxr-xr-x 2 ben ben  4096 Jul 21 14:14 nginx_full
drwxr-xr-x 2 ben ben  4096 Jul 21 13:58 providers
drwxr-xr-x 2 ben ben  4096 Jul 21 13:58 web-build
drwxr-xr-x 2 ben ben  4096 Jul 21 13:58 web-entrypoint.d
drwxr-xr-x 2 ben ben  4096 Jul 21 13:58 xhprof

**Comment by rfay** [comment]
/mnt/ddev_config is mounted fine. I don't know what happened with your other test.

I imagine the content of your academymortgage_1689933605.sql.gz is not a gzipped file or is not of type gzip. Try ungzipping it and see what's there. Then try doing `ddev import-db --src=academymortgage_1689933605.sql`

**Comment by supdake** [comment]
After running ddev exec -s db df /mnt/ddev_config and ddev exec -s db ls -l /mnt/ddev_config the database imported succesfully.  If you have any idea why I would love to know.

**Comment by rfay** [comment]
I don't know how either of those commands could affect your results. They just show what's there. Perhaps you did a reboot, or a `ddev poweroff`, or restarted Docker...

Glad it's working for you! Happy to continue the conversation here or elsewhere, closing for now.
