### ISSUE TITLE
After upgrade to 1.22.0 "disable_http2 and router = traefik are mutually incompatible"

### ISSUE THREAD

**Issue by ndeet** [ddev/ddev#5200]
### Expected Behavior

ddev to work as expected

### Actual Behavior

All ddev commands give `FATA[0000] unable to read global config: disable_http2 and router = traefik are mutually incompatible, as Traefik does not support disabling HTTP2 `

#### FIX:

Edit your ~/.ddev/global_config.yaml to remove the line `disable_http2: true` (or just set it to `disable_http2: false`. This setting is incompatible with the traefik router. After you've done this you can move on, commands will work, and you can choose whatever router you want, etc.

#### Description:

After upgrading to 1.22.0 on Ubuntu 22.04 LTS I can't run any ddev command anymore, it always shows the same error:
```
❯ ddev start
FATA[0000] unable to read global config: disable_http2 and router = traefik are mutually incompatible, as Traefik does not support disabling HTTP2 
```
Looking into `~/.ddev/global_config.yml`, the setting is `use_traefik: false`, not sure why that error get's triggered at all.

### Steps To Reproduce

- Ubuntu 22.04 LTS (Tuxedo branded version) with KDE
- Default config with disable_http2: true and use_traefik: false
- try to run any `ddev` command
- Error:
```
FATA[0000] unable to read global config: disable_http2 and router = traefik are mutually incompatible, as Traefik does not support disabling HTTP2 
```

Temporarily fixed it by downgrading to 1.21.6 which works as ever.

**Comment by rfay** [comment]
Please turn off disable_http2 (or just delete that line) in your ~/.ddev/global_config.yaml.

**Comment by rfay** [comment]
You apparently have 
```
disable_http2: true
```

**Comment by rfay** [comment]
Your two options as the error message says are:
* Remove the disable_http2 config
* Change to `router: nginx-proxy`

Either one will work to solve the conflict

**Comment by ndeet** [comment]
Thank you for the fast response. The `use_traefik: false` made me assume I met the condition of the error that Traefik is not used, I assumed therefore no need to change the disable_http2 option. Will report back later today when I had time to test.

**Comment by rfay** [comment]
The problem is that `use_traefik: false` is ignored (it's obsolete; traefik is the default router in v1.22.0). So if you just remove those two lines in your ~/.ddev/global_config.yaml mentioning traefik and disable_http2 you'll be all set.

**Comment by ndeet** [comment]
Thank you very much! I removed both global config options and it solved the problem.
