### ISSUE TITLE
Restructure the CMS quickstarts guide

### ISSUE THREAD

**Issue by rpkoller** [ddev/ddev#5206]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

The CMS quickstarts guide currently uses a two level tabbed nav which is hard to navigate as well as comprehend. 

### Describe your solution

- Untwine the first level tabbed nav.
- Each CMS gets an h2
- CMSes with more than one quickstart (for example Drupal) get a tabbed nav for the the different available quickstarts
- Currently Backdrop was found as a subset of Drupal and Statamic as a subset of Laravel. I've moved each out to their own CMS section in the quickstart.md. Both were sort of "hidden" inside their particular "parent". Backdrop is sort of "related" since it is a fork of Drupal 7 but still it should be more prominent imho. And in regards of statamic it is a CMS build on Laravel but not necessarily is a CMS that is build directly from the Laravel folks. it is independent. That is the reason i moved it out. Otherwise if all CMSes built on Laravel would be hosted on Laravel it would be necessary to add a section for Symfony and add CMSes like Drupal, SuluCMS (a quickstart i will add) or in part Typo3 there, which all use Symfony components. 
- Update the introduction to the quickstart.md mentioning python as well. 
- Move the configuratio files section to a dedicated page under usage called managing projects

(*corresponding discussion: https://discord.com/channels/664580571770388500/1124705152092348506/1124705152092348506)

**Comment by Firesphere** [comment]
I strongly agree with your usecase. The tabbed-subtabbed docs are quite tricky to navigate, as well as from a documenting perspective, tricky to write without making an error in indentation.

**Comment by rfay** [comment]
This is done, congratulations @rpkoller !
