### ISSUE TITLE
web_environment problem - environment variable not reaching PHP / Wordpress

### ISSUE THREAD

**Issue by atomtigerzoo** [ddev/ddev#5211]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected Behavior

A variable set in `config.yaml` should be accessible and used inside the containers as written in [the docs](https://ddev.readthedocs.io/en/latest/users/extend/customization-extendibility/#providing-custom-environment-variables-to-a-container)

So I would expect that setting

```
web_environment:
    - WP_DEBUG=false
```

then restarting the containers, that PHP should receive the value above and have WP_DEBUG disbaled.

### Actual Behavior

WP_DEBUG is still true in PHP and in Wordpress.

Logging into the container with SSH I can see that it is set correctly [`WP_DEBUG=false`] but it seems this does not reach PHP or Wordpress.

### Steps To Reproduce

1. set value in config.yaml or with `ddev config --web-environment-add="WP_DEBUG=false"`
2. (re)start ddev
3. debug the value inside PHP => WP_DEBUG is true
4. debug the value inside the container with SSH => WP_DEBUG is false

**Comment by stasadev** [comment]
There is a difference between environment variables and constants.

In this case, you want to change `WP_DEBUG` constant in the WordPress config.

But if you add `WP_DEBUG` as an environment variable, it is declared at a different level.

Reference:

- https://www.php.net/manual/en/language.constants.php
- https://www.php.net/manual/en/function.getenv.php

**Comment by atomtigerzoo** [comment]
Thank you for clarification. I hab in mind, that all the environments variables were available everywhere and thought that it must be visible inside or for PHP, too. SOrry for the misunderstanding then.

Is there a way to set PHP constants (for Wordpress in this case) at config level with ddev? Because when I want to set this or others, then I would have to disable the automatic updates of the two wp-config files, right?

**Comment by stasadev** [comment]
You can either:
- take control of the file where `WP_DEBUG` is set (remove `#ddev-generated`)
- or declare `WP_DEBUG` somewhere else, before including that config file where `WP_DEBUG` is set to `true`

**Comment by atomtigerzoo** [comment]
Yes, I removed the statement from the ddev-specific wp-config for now. But setting it inside the config would be very nice :)

Thank you for your help and time!
