### ISSUE TITLE
Txt file extension in documentation file instead of md

### ISSUE THREAD

**Issue by alessandro-bugatti** [ddev/ddev#5213]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

The readme file in pkg/ddevapp/dotddev_assets/providers/README.txt has the .txt extension instead of .md

### Describe your solution

Change the name from README.txt to README.md

**Comment by rfay** [comment]
Thanks for speaking up!

It is a README.txt because it's intended to be able to be read without any web browser or other technique. It's not intended to be part of the docs. 

Happy to continue the conversation here or elsewhere, but closing for now.
