### ISSUE TITLE
Connecting to wrong database with ddev 1.22.0

### ISSUE THREAD

**Issue by adrian-cid** [ddev/ddev#5217]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected Behavior

When I start more than one project the databases start to being mixed between them. I tried to solutions in #3369 but any of them are working.

ddev version v1.22.0
Docker Compose version 2.20.2

**Comment by rfay** [comment]
Hi @adrian-cid - 

You didn't provide the requested output of `ddev debug test`, so there are lots of questions I'd have to ask. Please go back and do that. You can put it in a gist or other pastebin, or attach as a file. 

Please explain exactly what's happening. Do you have custom config or are you using the DDEV-generated settings.ddev.php (assuming Drupal)? 

Maybe you can create a demonstration trivial project that shows this happening?

You should be able to just populate a single table with a single value and use `ddev mysql` to demonstrate this behavior.

**Comment by adrian-cid** [comment]
Here is the gist

https://gist.github.com/adrian-cid/ed3e0efd28a145d68abb9b6ddd8f5d64

I'm using ddev for drupal using the generated settings.

Once I create a project and import the database all is ok, then I go to another folder and create another project and try to import the configs, and I see drush cim is trying to import the configs in the other project database, then I use ddev sequelace to go and check the database and I'm connected to the wrong database. If I stop the first project and I run drush cim then my imports are done in the correct database.

How can I create a trivial project to demonstrate the problem?

**Comment by adrian-cid** [comment]
by the way, after update to the v 1.22.0 this message started to shown:

```
Error response from daemon: Ports are not available: exposing port TCP 127.0.0.1:443 -> 0.0.0.0:0: not allowed as current user.
You can enable privileged port mapping from Docker -> Settings... -> Advanced -> Enable privileged port mapping' 

```

I have enabled the option in docker desktop and I needed to change the ports in the config.yaml to be able to start the project.

**Comment by rfay** [comment]
Yes, the failure you had with `ddev debug test` is a result of a recent behavior change of Docker Desktop. But it gave you the right answer and you did the right thing with it. All you have to do is what it tells you to do, "You can enable privileged port mapping from Docker -> Settings... -> Advanced -> Enable privileged port mapping' "

**Comment by rfay** [comment]
Now, for a trivial project (or two of them). 

Since Drupal is home territory for you , just create two projects using the [quickstart](https://ddev.readthedocs.io/en/latest/users/quickstart/#drupal), in two different directories. Call them test1 and test2. Then change the title or whatever in each of them to "test1" and "test2". Something that will make it very clear which database is being used. Then you should be able to demonstrate the problem you're talking about. We haven't seen anything like that for a number of years but it's certainly important. I'm happy to do a live debugging screenshare session with you over in [Discord](https://[discord](https://discord.gg/hCZFfAMc5k).gg/hCZFfAMc5k) if you can demonstrate this clearly. It's super important.

**Comment by adrian-cid** [comment]
I have 

Docker Desktop 4.21.1 (114176) is currently the newest version available.

And have the option checked, but I'm still getting the same message

![image](https://github.com/ddev/ddev/assets/9852636/b8fa2df7-de06-46ac-846b-7bd11f0fce23)

**Comment by rfay** [comment]
You do have to stop and restart Docker Desktop, or probably restart your computer, and you then have to answer the prompt when it comes up.

**Comment by rfay** [comment]
I haven't seen anybody install the docker tools (docker CLI) into "User" before. It won't affect anything here, but it means that you'll have to add to your $PATH. 

Is it possible you have multiple docker CLIs out there? What does `which docker` say?

**Comment by rfay** [comment]
`which docker` shows /usr/local/bin/docker, but your Docker Desktop configuration shows otherwise, 
<img width="607" alt="image" src="https://github.com/ddev/ddev/assets/112444/8bf5294b-53e2-4932-b7aa-3c3eaad44aee">

I probably recommend the "System" configuration instead, which (should) point back to your /usr/local/bin/docker setup.

**Comment by rfay** [comment]
If this is related to what happened back in the day, you should be able to `ddev exec ping db` and see the IP address flip back and forth. But I suspect something else must be happening as that seemed to be nicely sorted out way back then. Of course if you have custom configuration, especially `.ddev/docker-compose.*.yaml`, please back that out while you're troubleshooting.

**Comment by adrian-cid** [comment]
I changed the configuration to System.

I started this project first and made ping and this is the output:
```
 Container ddev-ssh-agent  Recreate 
 Container ddev-ssh-agent  Recreated 
 Container ddev-ssh-agent  Started 
ssh-agent container is running: If you want to add authentication to the ssh-agent container, run 'ddev auth ssh' to enable your keys. 
time="2023-08-02T12:39:02-04:00" level=warning msg="network default: network.external.name is deprecated. Please set network.name with external: true" 
 Container ddev-dscm-elasticsearch  Created 
 Container ddev-dscm-portainer  Created 
 Container ddev-dscm-kibana  Created 
 Container ddev-dscm-db  Recreate 
 Container ddev-dscm-web  Created 
 Container ddev-dscm-db  Recreated 
 Container ddev-dscm-elasticsearch  Started 
 Container ddev-dscm-portainer  Started 
 Container ddev-dscm-db  Started 
 Container ddev-dscm-web  Started 
 Container ddev-dscm-kibana  Started 
Starting mutagen sync process... This can take some time. 
.......Mutagen sync flush completed in 9s.
For details on sync status 'ddev mutagen st dscm -l' 
 Container ddev-router  Created 
 Container ddev-router  Started 
> ddev exec ping db
PING db (172.27.0.4) 56(84) bytes of data.
64 bytes from ddev-dscm-db.ddev_default (172.27.0.4): icmp_seq=1 ttl=64 time=0.212 ms
64 bytes from ddev-dscm-db.ddev_default (172.27.0.4): icmp_seq=2 ttl=64 time=0.064 ms
```

I started then the second project and this is the output, as you can see this ping the first project

```
Starting traceline... 
time="2023-08-02T12:43:32-04:00" level=warning msg="network default: network.external.name is deprecated. Please set network.name with external: true" 
 Container ddev-traceline-portainer  Created 
 Container ddev-traceline-db  Created 
 Container ddev-traceline-web  Created 
 Container ddev-traceline-portainer  Started 
 Container ddev-traceline-db  Started 
 Container ddev-traceline-web  Started 
Starting mutagen sync process... This can take some time. 
..............................Mutagen sync flush completed in 33s.
For details on sync status 'ddev mutagen st traceline -l' 
 Container ddev-router  Recreate 
 Container ddev-router  Recreated 
 Container ddev-router  Started 
Successfully started traceline 
Project can be reached at https://traceline.ddev.site:8443 https://127.0.0.1:54624 
> ddev exec ping db
PING db (172.27.0.4) 56(84) bytes of data.
64 bytes from ddev-dscm-db.ddev_default (172.27.0.4): icmp_seq=1 ttl=64 time=0.261 ms
64 bytes from ddev-dscm-db.ddev_default (172.27.0.4): icmp_seq=2 ttl=64 time=0.059 ms
```

**Comment by adrian-cid** [comment]
The problem with the network is coming from portainer, I took the configuration file from 
https://github.com/ddev/ddev-contrib/blob/master/docker-compose-services/portainer/docker-compose.portainer.yaml

For elasticsearch I'm using:
https://github.com/ddev/ddev-contrib/blob/master/docker-compose-services/elasticsearch/docker-compose.elasticsearch.yaml

And for Kibana I'm using:
https://github.com/ddev/ddev-contrib/blob/master/docker-compose-services/kibana/docker-compose.kibana.yaml

[traceline-ddev-docker-compose-full.txt](https://github.com/ddev/ddev/files/12245466/traceline-ddev-docker-compose-full.txt)
[dscm-ddev-docker-compose-full.txt](https://github.com/ddev/ddev/files/12245467/dscm-ddev-docker-compose-full.txt)

I will try to recreate the two test sites later.

**Comment by rfay** [comment]
I imagine that if you remove https://github.com/ddev/ddev-contrib/blob/fd6fd1cd476b70fed8c2766227904af139956108/docker-compose-services/portainer/docker-compose.portainer.yaml#L27-L30

then it will work properly.

**Comment by rfay** [comment]
You might start by just removing docker-compose.portainer.yaml.

**Comment by adrian-cid** [comment]
Problem solved, removing the lines from the portainer file fixed the problem and portainer is still working.

Great job and support, buddy. I hope to see you soon in the Drupal issue queue 😄.

**Comment by rfay** [comment]
Could you please do a PR to ddev-contrib to update it? And consider creating and maintaining a portainer DDEV add-on since you seem to like it.

**Comment by adrian-cid** [comment]
Sure, I will create the PR, I would love to learn more about ddev, but I only have one week using it, If you point me over some docs to learn I can do it without problem.

**Comment by rfay** [comment]
Are you asking how to create a PR? Just go to ddev-contrib and navigate to the lines in question and edit them in a fork and GitHub will let you do it all in the web UI.  https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request
