### ISSUE TITLE
Add global setting for mailhog (or its replacement) port

### ISSUE THREAD

**Issue by Berdir** [ddev/ddev#5220]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

The "problem" is that while the router ports can now be global config, mailhog ports are not yet and they conflict for me on every project because I have a non-docker installation of that as well.

### Describe your solution

Add a global setting for that.

I've seen https://github.com/ddev/ddev/issues/4827, so that will obviously conflict with that. the global setting could have a generic name that doesn't actually use the name mailhog so it doesn't need to be updated if the used solution changes?

**Comment by rfay** [comment]
Have you considered running your external mailhog on a different port? Simple solution...

**Comment by rfay** [comment]
I hit this the other day trying to run ddev on two different WSL2 distros at the same time. Easy to move the main ports, more work to move this one.

**Comment by rfay** [comment]
Please test 
* https://github.com/ddev/ddev/pull/5313#issuecomment-1701826686

**Comment by rfay** [comment]
The global setting is now available in HEAD. Hope you like it!
