### ISSUE TITLE
Incorrect $_SERVER['SHLVL']

### ISSUE THREAD

**Issue by armin-gardenanet** [ddev/ddev#5235]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected Behavior

$_SERVER['SHLVL'] should only been set if the php script is called from the console

### Actual Behavior

$_SERVER['SHLVL'] is always set to 1, no matter if the PHP Script is called from a shell or from a browser/frontend

### Steps To Reproduce

1. `ddev ssh`
2. `php -f test.php`

While the file test.php contains the folling lines:
`<?php
var_dump($_SERVER['SHLVL']);`

the result is always:
`string(1) "1"`

In my opinion this behavior is wrong and SHLVL should only set to a value if the script is really executing in a shell.

Used versions:
DDEV: 1.22.0
PHP: 7.3.33
WSL: 1.2.4.0

### Anything else?

Thank you for DDEV, it's awesome!

**Comment by rfay** [comment]
Help me out with this, I don't see `SHVL` in https://www.php.net/manual/en/reserved.variables.server.php

**Comment by armin-gardenanet** [comment]
you are missing a L, its called SH**L**VL

**Comment by rfay** [comment]
Well, 'SHLVL' is also not listed in https://www.php.net/manual/en/reserved.variables.server.php. 

Can you explain with description and links why you expect it to be set?

**Comment by rfay** [comment]
AFACT SHLVL is a *shell* construct, which is sometimes reflected in $_SERVER ?  Looking forward to your info. I certainly don't 

You say 
> $_SERVER['SHLVL'] should only been set if the php script is called from the console

What would the "console" be in this context? terminal?

**Comment by armin-gardenanet** [comment]
> Can you explain with description and links why you expect it to be set?
Im expecting that $_SERVER['SHLVL'] is not set when calling a PHP script from the browser (which actually is). It could may be set when a PHP script is called from the shell by using the command `php -f test.php`.

With "console" i was meaning the terminal.

Please let me know, if u need more informations

**Comment by rfay** [comment]
@gilbertsoft probably helped explain what you're seeing.

Apparently PHP imports into $_SERVER all existing variables. So SHLVL would come from a parent process.

In DDEV v1.22+, supervisord is started from a shell process, similar to `ddev exec /start.sh`, which would mean that supervisord (which then launches php-fpm) would have started from the shell. In previous versions, start.sh was run directly by the Dockerfile.

**Comment by armin-gardenanet** [comment]
@rfay we used the follow condition to detect if a call was executed by a cronjob or by a customer (browser).
```
if($_SERVER['SHELL'] || $_SERVER['SHLVL']) {
  ...
}
```
Since i update to DDEV 1.22, our condition didnt work well because it was always true ($_SERVER['SHLVL'] was always set). That broke my local enviroment. To have a quick fix to this, i removed $_SERVER['SHLVL'] from the condition as its not officially supported.

As you mentionend
> In DDEV v1.22+, supervisord is started from a shell process, ...
this is probably the reason why $_SERVER['SHLVL'] is always set since v1.22.

The best solution is probably to not use $_SERVER['SHLVL'] in the own code :)

**Comment by rfay** [comment]
Yeah, I don't think that that is a correct (or php-supported) detection technique. 

But here you're talking about something that you expect to use in production, right? I wouldn't think you can count on it there either?

Anyway, I'm glad you have it sorted out. I'm quite sure you want a more robust technique. I'm interested in hearing what you use.

I'm happy to continue the conversation here or elsewhere, but closing this for now.
