### ISSUE TITLE
Also remove unused files from an add-on update

### ISSUE THREAD

**Issue by hanoii** [ddev/ddev#5236]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

Nope!

### Describe your solution

In working with https://github.com/hanoii/ddev-sshd/ at some point I changed one of the installed files from the install.yaml file, and I obviously was left out with the previous file in the project.

Now that we have a sanpshot metadata, wouldn't it make sense to remove files that are no longer present if the addon gets updated (with the condition that #ddev-generated tag is still there)?

**Comment by rfay** [comment]
Not sure I understand, but note that there are also removal actions now, so that's an additional path. 

When are you talking about removing? Currently we would do that only on `ddev get --remove`. Are you talking about doing it on `ddev get <url>` ? It's not a bad idea, but how would you know to do it?

**Comment by hanoii** [comment]
@rfay yes, see this commit for example: https://github.com/hanoii/ddev-sshd/commit/01e584f17a1b81e5bb5a850d9abe5cb40367d41e on `install.yaml`.

```
-  - homeadditions/.bashrc.d/sshd
+  - homeadditions/.bashrc.sshd
```

You can compare the installed files of the metadata before the update with the install.yaml files of the new get and act on difference. In this case `homeadditions/.bashrc.d/sshd` would be removed from the project.

**Comment by rfay** [comment]
So you could do this with a pre_install_actions or post_install_actions script if you knew about it...  Does that solve this? It seems like mostly a pretty free-form problem best solved by a script?

**Comment by hanoii** [comment]
hmmm, not exactly that, just the removal of the files, because I am thinking that removal_actions may have more destructive actions than just remove a file that's no longer needed

**Comment by hanoii** [comment]
The only thing I am saying is that if an addon installed a, b and c, and the next get installs a, b, and d, ddev can remove c unless `#ddev-generated` was removed.

**Comment by hanoii** [comment]
Although if what's on install_files is a directory, that might be harder to work around, I think you are right, better leave it ot the addon
