### ISSUE TITLE
ddev-router healthcheck.sh  permission denied

### ISSUE THREAD

**Issue by manoj-apare** [ddev/ddev#5243]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Output of `ddev debug test`

Running `ddev start` I see below error:

`Failed to start ahi: ddev-router failed to become ready; debug with 'docker logs ddev-router' and 'docker inspect --format "{{json .State.Health }}" ddev-router'; logOutput=, err=health check timed out after 1m0s: labels map[com.docker.compose.service:ddev-router] timed out without becoming healthy, status=`

But still the web app is accessible in browser and working fine.

To debug I ran `docker inspect --format "{{json .State.Health }}" ddev-router` and I got the below output:

`{"Status":"unhealthy","FailingStreak":757,"Log":[{"Start":"2023-08-07T11:20:47.937625831Z","End":"2023-08-07T11:20:48.076172289Z","ExitCode":126,"Output":"/bin/bash: /healthcheck.sh: Permission denied\n"},{"Start":"2023-08-07T11:20:49.087961165Z","End":"2023-08-07T11:20:49.258456123Z","ExitCode":126,"Output":"/bin/bash: /healthcheck.sh: Permission denied\n"},{"Start":"2023-08-07T11:20:50.271309582Z","End":"2023-08-07T11:20:50.407708957Z","ExitCode":126,"Output":"/bin/bash: /healthcheck.sh: Permission denied\n"},{"Start":"2023-08-07T11:20:51.418983124Z","End":"2023-08-07T11:20:51.563713416Z","ExitCode":126,"Output":"/bin/bash: /healthcheck.sh: Permission denied\n"},{"Start":"2023-08-07T11:20:52.574944875Z","End":"2023-08-07T11:20:52.654258958Z","ExitCode":126,"Output":"/bin/bash: /healthcheck.sh: Permission denied\n"}]}`

### Expected Behavior

**ddev-router** container should be **healthy**

### Actual Behavior

**ddev-router** container should be **unhealthy**

**Comment by ted933** [comment]
See [umask 0027 prevents healthcheck in ddev-router #5239](https://github.com/ddev/ddev/issues/5239)

**Comment by manoj-apare** [comment]
@rfay 
Sure will include output of `ddev debug test` from next time onwards.

Thanks. `chmod 755 ~/.ddev/router-build/*` this solved the problem.
