### ISSUE TITLE
Deprecation notice of removed "dba" container occurs too often, collapse into one message?

### ISSUE THREAD

**Issue by garvinhicking** [ddev/ddev#5246]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Output of `ddev debug test`

<details><summary>Expand `ddev debug test` diagnostic information</summary>

```
(shouldn't apply so I try to not waste the ressources for this at this point)
```
</details>         

### Expected Behavior

Using ddev commands lets me work without interruption or duplicate messages

### Actual Behavior

Getting duplicate warning messages about a deprecated functionality on every command  like `ddev launch` or even `ddev ssh`:

````
WARN[0000] PhpMyAdmin (`dba`) is no longer part of DDEV core, please edit your `omit_containers` configuration to remove it
WARN[0000] PhpMyAdmin (`dba`) is no longer part of DDEV core, please edit your `omit_containers` configuration to remove it
PhpMyAdmin (`dba`) is no longer part of DDEV core, please edit your `omit_containers` configuration to remove it
PhpMyAdmin (`dba`) is no longer part of DDEV core, please edit your `omit_containers` configuration to remove it
PhpMyAdmin (`dba`) is no longer part of DDEV core, please edit your `omit_containers` configuration to remove it
````

### Steps To Reproduce

In a ddev 1.22.x environment with a config of `omit_containers: [dba]` run any ddev command and see the duplicate messages.

### Anything else?

`dba` was removed via https://github.com/ddev/ddev/issues/3534.

I do see the need of informing users if the dba-container was maybe referenced, but if I previously explicitly omitted the container, I don't really need the information that it has been removed? (and not 5 times; one time per project would be sufficient, and best only once and never again)

Our reason for not just adding `omit_containers: []` to the configuration is, that we also have co-workers on older ddev versions, and if we change the ddev config to remove this `omit_containers` statement, those people will actually get `dba` installed for them.

We would love a way to either "mark a notice as read" to include in the configuration (harder feature, maybe not really woth effort), or better, just remove the information for an omitted container...?

(Once again, many thanks for the work on ddev, it can't be stated often enough)

**Comment by rfay** [comment]
We won't be trying to solve this, since it's temporary. DBA has been removed, once people have it out of their config, the messages are gone. The reason you're seeing it more than once is you have it configured in various places, and there's also a message on `ddev start` right now that tries to help you figure that out as well.

Are you having trouble figuring out how to remove it from your config @garvinhicking ? 

Chasing after a temporary problem by adding code complexity just isn't worth it.

**Comment by garvinhicking** [comment]
My thing is, we cannot remove it, because colleagues are still running on older ddev versions, and I think the message is not really useful in first place? Why is it shown in a case, where I omit the package, that is now already omitted by default - it only requires work for you, when in reality the outcome is the same?

(But if you decide against changing it, I can be happily silent and we can close this, I just thought it adds a layer of uneeded verbosity and wanted to help improve it ;))

**Comment by rfay** [comment]
I guess there could be an argument for just not showing the message at all. That doesn't add complexity. What do you think @gilbertsoft ?

**Comment by rfay** [comment]
I'm fine with just removing the warning. If anybody wants to take on this super easy PR it's welcome.

**Comment by fe-hicking** [comment]
Oh yes, I'd love to try! :-) Will report back here.
