### ISSUE TITLE
Pull failed: exit status 1 (PLATFORMSH_CLI_TOKEN not set)

### ISSUE THREAD

**Issue by budda** [ddev/ddev#5251]
Installed ddev and ddev-platformsh, attempting to do my first pull results in an error with no assistance in how to resolve (or the cause!). I'm working on a Drupal 7 project.

```% ddev pull platform      
You're about to delete the current database and files and replace with the results of a fresh pull.
Would you like to continue? [Y/n] (yes): Y
Authenticating...
Please make sure you have set PLATFORMSH_CLI_TOKEN.
Pull failed: exit status 1
```

I can ssh in to the p.sh project environment fine on the terminal so authentication works.

**Comment by budda** [comment]
doing `% echo $PLATFORMSH_CLI_TOKEN` returns my CLI token ok, so assume it's fine?

**Comment by budda** [comment]
> Just to clarify:
> 
> 1. Did you
>    
>    1. clone your repository from platform.sh (i.e. `platform get <projectid>`)? OR
>    2. clone your repository from a source control management platform (e.g. Github)?
> 2. If you did 1ii above, did you associate your local copy with platform (i.e. `platform set-remote <projectid>`)?
> 3. Did you do `ddev config` before running `ddev get ddev/ddev-platformsh` ?
> 4. Which method did you use to authenticate to platform.sh with the platform.sh cli tool: token or browser?
> 5. Did you
>    
>    1. Add your public ssh key to your platform.sh account? OR
>    2. have the platform.sh cli generate and add an ssh key for you?
> 6. When running `ddev get ddev/ddev-platformsh` did it
>    
>    1. prompt you to `Please enter your platform.sh token: `? OR
>    2. Say `Using existing PLATFORMSH_CLI_TOKEN.`?
> 
> Anything else in the logs that might give us some clues as to why it can't locate your token?

1. used `platform get`
3. yes
4. token - MFA is enabled
5.  platform tool generated ssh certificate
6. I think it said "Using existing PLATFORMSH_CLI_TOKEN"

What/where are the logs I should be looking at?

**Comment by rfay** [comment]
No, you would test with `ddev exec 'echo $PLATFORMSH_CLI_TOKEN'` because it needs to be inside the container. 

Setup is explained both in the .ddev/providers/platform.yaml in your project and also at https://ddev.readthedocs.io/en/latest/users/providers/platform/

You need to expose the PLATFORMSH_CLI_TOKEN to the container:

Number 2 in the docs is:

* Add the API token to the web_environment section in your global DDEV configuration at ~/.ddev/global_config.yaml:
```yaml
web_environment:
  - PLATFORMSH_CLI_TOKEN=abcdeyourtoken
```

**Comment by rfay** [comment]
Please let us know if that solved the problem for you @budda , thanks!

**Comment by rfay** [comment]
I'm going to close this for now @budda , happy to continue the conversation here or elsewhere. I see you acknowledged https://github.com/ddev/ddev/issues/5251#issuecomment-1673564876
