### ISSUE TITLE
failed build with nodejs_version:14 and webimage_extra_packages[build_essential, libnotify-bin,python]

### ISSUE THREAD

**Issue by kazajhodo** [ddev/ddev#5253]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Output of `ddev debug test`

<details><summary>Expand `ddev debug test` diagnostic information</summary>

```
[Output](https://gist.github.com/kazajhodo/a418a89fec49181b5b38b976de3e8bab)
```
</details>         

### Expected Behavior

Dev starts and builds as normal.

### Actual Behavior

Ddev is crashing with:

```
executor failed running [/bin/sh -c apt-get -qq update && DEBIAN_FRONTEND=noninteractive apt-get -qq install -y -o Dpkg::Options::="--force-confold" --no-install-recommends --no-install-suggests build-essential libnotify-bin make python]: exit code: 100
```

Due to webimage_extra_packages definition:
```
webimage_extra_packages:
    - build-essential
    - libnotify-bin
    - make
    - python
```

If remove and ddev restart, I then run into:

```
executor failed running [/bin/sh -c bash /tmp/setup_node.sh >/dev/null && apt-get install -y nodejs >/dev/null]: exit code: 1
```

Due to this line in config.yaml.
```
nodejs_version: '14'
```

If I remove all of the above, the project loads. This is since upgrading to 1.22.1.

If I remove the troublesome lines, the container starts with node 18 as the default. Attempted integer or string, didn't matter, also attempted array syntax vs dash syntax with webimage_extra_packages, didn't matter.

Current documentation states that 14 may be passed as a nodejs_version.

In previous version of ddev, the nodejs_version and webimage_extra_packages worked with this configuration. I did attempt to restart the project with only 'build-essential' in the array, but this also failed. I didn't try singling out the others.

If I 'ddev nvm install 14 && ddev nvm use 14', 'node -v' within the container returns 14.

If I ddev delete the project and rebuild, with the error causing mentions above within config.yaml, build fails with same errors. I expected this to be the case, but tried it anyways. Remove them and once again the project starts as expected without issue.

### Steps To Reproduce

Within config.yaml, add:

```
nodejs_version: '14'
webimage_extra_packages:
    - build-essential
    - libnotify-bin
    - make
    - python
```

Ddev start. Hopefully will return the reported errors.

Either configuration definition alone, will also return errors, as described above. I had just finished running a brew upgrade, so everything should be at its latest versions for docker-compose and so on.

**Comment by rfay** [comment]
I'm not having any trouble with this configuration, 
```
nodejs_version: "14"
webimage_extra_packages:
  - build-essential
  - libnotify-bin
  - make
  - python
```

You may possibly have had network trouble? Please try again. 

Also note that you don't need `make` if you're doing `build-essential`, which includes `make`. Also you'll want to be careful with `python`.  `python3` is already installed by default, as is `python-is-python3`, which gives you the `python` command as `python3`.

**Comment by kazajhodo** [comment]
I tried many times, and restarted Colima as well. If you can't replicate, that just means its something else specific to our project, perhaps machine.

Thanks for the instruction regarding the package includes. I find those sorts of things happen very very often, and prefer to avoid them.  :) I'll certainly remove make and python, as per your description, they are clearly not needed. I should've reviewed the includes.

I can't think of any other details that would be key to replication, which is on me, so we'll have to close the issue and assume its something we've done. I deleted .ddev entirely and created a config.yaml with ddev config, added webimage_extra_packages, with only build-essential and libnotify-bin, changed nodejs_version to 14 and added in our hooks- also tested without hooks.

Crashed with:
```
failed to solve: executor failed running [/bin/sh -c apt-get -qq update && DEBIAN_FRONTEND=noninteractive apt-get -qq install -y -o Dpkg::Options::="--force-confold" --no-install-recommends --no-install-suggests build-essential libnotify-bin]: exit code: 100
Failed to start metro: docker-compose build failed: ComposeCmd failed to run 'COMPOSE_PROJECT_NAME=ddev-metro docker-compose -f /Users/kazajhodo/Projects/metro/.ddev/.ddev-docker-compose-full.yaml --progress=quiet build', action='[--progress=quiet build]', err='exit status 17', stdout='', stderr='failed to solve: executor failed running [/bin/sh -c apt-get -qq update && DEBIAN_FRONTEND=noninteractive apt-get -qq install -y -o Dpkg::Options::="--force-confold" --no-install-recommends --no-install-suggests build-essential libnotify-bin]: exit code: 100', output='', stderr='failed to solve: executor failed running [/bin/sh -c apt-get -qq update && DEBIAN_FRONTEND=noninteractive apt-get -qq install -y -o Dpkg::Options::="--force-confold" --no-install-recommends --no-install-suggests build-essential libnotify-bin]: exit code: 100'
```

I then sshed into the container and ran:
```
apt-get -qq update && DEBIAN_FRONTEND=noninteractive apt-get -qq install -y -o Dpkg::Options::="--force-confold" --no-install-recommends --no-install-suggests build-essential libnotify-bin
```

Responded:
E: List directory /var/lib/apt/lists/partial is missing. - Acquire (13: Permission denied)

Does that help at all? Only thing I could think to try.

**Comment by kazajhodo** [comment]
I did take python out, as that seemed an unneeded complication.

**Comment by rfay** [comment]
You forgot the `sudo` with your `apt-get install`

**Comment by kazajhodo** [comment]
Ok, trying.

**Comment by kazajhodo** [comment]
Ran:

```
sudo apt-get -qq update && DEBIAN_FRONTEND=noninteractive apt-get -qq install -y -o Dpkg::Options::="--force-confold" --no-install-recommends --no-install-suggests build-essential libnotify-bin
```

Responded:
```
E: Could not open lock file /var/lib/dpkg/lock-frontend - open (13: Permission denied)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), are you root?
```

**Comment by kazajhodo** [comment]
I may be noobing this up, do I need to pass a user since its all non-interactive? sudo -u root -p...

**Comment by rfay** [comment]
You need `sudo` on both `apt-get update` and `apt-get install`

**Comment by kazajhodo** [comment]
Damn it. Smile.

**Comment by rfay** [comment]
All you have to do is `sudo apt update` and `sudo apt install -y <packagelist>`

**Comment by kazajhodo** [comment]
Yeah, I was just trying to replicate what the script was doing to get a better error response.

That ran fine with sudo on both.

Could that be the issue itself, I just copied what was being ran from the error message, those had no sudo prefixes.

**Comment by kazajhodo** [comment]
To bring it back to the front, I'm specifically referencing the error I received when running ddev start.

```
failed to solve: executor failed running [/bin/sh -c apt-get -qq update && DEBIAN_FRONTEND=noninteractive apt-get -qq install -y -o Dpkg::Options::="--force-confold" --no-install-recommends --no-install-suggests build-essential libnotify-bin]: exit code: 100
```

Per your instruction, prefixing sudo, the command ran without issue on the web container.

**Comment by rfay** [comment]
I imagine you have something wrong with your docker image or your docker cache. 

You can kill off the build cache with `docker buildx prune -a`

You can kill off all your docker images (does no harm) with `docker rm -f $(docker ps -aq)` and `docker rmi -f $(docker images -q)`

You can recreate your colima profile with `colima delete` and `colima start --cpu 4 --memory 6 --disk 100 --vm-type=qemu --mount-type=sshfs --dns=1.1.1.1` (BUT YOU WILL LOSE DATABASES, so `ddev snapshot -a` first if that matters)

**Comment by kazajhodo** [comment]
Yup, I've written scripts to do that stuff before, looks familiar. I thought something with cache as well, and found some other posts mentioning similar things.

Attempting. It must be something specifically related to me, or everyone would've ran into this. Attempting.

**Comment by rfay** [comment]
I should have mentioned a couple of things earlier:

* You can see the full output with `ddev debug refresh`
* You can see the full build with `export DDEV_VERBOSE=true` and `ddev start`
* You can see the full set of things that are being attempted in `.ddev/.webimageBuild/Dockerfile`

**Comment by kazajhodo** [comment]
Alright, so I did what you suggested, and just went full send. I manage 60+ish sites, and have recently converted them all over to ddev, so I wanted to get this right. I don't care if I have to pull dbs. We do everything in ddev now.

I've also added an issue for our weekly developer meeting to push for a ddev sponsorship. You guys should be well paid for your work.

Rained hellfire on docker, deleting all images... technically I think I still have volumes remaining- deleted colima and restarted it. Had it running the same way except with -m 8.

For reference, I grabbed my history- the commands were:
```
docker buildx prune -a
docker rm -f $(docker ps -aq)
docker rmi -f $(docker images -q)
colima delete
colima start --cpu 4 --memory 6 --disk 100 --vm-type=qemu --mount-type=sshfs --dns=1.1.1.1
```

This caused all the docker images to be re-downloaded. Afterwards I stopped getting the reported build errors regarding webimage_extra_packages and nodejs_version.

Now the question is, what HAS to be done for others that encounter this issue. I do think theres a chance this will come up with those upgrading to 1.22.1.

I'm not sure I needed to delete and restart Colima, doubt it. Likely just the docker cleanup; but I think that removes databases. Which for many is going to be annoying... but making an image can get you around that simply enough.

My teams are about to upgrade as well, I may be the first that did it. I want to make sure we're taking the least destructive path as possible.

It seems to me the repull of docker images was the critical part, and this seems only related to the web pulls. For instance I think the database images are likely fine, solr images in our case fine. Is there a way to repull only web related packages/images?

**Comment by rfay** [comment]
> Now the question is, what HAS to be done for others that encounter this issue. I do think theres a chance this will come up with those upgrading to 1.22.1.

I doubt this has to do with upgrading. It's more likely your docker buildx cache was corrupted by a network failure in an earlier build. My bet is just the build cache would have fixed it.

**Comment by kazajhodo** [comment]
Ok. The docker buildx command actually didn't work when I attempted to run it, but was likely cleared through the other methods.

Does that mean we should be able to `docker buildx prune -a`, and be done?

**Comment by rfay** [comment]
`docker buildx prune -a` was my suspicion. If you don't have the `docker buildx` subcommand it means you need to get it :) On macOS `brew install docker-buildx`. Read the instructions on `brew info docker-buildx` to enable.

**Comment by kazajhodo** [comment]
Yeah I just found it going through the man.

https://docs.docker.com/go/buildx/

**Comment by rfay** [comment]
Bottom line is I don't think you'll see this on other people's setup. And thanks so much for your support for the project. I'm happy to do a call with anybody in your company about DDEV sustainability and future plans.

**Comment by kazajhodo** [comment]
Alright, well I'll let you know if anyone else hits it. I destroyed everything, so I don't think I'll hit it again, haha.

I'll have the team let me know if we hit the exact same issue. Might just be lucky me, I'd find that surprising though. We'll find out.

Thanks for guidance and the rapid responses. Kinda over-the-top really, but obviously super helpful. As well the other information about our webimage_extra_packages includes. I took them out of our scaffold. We have a little composer installed module that pulls in ddev and adds all of our custom commands to it. Runs another version of the `ddev config` as well.

We're finally all not running and maintaining our own locals. Because we finally have something fast enough to replace them.

Again, thanks.

**Comment by g-brodiei** [comment]
Hi, I met similar issue after upgrading to 1.22.1 today.

### Environment
1. Ventura 13.4.1
2. M2
3. ddev 1.22.1
4. colima 0.5.4

### Step to reproduce
1. Upgraded with `brew upgrade ddev`, now 1.22.1
5. and when prompt to restart `ddev poweroff`, I hit `yes`.
6. Then when I hit `ddev start`, I have the following error message.
7. Removing the line of `nodejs_version: "16"` in `config.yaml` will start container successfully.

### Error message

```bash
failed to solve: executor failed running [/bin/sh -c npm install --unsafe-perm=true --global gulp-cli yarn || ( npm config set unsafe-perm true && npm install --global gulp-cli yarn )]: exit code: 127 
Failed to restart nii-d9: docker-compose build failed: ComposeCmd failed to run 'COMPOSE_PROJECT_NAME=ddev-nii-d9 docker-compose -f /Users/g-brodiei/project/nii-d9/.ddev/.ddev-docker-compose-full.yaml --progress=quiet build', action='[--progress=quiet build]', err='exit status 17', stdout='', stderr='failed to solve: executor failed running [/bin/sh -c npm install --unsafe-perm=true --global gulp-cli yarn || ( npm config set unsafe-perm true && npm install --global gulp-cli yarn )]: exit code: 127', output='', stderr='failed to solve: executor failed running [/bin/sh -c npm install --unsafe-perm=true --global gulp-cli yarn || ( npm config set unsafe-perm true && npm install --global gulp-cli yarn )]: exit code: 127'
```
```yaml
name: nii-d9
type: drupal9
docroot: docroot
php_version: "8.1"
webserver_type: nginx-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
database:
    type: mariadb
    version: "10.4"
nfs_mount_enabled: false
mutagen_enabled: false
use_dns_when_possible: true
composer_version: "2"
web_environment: []
# nodejs_version: "16" <---- I commented this line, then it works!
```

Running `ddev debug test` shows no error messages.

If there are other methods to debug this, please let me know, thanks!

**Comment by rfay** [comment]
Hi @kazajhodo - you might have had a networking issue.

You can see the full effort to build with `ddev debug refresh`, see if that helps.

Consider `export DDEV_VERBOSE=true && ddev debug refresh` if that doesn't give you enough information.
