### ISSUE TITLE
`ddev start` always creates a new hash_salt in settings.ddev.php (Drupal); should be static.

### ISSUE THREAD

**Issue by TonyTheFerg** [ddev/ddev#5255]
### Expected Behavior

Consistent hash_salt or none at all, not sure.

### Actual Behavior

Whenever ddev builds the containers, they create a new hash_salt every time. 

This creates [issues with the token values on Drupal contextual links](https://www.drupal.org/project/drupal/issues/3010562), as the hash_salt value is [checked here](https://git.drupalcode.org/project/drupal/-/blob/10.1.x/core/modules/contextual/src/ContextualController.php#L77). which leads to this issue.

You can reproduce this by opening the `settings.ddev.php` file, doing `ddev poweroff`, and then `ddev start` to view it change in real-time.

So a temporary fix is to place your hash_salt value AFTER the $ddev_settings section that gets added by DDEV in settings.php. This will allow that value to persist despite the new hash salt value that's created everytime DDEV starts up.

```
// Automatically generated include for settings managed by ddev.
$ddev_settings = dirname(__FILE__) . '/settings.ddev.php';
if (getenv('IS_DDEV_PROJECT') == 'true' && is_readable($ddev_settings)) {
  require $ddev_settings;
}

$settings['hash_salt'] = file_get_contents('/home/example/salt.txt');
```

You could also just move your local settings below the ddev settings, and put the hash_salt value in settings.local.php instead.

**Comment by rfay** [comment]
@TonyTheFerg could you please test the artifacts in https://github.com/ddev/ddev/pull/5262#issuecomment-1678306651 with your use case?

**Comment by darko-hrgovic** [comment]
> ### Expected Behavior
> Consistent hash_salt or none at all, not sure.
> 
> ### Actual Behavior
> Whenever ddev builds the containers, they create a new hash_salt every time.
> 
> This creates [issues with the token values on Drupal contextual links](https://www.drupal.org/project/drupal/issues/3010562), as the hash_salt value is [checked here](https://git.drupalcode.org/project/drupal/-/blob/10.1.x/core/modules/contextual/src/ContextualController.php#L77). which leads to this issue.
> 
> You can reproduce this by opening the `settings.ddev.php` file, doing `ddev poweroff`, and then `ddev start` to view it change in real-time.
> 
> So a temporary fix is to place your hash_salt value AFTER the $ddev_settings section that gets added by DDEV in settings.php. This will allow that value to persist despite the new hash salt value that's created everytime DDEV starts up.
> 
> ```
> // Automatically generated include for settings managed by ddev.
> $ddev_settings = dirname(__FILE__) . '/settings.ddev.php';
> if (getenv('IS_DDEV_PROJECT') == 'true' && is_readable($ddev_settings)) {
>   require $ddev_settings;
> }
> 
> $settings['hash_salt'] = file_get_contents('/home/example/salt.txt');
> ```
> 
> You could also just move your local settings below the ddev settings, and put the hash_salt value in settings.local.php instead.

This doesn't work in D7. Whatever I do, I cannot override the hash set by DDEV. Moving settings.local.php after settings.ddev.php and setting a value for $drupal_hash_salt in settings.local.php does not change the hash defined in settings.ddev.php. This leaves all images inserted with Insert module with ?itok broken locally, for example. The only way I can hack in my own production value of $drupal_hash_salt is to hack core bootstrap.inc drupal_get_hash_salt() and manually set it there, which seems unsustainable. How can I change the hash defined by DDEV?

**Comment by rfay** [comment]
You're in charge of the settings. If you're changing the hash salt in settings.php after settings.ddev.php gets included, then you are in full control. It has nothing to do with DDEV's convenience file `settings.ddev.php`. I recommend stepping through settings.php using xdebug and PhpStorm or your favorite IDE.

Again, all DDEV does is provide a convenience file, settings.ddev.php. Your settings.php includes it (although you can turn that behavior off and manage settings yourself, see https://ddev.readthedocs.io/en/stable/users/usage/cms-settings/). 

In your settings.php, after the inclusion of settings.ddev.php, if you change the hash_salt... you've changed it. I can't tell you what's going wrong on your site.
