### ISSUE TITLE
Codespaces changed preview domain to app.github.dev (ddev launch fails)

### ISSUE THREAD

**Issue by mandrasch** [ddev/ddev#5256]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected Behavior

- `ddev launch` works in codespaces ddev project, e.g. craftcms project

### Actual Behavior

- url not found since github changed codespaces url, see below

### Anything else?

Codespaces changed their port forwarding domain:

> To prepare for this change, replace any hardcoded references to preview.app.github.dev in your code with the GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN environment variable by July 31 to avoid any disruptions. The environment variable value will be updated from preview.app.github.dev to app.github.dev when the migration completes. Learn more about environments variables [here](https://docs.github.com/en/codespaces/developing-in-codespaces/default-environment-variables-for-your-codespace).

https://github.blog/changelog/2023-07-14-codespaces-port-forwarding-domain-name-updates/

Hardcoded here:

- https://github.com/ddev/ddev/blob/ef444846f1819c8a3f71495bb4628cebc16669aa/pkg/ddevapp/ddevapp.go#L2545-L2546

(Currently I don't have time resources to change and test this myself and provide a quick PR. Hope that I can provide such small fixes in future by myself (need to learn the whole workflow how to test that ddev still works after my changes 😬 😉 ))

**Comment by rfay** [comment]
Thanks! This one you could probably just do with the edit button on github, it's welcome. And testing might be as easy as downloading the artifacts from the PR page and running them on Codespaces.

**Comment by rfay** [comment]
This was fixed in
* https://github.com/ddev/ddev/pull/5257
