### ISSUE TITLE
Since 1.22 .ddev/config.*.yaml is not gitignored anymore

### ISSUE THREAD

**Issue by ericdsd** [ddev/ddev#5270]
### Expected Behavior
On ddev version prior to 1.22 we used to create various local ddev config overrides eg config.mac.yaml or config.test.yaml that were previously gitignored by default (which was a smart feature).

If there's no underlying reason to only ignore config.local.yaml by default it would be great to have the feature back as we end up having uncommitted files after ddev update.

.ddev/.gitignore previously contained 
/config.*.y*ml

### Actual Behavior

.ddev/.gitignore 
now contains :
/config.local.y*ml
Previously ignored config overrides are now considered as untracked files in our projects.

### Steps To Reproduce

Create a config override (not named config.local.yaml) eg config.ports.yaml in .ddev directory of a git managed project
This file will appear as untracked on git status.

**Comment by rfay** [comment]
This changed in v1.22.0, please see the [release notes](https://github.com/ddev/ddev/releases/tag/v1.22.0)

The behavior now is that `config.local.yaml` is gitignored, but all the others are not. This makes it so that add-on configuration gets properly committed.

**Comment by ericdsd** [comment]
Hi thank you for your fast answer. I get the point of the change, and missed that part of the release note.
It will impact people for some time, not sure it benefit more people though, but this is indeed not critical.

**Comment by ericdsd** [comment]
Closing the issue as it's a won't fix

**Comment by rfay** [comment]
Unfortunately, since add-ons have become so popular, the *old* way was impacting loads of people. add-on config.*.yaml added to a project was not being checked in.
