### ISSUE TITLE
Add-on (phpMyAdmin) `#ddev-generated` files not added to `.ddev/.gitignore`

### ISSUE THREAD

**Issue by Ambient-Impact** [ddev/ddev#5275]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

After switching to the phpMyAdmin add-on (see #3534), I noticed the files that are generated (with `#ddev-generated` in them` don't get added to `.ddev/.gitignore` like I would expect.

### Describe your solution

I added this to my root `.gitignore` for the time being:

```
/.ddev/.disabled-services/docker-compose.phpmyadmin.yaml
/.ddev/docker-compose.phpmyadmin-norouter.yaml
/.ddev/docker-compose.phpmyadmin.yaml
/.ddev/commands/host/phpmyadmin
```

I'd much rather DDEV handled this automagically it its own `.gitignore`.

Am I missing something

### Additional context

DDEV version is v1.22.1

Our DDEV config can be found in https://github.com/neurocracy/omnipedia/tree/9.x/.ddev

I also found #2180 while searching but unsure if it's directly related.

**Comment by rfay** [comment]
I think it's behaving correctly. People in general want to check in add-ons so their whole team has the same behavior. 

The files you list are intended to be checked in with git.

**Comment by Ambient-Impact** [comment]
I very much favour an automated workflow as my methodology; we use Composer to manage our many custom Drupal modules along with Yarn for front-end packages; as a result, we avoid committing anything that can or should be pulled in automatically, instead relying on lock files and similar things to keep different environments synced. Given all of the other stuff that's not meant to be checked in which gets built or pulled in automatically, this feels unexpected from a DX point of view, or at least it does from my point of view.

**Comment by rfay** [comment]
The DDEV philosophy is that everything that is part of a project can be checked in. Sorry it doesn't match yours. The basic idea is that any developer should be able to check out a project and `ddev start` and have it work the same as every one of their colleagues. That's why it's this way.

**Comment by Ambient-Impact** [comment]
Doesn't running `ddev start` for the first time download and build a bunch of stuff (automatically `.gitignore`d by default) as defined by `.ddev/config.yaml` (which I check in)? I clearly don't need to check in the stuff that it adds to `.gitignore` to reproduce the project on another machine. Ultimately it's your project and you can decide what you want to do, but I was just suggesting that how DDEV already treats its own generated configs be extended to how the generated configs for add-ons are treated by default, because I found it confusing that it did that in the former case but not the latter.

**Comment by rfay** [comment]
`ddev start` does not install add-ons. `ddev start` does generate many files that you do not need to check in. But it has no way to know what add-ons you might have. 

It might be possible to make `ddev start` use the new metadata that's available to reinstall all add-ons... if you checked in the metadata. There are no plans to do that.

**Comment by rfay** [comment]
Of course you can take over the .ddev/.gitignore by removing the #ddev-generated from it and checking it in. You can also use a project or global .gitignore to implement the way you prefer to work. The way it's working for add-ons right now is the way it's planned to work. Happy to continue the conversation here or elsewhere, but closing for now.

**Comment by Ambient-Impact** [comment]
Fair enough. I guess I misunderstood how add-ons are intended to work.
