### ISSUE TITLE
ddev config and docs inconsistencies

### ISSUE THREAD

**Issue by jamesmacwhite** [ddev/ddev#5280]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

I've been working on the schema templates for #4511 and noticed some inconsistencies when using the docs as a reference as well as `ddev config global --help` and `ddev config --help`

Doc reference: https://ddev.readthedocs.io/en/latest/users/configuration/config/

I think `simple_formatting` and `table_style` are wrongly using the hyphen casing in the docs when it should be underscore format for the YAML properties, just seems like a typo.

There are a couple of missing properties in the Global config that do not appear documented.

Global:

* `auto_restart_containers` (boolean)
* `project_info` (object)

Project:

* `bind-all-interfaces` (boolean)

### Describe your solution

Update the docs and add any missing properties for schema purposes for consistency and more up to date documentation.

**Comment by jamesmacwhite** [comment]
Turns out I had an older ddev binary which had some old options, so there's less than I originally thought, but there's still a couple I've flagged.

**Comment by rfay** [comment]
It's easier to do a PR than to do an issue, maybe you can just click the pencil in the upper right of the page and fix it. Thanks for pointing it out!

**Comment by jamesmacwhite** [comment]
No worries, I was flagging it first, in case I was wrong on my assessment, but there's just a couple of references that need adding based on what I found. I will do a PR to amend the docs.

**Comment by rfay** [comment]
Looking forward to your PR, thanks @jamesmacwhite

**Comment by jamesmacwhite** [comment]
@rfay Thanks, I'll look to get around to this soon.

**Comment by rfay** [comment]
auto_restart_containers will need to be removed, see https://github.com/ddev/ddev/issues/5282
project_info is private, not something people would ever deal with. It should be in another file of course.

* #5334 will take care of the remaining bind_all_interfaces
