### ISSUE TITLE
Remove `auto_restart_containers: true` as it can't work in DDEV v1.22+

### ISSUE THREAD

**Issue by nd-** [ddev/ddev#5282]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Output of `ddev debug test`

<details><summary>Output</summary>

Running bash [-c /tmp/test_ddev.sh] 
======= Existing project config =========
These config files were loaded for project spip42: [/home/nico/Sites/spip/spip42/.ddev/config.yaml]
name: spip42
type: php
php_version: 8.1
webserver_type: apache-fpm
webimage: ddev/ddev-webserver:20230803_php_serialize_precision
router_http_port: 80
router_https_port: 443
additional_hostnames: []
additional_fqdns: []
database: {mariadb 10.4}
mailhog_port: 8025
mailhog_https_port: 8026
project_tld: test
use_dns_when_possible: true
composer_version: 2
nodejs_version: 16
default_container_timeout: 120
======= Creating dummy project named  tryddevproject-5662 in ../tryddevproject-5662 =========
OS Information: Linux fedora-nico 6.4.9-200.fc38.x86_64 #1 SMP PREEMPT_DYNAMIC Tue Aug  8 21:21:11 UTC 2023 x86_64 GNU/Linux
User information: uid=1000(nico) gid=1000(nico) groupes=1000(nico),10(wheel),975(docker) contexte=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023
DDEV version:  ITEM             VALUE                                                
 DDEV version     v1.22.1                                              
 architecture     amd64                                                
 db               ddev/ddev-dbserver-mariadb-10.4:v1.22.0              
 ddev-ssh-agent   ddev/ddev-ssh-agent:v1.22.0                          
 docker           24.0.5                                               
 docker-compose   v2.20.0                                              
 docker-platform  Fedora Linux 38 (Workstation Edition)                
 mutagen          0.17.2                                               
 os               linux                                                
 router           traefik:v2.10                                        
 web              ddev/ddev-webserver:20230803_php_serialize_precision 
PROXY settings: HTTP_PROXY='' HTTPS_PROXY='' http_proxy='' NO_PROXY=''
======= DDEV global info =========
Global configuration:
instrumentation-opt-in=true
omit-containers=[]
performance-mode=none
router-bind-all-interfaces=false
internet-detection-timeout-ms=3000
disable-http2=false
use-letsencrypt=false
letsencrypt-email=
table-style=default
simple-formatting=false
auto-restart-containers=true
use-hardened-images=false
fail-on-hook-fail=false
required-docker-compose-version=v2.20.0
use-docker-compose-from-path=false
project-tld=test
xdebug-ide-location=
no-bind-mounts=false
router=traefik
wsl2-no-windows-hosts-mgt=false
router-http-port=80
router-https-port=443
traefik-monitor-port=10999

======= DOCKER info =========
docker location: -rwxr-xr-x. 1 root root 29375848 21 juil. 22:38 /usr/bin/docker
docker version: 
Client: Docker Engine - Community
 Version:           24.0.5
 API version:       1.43
 Go version:        go1.20.6
 Git commit:        ced0996
 Built:             Fri Jul 21 20:37:15 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          24.0.5
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.6
  Git commit:       a61e2b4
  Built:            Fri Jul 21 20:35:40 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.22
  GitCommit:        8165feabfdfe38c65b599c4993d227328c231fca
 runc:
  Version:          1.1.8
  GitCommit:        v1.1.8-0-g82f18fe
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
DOCKER_DEFAULT_PLATFORM=notset
======= Mutagen Info =========
======= Docker Info =========
Docker platform: Fedora Linux 38 (Workstation Edition) 
Using docker context: default (unix:///var/run/docker.sock) 
docker-compose: v2.20.0 
Using DOCKER_HOST=unix:///var/run/docker.sock 
Docker version: 24.0.5 
Able to run simple container that mounts a volume. 
Able to use internet inside container. 
Docker disk space:
Filesystem                Size      Used Available Use% Mounted on
/dev/mapper/luks-b498522e-dc39-42d3-8278-3def9c88fb70
                        929.9G    567.1G    362.4G  61% /

 Container ddev-laregion-db  Stopped 
 Container ddev-laregion-db  Removed 
 Container ddev-laregion-web  Stopped 
 Container ddev-laregion-web  Removed 
 Network ddev-laregion_default  Removed 
Project laregion has been stopped. 
 Container ddev-spip42-db  Stopped 
 Container ddev-spip42-db  Removed 
 Container ddev-spip42-web  Stopped 
 Container ddev-spip42-web  Removed 
 Network ddev-spip42_default  Removed 
Project spip42 has been stopped. 
 Container ddev-wiki-db  Stopped 
 Container ddev-wiki-web  Stopped 
 Container ddev-wiki-db  Stopped 
 Container ddev-wiki-web  Stopped 
 Container ddev-wiki-db  Removed 
 Container ddev-wiki-web  Removed 
 Network ddev-wiki_default  Removed 
Project wiki has been stopped. 
The ddev-ssh-agent container has been removed. When you start it again you will have to use 'ddev auth ssh' to provide key authentication again. 
Existing docker containers: 
CONTAINER ID   IMAGE         COMMAND    CREATED         STATUS                     PORTS     NAMES
b2623d6dd3ed   hello-world   "/hello"   10 months ago   Exited (0) 10 months ago             bold_mestorf
595a6fc6ae49   hello-world   "/hello"   10 months ago   Exited (0) 10 months ago             objective_kepler
Network ddev_default created 
Starting tryddevproject-5662... 
 Container ddev-ssh-agent  Created 
 Container ddev-ssh-agent  Started 
ssh-agent container is running: If you want to add authentication to the ssh-agent container, run 'ddev auth ssh' to enable your keys. 
The hostname tryddevproject-5662.test is not currently resolvable, trying to add it to the hosts file 
ddev needs to run with administrative privileges.
You may be required to enter your password for sudo or allow escalation. ddev is about to issue the command:
  sudo --preserve-env=HOME /usr/bin/ddev hostname tryddevproject-5662.test 127.0.0.1
 
[sudo] Mot de passe de nico : 
Not populating custom commands or hostadditions because running with root privileges
 
 Network ddev-tryddevproject-5662_default  Created 
 Container ddev-tryddevproject-5662-web  Created 
 Container ddev-tryddevproject-5662-db  Created 
 Container ddev-tryddevproject-5662-web  Started 
 Container ddev-tryddevproject-5662-db  Started 
 Container ddev-router  Created 
 Container ddev-router  Started 
Successfully started tryddevproject-5662 
Project can be reached at https://tryddevproject-5662.test https://127.0.0.1:32790 
======== Curl of site from inside container:
HTTP/1.1 200 OK
Server: nginx
Date: Sun, 20 Aug 2023 17:48:10 GMT
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
Vary: Accept-Encoding

======== curl -I of http://tryddevproject-5662.ddev.site from outside:
HTTP/1.1 404 Not Found
Content-Type: text/plain; charset=utf-8
X-Content-Type-Options: nosniff
Date: Sun, 20 Aug 2023 17:48:10 GMT
Content-Length: 19

curl: (22) The requested URL returned error: 404
Unable to curl the requested project Please provide this output in a new gist at gist.github.com.

Please run cleanup after debugging with 'ddev debug testcleanup'
Failed running test_ddev.sh: exit status 1
. You can run it manually with `curl -sL -O https://raw.githubusercontent.com/ddev/ddev/master/cmd/ddev/cmd/scripts/test_ddev.sh && bash test_ddev.sh` 

# ddev debug testcleanup

ddev needs to run with administrative privileges.
You may be required to enter your password for sudo or allow escalation. ddev is about to issue the command:
  sudo --preserve-env=HOME /usr/bin/ddev hostname --remove tryddevproject-5662.test 127.0.0.1
 
Volume tryddevproject-5662-mariadb for project tryddevproject-5662 was deleted 
Volume tryddevproject-5662-postgres for project tryddevproject-5662 was deleted 
Volume tryddevproject-5662_project_mutagen for project tryddevproject-5662 was deleted 
Project tryddevproject-5662 was deleted. Your code and configuration are unchanged. 
 Container ddev-tryddevproject-7509-db  Stopped 
 Container ddev-tryddevproject-7509-web  Stopped 
 Container ddev-tryddevproject-7509-db  Stopped 
 Container ddev-tryddevproject-7509-web  Stopped 
 Container ddev-tryddevproject-7509-db  Removed 
 Container ddev-tryddevproject-7509-web  Removed 
 Network ddev-tryddevproject-7509_default  Removed 
ddev needs to run with administrative privileges.
You may be required to enter your password for sudo or allow escalation. ddev is about to issue the command:
  sudo --preserve-env=HOME /usr/bin/ddev hostname --remove tryddevproject-7509.test 127.0.0.1
 
Volume tryddevproject-7509-mariadb for project tryddevproject-7509 was deleted 
Volume tryddevproject-7509-postgres for project tryddevproject-7509 was deleted 
Volume tryddevproject-7509_project_mutagen for project tryddevproject-7509 was deleted 
Project tryddevproject-7509 was deleted. Your code and configuration are unchanged. 
Finished cleaning ddev diagnostic projects 
</details>

### Expected Behavior

I adde the option `auto_restart_containers: true` in `global_config.yaml` and everything was working as expected.
On reboot, my active ddev projets where up and running again.

### Actual Behavior

After update to 1.22.1, my projets are'nt fully running, their status in `ddev list` is "db: running"
I have to restart them.

### Anything else?

After a discussion on Discord with @rfay I open an issue here.

Link to the post and answers from @rfay : https://discord.com/channels/664580571770388500/1142863431603605506

> But the problem is the restart: "always" in the .ddev/.ddev-docker-compose-base.yaml
> Ah, I see the problem.  In the latest ddev actual intervention from DDEV is required to finish the startup process. 
> 
> So if you docker ps  with this setting, you'll see that the containers started again after you rebooted (or restarted docker, much easier to test just restarting docker)
> BUT, ddev has to explicitly run the start.sh as it does with ddev start or things don't ever get ready. That's why you don't see as much as you expect on `ddev logs
> Your other containers are working fine, but ddev-webserver is waiting for instructions.

**Comment by rfay** [comment]
We should probably either make `auto_restart_containers` work or remove it. It's always been of questionable value or reliability.

**Comment by wimleers** [comment]
I recently updated my local `ddev` from the ancient https://github.com/ddev/ddev/releases/tag/v1.22.1 to the current latest: https://github.com/ddev/ddev/releases/tag/v1.23.4.

This commit (d5091e0) appears to have first shipped with https://github.com/ddev/ddev/releases/tag/v1.22.4. 

For _years_ this has worked absolutely fine for me 😬 Power interruptions or even just reboots for installing OS updates … none of it mattered: my website booted up just fine (CDN:80 → modem ISP:4444 → port forwarding → DDEV-managed Docker).

That's now no longer the case. Do I really need to resort to a kludge like
```
@reboot ddev --alll
```
in my `crontab`? 🙈

**Comment by rfay** [comment]
I don't recommend doing things like that in crontab, but in your .profile or related you could do something like

```
ddev list --active-only | grep "No DDEV" && ddev start -a
```

if you like that behavior.

**Comment by nd-** [comment]
I use this command (it may need to install jq) : 

```
for f in $(ddev list -A -j | jq '.raw' | jq '.[] | .name'); do ddev restart $(echo $f | sed 's/"//g'); done;
```
