### ISSUE TITLE
docs: codespaces - use bash script for postCreateCommand in tutorial?

### ISSUE THREAD

**Issue by mandrasch** [ddev/ddev#5288]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

The current tutorial uses a one liner for the `postCreateCommand` (https://ddev.readthedocs.io/en/latest/users/install/ddev-installation/#github-codespaces):

```
"postCreateCommand": "bash -c 'ddev config global --omit-containers=ddev-router && ddev config --auto && ddev debug download-images'"
```

My current experience is that
- a) `ddev config --auto` is not necessary when projects are already configured
- b) an external script is used by many people since you can add more commands there
- c) `ddev poweroff` is necessary for rebuilds, because codespaces keeps some docker containers, see https://github.com/ddev/ddev/issues/5071#issuecomment-1620570680

### Describe your solution

Solution which I use currently (e.g. https://github.com/mandrasch/ddev-craftcms-vite):

 ```
 "postCreateCommand": "chmod +x .devcontainer/setup_project.sh && .devcontainer/setup_project.sh"
```

```
#!/bin/bash
set -ex
ddev config global --omit-containers=ddev-router
ddev debug download-images

# catch rebuilds
ddev poweroff

# start ddev project
ddev start -y

# normal project setup
ddev composer install 
```

### Additional context

I'm happy to provide a PR as well, did not want to complicate things in the other, previous PRs.

**Comment by rfay** [comment]
I don't object to this approach; 

Note that `ddev config --omit-containers=ddev-router` should be irrelevant, as DDEV turns off the router when Codespaces or Gitpod is detected.

**Comment by mandrasch** [comment]
> I don't object to this approach;
> 
> Note that `ddev config --omit-containers=ddev-router` should be irrelevant, as DDEV turns off the router when Codespaces or Gitpod is detected.

Thanks, good information!

I created a new PR draft here quickly: https://github.com/ddev/ddev/pull/5290

**Comment by rfay** [comment]
Closing this in favor of tracking your excellent work in 
* #5290 

Thanks for caring for codespaces usage and users!
