### ISSUE TITLE
Installation instructions say to Initialize mkcert but it's missing certutil

### ISSUE THREAD

**Issue by joachim-n** [ddev/ddev#5316]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Output of `ddev debug test`

The docs at https://ddev.readthedocs.io/en/latest/users/install/ddev-installation/ say to do `mkcert -install`.

However, this complains about certutil.

### Expected Behavior

It runs without errors.

### Actual Behavior

```
 mkcert -install
Created a new local CA 💥
Sudo password:
The local CA is now installed in the system trust store! ⚡️
Warning: "certutil" is not available, so the CA can't be automatically installed in Firefox! ⚠️
Install "certutil" with "brew install nss" and re-run "mkcert -install" 👈
```

**Comment by rfay** [comment]
Hmm, most people don't use homebrew any more for installing on linux. If you use the apt installer nss-utils is in fact included:

https://github.com/ddev/ddev/blob/66471cf2645111a9704282465ef80cd597e92b60/.goreleaser.yml#L265-L274

**Comment by joachim-n** [comment]
I was following the instructions here which said to use homebrew: https://ddev.readthedocs.io/en/latest/users/install/docker-installation/

**Comment by rfay** [comment]
You're reading the mac instructions. Please take a look at the linux instructions, https://ddev.readthedocs.io/en/latest/users/install/docker-installation/#linux

(However, homebrew does work on Linux amd64)

**Comment by rfay** [comment]
OK, well it tells you exactly what to do, correct? 

```
Warning: "certutil" is not available, so the CA can't be automatically installed in Firefox! ⚠️
Install "certutil" with "brew install nss" and re-run "mkcert -install" 👈
```

**Comment by joachim-n** [comment]
It does, but it would be nice if the docs included `brew install nss` as a step (or a dependency of the ddev homebrew package?), rather than have the user hit a stumbling block.

**Comment by rfay** [comment]
`mkcert` works fine after a brew install.  It just doesn't support Firefox without nss.

**Comment by rfay** [comment]
AFAICT this is good enough, but docs PR is welcome. Closing, happy to continue the conversation.
