### ISSUE TITLE
'unable to create project at project root' error message should say how to fix the problem

### ISSUE THREAD

**Issue by joachim-n** [ddev/ddev#5322]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Output of `ddev debug test`

<details><summary>Expand `ddev debug test` diagnostic information</summary>

```
[COPY-PASTE HERE THE OUTPUT OF `ddev debug test`]
```
</details>         

### Expected Behavior

I did `ddev list` and there is a warning:

> unable to create project at project root '/Users/joachim/Sites/pants': project root /Users/joachim/Sites/pants does not exist

I googled for how to delete a project and at https://ddev.readthedocs.io/en/latest/users/usage/uninstall/ it says to do `[ddev delete <project>](https://ddev.readthedocs.io/en/latest/users/usage/commands/#delete)`. But I assume that's a project name - I don't know what that is.

There's a mention of this case at #2314.

But the error message should give the user next steps to fix the problem.

### Actual Behavior

Error message that the user can't act on.

**Comment by rfay** [comment]
Yes, `ddev delete --omit-snapshot <projectname> should delete your project just fine.

If not, just remove its line from ~/.ddev/global_config.yaml.

This typically comes from removing the files/directory from an exiting project.

A PR would be welcome if you think you know how to phrase that better. Remember that there are more ways than one to be in this situation, but this is the most common.

**Comment by tmotyl** [comment]
The error message "unable to create project at project root" could mention what command to run to remove the proejct.
Like:
```
If you want to remove the project, run:
ddev delete --omit-snapshot <project-name>
```
