### ISSUE TITLE
How to configure custom ddev-webserver

### ISSUE THREAD

**Issue by MakerTim** [ddev/ddev#5325]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

For development we want an environment where we are as close as possible to production.
On production we base our images on the distro alpine, but ddev uses debian.

Things where we currently are unable to test are things like imagemagic; where there is a difference in support for adobe-based images with results where we cannot debug locally.
And have to manage the correct libraries, where we run into problems where ddev has an extension we don't include into production or via versa. Then you could manage those with hooks, scripts etc. but then we are working against ourself.

### Describe your solution

I would love to have a types for alpine, debian etc.; but that would be a nightmare to support.

So realistically a `custom` or `compose` type where we then define our own image name would be ideal.

```yml
type: custom
webbuild:
    image: ...
    args:
        PHP_VERSION: "8.1"
        ...
    ...
```
And as support, we only document what ddev requires, with things like these ports are listening

### Describe alternatives

Don't know how impossible this is, and it may be a ddev v2.x feature or never be added.
But this limitation is currently stopping a few flows where there is no workaround for as in right now.

### Additional context

https://stackshare.io/stackups/alpine-linux-vs-debian
https://www.imagemagick.org/discourse-server/search.php?keywords=alpine

**Comment by stasadev** [comment]
I think there is already a setting for this:

```
ddev config --web-image <image>
```

Docs: https://ddev.readthedocs.io/en/stable/users/configuration/config/#webimage

However, the documentation suggests that the image be based on `ddev/ddev-webserver`, but if you can build the same [functionality](https://github.com/ddev/ddev/tree/master/containers/ddev-webserver) that is required by DDEV on alpine, then it is theoretically possible.

**Comment by rfay** [comment]
You can in fact change the web image, but if you need custom functionality it's SO much easier to just create a Dockerfile to add functionality.  Please see https://ddev.readthedocs.io/en/latest/users/extend/customizing-images/#adding-extra-dockerfiles-for-webimage-and-dbimage

Also please note that the php_version is completely customizable already in .ddev/config.yaml. Along with webserver type and so many other things. 

Maybe you can say what you're trying to accomplish... it's possible that it's all done and easy already.

**Comment by rfay** [comment]
The answer here is:
1. use .ddev/web-build/Dockerfile
2. Use the `web_image` in .ddev/config.yaml if you're so ambitious as to want to build another image that meets all the requirements of DDEV.

Happy to continue the conversation here or elsewhere. Closing this for now.
