### ISSUE TITLE
Upgrade ImageMagick to ImageMagick 7

### ISSUE THREAD

**Issue by WalterPrech** [ddev/ddev#5332]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

We use ddev for developing our drupal project. We use the image format AVIF and need ImageMagick 7 to convert JPG images to AVIF.

### Describe your solution

Possibility in config.yml to choose the ImageMagick version which should be installed.

**Comment by rfay** [comment]
AVIF (at least with GD) has been a problem with Debian Bullseye and the deb.sury.org packages we use, see 
* https://github.com/ddev/ddev/issues/4292

We're hoping for better when we can move ddev-webserver to be based on Bookworm, see
* https://github.com/ddev/ddev/pull/5278

Unfortunately, I just brought up DDEV with the Bookworm PR, and it doesn't look like you'll get to Imagick 7 with that:

<img width="1003" alt="image" src="https://github.com/ddev/ddev/assets/112444/f97e59e4-a6ce-44ed-be3b-2a351199c386">

So I'm pretty sure this can only be handled by you figuring out how to build php-8.x-imagiick yourself. I'm pretty sure this would be https://pear.php.net/manual/en/pyrus.commands.build.php - and can be done in a .ddev/web-build/Dockerfile, but I don't think you're going to have DDEV do this for you any time soon.

**Comment by rfay** [comment]
If you don't need php8.x-imagick, there are likely ways to get the imagick library or utility on there of the version you want.

**Comment by WalterPrech** [comment]
I installed ImageMagick 7 with the imei.sh script from https://github.com/SoftCreatR/imei.

But I have to uninstall first ImageMagick 6.

If it's not possible to install ImageMagick 7 with an option in the config file, then it should be possible to set an option in the config file to not install ImageMagick.

Then in the docker file the installation of ImageMagick 7 could be automated. E.g. with

```
ENV IMAGEMAGICK_DIR=/usr/local/imagemagick7
RUN mkdir -p $IMAGEMAGICK_DIR
RUN git clone https://github.com/SoftCreatR/imei $IMAGEMAGICK_DIR
RUN bash $IMAGEMAGICK_DIR/imei.sh
```

**Comment by rfay** [comment]
You can just add a 
`RUN apt remove imagemagic`

**Comment by rfay** [comment]
We won't be upgrading to Imagick 7 any time soon because of the dependencies involved, but please do post your technique here when you get it working. 

Closing for now, happy to continue the conversation here or elsewhere.

**Comment by WalterPrech** [comment]
Tested the suggested code for the Dockerfile, but it don't work for me. After some try, I was successful with this settings:
```
RUN apt update
RUN apt remove "*imagemagick*" --purge -y && apt autoremove --purge -y
RUN apt install -y php-pear php8.3-dev libaom-dev aom-tools cmake build-essential libltdl-dev libjpeg-dev libpng-dev libtiff-dev libgif-dev libfreetype6-dev liblcms2-dev libxml2-dev

ENV IMAGEMAGICK_DIR=/usr/local/imagemagick7
RUN mkdir -p $IMAGEMAGICK_DIR

RUN git clone https://github.com/SoftCreatR/imei $IMAGEMAGICK_DIR
RUN chmod +x $IMAGEMAGICK_DIR/imei.sh
RUN bash $IMAGEMAGICK_DIR/imei.sh
```

**Comment by mr-joery** [comment]
For me I needed to do two things in order to have ImageMagick 7 on ddev.

First, as mentionned above: Edit `.ddev/web-build/Dockerfile` and add this:
```
# Use ImageMagick 7 instead of 6
# See: https://github.com/ddev/ddev/issues/5332
RUN apt update
RUN apt remove "*imagemagick*" --purge -y && apt autoremove --purge -y
RUN apt install -y php-pear php8.3-dev libaom-dev aom-tools cmake build-essential libltdl-dev libjpeg-dev libpng-dev libtiff-dev libgif-dev libfreetype6-dev liblcms2-dev libxml2-dev

ENV IMAGEMAGICK_DIR=/usr/local/imagemagick7
RUN mkdir -p $IMAGEMAGICK_DIR

RUN git clone https://github.com/SoftCreatR/imei $IMAGEMAGICK_DIR
RUN chmod +x $IMAGEMAGICK_DIR/imei.sh
RUN bash $IMAGEMAGICK_DIR/imei.sh

# install the Imagick PHP Extension
RUN apt-get update \
    && pecl install imagick
```

Second, and this was missing for me in these comments: edit or create `.ddev/php/php.ini` and add this:
`extension = imagick.so`
In the PHP section, So your php.ini file might look like this:
```
[PHP]
memory_limit = 4G;
max_execution_time = 240;
extension = imagick.so
```

**Comment by tormi** [comment]
We have the similar situation in some of our Drupal projects - `v7` in `production` and `v6` in DDEV. Fortunately we can define `imagemagick_version` in config and we're doing just that with the help of `config_split`.

**Comment by rfay** [comment]
In DDEV v1.25.0, which will use Debian Trixie as base, we'll have imagemagick v8 by default :) That should be along within the next couple of months.

**Comment by tormi** [comment]
Then we still need to use `config_split` which is ok by us. Thanks, Randy for your quick response!

**Comment by thejimbirch** [comment]
@asipple1 Figured this one out for Drupal settings.php.  You could also if DDEV.

```
if ($_ENV['PANTHEON_ENVIRONMENT']) {
  // Use ImageMagick v7 on Pantheon.
  $config['imagemagick.settings']['imagemagick_version'] = 'v7';
}
```
