### ISSUE TITLE
`ddev get --remove` uses current directory as base for `removal_actions`, should use .ddev

### ISSUE THREAD

**Issue by rfay** [ddev/ddev#5342]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Output of `ddev debug test`

<details><summary>Expand `ddev debug test` diagnostic information</summary>

```
[COPY-PASTE HERE THE OUTPUT OF `ddev debug test`]
```
</details>         

### Expected Behavior

`removal_actions` should act in a predictable directory, which is normally assumed to be the project .ddev

### Actual Behavior

It actually acts in the current directory where `ddev get --remove` was executed, so may not successfully do a number of things.

### Steps To Reproduce

Use this in install.yaml
```
removal_actions:
  - echo "pwd=$PWD"
```

Then `cd .ddev/web-build`
`ddev get --remove <addon>` will show it not being in expected directory

**Comment by rfay** [comment]
`ddev get --remove` also inappropriately creates a .ddev directory in the current directory.

**Comment by stasadev** [comment]
>`ddev get --remove` also inappropriately creates a `.ddev` directory in the current directory.
>
>Also `ddev get --list` inappropriately creates a `.ddev` dir

How to test this behavior?

When I try to run these commands in `.ddev/web-build`, the dir `.ddev/web-build/.ddev` is not created.
Am I missing something?

**Comment by rfay** [comment]
```
rfay@rfay-tag1-m1:~/tmp$ rm -rf .ddev
rfay@rfay-tag1-m1:~/tmp$ ddev get --list >/dev/null
rfay@rfay-tag1-m1:~/tmp$ ls -l .ddev/
total 0
drwxr-xr-x  2 rfay  staff  64 Oct  4 22:33 addon-metadata
```


```
rfay@rfay-tag1-m1:~/workspace/d10/web$ rm -rf .ddev
rfay@rfay-tag1-m1:~/workspace/d10/web$ ddev get --remove adminer
Removed add-on adminer
rfay@rfay-tag1-m1:~/workspace/d10/web$ ls -l .ddev/
total 0
drwxr-xr-x  2 rfay  staff  64 Oct  4 22:35 addon-metadata
```

**Comment by stasadev** [comment]
Thank you for the details!

Unfortunately I cannot reproduce it yet.

```
# outside of any ddev project
~/tmp$ ls -la
total 12
drwxr-xr-x  3 stas stas 4096 Oct  4 20:47 .
drwx------ 49 stas stas 4096 Oct  5 18:51 ..
drwxr-xr-x  2 stas stas 4096 Oct  4 21:21 ddevtest

~/tmp$ ddev get --list >/dev/null

~/tmp$ ls -l .ddev/
ls: cannot access '.ddev/': No such file or directory

~/tmp$ ls -la
total 12
drwxr-xr-x  3 stas stas 4096 Oct  4 20:47 .
drwx------ 49 stas stas 4096 Oct  5 18:52 ..
drwxr-xr-x  2 stas stas 4096 Oct  4 21:21 ddevtest
```

```
# inside a ddev project
~/code/ddev/ddev-get-project$ mkdir web && cd web

~/code/ddev/ddev-get-project/web$ ddev get ddev/ddev-adminer >/dev/null && ddev get --remove ddev/ddev-adminer
Removed add-on ddev/ddev-adminer

~/code/ddev/ddev-get-project/web$ ls -l .ddev/
ls: cannot access '.ddev/': No such file or directory

~/code/ddev/ddev-get-project/web$ ls -la
drwxr-xr-x 2 stas stas 4096 Oct  5 19:01 .
drwxr-xr-x 6 stas stas 4096 Oct  5 19:01 ..
```

I am wondering if this is macOS problem or some specific DDEV version?

I tested it on Linux with the two versions.

```
$ ddev --version
ddev version v1.22.3-18-gd0af978b1 # latest

$ ddev --version
ddev version v1.22.3 # stable
```

**Comment by rfay** [comment]
Pretty weird! I guess it could be something arm64 related or mac related, but since it is so easy for me to replicate I expected it to happen easily to you.

**Comment by rfay** [comment]
Regardless, it wouldn't surprise me if you the eagle-eyed could spot the flaw just by reading the code.

**Comment by rfay** [comment]
I cannot reproduce on gitpod (amd64 linux)

**Comment by stasadev** [comment]
And I don't understand where `.ddev/addon-metadata` can come from in `ddev get --list`.

There is no place where it can be created.

**Comment by stasadev** [comment]
I'm going to open a PR for the issue in the title.

Because we are probably discussing something else.

**Comment by rfay** [comment]
Tried it on amd64 and arm64 macOS test runners and couldn't recreate there either. Tried on linux arm64, couldn't do it there. So maybe it's just my machine?

**Comment by stasadev** [comment]
>So maybe it's just my machine?

Maybe something with the user environment.

You can create a new user on your machine and try to recreate it there.

**Comment by rfay** [comment]
The main part was fixed by 
* https://github.com/ddev/ddev/pull/5402

Now to figure out the rest, https://github.com/ddev/ddev/issues/5342#issuecomment-1730304216

**Comment by rfay** [comment]
There's more than one way this can happen.

Opened
* https://github.com/ddev/ddev/issues/5419

Closing this one, thanks for fixing the original issue here.
