### ISSUE TITLE
ddev debug test should restart the sites it stopped

### ISSUE THREAD

**Issue by joachim-n** [ddev/ddev#5345]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Output of `ddev debug test`

<details><summary>Expand `ddev debug test` diagnostic information</summary>

```
[COPY-PASTE HERE THE OUTPUT OF `ddev debug test`]
```
</details>         

### Expected Behavior

Filing a bug report asks me to run 'ddev debug test'.
Doing that stops all my running sites.
It should restore them when it's done, as otherwise it's a pain to have to go round restarting everything.

### Actual Behavior

My sites get stopped.

**Comment by rfay** [comment]
Hi @joachim-n - I think it would be possible to do this:
1. Check running projects before running the scripts
2. Run the script
3. Restart the projects captured previously. 


This is all in https://github.com/ddev/ddev/blob/master/cmd/ddev/cmd/debug-test.go

Are you interested in taking a shot at it? I'm happy to help.

**Comment by nd-** [comment]
I was going to open a similar issue about updating ddev.
After doing a poweroff and then the update, it would be handy to restart the sites that were activated before.

I usually do `ddev list -A` before the update, so that I can restart them manually afterwards.

**Comment by rfay** [comment]
In general I'm always happy to have `poweroff` shut down the too-many sites I've started, so I can start too many again as I need them.

**Comment by nd-** [comment]
For a simple `poweroff`, you're right, of course. We need a way to shut down everything.

I was talking about the update process of ddev.
When a new version has been installed via a system upgrade (apt-get, dnf or whatever) and you want to start or restart a site, it begins with a `poweroff` first, then updates the docker images etc.
It would be handy to restart the sites that were activated before the update at the end of the process.

**Comment by rfay** [comment]
Basically you need an `unpoweroff` that knows about the state of projects before they were powered off. That's true for all these requests.

However, DDEV doesn't keep state, except project state. I don't think it would be easy to know how to undo a poweroff. How would it know which projects were recently stopped?

It's possible that `ddev debug test` could do it, because it lives through the whole process, and a contribution would be welcome for any of these, but I don't see this happening unless somebody gets ambitious and wants to make a contribution. 

Closing for now, happy to continue the conversation here or elsewhere.

**Comment by rfay** [comment]
Yes, `ddev debug test` could do this, but poweroff alone not very easily. But `ddev debug test` could just grab an array of running projects before starting the test_ddev.sh.

**Comment by nd-** [comment]
Maybe a parameter to add to `poweroff` (something like `--restart`) that the update procedure could use ?

**Comment by rfay** [comment]
I guess it's true that poweroff can easily check what's running and restore that list after it's finished. Not a bad idea.

**Comment by rfay** [comment]
But mostly people use poweroff to stop, not to "restart a bunch"

**Comment by rfay** [comment]
I'm not at all sure that restarting projects after `ddev debug test` would fix any of the problems that @joachim-n mentioned, since stopping projects during a migration or whatever is disruptive.

However:
* https://github.com/ddev/ddev/issues/5376

Is simple and important.

**Comment by nd-** [comment]
> But mostly people use poweroff to stop, not to "restart a bunch"

Yes, absolutely, it should be the default case. 
But we could have something like `ddev poweroff --restart` that would restart active projects, only when explicitely asked.
And the update procedure (as well as `ddev debug` maybe ?) could use this parameter to poweroff AND restart.

**Comment by rfay** [comment]
`ddev debug test` could do its own tracking, because it has business to do before starting projects up again.
