### ISSUE TITLE
WSL `autoMemoryReclaim` setting can break docker in WSL

### ISSUE THREAD

**Issue by tyler36** [ddev/ddev#5356]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected Behavior

MS recently released a preview version of WSL 2. 

One new feature is **automatic memory reclaim** which aims to reduce memory usage, however as reported [here](https://devblogs.microsoft.com/commandline/windows-subsystem-for-linux-september-2023-update/)

> In early testing we noticed that this will break the docker daemon when running it as a service in WSL, and so if you’re using this feature we recommend you use Docker Desktop for your docker needs. We are working with the Docker team to address this in the future.

Currently, DDEV recommends installing docker inside WSL so this has the potential to break things.

### Actual Behavior

Potential WSL docker daemon breaks.

### Anything else?

This issue was created to track this "potential" issue. Hopefully the problem will be resolved in the final release.

Blog: [Windows Subsystem for Linux September 2023 update](https://devblogs.microsoft.com/commandline/windows-subsystem-for-linux-september-2023-update/)

**Comment by rfay** [comment]
Sad. I was hoping to put this on the WSL2 test runners, which crash periodically, possibly due to memory exhaustion. Thanks for letting us know.

Although they waited a long, long time for this release, the issues I'm following don't show a lot of happy people in them.

**Comment by rfay** [comment]
What kind of breakage do you see? Does it destroy data?

**Comment by tyler36** [comment]
I haven't tried the preview version yet. There have been lots of issues with recent releases so I'll be waiting.

I was reading the article and it raised flags.

**Comment by rfay** [comment]
If you haven't tried it yet, why do you think this issue is important? Please give it a try!

**Comment by djpirra** [comment]
I have latest version of wsl2 and docker desktop and when I configure .wslconfig with the autoMemoryReclaim I get an error and WSL cannot start....

`Unknown key 'experimental.autoMemoryReclaim' in C:\Users\xxxxx\.wslconfig`

Anyone knows what is the issue?

**Comment by rfay** [comment]
@djpirra You don't have wsl 2.0.0. You have to `wsl --update --pre-release` to get it.

**Comment by tyler36** [comment]
Closing.

I've been running WSL 2.0.0 for a couple of days without issue. However, I don't use Docker in WSL so I am unlikely to come across the issue described in the blog.

**Comment by rfay** [comment]
Ah, you use Docker Desktop? 

Thanks for paying attention to these things! We'll see how it works out.

**Comment by rfay** [comment]
If you use Docker Desktop (which is completely dependent on WSL) I'd think you'd be affected just the same as if you use docker-ce.

**Comment by tyler36** [comment]
The original post implied Docker Desktop was recommended over docker in WSL. 
The memory reclaim functions are probably a little aggressive or only target WSL services.

**Comment by rfay** [comment]
Docker Desktop relies extensively on WSL services. It's completely implemented with them. I may not understand your point.

**Comment by rfay** [comment]
My hopes are dashed. I haven't set any of the new options, but the two test runners I installed 2.0.0 on, tb-wsl-12 and tb-wsl-13, just WSL-crashed as they typically do from time to time. So the defaults aren't helping us.

**Comment by rfay** [comment]
Related fix:
* https://github.com/microsoft/WSL/issues/10497

**Comment by tyler36** [comment]
Thanks for the follow-up.

**Comment by rfay** [comment]
Are you still using autoMemoryReclaim @tyler36 ?

**Comment by tyler36** [comment]
@rfay No. Not in my config which I refreshed around 2024.04 release.

**Comment by rfay** [comment]
I just introduced that in our Docker Desktop runners, which usually crash every day, apparently from memory overuse (even with 16GB of memory). We can hope that it will stabilize them. We've been rebooting them every time significant testing happens for a really long time.

**Comment by tyler36** [comment]
I'll put it in my config and see how it goes.
