### ISSUE TITLE
Include swagger-ui addon official

### ISSUE THREAD

**Issue by reloxx13** [ddev/ddev#5359]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

No

### Describe your solution

Created the addon here: https://github.com/reloxx13/ddev-swagger-ui

**Comment by rfay** [comment]
ddev-swagger-ui will need quite a lot more time incubating before it can be official. It needs people to use it. I'll try to do a little review of it to give you some direction.

The first thing I see is... It's not maintained by me, so change the bottom of the readme :)

Closing this for now, just come back after some time. I think this will likely do fine as your add-on for now.
