### ISSUE TITLE
Drupal10 'drupal10' is not a valid project type.

### ISSUE THREAD

**Issue by smethew** [ddev/ddev#5362]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Output of `ddev debug test`

<details><summary>Expand `ddev debug test` diagnostic information</summary>

```
[COPY-PASTE HERE THE OUTPUT OF `ddev debug test`]
```
</details>         

### Expected Behavior

I would like have Drupal 10 project run on this project.

### Actual Behavior

Project Type [backdrop, drupal6, drupal7, drupal8, drupal9, laravel, magento, magento2, php, shopware6, typo3, wordpress] (php): drupal10
'drupal10' is not a valid project type. Allowed project types are: backdrop, drupal6, drupal7, drupal8, drupal9, laravel, magento, magento2, php, shopware6, typo3, wordpress

Project Type [backdrop, drupal6, drupal7, drupal8, drupal9, laravel, magento, magento2, php, shopware6, typo3, wordpress] (php):

### Steps To Reproduce

1. Running on Windows 11 Docker and WSL V2 
2. mkdir my-drupal10-site
cd my-drupal10-site
ddev config --project-type=drupal10 --docroot=web --create-docroot
3. Creating a new ddev project config in the current directory (/home/saman/orip10)
Once completed, your configuration will be written to /home/saman/orip10/.ddev/config.yaml
apptype must be one of backdrop, drupal6, drupal7, drupal8, drupal9, laravel, magento, magento2, php, shopware6, typo3, wordpress
4 ddev start
Failed to get project(s): could not find a project in /home/saman/orip10. Have you run 'ddev config'? Please specify a project name or change directories: no .ddev/config.yaml file was found in this directory or any parent
5. $ ddev stop
Failed to get project(s): could not find a project in /home/saman/orip10. Have you run 'ddev config'? Please specify a project name or change directories: no .ddev/config.yaml file was found in this directory or any parent

-----------------------------------------
I try to many time but is not working out as I need to do. Any help please provide. 

Thank you,

### Anything else?

FYI: I can run Drupal 7,8 and 9 but can't create the Drupal 10 project.

**Comment by rfay** [comment]
Hi @smethew - Could you please use a recent version of DDEV? `drupal10` has been a valid type for about a year. You didn't provide the output of `ddev debug test` as requested, but ... Please upgrade :)

**Comment by smethew** [comment]
Hi @rfay , Here please see below:
$ ddev version
 ITEM            VALUE
 DDEV version    v1.18.2
 architecture    amd64
 db              drud/ddev-dbserver-mariadb-10.3:v1.18.2
 dba             phpmyadmin:5
 ddev-ssh-agent  drud/ddev-ssh-agent:v1.18.0
 docker          24.0.6
 docker-compose  v2.2.2
 mutagen         0.12.0
 os              linux
 router          drud/ddev-router:v1.18.2
 web             drud/ddev-webserver:v1.18.2
------------------------------------------------------------------
How I update DDEV to recent version?
------------------------------------------------------------------
$ ddev debug test
Usage:
  ddev debug [command] [flags]
  ddev debug [command]

Available Commands:
  compose-config      Prints the docker-compose configuration of the current project
  configyaml          Prints the project config.*.yaml usage
  download-images     Download all images required by ddev
  mutagen             Allows access to any mutagen command
  nfsmount            Checks to see if nfs mounting works for current project
  router-nginx-config Prints the nginx config of the router

Flags:
  -h, --help   help for debug

Global Flags:
  -j, --json-output   If true, user-oriented output will be in JSON format.

Use "ddev debug [command] --help" for more information about a command.

-------------------------------------------------------------
Thank you, @rfay

**Comment by rfay** [comment]
That version is quite old. Please upgrade to current DDEV v1.22.3 if you want drupal10 as a project type :)

Your old version doesn't even have `ddev debug test` :)

https://github.com/ddev/ddev/releases

Closing, happy to continue the conversation.

**Comment by smethew** [comment]
Hi @rfay,

I'm tried to do upgrade DDEV but no luck yet. Here what I go the issue
------------------------------------
$ sudo apt update && sudo apt install -y ddev
Hit:1 http://security.ubuntu.com/ubuntu focal-security InRelease
Hit:2 http://archive.ubuntu.com/ubuntu focal InRelease
Get:3 http://archive.ubuntu.com/ubuntu focal-updates InRelease [114 kB]
Hit:4 http://archive.ubuntu.com/ubuntu focal-backports InRelease
Get:5 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 Packages [2851 kB]
Get:6 http://archive.ubuntu.com/ubuntu focal-updates/main Translation-en [468 kB]
Err:7 https://dl.yarnpkg.com/debian stable InRelease
  Cannot initiate the connection to dl.yarnpkg.com:443 (2606:4700::6812:7e64). - connect (101: Network is unreachable) Cannot initiate the connection to dl.yarnpkg.com:443 (2606:4700::6810:ab63). - connect (101: Network is unreachable) Could not connect to dl.yarnpkg.com:443 (104.18.126.100), connection timed out Could not connect to dl.yarnpkg.com:443 (104.16.171.99), connection timed out
Err:8 https://deb.nodesource.com/node_14.x focal InRelease
  Cannot initiate the connection to deb.nodesource.com:443 (2606:4700:10::6816:41a). - connect (101: Network is unreachable) Cannot initiate the connection to deb.nodesource.com:443 (2606:4700:10::6816:51a). - connect (101: Network is unreachable) Cannot initiate the connection to deb.nodesource.com:443 (2606:4700:10::ac43:acd). - connect (101: Network is unreachable) Could not connect to deb.nodesource.com:443 (104.22.4.26), connection timed out Could not connect to deb.nodesource.com:443 (104.22.5.26), connection timed out Could not connect to deb.nodesource.com:443 (172.67.10.205), connection timed out
Err:9 https://pkg.ddev.com/apt * InRelease
  Cannot initiate the connection to pkg.ddev.com:443 (2406:da00:ff00::22e8:deaa). - connect (101: Network is unreachable) Cannot initiate the connection to pkg.ddev.com:443 (2406:da00:ff00::3698:9907). - connect (101: Network is unreachable) Cannot initiate the connection to pkg.ddev.com:443 (2406:da00:ff00::23ae:647f). - connect (101: Network is unreachable) Could not connect to pkg.ddev.com:443 (34.232.222.170), connection timed out Could not connect to pkg.ddev.com:443 (35.174.100.127), connection timed out Could not connect to pkg.ddev.com:443 (54.152.153.7), connection timed out
Fetched 3433 kB in 31s (111 kB/s)
Reading package lists... Done
Building dependency tree
Reading state information... Done
325 packages can be upgraded. Run 'apt list --upgradable' to see them.
W: Failed to fetch https://pkg.ddev.com/apt/dists/*/InRelease  Cannot initiate the connection to pkg.ddev.com:443 (2406:da00:ff00::22e8:deaa). - connect (101: Network is unreachable) Cannot initiate the connection to pkg.ddev.com:443 (2406:da00:ff00::3698:9907). - connect (101: Network is unreachable) Cannot initiate the connection to pkg.ddev.com:443 (2406:da00:ff00::23ae:647f). - connect (101: Network is unreachable) Could not connect to pkg.ddev.com:443 (34.232.222.170), connection timed out Could not connect to pkg.ddev.com:443 (35.174.100.127), connection timed out Could not connect to pkg.ddev.com:443 (54.152.153.7), connection timed out
W: Failed to fetch https://deb.nodesource.com/node_14.x/dists/focal/InRelease  Cannot initiate the connection to deb.nodesource.com:443 (2606:4700:10::6816:41a). - connect (101: Network is unreachable) Cannot initiate the connection to deb.nodesource.com:443 (2606:4700:10::6816:51a). - connect (101: Network is unreachable) Cannot initiate the connection to deb.nodesource.com:443 (2606:4700:10::ac43:acd). - connect (101: Network is unreachable) Could not connect to deb.nodesource.com:443 (104.22.4.26), connection timed out Could not connect to deb.nodesource.com:443 (104.22.5.26), connection timed out Could not connect to deb.nodesource.com:443 (172.67.10.205), connection timed out
W: Failed to fetch https://dl.yarnpkg.com/debian/dists/stable/InRelease  Cannot initiate the connection to dl.yarnpkg.com:443 (2606:4700::6812:7e64). - connect (101: Network is unreachable) Cannot initiate the connection to dl.yarnpkg.com:443 (2606:4700::6810:ab63). - connect (101: Network is unreachable) Could not connect to dl.yarnpkg.com:443 (104.18.126.100), connection timed out Could not connect to dl.yarnpkg.com:443 (104.16.171.99), connection timed out
W: Some index files failed to download. They have been ignored, or old ones used instead.
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package ddev

May I know how to fix it? Thanks!

**Comment by rfay** [comment]
Your system is broken and you have no internet. Please fix it. When `sudo apt update` works without errors, we can talk. This isn't the place for you to get support for learning how to use your linux system.
