### ISSUE TITLE
Windows WSL2/Docker Desktop Manual Install Missing Command

### ISSUE THREAD

**Issue by timnolte** [ddev/ddev#5364]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Output of `ddev debug test`

The issue is found here: https://github.com/ddev/ddev/blob/master/docs/content/users/install/ddev-installation.md?plain=1#L250

The Linux instruction indicate calling `sudo install -m 0755 -d /etc/apt/keyrings` before executing the `curl` request. The Windows instructions are missing this step and thus causing an error.

### Expected Behavior

Repository GPG Key is installed.

### Actual Behavior

`tee: /etc/apt/keyrings/ddev.gpg: No such file or directory`

### Steps To Reproduce

Use the "WSL2/Docker Desktop Manual Installation" install steps. Try performing step 12.

**Comment by rfay** [comment]
Did you use the script, if so which one?

If not, please just click the pencil in the upper right of the page and add the correct instructions, thanks!

**Comment by rfay** [comment]
Reading more closely I see you've completely diagnosed this. Why not click the edit button on https://github.com/ddev/ddev/blob/master/docs/content/users/install/ddev-installation.md?plain=1#L250 and solve it? It's much easier than an issue :)
