### ISSUE TITLE
Access Mailpit from inside?

### ISSUE THREAD

**Issue by Schnoop** [ddev/ddev#5367]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

I used the Mailhog API a lot during my automated E2E tests to check if mails are triggered. 

After switching to Mailpit, the API is not accessible inside the docker context right now.

### Describe your solution

Make Mailpit available from inside docker.

**Comment by tyler36** [comment]
Hi @Schnoop,

Mailpit does provide a simple REST API to view, search and delete stored messages. You can view the docs here: https://github.com/axllent/mailpit/wiki/API

I tend to mock the mail service in my tests so I never had a need for it in Mailhog and therefore have not used it in Mailpit.

**Comment by Schnoop** [comment]
I'am aware of this API. But i am not able to access is on localhost 8026.

**Comment by rfay** [comment]
You may also be interested in https://packagist.org/packages/koehnlein/codeception-email-mailpit
