### ISSUE TITLE
ddev debug test should ask before doing poweroff

### ISSUE THREAD

**Issue by joachim-n** [ddev/ddev#5376]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Output of `ddev debug test`

<details><summary>Expand `ddev debug test` diagnostic information</summary>

```
[COPY-PASTE HERE THE OUTPUT OF `ddev debug test`]
```
</details>         

### Expected Behavior

I recently did `$ ddev restart` and it very politely checked that it was ok to poweroff:

```
You seem to have a new DDEV version.
During an upgrade it's important to `ddev poweroff`.
May I do `ddev poweroff` before continuing?
This does no harm and loses no data. [Y/n] (yes):
```

The `ddev debug test` command should do the same.

### Actual Behavior

It shuts down sites without asking, which could lead to problems.

For example, a deveveloper who doesn't know it does this could use downtime while a test/migration/batch process is running to submit a bug report to ddev.

**Comment by rfay** [comment]
A PR would be welcome. Super easy. https://github.com/ddev/ddev/blob/master/cmd/ddev/cmd/scripts/test_ddev.sh or https://github.com/ddev/ddev/blob/master/cmd/ddev/cmd/debug-test.go
