### ISSUE TITLE
Email captured by mailpit shows a BCC to test@example.org

### ISSUE THREAD

**Issue by joelpittet** [ddev/ddev#5381]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Output of `ddev debug test`

<details><summary>Expand `ddev debug test` diagnostic information</summary>
N/A
</details>         

### Expected Behavior

Only the addresses I sent to are in the the messages.

### Actual Behavior

Mailpit adds a BCC to all messages of `test@example.org`

### Steps To Reproduce

- Generate email inside ddev with PHP
- Look at BCC line in mailpit

### Anything else?

Seems like this happened from a straight find/replace of the sendmail_path line.

https://github.com/ddev/ddev/blob/120cbe5ed6973bb42782014e493bbe183cafdbda/containers/ddev-php-base/ddev-php-files/etc/php/5.6/apache2/php.ini#L84

Maybe just remove that and the -t flag which don't do anything. See:
https://github.com/axllent/mailpit/wiki/Configuring-sendmail

**Comment by rfay** [comment]
You can test this by overriding the PHP config. Please do test your theory and do a PR if it works out.

**Comment by joelpittet** [comment]
@rfay I think you have a way to test a PR out locally down to a set of commands IIRC.  Is there a doc on how to do this that you could send me to?

**Comment by joelpittet** [comment]
PR is linked up ^^ BTW

**Comment by joelpittet** [comment]
Actually I just setup a local example of .ini in `.ddev/php/my-php.ini` and it worked like a charm.
https://ddev.readthedocs.io/en/latest/users/extend/customization-extendibility/#custom-php-configuration-phpini

<img width="547" alt="Screenshot 2023-09-26 at 08 34 07" src="https://github.com/ddev/ddev/assets/70129/0848d770-3463-436d-b7b0-797a982bdc9d">
<img width="810" alt="Screenshot 2023-09-26 at 11 45 42" src="https://github.com/ddev/ddev/assets/70129/1c91ce34-433c-4764-9885-8046ed4028e7">

**Comment by axllent** [comment]
Sorry, just jumping in here to clarify something (I'm the author of Mailpit). When sending to an address on the commandline which isn't set in the actual email itself, Mailpit will add that address as a BCC. The reason for this is that normally the SMTP server would just pass it onto the next server telling it who it was intended for, and so there's no record of it in the email itself, but here Maillot does not pass anything on. Mailpit instead creates a BCC record so it's visible in the web UI. Removing the address altogether from the sendmail command is the easiest solution and intended use here.

**Comment by rfay** [comment]
Wow @axllent , we're honored that you'd stop by! Thanks!

I think you just approved this PR, true?

**Comment by axllent** [comment]
> I think you just approved this PR, true?

LOL - yes :) The part that really needs removing is just the `test@example.org` ~ the `-t` part in regular sendmail clients means "read recipients from email" rather than specifying them on the commandline. The fact here is that Mailpit's sendmail implementation actually ignores the `-t` anyway (it's there for compatibility reasons), so technically it can go too.

**Comment by rfay** [comment]
> Edit / reword: I would probably leave the -t part in as this aligns more with other sendmail implementations - but either way it will work exactly the same in Mailpit's version.

I missed that, misremembering that `test@example.com` is not an argument to `-t`, but it seems to be working OK here, and we control the environment it's used in.
