### ISSUE TITLE
ddev get : Unable to YamlToDict: yamlToDict: type string not handled

### ISSUE THREAD

**Issue by christophe-hubert** [ddev/ddev#5385]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Output of `ddev debug test`

<details><summary>Expand `ddev debug test` diagnostic information</summary>

```Running bash [-c /tmp/test_ddev.sh] 
======= Existing project config =========
These config files were loaded for project stacy-frontend: [/home/var/www/etnic/stacy-frontend/.ddev/config.yaml]
name: stacy-frontend
type: drupal9
docroot: web
php_version: 8.0
webserver_type: nginx-fpm
webimage: ddev/ddev-webserver:v1.22.3
router_http_port: 80
router_https_port: 443
additional_hostnames: []
additional_fqdns: []
mysql_version: 8.0
database: {mysql 8.0}
hooks: map[post-start:[]]
webimage_extra_packages: [cron]
project_tld: ddev.site
use_dns_when_possible: true
nodejs_version: 18
default_container_timeout: 120
======= Creating dummy project named  tryddevproject-2670 in ../tryddevproject-2670 =========
OS Information: Linux Colombus 6.2.0-33-generic #33-Ubuntu SMP PREEMPT_DYNAMIC Tue Sep  5 14:49:19 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
User information: uid=1000(chub) gid=1000(chub) groups=1000(chub),4(adm),24(cdrom),27(sudo),30(dip),33(www-data),46(plugdev),116(lpadmin),126(sambashare),131(docker)
DDEV version:  ITEM             VALUE                                   
 DDEV version     v1.22.3                                 
 architecture     amd64                                   
 db               ddev/ddev-dbserver-mariadb-10.4:v1.22.3 
 ddev-ssh-agent   ddev/ddev-ssh-agent:v1.22.3             
 docker           24.0.6                                  
 docker-compose   v2.21.0                                 
 docker-platform  Ubuntu 23.04                            
 mutagen          0.17.2                                  
 os               linux                                   
 router           ddev/ddev-traefik-router:v1.22.3        
 web              ddev/ddev-webserver:v1.22.3             
PROXY settings: HTTP_PROXY='' HTTPS_PROXY='' http_proxy='' NO_PROXY=''
======= DDEV global info =========
Global configuration:
instrumentation-opt-in=true
omit-containers=[]
performance-mode=none
router-bind-all-interfaces=false
internet-detection-timeout-ms=3000
disable-http2=false
use-letsencrypt=false
letsencrypt-email=
table-style=default
simple-formatting=false
auto-restart-containers=false
use-hardened-images=false
fail-on-hook-fail=false
required-docker-compose-version=v2.21.0
use-docker-compose-from-path=false
project-tld=
xdebug-ide-location=
no-bind-mounts=false
router=traefik
wsl2-no-windows-hosts-mgt=false
router-http-port=80
router-https-port=443
mailpit-http-port=8025
mailpit-https-port=8026
traefik-monitor-port=10999

======= DOCKER info =========
docker location: -rwxr-xr-x 1 root root 57872384 juil.  3 11:51 /usr/local/bin/docker
docker version: 
Client: Docker Engine - Community
 Cloud integration: v1.0.35
 Version:           24.0.6
 API version:       1.43
 Go version:        go1.20.7
 Git commit:        ed223bc
 Built:             Mon Sep  4 12:31:40 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          24.0.6
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.7
  Git commit:       1a79695
  Built:            Mon Sep  4 12:31:40 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.24
  GitCommit:        61f9fd88f79f081d64d6fa3bb1a0dc71ec870523
 runc:
  Version:          1.1.9
  GitCommit:        v1.1.9-0-gccaecfc
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
DOCKER_DEFAULT_PLATFORM=notset
======= Mutagen Info =========
Mutagen is installed in ddev, version=0.16.0
--------------------------------------------------------------------------------
No synchronization sessions found
--------------------------------------------------------------------------------
======= Docker Info =========
Docker platform: Ubuntu 23.04 
Using Docker context: default (unix:///var/run/docker.sock) 
docker-compose: v2.21.0 
Using DOCKER_HOST=unix:///var/run/docker.sock 
Docker version: 24.0.6 
Able to run simple container that mounts a volume. 
Able to use internet inside container. 
Docker disk space:
Filesystem                Size      Used Available Use% Mounted on
overlay                 456.9G    385.6G     48.0G  89% /

Unable to create project at project root '/home/var/www/neo8/sites/demarcilly/drupal': project root /home/var/www/neo8/sites/demarcilly/drupal does not exist
Unable to create project at project root '/home/var/www/etnic/intranetmfwbv3': project root /home/var/www/etnic/intranetmfwbv3 does not exist
Unable to create project at project root '/home/var/www/etnic/stacy-front': project root /home/var/www/etnic/stacy-front does not exist
Stopped Mutagen daemon
The ddev-ssh-agent container has been removed. When you start it again you will have to use 'ddev auth ssh' to provide key authentication again.
Existing docker containers: 
CONTAINER ID   IMAGE           COMMAND                  CREATED         STATUS                     PORTS     NAMES
757816f22f8e   hello-world     "/hello"                 2 months ago    Exited (0) 2 months ago              kind_swirles
b2c73dbc24fa   aae3b76c2ae0    "/bin/sh -c 'export …"   19 months ago   Exited (0) 19 months ago             bold_rhodes
d8e8c204b00b   7d5678b001cc    "/bin/bash -c '(grou…"   19 months ago   Exited (0) 19 months ago             relaxed_cori
0c88a81b1ca6   9258d78bce7e    "/docker-entrypoint.…"   19 months ago   Created                              fervent_bell
779afc5a135e   8d1d48cf9b7b    "/docker-entrypoint.…"   19 months ago   Created                              hungry_ishizaka
ad0900dfc5d2   e0b33608be1f    "/docker-entrypoint.…"   19 months ago   Created                              charming_thompson
1175729d45dd   bed1b6fcab5e    "/bin/sh -c 'export …"   19 months ago   Exited (0) 19 months ago             blissful_heisenberg
55fbc32b8d5c   aae3b76c2ae0    "/bin/sh -c 'apt-get…"   19 months ago   Exited (0) 19 months ago             elastic_einstein
acdd829af55f   e9783a41a6ff    "/bin/sh -c '(groupa…"   19 months ago   Exited (0) 19 months ago             romantic_mirzakhani
c9b22ac7f771   a0bdac97d874    "/bin/sh -c '#(nop) …"   19 months ago   Created                              flamboyant_albattani
c2dd772d5953   82eaae05bc3e    "/bin/sh -c '#(nop) …"   19 months ago   Created                              relaxed_darwin
fa841e2abff2   6fb0f2b0d779    "/bin/sh -c '#(nop) …"   19 months ago   Created                              epic_mestorf
071f40154a3e   d1812c00c8e4    "/bin/sh"                20 months ago   Created                              phpstorm_helpers_PS-212.5080.71
a0320f32eab6   hello-world     "/hello"                 2 years ago     Exited (0) 2 years ago               nostalgic_bhaskara
648700e3bf3b   boondoggle/i1   "/sbin/my_init --ena…"   2 years ago     Exited (2) 2 years ago               boondoggle-c1
ae2fba0a774c   hello-world     "/hello"                 2 years ago     Exited (0) 2 years ago               xenodochial_chaplygin
Network ddev_default created 
Starting tryddevproject-2670... 
 Container ddev-ssh-agent  Created 
 Container ddev-ssh-agent  Started 
ssh-agent container is running: If you want to add authentication to the ssh-agent container, run 'ddev auth ssh' to enable your keys. 
v1.22.3: Pulling from ddev/ddev-dbserver-mariadb-10.4
7007490126ef: Pull complete 
4d07cf421114: Pull complete 
7f49892c3e51: Pull complete 
c5daef2619c3: Pull complete 
fb2dc274d0f1: Pull complete 
bc1a03f7b532: Pull complete 
18dcca1e7900: Pull complete 
1444ac5266ea: Pull complete 
72858cd9e827: Pull complete 
4f4fb700ef54: Pull complete 
b4ec44e36f91: Pull complete 
bcd5bd2a4196: Pull complete 
a38dac471b4a: Pull complete 
08100e9717a8: Pull complete 
f01779c3b84d: Pull complete 
3ed473dfd3a2: Pull complete 
46048ce9b087: Pull complete 
83df8fe67f0e: Pull complete 
932f0d6282ae: Pull complete 
be7c70da71e8: Pull complete 
9a8820e946e2: Pull complete 
f9a11cc95c4d: Pull complete 
05450d2ed3e9: Pull complete 
13e4afdd47a7: Pull complete 
Digest: sha256:3f00e76757856beacd2f88e2564d12c95d56ad5a90ffc11aac181c91d3fe96f0
Status: Downloaded newer image for ddev/ddev-dbserver-mariadb-10.4:v1.22.3
docker.io/ddev/ddev-dbserver-mariadb-10.4:v1.22.3
 Network ddev-tryddevproject-2670_default  Created 
 Container ddev-tryddevproject-2670-db  Created 
 Container ddev-tryddevproject-2670-web  Created 
 Container ddev-tryddevproject-2670-web  Started 
 Container ddev-tryddevproject-2670-db  Started 
 Container ddev-router  Created 
 Container ddev-router  Started 
Successfully started tryddevproject-2670 
Project can be reached at https://tryddevproject-2670.ddev.site https://127.0.0.1:32775 
======== Curl of site from inside container:
HTTP/1.1 200 OK
Server: nginx
Date: Wed, 27 Sep 2023 10:26:57 GMT
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
Vary: Accept-Encoding

======== curl -I of http://tryddevproject-2670.ddev.site from outside:
HTTP/1.1 200 OK
Content-Type: text/html; charset=UTF-8
Date: Wed, 27 Sep 2023 10:26:57 GMT
Server: nginx
Vary: Accept-Encoding

======== full curl of http://tryddevproject-2670.ddev.site from outside:
Success accessing database... db via TCP/IP
ddev is working. You will want to delete this project with 'ddev delete -Oy tryddevproject-2670'
======== Project ownership on host:
drwxr-xr-x 4 chub chub 4096 sept. 27 12:26 ../tryddevproject-2670
======== Project ownership in container:
drwxr-xr-x 4 chub chub 4096 Sep 27 10:26 /var/www/html
======== In-container filesystem:
Filesystem     Type 1K-blocks      Used Available Use% Mounted on
/dev/nvme0n1p2 ext4 479079112 405254380  49415340  90% /var/www/html
======== curl again of tryddevproject-2670 from host:
Success accessing database... db via TCP/IP
ddev is working. You will want to delete this project with 'ddev delete -Oy tryddevproject-2670'
Thanks for running the diagnostic. It was successful.
Please provide the output of this script in a new gist at gist.github.com
Running ddev launch in 5 seconds

Please run cleanup after debugging with 'ddev debug testcleanup'
➜  stacy-frontend git:(M0152364_resolution_des_photos) Gtk-Message: 12:27:03.452: Not loading module "atk-bridge": The functionality is provided by GTK natively. Please try to not load it.

(firefox:40336): Gtk-WARNING **: 12:27:03.502: GTK+ module /snap/firefox/3131/gnome-platform/usr/lib/gtk-2.0/modules/libcanberra-gtk-module.so cannot be loaded.
GTK+ 2.x symbols detected. Using GTK+ 2.x and GTK+ 3 in the same process is not supported.
Gtk-Message: 12:27:03.502: Failed to load module "canberra-gtk-module"

(firefox:40336): Gtk-WARNING **: 12:27:03.503: GTK+ module /snap/firefox/3131/gnome-platform/usr/lib/gtk-2.0/modules/libcanberra-gtk-module.so cannot be loaded.
GTK+ 2.x symbols detected. Using GTK+ 2.x and GTK+ 3 in the same process is not supported.
Gtk-Message: 12:27:03.503: Failed to load module "canberra-gtk-module"

```
</details>         

### Expected Behavior

When i launch ddev get xyz , for example :  
ddev get ddev/ddev-adminer   

I expect the add-ons to be downloaded, the installed in the .ddev folder of the project.

### Actual Behavior

The add on archive is well dowloaded, but the install failed

 ddev get ddev/ddev-adminer --verbose
Installing ddev/ddev-adminer:v0.2.2 
Downloading https://api.github.com/repos/ddev/ddev-adminer/tarball/v0.2.2 
v0.2.2_2887042928.tar.gz 7.94 KiB / ? [--=-------------------------------------------------------------------------------------------------------]  81.29% 0s 
Unable to YamlToDict: yamlToDict: type string not handled (post-start) 

### Steps To Reproduce

1. on ubuntu 23
2. create a ddev project
3. 
 ddev get ddev/ddev-adminer --verbose

### Anything else?

I search google , duck duck go, the githib ddev issues, i have found anything about this error.

**Comment by rfay** [comment]
I have seen this happen when github's API was broken. Please check https://githubstatus.com if you see it again.

I haven't been able to figure out exactly what happens, because of course it works by the time I take a look. It surely seems DDEV or the library it's using could give a better error than this. 

I assume this is working OK for you now, right?

What you show seems to say that the download failed in the middle of everything. That also is a situation where `ddev get` should fail and not give such a weird error.

**Comment by rfay** [comment]
Thanks for your report @sam2de - Is it working now?

**Comment by varioous** [comment]
Same issue when calling `ddev get ddev/ddev-phpmyadmin`

`ddev get ddev/ddev-phpmyadmin
Installing ddev/ddev-phpmyadmin:v0.3.0
Downloading https://api.github.com/repos/ddev/ddev-phpmyadmin/tarball/v0.3.0
v0.3.0_2479610336.tar.gz 7.32 KiB / 7.32 KiB [==============================================================] 100.00% 0s
Unable to YamlToDict: yamlToDict: type string not handled (post-start)`

**Comment by rfay** [comment]
Could you please `mv .ddev/.addon-metadata .ddev/addon-metadata.backup` and do this again? If that fixes it, would you mind providing the backup directory as a tarball/zipball?

**Comment by varioous** [comment]
@rfay - tried it.

`mv .ddev/.addon-metadata .ddev/addon-metadata.backup
mv: cannot stat '.ddev/.addon-metadata': No such file or directory`

But the directory does not exists.

My environment is 
- ddev version v1.22.3
- Windows // WSL // DockerDesktop for Windows

**Comment by rfay** [comment]
Sorry, the directory is `.ddev/addon-metadata` in your project directory. So please try `mv .ddev/addon-metadata .ddev/addon-metadata.backup`, thanks.

**Comment by varioous** [comment]
No changes, same error

**Comment by rfay** [comment]
Could you please create a trivial project and try it there? And try more than one add-on? So for example:
```
mkdir ~/junk && cd ~/junk
ddev config --auto
ddev get ddev/ddev-phpmyadmin
ddev get ddev/ddev-redis
```

If you should show the whole output of that it would be great.

If you still have the failure with that, it would be lovely if you could do `ddev debug test` and capture the output and provide it as a gist in gist.github.com or as a file, or if it's sensitive, PM me with it on Discord, https://discord.gg/hCZFfAMc5k

**Comment by rfay** [comment]
Oh, I should have suggested that you temporarily disable your virus checker as well. That could easily be it.

**Comment by varioous** [comment]
Hi,

i disabled virus checker and firewall - no changes.

With a clean and new project, it works.

Here is the ddev config of the project, where it does not work:

`name: private
type: php
docroot: ""
php_version: "7.3"
composer_version: "2"
webserver_type: apache-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
mariadb_version: "10.2"
provider: default
use_dns_when_possible: true
timezone: ""
webimage_extra_packages: ["wkhtmltopdf"]`

**Comment by rfay** [comment]
Oh, this is a very old config.yaml. We don't use `mariadb_version` any more, nor is `provider` in there any more.

Could you just do `ddev config --auto` to update it?

Then see what happens.

**Comment by rfay** [comment]
If you wouldn't mind, could you tar up or zip up your whole .ddev directory and get it to me? (Assuming you don't solve it soon.)

Thanks so much for collaborating to find the cause of this.

**Comment by sam2de** [comment]
> Oh, this is a very old config.yaml. We don't use `mariadb_version` any more, nor is `provider` in there any more.
> 
> Could you just do `ddev config --auto` to update it?
> 
> Then see what happens.
> 
> (Edit: I'm unable to recreate the problem with your config.yaml)

ddev config --auto worked for me

**Comment by sam2de** [comment]
I tried moving ".ddev/addon-metadata" directlry first that didn't fix it but after running ddev config --auto I was abled to install 2 add-ons with no issues. Thanks

**Comment by rfay** [comment]
I wish I could recreate it with your config.yaml, then we'd be able to step through and find the actual bug. There are a couple of problems here. One is that DDEV somehow isn't handling a failure properly. The other, obviously, is something upstream of that.

**Comment by sam2de** [comment]
> I wish I could recreate it with your config.yaml, then we'd be able to step through and find the actual bug. There are a couple of problems here. One is that DDEV somehow isn't handling a failure properly. The other, obviously, is something upstream of that.

I will share it on discord a bit later today

**Comment by rfay** [comment]
Thanks, I would have thought that just your config.yaml (shared above) would have worked, but perhaps there's something else in there.

**Comment by varioous** [comment]
Hi @rfay,
after running `ddev config --auto` everything works.

I sent you the old .ddev-folder as archive via Discord PM.

Thanks for your work on this great project!

**Comment by rfay** [comment]
Thanks so much for your help with this. I can now recreate the problem and will have to sort out what's causing it. But because of your patience it will be solvable!

**Comment by rfay** [comment]
@sam2de (I think) you had a completely invalid configuration in the .ddev/config.yaml:

```yaml
hooks:
post-start:
    - host-exec: ddev auth ssh
```

That is not right in many ways, and was ignored by `ddev start` somehow, but not by `ddev get`.

What you wanted was 
```yaml
hooks:
  post-start:
  - exec-host: ddev auth ssh
```

Just changing that fixes the problem. Of course DDEV should say it's not valid, but it's very much not valid. `post-start:` must be indented, and it's `exec-host` not `host-exec`. 

`ddev config --auto` throws away the invalid config and writes a valid one.

**Comment by rfay** [comment]
@varioous I'm unable to recreate your problem with the tarball you provided. Could you please see if you are still able to recreate it? Is it possible you gave me the *working* version of the .ddev directory?

**Comment by christophe-hubert** [comment]
Hi rfay
ddev config --auto 
Works fine for me. 

By the way, what does ddev config --auto  on an existing project ? 

Thank you very much for your work. DDEV rocks, as american people say :)

**Comment by rfay** [comment]
@christophe-hubert if you still have the broken .ddev directory available, I'd love to see it. Probably just the config.yaml, assuming it has an error in it...

> By the way, what does ddev config --auto on an existing project

`ddev config --auto` just does `ddev config` without asking any questions. It autodetects the docroot and project type (or uses existing) and rewrites the config.yaml file. In the process it will lose old statements like `mariadb_version` or invalid statements in the config.yaml file.

**Comment by christophe-hubert** [comment]
Hi rfay this is : 
[ddev.zip](https://github.com/ddev/ddev/files/12855637/ddev.zip)

**Comment by rfay** [comment]
Thanks @christophe-hubert - that helps me a lot.

Your config.yaml has the obsolete usage from a very old DDEV version:
```
mariadb_version: ""
mysql_version: "8.0"
```
and `ddev get` seems to die on that, even though `ddev config` handles it fine. 

❤️
