### ISSUE TITLE
Add renovate to ddev org

### ISSUE THREAD

**Issue by seebeen** [ddev/ddev#5387]
Hello,

As mentioned on [Discord](https://discord.com/channels/664580571770388500/1152623153265250374/1156667164019916861) - I'm asking you to think about adding [Renovate](https://www.mend.io/renovate/) to the DDEV org.

[Renovate](https://github.com/marketplace/renovate) is a tool which automates dependency updates in a consistent and a stable manner. It supports many package managers - some of which are crucial for ddev (dockerfile, docker compose).

It's scalable, it can be configured via templates, and has a bajillion options to tweak it to suit every workflow, project, and org.
The best part is - activating it on the org, doesn't mean it will run amok on all the repos. You can add the app to the org, and limit it to this repo and I'll set it up to work with this workflow set.

After some time, we can onboard it on some more repos, and later on create a reusable config, and automate a lot of dep updates :)

Feel free to skim over the [docs](https://docs.renovatebot.com/getting-started/installing-onboarding/) and let me know what you think.

**Comment by seebeen** [comment]
Any news? 😊

**Comment by rfay** [comment]
So far I haven't seen the value in renovate, as opposed to using a major tag and letting it float. I just see lots of chatter from your repos that I follow, but don't get any value out of what they do. But I appreciate you proposing it. I will close this for now, but feel free to continue the conversation here, and when you see actual incidents in DDEV's maintenance that would be improved with Renovate, please point them out.
