### ISSUE TITLE
Apache Gateway timeout while debugging

### ISSUE THREAD

**Issue by MakerTim** [ddev/ddev#5393]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

I use the Treafic router, but after ~30s deubbing, i got a timeout screen and makes my debugging output useless.

Looking at the docs, i got a few sugestions where timing could be an issue

** dialTimeout
> `dialTimeout` is the maximum duration allowed for a connection to a backend server to be established. Zero means no timeout.
https://doc.traefik.io/traefik/routing/services/#forwardingtimeoutsdialtimeout

** responseHeaderTimeout
> `responseHeaderTimeout` if non-zero, specifies the amount of time to wait for a server's response headers after fully writing the request (including its body, if any). This time does not include the time to read the response body. Zero means no timeout.
https://doc.traefik.io/traefik/routing/services/#forwardingtimeoutsresponseheadertimeout

** idleConnTimeout
> `idleConnTimeout` is the maximum amount of time an idle (keep-alive) connection will remain idle before closing itself. Zero means no limit.
https://doc.traefik.io/traefik/routing/services/#forwardingtimeoutsidleconntimeout 

### Describe your solution

I suppose my issue is with `responseHeaderTimeout`. While the default is 0<unlimited>, my gut feeling thinks it is changed somewhere here in the code?

But i would like to see the others get a bump or set to unlimited

### Additional context

![image](https://github.com/ddev/ddev/assets/1375359/1b5d3fed-02c4-4594-b7be-ec0d35215cf5)

**Comment by rfay** [comment]
This appears to be Apache timing out, shouldn't have to do with traefik in this situation. You can give a custom apache config with a super-long timeout maybe? It also may be php-fpm timing out. 

Custom Apache config: https://ddev.readthedocs.io/en/latest/users/extend/customization-extendibility/#custom-apache-configuration
Custom PHP config: https://ddev.readthedocs.io/en/latest/users/extend/customization-extendibility/#custom-php-configuration-phpini

If I were you I'd try nginx first.

**Comment by rfay** [comment]
But the reality is... your timeouts will timeout if you spend a lot of time debugging. But it doesn't do any harm. You can still debug to the end. This has always been true in every environment I've worked in over the decades with xdebug (and php-fpm serving results to a webserver). If you need help with the nginx or apache configs we can talk. If you change them, make sure to remove the #ddev-generated in the top of the file. Closing for now, happy to continue the conversation here or elsewhere.
