### ISSUE TITLE
Impossible to determine which project a SequelAce window belongs to

### ISSUE THREAD

**Issue by joachim-n** [ddev/ddev#5394]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Output of `ddev debug test`

<details><summary>Expand `ddev debug test` diagnostic information</summary>

```
[COPY-PASTE HERE THE OUTPUT OF `ddev debug test`]
```
</details>         

### Expected Behavior

The SequelAce window should give me some indication of which project it is connected to.

### Actual Behavior

I've used `ddev sequelace` in several projects.
I now can't tell which SequelAce window is for which project, because the window title is the same for all of them.

### Steps To Reproduce

1. Do `ddev sequelace` in two projects
2. Observe window titles are identical

**Comment by rfay** [comment]
You don't need to do any go. Just do a PR with a change to https://github.com/ddev/ddev/blob/master/pkg/ddevapp/global_dotddev_assets/commands/host/sequelace

To experiment with it all you have to do is take that script, remove the #ddev-generated, put it in ~/.ddev/commands/host, and get it working the way you want. Then do a PR with what you want, put the #ddev-generated back in.

**Comment by rfay** [comment]
Related, of course @joelpittet 's 
* https://github.com/Sequel-Ace/Sequel-Ace/issues/1819
