### ISSUE TITLE
ddev share: ngrok to support static domains

### ISSUE THREAD

**Issue by agviu** [ddev/ddev#5408]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

Ngrok has recently updated its free tier for supporting static domains, as explained by them [here](https://ngrok.com/blog-post/free-static-domains-ngrok-users).

In short, this update allows to ngrok's free tier users to have a static domain that does not change any time they create a tunner using ngrok, which is a nice feature for end users because they can now re-use this URL and use it in their configurations, for example.

In order to use this feature from ngrok, first the user needs to create the static domains in their account in ngrok, and then use them by passing the _--domain_ parameter when running ngrok in the command line.

It would be ideal for DDEV to support this feature, too, when using the **ddev share** command.

### Describe your solution

The **share** command should support this extra option when creating a tunnel using ngrok, both command line or the [proposed change](https://github.com/ddev/ddev/issues/4365) to use ngrok-go library.

Currently, the command share supports the _--subdomain_ option passed in the CLI. This would be a new addition for supporting the _--domain_ option in ngrok, via CLI.

### Describe alternatives

I cannot find any alternative. Using the existing _--subdomain_ option in share command does not work with the _--domain_ option in ngrok.

**Comment by stasadev** [comment]
Already implemented in

- https://github.com/ddev/ddev/pull/5331

Not yet in stable release, will appear in v1.22.4:

1. Use the latest version of DDEV from [master](https://nightly.link/ddev/ddev/workflows/master-build/master).
2. Or use `ngrok_args` in `.ddev/config.yaml` for `--domain` option.
