### ISSUE TITLE
ddev-webserver bashrc: clear/unset variables

### ISSUE THREAD

**Issue by benwalch** [ddev/ddev#5409]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Output of `ddev debug test`

<details><summary>Expand `ddev debug test` diagnostic information</summary>

```

```
</details>         

### Expected Behavior

bash variables `$f` and `$i` which are not used anymore should be cleared or unset. 

This leads to errors, when using bash scripts in ddev container which also use the same variable names,
e.g. https://github.com/mrbaseman/parse_yaml

### Actual Behavior

bash variables aren't cleared.
The variables `f` and `i` used in the loops [here](https://github.com/ddev/ddev/blob/master/containers/ddev-webserver/ddev-webserver-base-files/etc/bash.nointeractive.bashrc) are still set in ddev webserver environment.

### Steps To Reproduce

1. in your ddev project, add a file in `.ddev/homeadditions/bashrc.d/`
2. ssh into ddev webserver container
3. run `echo $f` or `echo $i`.

**Comment by rfay** [comment]
A PR is welcome. You can just do on on https://github.com/ddev/ddev/blob/master/containers/ddev-webserver/ddev-webserver-base-files/etc/bash.nointeractive.bashrc by clicking the edit button.

**Comment by rfay** [comment]
It does seem like you might want to do a pr to parse_yaml, because it seems unusual that previous usage of variables like this should break it.

**Comment by benwalch** [comment]
i agree. Bash scripts like parse_yaml should (also) take care of fresh variables - even though it's good practice to cleanup vars not being used anymore for a bash session.
