### ISSUE TITLE
Document mkcert for Firefox Developer Edition or Flatpak in Linux

### ISSUE THREAD

**Issue by gitressa** [ddev/ddev#5415]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

After installing the mkcert certificate, it is sometimes not found. It could be due to using a special version of Firefox, developer edition or installed via Flatpak. See https://github.com/FiloSottile/mkcert/issues/370

### Describe your solution

We could add a single line under the install command, like this?

> Modern browsers require valid certificates, which mkcert can create. [Install mkcert](https://github.com/FiloSottile/mkcert#installation), and then run this:
> 
> \# Initialize mkcert
> mkcert -install
> 
> Note: Some versions of Firefox (Developer Edition, Flatpaks) may need some [extra work](https://github.com/FiloSottile/mkcert/issues/370#issuecomment-1280377305), see also https://github.com/ddev/ddev/issues/5415.

**Comment by rfay** [comment]
This process is explained for Windows firefox in https://ddev.readthedocs.io/en/latest/users/install/ddev-installation/#windows

Maybe there's a way to consolidate the information. 

Or maybe there's a way to convince people not to use Flatpak :)

**Comment by gitressa** [comment]
Great! ... and you're right, maybe it should be extracted? Though I am not sure where it should live -- you probably have a better idea for that :)

I think Flatpaks are here to stay, and it seems to me, getting close to become the de facto solution in Linux, if you need a newer version of a program. Debian usually ships with old versions of for example Thunderbird and Firefox, and Flatpak's are easy replacements.

Do note, I am not even sure Flatpak was the issue, since others had the problem with Firefox Developer Edition, so it's not isolated to Flatpak, in any case.

**Comment by rfay** [comment]
I have been betrayed many times by both snap and flatpak. Because of their sandbox implementation, super important tools often don't behave predictably, and they give no indication of that. So I've sworn them off except for the most trivial tools.

**Comment by gitressa** [comment]
I agree about Snaps, I am also not a fan. They can lag, as well as add a lot of entries in the file system.

I haven't had too much Flatpak experience, but there are quite a few [Firefox issues](https://github.com/flatpak/flatpak/issues?q=is%3Aissue+firefox) ... and with this problem, I am getting suspicious (like you are) that they might not be so great after all ...

> Or maybe there's a way to convince people not to use Flatpak :)

I am!

Removing Flatpak Firefox and re-installing the standard Firefox ESR 115.3.0 in Debian 12 fixed it. To make mkcert work, I had to

- Visit a SSL web site _before_ generating the certificate (https://github.com/FiloSottile/mkcert/issues/120) 
- Restart Firefox (https://github.com/FiloSottile/mkcert/issues/482)
- Restart DDEV

Then the certificate is installed and works :)

To keep it simple, perhaps we could consider adding a short note that Firefox Developer Edition and Flatpaks may face challenges, and link to this issue?

> Modern browsers require valid certificates, which mkcert can create. [Install mkcert](https://github.com/FiloSottile/mkcert#installation), and then run this:
> 
> \# Initialize mkcert
> mkcert -install
> 
> Note: Some versions of Firefox (Developer Edition, Flatpaks) may need some [extra work](https://github.com/ddev/ddev/issues/5415).

**Comment by rfay** [comment]
That's a totally reasonable path. Or perhaps open (or check) the issues in the mkcert issue queue and see if it's all already there and link to that. I know the installation technique is there, but it's only mentioned for Windows Firefox I think.

**Comment by gitressa** [comment]
Ah yes, let's do that, that's also what I did in the Issue Summary. I updated it, adding a link to this issue. What do you think about that?

**Comment by rfay** [comment]
Sound good, thanks!

**Comment by gitressa** [comment]
Great, MR created!
