### ISSUE TITLE
Streamline name usage, always use DDEV in human readable text

### ISSUE THREAD

**Issue by gitressa** [ddev/ddev#5462]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

To better market DDEV, it would probably be worth considering making a conscious decision to use "DDEV" in human readable text everywhere, and not "ddev".

This would have many positive side effects, such as brand recognition, as well as making it stand out in large texts. As an example, see https://www.drupal.org/project/ideas/issues/2965681#comment-15290759 where "ddev" is lost in the text. Had DDEV been used instead, it would have stood out.

Also, "dev" is an often used word in development, which also helps over looking mentions of "ddev".

### Describe your solution

Streamline human readable texts such as documentation to use "DDEV", not "ddev".

We of course cannot force people to use "DDEV" and not "ddev", but if only "DDEV" is used here and on https://ddev.com/ and elsewhere, it would help drive home that upper case "DDEV" is the official name.

**Comment by rfay** [comment]
This is already clearly stated in https://ddev.readthedocs.io/en/latest/developers/brand-guide/#use-of-the-word-mark-ddev

**Comment by gitressa** [comment]
That's great, thanks for that link.
