### ISSUE TITLE
Allow specifying a single key or keys in `ddev auth ssh`

### ISSUE THREAD

**Issue by JeanDavidDaviet** [ddev/ddev#5465]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

I use a lot of differents key for different project.
But today you have to use a folder to specify a different key. You can't directly define a key.
`ddev auth ssh --ssh-key-path .ssh/myfolder`
I can't use a different key directly, I have to provide a folder name.

### Describe your solution

When using ddev auth
I would like to be able to use the command like this
`ddev auth ssh --ssh-key .ssh/mykey`
or
`ddev auth ssh -k .ssh/mykey`

**Comment by rfay** [comment]
This is a good idea. Alternately, explaining better how to specify a single key inside the container would be good.

**Comment by rfay** [comment]
I think you already know about https://stackoverflow.com/a/61485062/215713

You can absolutely use the homeadditions technique shown there.

**Comment by powpow12** [comment]
@rfay I tried step 1 `Workaround #1: Use just a few keys`. Here are the steps I followed:

1. `mkdir ~/ddev-ssh-keys`
2. I only have two keys so I manually symlinked them. The end result is this
![Image](https://github.com/user-attachments/assets/efed2609-b4a0-4ec2-b519-f29a1487be8e)

3. when I run this `ddev auth ssh -d ~/ddev-ssh-keys` I get the following error:
> Docker command 'docker [run -it --rm --volumes-from=ddev-ssh-agent --user=502 --entrypoint= --mount=type=bind,src=/Users/robpowell/ddev-ssh-rsa,dst=/tmp/sshtmp ddev/ddev-ssh-agent:v1.23.4-built bash -c cp -r /tmp/sshtmp ~/.ssh && chmod -R go-rwx ~/.ssh && cd ~/.ssh && ssh-add $(file * | awk -F: "/private key/ { print \$1 }")]' failed: exit status 1

**Comment by powpow12** [comment]
Disregard, it looks like I added the wrong key to pantheon 😬 . Now that I've updated it to the correct key, terminus drush is working.
