### ISSUE TITLE
Support MySQL 8.2 and 8.3

### ISSUE THREAD

**Issue by rfay** [ddev/ddev#5468]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

mysql 8.2 is now available, so I'm sure it's time to support it.

### Describe your solution

Suport 8.2

### Additional context

Related initiative: See if we can use the bitnami/mysql images instead of the complicated build we currently do for mysql 8.0 arm64.  However, bitnami/mysql does not yet have 8.2, and I doubt Ubuntu does. So this probably won't be possible in the immediately coming months.

**Comment by rfay** [comment]
Bitnami now has mysql 8.2, https://hub.docker.com/r/bitnami/mysql/tags

We may be able to move along to using bitnami instead of Ubuntu as a base image.

**Comment by liayn** [comment]
Note/Question: Shouldn't this rather be raised to mysql **8.3**, which is out for a while now?

**Comment by rfay** [comment]
Are you interested in 8.3?

The difference between "innovation" and LTS versions is described in https://dev.mysql.com/blog-archive/introducing-mysql-innovation-and-long-term-support-lts-versions/

It does look like per https://endoflife.date/mysql that it would be reasonable to support 8.2 and 8.3, although it's annoying :)

**Comment by rfay** [comment]
Note that we can't support any version of MySQL that doesn't have a Percona Xtrabackup build for it. They currently have 8.2 but not 8.3, https://docs.percona.com/percona-xtrabackup/innovation-release/release-notes/release-notes.html

(Xtrabackup is how `ddev snapshot` is implemented for MySQL.)

**Comment by liayn** [comment]
> Note that we can't support any version of MySQL that doesn't have a Percona Xtrabackup build for it. They currently have 8.2 but not 8.3, https://docs.percona.com/percona-xtrabackup/innovation-release/release-notes/release-notes.html
> 
> (Xtrabackup is how `ddev snapshot` is implemented for MySQL.)

Okay, sure. I wasn't aware of this requirement. 8.3 is probably too new, so Percona didn't catch up yet.

In regards to our "interest": Well, we are running some projects on the current MySQL version as we tend to keep our live system on the latest versions, if feasible. (Production systems are using the official mysql docker images.)
We are not using any of the latest features of 8.3 or so, it is just to make sure the "basic things" are working as intended.

**Comment by GuySartorelli** [comment]
Mariadb 11.0, 11.1, 11.2, 11.3, and 11.4 are all out now as well and should likewise be supported.

Just had a CI failure for a project and I had to run through a bunch of hoops to get mariadb 11.3 running in a separate service in order to reproduce it locally 😓

**Comment by GuySartorelli** [comment]
On your note about snapshots, perhaps for versions of mysql/mariadb that are too new for snapshots could be supported in ddev, but with a warning (and perhaps even an interactive "are you sure" prompt) that snapshots won't be supported?

**Comment by rfay** [comment]
> Mariadb 11.0, 11.1, 11.2, 11.3, and 11.4 are all out now as well and should likewise be supported.

We only support MariaDB LTS versions. It got too crazy. They release all these versions and then only support them for a short time. So when they come out with LTS, we add it.

**Comment by rfay** [comment]
> 
On your note about snapshots, perhaps for versions of mysql/mariadb that are too new for snapshots could be supported in ddev, but with a warning (and perhaps even an interactive "are you sure" prompt) that snapshots won't be supported?

We don't support postgres:9, but that's the only one right now. I'm hoping that by the time mysql:8.3 is available xtrabackup will be available for it. I saw them pull a PR for it the other day. Then the question will be whether xtrabackup 8.3 will be compatible with mysql:8.2.

But whatever we're doing for postgres:9 to exclude snapshots should work per your idea. 

Not sure this can make it into v1.23.0 though.

**Comment by GuySartorelli** [comment]
> We only support MariaDB LTS versions.

Ahh yup that makes sense. Now that I look for that in the DDEV docs I can see it's mentioned exactly where it should be lol.

How do you tell which are LTS? I can't see anything in https://mariadb.com/kb/en/mariadb-releases/ or https://mariadb.com/kb/en/mariadb-server-release-dates/ that says it, but I may just be looking in the wrong place.

**Comment by rfay** [comment]
One easy place is https://endoflife.date/mariadb

But also on https://mariadb.com/kb/en/mariadb-server-release-dates/

<img width="738" alt="image" src="https://github.com/ddev/ddev/assets/112444/4381e21d-a0ff-4d7c-b8f2-936c13346a2a">

**Comment by tyler36** [comment]
Opened a draft PR to hightligh the database types and versions. https://github.com/ddev/ddev/pull/5884

**Comment by rfay** [comment]
We will not be supporting MySQL Innovation releases, just as we do not support MariaDB non-LTS versions. When MySQL 10.4 goes LTS, we'll support it. The others have too short a life. https://dev.mysql.com/blog-archive/introducing-mysql-innovation-and-long-term-support-lts-versions/
