### ISSUE TITLE
ddev import-files removes settings.php and settings.ddev.php

### ISSUE THREAD

**Issue by rebelmusic** [ddev/ddev#5474]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected Behavior

settings.php and settings.ddev.php should remain as is.

### Actual Behavior

settings.php settings.ddev.php are deleted

### Steps To Reproduce

1. add settings.php to web/sites/default
2. start a **new** Drupal project with `ddev start`
3. run `ddev import-files --source=.tarballs/files.tgz`

**Comment by rfay** [comment]
We always want to hear about problems, so thanks for filing this issue.

I just attempted to recreate this with a drupal10 site and wasn't able to. Is it possible that it had to do with the content of your files.tgz file? Please take a look at that. It could also be that your project wasn't of type drupal*, or that you had `upload_dirs` set to something "interesting" that wasn't correct?

You didn't provide the requested output of `ddev debug test` so I don't have any answers to these questions, but maybe you can come back and add that to the issue, or out the output in a gist on gist.github.com or some other pastebin.

But before that, please make sure you can recreate this behavior. 

It would be nice if you'd do a trivial plain-vanilla drupal10 project and demonstrate it with that. You can create one with the instructions at https://ddev.readthedocs.io/en/latest/users/quickstart/#drupal

If you'd like a sample files.tgz to work with, there's a d10 version of a set of files at https://github.com/ddev/d10simple-artifacts

**Comment by rfay** [comment]
I just repeated my test on a plain-vanilla drupal9 site and certainly didn't see this behavior. Please make sure you can provide a recreatable scenario. Maybe you can push up a repo to GitHub that demonstrates it? Maybe you can PM me the files.tgz (but look inside first). 

(I should note that DDEV manages the settings.ddev.php, and it will be recreated on every `ddev start` unless the #ddev-generated has been removed from it.)

**Comment by rfay** [comment]
Yes, if you use `--target=sites/default` it puts your files into sites/default, overwriting what was there, which was your settings.php.

**Comment by rfay** [comment]
Please don't use the `--target` if you don't know what it's for.

**Comment by rfay** [comment]
I would love to have you explain why you were using `--target` though, and what made you think that pointing it at `sites/default` was a good idea. Is there something in the docs or `ddev help import-files` that led you down this path?
