### ISSUE TITLE
Join Drupal.org discussion about DDEV recommended Drupal local development environment

### ISSUE THREAD

**Issue by Francewhoa** [ddev/ddev#5487]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

Hello DDEV and Drupal enthusiasts :) This is to inform you that there is presently a community discussion on Drupal.org about adding DDEV to the official Drupal.Org documentation about recommended Drupal local development environment. Which in turn could result in significantly growing DDEV community.

All are welcome to join this discussion. Now is a good time to share your feelings and thoughts about this. And answer questions or concerns at https://www.drupal.org/project/ideas/issues/2965681

I'm new to DDEV. So, not yet familiar, with where it is the most appropriate to post this invite. Feel free to move it to another location.

### Describe your solution

For those interested, now is a good time to join this discussion at https://www.drupal.org/project/ideas/issues/2965681

**Comment by rfay** [comment]
Welcome @Francewhoa , and thanks for contributing and opening this issue.

I would prefer that people not add "me too" comments to the Drupal.org issue. Constructive additions to the new sub-issues are welcome, especially if people start to work on the issues. But Drupal issues of this type tend to fill up with people expressing opinions that just confuse and bike-shed. 

Right now it appears that the maintainers of Drupal are on the right track and trying to guide this to completion, so I prefer that we let them do that. And they already know that we're way happy to help along the way.

Closing this for now, again thanks for the contribution.

**Comment by Francewhoa** [comment]
Thanks for your reply @rfay :) As maintainer of this repo, feel really free to close this ticket.

Thanks for all your numerous contributions to both DDEV and the Drupal community
