### ISSUE TITLE
Remove unnddev.readthedocs.io from the internet

### ISSUE THREAD

**Issue by gitressa** [ddev/ddev#5495]
### Problem

I searched for something DDEV-related and found an old DDEV manual online: 

https://unnddev.readthedocs.io/en/latest/

### Solution

It should probably be removed. If there are other old version DDEV readthedocs out there, likewise.

**Comment by rfay** [comment]
I'll ask @unn to remove it.

**Comment by gitressa** [comment]
Thanks!

**Comment by gitressa** [comment]
I found another one: https://mootari-ddev.readthedocs.io/en/latest/

**Comment by rfay** [comment]
@mootari Would you mind removing https://mootari-ddev.readthedocs.io/en/latest/  if you're not using it? These days PRs create branch previews on Readthedocs so we don't need the extra versions any more.

**Comment by mootari** [comment]
@rfay Done!

**Comment by unn** [comment]
@rfay and it's gone.

**Comment by rfay** [comment]
Thanks so much @unn !

**Comment by rfay** [comment]
And always nice to cross paths with you @unn ! Hope things are going great.
