### ISSUE TITLE
Use n for managing node version

### ISSUE THREAD

**Issue by hanoii** [ddev/ddev#5509]
I like to pin the node version, it's a personal preference, but I normally do this on most of my projects:

```
RUN npm install -g n
RUN n install 20.9.0
```

This works very nicely and you can use almost [any node version.](https://www.npmjs.com/package/n#specifying-nodejs-versions).

I wonder if you'd consider this instead of what ddev is doing right now? I would go one step forward and add node_extra_packages and add that to the dockerfile automatically. 

Just an idea.

**Comment by rfay** [comment]
How is this better than `ddev nvm` to pin things?

**Comment by hanoii** [comment]
This goes on the image

**Comment by rfay** [comment]
Would there be a way to do it that did *not* pin, so we could continue using `nodejs_version: 20` for example? But have the option of `nodejs_version: 20.9.0` ?

**Comment by hanoii** [comment]
You can pin to whatever, even `20`, you can do `n install 20` and it would be the same as what you have now, obviously this would not pin to the latest as it goes to the dockerfile, so until the cache bust, but is the same as your apt approach.

**Comment by rfay** [comment]
If this can be done without changing the behavior of `nodejs_version` at all, I would probably be OK with it.
