### ISSUE TITLE
Add facility to make it easy to add `launch` type custom commands that open browser with correct URL

### ISSUE THREAD

**Issue by tyler36** [ddev/ddev#5518]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

Recently, I created a custom command to launch the xhgui service in a browser.
This is currently quite complex;
- checks if HTTP / HTTPS
- checks for Gitpod or Codespaces
- checks if DEBUG is enabled
- case for linux
- case for darwin
- case for window

It would be convient to have a centralized helper function that custom command developers can call.
This would allow all open-in-browser commands to be updated if, say, Codespaces is updated.

### Describe your solution

I would like DDEV to provide a helper function to create a new command.
For example:

```
#!/bin/bash shell

## #ddev-generated
## Description: Launch a browser to XHGui
## Usage: xhgui
## Example: "xhgui"

HTTP_PORT = 8142
HTTPS_PORT = 8143

launch_service(HTTP_PORT, HTTPS_PORT )
```

### Additional context

Several modules, including the `launch` command would benefit from this:

Eg.
- ddev-xhgui
- ddev-adminer

**Comment by rfay** [comment]
Maybe `launch` and `phpstorm` and `adminer` commands could be rolled into this...

**Comment by rfay** [comment]
Is this fixed with 
* https://github.com/ddev/ddev/pull/6024
?

**Comment by tyler36** [comment]
Yes, that resolves this issue.  Glad we got this feature in. 

## Test 

1. Install ddev-adminer

```shell 
ddev get ddev/adminer
```

2. Update global adminier command as below.


```bash
DDEV_ADMINER_PORT=9100
DDEV_ADMINER_HTTPS_PORT=9101

if [ ${DDEV_PRIMARY_URL%://*} = "https" ]; then
    ddev launch :$DDEV_ADMINER_HTTPS_PORT
else
    ddev launch :$DDEV_ADMINER_PORT
fi
```

3. Restart DDEV

```shell
ddev restart
```

4. Confirm update command generates correct URL

```shell
$ DDEV_DEBUG=TRUE ddev adminer
FULLURL https://30days-l11-demo.ddev.site:9101
```

5. Confirm it opens browser to Adminer.

```shell
ddev adminer
```

DDEV: `v1.23.0-rc1`
OS: WSL2 Ubuntu on Win10.

UPDATE:
Look like I just confirmed what @stasadev  said [here ](https://github.com/ddev/ddev/pull/6024#discussion_r1542688034)

**Comment by rfay** [comment]
Thanks. 
I assume you'd like to be able to update existing commands to use this feature though also, right?

**Comment by tyler36** [comment]
Yes, as I come across addons that benefit, I'll make PRs as nessasary.
