### ISSUE TITLE
feat: allow users to set mailpit version

### ISSUE THREAD

**Issue by tyler36** [ddev/ddev#5526]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

Until recently, mailpit was available as an addon.
The addon used a docker implementaion which allowed users to change the image version number at will.

Now that mailpit is in core, we no longer have the ability to easily change the version. Developer have to wait for PRs and new images to be built.  

This leads to PRS like #5524 . 

Currently, the core version is 12 versions behind the latest.

### Describe your solution

Ability to set mailpit version via configuration (similar to PHP and nodejs).

### Additional context

Not sure if this is even possible presently.

One of mailpits selling points is on-going development so we are not currently able to take advantage of this (or aleast at a reduced rate).

**Comment by rfay** [comment]
I was thinking it would be best to just use latest version, https://github.com/ddev/ddev/pull/5524#issuecomment-1804220473

**Comment by rfay** [comment]
#5524 already went in.

If somebody really had to do this it's easy to do with a .ddev/web-build/Dockerfile.mailpit. 

I think we can probably get along with what we have.
