### ISSUE TITLE
Feature: add `ddev snapshot restore -a`

### ISSUE THREAD

**Issue by mejta** [ddev/ddev#5543]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

Thank you for a great tool; ddev helps me a lot! It's also great that we have a `ddev snapshot -a` possibility that will do a database snapshot for all the projects. That helped me a lot while upgrading colima lately. But what would also be great was `ddev snapshot restore -a`. This command would restore latest snapshot for each project. Can you add that, please? It would be a great addition!

### Describe your solution

Add a `ddev snapshot restore -a` that will restore latest snapshot for each project.

### Describe alternatives

Some bash function works as well. I have the following:

```bash
ddevrestore() {
    # Create a temporary file to hold the project paths
    local temp_file=$(mktemp)

    # Ensure the temporary file is removed even if the script exits unexpectedly
    trap 'rm -f "$temp_file"' EXIT

    # Get the list of projects using ddev list -j and parse it using jq
    ddev list -j | jq -r '.raw[].approot' > "$temp_file"

    # Initialize an empty array to store project paths
    local project_paths=()

    # Read the file line by line and add to the array
    while IFS= read -r line; do
        project_paths+=("$line")
    done < "$temp_file"

    # Iterate over the project paths
    for project in "${project_paths[@]}"; do
        if [ -n "$project" ]; then
            echo "Processing project: $project"

            # Change to the project directory
            if cd "$project"; then
                # Restore the latest snapshot (adjust the command if needed)
                ddev snapshot restore --latest

                # Stop the project
                ddev stop

                # Return to the original directory
                cd - > /dev/null
            else
                echo "Could not change to directory $project"
            fi
        fi
    done

    # Remove the temporary file
    rm -f "$temp_file"
}
```

**Comment by rfay** [comment]
You can use this custom command, requires `jq`.  Place these contents in ~/.ddev/commands/host/restoreallsnapshots and `ddev restart` and try `ddev restoreallsnapshots`:

```bash
#!/bin/bash

## Description: Restore the latest snapshot from all registered projects
## Usage: restoreallsnapshots
## Example: "ddev restoreallsnapshots"

#set -x
set -eu -o pipefail
approots=$(ddev list -j | docker run -i --rm ddev/ddev-utilities jq -r ".raw[] | .approot")
for projdir in ${approots}; do
  cd ${projdir}
  ddev snapshot restore --latest || (printf "\nWarning: snapshot restore failed or no snapshot available for ${projdir}\n" && true)
  ddev stop
done
```

**Comment by rfay** [comment]
Looks like you beat me to it!

**Comment by rfay** [comment]
A PR would be welcome to do it in golang as well.

**Comment by rfay** [comment]
I think this might be too intrusive for people, so closing for now, happy to continue the conversation here or elsewhere.
