### ISSUE TITLE
Feature: A hook that runs every time a ddev command is executed

### ISSUE THREAD

**Issue by hanoii** [ddev/ddev#5557]
I would like a hook that would allow me to automate things like:
- `ddev restart` after a git pull if a certain criteria is met
- `notify something to the team members` if a certain criteria is met
- etc.

Although the issue should have come first, there's #5448 that adds an idea for this.

More context on https://discord.com/channels/664580571770388500/1144344589549973636/1166023601540051004

**Comment by rfay** [comment]
Thanks, how would this help with a "ddev restart after a git pull if a certain criteria is met"? Do you have git hooks that do DDEV things?

**Comment by hanoii** [comment]
I don't have git hooks currently, and while some of this can be sorted with githooks I can think of other ways where ddev can be of use, specially if I assume that githooks are supposed to be run on the container, but the idea is that:

i.e.:

- I add an add-on to the ddev project
- I commit and push the add-on to the repo
- A team member pulls the new code but doesn't notice the add-on is added
- He continues to work on his project as usual but after a ddev comman is run, a script realizes that something has changed and executes a ddev restart.

Same thing can be done to theme rebuilt, composer installs, etc.

**Comment by hanoii** [comment]
This is almost like the version constraint validation that happens on config, if a new version constraint is pushed, subsequent commands will fail. That's another place where I considered adding a hook.. `post-config-valid` or something, but the same concern about json output and whatever happens in that hook will likely be the same.

**Comment by hanoii** [comment]
is like a bootstrap hook.

**Comment by rfay** [comment]
But please explain how this feature would help you, compared to, for example, a `git fetch` or `git pull` in a pre-start exec-host command...

**Comment by hanoii** [comment]
it's the other way around, and this is outside or `ddev start`. Assume the project is already running, git pull is called on the host, I want to be able to detect changes within the running ddev and act accordingly (this is the automation I can think of right now).

**Comment by rfay** [comment]
> Assume the project is already running, git pull is called on the host, I want to be able to detect changes within the running ddev and act accordingly

In this case, git hooks would be invaluable and far more direct... And they'd catch the issue right away.

**Comment by chrisfromredfin** [comment]
My only counterpoint (I totally agree git hooks would be the best solution for this) is that git hooks can't really ship with a repo, but DDEV commands/hooks can. There are projects like https://github.com/captainhookphp/captainhook that would help ship hooks with the project, but that does add a layer of complexity, of course.

**Comment by rfay** [comment]
DDEV ships git hook *setup* scripts, https://github.com/ddev/ddev/tree/master/.githooks

That's part of the way along the path you're mentioning @chrisfromredfin 

But an add-on is an interesting thought as a way to manage it.

**Comment by hanoii** [comment]
repo-based git hooks is a subject that I've been following for a long time. captain hooks ia a bit of a nice placeholder but it's only for php/composer projects. Obviously an add-on is useful to ease it use. My next plan when I have some time is going with a similar approach to ddev, but instead is with the use of [core.hooksPath](https://pilot34.medium.com/store-your-git-hooks-in-a-repository-2de1d319848c).

I can't think of a strong counterargument to having something like this, it still believe it's useful as I am all for extendability but I understand that with a great flexibility comes greater supportability, so for now I am gonna leave it lingering here. 

If I can come up with any other strong point for something like this, I'll be sure to mention it.

**Comment by hanoii** [comment]
The above is also useful to enforce some other git config stuff if you dare like:

```
[pull]
        rebase = merges
```

(I'll probably dare)

**Comment by rfay** [comment]
Decided against this in 
* https://github.com/ddev/ddev/pull/5448#issuecomment-1858512522
