### ISSUE TITLE
Add ddev exec option to exclude custom docker-compose files

### ISSUE THREAD

**Issue by timkelty** [ddev/ddev#5585]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

When working on a PHP project, I will often want to work on a composer package that I have the repo checked out elsewhere.
To do this, I can add `.ddev/docker-compose.local.yaml`:

```yaml
services:
  web:
    volumes:
      - ~/Dev/craftcms-4:/var/www/html/vendor/craftcms/cms:ro
```

This works great, but when running `ddev composer` commands, you will run into trouble, as composer will often delete package dirs in the update process. This is why I have the `:ro` flag, as otherwise you can accidentally delete your repo. When this happens, you'll see an error like this:

```
❯ ddev composer require "craftcms/commerce:^4" -W
  - Upgrading craftcms/cms (4.5.11 => 4.5.11.1): Extracting archive
    Update of craftcms/cms failed

In Filesystem.php line 288:

  Could not delete /var/www/html/vendor/craftcms/cms/.lintstagedrc.json:
```

So, the process I'm trying to improve is:

- `ddev stop`
- comment out the contents of `.ddev/docker-compose.local.yaml`
- Run your `ddev composer` command
- `ddev stop`
- bring back the contents of `.ddev/docker-compose.local.yaml`
- `ddev start`

### Describe your solution

What would be great is if `ddev exec` had an option to ignore custom docker-compose files. So, it might look like:

```
ddev exec --ignore-custom-docker-compose composer require "craftcms/commerce:^4" -W
```

…which would exec without including any `.ddev/docker-compose.*.yaml` files.

### Describe alternatives

Another solution could be to introduce a new command to toggle whether those files are included:

```
ddev custom-docker-compose off
ddev composer update
ddev custom-docker-compose on
```

**Comment by rfay** [comment]
Instead of `docker-config.local.yaml` everywhere you mean `docker-compose.local.yaml` right? Please edit.

**Comment by rfay** [comment]
`ddev exec --ignore-custom composer require "craftcms/commerce:^4" -W` isn't really going to work here; `exec` is a general-purpose tool, and it doesn't know that composer even exists.

However, you can easily make a custom web command that does exactly what you want. Custom web commands are essentially "exec" on steroids with any details you want. Try it out! https://ddev.readthedocs.io/en/latest/users/extend/custom-commands/

**Comment by timkelty** [comment]
> isn't really going to work here; exec is a general-purpose tool, and it doesn't know that composer even exists.

How do you mean? Composer is just part of my example use-case, but would have nothing to do with this feature. `ddev exec composer require` works just fine (assuming `composer` is in the container's PATH, which in my case it is). I'm just proposing adding a `--ignore-custom` arg to `exec`.

**Comment by timkelty** [comment]
> Maybe you mean --ignore-custom-docker-compose

yep, that would be a better arg name :).
So if that arg was present, ddev wouldn't include any `.ddev/docker-compose.*.yaml` files when it compiles its final compose file.

**Comment by rfay** [comment]
Unfortunately, the project has already been started, with all the additional docker-compose.*.yaml, so `exec` doesn't have anything to do with loading them.

**Comment by rfay** [comment]
This approach isn't going to work, but happy to continue brainstorming with you to figure out what might work. 

I think you *may* be able to use a custom command. Give it a try.

Closing this for now, happy to continue the conversation here or elsewhere.
