### ISSUE TITLE
Move colima tests to buildkite

### ISSUE THREAD

**Issue by rfay** [ddev/ddev#5598]
Running colima + ddev on github actions runner is just too terribly painfully slow.

Move it to our buildkite runners.

**Comment by rjensen26** [comment]
@rfay , I was wondering if you changed https://github.com/ddev/ddev/blob/master/.github/workflows/colima-tests.yml#L107C10-L107C11

```
--vm-type=qemu --mount-type=sshfs
```
to
```
--vm-type=vz --mount-type=virtiofs
```

I know the `qemu` was a lot slower on M1 pro macOs and was a lot faster using `virtiofs`.

**Comment by rfay** [comment]
* Github only supports macOS 13 so far, and not that well. VZ works a lot better on macOS 14. 
* We aren't yet recommending VZ/virtiofs in the docs, so we want to test what we're recommending...

**Comment by rfay** [comment]
Colima is now failing almost all the time for reasons we can't quite understand, so this is going to be one path forward.
