### ISSUE TITLE
Out of date URL in error message

### ISSUE THREAD

**Issue by joachim-n** [ddev/ddev#5604]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Output of `ddev debug test`

.

### Expected Behavior

The error message

>  See https://en.wikipedia.org/wiki/Hostname#Restrictions_on_valid_hostnames for valid hostname requirements

has an out of date URL - the anchor is no longer valid.

### Actual Behavior

Link needs updating.

**Comment by stasadev** [comment]
Thanks for noticing this!
