### ISSUE TITLE
Project Hostname in additional services receives the wrong IP address

### ISSUE THREAD

**Issue by sebastian-ehrling** [ddev/ddev#5607]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Output of `ddev debug test`

I've added an additional service to my ddev project via an additional yaml file.

Everythink works fine. But i'm unable to resolve the correct ip address for the project hostname via ssh from the new container. 
I always get 127.0.0.1. But i want to get the ip address from the web container.

### Expected Behavior

I get the ip address from the web container and not 127.0.0.1

### Actual Behavior

i get the ip address 127.0.0.1

### Steps To Reproduce

**Steps to reproduce:**
ddev start
ddev ssh -s myservice
ping myproject.ddev.site   --> Result 127.0.0.1 👎 

**Alternative SSH via web container:**
ddev ssh
ping myproject.ddev.site   --> Result 172.19.0.7.   👍 

### Anything else?

EXAMPLE Service YAML FILE
`
version: '3.6'
services:
  myservice:
    container_name: ddev-${DDEV_SITENAME}-myservice
    hostname: ${DDEV_SITENAME}-myservice
    image: image/image:latest
    expose:
      - "1880"
    ....
  web:
    links:
      - myservice:myservice

volumes:
  myservice:

`

**Comment by rfay** [comment]
Hi @sebastian-ehrling - `*.ddev.site` is in DNS worldwide as 127.0.0.1. If you're inside your extra container, you can easily `ping web` to get direct access to the web container.  If you prefer to use an alias or introduce additional lookup, you can use techniques like in https://github.com/rfay/ddev/tree/20231205_xdebug

For example, in your `myservice` service, try
```yaml
services:
  myservice:
    external_links:
      - "ddev-router:myproject.ddev.site"
```

Alternately, if you want to refer directly to the `web` container (as opposed to the router), try 

```yaml
services:
  myservice:
    external_links:
      - "web:myproject.ddev.site"
```

**Comment by sebastian-ehrling** [comment]
Hi @rfay 
thx!  The following configurations works perfect for me:
    external_links:
      - "web:${DDEV_SITENAME}.ddev.site"

I've another question. How is ist possible to use the ssh agent oder my ssh keys inside the new container myservice?

**Comment by tyler36** [comment]
@sebastian-ehrling 

Are you talking about [`ddev auth ssh` ](https://ddev.readthedocs.io/en/latest/users/usage/commands/#auth-ssh)?

BTW, issue queues are not are good place to ask unrelated questions. Here's a [link to the dicord server](https://discord.gg/kDvSFBSZfs) which is a great place to ask the community. 😄

**Comment by sebastian-ehrling** [comment]
@jonaseberle thx!
Yes, i need the real hostname and certificate for an http request.
