### ISSUE TITLE
Acquia provider settings file

### ISSUE THREAD

**Issue by danepowell** [ddev/ddev#5609]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

When initializing DDEV for an Acquia-hosted project, I must manually create a local.settings.php file with the DDEV-specific db info. This should be unnecessary, since all Acquia projects automatically include db info and other settings from a server-side settings file located at `/var/www/site-php/${group}/${group}-settings.inc`.

### Describe your solution

When using the Acquia integration, a settings file should be automatically created at `/var/www/site-php/${group}/${group}-settings.inc` containing DDEV-specific settings.

### Additional context

Based on my reading of the provider documentation, this isn't currently possible with DDEV. Providers can override specific commands, but not mount arbitrary files.

Lando already supports this in its Acquia integration, and that's what I'd like to replicate: https://github.com/lando/acquia/blob/7ff7dbea42de94c3a32bdcce91e7b6d76f5366c2/recipes/acquia/builder.js#L94C70-L94C118

**Comment by rfay** [comment]
Ddev normally just creates settings.ddev.php with the settings info, and no additional settings are required. What more benefit does it add to imitate the Acquis way? It is absolutely not necessary to create the file you suggest and I've never had to do it. Same with Pantheon.

**Comment by danepowell** [comment]
Of course, and settings.ddev.php does 90% of the work. But that still requires a customer adopting DDEV for the first time to add `require settings.ddev.php` to their own settings.php, right?

My point is that customers _already_ `require` a predictably-named settings file on the Acquia platform. By moving and renaming `settings.ddev.php` to that location (or installing a shim file at that location) we can create a seamless experience for customers onboarding to Lando.

**Comment by rfay** [comment]
So glad to have you visiting this.

When you `ddev config` you choose the docroot (normally automatically detected, always works for Acquia). When you use project type drupal6+, DDEV on `config` or `start` adds an include to the settings.php. I hope you'll try it out with a project you use for testing. You'll see that nothing has to be done.

**Comment by danepowell** [comment]
You're right! Sorry I missed that automatic addition to settings.php the first time, it was obscured by an unrelated application error.

Still, I think there'd be value in allowing an Acquia application to automatically connect to the db _without_ adding the `settings.ddev.php` include to settings.php. The current method works well enough, but does require some thought and effort from the customer to commit the ddev-managed changes to settings.php, versus everything just working out of the box if ddev could provide the same settings via `/var/www/site-php/$AH_SITE_GROUP/$AH_SITE_GROUP-settings.inc` (along with the appropriate env vars)

**Comment by rfay** [comment]
Can you be more specific about what you'd do that's not already being done? In general, it is a catastrophe to naively apply upstream settings from Acquia (or Pantheon ... or Platform ...) because they're intended for the environment they live in. 

However, Platform does have ddev/platformsh, which is an add-on which tries to interpret upstream specific config and apply it locally. Add-ons are pretty easy, and it wouldn't be hard to create one for Acquia if you're interested and know what you'd want to do.

**Comment by rfay** [comment]
I'm sure you've already looked at what DDEV adds to the settings.php; it doesn't matter in any non-ddev environment, doesn't break Lando, Lando doesn't break it, and it has no impact on an Acquia configuration:

```
if (getenv('IS_DDEV_PROJECT') == 'true' && file_exists(__DIR__ . '/settings.ddev.php')) {
  include __DIR__ . '/settings.ddev.php';
}
```

Since DDEV itself has no knowledge that a given project is an Acquia project (and doesn't need to know) it would be a heavy lift to reconfigure everything to work differently for Acquia, so I'm not that thrilled about the idea :) And of course, this is the first issue I can ever remember where anybody from Acquia ever opened any kind of conversation about the integration. We're glad you're here and welcome collaboration! But probably won't re-architect DDEV based on a first feature request.

**Comment by danepowell** [comment]
> it doesn't matter in any non-ddev environment, doesn't break Lando, Lando doesn't break it,

Right, and I'm not claiming that it _does_ break anything. I'm simply saying that modifying settings.php at all (even in a relatively harmless way) creates minor overhead and a loose coupling to DDEV that could be entirely avoided by simply moving and renaming settings.ddev.php.

I'm also not asking _you_ to necessarily do the work; I'd be happy to submit a PR if it were possible, but it seems like custom providers aren't able to mount arbitrary files. That seems like a valuable feature to have even apart from this particular issue, but I leave that judgement to you.

At any rate, I appreciate your point that I'm the only person making noise about this so far, and I don't want to trouble you any further. Thanks for listening. If you decide to circle back to this and want help, let me know.

**Comment by rfay** [comment]
> Right, and I'm not claiming that it does break anything. I'm simply saying that modifying settings.php at all (even in a relatively harmless way) creates minor overhead and a loose coupling to DDEV that could be entirely avoided by simply moving and renaming settings.ddev.php.

I don't disagree with you about that and would prefer not to do it. In a number of other CMSes we are able to do it with something like a .env.local, for example, which is far better. However, it's been years and years now and people love how easy it is to spin up a Drupal project. Completely invisible to them. If it were today, we'd probably try to figure out something with a .env, etc. But I think even with the state of Drupal today you couldn't do that without forcing people to add a module or something.

So happy to have you here in the issue queue! And thanks for fixing the mysql thing in acli. Hopefully I can get back to the Acquia integration now and do things the easier way.
