### ISSUE TITLE
Feature request: `ddev mailpit` command

### ISSUE THREAD

**Issue by gitressa** [ddev/ddev#5627]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

Wouldn't it be great if `ddev mailpit` launched Mailpit? `ddev launch -m` is less intuitive, nor rememberable ...

### Describe your solution

Make `ddev mailpit` launch Mailpit.

**Comment by rfay** [comment]
Why don't you create one and start using it, and then contribute it? Super easy. People have loved `ddev launch -m` but I do think `ddev mailpit` might be better.

**Comment by GuySartorelli** [comment]
PR: https://github.com/ddev/ddev/pull/5642

**Comment by gitressa** [comment]
Thanks @GuySartorelli and @stasadev, I'm looking forward to using `ddev mailpit` :)

**Comment by gitressa** [comment]
Thanks, this is awesome :)
