### ISSUE TITLE
Failed to start solr, no matching manifest for linux/arm64/v8

### ISSUE THREAD

**Issue by markabur** [ddev/ddev#5630]
### Is there an existing issue for this?

- [X] I have searched the existing issues

I am trying to install solr for a Drupal 7 site, following the instructions at the top of this file:

https://github.com/ddev/ddev/blob/v1.11.0/pkg/servicetest/testdata/services/docker-compose.solr.yaml

When I run ddev start, I get this error:

Failed to start mtf-d7: composeCmd failed to run 'COMPOSE_PROJECT_NAME=ddev-mtf-d7 docker-compose -f /Users/mab/Sites/mtf/d7/.ddev/.ddev-docker-compose-full.yaml up -d', action='[]', err='exit status 18', stdout='', stderr=' solr Pulling 
no matching manifest for linux/arm64/v8 in the manifest list entries' 

I have found some docker discussions regarding linux/arm64/v8 errors but I still can't figure out how to fix the problem.

### Output of `ddev debug test`
Here is the output of ddev test:

https://gist.github.com/markabur/f588f6c406469177bbbe6dd585f5e916

### Expected Behavior

The site should start with no errors, and solr 6.6 should be running

### Actual Behavior

I get the following error:

Failed to start mtf-d7: composeCmd failed to run 'COMPOSE_PROJECT_NAME=ddev-mtf-d7 docker-compose -f /Users/mab/Sites/mtf/d7/.ddev/.ddev-docker-compose-full.yaml up -d', action='[]', err='exit status 18', stdout='', stderr=' solr Pulling 
no matching manifest for linux/arm64/v8 in the manifest list entries' 

### Steps To Reproduce

1. mkdir solr
2. cd solr
3. ddev config; accept all defaults
4. follow steps 1 - 3 in the https://github.com/ddev/ddev/blob/v1.11.0/pkg/servicetest/testdata/services/docker-compose.solr.yaml file, copying the conf files from any up-to-date D7 site that has search_api_solr installed
5. ddev start

Alternatvely, this could be added to an existing D7 site instead of creating a standalone solr site, but in either case the error is the same.

**Comment by rfay** [comment]
Solr isn't a feature of DDEV core.

I'm not sure what you've done here, but would you please remove it all and use `ddev get ddev/ddev-solr` instead and see how that goes? DDEV v1.11.0 was a very, very long time ago. Years. And the thing that you quote from years ago is test data only.

Please take a look at https://github.com/ddev/ddev-solr
or perhaps
https://github.com/ddev-drupal9-solr

**Comment by markabur** [comment]
Thanks, I was following the tip here:

https://stackoverflow.com/questions/63782201/configure-ddev-with-apache-solr-on-drupal-7-for-search-api

It looks like ddev-solr requires the search_api_solr_admin module, which is not compatible with Drupal 7?

**Comment by rfay** [comment]
So the "no matching manifest" problem is that you're on a mac with Apple Silicon, right? And you're specifying an ancient version of Solr that didn't have an arm64 version? 

ddev-solr does *not* require search_api_solr, it just explains how to use it. People use it (and ddev-drupal9-solr) with other CMSs completely.

**Comment by rfay** [comment]
If you're able to use a version of solr that has arm64 images you'll be able perhaps to make progress with that recipe, but I think the first one was solr:8, I'm not sure. There are ways you can run your docker provider in an emulation mode, and I can give more hints, but it sure isn't recommended, especially for a Java hog like solr.

**Comment by markabur** [comment]
OK, thanks. I really don't know anything about ARM or architectures or Docker providers or emulation mode or all of that. I just got a new machine and VirtualBox won't run on it so I'm tryng to find another way to get Solr running for this D7 site. I don't care how it happens but nothing I've tried has come close to working. I guess the main problem is search_api_solr as the d7 module only supports ancient versions of Solr that don't have an arm64 version. Ideally I'd be able to run some kind of Docker or ddev server that matches everything on Pantheon but I guess that would require me to be running the same kind of hardware as them. Thanks again for your help

**Comment by rfay** [comment]
Here are some resources to help you, but this is definitely a common problem when people get sparkling new Macs. Also, please make sure you've reinstalled homebrew in the right place. `which brew` should show /opt/homebrew/bin/brew` and `which ddev` should show it also in /opt/homebrew.

* [Primer on architectures](https://ddev.com//blog/arm64-apple-silicon-m1-ddev-local-what-does-it-all-mean/)
* [Running amd64 on an arm64 machine](https://ddev.com//blog/amd64-on-apple-silicon-ddev/)

Good luck on your quest. You do not need to have search_api_solr, but you do probably have to have a solr version that has an arm64 image. Images are at https://hub.docker.com/_/solr/tags

Closing, wishing you well.
