### ISSUE TITLE
Add README guideline, for example to streamline add-on titles

### ISSUE THREAD

**Issue by gitressa** [ddev/ddev#5641]
[Add-on](https://ddev.readthedocs.io/en/latest/users/extend/additional-services/) headers in their individual repos are either missing, they can be all capitals, or "What is this?"

It would be great to streamline the style, by following some simple guidelines, like the [Drupal README template](https://www.drupal.org/docs/develop/managing-a-drupalorg-theme-module-or-distribution-project/documenting-your-project/readmemd-template).

As a start, for a title template, I'd like to nominate the format from "DDEV Adminer Service" https://github.com/ddev/ddev-adminer using this format:

> # DDEV Service Name

So for example for [ddev-drupal9-solr](https://github.com/ddev/ddev-drupal9-solr), the header should be:

> # DDEV Drupal9 Solr

## Proposed solution

A brief README guideline section could be added under https://ddev.readthedocs.io/en/latest/developers/writing-style-guide/

**Comment by rfay** [comment]
I don't see any reason this shouldn't be done, but the best path is for you to do PRs in the various repos, which I think you've already started, thanks.

**Comment by gitressa** [comment]
Great, I created the MR #5673 for the [Writing Style Guide](https://ddev.readthedocs.io/en/latest/developers/writing-style-guide/).
