### ISSUE TITLE
v1.22.6 reports incorrect homebrew rosetta error: "You seem to be running under Rosetta, please install the ARM64 version of DDEV."

### ISSUE THREAD

**Issue by russback** [ddev/ddev#5643]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected Behavior

Should be able to upgrade to v1.22.6 without error.

### Actual Behavior

When upgrading from v1.22.5 to v1.22.6 I get this error:

`You seem to be running under Rosetta, please install the ARM64 version of DDEV. If you're using homebrew, you need to reinstall it properly, see https://brew.sh`

Downgrading to v1.22.5 enables me to poweroff and continue without errors:

`curl -fsSL https://ddev.com/install.sh | bash -s v1.22.5`

**Comment by stasadev** [comment]
Hi @russback,

Please provide output for `ddev debug test` (if you can't do it in v1.22.6, please do it in v1.22.5).

Also, what will be output for `uname -m` ?

**Comment by jonnykates** [comment]
I'm getting this same issue when upgrading to 1.22.6 on an M1. `unname -m` is `arm64`. Here's the output from `ddev debug test`;

```
Running bash [-c /var/folders/cc/wb93yvjs08n9nxlgrdzmhckm0000gn/T/test_ddev.sh] 
======= Existing project config =========
These config files were loaded for project boilerplate: [/Users/jonny/Code/williamjoseph/wj-craft4-boilerplate/.ddev/config.yaml]
name: boilerplate
type: craftcms
docroot: web
php_version: 8.2
webserver_type: nginx-fpm
webimage: ddev/ddev-webserver:v1.22.6
router_http_port: 80
router_https_port: 443
additional_hostnames: []
additional_fqdns: []
database: {mariadb 10.3}
project_tld: ddev.site
use_dns_when_possible: true
composer_version: 2
nodejs_version: 20
default_container_timeout: 120
======= Creating dummy project named  tryddevproject-22392 in ../tryddevproject-22392 =========
OS Information: Darwin Jonnys-MacBook-Air.local 22.6.0 Darwin Kernel Version 22.6.0: Wed Oct  4 21:25:40 PDT 2023; root:xnu-8796.141.3.701.17~4/RELEASE_ARM64_T8103 x86_64
ProductName:            macOS
ProductVersion:         13.6.1
BuildVersion:           22G313
User information: uid=501(jonny) gid=20(staff) groups=20(staff),12(everyone),61(localaccounts),79(_appserverusr),80(admin),81(_appserveradm),98(_lpadmin),701(com.apple.sharepoint.group.1),33(_appstore),100(_lpoperator),204(_developer),250(_analyticsusers),395(com.apple.access_ftp),398(com.apple.access_screensharing),399(com.apple.access_ssh),400(com.apple.access_remote_ae)
DDEV version:  ITEM             VALUE                                   
 DDEV version     v1.22.6                                 
 architecture     amd64                                   
 db               ddev/ddev-dbserver-mariadb-10.4:v1.22.6 
 ddev-ssh-agent   ddev/ddev-ssh-agent:v1.22.6             
 docker           24.0.7                                  
 docker-compose   v2.23.3                                 
 docker-platform  docker-desktop                          
 mutagen          0.17.2                                  
 os               darwin                                  
 router           ddev/ddev-traefik-router:v1.22.6        
 web              ddev/ddev-webserver:v1.22.6             
PROXY settings: HTTP_PROXY='' HTTPS_PROXY='' http_proxy='' NO_PROXY=''
======= DDEV global info =========
Global configuration:
instrumentation-opt-in=true
omit-containers=[]
performance-mode=none
router-bind-all-interfaces=false
internet-detection-timeout-ms=3000
disable-http2=false
use-letsencrypt=false
letsencrypt-email=
table-style=default
simple-formatting=false
use-hardened-images=false
fail-on-hook-fail=false
required-docker-compose-version=v2.23.3
use-docker-compose-from-path=false
project-tld=
xdebug-ide-location=
no-bind-mounts=false
router=traefik
wsl2-no-windows-hosts-mgt=false
router-http-port=80
router-https-port=443
mailpit-http-port=8025
mailpit-https-port=8026
traefik-monitor-port=10999

======= DOCKER info =========
docker location: lrwxr-xr-x  1 jonny  admin  54 Jul 18  2021 /usr/local/bin/docker -> /Applications/Docker.app/Contents/Resources/bin/docker
Docker Desktop Version: Docker Desktop for Mac 4.26.1 build 131620
docker version: 
Client:
 Cloud integration: v1.0.35+desktop.5
 Version:           24.0.7
 API version:       1.43
 Go version:        go1.20.10
 Git commit:        afdd53b
 Built:             Thu Oct 26 09:04:20 2023
 OS/Arch:           darwin/arm64
 Context:           default

Server: Docker Desktop 4.26.1 (131620)
 Engine:
  Version:          24.0.7
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.10
  Git commit:       311b9ff
  Built:            Thu Oct 26 09:08:15 2023
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.25
  GitCommit:        d8f198a4ed8892c764191ef7b3b06d8a2eeb5c7f
 runc:
  Version:          1.1.10
  GitCommit:        v1.1.10-0-g18a0cb0
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
DOCKER_DEFAULT_PLATFORM=notset
======= Mutagen Info =========
Mutagen is installed in ddev, version=0.17.2
Started Mutagen daemon in background (terminate with "mutagen daemon stop")     
--------------------------------------------------------------------------------
No synchronization sessions found
--------------------------------------------------------------------------------
======= Docker Info =========
Docker platform: docker-desktop 
Using Docker context: default (unix:///Users/jonny/.docker/run/docker.sock) 
docker-compose: v2.23.3 
Using DOCKER_HOST=unix:///Users/jonny/.docker/run/docker.sock 
Docker version: 24.0.7 
v1.22.6: Pulling from ddev/ddev-webserver
24563a412776: Pull complete 
Digest: sha256:72f73a814364a0ecb41bc10632b99e32a61afe53379f7a2d9269ab599079e25d
Status: Downloaded newer image for ddev/ddev-webserver:v1.22.6
docker.io/ddev/ddev-webserver:v1.22.6
Able to run simple container that mounts a volume. 
Able to use internet inside container. 
Docker disk space:
Filesystem                Size      Used Available Use% Mounted on
overlay                  31.3G     19.4G     10.3G  65% /

Unable to create project at project root '/Users/jonny/Code/williamjoseph/zpb-bame-covid': project root /Users/jonny/Code/williamjoseph/zpb-bame-covid does not exist
Stopped Mutagen daemon
The ddev-ssh-agent container has been removed. When you start it again you will have to use 'ddev auth ssh' to provide key authentication again.
Network ddev_default removed
Network ddev-boilerplate_default removed
Existing docker containers: 
CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES
Network ddev_default created 
Starting tryddevproject-22392... 
Network ddev-tryddevproject-22392_default created 
You seem to be running under Rosetta, please install the ARM64 version of DDEV. If you're using homebrew, you need to reinstall it properly, see https://brew.sh 
```

**Comment by stasadev** [comment]
Hi @jonnykates,

In version 1.22.6, a new check has been added to prevent DDEV amd64 from running on a machine with arm64 architecture (this can cause unexpected errors).

Please uninstall your DDEV (projects or their data will not be deleted) and reinstall it using the correct arm64 binary.

**Comment by rfay** [comment]
Hi @russback @jonnykates - I think you'll find that you brought your homebrew stuff over from your amd64 (Intel) machine. It doesn't work that way, you need to reinstall homebrew properly. 

You can easily check this - `which ddev` will show /usr/local/bin/ddev and `which brew` will show /usr/local/bin/brew. Those are the Intel versions of those commands. You're accidentally using them via Rosetta on your Apple Silicon machines.  You can also do `file $(which ddev)` and you'll see that it's the wrong architecture. 

There are a number of tutorials of how to fix this on the internet, but you'll need to remove your homebrew stuff from /usr/local and install it again with the instructions on https://brew.sh

**Comment by russback** [comment]
Hey @rfay.

This is a new M1 Mac and nothing's been copied over from a previous machine or backup.

Running `arch` shows `i386` and `brew doctor` does not report any architecture problems. I assume this be because the terminal (and iTerm) application has the `Open using Rosetta` option enabled. 

With that option *disabled*, `arch` shows `arm64` and `brew doctor` reports warnings including `Your Homebrew's prefix is not /opt/homebrew.`

With `Open using Rosetta` everything has worked fine until this release reported the architecture issue, so I'm guessing that `Open using Rosetta` is no longer viable for DDEV?

**Comment by jonnykates** [comment]
Similarly I haven't copied anything over from a previous environment. Running `file $(which ddev)` returns `/usr/local/bin/ddev: Mach-O 64-bit executable arm64`. I am running Zsh, I wonder if that has anything to do with it.

**Comment by rfay** [comment]
No, it wouldn't have anything to do with zsh.

@jonnykates you definitely have the wrong homebrew, it's showing /usr/local/bin/ddev; if properly insttalled on your mac it would be in /opt/homebrew/bin. 

Somehow you both seem to have installed the amd64 homebrew on your Apple Silicon macs. I recommend turning off Rosetta completely temporarily so you can get this sorted out.

**Comment by russback** [comment]
- Disabled Rosetta setting on terminal
- Uninstalled homebrew
- Installed homebrew
- Confirmed path now `/opt/homebrew`
- Installed ddev (now latest version)
- Confirmed works

Thanks guys

**Comment by rfay** [comment]
I think you'll be much happier with both performance and stability. It's amazing how much less work your nice new mac has to do now.

**Comment by raileanunalexandru** [comment]
> * Disabled Rosetta setting on terminal
> * Uninstalled homebrew
> * Installed homebrew
> * Confirmed path now `/opt/homebrew`
> * Installed ddev (now latest version)
> * Confirmed works
> 
> Thanks guys

Encountered the same issue, had to reinstall homebrew in order to correctly install ddev on an M2. Thank you!

**Comment by jenlampton** [comment]
I've uninstalled and reinstalled homebrew twice now, but `which brew` always outputs `/usr/local/bin/brew` :(

**Comment by rfay** [comment]
@jenlampton there is no arm64-specific installer... Just `/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"`

but please turn off Rosetta before continuing. 

And do just kill off /usr/local/Homebrew. 

But what does it say when you type `arch` ???

**Comment by jenlampton** [comment]
> but please turn off Rosetta before continuing.

I don't know what this means? I thought there was a per-app setting that allowed you to open something using rosetta. Is there something else? I googled "Open using Rosetta" but didn't find anything. 

> But what does it say when you type `arch` ???

It returns `arm64`.

**Comment by rfay** [comment]
Here's one writeup on how to uninstall Rosetta, https://iboysoft.com/news/uninstall-rosetta-2.html

You can always install it again when things get sorted out again.

**Comment by rfay** [comment]
You're on the right track to completely get rid of the old homebrew though:

There are [uninstall instructions](https://docs.brew.sh/FAQ#how-do-i-uninstall-homebrew) but in your situation I'd do what you were planning and

```
sudo rm -rf /usr/local/Homebrew
sudo rm /usr/local/bin/brew
```

Then I'd look in /usr/local/bin for other remnants of homebrew (`ls -l /usr/local/bin/*`) looking for things that point to /usr/local/Homebrew and get rid of them.

**Comment by martinsotirov** [comment]
I reinstalled Homebrew using @rfay 's suggestion and now I see `Rosetta 2: false` when I run `brew config` but ddev still complains
> You seem to be running under Rosetta, please install the ARM64 version of DDEV. If you're using homebrew, you need to reinstall it properly, see https://brew.sh

**Comment by rfay** [comment]
Hi @martinsotirov , I'll be happy to help you, but I imagine you still see the wrong binary with `file $(which ddev)`. Maybe you can show the output of `which -a ddev` and `file $(which ddev)`

If it doesn't show `/opt/homebrew/bin/ddev` then you're not using the brew-installed ARM64 brew binaries.

**Comment by martinsotirov** [comment]
> Hi [@martinsotirov](https://github.com/martinsotirov) , I'll be happy to help you, but I imagine you still see the wrong binary with `file $(which ddev)`. Maybe you can show the output of `which -a ddev` and `file $(which ddev)`

The -a flag of `which` did the trick. Apparently I had a local binary along with the Homebrew one and it had higher priority in the PATH. I deleted it and now it works properly. Thanks!
