### ISSUE TITLE
Typo in install/upgrade snippet for homeBrew

### ISSUE THREAD

**Issue by low-res** [ddev/ddev#5644]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Output of `ddev debug test`

<details><summary>homebrew snippet for macOS installation/ugrade is wrong</summary>

I just discovered a typo in DDEV installation and upgrade documentation.
The current snippet is:
`brew upgrade ddev/ddev/ddev`

but it must be
`brew upgrade drud/ddev/ddev`
</details>         

### Expected Behavior

Using the snippet should uprade ddev.

### Actual Behavior

Homebrew responses with the error message:

_Error: No available formula or cask with the name "ddev/ddev/ddev"._

### Steps To Reproduce

1. Go to https://ddev.readthedocs.io/en/stable/users/install/ddev-upgrade/
2. Look at maxOS homebrew snippet
3. try `brew upgrade ddev/ddev/ddev`

### Anything else?

The same typo can also be found in the installation instructions

**Comment by stasadev** [comment]
Hi @low-res,

There is no error, the command `brew upgrade ddev/ddev/ddev` is correct.

You should remove the old formula, and run `brew update && brew install ddev/ddev/ddev`

**Comment by low-res** [comment]
All right! Thanks for the clarification and sorry for the false alarm.

**Comment by stasadev** [comment]
No worries, closing.
