### ISSUE TITLE
Document how to run PHPUnit tests in Drupal

### ISSUE THREAD

**Issue by gitressa** [ddev/ddev#5646]
## Problem

Search for info on how to run PHPUnit test in Drupal with DDEV, and find a PHPStorm page:
https://presearch.com/search?q=site:ddev.readthedocs.io+phpunit
`>` https://ddev.readthedocs.io/en/latest/users/install/phpstorm/

Since you don't need PHPStorm to run PHPUnit tests, it could have its own separate section in the documentation.

## Proposed solution

Add a brief section in the documentation on how to install [DDEV Selenium Standalone Chrome](https://github.com/ddev/ddev-selenium-standalone-chrome):

> # PHPUnit with DDEV Selenium Standalone Chrome
> 
> [DDEV Selenium Standalone Chrome](https://github.com/ddev/ddev-selenium-standalone-chrome) has made it super easy to run PHPUnit tests in DDEV. Add the `drupal/core-dev` Composer package, and then run this::
> ```
> ddev get ddev/ddev-selenium-standalone-chrome
> ddev restart
> ```
> 
> Run a test like this:
> ```
> ddev exec -d /var/www/html/web "../vendor/bin/phpunit -v -c ./core/phpunit.xml.dist --group olivero"
> ```

A new sub section could be added on the https://ddev.readthedocs.io/en/latest/users/extend/additional-services/ page, or somewhere else?

**Comment by tyler36** [comment]
`ddev-selenium-standalone-chrome` is only required if you want to run functional javascript tests. 
It is not required for unit tests, kernel tests or functional tests.

I think setup and usage belongs on the `ddev-selenium-standalone-chrome` page. Perhaps a link to that page would be useful?

**Comment by gitressa** [comment]
Ok, but it looks to me like that, on top of Nightwatch tests, `ddev-selenium-standalone-chrome` also allows running PHPUnit tests, which can be complicated to set up ... I created https://github.com/ddev/ddev-drupal-contrib/issues/24 to make it clearer to me how the two are related.

**Comment by tyler36** [comment]
You are right. I always forget about Nightwatch tests, I so rarely encounter them.

**Comment by rfay** [comment]
I'm sure you already know about https://ddev.readthedocs.io/en/latest/users/install/phpstorm/#enabling-phpunit

However, I thought we already had a "CMS-Specific" section with something like this on Drupal PhpStorm. That said, this really isn't a DDEV topic. But it can go in the docs here if we can find a good place.

**Comment by rfay** [comment]
@gitressa you're welcome to document this and we'll be happy to advise here or elsewhere. Closing this for now. I think it probably belongs in the drupal.org docs but we can find a place for it here and it can also be in one of the add-ons.
