### ISSUE TITLE
Feature Request: start Docker automatically

### ISSUE THREAD

**Issue by macmladen** [ddev/ddev#5656]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

Not a problem _per se_ but an annoyance: if the docker is not running, ddev yells.

```
$ ddev start
ERRO[0000] app.FindContainerByType(web) failed 
ERRO[0000] app.FindContainerByType(web) failed 
Could not connect to a Docker provider. Please start or install a Docker provider.
For install help go to: https://ddev.readthedocs.io/en/latest/users/install/
```

### Describe your solution

DDEV could offer to start the docker:

```
$ ddev start
Could not find any docker provider running.
Do you wish me to start the configured docker provider [colima] [Y/n]
Starting the docker provider... Done.
Starting your_project...
...
```

**Comment by rfay** [comment]
DDEV can't start docker. It doesn't know what Docker you want to use. DDEV works the same on many different OSs and environments, and on macOS alone can work with at least 4 different Docker providers. Most Docker providers have a way to auto-start on reboot, what Docker provider are you using?

**Comment by rfay** [comment]
Happy to continue the conversation here or elsewhere if you have ideas, but I don't know how this could be done presently.
