### ISSUE TITLE
Period/dot in project `name` break web routing

### ISSUE THREAD

**Issue by timkelty** [ddev/ddev#5666]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Output of `ddev debug test`

<details><summary>Expand `ddev debug test` diagnostic information</summary>

```
======= Existing project config =========
These config files were loaded for project craftnet: [/Users/timkelty/Dev/craftnet/.ddev/config.yaml /Users/timkelty/Dev/craftnet/.ddev/config.local.yaml]
name: craftnet
type: craftcms
docroot: web
php_version: 8.1
webserver_type: nginx-fpm
webimage: ddev/ddev-webserver:v1.22.4
router_http_port: 80
router_https_port: 443
additional_hostnames: [id.craftnet api.craftnet composer.craftnet plugins.craftnet feeds.craftnet]
database: {postgres 15}
host_db_port: 32784
project_tld: ddev.site
use_dns_when_possible: true
composer_version: 2
nodejs_version: 16
default_container_timeout: 120
web_extra_exposed_ports: [{vite 8083 8084 8083} {storybook 6006 6007 6006}]
disable_upload_dirs_warning: true
======= Creating dummy project named  tryddevproject-32340 in ../tryddevproject-32340 =========
OS Information: Darwin tasha-mbp.local 23.2.0 Darwin Kernel Version 23.2.0: Wed Nov 15 21:53:18 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T6000 arm64
ProductName:		macOS
ProductVersion:		14.2.1
BuildVersion:		23C71
User information: uid=501(timkelty) gid=20(staff) groups=20(staff),12(everyone),61(localaccounts),79(_appserverusr),80(admin),81(_appserveradm),98(_lpadmin),333(piavpn),33(_appstore),100(_lpoperator),204(_developer),250(_analyticsusers),395(com.apple.access_ftp),398(com.apple.access_screensharing),399(com.apple.access_ssh),400(com.apple.access_remote_ae)
DDEV version:  ITEM             VALUE
 DDEV version     v1.22.4
 architecture     arm64
 db               ddev/ddev-dbserver-mariadb-10.4:v1.22.4
 ddev-ssh-agent   ddev/ddev-ssh-agent:v1.22.4
 docker           24.0.7
 docker-compose   v2.21.0
 docker-platform  orbstack
 mutagen          0.17.2
 os               darwin
 router           ddev/ddev-traefik-router:v1.22.4
 web              ddev/ddev-webserver:v1.22.4
PROXY settings: HTTP_PROXY='' HTTPS_PROXY='' http_proxy='' NO_PROXY=''
======= DDEV global info =========
Global configuration:
instrumentation-opt-in=true
omit-containers=[]
performance-mode=none
router-bind-all-interfaces=false
internet-detection-timeout-ms=3000
disable-http2=false
use-letsencrypt=false
letsencrypt-email=
table-style=default
simple-formatting=false
use-hardened-images=false
fail-on-hook-fail=false
required-docker-compose-version=v2.21.0
use-docker-compose-from-path=false
project-tld=
xdebug-ide-location=
no-bind-mounts=false
router=traefik
wsl2-no-windows-hosts-mgt=false
router-http-port=80
router-https-port=443
mailpit-http-port=8025
mailpit-https-port=8026
traefik-monitor-port=10999

======= DOCKER info =========
docker location: l
```
</details>         

### Expected Behavior

In `.ddev/config.yaml`:

```
name: a.myproject
additionalHostnames:
  - b.myproject
  - c.myproject
```

I expect `https://a.myproject.ddev.site` to work

### Actual Behavior

All web requests return `Bad Gateway`.

### Anything else?

There is no validation error if you put a dot/period in the project `name`, so I would expect this to work.

FWIW, rather than allowing this to work, I think a better approach would probably be do add validation to the `name`, and allow customizing the hostname independently of the project name, eg:

```
name: myproject
hostname: a.myproject
additional_hostnames:
  - b.myproject
```

**Comment by rfay** [comment]
I assume this is a regression with the traefik router, and it works ok with the nginx-proxy router? Could you test that please?

**Comment by timkelty** [comment]
@rfay right you are! Worked fine with `nginx-proxy`

**Comment by rfay** [comment]
The `additional_hostnames` in your example is irrelevant to the result, right? Please edit it out in that case.

**Comment by timkelty** [comment]
@rfay right - that was just related to the alternate suggestion of introducing an explicit `hostname` config, but it sounds like `name` is supposed to work with a dot.

**Comment by rfay** [comment]
Hmm, you have `hostname: a.myproject` - what is that about? That's not a  useful DDEV configuration... ???

You also have `additionalHostnames`, which is not valid. 


I guess you want this configuration, which works fine for me using the traefik router. 

```
name: a.myproject
additional_hostnames:
  - b.myproject
  - c.myproject
```

Please see https://ddev.readthedocs.io/en/latest/users/configuration/config/ for valid configuration options.

**Comment by timkelty** [comment]
@rfay forget the `hostname` bit – that was just me suggesting an alternative if `name` wasn't able to work with a dot.

> You also have additionalHostnames, which is not valid.

Sorry, just a typo in the issue.

> I guess you want this configuration, which works fine for me using the traefik router.

```
name: a.myproject
additional_hostnames:
  - b.myproject
  - c.myproject
 ```

Exactly. For me, it only works with nginx-proxy, with traefik I get `Bad Gateway`. If you say it is working for you I'll try it on some other test cases.

**Comment by rfay** [comment]
I have no trouble at all using traefik with that. Please try with a trivial project, maybe just an index.php that says hello world.

**Comment by rfay** [comment]
Oh, it's possible that https://github.com/ddev/ddev/pull/5647 could have affected this for craft. Please also try using latest DDEV.

**Comment by timkelty** [comment]
I reset everything and, reinstalled latest, and it seems to work now.

I was trying it by renaming an existing project, so that may have had something to do with it.
