### ISSUE TITLE
Skip mutagen sync when running ddev snapshot -a

### ISSUE THREAD

**Issue by ericdsd** [ddev/ddev#5671]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

When you have lots of projects and you want to run `ddev snapshot -a` every project is spawned sequentially and one of the longest part of it is generally the mutagen sync which seem useless in this context.

### Describe your solution

Prevent mutagen sync to be run when the command is ddev snapshot -a.

**Comment by rfay** [comment]
If you're having long mutagen sync times, there's probably something wrong with your projects. How long is the sync taking? You probably need to exclude some directories. Normally a second start of a project takes less than 10s to mutagen-sync.

**Comment by ericdsd** [comment]
Hi it actually seems to really depend on the machine's resources, for the same project on my m1 Pro with 16Gb it takes generally 5 to 15s, but on an older mac it's really much longer (which is not a surprise indeed). That's why i think it can be useful to avoid unneeded time consuming steps.

**Comment by rfay** [comment]
Unfortunately, start is required to do snapshot, so I think the complexity of your request would be quite high. And projects might be left running in an unstable mode.

**Comment by ericdsd** [comment]
Hi that's why i proposed to only do it for ddev snapshot -a which closes stops the vm directly, but of course i had no idea of the complexity of this change. Thanks anyway for your reply. Have a great year !

**Comment by rfay** [comment]
Thanks, yes, I think it has effects that are probably too broad for the benefit. 

However, you could make a script that did
`ddev config global --performance-mode=none && ddev snapshot -a && ddev config global --performance-mode=mutagen`

if you do this often and it's annoying. 

Closing for now, happy to continue the conversation here or elsewhere.
