### ISSUE TITLE
failed to pull image busybox:stable

### ISSUE THREAD

**Issue by keithdoyle9** [ddev/ddev#5680]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Output of `ddev debug test`

<details><summary>Expand `ddev debug test` diagnostic information</summary>

```
Running bash [-c /var/folders/pt/wgs8tvgd7m72dd1935hsy2b80000gn/T/test_ddev.sh]
======= Existing project config =========
These config files were loaded for project seic-enterprise: [/Users/kdoyle/Code/seic-enterprise/.ddev/config.yaml]
name: seic-enterprise
type: drupal9
docroot: docroot
php_version: 8.2
webserver_type: apache-fpm
webimage: ddev/ddev-webserver:v1.22.6
router_http_port: 80
router_https_port: 443
additional_hostnames: []
additional_fqdns: []
database: {mysql 5.7}
hooks: map[post-import-db:[map[exec:drush deploy]] post-start:[map[exec:acli auth:login --key $ACQUIA_API_KEY --secret $ACQUIA_API_SECRET -n] map[composer:install] map[exec-host:ddev auth ssh]]]
webimage_extra_packages: [make g++]
project_tld: ddev.site
use_dns_when_possible: true
composer_version: 2
nodejs_version: 18
default_container_timeout: 120
web_extra_exposed_ports: [{storybook 6006 9998 9999}]
======= Creating dummy project named  tryddevproject-15177 in ../tryddevproject-15177 =========


Please run 'ddev debug test' in the root of the existing project where you're having trouble.

Failed running test_ddev.sh: exit status 4
. You can run it manually with `curl -sL -O https://raw.githubusercontent.com/ddev/ddev/master/cmd/ddev/cmd/scripts/test_ddev.sh && bash test_ddev.sh`
```
</details>         

### Expected Behavior

Expected ddev to start up the containers

### Actual Behavior

Failed to start.

### Steps To Reproduce

1. Ran `ddev poweroff`, `ddev delete --omit-snapshot`
2. Delete all containers, volumes, images from Docker Desktop
3. Run `ddev start` in project folder

Initial error was on v1.22.5 so I upgraded to v1.22.6 and still have an issue. This is happening on both Mac and Windows.

**Comment by rfay** [comment]
Hi @keithdoyle9 - 

I can't understand what your issue is. The title is "Unable to pull" but you don't describe what's happening.

I see from `ddev debug test` that you're trying to do a very complex project, but I can't see what's actually happening.

Could you please just do a trivial Drupal project using https://ddev.readthedocs.io/en/latest/users/quickstart/#drupal and see how that goes? 

Then after you've done that, please give complete information about what happens with your problem. Are you having trouble pulling images?

**Comment by dgilbertsei** [comment]
This is the error we've been receiving; `Failed to RunSimpleContainer to inspect database version/type: failed to pull image busybox:stable: exit status 1, output=`

**Comment by keithdoyle9** [comment]
@rfay Here's the output from running a quickstart.

`/Code $ mkdir d10-site
~/Code $ cd d10-site
~/Code/d10-site $ ddev config --project-type=drupal10 --docroot=web --create-doc
root
Creating a new DDEV project config in the current directory (/Users/kdoyle/Code/d10-site)
Once completed, your configuration will be written to /Users/kdoyle/Code/d10-site/.ddev/config.yaml

Created docroot at /Users/kdoyle/Code/d10-site/web
You have specified a project type of 'drupal10' but no project of that type is found in /Users/kdoyle/Code/d10-site/web
Error response from daemon: Head "https://registry-1.docker.io/v2/library/busybox/manifests/stable": Get "https://auth.docker.io/token?account=kdoyle&scope=repository%3Alibrary%2Fbusybox%3Apull&service=registry.docker.io": EOF
Failed to RunSimpleContainer to inspect database version/type: failed to pull image busybox:stable: exit status 1, output=`

**Comment by keithdoyle9** [comment]
This is the response we get on multiple different networks (not just company network) when visiting the URL for the busybox image (https://registry-1.docker.io/v2/library/busybox/manifests/stable). 

Also looks to be similar to other users issues recently: https://forums.docker.com/t/401-unauthorized-error-on-performing-docker-pull-for-private-registry/139169

```
{
    "errors": [
        {
            "code": "UNAUTHORIZED",
            "message": "authentication required",
            "detail": [
                {
                    "Type": "repository",
                    "Class": "",
                    "Name": "library/busybox",
                    "Action": "pull"
                }
            ]
        }
    ]
}
```

**Comment by rfay** [comment]
`docker logout` usually solves this class of problem.

It's not a ddev problem, docker pull anything will fail.

**Comment by keithdoyle9** [comment]
Looks like that didn't help. Did a `docker logout` then deleted the ddev project and all images. Restarted Docker Desktop.

```
/Code/seic-enterprise master $ ddev debug refresh
Network ddev_default created
Network ddev-seic-enterprise_default created
Error response from daemon: Head "https://registry-1.docker.io/v2/library/busybox/manifests/stable": Get "https://auth.docker.io/token?scope=repository%3Alibrary%2Fbusybox%3Apull&service=registry.docker.io": EOF
Unable to pull Docker images: exit status 1
Error response from daemon: Get "https://registry-1.docker.io/v2/library/busybox/manifests/sha256:ba76950ac9eaa407512c9d859cea48114eeff8a6f12ebaa5d32ce79d4a017dd8": EOF
Failed to RunSimpleContainer to inspect database version/type: failed to pull image busybox:stable: exit status 1, output=
```

**Comment by keithdoyle9** [comment]
Just on a hunch, I tried enabling an experimental feature in Docker Desktop to use containerd for pulling and storing images. Everything worked after that. For reference, I'm on Docker Desktop v4.25.2

![image](https://github.com/ddev/ddev/assets/54675374/659114da-118a-4739-94e7-c4a9d99c7ff5)
