### ISSUE TITLE
Feature Request: Expand `ddev launch` to do full URL's

### ISSUE THREAD

**Issue by MakerTim** [ddev/ddev#5685]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

When using ddev launch it's only capable to do paths.

Now when i do commands like `drush uli` you cannot let the browser open the URL.
But inside WSL it uses `https://wslutiliti.es/wslu/` and that opens/uses the url. Then my one-time login has been opened by WSLU.
Then when wslu redirects its request to the host-browser the url is no longer valid.
I can imagen many more usecases where you want to open the browser from out the wsl environment, and ddev could be the winner for implementing it.

### Describe your solution

If we look into expanding `ddev launch [path]` into `ddev launch [url]` then we can use ddev to open the browser from scripts without editing the url in scripts.

### Describe alternatives

It currently works by editing the uli so it no longer contains the url but only the path
```ddev launch `drush uli | sed 's/.*\.\w*//'````` 

But that feels dirty :/
And doesn't work when you need services like solr

### Additional context

I think ddev uses still WSL open-browser / linux side of the host.
because ```ddev launch `drush uli | sed 's/.*\.\w*//'` ``` has the same issue that the URL is already visited
![image](https://github.com/ddev/ddev/assets/1375359/b449e41f-b08c-4f3a-b9da-b23612fefc75)

**Comment by rfay** [comment]
You seem to be talking about more than one thing here. 

`ddev drush uli` outputs a URL. In WSL2 you can click the URL with the `<ctrl>` key and it will open, at least if you're using WIndows Terminal and have link-clicking enabled (highly recommended). You can also use the `URI` part of the URL given to `ddev drush uli` in `ddev launch <drush-uri-part>`. 

`ddev launch` is just a shortcut to open any project. It's the same as pasting a URL into your browser. You can do that any time.  

Please edit your question and follow up to make it clearer and be specific about what you're asking.

`ddev launch` is just a [script](https://github.com/ddev/ddev/blob/master/pkg/ddevapp/global_dotddev_assets/commands/host/launch). You'll find it in ~/.ddev.commands/host/launch, and you can remove the `#ddev-generated` there and edit it as you see fit, and contribute back your solution. On WSL2, it uses `xdg-open` from `xdg-utils` to open a browser.

**Comment by MakerTim** [comment]
It is kinda related to https://github.com/wslutilities/wslu/issues/268

When you open a URL by wslu, it does a curl operation (to check for a valid url...) on the backgrond and then serve it to the browser on the Windows part

I hoped, but didnt check, that the launch script would have use workaround to launch my page into the browser without those issues.
but ddev is depending on wslu.

And i know you can click or copy manually, but as a lazy developer i hoped that i could fix my `ddev drush uli` issue by wrapping it in `ddev launch` for automagicly opening it into my browser
the not-browser opening is consistent on windows,mac,linux _because drush is wrapped in the docker container_ and does not open, like it used to do with php installed on my system.

**Comment by chrisfromredfin** [comment]
I just made a DDEV custom command for this, and I use `ddev login` instead of `ddev launch` - see https://github.com/redfinsolutions/ddev-commands/blob/main/commands/host/login
