### ISSUE TITLE
Add-on for easily turning on/off or tail-ing the db query log

### ISSUE THREAD

**Issue by apotek** [ddev/ddev#5689]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

When using ddev with a framework with a database abstraction layer, it can be finicky to set up being able to see the actual database queries generated by the application. 

### Describe your solution

A custom ddev command that allows a user to very very easily turn on or off query logging and optionally to tail that log. 

Due to the noisy nature of the db log output, it would be best to exclude it from the general `ddev logs` output.

- [X] I have contributed an add-on https://github.com/ChromaticHQ/ddev-dblog

### Describe alternatives

I considered adding configuration to the db container that would send all queries to the ddev logs. But I realized that would create a lot of noise, would slow down the application, and would make it difficult to toggle on and off. Looking at the db logs is generally something only necessary to do occasionally. 

### Additional context

I have written a command as described above and am using it successfully. I am posting this issue to see whether it would be considered generally worthwhile enough for it to be contributed to the ddev project as an included command.

**Comment by tyler36** [comment]
@apotek Thanks for the suggestion.

Might be worth posting the command here, or sharing a gist to it so people can have a play and give feedback.
If it's something you think you might use a lot, consider creating an addon. That makes it easier to install for anyone. 😄

**Comment by apotek** [comment]
> @apotek Thanks for the suggestion.
> 
> Might be worth posting the command here, or sharing a gist to it so people can have a play and give feedback. If it's something you think you might use a lot, consider creating an addon. That makes it easier to install for anyone. 😄

Hi @tyler36 and thank you for your reply. I just posted a merge request which should demonstrate the approach. I am curious about "creating an addon." I'll look into that.

I can in the meantime attempt to expand this script to include pgsql support as well (or just write another for that). But this should provide a starting point.

**Comment by tyler36** [comment]
You can find the template here: https://github.com/ddev/ddev-addon-template

EG. https://github.com/tyler36/ddev-vscode-devcontainer is a simple addon that adds a "code" command.

**Comment by jonaseberle** [comment]
I think that is a great idea and it helps me often when debugging. 

I've made this command some years ago: https://gist.github.com/jonaseberle/28a675d034dfa1dbaf8e586184fd1d77 but I've not come around to upstream it as a DDEV add-on. Please feel free to take from it what you find useful. I am happy to install the add-on from you then! :)

**Comment by apotek** [comment]
Hi @tyler36 and @jonaseberle ! Thank you for your suggestions. I have created a rough draft for this as an add-on. Once I get it to pass its initial tests, I'll post a link to it here. 

@jonaseberle I like a lot of the ideas in your script and may want to incorporate some of them while keeping the command light weight.
@tyler36 I agree also with you that it would be nice to make the command db-engine agnostic.

**Comment by apotek** [comment]
@tyler36 I have put up test-passing beta at https://github.com/ChromaticHQ/ddev-dblog and posted a feature request for postgres support here: https://github.com/ChromaticHQ/ddev-dblog/issues/1

@jonaseberle I have added a feature request to maybe implement some of your gist-ideas into the UX as the add-on matures. Thank you again for your suggestions: https://github.com/ChromaticHQ/ddev-dblog/issues/2

**Comment by jonaseberle** [comment]
Thanks, that works well.

I think we can close here and use `ddev get chromatichq/ddev-dblog` and `ddev dblog tail` :)

**Comment by rfay** [comment]
Yay, thanks!
