### ISSUE TITLE
On-demand user-generated files sync (upload_dirs)

### ISSUE THREAD

**Issue by Berdir** [ddev/ddev#5691]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

Syncing all files is often slow and quickly fills up local disk space.

Drupal has http://drupal.org/project/stage_file_proxy to solve this, but it's a drupal module, so you have to set up config split and similar solutions to handle that.

### Describe your solution

Add something that can automatically fetch missing files from an origin server as they are accessed.

I'm well aware that this isn't trivial, especially also with Drupal image styles where 404 responses are from the PHP application and I have no idea how feasible this is. But I've been thinking that this would be useful a few times and thought it doesn't hurt to create a feature request to discuss it.

**Comment by rfay** [comment]
Hmm, you didn't provide `ddev debug test` so I don't have any idea what OS or docker provider you're using. However, you're @Berdir so you know everything!

DDEV by default bind-mounts the directories named by `upload_dirs` so any project that specifies those (or has them by default, like the `drupal*` project types doesn't have the problem you're talking about. 

But say more please!

**Comment by Berdir** [comment]
Hi @rfay! Maybe I'm nissing something but I think that's not related to what I mean.

I'm talking about sync from my production environment as files are accessed by web requests. Have a look at what stage file proxy does.

**Comment by rfay** [comment]
I know stage file proxy well. I don't think it's part of DDEV's job to do that  but have you looked at ddev pull already?

**Comment by Berdir** [comment]
>  I don't think it's part of DDEV's job to do that

That's fair, if you think that's not something that ddev should cover then feel free to close this.

> have you looked at ddev pull already?

Sure, but if you have projects with dozens or hundreds of GB of files, then ddev pull is not feasible for multiple reasons. I almost always use --skip-files and live with the broken files, but sometimes they're useful/needed for certain tasks.

**Comment by rfay** [comment]
I don't think it's likely that DDEV itself could handle the gazillions of ways that people might access upstream files. stage_file_proxy adjusts the URL for files, which DDEV could never know how to do for all the things it works with.

**Comment by rfay** [comment]
It's possible that files pull could be extended to use sync where possible, but I doubt you'd be happy with performance of that. Stage file proxy is so great because it changes application behavior, not because it syncs 

Closing this for now, happy to continue the conversation.
