### ISSUE TITLE
Support a means to get "latest" database version

### ISSUE THREAD

**Issue by apotek** [ddev/ddev#5694]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

During `ddev config` it would be nice to be able to say `latest` instead of a specific version number. Like `drupal:latest`, or `--database=mariadb:latest`

This way, scripts and tests can stay in line with the latest images without having to be re-written, and a developer doesn't need to go look for a specific version number to use. 

Related, it would be nice if `--database=mariadb` would work, without a version number, in which case the default version would be installed. 

### Describe your solution

To always install the latest version of something (I am using database as an example only), specify `:latest` after the server type. 

        --database=mariadb:latest
        
To always install the default version of something, don't specify a version number at all. 

        --database=mariadb 

This would be useful for automated testing etc. 

### Additional context

A somewhat related issue: https://github.com/ddev/ddev/issues/5693

**Comment by rfay** [comment]
It's not entirely predictable when a database can be upgraded, which is why DDEV insists on specific config.

**Comment by rfay** [comment]
Mostly I can't see how this would work as currently expressed, although I can see why you're interested in it. Happy to continue the conversation here, or to have to expand on the idea and make it clearer and explain how it could work with real examples. Closing for now.

**Comment by apotek** [comment]
> Mostly I can't see how this would work as currently expressed, although I can see why you're interested in it. Happy to continue the conversation here, or to have to expand on the idea and make it clearer and explain how it could work with real examples. Closing for now.

I understand. I'll try to come back with a clearer formulation. 

I was writing this request based on standard docker containers, where most docker hub containers maintain a `latest` tag that is pointing to a versioned tag. Thus, for example, with redis, you can say `docker pull redis:latest` and always get the latest version. (See how they set up tags here https://hub.docker.com/_/redis/tags). Most official images do this, so I naively expected that the ddev containers would follow a similar convention. 

IOW, this isn't a feature request that should require much coding, but rather changes to how the containers are tagged. In the case of most official images <container_name> and <container_name:latest> do the same thing, with `:latest` just being a way to make it explicit. 

If that convention were to be followed, the only part of the original request that would require a bit of engineering would be the `:default` part, where there would have to be either a maintained lookup map to map `:default` to the default ddev version of that image or, maybe much easier to do, add a `:default` tag to the version of the container that is the default. 

Anyway, I'll think on this for a while and see if I can put together the framework in a better way.

**Comment by rfay** [comment]
I should note that `:latest` in Docker images is mostly a terrible thing. It means that behavior of an application can change over time with no explainable reason. Mostly it's recommended not to use it, even though it's the default if you don't provide a tag.

**Comment by apotek** [comment]
> I should note that `:latest` in Docker images is mostly a terrible thing. It means that behavior of an application can change over time with no explainable reason. Mostly it's recommended not to use it, even though it's the default if you don't provide a tag.

Ok. So this is "works as designed". Like you, I tend to be in favor of software pinning (when working on an long-lived project that people rely on). I concede, however, that it is less useful when using `ddev` as a test or prototyping bed and you just want latest Drupal/Symfony whatnot with latest everything and you have no legacy support to worry about. 

Thank you for the insights! 📕
