### ISSUE TITLE
Use php-profiler to improve xdebug and xhgui

### ISSUE THREAD

**Issue by tyler36** [ddev/ddev#5698]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

The current implementation is cause friction between xdebug and [ddev-xhgui ](https://github.com/tyler36/ddev-xhgui).

Originally posted in https://github.com/tyler36/ddev-xhgui/pull/18#issuecomment-1888002421 by @deviantintegral 

> The challenge with the current API (imposed by xdebug) is that when you call xdebug_disable(), you get the profiler data and no one else can. But, if we used the above package, we could add a class that keeps a reference to the return'ed data, and returns that instead of calling xdebug_disable().

### Describe your solution

Originally posted in https://github.com/tyler36/ddev-xhgui/pull/18#issuecomment-1888002421 by @deviantintegral 

> 1st xdebug_disable() call stores the reference to the returned data, stores it in a class property.
> By default, subsequent calls return that same data.
> If you call enable() again, we set the property back to [] or null or whatever.
> https://github.com/perftools/php-profiler/tree/main/src/Profilers

**Comment by rfay** [comment]
Looking forward to thinking this through. I'm quite sure we can figure something out that is simpler than what we're doing now.

**Comment by seebeen** [comment]
You can take a peek at my implementation - https://github.com/oblakstudio/ddev-xhgui-pro. Feel free to take anything you might need from it.

**Comment by rfay** [comment]
You have already accomplished this @tyler36 , true?

**Comment by tyler36** [comment]
Closing.

Yes, seems outdated now. Thank you for the nudge.
