### ISSUE TITLE
Add `-s, --service` argument to ddev launch

### ISSUE THREAD

**Issue by timkelty** [ddev/ddev#5700]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

Services often have their own web UIs, which are shown via `ddev describe`, but not available to `ddev launch`

### Describe your solution

Like `ddev exec`, it would be nice if one could do:

```
ddev launch -s minio
ddev launch -s mailpit # would be equivalent to `ddev launch -m`
```

**Comment by jonaseberle** [comment]
In my understanding the `--service` refers to a container which is part of a docker-compose project. docker-compose uses the word "service" for that. "mailpit" is currently not a service in that sense but merely a program that runs in the "web" container.

"launch" opens an URL.

A service does not necessarily have a URL. DDEV could check if it published any ports via the router (by looking into the `HTTP(S)_EXPOSE` env settings) and could theoretically launch the first one?
I think your wish is conceptually a bit difficult but I might overlook something.

Note: We have now a command `ddev mailpit` as alias for `ddev launch -m` (#5642)

**Comment by tyler36** [comment]
I'm working on PR #5525  that will allow you to use  `ddev port 3000` to open a specific port.
This will make custom commands and alias much easier to develop.

**Comment by timkelty** [comment]
Thanks for the clarification – in my case (ignoring my mailpit example), I _am_ trying to launch URL from a docker-compose service (defined by `HTTP(S)_EXPOSE`).

Sounds like this is by design, so for now I'll just do this by defining a separate custom command.

**Comment by rfay** [comment]
`ddev launch` has in fact been updated to take ports, for example, so `ddev launch :8037`, which gets you part of the way there.
