### ISSUE TITLE
RFC: CakePHP Project Type

### ISSUE THREAD

**Issue by ajibarra** [ddev/ddev#5713]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

No, it is not.

### Describe your solution

Since we mainly work with CakePHP projects and we use DDEV for all our local environments, from CakeDC we want to contribute to DDEV with a new project type for CakePHP that includes all the validations and tasks needed to configure a CakePHP project. We would also include a "cake" command for ddev to allow running cake tasks from outside.

### Describe alternatives

N/A

### Additional context

We would like to know if you would consider this project type and command to be integrated into DDEV so we spend the time implementing this and updating docs.

**Comment by rfay** [comment]
We would accept it. 

Only do it if the `php` project type is not meeting your needs.

Remember that you'll need to implement automated tests and that you'll be expected to maintain the integration over the long term. https://ddev.readthedocs.io/en/latest/developers/project-types/

Thanks for contributing!

**Comment by ajibarra** [comment]
Thanks for your quick response!

`php` project type works but of course it misses some of the automated tasks that we would be adding after importing database, configuring the project or even starting it. We are still defining which tasks we will run on each situation and then we will prepare the PR. 

About maintaining it, it totally makes sense so we would do it for sure.

**Comment by rfay** [comment]
As you consider working on it, think about whether a DDEV add-on that provides the extra commands or features would be easier to create an maintain.

**Comment by rfay** [comment]
Closing for now, this will require somebody to implement it using the instructions given and that's how it will go forward.
