### ISSUE TITLE
Allow changing password for db user

### ISSUE THREAD

**Issue by h1nds1ght** [ddev/ddev#5723]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

I have seen that there are several variables for the passwords of the root and db user inside the db container

```
MYSQL_PWD=db
MYSQL_ROOT_PASSWORD=root
MYSQL_PASSWORD=db
```

Would it be possible to read these variables from the `.ddev/.env` file, i.e. via

```
MYSQL_PASSWORD=db-changed
MYSQL_ROOT_PASSWORD=root-changed
```

and pass it to the `/healtcheck.sh` inside the db container?

While changing the root password currently works, changing the password of the db user seems to collide with the `/healthcheck.sh` of the db container, since the password is hardcoded

```
# If we can now access the server, we're healthy and ready
if  mysql --host=127.0.0.1 -udb -pdb --database=db -e "SHOW DATABASES LIKE 'db';" >/dev/null;  then
    printf "healthy"
    touch /tmp/healthy
    exit 0
fi
```

and the `.ddev/.env` file is not passed to the db container.

Of course i could create another user for this, but it would be more elegant to change the password of the existing db user only. 

### Describe your solution

- Include `.ddev/.env` in db container or source it in `/healtcheck.sh` from `/mnt/ddev_config/.env`
- Adjust `/healtcheck.sh` inside the db container to use the environment variable `MYSQL_PASSWORD`

**Comment by rfay** [comment]
Hi @h1nds1ght - thanks for opening this. 

DDEV's strategy has always been to keep the db user as simple as possible (named 'db', with password 'db' and host and database 'db'.  But at the same time, it gives you complete control just like you'd have on your own server, see https://ddev.readthedocs.io/en/latest/users/usage/database-management/#database-management

Can you say more about what you'd want to accomplish? Since you have complete control, you can already add users access, or grant the `db` user access to any database.

**Comment by rfay** [comment]
It's easy but undesirable to change the `db` user password, but since you have full control you can do it anyway. You can also add additional users. 

Closing since this can be done already and is fully under user control. Happy to continue the conversation here or elsehwere.

**Comment by h1nds1ght** [comment]
I am using ddev on a test development server for a drupal10 project and even there the user db:db would not fulfill the quite low security requirements, beside using hardened_images.

But I think overall it is the best idea to just create another user with a more secure password. For the moment I just create it on post start with credentials provided by .ddev/.env, included also in settings.local.php. 

At post-start I also change the root password. The only thing I noticed is a message at ddev start which might be a result of a hard coded root password somewhere in ddev:

> Unable to SET GLOBAL TRANSACTION ISOLATION LEVEL READ COMMITTED: composeCmd failed to run 'COMPOSE_PROJECT_NAME=ddev-some-project docker-compose -f /some/path/.ddev/.ddev-docker-compose-full.yaml exec -T db bash -c set -eu && ( mysql -uroot -proot -e "SET GLOBAL TRANSACTION ISOLATION LEVEL READ COMMITTED;" >/dev/null 2>&1)', action='[]', err='exit status 1', stdout='', stderr=''

Would be nice if you could have a look at this.

Beside this everything seems to work surprisingly good. 

Thank you for your work, makes life easier every day 😄

**Comment by rfay** [comment]
You'll note that the command in question is using `mysql -uroot -proot` - I imagine you changed the root password?

**Comment by h1nds1ght** [comment]
Yes thats the point of this issue. I want to use ddev on a test development server and therefore change at least the passwords.

For the db user I can just create a new user, but for the root user I need to change the password, otherwise it would be pointless.

**Comment by rfay** [comment]
Again, DDEV is designed for local development. You're using it for other things. I should note that database passwords are pretty much useless anyway (as all passwords are pretty much useless.)
