### ISSUE TITLE
Provide "Apache with mod-php" webserver type (formerly apache-cgi)

### ISSUE THREAD

**Issue by GuySartorelli** [ddev/ddev#5725]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

Yes!
I'm a maintainer of Silverstripe CMS, and need to be able to test if things work in Apache without fpm. Currently I have to set up a custom container to handle that.

Notably, Apache running without fpm seems to use HTTP 1.x, while it uses HTTP 2.x with fpm - and that difference does sometimes result in edge cases causing problems.

### Describe your solution

Add `apache` (could be `apache-no-fpm` if you want to be super clear about it) to the `--webserver-type` options with the config command.

**Comment by rfay** [comment]
Are you talking about Apache with mod_php? We removed that feature many years ago because it wasn't used.

**Comment by GuySartorelli** [comment]
Yup that's what I meant. Though I guess if it was intentionally removed then probably I'll just need to modify the docker images to suit my needs.

**Comment by rfay** [comment]
I think it should be a pretty straightforward add-on. 

* Remove fpm from supervisord (although that's not critical, it doesn't do any harm)
* Enable mod_php
* Add new apache-site.conf

**Comment by rfay** [comment]
I did a little fiddling with this and
```
webimage_extra_packages:
  - libapache2-mod-php${DDEV_PHP_VERSION}
```


Along with `sudo a2enmod php${DDEV_PHP_VERSION}`

got me a lot of the way there. There was still the tiniest bit of fiddling with the apache2.conf


I was devastated by how slow it was. I suspect this was another reason for its removal.

**Comment by GuySartorelli** [comment]
Sweet, thanks. I'll slap something together along those lines next time I need to test something with mod-php then.

**Comment by rfay** [comment]
I would definitely love to hear what you come up with. Just every once in a while this is important to somebody. It should be pretty easy to do an add-on that just changes the behavior of apache-ftp to mod-fpm behavior.
