### ISSUE TITLE
Provide an Add-on to enable and disable Twig debugging in Drupal

### ISSUE THREAD

**Issue by mlncn** [ddev/ddev#5729]
### Is there an existing issue for this?

- [X] I have searched the existing issues

(also searched web for "ddev one command to turn twig debugging on off" :grin: )

### Is your feature request related to a problem?

It would save even our small tech collective a combined total of a dozen hours a year to have a single command for turning twig debugging on and off.

### Describe your solution

`ddev twig-debug on`
`ddev twig-debug off`

I know this wouldn't live in DDEV itself but would be a add-on.

If there is no `/sites/default/services.yml` file, create it with just enough configuration to enable twig debugging:

```yaml
parameters:
  twig.config:
    debug: true
```

  Or maybe that would be a special file like `/sites/default/twig_debug.services.yml` that is then included explicitly if it exists from settings.ddev.php.  Then it can be created or deleted without any fear.

### Describe alternatives

A shell script of some kind, which is probably what this DDEV plugin would be running, but the value in `ddev get cool-new-twig-debug-plugin` and then `ddev twig-debug on` as standardized for every project is what would be so valuable.

### Additional context

We at [Agaric](https://agaric.coop/) (ok really @wolcen) could (help) maintain this plugin, but we would love for the architecture to be

**Comment by rfay** [comment]
Add-ons are so easy! Your steps would be:
1. Create a custom command named `twig` that does what you want. Or maybe you'll want something else. Get it working the way you want.
2. Create an add-on that installs it, either globally or as a project custom command.
Anybody can create an add-on. 

https://ddev.readthedocs.io/en/latest/users/extend/additional-services/#additional-service-configurations-add-ons

Thanks so much for contibuting, raising this, and the good thinking, and of course thanks for your sponsorship of the project.

**Comment by chrisfromredfin** [comment]
Just pointing out that Drush now supports this natively (we had a custom ddev command to do it up to this point).

https://www.drush.org/12.1.3/commands/twig_debug/

**Comment by rfay** [comment]
It sounds like the drush path forward is the best, but happy to help you with an add-on if you want to go that way. It's amazingly easy.

**Comment by chrisfromredfin** [comment]
@mlncn BTW we implemented this before Drush supported it.

https://github.com/redfinsolutions/ddev-commands/blob/main/commands/web/tdebug
