### ISSUE TITLE
Linux: autocompletions should not be added in /usr/bin for deb and rpm

### ISSUE THREAD

**Issue by stasadev** [ddev/ddev#5734]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Output of `ddev debug test`

<details><summary>Expand `ddev debug test` diagnostic information</summary>

```
[COPY-PASTE HERE THE OUTPUT OF `ddev debug test`]
```
</details>         

### Expected Behavior

The autocomplete scripts are already installed in `/usr/share`, where they belong.
`/usr/bin` for executables only.

### Actual Behavior

 `ddev_bash_completion.sh`, `ddev_fish_completion.sh` and `ddev_zsh_completion.sh` are added to `/usr/bin` folder for deb and rpm packages, and they are all executable, which adds to the confusion when trying to autocomplete `ddev` in your console.

See:
- https://pkg.ddev.com/deb:ddev/-/content/usr/bin
- https://pkg.ddev.com/rpm:ddev/-/content/usr/bin

### Steps To Reproduce

1. Use Linux (or WSL2).
2. Type `ddev<TAB><TAB>` in console
3. See

```
$ ddev
ddev                     ddev_bash_completion.sh  ddev_zsh_completion.sh
ddev.link                ddev_fish_completion.sh
```

### Anything else?

Noticed this in:
- https://github.com/ddev/ddev/pull/5701#discussion_r1463720177

**Comment by rfay** [comment]
Is this a problem with goreleaser?

**Comment by stasadev** [comment]
Yes, goreleaser builds all binaries for `apt` and `rpm` without filtering.

I believe #5759 might fix it, but I don't know how to test it.
