### ISSUE TITLE
Update Drupal10 to use PHP8.2

### ISSUE THREAD

**Issue by karenmurky** [ddev/ddev#5735]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

When setting up a new Drupal 10.2 installation (using the Commerce kickstart distribution) it comes bundled with commerce_authnet, which has a dependency that requires PHP 8.2. 
The stable release of PHP is now 8.2.6, so seems logical to update drupal10 to use PHP82

### Describe your solution

Change from PHP81 to PHP82

**Comment by tyler36** [comment]
I just followed the [DDEV Drupal 10 quickstart guide](https://ddev.readthedocs.io/en/latest/users/quickstart/#drupal).
It resulted in a Drupal `10.2.2` website with PHP `8.1.26`. So it's _not_ a requirement for vanilla Drupal.

[Drupal.org](https://www.drupal.org/docs/getting-started/system-requirements/overview#s-php) says:

> [Drupal 10 requires at least PHP 8.1](https://www.drupal.org/node/3264830). [PHP 8.1.6 is recommended.](https://www.drupal.org/node/3295061)

However, the status page suggest `8.2` as the recommended version:

![image](https://github.com/ddev/ddev/assets/7234392/3757b88a-d095-4c03-bb88-00b1f51b5981)

According to https://www.php.net/supported-versions.php.

- PHP `8.1` has active support until 25 Nov 2023 (2 months ago)
- PHP `8.2` has active support until 8 Dec 2024.
