### ISSUE TITLE
Automatically install bee with the Backdrop CMS recipe (along with or instead of drush)

### ISSUE THREAD

**Issue by klonos** [ddev/ddev#5740]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

Recent versions of Backdrop CMS support up to and including PHP 8.2, however the development of drush v8 (the latest version of drush that supports Drupal 7 and Backdrop) has stopped and it cannot run in PHP 8.x:

```
ddev drush st
Undefined array key "description" command.inc:1308                     [warning]
Undefined array key "description" command.inc:1308                     [warning]
Undefined array key "description" command.inc:1308                     [warning]
Undefined array key "description" command.inc:1308                     [warning]
Undefined array key "description" command.inc:1308                     [warning]
Undefined array key "description" command.inc:1308                     [warning]
Undefined array key "description" command.inc:1308                     [warning]
Undefined array key "description" command.inc:1308                     [warning]
Undefined array key "description" command.inc:1308                     [warning]
Undefined array key "description" command.inc:1308                     [warning]
Undefined array key "description" command.inc:1308                     [warning]
Undefined array key "description" command.inc:1308                     [warning]

PDOException: SQLSTATE[HY093]: Invalid parameter number: number of bound
variables does not match number of tokens: SELECT name FROM {system} WHERE
type='module' AND status=1; Array
(
    [:type] => module
    [:status] => 1
)
 in drush_db_select() (line 131 of phar:///usr/local/bin/drush8/includes/dbtng.inc).

Drush command terminated abnormally due to an unrecoverable error.       [error]
Failed to run drush st: exit status 1
```

### Describe your solution

The Backdrop CMS community has for some time now shifted efforts towards https://github.com/backdrop-contrib/bee as its official command line tool instead of the drush extension (https://github.com/backdrop-contrib/backdrop-drush-extension), which is tested and actively maintained. DDEV instances for Backdrop CMS should have bee installed and working with `ddev bee` out of the box.

**Comment by klonos** [comment]
I have personally been a long-term Lando user, but have recently switched to DDEV + Rancher Desktop. I've been using bee in Lando with the following tooling:

```yml
...

services:
  appserver:
    extras:
      - wget -qO bee.zip https://github.com/backdrop-contrib/bee/archive/1.x-1.x.zip
      - unzip -q bee.zip && rm bee.zip
      - mv bee-1.x-1.x /usr/local/bin/bee

...
```

**Comment by stpaultim** [comment]
I would also be interested in this.

**Comment by rfay** [comment]
So glad to see you Backdrop folks here! It's been a long time since there was any interaction with the Backdrop support.

I would be fine with adding bee support directly to DDEV, but @tyler36 is certainly right that if you do it as an add-on, it's super easy to maintain independently from DDEV, and of course you can do with it what you want.

Does bee install in the project or globally?

**Comment by laryn** [comment]
Here's how I've been doing it, but I'd certainly support it being there by default:

https://github.com/backdrop-contrib/bee/wiki/Using-bee-with-DDEV

**Comment by klonos** [comment]
> So glad to see you Backdrop folks here! ...

Thanks @rfay 😄 ...personally, I started using Lando way back when merely because @serundeputy who has been one of our core committers was working at Kalamuna (the creators of Lando), so there was easy access to "internal" knowledge and quick support to bugs and questions etc. ...I've been meaning to switch to DDEV for a few years now, but all my local scripts and automation was using lando, and besides, lando itself didn't really give me any reason to switch.

Lando and DDEV are both awesome tools that provide great ease to the open source community, and they are both free to use, so I am equally grateful to the people behind them 🙏🏼 ❤️  ...both have their pros and cons I imagine, but for a person like me, the tool is not the purpose nor the end goal - I just want to be able to make contributions hustle-free. The tipping point for the switch in my case was plain lack of progress in https://github.com/lando/lando/issues/3388 for years, and the fact that I really have been wanting to move away from Docker Desktop mainly for ethics.

> Does bee install in the project or globally?

I believe that both are supported, but my scripts/automation have been installing it on each local project specifically. There was no reason for me to run it globally, as I have only been using container-based local instances. (I hope I understood your question correctly and that my answer makes sense)

> I would suggest creating a DDEV addon ...

That's definitely an interesting option @tyler36 👍🏼 ...I haven't gotten that far in my doc-reading yet, so thanks for pointing it out 🙏🏼  ...however, I would love it if there was a `ddev bee` command provided out of the box, same as I see support for `ddev drush` /`ddev wp` /`ddev typo3` / `ddev magento` in https://ddev.readthedocs.io/en/latest/users/usage/commands.

And finally, thanks @laryn 🙏🏼 ...I was only looking at what was available in the README for bee, and failed to notice that the wiki was enabled for the GitHUb repo. Cheers!

**Comment by tyler36** [comment]
Yes, a `ddev bee` command OOTB would be ideal in the long run.
An addon will let you develop and share a working solution while you playing with implementation. 

There are lots of friendly folk happy to help if you have problem (check out our [Discord ](https://discord.gg/5wjP76mBJD))

**Comment by Wylbur** [comment]
I'll add an additional consideration, comparing Drupal 10 and Drush, and Backdrop and Bee.  

Drupal 8/9/10 are composer driven projects, with modules and Drush installed via composer.  Instead of packaging Drush within the docker images it is installed with the project, and goes on to be used in the servers as part of the installed project.  Like Drupal, Drush requires installation via composer and installs outside dependencies as part of the install process.  

For Backdrop CMS, we have a very different approach.   We don't use composer, and modules and themes are complete packages onto themselves.  Our goal is to lower the install requirements to make the project as accessible as possible.  We are targeting non-developers who want to build websites.  The Bee installation reflects that approach.  Like Backdrop itself, Bee installation does not require additional libraries and dependencies or a composer installation. 

Given this, it would be great for our project to be able to offer our prospective users a 'complete' solution.  Without a need to learn DDev AND also how to install addons or additional tooling scripts.   

I also use the tooling mentioned by @klonos above.  It packages everything to make a seamless installation, but I'm an advanced user.  We'd like to remove that obstacle for the new adopters of our project.  

Thanks for your attention to our project, we really appreciate your help and your incredible tools!

**Comment by dstorozhuk** [comment]
I also vote for direct integration of the Bee with ddev. 
Apart from that, it would be right to remove the drush integration from  backdrop project or alias the drush command to bee??. Or add the message saying that drush does not work Backdrop as expected and it is usable is deprecated. 

I created the issue to deprecate the backdrop-drush-extension and provided some argumentation:
https://github.com/backdrop-contrib/backdrop-drush-extension/issues/262

**Comment by omega8cc** [comment]
Just a note that we maintain Drush 8 fork which supports PHP 8.2 and we even use it to maintain Drupal 10 sites in Aegir. Even more importantly we aim to add Backdrop CMS support in Aegir and even replace Aegir admin interface with Backdrop, so deeper integration with Drush 8 is being worked on.

**Comment by jenlampton** [comment]
I'd also like to add a vote for ddev to have `bee` support when you set up a fbackdrop project, but it would also be great if we could have (or keep) the Drush 8 option available too, since people have different preferences. 

@omega8cc I'm looking forward to deeper Backdrop Drush 8 integration, as I have a handful of D7 site that use Drush heavily, and it will take some time to get them all switched over to bee.

**Comment by rfay** [comment]
It's so very easy to create an add-on, please do it! You might want to create a ddev-backdrop add-on which would have the potential to do more than just install bee in the future. 

It will take less than a half hour to do it :) https://github.com/ddev/ddev-addon-template

**Comment by laryn** [comment]
@rfay Is the idea we could create a Backdrop addon and then it would get transferred into the ddev library as an "official" add on that is automatically added in the Backdrop recipe when approved?

**Comment by rfay** [comment]
The first step is to make it work the way you want it to work. (Just add a .ddev/web-build/Dockerfile.backdrop that installs bee, and perhaps a `bee` custom web command that gets installed). 

Next step when you like it and can commit to maintaining it would be to make it "official", which is fine. (Any really useful add-on with a committed maintainer can be promoted). 

The great thing about an add-on is that you can maintain it as needed, add features, etc, without being tied to DDEV's release schedule or using Golang. 

But when you have it the way you like it and people are successful with it and you really think it should go into DDEV, a PR will be welcome there.

**Comment by Wylbur** [comment]
Randy, go ahead and assign this ticket to me, I will get the initial add-on up and running.

**Comment by rfay** [comment]
You're on, thanks!

**Comment by rfay** [comment]
Closing for now, Backdrop community can pursue. And add-on is super easy, and it can proceed from there.

**Comment by jenlampton** [comment]
@Wylbur  can you add a link here when there is an add-on ready for testing? I'd love to help with QA :)

**Comment by jenlampton** [comment]
I have created an addon, it is located at https://github.com/jenlampton/ddev-backdrop-bee. 

It works! 

All you need to do is:
1. Install this addon with `ddev get jenlampton/ddev-backdrop-bee`.
2. Restart DDEV with `ddev restart`.
3. Test bee by running `ddev bee status`.

The bats tests are failing. Unfortunately, I don't know anything about bats tests so I'm not sure I have the time to get to the bottom of why step 3 (above) fails in the tests, when it works in reality. If anyone wants to make a PR against my project, I would appreciate it :D

**Comment by rfay** [comment]
Awesome!

Your test from release is looking at the wrong thing, still pointing to the template,
```
@test "install from release" {
  set -eu -o pipefail
  cd ${TESTDIR} || ( printf "unable to cd to ${TESTDIR}\n" && exit 1 )
  echo "# ddev get ddev/ddev-addon-template with project ${PROJNAME} in ${TESTDIR} ($(pwd))" >&3
  ddev get ddev/ddev-addon-template
  ddev restart >/dev/null
  health_checks
}

```

You'll see in the test output:

```
ok 1 install from directory
# ddev get ddev/ddev-addon-template with project test-addon-template in /home/runner/tmp/test-addon-template (/home/runner/tmp/test-addon-template)
not ok 2 install from release
```

So that's why...

**Comment by jenlampton** [comment]
Thanks @rfay  and @tyler36 for the assistance, I have made the first "official" 1.0.0 release :D

**Comment by jenlampton** [comment]
Since the command has updated (and this is a top search result) adding the new command here for installing bee:

`ddev add-on get backdrop-ops/ddev-backdrop-bee`
