### ISSUE TITLE
Could DDEV_APPROOT be exposed to container scripts?

### ISSUE THREAD

**Issue by BernhardBaumrock** [ddev/ddev#5748]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

I'm maintaining a module for the ProcessWire CMS and there we have TracyDebugger which adds clickable links to backtrace logs and dumps, which is great.

For that to work we need a config like this:

```php
// tracy config for ddev development
$config->tracy = [
  'localRootPath' => '/local/path/to/project/',
];
```

I'd like to set that `localRootPath` automatically. I'm working on many projects and this is one last thing that is still not automated.

For the project name I can use this:

```php
$defaulthost = getenv('DDEV_PROJECT')
  ? getenv('DDEV_PROJECT') . ".ddev.site"
  : "example.com";
```

This is great, but unfortunately the `DDEV_APPROOT` is not set.

### Describe your solution

I'd wish I could just do this:

```php
// tracy config for ddev development
$config->tracy = [
  'localRootPath' => getenv('DDEV_APPROOT'),
];
```

### Describe alternatives

The alternative is to do that manually, but it's tedious and error prone. I have to `pwd` the directory, copy it, paste it, make sure that I don't/do have trailing slash (and I always forget)...

### Additional context

Thank you very much for your support and for the great tool!

**Comment by rfay** [comment]
The project root is always /var//www/html, it would be pretty easy for this to be set though.

**Comment by BernhardBaumrock** [comment]
Hey @rfay  Yeah it's `/var/www/html` inside the container, but I need the path on the local file system of the host machine, eg `/Users/bernhard/projects/example.com`.

I can get the hostname `example.com` with `DDEV_PROJECT` but I can't get the full host machine docroot.

**Comment by rfay** [comment]
`$DDEV_APPROOT` is the full path of the project on the host side. It doesn't make any sense to expose that inside the container, I don't think. 

I would be fine with DDEV_APPROOT always being /var/www/html inside the web container, which is super easy to do. 

But I don't think you want the current DDEV_APPROOT being exposed inside the container, which knows nothing (and should know nothing) about the structure of the host filesystem.

**Comment by BernhardBaumrock** [comment]
Hey @rfay thx for your message!

I'm really sad about it being a little ignorant though :( Just because you don't have a need for it (or don't see it yet) does not mean it does not make any sense.

Also I don't understand what you are saying here, as this makes no sense to me:

> I would be fine with DDEV_APPROOT always being /var/www/html inside the web container, which is super easy to do.

So I really wonder if you understood my request!

I'll try to explain again:

Example 1) Using Tracy Debugger throwing exceptions (https://tracy.nette.org/en/)

Have a look at this screenshot. This is how Tracy Debugger shows debugging info when exceptions occur:

<img width="1319" alt="image" src="https://github.com/ddev/ddev/assets/8488586/a762a204-0dd5-4bfb-87ac-616c88768143">

See the two red arrows? These are links to the files that caused the error! The links have a link like this: `vscode://file/path/to/file:123` which causes VSCode to open up and directly open /path/to/file and jump to line 123 of that file. That super awesome - but it only works if those links point to the LOCAL filepath (eg /Users/bernhard/project/file) and NOT to the internal path (like /var/www/html).

Example 2) Dumping Variables

<img width="656" alt="image" src="https://github.com/ddev/ddev/assets/8488586/d83c906f-9018-4736-b0ab-36dc2c7e23b4">

This is how it looks like when dumping any variable to the debug bar. In the example it's just a string, but it can also be complex types like objects or nested arrays etc.; In the example I've added `bd("Demo for Randy!");` to my /site/ready.php

In bubble 1 you see that this code lives at `vscode://file/Users/bernhard/baumrock/magiclayouts/site/ready.php:19` and when clicking that link it opens vscode for me. In bubble 2 you see that it lives at `/var/www/html/site/ready.php` inside the container, but this path is useless for this scenario.

Example 3) ALFRED links for easier frontend development

That's a feature that I (and many others that use my open source module) use all the time:

![image](https://github.com/ddev/ddev/assets/8488586/e6b8b4a3-05fb-4f30-837d-9150cb3984c6)

https://www.baumrock.com/en/processwire/modules/rockfrontend/docs/alfred/#easier-development

See bubble 2? Whenever I click on that Icon it opens up VSCode and I instantly know where the markup of that section of my website is coming from! For my daily work that makes a lot of sense, so it would be an absolutely logical step to get those links from a variable rather than having to define it for every project manually over and over again (and change it if you move your project).

You can see it in action here - the link takes you directly to the part we are talking about and you only have to watch for < 3minutes. And it even shows the problem that would not exist if we had that feature in DDEV, namely that I need to go to a config, enter the correct path, etc... Sure, not a big deal, but I don't see why it would be a big deal to add this to DDEV and that's just 3 examples where it would be helpful for me - I'm quite sure there are others that would benefit from it as well.

https://youtu.be/7CoIj--u4ps?si=mLC79BgDtZINNRnH&t=1954

Thx for reconsidering!

**Comment by jonaseberle** [comment]
What's in `$customHOST_DDEV_APPROOT` on a Windows host if you try my suggestion?

**Comment by BernhardBaumrock** [comment]
Sorry @jonaseberle I didn't mean to ignore you. I thought I've already answered, but seems my post got lost or never sent...

> While a full host root path is not available in DDEV containers, you could add a .ddev/docker-compose.host-ddev-approot.yaml with this content:

Thx for the suggestion! But that would not help, because I'd need to do that for every project and it would be more work than just adding it to my config.php - or am I missing something?

**Comment by rfay** [comment]
From your screenshots it looks like Tracy is doing just fine with relative paths, and you have a problem with vscode configuration that doesn't have to do with DDEV_APPROOT or anything.

(Sidenote, no need to respond... I'm sure you know that Xdebug is the standard in the PHP world and has enormous support in every corner. It's worth it to use it just because it's so widely supported.)

But AFAICT you have a configuration problem with vscode or perhaps with Tracy. This is a completely normal situation, having different path roots on the host vs container, maybe you should contact tracy for help?

Note that you can easily add an environment variable with `web_environment` to accomplish this:
```yaml
web_environment:
  - DDEV_APPROOT=$DDEV_APPROOT
```

If you're on WSL2, are you running the IDE in WSL2 or on the Windows side? If you're running it on the Windows side, none of this will help you anyway because your code will be in `\\Linux\Ubuntu\home\you\...`, which isn't related to the DDEV_APPROOT

**Comment by rfay** [comment]
Closing this, since the solution is so easy, but happy to continue the conversation here or elsewhere.

**Comment by BernhardBaumrock** [comment]
@rfay I don't have a configuration problem. I don't have a problem at all, I was just asking for DDEV to make a little change that makes my life easier. Not more, not less.

Your response sounds like you still don't understand.

![image](https://github.com/ddev/ddev/assets/8488586/33bb33f4-ec32-40dc-877e-4a2183cbf25b)

This screenshot shows the working solution. It works, because I have set the path of the first bubble manually in my project's config.php

I have to do that manually. On every project. On every move of the folder. On every device. Of any developer.

Not a huge deal. But inconvenient and I thought it would be very easy to just add that env to the container, so that I can do this in my code and it will work for any project, for any device, for any developer on the team:

```php
$config->tracy['localRootPath' => getenv('DDEV_APPROOT')];
```

Instead of this:

```php
$config->tracy['localRootPath' => '/home/users/bernhard/whatever'];
```

Note that the second version has to be done by any developer. The suggestion of adding `web_environment:  - DDEV_APPROOT=$DDEV_APPROOT` to the config does solve that though. But it does not solve the problem that I have to add that to every single project over and over again. But I just had the idea to add that to my ddev config alias, so I don't need to think of that any more.

So I have a solution for myself and I'm happy and thankful for that. Still don't understand the problem of adding it globally, but maybe I'm not seeing any complications that may arise with adding it to ddev, who knows.

Thx.

**Comment by rfay** [comment]
I would set DDEV_APPROOT to `/var/www/html` if implementing the original request, because that's the project root inside the container.

**Comment by BernhardBaumrock** [comment]
@rfay yeah, you totally got me wrong. Really. That does not help at all and that is not the problem that I'm describing. :(

**Comment by rfay** [comment]
Have you tried `$config->tracy['localRootPath' => '.'];` to use a relative path?

I still think this is a configuration problem on the host side.

**Comment by BernhardBaumrock** [comment]
Thx @rfay but Tracy really needs the path of the host. That's my point. It needs /users/bernhard/project/file.php not /var/www/html/file.php

**Comment by BernhardBaumrock** [comment]
So the technical workflow is this:

```
1) CMS/TracyDebugger creates links to edit the files --> vscode://file/...
I open the website in a browser
I click on the link
MacOS sees the link and interprets href="vscode://..." and tries to find that file on the OS
If MacOS finds that link (which is only the case for /users/bernhard... and not /var/www/html...) then it opens VSCode
```

Step 1) is the problem. CMS/Tracy don't know where the project is stored on the host system. I need to tell it manually. Every time on every project.

**Comment by rfay** [comment]
`web_environment` is also available in the DDEV global config. 

I think you can solve every single thing with this one action:

```
ddev config global --web-environment-add='TRACY_APPROOT=$DDEV_APPROOT'
```

Then use $TRACY_APPROOT.

It still looks like naive vscode configuration though. Probably something to take up with the Tracy project.

**Comment by BernhardBaumrock** [comment]
@rfay That would work for me, but it would not work for my team members that checkout the same project. Really. I don't get it.

It's not related to TracyDebugger as well. I told you that I'm having the same problem with my RockFrontend module: https://github.com/baumrock/RockFrontend

Any application that wants to provide links that could be opened in VSCode/Cursor/Sublime/PhpStorm whatever has this problem because they always work the same.

The link needs to be this:

    [editor]://[path-to-file-on-HOST]

A link with /var/www/html is meaningless to the host operating system and thus they can't handle it.

I ask you:

If it worked like you are describing how would the operating system (mac/windows/linux, whatever, it's the same for all, so it's not a mac/windows issue or such). How would the host know which file to open in VSCode/Sublime/etc??

    vscode://var/www/html/foo.php

Which file would vscode open??

/users/bernhard/project-A/foo.php?

Or /users/bernhard/project-B/foo.php?

Or /users/bernhard/project-C/foo.php?

Ok... just add it to the config...

Now Gerhard works on my project and clicks on the link...

> File /users/bernhard/project-X/foo.php not found!

So he needs to add the config also.

All that would be obsolete if we could just read the host filepath from the config and that's it.

**Comment by BernhardBaumrock** [comment]
I just tried to solve the issue by adding it to my ddev config alias, but I can't get the `$DDEV_APPROOT` to show up in my config automatically :(

Maybe you can help me with this?


```sh
alias ddc='colima start && ddev config --php-version=8.2 --database=mariadb:10.6 --webserver-type=apache-fpm --timezone=Europe/Vienna --omit-containers=dba --web-environment="DDEV_APPROOT=\$DDEV_APPROOT" '
```

Result:

```yaml
web_environment:
    - DDEV_APPROOT=
```

**Comment by rfay** [comment]
The single command
```
ddev config global --web-environment-add='TRACY_APPROOT=$DDEV_APPROOT'
```

needs to be executed exactly once. It's global. It will work on all projects, no configuration is required for each project. You *must* use single quotes around `'$DDEV_APPROOT'` as shown above.

**Comment by BernhardBaumrock** [comment]
Hi @rfay,

Thank you for engaging in this discussion and for your suggestions. I appreciate your efforts to find a solution within the current capabilities of DDEV. However, I believe there is a huge misunderstanding regarding the core of the issue we're facing.

> It's global. It will work on all projects, no configuration is required for each project.

I'm sorry to say, but this is not true. It is not "global": One of the greatest things about DDEV is that I can push a project to github and it will work. Everywhere and for everyone.

Your advice would break that integral part of our workflows. I can't simply push the project and my colleague would do a `git pull && ddev start`. He'd also have to add that config to his/her project.

"Just add that to the readme" - I hear you say...

Yes, but then again I have to add it to the readme OF EVERY PROJECT and I have to think of that to not forget. It's such a small request, I can't understand why it is such an issue to add this little feature :(

-----

But I finally made my `ddev config` alias work so that it adds the setting automatically to my project's `.ddev/config.yaml` file so that all others working on it (or myself when working on it 2 years later with another laptop will still only have to do `git pull && ddev start` without updating any config variables that have changed in the meantime.

Here's the solution that is placed in my `.zshrc` file:

```sh
alias ddc="colima start && ddev config --php-version=8.2 [...] --web-environment='DDEV_APPROOT=\$DDEV_APPROOT' "
```

**Comment by BernhardBaumrock** [comment]
Hey @rfay thought I'd share a screenshot that illustrates that tracy debugger is really something different than xdebug:

<img width="782" alt="image" src="https://github.com/ddev/ddev/assets/8488586/a3da9b19-f9c4-4d86-bd28-13283ae316ed">

You see that it lists all template files that are rendered for the current webpage, which is great.

You can click on every path and it will open up in vscode/cursor/phpstorm whatever.

That's why I need the host machines paths in my web application in the container. If I don't have that path it tries to open /var/www/html... which does not exist on my computer:

<img width="275" alt="image" src="https://github.com/ddev/ddev/assets/8488586/12247048-b8ca-461e-8e2a-0bb08092acc3">

I've updated all my projects to inject that ENV to the web container. Still it's a mystery why we can't add that to ddev by default. But thx for the great tool anyhow.

**Comment by rfay** [comment]
I think opening an issue with them to get them to use relative paths would be a great thing. Whatever they're doing breaks all container-related development.

**Comment by BernhardBaumrock** [comment]
Hey @stasadev thx for finally understanding what I'm talking about :) 

After thinking about your arguments I agree that the debugger should be responsible for providing the ENV variables. Otherwise the debugger would need to implement all variables for all possible platforms (ddev, devilbox, etc)... Also thx about the hint that I can set the editor in my personal global config - so I don't have to configure it over and over again but other DEVS on the same project are not forced to use the same editor - great :)

So finally we have a good solution and I understand now that having DDEV_APPROOT in the container would be a good solution for me but not in general (as every debugging tool would have to implement this specification).

Here's what I did (just for reference):

- Created a PR for tracy debugger to read `TRACY_LOCALROOTPATH` and `TRACY_EDITOR` from env https://github.com/adrianbj/TracyDebugger/pull/90
- Added this to my config alias used to setup every project: `alias ddc="colima start && ddev config ... --web-environment='TRACY_LOCALROOTPATH=\$DDEV_APPROOT'"`
- Added this to my personal global ddev config: `ddev config global --web-environment-add=TRACY_EDITOR=cursor://file/%file:%line`

Thx for your help!
