### ISSUE TITLE
`ddev start` suggests "you can run this command with the --remove-orphans flag" but that's not a valid flag

### ISSUE THREAD

**Issue by joachim-n** [ddev/ddev#5755]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Output of `ddev debug test`

<details><summary>Expand `ddev debug test` diagnostic information</summary>

```
[COPY-PASTE HERE THE OUTPUT OF `ddev debug test`]
```
</details>         

### Expected Behavior

DDEV shouldn't tell the user to do something that's impossible.

### Actual Behavior

Doing `ddev start` said:

```
Error response from daemon: network with name ddev-thewsd_default already exists
time="2024-01-30T15:00:17Z" level=warning msg="Found orphan containers ([ddev-thewsd-frontend-1 ddev-thewsd-test_report_creator-1 ddev-thewsd-web ddev-thewsd-db ddev-thewsd-redis-1]) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up."
```

Doing `ddev start --remove-orphans` said:

> Error: unknown flag: --remove-orphans

**Comment by stasadev** [comment]
See https://stackoverflow.com/questions/62997751/found-orphan-containers-when-starting-ddev-project

**Comment by joachim-n** [comment]
The only thing I can thing of is to tweak the error message specifically when saying '--remove-orphans' isn't a valid flag, to say something like:

> Error: unknown flag: --remove-orphans. If you've passed this flag because of a message about orphan containers, then [SOME SORT OF ADVICE ABOUT WHAT TO DO INSTEAD].

Up to the maintainer to balance the ick of adding babysitting code to do this vs having to deal with future duplicates of this issue :)

**Comment by rfay** [comment]
Can you please show how to recreate this? I assume it's an invalid `docker-compose.*.yaml`, happy to take a look if you have a recreation scenario.

**Comment by rfay** [comment]
Same issue: https://github.com/ddev/ddev-sqlsrv/blob/623bfa61588adbb18980d01f86daf94fa58a145d/docker-compose.sqlsrv.yaml#L16-L17

**Comment by joachim-n** [comment]
I have no idea how to recreate it, sorry. My best guess is that I had some test projects from the ddev debug command which I had not deleted, or not correctly deleted by deleting only the folder and not DDEV's definition of them.

**Comment by rfay** [comment]
It turns out there is a COMPOSE_REMOVE_ORPHANS and [COMPOSE_IGNORE_ORPHANS](https://docs.docker.com/compose/environment-variables/envvars/#compose_ignore_orphans)

I think we should just set COMPOSE_REMOVE_ORPHANS=true
