### ISSUE TITLE
Missing links in `ddev describe`

### ISSUE THREAD

**Issue by sreichel** [ddev/ddev#5777]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

Just an idea, but `ddev describe` should show links to

- treafik dasboard
- xhprof (if enabled)
- phpMyAdmin (or successor - i dont use it, im happy with phpstorm, but maybe others)
- ...

### Describe your solution

Would be nice to have easy access to all features/services from that command.

**Comment by rfay** [comment]
* `ddev list` gives a link to the traefik dashboard
* If you have PhpMyAdmin, `ddev describe` does in fact provide a link.
* I guess you're right about xhprof, but not sure it's common enough to put it in there.

**Comment by sreichel** [comment]
Thanks. I do not use phpAdmin so i missed that.

I link to treafik would be nice.
xhprof is not there ... i really like it and when its easy to implement ... why not?

Please close if it is not relevant.

**Comment by rfay** [comment]
I think we'll be reworking Xhprof shortly in 
* https://github.com/ddev/ddev/issues/5532
* https://github.com/ddev/ddev/issues/4606
* https://github.com/ddev/ddev/issues/3782

I'll make a note there because it's not a bad idea.
