### ISSUE TITLE
DDEV Swag Shop: Improvements, marketing and promotion

### ISSUE THREAD

**Issue by bmartinez287** [ddev/ddev#5792]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

Up to recently, DDEV did not have an official swag shop.
You could either make unofficial branded items or hope platform.sh might carry some at their booths.
This would make it harder to acquire t-shirts and other swag items.

### Describe your solution

https://ddev.threadless.com/
It is currently live and in its early phase. I added the dark theme logo and some swag shop items.
It would be great to compile community feedback on what could make it better and then research if that is a possibility.
The current store was based on https://vue.threadless.com/ though they have a limited subset of items.

I bought a couple of T-shirts for myself that I'm wearing at the Florida Drupal camp and a pillow because why that's a cool non-conventional item.

The idea is for the store to be an asset to the community and allow the maintainers to be hands-off with it. For the most part, threadless handles all customer-related issues, shipping, and more.

### Describe alternatives

Alternatives were discussed on Discord's marketing channel, but this store had something unique going for it.
It allows you to print a logo on multiple places within the same shirt, chest, back, and front pocket area.

**Comment by bmartinez287** [comment]
The plan at the moment consists of:

- Creating a DDEV issue
- Sharing the store URL and gathering feedback from Discord
- As feedback comes in, sort requests and get input from maintainers.
- Share store at conferences.
- Improve as needed.

**Comment by bmartinez287** [comment]
Because the store is mostly self-managed by threadless income might not be much since they take a percentage, but whatever is generated from it goes into the DDEV foundation Paypal account. In case anybody was wondering.

**Comment by tyler36** [comment]
Thank you for this. I like the simplicity.

Would it be possible to add a link to "https://ddev.com/" somewhere? For convience and for anyone wondering what DDEV is.
Likewise, we should add a link on https://ddev.com/ to the shop (maybe the Github page and ReadTheDocs?)

**Comment by rfay** [comment]
We can put a blog post and a link on ddev.com! Maybe swag link in the footer?

**Comment by julienloizelet** [comment]
Thank you :) 

I just noticed a problem with the mug.
It says: 
> This premium ceramic coffee mug is available in 11 oz and 15 oz.

But there's only one model sold (11oz or 15oz, I don't know).

**Comment by bmartinez287** [comment]
Both mug sizes are available now. 
Plus I added:
- zip pouch
- fleece blanket
- bath matt

**Comment by rfay** [comment]
@bmartinez287 could you please research the profit levels we can anticipate? I'm fine with it being minimal at least at first. The prices seem pretty high anyway. But please report, per https://phpc.social/@cybersmog/111891477272345510

**Comment by bmartinez287** [comment]
To simplify pricing we use threadless managed pricing as of now.

https://artistshopshelp.threadless.com/article/665-how-do-artist-earnings-work.
https://creativeresources.threadless.com/how-managed-pricing-and-promotions-helps-artist-shop-owners/
Our earnings vary from whichever promotion and discounts they might be running on https://www.threadless.com/. 
Marketplace sales primarily cut our earnings. For example, if a base cost is $10 and they run a sale at $11 per item. They get their base cost plus 5 percent and we get whatever is left.

This lets us take advantage of their black Friday plus other store-wide holiday discounts but at the expense of reduced earnings.

The other option is for us to set our pricing per item. In that case, we could make sure we always make $5 or 8 dollars on every sale. More predictable income but at the expense of customer sales during discounts.

Due to our earnings being impacted by sales, products with varied base costs ( t-shirts vs stickers vs pillows), and sales volume we probably need more sales before making an estimate. My guess is earnings will average about 6$ per sale.

**Comment by rfay** [comment]
Could you please say more specifically what the actual results are? For example choose an example like t-shirt and say what amount goes to DDEV.

**Comment by rfay** [comment]
For remote-config (ddev notifications):
* https://github.com/ddev/remote-config/pull/23

**Comment by bmartinez287** [comment]
Below I added 3 different variations of t-shirt though there are more.

Type | Price | Product Cost | 5% fee  | DDEV Foundation earnings.
-- | -- | -- | -- | --
Men's \| T-Shirt \| Triblend - Crest + Back | $40.95 | $34.20 | $2.047 | $4.703
Men's \| T-Shirt \| Extra Soft - Crest + Back | $31.95 | $26.93 | $1.597 | $3.423
Men's \| T-Shirt \| Premium - Crest + Back | $41.95 | $35.28 | $2.097 | $4.5725


the formula is Price - (cost +(5% x Price))

**Comment by rfay** [comment]
Thanks so much! I think people would be happy to do 10% for DDEV Foundation. I do wish the costs were lower in the first place, but I guess these are competitive for demand-printed stuff. I'll probably get a shirt and a mug!

**Comment by GuySartorelli** [comment]
Shipping is a bit ridiculous internationally it turns out. If I want a single sticker it'll cost more than $40 NZD 😂

**Comment by rfay** [comment]
Stickers just aren't a reasonable idea in the first place, maybe we should take those out @bmartinez287 ? I would like to make a bunch (elsewhere), shouldn't cost anything much, and it would be great to get them to conferences and things. DDEV Foundation can afford to buy stickers to give away, probably not t-shirts.

**Comment by rfay** [comment]
Thanks for this initiative @bmartinez287 ! Does anything else need to be done? If not, please close.

**Comment by rfay** [comment]
Closing, happy to continue the conversation, thanks for all the work!
