### ISSUE TITLE
Support XDG base directory specification

### ISSUE THREAD

**Issue by danepowell** [ddev/ddev#5807]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

I'm frustrated when software such as DDEV doesn't respect the [XDG base directory specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html), leading to a cluttered home directory fully of one-off config directories like `~/.ddev`.

### Describe your solution

Follow the XDG base directory spec. For instance, in the absence of any XDG environment variables, move `~/.ddev` to `~/.config/ddev`. If XDG_CONFIG_HOME is set, move `~/.ddev` to `$XDG_CONFIG_HOME/ddev`.

As a transitional solution (so this doesn't need to be a breaking change), load and use the `~/.ddev` directory if it already exists instead of following XDG_CONFIG_HOME.

Note that there are other XDG directories besides the config home; I haven't investigated whether DDEV can or should make use of those.

**Comment by rfay** [comment]
I'd be fine with this if it were supported farther up the chain.

DDEV uses https://pkg.go.dev/os#UserHomeDir to figure out the homedir

While XDG base directory is a super-valid idea, it's really linux-oriented, right? And DDEV is very much for many different environments.

**Comment by danepowell** [comment]
It looks like you could (and should) use [UserConfigDir](https://pkg.go.dev/os#UserConfigDir) instead of UserHomeDir.

**Comment by rfay** [comment]
Sounds promising. Interested in doing a PR?

**Comment by danepowell** [comment]
Thanks, I took a crack at a PR: https://github.com/ddev/ddev/pull/5813

It just respects XDG_CONFIG_HOME for now. You may want to adopt other parts of XDG in the future, but this is good enough for me.
