### ISSUE TITLE
Let docker-compose manage the Docker project network

### ISSUE THREAD

**Issue by stasadev** [ddev/ddev#5810]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Output of `ddev debug test`

<details><summary>Expand `ddev debug test` diagnostic information</summary>

```
[COPY-PASTE HERE THE OUTPUT OF `ddev debug test`]
```
</details>         

### Expected Behavior

Custom `docker-compose.yaml` configurations should work for the Docker project network.

### Actual Behavior

From [Discord](https://discord.com/channels/664580571770388500/1205594721330659349/1205594721330659349):

> When setting the default.driver_opts.'com.docker.network.driver.mtu' ... it seems to not carry though

It doesn't work because of

- #5508

It affects DDEV v1.22.5, v1.22.6, v1.22.7

It's better to partially revert #5508 (only the part where the Docker project network is pre-created, duplicates will be checked anyway) to allow overrides for the project network configs.

Additional note: Docker v25+ doesn't allow to create duplicate networks at all.

### Steps To Reproduce

Create `docker-compose.network.yaml` with:
```yaml
networks:
  default:
    driver_opts:
      com.docker.network.driver.mtu: 1440
```
And inspect the Docker project network for this value:
```
docker inspect ddev-project-name_default
```

**Comment by rfay** [comment]
Have we had enough fun with docker-compose networks yet? :)

**Comment by stasadev** [comment]
Yes 🙂
Better to make network creation more straightforward and customizable.

This may bring back the duplicate error in some cases (in docker before v25), but it's worth the sacrifice.

I will replace the network creation with a duplicate check at startup, so that the user can run `ddev start` again to make the project work.
