### ISSUE TITLE
Shell completion file is a tar file but named as if it were tar.gz

### ISSUE THREAD

**Issue by HongPong** [ddev/ddev#5811]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Output of `ddev debug test`

not related to ddev test but a distro release issue.

### Expected Behavior

gzip expand the ddev_shell_completion_scripts.v1.22.7.tar.gz and install at /usr/local/bin for shell completions.

### Actual Behavior

it says it is not a valid gzip file. when i use `more` it shows it is (at least mostly) plaintext file. 
```
tar -zxf ddev_shell_completion_scripts.v1.22.7.tar.gz 
gzip: stdin: not in gzip format
```
The 1.22.6 file seems about identical as well

### Steps To Reproduce

download the file and run gunzip or tar -zxf on it.

Actually the following does work, so the problem is the GZ not the TAR part - the file is a valid Tar but not a valid gzip and should be renamed accordingly: 

tar -xvf ddev_shell_completion_scripts.v1.22.6.tar.gz 
./
./ddev_fish_completion.sh
./ddev_fig_spec.ts
./ddev_zsh_completion.sh
./ddev_powershell_completion.ps1
./ddev_bash_completion.sh

**Comment by rfay** [comment]
I confirm this, thanks for reporting!

**Comment by HongPong** [comment]
cool thanks @rfay  this is literally the only glitch i've had in ages. much appreciate the tons of work on this thing.

**Comment by rfay** [comment]
We're working on shell completion in general in a couple of active issues, would love to have your feedback,

https://github.com/ddev/ddev/issues?q=is%3Aissue+is%3Aopen+autocompletion
