### ISSUE TITLE
Flag annotations on the custom commands doc page should use backticks

### ISSUE THREAD

**Issue by GuySartorelli** [ddev/ddev#5820]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

As discussed in https://github.com/ddev/ddev/pull/5785#discussion_r1485205849, the headings for flag annotations on the [custom commands page](https://ddev.readthedocs.io/en/stable/users/extend/custom-commands/) should be surrounded in backticks, not souble quotes. 

### Describe your solution

1. Surround annotation references in backticks
2. Remove any spell check references to the annotations

**Comment by rfay** [comment]
:) Thanks

**Comment by GuySartorelli** [comment]
I've created https://github.com/ddev/ddev/pull/5927 for this.
