### ISSUE TITLE
KDE Discover reports ddev packages as unsigned on update

### ISSUE THREAD

**Issue by liayn** [ddev/ddev#5826]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected Behavior

Updates via KDE Discover (PackageKit) should work

### Actual Behavior

Updates fail with 

> /var/cache/PackageKit/39/metadata/ddev-39-x86_64/packages/ddev_1.22.7_linux_amd64.rpm could not be verified.
> /var/cache/PackageKit/39/metadata/ddev-39-x86_64/packages/ddev_1.22.7_linux_amd64.rpm:  Prüfsumme:  SIGNATURE:  NICHT OK

### Steps To Reproduce

1.) Fedora 38 KDE spin (Plasma)
2.) Install DDEV as described in the docs
3.) Let KDE Discover find an available update
4.) Click to update

### Anything else?

Sounds extremely similar to https://github.com/tailscale/tailscale/issues/1882
Not sure if related: https://github.com/ddev/ddev/issues/3997

Updates work fine with just using `dnf` on the CLI.

**Comment by rfay** [comment]
The Fedora packages are in fact unsigned. The vendor has not yet gotten around to working on signed RPMs. 

This is a duplicate as you discovered of
* https://github.com/ddev/ddev/issues/3997

And... I just checked and gemfury.com seems to have enabled signing finally for RPMs. So we'll continue in the other issue! Thanks for waking this up. Closing this one, please follow the other one.

**Comment by rfay** [comment]
@liayn can you walk me through step by step how to demonstrate this in Discover?

**Comment by liayn** [comment]
The steps are pretty straight forward:

* Create a new release on your side
* Open Discover
* Let it search for new updates
* Click "install all"
* See the pop-up containing exactly the error message I posted above

**Comment by rfay** [comment]
Thanks, hope to be able to resolve this someday! Followups in 
* https://github.com/ddev/ddev/issues/3997

I was trying to see if they had in fact done anything about this and it seems not.
