### ISSUE TITLE
New DDEV got installed ("build: improve goreleaser, add testing capabilities, "head" release, …")

### ISSUE THREAD

**Issue by gitressa** [ddev/ddev#5830]
I just got a new release offered, but it looks like maybe it wasn't planned? The title is "build: improve goreleaser, add testing capabilities, "head" release, …"

```
$ ddev start
You seem to have a new DDEV version. 
During an upgrade it's important to `ddev poweroff`.
May I do `ddev poweroff` before continuing?
This does no harm and loses no data. [Y/n] (yes): y
The ddev-ssh-agent container has been removed. When you start it again you will have to use 'ddev auth ssh' to provide key authentication again. 
Network ddev_default removed 
Starting drupal10... 
Network ddev_default created 
Network ddev-drupal10_default created 
20230818_bump_debian_bookworm: Pulling from ddev/ddev-webserver
e02d68a69f9c: Pull complete 
Digest: sha256:0017f77d8046ab81a4666addb56e0bbf14230c028b63f5f6b57d12634a59c212
Status: Downloaded newer image for ddev/ddev-webserver:20230818_bump_debian_bookworm
docker.io/ddev/ddev-webserver:20230818_bump_debian_bookworm
 Container ddev-ssh-agent  Created 
 Container ddev-ssh-agent  Started 
```

```
$ ddev version
 ITEM             VALUE                                             
 DDEV version     v1.22.7-12-g8c9ad1188                             
 architecture     amd64                                             
 db               ddev/ddev-dbserver-mariadb-10.4:v1.22.7           
 ddev-ssh-agent   ddev/ddev-ssh-agent:v1.22.7                       
 docker           25.0.3                                            
 docker-compose   v2.24.5                                           
 docker-platform  linux-docker                                      
 mutagen          0.17.2                                            
 os               linux                                             
 router           ddev/ddev-traefik-router:v1.22.7                  
 web              ddev/ddev-webserver:20230818_bump_debian_bookworm 
```

**Comment by rfay** [comment]
Thanks for subscribing to releases @gitressa ! 

We're all getting the same thing and we think we've figured out why.  Will get it sorted.

**Comment by rfay** [comment]
* there was a logic error in the workflow committed here
* I think people who subscribe to releases will be annoyed by "head" releases for every commit to master anyway.
* I think we should revert the "head" release feature and the minor doc that relates to it.

**Comment by gitressa** [comment]
Thanks, but I am not subscribed to email notifications :) I simply got an update offered when I started DDEV, which I accepted ... Normally, it results in going from 1.22.6 to 1.22.7, but not this time.

**Comment by gitressa** [comment]
It's #1 at the top of https://github.com/ddev/ddev/releases

**Comment by rfay** [comment]
That's because it's the most recent @gitressa

**Comment by rfay** [comment]
> 
Thanks, but I am not subscribed to email notifications :) I simply got an update offered when I started DDEV, which I accepted ... Normally, it results in going from 1.22.6 to 1.22.7, but not this time.


Oh, DDEV offered it? It's a prerelease, so it should never be offered by DDEV itself. Can you show what you saw?

**Comment by gitressa** [comment]
But ... why isn't it tagged with 1.22.8 then?

**Comment by gitressa** [comment]
But I got it offered and it got installed. I put it right there in my issue :)

**Comment by rfay** [comment]
Thanks for reporting that. How did you install it? By downloading?

There was an enormous amount of chatter in Discord about the email notification problem about this release, so I just read your title and thought that was the whole deal.

I have deleted the "head" release and tag.

**Comment by gitressa** [comment]
And to clarify, I have not set DDEV to get anything but stable releases, which is why I was really surprised to get a pre-release.

**Comment by rfay** [comment]
DDEV doesn't "get" anything. Can you say how you installed it?

**Comment by gitressa** [comment]
I installed it with the standard Linux method: https://ddev.readthedocs.io/en/latest/users/install/ddev-installation/#linux

**Comment by rfay** [comment]
So you're on Ubuntu, and you did an `sudo apt-get update && sudo apt-get install -y`?

**Comment by rfay** [comment]
I see that it got pushed inappropriately to the apt and yum repos, working on deleting it.

**Comment by gitressa** [comment]
Great, thanks for confirming that there is an issue.

**Comment by rfay** [comment]
* I deleted the errant apt/yum releases
* I deleted the "head" release and tag
* It didn't go to homebrew or the homebrew edge release

**Comment by rfay** [comment]
Anybody on Linux who got an inappropriate package installed should be able to fix it with

`sudo apt update && sudo apt install ddev`

**Comment by gitressa** [comment]
Thanks @rfay, and sorry I left out the version when I created the issue. I was in a hurry, since I thought that the situation was a bit critical. Great that it got resolved.

I tried the command which made no difference ...

```
$ sudo apt update && sudo apt install ddev
Hit:2 https://mirror.netsite.dk/ubuntu/archive focal InRelease                                                                         
Hit:3 https://mirror.netsite.dk/ubuntu/archive focal-updates InRelease                                                                 
[...]
Reading state information... Done
ddev is already the newest version (1.22.8~8c9ad1188-head).
0 upgraded, 0 newly installed, 0 to remove and 4 not upgraded.
```

Though I am not sure if I got an inappropriate package?
```
$ ddev version
 ITEM             VALUE                                             
 DDEV version     v1.22.7-12-g8c9ad1188                             
 architecture     amd64                                             
 db               ddev/ddev-dbserver-mariadb-10.4:v1.22.7           
 ddev-ssh-agent   ddev/ddev-ssh-agent:v1.22.7                       
 docker           25.0.3                                            
 docker-compose   v2.24.5                                           
 docker-platform  linux-docker                                      
 mutagen          0.17.2                                            
 os               linux                                             
 router           ddev/ddev-traefik-router:v1.22.7                  
 web              ddev/ddev-webserver:20230818_bump_debian_bookworm 
```

**Comment by gitressa** [comment]
It's odd, APT says `1.22.8~8c9ad1188-head`, but DDEV says `v1.22.7-12-g8c9ad1188`.

**Comment by gitressa** [comment]
Docker says:
```
$ docker ps --all
CONTAINER ID   IMAGE                               COMMAND                 CREATED         STATUS                   PORTS     NAMES
899bf4cfa978   ddev/ddev-ssh-agent:v1.22.7-built   "/entry.sh ssh-agent"   5 minutes ago   Up 5 minutes (healthy)             ddev-ssh-agent
```

**Comment by rfay** [comment]
You'll want to remove and reinstall, please try that, thanks. `sudo apt update && sudo apt remove ddev && sudo apt install -y ddev`

**Comment by gitressa** [comment]
Thanks, all is well now :)

```
$ ddev version
 ITEM             VALUE
 DDEV version     v1.22.7
[...]
```

**Comment by rfay** [comment]
Sorry for the trouble! Cascading series of bugs!

**Comment by gitressa** [comment]
Heh, no problem! I am very grateful for the wonderful tool that DDEV is, and how you guys maintain it so well, and expand it with features continually. A very small hiccup like this is to be expected with all the development going on :)
