### ISSUE TITLE
Allow `ddev ssh` to start a shell in the equivalent directory inside the guest

### ISSUE THREAD

**Issue by diegoe** [ddev/ddev#5839]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

When working on a project you often navigate your terminal to a directory inside of it, example `docroot/themes/custom/something`, but then realize that you need to do something _inside_ the guest _in_ this directory, but `ddev ssh` logs into `/var/www/html` or to a directory you pass as `--dir`.

### Describe your solution

I would like to be able to call `ddev ssh -c` (or similar) to be equivalent to `ddev ssh --dir /var/www/html/themes/custom/something` when the host terminal has `$CWD` as `approot/docroot/themes/custom/something`.

Since `ddev` knows all the above information, it should be possible to substract everything up to `docroot/` from the host's `$CWD`, and prefix the resulting string with the guest's absolute path to its docroot.

### Describe alternatives

Passing the `--dir` option requires an absolute path, from the perspective of the guest so you need to manually edit your `cwd` to use the `/var/www/html` prefix instead of whatever you have on your host `$CWD`.

### Additional context

`ddev` rocks ✌️

**Comment by tyler36** [comment]
Hi @diegoe 

I can't remember when this was introduced, but in DDEV `1.22.7` use `-d`

```shell
$ ddev ssh -d /var/www/html/web/sites/default
$ pwd
/var/www/html/web/sites/default
```

Use `ddev ssh --help` to see other options such as open a terminal in the database container.

**Comment by tyler36** [comment]
On closer ready, you want to be able to pass a relative path and not the full path, right?

Something like, but working (without the error)

```shell
$ ddev ssh -d web/sites/default              
OCI runtime exec failed: exec failed: Cwd must be an absolute path: unknown
```

**Comment by diegoe** [comment]
> On closer read, you want to be able to pass a relative path and not the full path, right?
> 
> Something like, but working (without the error)
> 
> ```shell
> $ ddev ssh -d web/sites/default              
> OCI runtime exec failed: exec failed: Cwd must be an absolute path: unknown
> ```

Rather this, which I believe would be better:
```shell
diego@host$ cd myproject
diego@host$ ddev start
diego@host$ cd docroot/themes/custom/my_theme
# Oh no, I gotta run a command in this directory, but _inside_ the guest
diego@host$ ddev ssh --cwd
diego@myproject-web:/var/www/html/themes/custom/my_theme$
# Do whatever I needed without doing path-math for `--dir` or `cd themes/...`
```

**Comment by rfay** [comment]
(Just for context, `ddev ssh -d` has been in the product for 5-6-7 years I think)

**Comment by chrisfromredfin** [comment]
I think OP is asking for something like "ddev ssh --equiv" (or -e), where DDEV just puts you in the corresponding folder you're in on the host. 

I did something like this with `ddev exec` by making a custom command `ddev x` - see https://github.com/redfinsolutions/ddev-commands/blob/main/commands/host/x

I think this might be good to leave for a custom command implementation where you can do something like `ddev sshe` or something, which can figure out and then auto-pass --dir from your custom command.

**Comment by rfay** [comment]
Can you take a look at #5894 and help them along @chrisfromredfin ? Would be much appreciated. Maybe it should be done the same for exec and ssh...

**Comment by rfay** [comment]
https://github.com/ddev/ddev/pull/5894#issuecomment-1979732170 explains how to add an `sshhere` custom command. You could also deploy that with an add-on. 

Closing for now.
