### ISSUE TITLE
TYPO3: Mailpit configuration should be placed in the additional.php file

### ISSUE THREAD

**Issue by wowaTYPO3** [ddev/ddev#5841]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

When I set up a new TYPO3 installation, the following line is written to the config/system/settings.php file:
```transport_sendmail_command' => '/usr/local/bin/mailpit sendmail --smtp-addr 127.0.0.1:1025```

However, this is a configuration that only makes sense in the local development environment and can even cause error messages if it is in the settings.php.

### Describe your solution

The line should be placed in config/system/additional.php, which is created by DDEV.
A generic configuration line could be placed in settings.php, as this must be adapted to the live system by the developer anyway, for example:
```'transport_sendmail_command' => '/usr/local/bin/sendmail -bs',```

**Comment by jonaseberle** [comment]
Hi @wowaTYPO3,
DDEV should not touch `config/system/settings.php` and to my knowledge it does not. When I run the [quick start](https://ddev.readthedocs.io/en/latest/users/quickstart/#typo3) (but using PHP 8.2+ ([PR](https://github.com/ddev/ddev/pull/5842))), only `config/system/additional.php` is added.

It is TYPO3 (or maybe something in `helhum/typo3-console`?) that gets confused sometimes and writes values from the current environment into `settings.php`. I agree something is wrong there but we just have to be careful when committing changes to the file.

**Comment by rfay** [comment]
Correct, DDEV adds settings (optionally) to additional.php. (More about settings management and how to turn it off is at https://ddev.readthedocs.io/en/latest/users/usage/cms-settings/)

@wowaTYPO3 could you please try a trivial TYPO3 project (https://ddev.readthedocs.io/en/latest/users/quickstart/#typo3) and see if it behaves the way you expect?

**Comment by wowaTYPO3** [comment]
Okay, I have just set up an empty, fresh TYPO3 12 project.
DDEV only creates the additonal.php, correct.
Then I install TYPO3 via:
`ddev typo3 setup`
Then the corresponding line is in the settings.php
Where does this code come from?

**Comment by stasadev** [comment]
Hi @wowaTYPO3,

DDEV configures `sendmail_path` in `php.ini` and [TYPO3 reads this value](https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/7.5/Feature-65791-UsePHPConfiguredSendmailPathIfMAILtransportSendmailIsActive.html) on install.

> New installations will have `[MAIL][transport_sendmail_command]` automatically set during installation using `sendmail_path` from PHP runtime configuration. It can still be changed manually.
> As this setting is only used if `[MAIL][transport]` is set to `sendmail`, it doesn't have impact on other transport schemes.

Given that we already set `[MAIL][transport]` to `smtp` in `additional.php` - it's not `sendmail` by default.
I don't think there is anything we can do about it. The `settings.php` file still needs to be configured manually.

You may ask why we set `sendmail_path` and whether it can be removed - the answer is no, this value is required for emails to work in all DDEV environments.

**Comment by wowaTYPO3** [comment]
Okay, thanks for the explanation.

**Comment by jonaseberle** [comment]
@wowaTYPO3 `ddev typo3 setup` is not a TYPO3 Core command. It is added by `helhum/typo3-console`. It re-writes `settings.php`. 

But to be fair the same happens when changing any setting via the backend (then other settings happen to be filled with the current environment's values). So it is also Core that happens to get confused when values are supplied via `additional.php`. 
I've just accepted that ¯\_(ツ)_/¯.

Thank you for your great TYPO3 videos! :)

**Comment by wowaTYPO3** [comment]
@jonaseberle No, this has been a core command for some time now. In my test installation, I did not install Helmut's console at all.

**Comment by rfay** [comment]
`ddev typo3` command is provided by DDEV (maybe it shouldn't be?) but how you use it and what it does are completely dependent on you and helhum/typo3-console. And of course it depends on you doing a `ddev composer require` on that package.

**Comment by jonaseberle** [comment]
> @jonaseberle No, this has been a core command for some time now. In my test installation, I did not install Helmut's console at all.

Sorry, yes, you are totally right :)
