### ISSUE TITLE
Support Pimcore CMS

### ISSUE THREAD

**Issue by rfay** [ddev/ddev#5843]
### Discussed in https://github.com/orgs/ddev/discussions/5840

<div type='discussions-op-text'>

<sup>Originally posted by **80982proton** February 14, 2024</sup>
Hello folks,

it would be great if you could add support for Pimcore. @dpfaffenbauer @brusch

Best regards</div>

**Comment by dpfaffenbauer** [comment]
We are not using ddev, we have our custom setup to be as close as possible to our kubernetes cluster as possible

**Comment by rfay** [comment]
* https://github.com/ddev/ddev/pull/5909

**Comment by SuperFlySly** [comment]
@dpfaffenbauer That may be true, but Pimcore is above all an open source project with a relatively large community. I work at one of the largest Pimcore service providers and even we rarely use Kubernetes. DDEV is ideal for local development of Pimcore - especially if you work in large teams and you want to make sure that everyone has a consistent local development environment.

**Comment by dpfaffenbauer** [comment]
@SuperFlySly yes, I never stated anything different. we just happen to use a custom setup to be as close as possible to our production env.
