### ISSUE TITLE
Adding second docroot in apache breaks default docroot from config

### ISSUE THREAD

**Issue by samyouel** [ddev/ddev#5845]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected Behavior

I'm running a multisite with 4 different sites, that have different docroots. 
Therefore I am trying to setup the other apache webserver's with the [provided file from the apache folder](https://github.com/ddev/ddev/blob/master/pkg/ddevapp/webserver_config_assets/apache_second_docroot_example-site-php.conf).

So I want my primary site to be the docroot defined in my `config.yml` and the other sites are defined as 3 individual apache config files.

### Actual Behavior

When I then spin up my ddev, I can access the other pages, but the default docroot that I assigned in my config is not accessible with the standard `mysite.ddev.site` domain anymore. 

**Instead, the router picks the config file that is alphabetically listed first inside the apache folder**  and uses this for the main domain and also for any other `additional_hostnames` or `additional_fqdns` that are defined. That way, the primary docroot isn't accessible anymore, and instead, another docroot is served.

### Steps To Reproduce

Clone the `seconddocroot.conf.example` file in the `.ddev/apache` folder and rename it to something like `apache-anothersite.conf`, so that this new file is listed before the default `apache-site.conf` file.

The apache conf file:
``` .conf
ServerName anothersite.ddev.site
DocumentRoot /var/www/html/anothersite
<Directory "/var/www/html/anothersite/">
 ```
 
I also added the new hostnames in my config file, so that the https resolves.
``` yml
name: mysite
type: php
docroot: mysite
additional_hostnames:
   - anothersite
```

Now try reaching `mysite.ddev.site` -> you will be rerooted to `/var/www/html/anothersite` instead of `/var/www/html/mysite`.

**Comment by rfay** [comment]
Hi @samyouel - Normally a "multisite" does not have separate docroots. When you're running with separate docroots, you essentially are running different sites from the same codebase. 

If you set up the trivial example in the Apache second docroot setup, does it work?

**Comment by samyouel** [comment]
Yes, that is what I am doing. Then don't call it multisite but something else.
I use Kirby, a flat file CMS, where I have multiple entry points for the different multisites, but they all link back to one codebase. It's setup a bit like in their docs [here](https://getkirby.com/docs/cookbook/setup/multisite-variant).

If I use the example and keep the file name as `seconddocroot.conf`, then yes of course, it works. If I would rename that exact file to something like `aaaa-seconddocroot.conf`, so that it's listed before the standard `apache-site.conf` in the file tree (alphabetically), the described issue keeps occurring.

**Comment by rfay** [comment]
Couldn't you just change your approach since you know exactly what to do? (just use something that comes after "ap" in the alphabet?

**Comment by samyouel** [comment]
Well yes of course, but obviously it seems this is not intended behaviour, or is it? At least it took me quite some time and frustration finding out that by default it always takes this first file in the apache folder no matter the settings.

**Comment by rfay** [comment]
You should be able to study what's happening by taking over the apache-site.conf and adjusting it, if that's what you want to do. A PR is welcome. But it seems that your second-docroot depends on the apache-site.conf. But since you also can take over the apache-site.conf you should be able to completely overcome this. You could probably even mostly empty it out and then copy it to aaa.conf and proceed. I don't think you can delete it because DDEV will recreate it.

**Comment by rfay** [comment]
I think this is a matter of Apache expertise, and should work out OK. Closing for now.
