### ISSUE TITLE
Include b13/ddev-apache-solr in official addons

### ISSUE THREAD

**Issue by ochorocho** [ddev/ddev#5860]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

No

### Describe your solution

Created a apache solr addon (standalone) - We use it with TYPO3, but it should be useable with any other application.

https://github.com/b13/ddev-apache-solr

### Additional context

Other addons using solr cloud or are tailored to drupal.

**Comment by rfay** [comment]
I don't think that [ddev/ddev-solr](https://github.com/ddev/ddev-solr) is supposed to be tailored for Drupal - the maintainer claims it should work anywhere. Could you take a look at it and see if that's true, or if contributions there could work?

**Comment by ochorocho** [comment]
Maybe ddev/ddev-solr can integrate a standalone (non-cloud mode). I have to look into this.

The [b13/ddev-apache-solr](https://github.com/b13/ddev-apache-solr) addon offers a way to automatically create
cores defined in a config file.

DDEV Solr cloud (does not work wiht TYPO3, tested):
https://github.com/ddev/ddev-solr

DDEV Solr Addon for Drupal  (not tested, well it says it's for drupal in the docs):
https://github.com/ddev/ddev-drupal9-solr

Thank you.

**Comment by rfay** [comment]
Are you able to diagnose why ddev-solr doesn't work for TYPO3? If so, of course, contributions there would be better. 

Of course, if it's fundamental that Solr Cloud can't be used with things other than Drupal, perhaps that one should be renamed and updated. 

Could you at least start by opening an issue in ddev-solr with your findings and analysis?

**Comment by rfay** [comment]
The bottom line is I'm happy to promote this. I think since TYPO3 is your expertise and where you most often use it, it probably should be named `ddev-typo3-solr` ? 

Thanks for creating and maintaining this. I have invited you as an owner to the `ddevl` org. Please accept that, then move your repo to ddevl, and I'll move it to ddev and give you admin privs on it. 

Just let me know if `ddev-typo3-solr` is OK for the name. Thanks!

**Comment by rfay** [comment]
If you don't think you can got to this soon @ochorocho I can take you off the `ddevl` org and put you back again when you have some time for it.

**Comment by ochorocho** [comment]
@rfay will have time this weekend. Hope this is soon enough. :-)

**Comment by ochorocho** [comment]
@rfay renamed the addon and pushed it to https://github.com/ddevl/ddev-typo3-solr

Can you please give [@bmack](https://github.com/bmack) access to this project as well?

**Comment by rfay** [comment]
Done, thanks! Now you have a bunch of name-changing work to do :)
