### ISSUE TITLE
Using Docker API broke Colima/Lima/Rancher usage

### ISSUE THREAD

**Issue by rfay** [ddev/ddev#5861]
It seems that Colima doesn't work at all any more since 
* https://github.com/ddev/ddev/pull/5787

We have always had trouble with Colima, so we just kind of ignored the failures there I think. 

Now Colima never works at all

This is easy to recreate  running TestComposerVersion, and Colima isn't actually dead after it completes.

I checked out the commit before the Docker API change, and it passes this test just fine using Colima.

For a test environment, feel free to take one of the macOS Test Runners offline `brew services stop buildkite-agent` and use Goland or vscode there.

## Manual Testing

1. Install Colima (current release) using normal DDEV instructions, https://ddev.readthedocs.io/en/latest/users/install/docker-installation/#macos
  This can also be done as a separate profile if you want to, for example `colima start qemu --cpu 4 --memory 6 --disk 100 --vm-type=qemu --mount-type=sshfs --dns=1.1.1.1` to create a profile called `qemu` and not disturb anything you already have set up.

1. Stop all other docker providers so that they can't be part of the problem.
2. Verify that the context is set correctly and is pointing to your new colima instance, `docker context ls`
3. Verify that `docker ps` works OK.

To run the actual test, you can run it manually (below) or in your IDE:
```
GOTEST_SHORT=true make testpkg TESTARGS='-run TestComposerVersion --count=1'
```

It's instructive to `ddev list` or `docker ps` while docker is broken.

## Testing environment

I was unable to get this to fail on tb-macos-amd64-3, but it fails just fine on tb-macos-arm64-7. tb-macos-arm64-7 is all set up for testing, except you may want an ide there to step through things.

```
brew services stop buildkite-agent
orb stop
# Make sure rancher is stopped as well.
colima start
cd ~/workspace/ddev
GOTEST_SHORT=true make testpkg TESTARGS='-run TestComposerVersion --count=1'
```

**Comment by rfay** [comment]
Running `ddev list` while waiting for TestComposerVersion to finish starting up can get something like this:

<img width="1295" alt="image" src="https://github.com/ddev/ddev/assets/112444/7a5bb9e2-3fce-4222-9d3d-709be12418e0">

**Comment by stasadev** [comment]
I tested it, but still can't figure it out, so I decided to fix this first:
- #5862

**Comment by rfay** [comment]
Looking for simpler setups I stumbled across one. I used `ddev/ddev-solr` with a standard Drupal 10 setup. In this exact case we get the failure to connect to the db container and then a bonus panic.

```
% ddev start
Network ddev_default created
Starting d10...
 Container ddev-ssh-agent  Created
 Container ddev-ssh-agent  Started
ssh-agent container is running: If you want to add authentication to the ssh-agent container, run 'ddev auth ssh' to enable your keys.
Building project images...
Project images built in 0s.
 Network ddev-d10_default  Created
 Container ddev-d10-zoo  Created
 Container ddev-d10-db  Created
 Container ddev-d10-solr  Created
 Container ddev-d10-web  Created
 Container ddev-d10-zoo  Started
 Container ddev-d10-db  Started
 Container ddev-d10-solr  Started
 Container ddev-d10-web  Started
Starting Mutagen sync process...
....Mutagen sync flush completed in 6s.
For details on sync status 'ddev mutagen st d10 -l'
Waiting for web/db containers to become ready: [web db]
Starting ddev-router if necessary...
 Container ddev-router  Created
 Container ddev-router  Started
Waiting for additional project containers to become ready...
All project containers are now ready.
Successfully started d10
Project can be reached at https://d10.ddev.site https://127.0.0.1:32777
PANI[0029] CheckErr(): ERROR:failed to find container of type db: error during connect: Get "http://%2FUsers%2Frfay%2F.colima%2Fqemu%2Fdocker.sock/v1.24/containers/json?all=1&filters=%7B%22label%22%3A%7B%22com.ddev.site-name%3Dd10%22%3Atrue%2C%22com.docker.compose.service%3Ddb%22%3Atrue%7D%7D": EOF
panic: (*logrus.Entry) 0x1400018a4d0

goroutine 1 [running]:
github.com/sirupsen/logrus.(*Entry).log(0x1400018a3f0, 0x0, {0x14000186360, 0x120})
	/Users/rfay/workspace/ddev/vendor/github.com/sirupsen/logrus/entry.go:260 +0x494
github.com/sirupsen/logrus.(*Entry).Log(0x1400018a3f0, 0x0, {0x1400303f948?, 0x105371488?, 0x2?})
	/Users/rfay/workspace/ddev/vendor/github.com/sirupsen/logrus/entry.go:304 +0x60
github.com/sirupsen/logrus.(*Logger).Log(0x105b25e60, 0x0, {0x1400303f948, 0x2, 0x2})
	/Users/rfay/workspace/ddev/vendor/github.com/sirupsen/logrus/logger.go:204 +0x60
github.com/sirupsen/logrus.(*Logger).Panic(...)
	/Users/rfay/workspace/ddev/vendor/github.com/sirupsen/logrus/logger.go:253
github.com/sirupsen/logrus.Panic(...)
	/Users/rfay/workspace/ddev/vendor/github.com/sirupsen/logrus/exported.go:129
github.com/ddev/ddev/pkg/util.CheckErr(...)
	/Users/rfay/workspace/ddev/pkg/util/errcheck.go:15
github.com/ddev/ddev/pkg/ddevapp.(*DdevApp).Describe(0x140002a0708, 0x0)
	/Users/rfay/workspace/ddev/pkg/ddevapp/ddevapp.go:254 +0x27bc
github.com/ddev/ddev/pkg/ddevapp.(*DdevApp).SetInstrumentationAppTags(0x140002a0708)
	/Users/rfay/workspace/ddev/pkg/ddevapp/instrumentation.go:73 +0xb8
github.com/ddev/ddev/cmd/ddev/cmd.init.func48(0x105b361a0, {0x105ba4c60?, 0x0?, 0x0?})
	/Users/rfay/workspace/ddev/cmd/ddev/cmd/root.go:151 +0x3f0
github.com/spf13/cobra.(*Command).execute(0x105b361a0, {0x105ba4c60, 0x0, 0x0})
	/Users/rfay/workspace/ddev/vendor/github.com/spf13/cobra/command.go:1005 +0x96c
github.com/spf13/cobra.(*Command).ExecuteC(0x105b34aa0)
	/Users/rfay/workspace/ddev/vendor/github.com/spf13/cobra/command.go:1115 +0x344
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/rfay/workspace/ddev/vendor/github.com/spf13/cobra/command.go:1039
github.com/ddev/ddev/cmd/ddev/cmd.Execute()
	/Users/rfay/workspace/ddev/cmd/ddev/cmd/root.go:163 +0x24
main.main()
	/Users/rfay/workspace/ddev/cmd/ddev/main.go:27 +0xb8
```

**Comment by rfay** [comment]
A more predictable one, without the panic, same site, right after the above:
```
% ddev restart
Restarting project d10...
 Container ddev-d10-db  Stopped
 Container ddev-d10-web  Stopped
 Container ddev-d10-solr  Stopped
 Container ddev-d10-zoo  Stopped
 Container ddev-d10-web  Stopped
 Container ddev-d10-db  Stopped
 Container ddev-d10-db  Removed
 Container ddev-d10-web  Removed
 Container ddev-d10-solr  Stopped
 Container ddev-d10-solr  Removed
 Container ddev-d10-zoo  Stopped
 Container ddev-d10-zoo  Removed
 Network ddev-d10_default  Removed
Building project images...
Project images built in 0s.
 Network ddev-d10_default  Created
 Container ddev-d10-zoo  Created
 Container ddev-d10-db  Created
 Container ddev-d10-solr  Created
 Container ddev-d10-web  Created
 Container ddev-d10-db  Started
 Container ddev-d10-zoo  Started
 Container ddev-d10-solr  Started
 Container ddev-d10-web  Started
Starting Mutagen sync process...
Mutagen sync flush completed in 2s.
For details on sync status 'ddev mutagen st d10 -l'
Waiting for web/db containers to become ready: [web db]
Starting ddev-router if necessary...
 Container ddev-router  Created
 Container ddev-router  Started
Waiting for additional project containers to become ready...
All project containers are now ready.
Failed to restart d10: db container failed: log=, err=failed to query container labels=map[com.ddev.site-name:d10 com.docker.compose.service:db]: error during connect: Get "http://%2FUsers%2Frfay%2F.colima%2Fqemu%2Fdocker.sock/v1.24/containers/json?all=1&filters=%7B%22label%22%3A%7B%22com.ddev.site-name%3Dd10%22%3Atrue%2C%22com.docker.compose.service%3Ddb%22%3Atrue%7D%7D": EOF
```

**Comment by rfay** [comment]
The panic should be fixed in https://github.com/ddev/ddev/pull/5873, but of course it doesn't solve the real problem. You're welcome to just bring in #5873 if it's useful.

**Comment by rfay** [comment]
After having no trouble replicating this over and over all day, I can't recreate the basic problem tonight.

**Comment by stasadev** [comment]
I see a difference in the syntax of Docker API requests in:

https://github.com/ddev/ddev/blob/08d94f74f25c5617791a71f2be15e403cf79510f/pkg/ddevapp/ddevapp.go#L183-L191

Old `fsouza/go-dockerclient`:

`http://unix.sock/containers/json?all=1&filters=%7B%22label%22%3A%5B%22com.docker.compose.service%3Dweb%22%2C%22com.ddev.site-name%3Dd10%22%5D%7D`

`filters={"label":["com.docker.compose.service=web","com.ddev.site-name=d10"]}`

New `docker/docker/client`:

`http://%2Fvar%2Frun%2Fdocker.sock/v1.44/containers/json?all=1&filters=%7B%22label%22%3A%7B%22com.ddev.site-name%3Dd10%22%3Atrue%2C%22com.docker.compose.service%3Dweb%22%3Atrue%7D%7D`

`filters={"label":{"com.ddev.site-name=d10":true,"com.docker.compose.service=web":true}}`

**Comment by rfay** [comment]
> I noticed that I didn't close the connection to the client in GetDockerClient():

In https://github.com/ddev/ddev/issues/5875 I noted that at the time of the timeout panic there were hundreds? of theads active at time of the timeout panic. I didn't know what they were (still don't).
