### ISSUE TITLE
Add WP_ENVIRONMENT_TYPE constant for WordPress

### ISSUE THREAD

**Issue by JUVOJustin** [ddev/ddev#5866]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

In wordpress it is possible to set an environment type via wp-config.php. This would be helpful to determine the env type in custom logic later. One example: Advanced Custom Fields Pro has a local json sync, where it makes sense to only save back to the filesystem while developing.

### Describe your solution

Setting the `WP_ENVIRONMENT_TYPE` constant to something like "development" by default.

There shouldn't be any side effects. The `WP_DEBUG` constant will become obsolete, since it is set implicitly.

**Comment by rfay** [comment]
DDEV doesn't really try to set your working environment up for you.  This seems more intrusive than we usually do.  If DDEV were to set it in the (tiny) added wp-config-ddev, wouldn't that have the possibility of breaking people?

**Comment by JUVOJustin** [comment]
I don't think so. From my understanding of this function there are no ootb implications: https://developer.wordpress.org/reference/functions/wp_get_environment_type/#description 

The documentation even states it is expected by devs to set this flag. I would consider this as intrusive as the WP_DEBUG. 

Personally, i don't know any logic attached to this constant by core or third party plugins. But when using it, it can save quite some time setting it right away.

Only in the experimental hosting feature of ddev this could have side effetcs when not setting it back to "production".

**Comment by rfay** [comment]
Here's the file, https://github.com/ddev/ddev/blob/master/pkg/ddevapp/wordpress/wp-config-ddev.php - want to try a PR and test the results?

**Comment by stasadev** [comment]
This was added in:

- #6695

**Comment by timnolte** [comment]
This change should have never been pushed. It is now breaking things for us after having updated to a newer release of DDev. There should be a way to prevent DDev from setting this up. People should just be using the `.env` which would have not forced this change on people.

**Comment by JUVOJustin** [comment]
@timnolte why though? It is a local environment and enables debugging as well. I do not see a side effect? Could you elaborate?

**Comment by rfay** [comment]
@timnolte Rather than saying "it is now breaking things", please open a new issue saying specifically what problem you're having. Thank you!

**Comment by timnolte** [comment]
> @timnolte why though? It is a local environment and enables debugging as well. I do not see a side effect? Could you elaborate?

This may be considered a "local" environment but when you deal in support you need to be able to choose which environment it is recognizing as. Additionally, we leverage environment specific configuration that is loaded base in the environment. We don't want to have to now also manage a configuration set marked as "local". DDev should only be configuring the bare minimum of what is needed which is database connectivity and the automatic DNS for the local site. It shouldn't be dictating other things that have to always be overridden.

**Comment by rfay** [comment]
DDEV's secret sauce is its community, which is where the recommendation came from. Again, please open an issue saying exactly what the problem is and what workarounds you have to apply. We love folks from the WP community helping us to understand what works best for them!
