### ISSUE TITLE
Clean install on mac results in warning on each command

### ISSUE THREAD

**Issue by jakeparis** [ddev/ddev#5911]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Output of `ddev debug test`

<details><summary>Expand `ddev debug test` diagnostic information</summary>

```
I don't even have any projects yet. I also tried creating a new project
```
</details>         

### Expected Behavior

When I run `ddev -v` (or any other ddev command) I expect only the regular output, not any warnings.

### Actual Behavior

Instead, every command results in a yellow warning, printed before the regular output:
`Adding custom/shell commands failed: open /Users/jparis/.ddev/commands/host: no such file or directory`

### Steps To Reproduce

1. On a mac Intel, Ventura
2. Running Docker v4.27.2 with default setting (I'm pretty sure)
3. run `brew install ddev/ddev/ddev`
4. run `ddev -v`

**Comment by jakeparis** [comment]
Somehow, this went away on it's own after 5 minutes of various commands.

**Comment by rfay** [comment]
This problem
> Adding custom/shell commands failed: open /Users/jparis/.ddev/commands/host: no such file or directory

was fixed in 
* https://github.com/ddev/ddev/pull/5854

The warning only happened when you were issuing DDEV commands outside of a project.  So you got a project going and the warnings went away.

Thanks for filing the issue!
