### ISSUE TITLE
Check quickstarts for compatibility with mariadb:10.11

### ISSUE THREAD

**Issue by stasadev** [ddev/ddev#5919]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Output of `ddev debug test`

<details><summary>Expand `ddev debug test` diagnostic information</summary>

```
[COPY-PASTE HERE THE OUTPUT OF `ddev debug test`]
```
</details>         

### Expected Behavior

All quickstarts should work.

### Actual Behavior

`magento2` is incompatible with `mariadb:10.11`.
Before adjusting the quickstart for `magento2`, it is better to check all quickstarts.

### Steps To Reproduce

Try magento2 quickstart:

```
$ ...
$ ddev magento setup:install --base-url='https://ddev-magento2.ddev.site/' --cleanup-database --db-host=db --db-name=db --db-user=db --db-password=db --elasticsearch-host=elasticsearch --search-engine=elasticsearch7 --elasticsearch-port=9200 --admin-firstname=Magento --admin-lastname=User --admin-email=user@example.com --admin-user=admin --admin-password=Password123 --language=en_US

Starting Magento installation:
File permissions check...
[Progress: 1 / 1332]
Required extensions check...
[Progress: 2 / 1332]
Enabling Maintenance Mode...
[Progress: 3 / 1332]
Installing deployment configuration...
[Progress: 4 / 1332]
Cleaning up database...
Cleaning up database `db`
[Progress: 5 / 1332]
Installing database schema:
Schema creation/updates:

In SqlVersionProvider.php line 103:
                                                                               
  Current version of RDBMS is not supported. Used Version: 10.11.7-MariaDB-1:  
  10.11.7+maria~ubu2204-log. Supported versions: MySQL-8, MySQL-5.7, MariaDB-  
  (10.2-10.6)
```

**Comment by rfay** [comment]
Thanks for catching that! It's easy to fix both in the code and in the quickstart. I think we should override in the code.

mariadb:10.6 is the old LTS (still LTS). So it's completely reasonable that projects would still be using it.

**Comment by rpkoller** [comment]
forgot to report back in here. i went through all the quickstarts listed in http://ddev.readthedocs.io/en/latest/ testing with the latest version of head. my notes: 

```
backdrop new project - working
craft CMS new project - working
drupal 10 - working  
drupal 9 - EOL
drupal 7 -working
drupal 6 - working but EOL
expression engine git - working
ibexa dxp - working
laravel composer - working 
moodle: 

$> ddev config --composer-root=public --docroot=public --webserver-type=apache-fpm --database=mariadb:10.6
Creating a new DDEV project config in the current directory (/Users/rkoller/Sites/validate) 
Once completed, your configuration will be written to /Users/rkoller/Sites/validate/.ddev/config.yaml
 
Created docroot directory at /Users/rkoller/Sites/validate/public 
Configuring a 'php' project with docroot 'public' at /Users/rkoller/Sites/validate/public 
unable to configure project validate with database type mariadb:10.11 because that database type does not match the current actual database. Please change your database type back to mariadb:10.11 and start again, export, delete, and then change configuration and start. To get back to existing type use 'ddev config --database=mariadb:10.11', and you can try a migration with 'ddev debug migrate-database mariadb:10.6' see docs at https://ddev.readthedocs.io/en/stable/users/extend/database-types/ 

pimcore - working
shopware -working 
silverstripe composer - working
statamic composer - working
typo3 composer -working
wordpress wp-cli -working
wordpress bedrock - working
```

the only real error was with moodle which set the db to mariadb 10.6. . since the minimum requirements for mariadb are 10.6.7 while the recommended is set to latest according to https://moodledev.io/general/releases/4.3 i've simply tried to remove `--database=mariadb:10.6` and it also worked without any complaints. updated the quickstarts accordingly, see https://github.com/ddev/ddev/pull/5935. aside that i did a few more cosmetic changes like removing a EOL version of drupal or changing the order of steps for silverstripe.

**Comment by rfay** [comment]
Thanks! @stasadev please close when you think it's OK.

**Comment by stasadev** [comment]
Thank you, @rpkoller !

**Comment by tyler36** [comment]
@rpkoller 
Thank you for going through all those frameworks!

**Comment by rfay** [comment]
Three cheers! 

I'm looking forward to the day when we do automated tests on our quickstarts. I don't think it should be that hard. We have to restructure them into some kind of testable recipe format, and then present them in the docs.
