### ISSUE TITLE
Remove nginx proxy router

### ISSUE THREAD

**Issue by GuySartorelli** [ddev/ddev#5940]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

DDEV uses traefik by default, which works great for most if not all scenarios.

There is also a legacy `ddev config global --router=nginx-proxy` option. @rfay mentioned in the advisory group discussion that it would be good to remove it in the interest of reducing complexity.

### Describe your solution

Remove the nginx proxy router.

### Additional context

I have never used the nginx proxy router - I'm not sure if there are use cases for it that the traefic router doesn't handle, can't handle, or can handle but only with difficulty. It would be good to get some context around that before any work is done to remove it.

**Comment by rfay** [comment]
Thanks for opening the issue.

I know of one specific case that is the only reason I use nginx-proxy, which is Let's Encrypt support, see https://ddev.readthedocs.io/en/latest/users/topics/hosting/ - it should be easy to update that usage. If you're interested, it should be a fun little thing to do with somebody that has internet resources.

There have been a very few support issues where people reverted to nginx-proxy but in most cases I think they just didn't want to deal with change.

**Comment by rfay** [comment]
The nginx-proxy router is deprecated and will be removed in DDEV v1.24, along with the things that go with it.
