### ISSUE TITLE
Consider replacing mailpit with buggregator

### ISSUE THREAD

**Issue by cweagans** [ddev/ddev#5941]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

mailpit is excellent. I find myself constantly replacing it with [buggregator](https://buggregator.dev) though. It does what mailpit does and then some + it's compatible with multiple language runtimes.

### Describe your solution

buggregator is open source, already packaged as a Docker container, and already available as a ddev addon https://github.com/iljapolanskis/ddev-buggregator

It contains:
* a mail catcher
* an xhprof visualizer
* a [Ray](https://spatie.be/products/ray) server, which can be used to dump variables from programs written in multiple languages
* a [Sentry](https://sentry.io) endpoint, which means that all existing Sentry instrumentation can be directed to buggregator and visualized easily
* a Monolog endpoint for catching log messages
* an [Inspector](https://inspector.dev) server, which can be used for visualizing APM traces from Inspector
* an HTTP dumper, which works sort of like [RequestBin](https://pipedream.com/requestbin)

All of those pages will update in real time, so you can open buggregator in a separate window, send whatever data you need to send to buggregator, and have it just show up.

It's a really comprehensive set of tools that really make a dev environment complete. With the new experimental Python app functionality, having cross-language dev tools like this seems like a really valuable thing to ship by default.

**Comment by rfay** [comment]
Great to see you @cweagans ! buggregator sure seems to do a lot of things!

**Comment by GuySartorelli** [comment]
I haven't looked at it much, but I do note that buggregator marks itself as "Ultimate Debugging Server for PHP" - PHP being the term there that I want to bring attention to.

Mailpit is not solely for use with PHP projects, so I'd be hesitant to **replace** it with something that seems like it might be.

**Comment by cweagans** [comment]
There are PHP specific things in it, but it's not _only_ for PHP. The mail catcher works across languages. Ditto for the Ray, Sentry, Inspector, and HTTP Dumper viewers.

The only PHP-specific things appear to be the xhprof and monolog integrations.

**Comment by rfay** [comment]
It does of course say in very large, friendly letters on the very top of the repo "tailor-made for PHP applications"

**Comment by rfay** [comment]
Rather than replacing mailpit, a buggregator add-on would be more appropriate.  Closing for now, looking forward to the add-on.

**Comment by tyler36** [comment]
> ... already available as a ddev addon https://github.com/iljapolanskis/ddev-buggregator

FYI OP mentions the addon in the description.
