### ISSUE TITLE
Remove debug code related to #5089, which has been resolved

### ISSUE THREAD

**Issue by GuySartorelli** [ddev/ddev#5942]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

The below code related to #5089 says it should be removed "when #5089 is resolved, or at least by 2024-01-01"

Since both of those criteria are met, it's probably time to remove this.

https://github.com/ddev/ddev/blob/3a1ec3055aff80bc9995852cd6f2bd4b7d3c47e5/pkg/ddevapp/ddevapp.go#L1362-L1375

### Describe your solution

Remove the code in question.

### Describe alternatives

We could leave it in - it's not doing any harm. Just no sense having it there if it's not needed.

**Comment by GuySartorelli** [comment]
@rfay Just to confirm before I raise a PR, that isn't needed for anything anymore is it?

**Comment by rfay** [comment]
You're right that it can be removed, thanks!

**Comment by rfay** [comment]
Removed in 
* #5959
