### ISSUE TITLE
DDEV should prompt to update when new releases come out (it already does)

### ISSUE THREAD

**Issue by bmartinez287** [ddev/ddev#5947]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

I don't update as often as I should, maybe we should nudge users a bit more by giving them a notice like on my zsh.

### Describe your solution

<img width="289" alt="Screenshot 2024-03-07 at 3 28 32 PM" src="https://github.com/ddev/ddev/assets/39039024/52bbc1e0-ca01-4a30-9b85-f7f9b0b9e83c">

It be nice if we could do it like oh my zsh and include the release notes while prompting an update notice.
i do like how the include the release notes too. Allows one to parse through their feature, upgrades, and bug fixes quickly.

**Comment by rfay** [comment]
DDEV prompts once a week in current released version.

In upcoming versions it's set to prompt every 4 hours. https://github.com/ddev/ddev/pull/5890

I hope that works out for you :)

Did you never see the weekly pester?

**Comment by rfay** [comment]
Related: 
* https://github.com/ddev/ddev/issues/5889

**Comment by bmartinez287** [comment]
I should upgrade 😬 haha, I have been [v1.22.4](https://github.com/ddev/ddev/releases/tag/v1.22.4) which likely explains why I did not see it.
Updating now.

**Comment by rfay** [comment]
Well, the weekly pester has been in there for years. But you're not the only one that ever said you didn't notice it.

**Comment by bmartinez287** [comment]
![Screenshot 2024-03-11 at 12 12 33 PM](https://github.com/ddev/ddev/assets/39039024/16bf4384-5e7e-4588-902e-80b3b2871e0c)
I wonder if that making that a prompt would be a good idea.

**Comment by rfay** [comment]
> I wonder if making that a prompt would be a good idea

I'm not sure what you're suggesting. Isn't that what we already do?

**Comment by rfay** [comment]
We increased the frequency, closing. We can reopen if this isn't adequately resolved for you.
