### ISSUE TITLE
Global database commands cannot open a database when the project is stopped

### ISSUE THREAD

**Issue by stasadev** [ddev/ddev#5949]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Output of `ddev debug test`

<details><summary>Expand `ddev debug test` diagnostic information</summary>

```
[COPY-PASTE HERE THE OUTPUT OF `ddev debug test`]
```
</details>         

### Expected Behavior

It should open the database (or ask the user to start the project).

### Actual Behavior

When I tested `ddev dbeaver` with a stopped project, it started the project and tried to open the database with `3306` port (which is not the correct host port), and on the second run the db was opened with the actual working port.

### Steps To Reproduce

1. `ddev stop`
2. `ddev dbeaver` (or any other db command)
3. see the database connection with the wrong port

### Anything else?

I assume that this is because the DDEV env variables in the `dbeaver` script (and any other script for opening a database) are not updated after `ddev start`, so it only works when the project is started.

Is it possible to update env in Bash after `ddev start`? Or maybe we need to change the logic for db commands from:

```bash
if [ "${DDEV_PROJECT_STATUS}" != "running" ]; then
  echo "Project ${DDEV_PROJECT} is not running, starting it"
  ddev start
fi
```
to
```bash
if [ "${DDEV_PROJECT_STATUS}" != "running" ]; then
  echo >&2 "Project ${DDEV_PROJECT} is not running, please start it"
  exit 1
fi
```

**Comment by rfay** [comment]
The actual port is an ephemeral port and isn't known until after we start. 

Related:
* https://github.com/ddev/ddev/issues/3566

**Comment by rpkoller** [comment]
I've installed sequelace today and noticed the exact same behavior. found this issue when searching if there is an already existing issue.
