### ISSUE TITLE
DDEV_PRIMARY_URL has http scheme despite custom cert

### ISSUE THREAD

**Issue by SomeBdyElse** [ddev/ddev#5966]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected Behavior

The environment variable DDEV_PRIMARY_URL inside the web container should point to a `https://` URL, same as it does if using mkcert. 

### Actual Behavior

The DDEV_PRIMARY_URL has a http scheme. e.g.: http://projectname.ddev.site

### Steps To Reproduce

* Create a new ddev project
* Add [custom TLS certificates](https://ddev.readthedocs.io/en/latest/users/extend/custom-tls-certificates/)
* Start the project with `ddev start`

Check the `DDEV_PRIMARY_URL` env variable:

```bash
ddev ssh
echo $DDEV_PRIMARY_URL
```

### Anything else?

https://github.com/ddev/ddev/blob/4928230143fa6a271ed6d38fd0a266f64307e021/pkg/ddevapp/utils.go#L507 seems to indicate that projects with custom cert should be available via https. 

I tried to override the environment variable with 

```yaml
# config.local.yaml
web_environment:
  - DDEV_PRIMARY_URL=https://…
```

Unfortunately the default from ddev takes presedence

**Comment by stasadev** [comment]
Hi @SomeBdyElse,

Thank you for exploring the DDEV code, you are looking at changes in DDEV HEAD (meaning it is not released yet).

- #5684

Would like to hear your results using the latest DDEV HEAD:

https://ddev.readthedocs.io/en/stable/developers/building-contributing/

**Comment by rfay** [comment]
We're happy to help with this, happy to continue the conversation here or elsewhere, but no response so far, so closing this.
