### ISSUE TITLE
docs: Remove docs and test for `#ddev-nodisplay` 

### ISSUE THREAD

**Issue by hanoii** [ddev/ddev#5969]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected Behavior

I searched the code and found one test but I think all this stanza behavior was removed from ddev, not sure if by accident of on purpose. So if it was removed on purpose, probably worth removing it altogether and fixing https://github.com/ddev/ddev-addon-template/blob/main/install.yaml

project-wide search of #ddev-nodisplay

```
Searching 5610 files for "ddev-nodisplay"

~/Sites/work/ddev/cmd/ddev/cmd/testdata/TestCmdGetComplex/recipe/install.yaml:
    3  pre_install_actions:
    4  - |
    5:   #ddev-nodisplay
    6    echo "This action should not have any output"
    7  - |

~/Sites/work/ddev/docs/content/users/extend/additional-services.md:
  102  In any stanza of `pre_install_actions` and `post_install_actions` you can:
  103  
  104: * Use `#ddev-nodisplay` on a line to suppress any output.
  105  * Use `#ddev-description:<some description of what stanza is doing>` to instruct DDEV to output a description of the action it's taking.
  106  

2 matches across 2 files
```

### Actual Behavior

n/a

**Comment by rfay** [comment]
It's used extensively in ddev/ddev-platformsh

https://github.com/ddev/ddev-platformsh/blob/main/install.yaml

**Comment by hanoii** [comment]
I am just saying it doesn't appear that there's code on ddev that does anything with it.

**Comment by hanoii** [comment]
See https://github.com/search?q=repo%3Addev%2Fddev%20%23ddev-nodisplay&type=code

**Comment by hanoii** [comment]
I found some of it was added on https://github.com/ddev/ddev/commit/80a2907fd708618ff5a511ce2723ae17b3bb6669

But that logic is not currently anywhere.

**Comment by rfay** [comment]
You're right of course.

I see it was removed in 
* https://github.com/ddev/ddev/pull//4431

(`git log -S 'ddev-generated'`)

I think it turned out that the output was rarely useful, but I would think I would note it in the PR.
