### ISSUE TITLE
"Using nginx snippets" notification could have improved formatting

### ISSUE THREAD

**Issue by diegoe** [ddev/ddev#5985]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Output of `ddev debug test`

NA

### Expected Behavior

`ddev` could report `nginx` snippets in a more readable fashion (?):

```
Using nginx snippets: [
  /Users/diego/some-project/.ddev/nginx/some.conf,
  /Users/diego/some-project/.ddev/nginx/some-other.conf
]
Custom configuration, including snippets, is only updated on project restart.
Run `ddev restart` if you do not see your configuration in effect.
```

Of course, the above could be smarter about other snippets or servers. I'm not familiar with other setups.

### Actual Behavior

`ddev` reports `nginx` snippets like:

```
Using nginx snippets: [/Users/diego/some-project/.ddev/nginx/some.conf /Users/diego/some-project/.ddev/nginx/some-other.conf]
Custom configuration is updated on restart.
If you don't see your custom configuration taking effect, run 'ddev restart'.
```

### Steps To Reproduce

1. Use a snippet in `.ddev/nginx`
2. Restart the project
3. Message is printed in hard to read format

### Anything else?

See: https://github.com/ddev/ddev/blob/master/pkg/ddevapp/config.go#L613

**Comment by rfay** [comment]
A PR is welcome. Snippets are little-used and were scheduled for removal, but people liked them so they're still around. 

If you aren't interested in doing a PR I doubt this will be addressed.
