### ISSUE TITLE
ddev-webserver healthcheck should exit early on error with apache/nginx/php-fpm

### ISSUE THREAD

**Issue by stasadev** [ddev/ddev#5993]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Output of `ddev debug test`

<details><summary>Expand `ddev debug test` diagnostic information</summary>

```
[COPY-PASTE HERE THE OUTPUT OF `ddev debug test`]
```
</details>         

### Expected Behavior

The user should not wait two minutes for a timeout if something goes wrong with apache/nginx/php-fpm

### Actual Behavior

If the container fails to become healthy on `ddev start`, the supervisor tries to restart apache/nginx/php-fpm until the 2 minute timeout. Previously, this led to early failure, but now we have a timeout.

The logic changed after
- #5936

### Steps To Reproduce

See:

- https://github.com/ddev/ddev/issues/5899#issuecomment-2000105112

### Anything else?

The issue is partially discussed in:
- #5978

**Comment by rfay** [comment]
Thanks for opening the issue!
