### ISSUE TITLE
"test this PR on Gitpod" should open a more generic project, not just "drupal10"

### ISSUE THREAD

**Issue by tyler36** [ddev/ddev#6014]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Output of `ddev debug test`

<details><summary>Expand `ddev debug test` diagnostic information</summary>

```
[COPY-PASTE HERE THE OUTPUT OF `ddev debug test`]
```
</details>         

### Expected Behavior

I want a "clean" environment so I can follow a quickstart guide.

Idealy, the link opens a workspace with _only_ DDEV configured and installed. Developers can then follow a quickstart guide to keep things minimal and lean.

I can see the benefit of a preinstalled environment so perhaps we could offer both?

"You can also **test this PR in a clean Gitpod** or with a **simple Drupal 10 project**.

* Wording a work-in-progress.

### Actual Behavior

After clicking the "test this PR on Gitpod" link, it created a workspace that installed, configured and started the Drupal Umami demo.

This is great for developers that are familiar with Drupal. However:

- not everyone is familiar Drupal
- adds additional overhead to install/configure/import a Drupal installation when it may not be needed
- additional hdd, cpu cycles used that may not be needed.

For new developers this could raise some questions:
- Is it better to stop the project before trying to start a new one?
- Where should I put my new project?
- Will the 2 projects conflict? (No, thats we are using DDEV)

### Steps To Reproduce

1. Visit https://github.com/ddev/ddev/pull/5888
2. Click the [test this PR on Gitpod](https://gitpod.io/?autostart=true#https://github.com/ddev/ddev/pull/5888).

**Comment by tyler36** [comment]
Related to #5989

**Comment by tyler36** [comment]
Yes, getting errors now:

1. Stop `d10simple` and make new project

```shell
ddev stop
cd ..
mkdir my-cakephp-app
cd my-cakephp-app
```

2. Configure project

```shell
$ ddev config --project-type=cakephp --docroot=webroot --create-docroot --php-version=8.3
Configuration complete. You may now run 'ddev start'.
$ ddev composer create--prefer-dist cakephp/app:~5.0
Failed to start workspace: host port 3306 has already been allocated to project d10simple
```

**Comment by rfay** [comment]
You have to do a `ddev delete -Oy d10simple` normally on gitpod, because it's all set up to do one project at a time (and the exposed ports all default to the same).

**Comment by rfay** [comment]
The gitpod setup here is built around building the `ddev` executable, not around having a proper project to test. I don't think we could succeed at that.

I'm happy to walk through the steps though.

**Comment by tyler36** [comment]
> You have to do a `ddev delete -Oy` d10simple normally 

That would work. Not sure best way to communicate that to new developers though.

**Comment by rfay** [comment]
Most of the time people just need a random site to work with. What we could do is replace d10simple with a trivial php project with an index.php I guess. And maybe the index.php could say what to do to go forward. 

This is done by https://github.com/ddev/ddev/blob/master/.gitpod.yml

It's not hard to do it with a simple php repo, and then tell people how to override what they have there. 

Interested in experimenting with it?

**Comment by tyler36** [comment]
If I have free time, I'll play around. New business year starts next week, so not sure how far I will get.

**Comment by quicksketch** [comment]
I had to work with GitPod recently and I was thrown into their new product offering, ["GitPod Flex"](https://www.gitpod.io/blog/introducing-gitpod-flex-faq). Apparently new customers are funneled into this new offering.

The short version of the story is:

- GitPod will no longer provide hosted environments after April 2025
- You can still run GitPod on _your own_ infrastructure. But right now that is exclusively on AWS.
- GitPod can be run locally... but only on Mac. There is no Windows or Linux version yet. But if you're using DDEV, I would expect that GitPod provides a pretty limited utility when running locally.
- Pricing can only be determined via a calculator or by "contacting sales".

The original report here is still valid: users need a way to test DDEV, and that doesn't need to be coupled to Drupal. But the future of GitPod specifically does not look good.

**Comment by rfay** [comment]
Yes, we're tracking the significant gitpod trouble because it throws an entire monkey wrench into the excellent Drupalpod project :( 

We'll be removing the link to gitpod at the appropriate time.

It's sad that Gitpod Flex doesn't seem to be a related product. I also haven't succeeded in setting it up although I've tried a couple of times.

**Comment by quicksketch** [comment]
Between GitHub Workspaces, [Tugboat](https://www.tugboatqa.com/), and [Drupal Forge](https://www.drupalforge.org/). There are some good alternatives.

**Comment by rfay** [comment]
I'm going to close this one, as gitpod is going away, and we'll need to have replacements. Perhaps we just need to transfer the ideas to codespaces for now.
