### ISSUE TITLE
`$SHELL` not exported in `ddev ssh`

### ISSUE THREAD

**Issue by hanoii** [ddev/ddev#6018]
This is an odd thing but as I saw it twice in different situations I rather raise it up.

Some time ago I submitted https://github.com/platformsh/cli/issues/117

In working with https://github.com/hanoii/ddev-pimp-my-shell I also submitted https://github.com/junegunn/fzf-git.sh/issues/37. I couldn't really understand what was going on until I figured those issues were the same issue, `$SHELL` was not `bash` on either situation. 

### Steps To Reproduce

I tried to reproduce it with scripts, but I couldn't, the best way I found for you to reproduce it is to spin up a bare php project and install the platform-cli inside `ddev ssh`:

`curl -fsSL https://raw.githubusercontent.com/platformsh/cli/main/installer.sh | bash`

Then run

`platform self:install`

You will see the following in the output:

`Setting up autocompletion... skipped (unsupported shell)`

If you run, however, the following:

`SHELL=$SHELL platform self:install`

You will see:

`Setting up autocompletion... done`

So not sure if this is the expected behavior. I think SHELL just needs to be properly exported, but I haven't tracked why this happens.

I ended up export SHELL myself on my addon at https://github.com/hanoii/ddev-pimp-my-shell/blob/514d264b76e3555c87df2390283aaea36b0aac81/homeadditions/.bashrc.d/pimp-my-shell.sh#L4 which fixed both things.

**Comment by rfay** [comment]
Is this is the right repo?

**Comment by hanoii** [comment]
Erm.. I think so, why?

**Comment by hanoii** [comment]
I think it's the fact that the image doesn't properly export SHELL as it should, but that's my understanding, I might be wrong.

**Comment by rfay** [comment]
It doesn't mention anything about DDEV, all about platform cli?

**Comment by rfay** [comment]
I think your answer is in https://unix.stackexchange.com/questions/277944/what-sets-the-shell-environment-variable

SHELL is set on login shells.

**Comment by hanoii** [comment]
Just an experience I had on ddev with those tools. I would expect platform
self:install to just work normally

Reply might shorter than usual / Respuesta más resumida qué de costumbre
Enviado desde el celular / Sent from Mobile

**Comment by hanoii** [comment]
> SHELL is set on login shells.

but SHELL is set, that's why `SHELL=$SHELL platform self:install` works (within ddev)

**Comment by rfay** [comment]
Maybe you can come up with a recreation scenario so we can talk. I can't understand how this relates to DDEV at this point. 

I always appreciate your careful attention to DDEV and reporting problems and frictions!

**Comment by hanoii** [comment]
Isn’t the steps to reproduce on the original comment ok? I can showcase it
otherwise.

Reply might shorter than usual / Respuesta más resumida qué de costumbre
Enviado desde el celular / Sent from Mobile

**Comment by rfay** [comment]
Please provide a simple recreation scenario that shows step-by-step what to do to demonstrate the issue.  Use a simple script perhaps?

**Comment by rfay** [comment]
Thanks for taking the time to explain this  in Discord.

Although it's not exactly standard for `bash -l` to set $SHELL I'm OK with a PR to /etc/skel/.bash_profile that exports it.

**Comment by rfay** [comment]
Closing for now, I think a PR is fine, but this is mighty obscure!
