### ISSUE TITLE
v1.23.0 Test Plan and release notes draft

### ISSUE THREAD

**Issue by stasadev** [ddev/ddev#6039]
It's testing time again here in the DDEV factory. We love community help with every item that is interesting or relevant to you, and just *using* the release candidates is hugely helpful, because you may stumble across something in your regular workflow. Please use the latest pre-release for your testing, https://github.com/ddev/ddev/releases

I don't think in general you'll have trouble using this in your daily workflow, so would love you to do that. You can switch back and forth, see [How can I install a specific version of DDEV in the FAQ](https://ddev.readthedocs.io/en/stable/users/usage/faq/).

If you find a bug that you're pretty sure is a bug, then [just open an issue for it](https://github.com/ddev/ddev/issues/new/choose).

To give feedback or ask questions, please just reply on this issue or discuss in [Discord](https://discord.gg/5wjP76mBJD) or any other support channel.

See [commits since v1.22.7](https://github.com/ddev/ddev/compare/v1.22.7...master) and [PRs merged since February 8, 2024](https://github.com/ddev/ddev/pulls?q=is%3Apr+is%3Aclosed+merged%3A%3E2024-02-08)

1. Go through quickstarts:
    - [ ] Check if all `ddev composer create` are updated to the latest syntax (i.e. do not have outdated flags, like `-y`)
    - [ ] Test them and verify PHP versions for the created projects, the current default is PHP 8.2, and some of projects may have customizations and use something outdated like PHP 8.1
2. Node.js version defaults to `20`, check it out.
3. Check if `*.webp` images open from hidden directories with nginx.
4. Test if primary URL for app is HTTPS when using custom certificates.
5. Check autocompletion for custom commands, like ddev npm, nvm, blackfire, xdebug, xhprof
6. Check for leftovers from segment.io
7. Examine `ddev debug test` output
    - [ ] Repeat the same with heavily customized global DDEV config (it should work with custom ports, etc.)
8. Test if missing projects are removed from the `ddev list`
9. Custom commands (shell commands) have been radically restructured, especially global commands. 
    - [ ] Custom commands should work
    - [ ] No project .ddev/.global_commands should exist any more
    - [ ] Global custom commands should work but probably still require a `ddev restart`
10. `ddev exec symfony -v` should show symfony version and help.

**Comment by rfay** [comment]
## Testing on WSL2 with Ubuntu 24.04-beta with docker-ce and DDEV v1.23.0-rc1

I was able to install DDEV+docker-ce using the normal instructions.

1. Quickstarts:
  * ✅

**Comment by penyaskito** [comment]
I updated a project and had to do a couple of amends, mostly related to the update to bookworm.

We have our own Dockerfile with some extensions:

- csvkit: 

Before: `sudo apt-get install python3-pip -y && pip3 install csvkit`
After: Bookworm suggest using apt when possible with big warning, so changed that to `sudo apt-get install python3-pip python3-csvkit -y`

- KasmVNC: 
Just changed the package download for the right distro: 
`RUN /bin/bash -c 'if [ $(arch) == "aarch64" ]; then KASM_ARCH=arm64; else KASM_ARCH=amd64; fi; wget https://github.com/kasmtech/KasmVNC/releases/download/v1.3.1/kasmvncserver_bookworm_1.3.1_${KASM_ARCH}.deb'
`

**Comment by rfay** [comment]
FYI `pip3` has already been available in DDEV without being added for a year or so (v1.22.0). So you shouldn't need to install it in the first place.

**Comment by rfay** [comment]
Thanks @penyaskito - As you see over there, it seems the user had taken over the .ddev/.gitignore so it couldn't be updated by the normal process. This kind of change happens regularly in DDEV releases, but the answer is always the same, please don't take over the .ddev/.gitignore.

**Comment by stasadev** [comment]
From my testing, the DDEV HEAD is quite stable.

I admit that I didn't test all the quickstarts (impressive work, thanks @rfay).

Everything else looks good to me.

**Comment by rfay** [comment]
Complete!
