### ISSUE TITLE
Unable to update / install ddev 1.23.0 alpha on Ubuntu 20.04

### ISSUE THREAD

**Issue by nlighteneddesign** [ddev/ddev#6046]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Output of `ddev debug test`

<details><summary>Expand `ddev debug test` diagnostic information</summary>

```
[COPY-PASTE HERE THE OUTPUT OF `ddev debug test`]
```
</details>         

### Expected Behavior

I should be able to install or update ddev. ( I had previously been using ddev, but needed to update it to support php 8.3

I tried manually installing the latest and using the .deb

### Actual Behavior

ddev --version
ddev: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ddev)
ddev: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ddev)

### Steps To Reproduce

I am on Ubuntu 20.04

**Comment by rfay** [comment]
Could you please say how you are installing it? Did you download the .deb ?

**Comment by rfay** [comment]
I was able to install using the [deb](https://github.com/ddev/ddev/releases/download/v1.23.0-alpha1/ddev_1.23.0-alpha1_linux_amd64.deb) on Gitpod (Ubuntu 22.04, amd64):

```
gitpod /workspace/xhprof (master) $ sudo dpkg -i ./ddev_1.23.0-alpha1_linux_amd64.deb 
(Reading database ... 51156 files and directories currently installed.)
Preparing to unpack .../ddev_1.23.0-alpha1_linux_amd64.deb ...
Unpacking ddev (1.23.0~alpha1) over (1.23.0~alpha1) ...
Setting up ddev (1.23.0~alpha1) ...
gitpod /workspace/xhprof (master) $ which ddev
/usr/bin/ddev
gitpod /workspace/xhprof (master) $ ddev --version
ddev version v1.23.0-alpha1
gitpod /workspace/xhprof (master) $ 
```

I was also able to install the binary (tarball):

```
$ curl -LO https://github.com/ddev/ddev/releases/download/v1.23.0-alpha1/ddev_linux-amd64.v1.23.0-alpha1.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 13.3M  100 13.3M    0     0  18.5M      0 --:--:-- --:--:-- --:--:-- 18.5M
gitpod /workspace/xhprof (master) $ tar -zxf ddev_linux-amd64.v1.23.0-alpha1.tar.gz 
gitpod /workspace/xhprof (master) $ ./ddev --version
ddev version v1.23.0-alpha1
```


Please let me know exactly what you did. Is it possible you installed the arm64 version of DDEV on an amd64 computer (most are amd64)?

**Comment by nlighteneddesign** [comment]
The first thing I did was download this release: ddev_linux-amd64.v1.23.0-alpha1 (AMD not ARM)
Then I extracted it
Then I copied the ddev file to /usr/local/bin/ddev

Then I tried running ddev --version and received the error I posted

I then tried installing it with apt, that threw the same error.
I uninstalled the apt version then downloaded 1.22.7 from releases, extracted it and moved ddev to /usr/local/bin/ddev and ddev works.

**Comment by nlighteneddesign** [comment]
Actually I apologize, I just realized my laptop is actually on ubuntu 20.04, not 22.04

**Comment by rfay** [comment]
I will take a look at Ubuntu 20.04.

**Comment by rfay** [comment]
Thank you very much @nlighteneddesign , I'm able to recreate this on Ubuntu 20.04. It's a critical failure in the build I guess (CGO_ENABLED must be being set to 1)

The `ddev` binary should not have any dependencies anywhere, and apparently this build got dependencies, which is only supposed to happen when we're checking for races. 

If I just do a `make` on Ubuntu 20.04, I get a binary that runs, but if I download the one from the release, it fails as you show.

**Comment by rfay** [comment]
And thanks for testing!

**Comment by rfay** [comment]
Here's one way we can detect and test after build whether CGO was inappropriately enabled:
* https://stackoverflow.com/questions/65103958/is-it-possible-from-go-app-to-detect-if-cgo-enabled

**Comment by rfay** [comment]
The build shows it having been done with CGO_ENABLED=0, https://github.com/ddev/ddev/actions/runs/8437362553/job/23106996344#step:7:26

**Comment by rfay** [comment]
Thanks so much for reporting this @nlighteneddesign - it saved us a lot of heartache. 

And thanks for testing the pre-releases!

Please test the assets in https://github.com/ddev/ddev/releases/tag/v1.23.0-beta1 and let us know how it goes.

**Comment by rfay** [comment]
Oh, didn't realize you were really @nicxvan, HI!

**Comment by nlighteneddesign** [comment]
Yep, that's me, HI!

This is my business account so most Github issues get filed under this account.
I've tested and confirmed that the beta works on Ubuntu 20.04 now.
Now I need to update my laptop since 20.04 is getting a bit old!
