### ISSUE TITLE
DDEV should respect existing .env values

### ISSUE THREAD

**Issue by n8-dev** [ddev/ddev#6070]
## Is there an existing issue for this?

- [X] I have searched the existing issues

## Is your feature request related to a problem?

`ddev start` updates a `.env` file.

`.env` typically are ignored in your project.

This can cause issues where things do not line up with what we are expecting.

> [!IMPORTANT]  
> Note: I am a Silverstripe CMS (read: framework) developer, currently work at Silverstripe Ltd (read: company) and will use Silverstripe CMS as my example going forward

### Example 1.
Say I have a site running locally, for what ever reason I might need to take a snapshot of production to investigate something further.
Say prod database is very large, 30GB+; loading and unloading that constantly isn't a decent use case of time.
So a create a new database called `prod`, import that to there, adjust my .env
```.env
SS_DATABASE_NAME="prod"
```
and away I go doing my work. 👍 

However, if for any reason my DDEV details are stopped. (computer restart, ran `ddev stop` for some reason, etc) and I return to this project and run `ddev start` I'll loose connection to this prod database...

If we check the `.env` instead of that `"prod"` we will see the following.
```.env
SS_DATABASE_NAME="db"
```

It's been reset.

\#ytho 🤔 

I view this as an anti-pattern/an issue. I should be in charge of my own `.env` file once it's made.

### Example 2.
Current config standards for Silverstripe .env is as follows
```env
SS_DATABASE_SERVER="db"
SS_DATABASE_USERNAME="db"
SS_DATABASE_PASSWORD="db"
SS_DATABASE_NAME="db"
```

> [!NOTE]  
> *Background:* I make use of some internals of Silverstripe in testing that spins up a temp database to write data to and read from for tests.

Since database connections are all auto handled it makes the most sense to run this within `DDEV`.
Say there's some composer script call phpunit or what ever
```shell
ddev composer test
```
I'll get the follow error
```
Access denied for user 'db'@'%' to database 'ss_tmpdb_1695692556_3766499'
```

Ah, `db` user doesn't have full permissions. Cool, I'm only running locally right now, lets just use the root user.
```.env
SS_DATABASE_USERNAME="root"
SS_DATABASE_PASSWORD="root"
```

For what ever reason, I have to eventually run `ddev start`... 

❓ errors again, why?
`.env` has reverted back to this state.
```.env
SS_DATABASE_USERNAME="db"
SS_DATABASE_PASSWORD="db"
```

Overall I think this came about from the two paradigms of `migrating an existing project to DDEV` and `creating a new project at inception with DDEV running`

Who should do what.
It's kind that DDEV is attempting to help, however its overzealous right now.
Is it DDEV's job to edit my project to ensure it runs?
Arguably the `project-type` should.

> [!CAUTION]
> Ultimately I do not think this is an issue only for Silverstripe CMS projects.
One would not expect changes like this to happen and things to get overidden.

## Describe your solution

My ideal solution is for `ddev start` to not make any changes to my `.env` file. ever. 😅 

And to me the most sensible path forward is to severe the logic updating this on `ddev start`
A bonus would be for `ddev start` to report something is missing/undefined.
Extra extra bonus would be to offer updating it.

What/ if DDEV does actions with `ddev config`/ project set up is up for debate.
And potentially should be explored within it's own issue.
There are many possibilities...
- could create if not existing
- offer suggestions
- only create a base if there is no `.env` at all?

## Describe alternatives

Yes I am aware I could set these details within the `.ddev/config.yaml` under `web_environment` however that isn't a sensible solution.

1. my projects contain a `.env.dist` as an example for you to build from – implying I have control
1. `.ddev/config.yaml` makes the most sense to commit to a project, so if I make changes for my current work requirements I have to manually ensure I don't commit these changes now
1. I already use my .env to control all sorts of other things I shouldn't have to manage both it and a `.ddev/config.yaml`
  - I should not have to empty my `.env` into `.ddev/config.yaml` – some other tools might read that `.env`
  - I should not have to mess with a `.ddev/config.local.yaml`
  
  
  

For that database access one, I shouldn't have to mess with a post hook either to do that for me...
```yml
hooks:
    post-start:
      - exec: mysql -uroot -proot -hdb -e "GRANT ALL ON *.* TO 'db'@'%';"
```

### Additional context

I looked at trying to adjust this for Silverstripe https://github.com/ddev/ddev/pull/5380, being new to GO the tests on this PR were failing.
I was also informed that this should not be just a change for Silverstripe projects so have brought this around to be a larger discussion within DDEV.

That was around trying to reduce `WriteProjectEnvFile()` usage.

**Comment by n8-dev** [comment]
I think it should be noted that we are internally to avoid this issue doing the following:
1. specifically avoiding the project type value
2. manually adding associated DDEV commands that the project type would enable to projects
3. Linking to this issue in those commands to explain why they're there.


This is not ideal and project-type handles a lot of things that make sense for you automatically.
(upload_dir)

**Comment by GuySartorelli** [comment]
I avoid using the `silverstripe` project type for this exact reason.

Ideally imo the following should be true:

1. When creating a new project, if there is no `.env` file, a new `.env` file is created with appropriate default values.
2. At any time, if there is already an existing `.env` file, DDEV should at most:
    1. Add any missing default variables, and
    2. warn me if some values do not match the default values for the selected project type.
    3. MAYBE ask if it can change values - though 90% of the time I suspect if someone has set some values in their `.env` file, they do not want those values overridden. 
4. There could possibly be a global configuration option to allow opting-in to letting DDEV override `.env` values without asking first.

**Comment by tyler36** [comment]
If I am reading this correcly, it sounds like you want to [disable settings management](https://ddev.readthedocs.io/en/latest/users/configuration/config/#disable_settings_management)

```shell
ddev config --disable-settings-management=true 
```

This stops DDEV from making changes to the `.env` file. This is a pre-project setting.

**Comment by GuySartorelli** [comment]
Oh nice! Gotta love when things exist before you ask for them 😂👍

**Comment by tyler36** [comment]
Thank you. Updated the link.

**Comment by n8-dev** [comment]
Righttt...

I feel that needs somehow to be promoted to be found easier in docs, than just burried in a settings area...

Hmmm...
Stuff to ponder

**Comment by rfay** [comment]
The general idea is... read about settings so you understand what and why DDEV does things:

https://ddev.readthedocs.io/en/stable/users/usage/cms-settings/

The `silverstripe` project type was created and is maintained by the Silverstripe community. It exists for you, and if the community wants changes, well, let's get them done. but it wouldn't exist if not promoted and implemented by the Silverstripe community, and really, because you're the experts, you have to be the ones that make things work.

**Comment by n8-dev** [comment]
> @n8-dev where would you expect to see a mention of `ddev config --disable-settings-management`?


I guess I'm starting to think from the angle of docs around working with DDEV.
For lack of better terminology, Human centered docs.
Those kind of "Common actions", "Working as team", "Tips"....

Hmm.


I'm trying to remember why I didn't open this page whilst browsing around...


At least right now I'm tripping on `CMS` in the title.
Technically...
Is Laravel a CMS? https://ddev.readthedocs.io/en/stable/users/quickstart/#laravel

I guess I would have expected something mentioning about how to disable the update/overwrite next to words like this.


> ...
> The Laravel project type can be used for [Lumen](https://lumen.laravel.com/) like it can for Laravel. **_DDEV automatically updates or creates the .env file with the database information._**


Hmm...

I'll have a think..

Thank you for DDEV though 👏

**Comment by rfay** [comment]
DDEV is an open-source project, contributions are welcome. To improve the docs, click the pencil icon in the top of any docs page, thanks! Closing this for now.

**Comment by tyler36** [comment]
@n8-dev 

Also consider adding a PR to https://github.com/ddev/remote-config which displays the "tip of the day".

**Comment by GuySartorelli** [comment]
A warning would imply that it's best practice or at least recommended to disable settings management - but at least until now DDEV has tried to be beginner friendly to the extent that it's recommended to keep settings management enabled until/unless you need it disabled for your use case.
It can be debated whether that should remain the case, though.

I do like the idea of `ddev config` prompting you. That has two main benefits:
1. For anyone just getting started with DDEV, it's possibly the first time they're being introduced to the idea that DDEV will manage files outside of the `.ddev/` directory
2. For anyone who has used DDEV for a while but is running in auto-pilot, having an off day, hasn't started a project from scratch for a while, or for whatever reason has forgotten about settings management, it's a nice quick reminder at the time of starting a new project.

**Comment by stasadev** [comment]
I want to implement this, comment if you like it or not:

- #7309

**Comment by rfay** [comment]
Sorry, this important discussion should not take place in an old (solved) issue. Please don't do that.

Create a new issue, focus it on .env settings implementations like Craft/Laravel. It's important. 

To understand the history of this situation, note that first many CMS/Platforms that DDEV supported used PHP to load settings, so it was easy to add an "if" in there, so the settings were loaded only IF DDEV was running.

DDEV's creation of default database settings has been wildly successful and dearly loved for years. It can surely be done better with projects that use .env for database settings.

**Comment by ChloeSartorelli** [comment]
It was closed because it was a rejected idea. For my part (I won't speak for others), I wanted to make sure we weren't just suggesting essentially the same idea again which would just be closed again with discussion across multiple issues.

It's hard to know at what point discussion stops being about the old idea and starts being something completely new.

**Comment by rfay** [comment]
We would prefer not to make changes to the application's .env, and in Craft have succeeded in stopping doing that, by using `.ddev/.env.web` instead. Since we have better capabilities now, could that be done with Silverstripe?

**Comment by ChloeSartorelli** [comment]
Let's bring that question over to https://github.com/ddev/ddev/issues/7309 since @stasadev did end up creating a new issue for resolving this going forward.
