### ISSUE TITLE
blackfire upgrade is failing, needs to be fixed

### ISSUE THREAD

**Issue by rfay** [ddev/ddev#6078]
### Expected Behavior

```
ddev ssh
sudo apt update && sudo apt upgrade -y
```

gets

```
Preparing to unpack .../blackfire_2%3a2.26.3_arm64.deb ...
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
Unpacking blackfire (2:2.26.3) over (2:2.26.1) ...
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
dpkg: warning: old blackfire package post-removal script subprocess returned error exit status 1
dpkg: trying script from the new package instead ...
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
dpkg: error processing archive /var/cache/apt/archives/blackfire_2%3a2.26.3_arm64.deb (--unpack):
 new blackfire package post-removal script subprocess returned error exit status 1
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
dpkg: error while cleaning up:
 new blackfire package post-removal script subprocess returned error exit status 1
```

`apt-cache policy blackfire`:

```
root@82d8e99a1c9d:/# apt list --upgradable
Listing... Done
blackfire/any 2:2.26.3 arm64 [upgradable from: 2:2.26.1]
nodejs/nodistro 20.12.2-1nodesource1 arm64 [upgradable from: 20.12.1-1nodesource1]
root@82d8e99a1c9d:/# apt-cache policy blackfire
blackfire:
  Installed: 2:2.26.1
  Candidate: 2:2.26.3
  Version table:
     2:2.26.3 500
        500 http://packages.blackfire.io/debian any/main arm64 Packages
     2:2.26.2 500
        500 http://packages.blackfire.io/debian any/main arm64 Packages
 *** 2:2.26.1 500
        500 http://packages.blackfire.io/debian any/main arm64 Packages
        100 /var/lib/dpkg/status
     2:2.26.0 500
        500 http://packages.blackfire.io/debian any/main arm64 Packages
     2:2.25.0 500
        500 http://packages.blackfire.io/debian any/main arm64 Packages
     2:2.24.4 500
```

**Comment by rfay** [comment]
I am able to do ddev-webserver build successfully, so the upgrade may fail, but fresh install is OK. Short-term fix works to just rebuild ddev-webserver.

**Comment by rfay** [comment]
Requested support in https://platformsh.slack.com/archives/C0288FGG36Y/p1712785049032439

**Comment by rfay** [comment]
The blackfire problem is supposed to be solved in this (not public) MR:
https://lab.plat.farm/platformsh/observability/blackfire/blackfire.io/-/merge_requests/33680

"the fix was released in version 2.26.4 of the client."

**Comment by stasadev** [comment]
I see we still have the pin for blackfire:

https://github.com/ddev/ddev/blob/master/containers/ddev-webserver/ddev-webserver-base-files/etc/apt/preferences.d/blackfire

Should we revert it?

**Comment by rfay** [comment]
I think we should keep the pin. The current version wasn't working for arm64 still, and they stopped responding in slack and elsewhere.

**Comment by stasadev** [comment]
It's failing with newer version because of this https://docs.blackfire.io/up-and-running/agent-upgrade#drop-of-sysvinit-in-favor-of-systemd

And there is a `blackfire/blackfire` Docker image available, so we can consider replacing core support with an add-on.

**Comment by rfay** [comment]
We should consider just removing blackfire. We don't know that anybody anywhere uses it.

**Comment by rfay** [comment]
Another option is to see if there's any help in their Discord.

**Comment by rfay** [comment]
Maybe we should remove blackfire in next major release with a note that we'll be happy to put together an add-on if anybody notices.

**Comment by tyler36** [comment]
My vote is to remove it. The community will provide an addon, if there is a big enough demand.
