### ISSUE TITLE
Update `schema.json` for v1.23 major release

### ISSUE THREAD

**Issue by stasadev** [ddev/ddev#6097]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Output of `ddev debug test`

<details><summary>Expand `ddev debug test` diagnostic information</summary>

```
[COPY-PASTE HERE THE OUTPUT OF `ddev debug test`]
```
</details>         

### Expected Behavior

`schema.json` should contain actual values.

### Actual Behavior

I noticed that `corepack_enable` is highlighted in red in PhpStorm.

### Steps To Reproduce

View the latest `config.yaml` in PhpStorm.

### Anything else?

Review `schema.json` for deprecated and obsolete values.

**Comment by rfay** [comment]
Nice catch!

**Comment by rfay** [comment]
It would be great to fix 
* https://github.com/ddev/ddev/issues/6100

as well.
