### ISSUE TITLE
DDEV version constraint

### ISSUE THREAD

**Issue by claudiu-cristea** [ddev/ddev#6109]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

When a new DDEV version comes out, I want to make sure the whole team will update their binaries. I would expect that a certain state of `.ddev/config.yaml` to require a specific minimum version of DDEV.

### Describe your solution

Add a constraint in `.ddev/config.yaml` that would make impossible to use that code with a lower DDEV version, e.g., `ddev_version: ^1.23`

When a new DDEV is coming out, and `ddev config --auto` is run, `.ddev/config.yaml`, which is under VCS control, is updated. Then the constraint is manually updated. The team will not be able to run an older DDEV with the new code. Consider to automatically update the `.ddev/config.yaml` constraint as part of `ddev config --auto` run.

**Comment by penyaskito** [comment]
This is already a thing since 1.22.4:

https://ddev.readthedocs.io/en/stable/users/configuration/config/#ddev_version_constraint

I'm leaving this open because of 

> Consider to automatically update the .ddev/config.yaml constraint as part of ddev config --auto run.

which might require further discussion if we want to do.

**Comment by claudiu-cristea** [comment]
Sorrrrrryyyy! 😀 I've missed that

**Comment by rfay** [comment]
We won't be doing anything automatically to the config wrt the version constraint, because that would violate the whole idea. 

Closing! Wow you got that feature really, really fast! :)
