### ISSUE TITLE
Upgrade SQLite to version >= 3.45.0 to support Drupal 11

### ISSUE THREAD

**Issue by rpkoller** [ddev/ddev#6110]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

I wanted to give https://github.com/justafish/ddev-drupal-core-dev/pull/23 a final run through and cross check the successful test with 1.23.0 @simesy ran. But i ran into a new error i haven't encountered yet: 
![Screenshot 2024-04-17 at 13 22 32](https://github.com/ddev/ddev/assets/1665422/408951af-2f36-4ee3-a245-f459c423e006)
in the container i have: 
`3.40.1 2022-12-28 14:03:47 df5c253c0b3dd24916e4ec7cf77d3db5294cc9fd45ae7b9c5e82ad8197f3alt1`
on my host: 
`3.43.2 2023-10-10 13:08:14 1b37c146ee9ebb7acd0160c0ab1fd11017a419fa8a3187386ed8cb32b709aapl (64-bit)`

Turns out a critical issue got merged into Drupal Core yesterday upgrading SQLite to version 3.45: 
https://www.drupal.org/project/drupal/issues/3420972

### Describe your solution

Upgrade SQLite to version >= 3.45.0 in the webcontainer if possible

**Comment by rpkoller** [comment]
Oh no the policy was agreed on earlier: https://www.drupal.org/project/drupal/issues/3346338 the link in the issue summary only references the tests. But on previous tests the weeks before it never failed on the SQLite requirement yet.

**Comment by stasadev** [comment]
Workaround using the `sqlite3` package from Debian 13 Trixie:

```
$ cat .ddev/web-build/Dockerfile.sqlite
ARG TARGETPLATFORM
RUN SQLITE_VERSION=3.45.1 && \
    mkdir /tmp/sqlite3 && \
    wget -O /tmp/sqlite3/sqlite3.deb https://ftp.debian.org/debian/pool/main/s/sqlite3/sqlite3_${SQLITE_VERSION}-1_${TARGETPLATFORM##linux/}.deb && \
    wget -O /tmp/sqlite3/libsqlite3.deb https://ftp.debian.org/debian/pool/main/s/sqlite3/libsqlite3-0_${SQLITE_VERSION}-1_${TARGETPLATFORM##linux/}.deb && \
    dpkg -i /tmp/sqlite3/*.deb && \
    rm -rf /tmp/sqlite3
```

```
$ ddev exec sqlite3 --version
3.45.1 2024-01-30 16:01:20 e876e51a0ed5c5b3126f52e532044363a014bc594cfefa87ffb5b82257ccalt1 (64-bit)
```

If this is only needed for tests, then I think it's better to add it to https://github.com/justafish/ddev-drupal-core-dev/blob/main/web-build/Dockerfile

**Comment by rpkoller** [comment]
thank you! no i just stumbled across the requirement in my latest test, before that i never ran into that issue. and it is not about tests. Drupal 11 will have the minimum requirement of SQLite 3.45.0 (when Drupal 11 is released is not decided yet, either in june 2024 or december 2024). and with that add-on you actually use the main branch of drupal which equals to 11.x-dev@dev and the add-on uses SQLite instead of using any of ddevs db containers. so with the add-on you actually using sqlite for running the site. 
in the short term i agree the best might be to make the adjustment in the dockerfile of the add-on. will take a look at https://ddev.readthedocs.io/en/latest/users/extend/customizing-images/#adding-extra-dockerfiles-for-webimage-and-dbimage in addition to your example (cuz i guess to properly uprade the version of sqlite in the addons dockerfile it has to reside somewhere else than in a temp directory?). and in the long run it might be good if the sqlite version could be upgrade in the ddev web container.

**Comment by stasadev** [comment]
> to properly uprade the version of sqlite in the addons dockerfile it has to reside somewhere else than in a temp directory?

No, it is installed properly where it should be, I just download the installation files to a temporary folder and then clean it.

> Drupal 11 will have the minimum requirement of SQLite 3.45.0

Okay. Then let's wait for @rfay's decision on this (in fact, we can do the same thing in the webserver Dockerfile).

**Comment by rpkoller** [comment]
> No, it is installed properly where it should be, I just download the installation files to a temporary folder and then clean it.

ahhhhhh! i've assumed since you've mentioned, if it should be used for testing only, it would only temporarily install the version and then remove it again :D (i am not a developer ;) ). but yep i've simply pasted the snippet you've provided into the add-ons docker file and that fixes the problem. excellent! thank you!

> Okay. Then let's wait for @rfay's decision on this (in fact, we can do the same thing in the webserver Dockerfile).

yep completely agree

**Comment by rfay** [comment]
I think it's completely weird that they'd move to a non-stable version of sqlite.  Some strange decisions in Drupal 11.

Since sqlite is normally used by D11 only for testing, it will be easy to add this to an add-on like justafish and be solved that way.

**Comment by rpkoller** [comment]
hm according to the [issue summary](https://www.drupal.org/project/drupal/issues/3346338)

> Debian and Ubuntu both have releases scheduled prior to Drupal 11's earliest release date which will support SQLite 3.45.

it sounds like debian and ubuntu ship releases supporting 3.45 prior to the release of Drupal 11. that way it sounds reasonable. it is just tricky and problematic in the context of local environment like ddev that run into those requirements earlier.

**Comment by rfay** [comment]
It's not true that Debian Trixie will be released before Drupal 11. In fact, Debian never commits to release dates. (But Debian Trixie, aka "testing" does have this version in it.) I guess one could say it's not true that Debian Trixie will become stable (released from "testing")

It is true that Ubuntu 24.04, coming out on April 24,  will have Sqlite3 3.45.1

We can use these techniques to install sqlite3 in Debian Bookworm as a perhaps more robust approach: 
https://serverfault.com/questions/22414/how-can-i-run-debian-stable-but-install-some-packages-from-testing

**Comment by rfay** [comment]
I just ran through this answer, https://serverfault.com/a/22421/79810 and it worked fine for me. However, it required editing 2 files in /etc/apt and then also doing the `apt install -t trixie sqlite3` to a Dockerfile. But it also provides trixie packages to people who need them. There are problems with mixing systems. Not sure how bad they are for just sqlite3.

A note: I think Trixie (testing) was probably affected by the xzutils problem. That's the way these things are.

**Comment by rfay** [comment]
I thought it would be easy to do this because I could manually use the technique, but it broke later `apt install` things. https://github.com/rfay/ddev/tree/20240417_sqlite3_trixie

In general, it's a bad idea to mix Debian releases.

**Comment by rfay** [comment]
@stasadev I think sqlite3 depends on libsqlite3, and probably phpX.X-sqlite3 depend on these as well. 

So @rpkoller using that technique requires more than just getting past the requirements stage, it requires running tests that use sqlite.

**Comment by stasadev** [comment]
> I think sqlite3 depends on libsqlite3, and probably phpX.X-sqlite3 depend on these as well.

I install `libsqlite3-0` in my `Dockerfile`, otherwise it wouldn't work at all.

And I compared the dependency list before providing a workaround (there is only `libsqlite3-0` that matters):
https://packages.debian.org/trixie/sqlite3
https://packages.debian.org/bookworm/sqlite3

phpX.X-sqlite3 - I don't think it depends on a specific `sqlite3` build, @rpkoller ran Drupal tests (from what I read) and it seems to have worked.

**Comment by rfay** [comment]
Commented on the upstream issue in [Set the SQLite minimum requirement to at least 3.45](https://www.drupal.org/project/drupal/issues/3346338#comment-15572139)

**Comment by rfay** [comment]
I think we could probably solve this with a Dockerfile layer added to Drupal 11 type without risk.

**Comment by steffenr** [comment]
Thanks for clarification. Just had the same problem with an older Drupal 11.0.1 project, which i updated to latest Drupal 11.1.0. 
By running `ddev config` in the project and selecting **drupal11**, the configuration is rewritten and the appropriate images are updated..
