### ISSUE TITLE
`ddev debug test` may have conflicts when running sequentially (and `ddev debug testcleanup` have no effect)

### ISSUE THREAD

**Issue by stasadev** [ddev/ddev#6111]
### Is there an existing issue for this?

- [X] I have searched the existing issues

From Discord:
https://discord.com/channels/664580571770388500/1230114214182522922/1230114214182522922

### Output of `ddev debug test`

<details><summary>Expand `ddev debug test` diagnostic information</summary>

```
[COPY-PASTE HERE THE OUTPUT OF `ddev debug test`]
```
</details>

### Expected Behavior

Each `ddev debug test` should succeed and cleanup after itself.

### Actual Behavior

1. `host port 60001 has already been allocated`:
```
...
Configuring a 'php' project with docroot 'web' at /home/stas/code/ddev/tryddevproject-5008/web
could not write DDEV config file /home/stas/code/ddev/tryddevproject-5008/.ddev/config.yaml: host port 60001 has already been allocated to project tryddevproject-27049
...
```

2. There is `ddev stop --unlist` at the end of the script, which does not clean up Docker resources.

### Steps To Reproduce

Run `ddev debug test`
Abort the test before `ddev stop --unlist`:
```
======== Thanks for running the diagnostic! ========
Running ddev launch in 3 seconds
Running ddev launch
Waiting 10 seconds to run ddev stop --unlist
^C
```
Run `ddev debug test` again, see an error

### Anything else?

Maybe it is better to add `ddev debug testcleanup` at script start and script end, because when you run `ddev stop --unlist`, the test project cannot be removed with cleanup command.

**Comment by rfay** [comment]
I actually removed the cleanup function in this last round, so that's the direct cause of this. The reason for removal was that it prevented debugging the existing problem site. But obviously needs to be looked at again.

A side-note is that when `ddev debug test` is working it cleans up after itself now and makes `ddev debug testcleanup` obsolete.

**Comment by rfay** [comment]
> host port 60001 has already been allocated to project

I wonder what's up with that, because we don't allocate ports normally for one of these. This may be a docker failure?

**Comment by stasadev** [comment]
> host port 60001 has already been allocated to project

It is hard-coded...

https://github.com/ddev/ddev/blob/56087f9f8f87ba2df0cd91b7cfec8af65df6c577/cmd/ddev/cmd/scripts/test_ddev.sh#L68

> A side-note is that when ddev debug test is working it cleans up after itself now and makes ddev debug testcleanup obsolete.

No, the only thing it does is `ddev stop --unlist`, and that's it.

---

There were so many changes, I simply didn't notice these on review.

**Comment by rfay** [comment]
> It is hard-coded...

I have no idea why I did that.

> No, the only thing it does is ddev stop --unlist, and that's it.

That cleans up everything except an empty database, but you're right.
