### ISSUE TITLE
`ddev snapshot --list` output could be easier to read

### ISSUE THREAD

**Issue by bmartinez287** [ddev/ddev#6116]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

Is super hard to visually parse snapshots once you get more than 3 and the date attached to the file name is handy development wise but if i rename the file i lose that info. Also, the dates can be easier to read as part of a new field.
### Describe your solution

![Screenshot 2024-04-18 at 2 11 44 PM](https://github.com/ddev/ddev/assets/39039024/0fcd96bd-ff2a-4f7b-825a-36d4884c2b24)
I like how DDEV describe adds a nice easy to read table.

It be nice if `ddev snapshot --list` had the following columns instead of the paragraph which is harder to parse visually.

Name - Created on - Location

### Extra credit.

Also this might be a slightly different issue but as seen in the picture below there is no
`ddev snapshot restore [name]` Example.

So the one thing I'm sure some including me have to do is go into the docs to find how to restore a file.
Knowing how to restore a file should be the first or second example on that list.

![Screenshot 2024-04-18 at 2 00 54 PM](https://github.com/ddev/ddev/assets/39039024/fe90be0b-99b0-4b60-846e-2e68be54f47f)

**Comment by bmartinez287** [comment]
Seems like this be mostly modifying the command below.
https://github.com/ddev/ddev/blob/master/cmd/ddev/cmd/snapshot.go#L59

Looks like this does the list
https://github.com/ddev/ddev/blob/master/cmd/ddev/cmd/list.go
but i haven't found where the template for that table output is at.


Looks like this should address the extra section above.
https://github.com/ddev/ddev/blob/master/cmd/ddev/cmd/snapshot.go#L28

**Comment by bmartinez287** [comment]
Found it https://github.com/ddev/ddev/blob/master/pkg/ddevapp/list.go#L101
Mmm, maybe it can be extracted and use to replace the outcome from
https://github.com/ddev/ddev/blob/master/pkg/ddevapp/snapshot.go#L71

**Comment by rfay** [comment]
Real extra credit: Use Bubbletea and family, 
* https://github.com/ddev/ddev/issues/5762

**Comment by rfay** [comment]
You know that `ddev snapshot restore` has a nice interactive selection, right?

Could you please give a specific example of what you'd like? (Please stay on one topic). Please update the title to say exactly what you're interested in, instead of "could be easier". Thanks!

**Comment by GuySartorelli** [comment]
I've raised https://github.com/ddev/ddev/pull/6490 to tackle this.
