### ISSUE TITLE
Don't disable ssh-agent by default on gitpod

### ISSUE THREAD

**Issue by jonaseberle** [ddev/ddev#6132]
Hi and thank you for this amazing project! How it works is magic to me but I try to understand :)

I use the URL-generator https://ddev.github.io/ddev-gitpod-launcher/ to launch a Gitpod instance on a DDEV project.
It is great how seamlessly that works and how fast the Gitpod instance is!

We are working with the ssh-agent in custom DDEV `pull` providers.

I found `ddev auth ssh` works well in Gitpod when I edit `~/.ddev/global_config.yaml` and just remove `ddev-ssh-agent` from `omit_containers:`, then `ddev poweroff`.

But I have to do it every time I reenter the Gitpod workspace.

Could the ssh-agent be enabled by default?

**Comment by rfay** [comment]
It should work for you now @jonaseberle, but do tell us how you manage the ssh key you need there.

**Comment by jonaseberle** [comment]
Thank you, that works.

Re: SSH keys in Gitpod
So far I have been either generating them on the system (`ssh-keygen`) and pushed them to the server (`ssh-copy-id`) or copied my local private key to the gitpod server manually. It vanishes after a gitpod instance stop/start, though so we would have to find a solution for that if we would want to use Gitpod more often.

**Comment by rfay** [comment]
The way Drupalpod does it is they store the private key in a Gitpod environment variable and write it into the .ssh dir. 

https://github.com/shaal/DrupalPod
