### ISSUE TITLE
Installation information for Ubuntu 24.04

### ISSUE THREAD

**Issue by tomasnorre** [ddev/ddev#6142]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

After updating to Ubuntu 24.04 LTS, the apt/sources files have changed. 

The format is now.
```
Types: deb
URIs: http://dk.archive.ubuntu.com/ubuntu/
Suites: noble noble-updates noble-backports
Components: main restricted universe multiverse
Signed-By: /usr/share/keyrings/ubuntu-archive-keyring.gpg
```

If one upgrade from e.g. 22.04 LTS to 24.04 LTS isn't not a problem as the apt-migration process is converting them correctly. 

But if installing them on a fresh Ubuntu 24.04 LTS, with the instructions in the currect documentation, it doesn't work the old format gets ignored. 

### Describe your solution

The documentations should for Ubuntu 24.04 LTS be updated. 
https://github.com/ddev/ddev/blob/6cb25692aababe47c3bf8b1b02e5f474b3599de1/docs/content/users/install/ddev-installation.md?plain=1#L53

I don't know exactly yet, how this should be, but can try to investigate. 

I think we need to split the Debian/Ubuntu into an additional option Ubuntu 24.04 LTS

**Comment by stasadev** [comment]
I tested this on Ubuntu 24.04, and we don't really need to change anything (the old syntax is still supported):

```
$ cat /etc/apt/sources.list.d/ddev.list
deb [signed-by=/etc/apt/keyrings/ddev.gpg] https://pkg.ddev.com/apt/ * *
```

New syntax (note the file name change, this is **important**):

```
$ cat /etc/apt/sources.list.d/ddev.sources
Types: deb
URIs: https://pkg.ddev.com/apt/
Suites: *
Components: *
Signed-By: /etc/apt/keyrings/ddev.gpg
```

**Comment by rfay** [comment]
I also have done Ubuntu 24.04 installation without any trouble using the regular instructions from https://ddev.readthedocs.io/en/stable/users/install/ddev-installation/#linux

**Comment by rfay** [comment]
@stasadev where is the upstream where the style is changing? Debian Trixie inherited by Ubuntu 24.04? Do you have a link?

**Comment by tomasnorre** [comment]
> I tested this on Ubuntu 24.04, and we don't really need to change anything (the old syntax is still supported):

That's true. But I would always prefer the suggestion syntax instead of the legacy one. But sure, it doesn't need to change to work.

**Comment by rfay** [comment]
@stasadev says it's supported since long ago. If it's good for Ubuntu 20.04+ and Debian 11 Bullseye+ then I'm fine with updating the syntax used in the docs.

**Comment by stasadev** [comment]
> @stasadev says it's supported since long ago

I didn't say that 😅. The first appearance of this syntax is in Debian 12, and Ubuntu 24.04.

> That's true. But I would always prefer the suggestion syntax instead of the legacy one. But sure, it doesn't need to change to work.

I agree that we should switch to a new syntax at some point, but people tend to copy and paste commands without reading them.

**Comment by rfay** [comment]
Let's stick with the old-fashioned for now then, thanks. It will be a few years before people switch over.

**Comment by tomasnorre** [comment]
I'm OK with closing the issue to not clutter up the issue tracker.

**Comment by rfay** [comment]
Closing for now, thanks for reporting, and please reopen in the future when you think the time has come.
