### ISSUE TITLE
DDEV support in Drupal Starshot

### ISSUE THREAD

**Issue by gitressa** [ddev/ddev#6158]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

This is just to make the DDEV developers aware of the issue https://github.com/phenaproxima/starshot-prototype/issues/49 in https://github.com/phenaproxima/starshot-prototype for https://www.drupal.org/starshot. (Maybe I could mention a DDEV developer, in that issue and the person would get pinged? I am not sure ....)

### Describe your solution

Perhaps the DDEV developers got an idea how to solve this best?

**Comment by rfay** [comment]
Thanks. @penyaskito is already looking around to see what might need to be done.

**Comment by gitressa** [comment]
Thanks for looking into this @rfay and @penyaskito -- @phenaproxima just made a great solution, see https://github.com/phenaproxima/starshot-prototype/pull/50.

**Comment by gitressa** [comment]
Just leaving a comment here, that some folders have started being owned by root in the Starshot project ... maybe someone from the DDEV team can check it out? https://github.com/phenaproxima/starshot-prototype/issues/94

**Comment by rfay** [comment]
As commented there, I'd love to help you debug this @gitressa because something is seriously wrong with either your docker setup or the starshot setup (something is mounting the project as root)
