### ISSUE TITLE
config --update do not update mariadb version for Drupal 11 and does not trigger any information

### ISSUE THREAD

**Issue by plopesc** [ddev/ddev#6160]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Output of `ddev debug test`

<details><summary>Expand `ddev debug test` diagnostic information</summary>

```
[COPY-PASTE HERE THE OUTPUT OF `ddev debug test`]
```
</details>

### Expected Behavior

When running `ddev config --update` in a project with latest Drupal 11 codebase, and the container was set to mariadb 10.4, the output should indicate that mariadb has to be updated manually to 10.6 after ensuring that volume data is saved. 

### Actual Behavior

The output shows that `ddev config --update` execution is successful.
```
$ ddev config --update                      
You are reconfiguring the project at /home/plopesc/projects/lullabot/core.
The existing configuration will be updated and replaced.
Auto-updating project configuration because update is requested.
Configuring a 'drupal' project with docroot '' at /home/plopesc/projects/lullabot/core
Configuration complete. You may now run 'ddev start'.

```

**Comment by rfay** [comment]
Hi @plopesc - If you have an existing "latest drupal11 codebase" then it would not have had a mariadb:10.4 configuration. 

DDEV refuses to risk your existing databases, so it will not upgrade them for you. You will need to reconfigure as needed. 

```
ddev export-db --file=/tmp/db.sql.gz 
ddev delete 
ddev config --database=mariadb:10.11
ddev start
ddev import-db --file=/tmp/db.sql.gz
```

But since you can't take the database with you anyway to drupal 11 (right?) then just `ddev delete -Oy && ddev config --database=mariadb:10.11`

**Comment by rpkoller** [comment]
no i think @plopesc's point was that the user isn't informed in the output that `ddev config --update` returns, that the database the project currently uses is dated compared to the version the project should actually be using after running the update command:

```
You are reconfiguring the project at /home/plopesc/projects/lullabot/core.
The existing configuration will be updated and replaced.
Auto-updating project configuration because update is requested.
Configuring a 'drupal' project with docroot '' at /home/plopesc/projects/lullabot/core
Configuration complete. You may now run 'ddev start'.
```
at the moment there is no cue and call to action here telling the user you have mariadb version 10.4, you should manually update to version 10.11 or something like that. to make the user aware of that shortcoming. and i agree that the user should be informed about that imho

**Comment by stasadev** [comment]
Take a look at this:

- #6165

**Comment by plopesc** [comment]
Thank you!
