### ISSUE TITLE
Traefik cert files not gitignored after renaming a project

### ISSUE THREAD

**Issue by mandrasch** [ddev/ddev#6164]
### Is there an existing issue for this?

- [X] I have searched the existing issues

```
# .ddev/config.yaml
name: craft5-green-coding-jobs
```

ddev version v1.23.0

### Expected Behavior

After renaming a project, auto-generated `.ddev/gitignore` should still work.

### Actual Behavior

This is just a minor thing I noticed.

I renamed a project and noticed that some files in `.ddev/traefik` are not git-ignored automatically anymore. 

<img width="315" alt="image" src="https://github.com/ddev/ddev/assets/777278/bc20b065-5e2c-4903-9929-fc86fa1fc8c9">

This is because they are based on the project name in the auto-generated `.ddev/gitignore`:

```
/traefik/config/craft5-green-coding-jobs.yaml
/traefik/certs/craft5-green-coding-jobs.crt
/traefik/certs/craft5-green-coding-jobs.key
```

A current workaround is just to delete `.ddev/gitignore` and run `ddev start` again, gitignore is updated. 

### Steps To Reproduce

1. Delete existing project via `ddev delete`
1. Change `name` in `.ddev/config.yaml`
1. Run `ddev start`

### Anything else?

https://ddev.readthedocs.io/en/latest/users/usage/faq/#how-can-i-change-a-projects-name could maybe cover this case, but maybe automatically re-generating the gitignore file on fresh project starts is also possible. Thanks!

**Comment by stasadev** [comment]
I can't reproduce it, my `.ddev/.gitignore` is updated every time I run `ddev start` with the correct values for:
```
/traefik/config/project-name.yaml
/traefik/certs/project-name.crt
/traefik/certs/project-name.key
```

**Comment by mandrasch** [comment]
Oh sorry, on second attempt it runs here as well. Guess I didn't wait for `ddev start` to complete, sorry! Thanks very much for checking!
