### ISSUE TITLE
flag to skip post-import-db-* hooks when using import-db

### ISSUE THREAD

**Issue by hanoii** [ddev/ddev#6185]
A colleague asked me about this and I was surprised to not find a native way of doing it.

I wonder if this is something logical to add?

**Comment by rfay** [comment]
This would be a duplicate of
* https://github.com/ddev/ddev/issues/2129
true?

**Comment by hanoii** [comment]
True

**Comment by rfay** [comment]
#2129 seems like a modest effort and right up your alley for a contribution :)

**Comment by hanoii** [comment]
I'll take a look
