### ISSUE TITLE
Support project directories containing underscores

### ISSUE THREAD

**Issue by mbomb007** [ddev/ddev#6206]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

Drupal modules frequently contain underscores in the project names. It's annoying to have to specify a different project name, or manually convert underscores to hyphens, each time I create a DDEV project for one. It seems a bit arbitrary that underscores aren't allowed.

### Describe your solution

Allow underscores in project names.

### Describe alternatives

Automatically convert underscores to hyphens and use that as the default project name when running `ddev config`.

**Comment by rfay** [comment]
As you see in the error message, underscores cannot be used in domain names, and so are excluded for that reason. You can easily change the name of your project with `ddev config --project-name=module-name` instead of `module_name`

**Comment by rfay** [comment]
I don't see any harm in the suggestion of swapping underscore for hyphen in the default project name. A PR would be welcome.

Note that you can also improve your alias to do this quite trivially.

Also note that `mariadb:10.11` is the current default, so you don't need that in there. Also note that if your project is already populated with code and it's a Drupal 10 project, it will autodetect the docroot and project type if that's useful to you.

**Comment by rfay** [comment]
No worries, it will get reviewed. It may need some improvement to tests to make sure this permutation gets tested.
