### ISSUE TITLE
DDEV could manage Docker providers and offer hosting providers

### ISSUE THREAD

**Issue by bmartinez287** [ddev/ddev#6215]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

At DrupalCon Portland a few improvements were discussed.

1. DDEV should start colima, docker desktop, or its primary docker environment upon running a `ddev start` instead of just failing. If multiple environments are detected such as docker desktop and colima, the user could be prompted with an option to start either. If only one is present then 
2. DDEV hosting providers could be included as part of `ddev config` and have their setup simplified. Probably at the end of the current prompts, we could ask the user if they would like to set up a hosting provider and based on that create .env file and place their tokens in there.

### Describe your solution

see above

### Additional context

All of this with goal of increasing developer adoption as we ease their transition from other tools.

**Comment by rfay** [comment]
One suggestion per issue is better :)

My first impression is that we could not successfully manage all the Docker providers in the world. Docker Desktop does not even have a command-line interface. And on WSL2 Docker Desktop users don't have access to the Windows side; For docker-ce sudo would be required. 

I don't think the majority of users use the hosting providers, and we aren't even aware of most of the ones people use outside the Drupal ecosystem, except Platform.sh

**Comment by rfay** [comment]
One of the worst things historically about Lando is its attempt to manage Docker Desktop. By default, from years back, it has depended on an explicit (and usually outdated) version of Docker Desktop, and has installed that version by default during its install process. Having experienced that in the earliest days we always committed to avoiding that kind of thing.

**Comment by bmartinez287** [comment]
It's true we don't know what people use outside of the Drupal ecosystem use, it be great to hear from them.
However, most of the feedback i collected lately on why some people hesitate to try DDEV is due to the fact they will like an a easier hosting provider experience. We already do this for the technologies themselves drupal, wordpress, craftcms and many others, It just be that experience for hosting providers for those that need that.

We already have the ability for them to put variables on their .env or config.yml but a wrapper that does it for you after you enter a key/token would be interesting for early adoption.

In regards to manage docker providers. I can see how that be a challenge. I will look into it a bit more. If DDEV is aware that it ran inside colima or docker desktop maybe it can prompt back what the command is for the last environment it ran into. Save the environments on some sort of log. So instead of just Could not connect to a docker provider maybe it can give hints to which ones it has connected before and the command to start them. Start small and move on from there.

**Comment by rfay** [comment]
Thanks for listening to people!

> However, most of the feedback i collected lately on why some people hesitate to try DDEV is due to the fact they will like an a easier hosting provider experience. We already do this for the technologies themselves drupal, wordpress, craftcms and many others, It just be that experience for hosting providers for those that need that.

I'd be interested in more explicit feedback about people's challenges. People use such a huge variety of hosting providers that I don't know how to handle that well.

Also note that DDEV's goal is to be a local development environment, so that's always going to be our focus.

**Comment by bmartinez287** [comment]
That makes sense, i will look into it some more. The idea is to use what we already and wrap it from a different angle. Get the 80% gains with 20% of the effort. Local first but once you are ready hit
I imagine something like this
```
ddev config platformsh
What is your platformsh token?
[user enter token]
Done. ddev pull to get your db from pantheon

ddev config acquia
What is your pantheon key?
[user enter token]
Done.
```
I use those two since I'm most familiar with them but the idea is if some need an extra variable it be on more step but that be it and then ddev pull be linked.

Behind the scenes the env file will be populated on that given project.

Ps: I just noticed there used to be a `ddev config pantheon` that gives me a warning. I might check on what happen with that get some of that history.

**Comment by rfay** [comment]
> Ps: I just noticed there used to be a ddev config pantheon that gives me a warning. I might check on what happen with that get some of that history.

DDEV hasn't had `ddev config pantheon` for 2-3-4 years, since the hosting provider stuff was completely redone.

**Comment by rfay** [comment]
I think this started out about DDEV managing/installing Docker providers. I see no way to do that given the scope of where DDEV is used.  That is also a very significant problem with Lando, that it takes that responsibility (and installs Docker Desktop without clear interaction). 

If that's what this issue is about, I'm going to close it. If you have another issue about hosting providers, please open another issue and state it clearly. Thanks!
