### ISSUE TITLE
Create Sulu CMS Quickstart

### ISSUE THREAD

**Issue by rfay** [ddev/ddev#6230]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

[Sulu](https://sulu.io/) is a Symfony-based CMS which could very well profit from using DDEV.

### Describe your solution

Let's start by creating a PR for a quickstart.

**Comment by rpkoller** [comment]
https://github.com/ddev/ddev/pull/6256
