### ISSUE TITLE
Support for MySQL 8.4

### ISSUE THREAD

**Issue by ajibarra** [ddev/ddev#6241]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

MySQL 8.4 was released last month and it is an LTS version. It includes several changes and it would be a great addition to the project.

The release notes here: https://dev.mysql.com/doc/relnotes/mysql/8.4/en/news-8-4-0.html

### Describe your solution

Add MySQL 8.4 support

**Comment by rfay** [comment]
Thanks so much for this. Are you planning on using mysql 8.4 any time soon in production?

I see there's now already an official Docker image, so that's one step forward, https://hub.docker.com/_/mysql/tags?page=&page_size=&ordering=&name=8.4

Percona Xtrabackup does not yet have an 8.4 version, which we'll need (`ddev snapshot` depends on it for mysql). But hopefully they'll catch up soon.

**Comment by rfay** [comment]
Percona Xtrabackup does not yet have 8.4 support, we'll be waiting for that, otherwise we can't do snapshots.

**Comment by enoliveiraic** [comment]
When we will have the percona-xtrabackup-84 available to install?

**Comment by rfay** [comment]
It looks like they're getting closer:
* https://github.com/percona/percona-xtrabackup/pull/1594

**Comment by rfay** [comment]
Since you're eager, please check their downloads from time to time to see when they add it. https://www.percona.com/downloads

I imagine it will be a new tab?

<img width="867" alt="image" src="https://github.com/user-attachments/assets/141e889e-e49b-43f4-96fb-63a83c5f18a2">

**Comment by rfay** [comment]
Although Xtrabackup 8.4 has now been released, there is no arm64 support, although they've promised arm64 builds.

**Comment by rfay** [comment]
We should fix 
* https://github.com/ddev/ddev/issues/6511

when working on this.

**Comment by rfay** [comment]
The PXB Xtrabackup issue is https://perconadev.atlassian.net/issues/PXB-2464

**Comment by rfay** [comment]
Opened new issue [percona-release setup pxb84-lts fails due to directory naming](https://perconadev.atlassian.net/issues/PXB-3361)

**Comment by rfay** [comment]
I see some specialty code for MySQL 8.0+ that probably needs to be removed now:

https://github.com/ddev/ddev/blob/507cfca2508b97786b80e8b8c83ea17f5c0fea20/pkg/ddevapp/ddevapp.go#L2539-L2542

**Comment by rfay** [comment]
xtrabackup for debian mysql 8.0 arm64 is now available at https://www.percona.com/downloads

**Comment by rfay** [comment]
If we don't get percona-xtrabackup in percona-setup before the DDEV v1.24.0 release we can just punt this until v1.24.1.
