### ISSUE TITLE
Add-on is installing global custom command, but it can't be accessed (with DDEV HEAD) at ~/.ddev/commands

### ISSUE THREAD

**Issue by rfay** [ddev/ddev#6252]
### Discussed in https://github.com/orgs/ddev/discussions/6251

From @apotek:

<div type='discussions-op-text'>

<sup>Originally posted by **apotek** May 28, 2024</sup>
Hello, I have an add-on at https://github.com/ChromaticHQ/ddev-dblog/. Three days ago, it's test began to fail. 

Leaving alone the bizarre fact that `stable` passes but HEAD doesn't even though they are identical, in the HEAD test output, there is no indication of the failure point. Everything looks fine until 

> not ok 1 install from release
> \# (in test file tests/test.bats, line 71)
> \#   `ddev get chromatichq/ddev-dblog' failed

<details><summary>More context...</summary>
<pre>
Bash completion has been installed to:
  /home/linuxbrew/.linuxbrew/etc/bash_completion.d
Run ddev debug download-images >/dev/null
  ddev debug download-images >/dev/null
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    HOMEBREW_NO_INSTALL_FROM_API: 
Run cd ./ && bats tests
  cd ./ && bats tests
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    HOMEBREW_NO_INSTALL_FROM_API: 
    DDEV_GITHUB_TOKEN: ***
    DDEV_NONINTERACTIVE: true
    DDEV_NO_INSTRUMENTATION: true
1..3
# ddev get chromatichq/ddev-dblog with project ddev-dblog in /home/runner/tmp/test-ddev-dblog (/home/runner/tmp/test-ddev-dblog)
not ok 1 install from release
# (in test file tests/test.bats, line 71)
#   `ddev get chromatichq/ddev-dblog' failed
# Creating a new DDEV project config in the current directory (/home/runner/tmp/test-ddev-dblog)
# Once completed, your configuration will be written to /home/runner/tmp/test-ddev-dblog/.ddev/config.yaml
# 
# Configuring a 'php' project named 'ddev-dblog' with docroot '' at '/home/runner/tmp/test-ddev-dblog'.
# For full details use 'ddev describe'.
# Configuration complete. You may now run 'ddev start'.
# ssh-agent container is running: If you want to add authentication to the ssh-agent container, run 'ddev auth ssh' to enable your keys.
# Not trying to add hostnames because DDEV_NONINTERACTIVE=true
# .....Installing chromatichq/ddev-dblog:v1.0.0
# Downloading https://api.github.com/repos/ChromaticHQ/ddev-dblog/tarball/v1.0.0
# 
# Installing global components:
# 👍 commands/db/dblog
# 
# Executing post-install actions:
# chmod: cannot access '/home/runner/.ddev/commands/db/dblog': No such file or directory
# failed to change mode of '/home/runner/.ddev/commands/db/dblog' from 0000 (---------) to 0000 (---------)
# 
# 👎 
# Could not process post-install action (0) ''

</pre>
</details> 

When I run the same commands in my shell, I am able to download/add the add-on just fine. 

My guess is that maybe the test have  changed and I need to update them? I am looking for docs on how to diagnose and fix failing add-on tests... What steps should I take? 

Thank you.</div>

**Comment by rfay** [comment]
Answer from the discussion:

What's going on (I think) is that in the latest (2) commits in DDEV HEAD the XDG_CONFIG_HOME environment variable is supported, and Github actions has XDG_CONFIG_HOME set. That means that DDEV is going to try to put the dblog command into ~/.config/ddev/commands/db/dblog. It's doing that... but then your post-install action is trying to find it at the ~/.ddev location. 

So the HEAD tests did what they want to do and told us when something is failing...

However...
* Please remove the chmod, as it's not necessary anyway, DDEV does that for you. Or check it in with executable.
* You don't need the removal_action, because DDEV will remove things that you installed with your install.yaml.

So removing those two will solve this. 

However, I'm going to convert this to an issue for now because this general problem may affect other add-ons that make assumptions about where the global DDEV config dir lives.

**Comment by apotek** [comment]
> Answer from the discussion:
> 
> What's going on (I think) is that in the latest (2) commits in DDEV HEAD the XDG_CONFIG_HOME environment variable is supported, and Github actions has XDG_CONFIG_HOME set. That means that DDEV is going to try to put the dblog command into ~/.config/ddev/commands/db/dblog. It's doing that... but then your post-install action is trying to find it at the ~/.ddev location.
> 
> So the HEAD tests did what they want to do and told us when something is failing...
> 
> However...
> 
>     * Please remove the chmod, as it's not necessary anyway, DDEV does that for you. Or check it in with executable.
> 
>     * You don't need the removal_action, because DDEV will remove things that you installed with your install.yaml.
> 
> 
> So removing those two will solve this.
> 
> However, I'm going to convert this to an issue for now because this general problem may affect other add-ons that make assumptions about where the global DDEV config dir lives.

First and foremost, THANK YOU for taking the time to answer and explain. I ended up with a few questions:

I removed my `post_install_actions` and `removal_actions` from my install.yaml file and pushed back up to main. So unless I am missing something fundamental, HEAD should now have an install file that does not try to chmod or remove. However, when I ran the tests (triggered manually), the test [_still_ attempts to run the same actions](https://github.com/ChromaticHQ/ddev-dblog/actions/runs/9277111776/job/25525627410). 

I still get:

> \# ddev get chromatichq/ddev-dblog with project ddev-dblog in /home/runner/tmp/test-ddev-dblog (/home/runner/tmp/test-ddev-dblog)
> not ok 1 install from release
> \# (in test file tests/test.bats, line 71)
> \#   `ddev get chromatichq/ddev-dblog' failed

in the output, and the post_install action is still triggered, despite it no longer existing in the install.yaml file. 

So that is head-scratcher number one for me. 

The second head-scratcher is that you reference, in your answer `~/.config/ddev/...` whereas I don't have that directory. I only have `~/.ddev/...`. 

Do I need to be updating my tests? And if so, is there a documented way to do that? (Basically refresh the add-on template in my existing add-on). Thanks again.

**Comment by rfay** [comment]
* You changed your code but didn't do a release. So when it does "install from release" it's still getting the old code.
* On Github Actions (linux) GitHub sets XDG_CONFIG_HOME, which on DDEV Head now respects, and it's set to ~/.config/ddev . The default for DDEV remains ~/.ddev, but Github Actions by setting XDG_CONFIG_HOME causes the new behavior. I'm currently trying to sort this out in 
* https://github.com/ddev/ddev/pull/6239

**Comment by apotek** [comment]
Thank you @rfay . Tests are now passing.

Lessons learned (in case anyone else is reading):

1. If your changes are related to the tests themselves, you will need to create a release to test those changes. 
2. Try not to assume paths that work will continue to work. See if there is an environment variable that gives you what you need.
3. Don't test more than you need to test. (In this case, adding actions that weren't necessary).

**Comment by tyler36** [comment]
Thank you for the overview @apotek !

**Comment by rfay** [comment]
> If your changes are related to the tests themselves, you will need to create a release to test those changes

That actually isn't correct. It's when the changes are related to the functionality that you need to create a release for it to work. But it's confusing! 
* https://github.com/ddev/github-action-add-on-test/issues/30 proposes not running the release test on a PR.

**Comment by rfay** [comment]
Glad it's working for you!
