### ISSUE TITLE
Windows: `ddev self-upgrade` doesn't work

### ISSUE THREAD

**Issue by tyler36** [ddev/ddev#6274]
### Preliminary checklist

- [X] I am using the latest stable version of DDEV (see [upgrade guide](https://ddev.readthedocs.io/en/stable/users/install/ddev-upgrade/))
- [X] I have searched [existing issues](https://github.com/ddev/ddev/issues)
- [X] I have checked the [troubleshooting guide](https://ddev.readthedocs.io/en/stable/users/usage/troubleshooting/)
- [X] I have run `ddev debug test` to include output below

### Output of `ddev debug test`

<details><summary>Expand `ddev debug test` diagnostic information</summary>

```
[COPY-PASTE HERE THE OUTPUT OF `ddev debug test`]
```
</details>

### Expected Behavior

The error message should display the correct path in full. 
Ideally, `\` should be used instead of `/` as that is the Windows convention.

```
Unable to determine how you installed DDEV, but you can remove "c:\Program Files\DDEV\ddev" and reinstall with one of the techniques in https://ddev.readthedocs.io/en/stable/users/install/ddev-installation/
```

### Actual Behavior

Attempting to upgrade results in a broken message. 

```
❯ ddev self-upgrade
Unable to determine how you installed DDEV, but you can remove /c/Program and reinstall with one of the techniques in https://ddev.readthedocs.io/en/stable/users/install/ddev-installation/
Unable to determine how you installed DDEV, but you can remove Files/DDEV/ddev and reinstall with one of the techniques in https://ddev.readthedocs.io/en/stable/users/install/ddev-installation/
```

I guess the path string is not being wrapped with `"` somewhere in the message code.

### Steps To Reproduce

1. Install DDEV via [Windows binary](https://github.com/ddev/ddev/releases) . Eg. [ddev_windows_installer.v1.23.1.exe](https://github.com/ddev/ddev/releases/download/v1.23.1/ddev_windows_installer.v1.23.1.exe)
2. In the terminal, attempt to upgrade DDEV

```shell
❯ ddev self-upgrade
Unable to determine how you installed DDEV, but you can remove /c/Program and reinstall with one of the techniques in https://ddev.readthedocs.io/en/stable/users/install/ddev-installation/
Unable to determine how you installed DDEV, but you can remove Files/DDEV/ddev and reinstall with one of the techniques in https://ddev.readthedocs.io/en/stable/users/install/ddev-installation/
```

### Anything else?

I use DDEV via WSL2 100% of the time.

Generally, I use `choco` to manage DDEV on Windows. 
However, I wanted to document the installation steps. Therefore I removed the choco version and went with the binary. I plan on returning to the choco version immediately.

**Comment by rfay** [comment]
Are you running this in git-bash or PS or where? The results will normally be different.

We encourage people to use git-bash, where forward slashes would be normal.

But that message is pretty ugly!

It's just a script, if you can figure out how to improve it, it's sure welcome. 

It looks like it was always intended to be run in git-bash:

https://github.com/ddev/ddev/blob/master/pkg/ddevapp/global_dotddev_assets/commands/host/self-upgrade

**Comment by tyler36** [comment]
Have the same issue in git-bash:

```shell
MINGW64 /d/code/temp/goo
$ echo $SHELL
/usr/bin/bash

MINGW64 /d/code/temp/goo
$ git -v
git version 2.45.1.windows.1

MINGW64 /d/code/temp/goo
$ ddev self-upgrade
Unable to determine how you installed DDEV, but you can remove /c/Program and reinstall with one of the techniques in https://ddev.readthedocs.io/en/stable/users/install/ddev-installation/
Unable to determine how you installed DDEV, but you can remove Files/DDEV/ddev and reinstall with one of the techniques in https://ddev.readthedocs.io/en/stable/users/install/ddev-installation/
```

**Comment by tyler36** [comment]
Looking at the link, I installed via the EXE so I should be hitting the installer package line:

 ```
    "/c/Program Files/DDEV/ddev")
      printf "DDEV was either installed with\nchoco install -y ddev\nor with the installer package.\n"
      echo "You can upgrade with 'choco upgrade -y ddev'"
      echo "Or by downloading the Windows installer from https://github.com/ddev/ddev/releases"
      ;;
    *)
      echo "Unable to determine how you installed DDEV, but you can remove $ddev_path and reinstall with one of the techniques in https://ddev.readthedocs.io/en/stable/users/install/ddev-installation/"
```

But the bad error suggest I'm hitting "Unable to determine". 

```shell
$ which ddev
/c/Program Files/DDEV/ddev

$ ddev self-upgrade
Unable to determine how you installed DDEV, ....
```
