### ISSUE TITLE
Deprecate and remove `ddev service` commands

### ISSUE THREAD

**Issue by rfay** [ddev/ddev#6298]
`ddev service` has been mostly replaced with add-on commands.

Deprecate and remove it.

**Comment by stasadev** [comment]
For the context, how it's replaced by add-on commands:

Now you can do this:
```
ddev add-on remove redis
```

Instead of this:
```
ddev service disable redis
```

**Comment by rfay** [comment]
Our approach for this will be:
* In v1.24: Change to a message saying "Use ddev add-on commands ..." and make a hidden command and remove from docs
* In v1.25: Remove it completely
