### ISSUE TITLE
Run CakePHP Quickstart with no interaction (skip setting directory permissions)

### ISSUE THREAD

**Issue by tyler36** [ddev/ddev#6300]
### Preliminary checklist

- [X] I am using the latest stable version of DDEV (see [upgrade guide](https://ddev.readthedocs.io/en/stable/users/install/ddev-upgrade/))
- [X] I have searched [existing issues](https://github.com/ddev/ddev/issues)
- [X] I have checked the [troubleshooting guide](https://ddev.readthedocs.io/en/stable/users/usage/troubleshooting/)
- [X] I have run `ddev debug test` to include output below

### Output of `ddev debug test`

<details><summary>Expand `ddev debug test` diagnostic information</summary>

```
[COPY-PASTE HERE THE OUTPUT OF `ddev debug test`]
```
</details>

### Expected Behavior

Copy and pasting the CakePHP quickstart should:
- install website
- automatically launch the browser to the functionaling website

### Actual Behavior

Composer stops and asks to "Set Folder Permissions":

```shell
$ ddev composer create --prefer-dist cakephp/app:~5.0
...
PHP CodeSniffer Config installed_paths set to ../../cakephp/cakephp-codesniffer,../../slevomat/coding-standard
Executing composer command: [composer run-script post-create-project-cmd]
 
> App\Console\Installer::postInstall
Created `config/app_local.php` file
Created `/var/www/html/logs` directory
Created `/var/www/html/tmp/cache/views` directory
Set Folder Permissions ? (Default to Y) [Y,n]? 
```

### Steps To Reproduce

Follow quickstart guide for CakePHP (replicated below)

```shell
mkdir my-cakephp-site && cd my-cakephp-site
ddev config --project-type=cakephp --docroot=webroot
ddev composer create --prefer-dist cakephp/app:~5.0
ddev cake
ddev launch
```

### Anything else?

I tried use `--no-interaction` on the composer line but it still stopped.
Eg. `ddev composer create --prefer-dist cakephp/app:~5.0 --no-interaction`

I believe this is because of the `composer run-script post-create-project-cmd` line which doesn't inherit the flag.

Adding a `.ddev/.env` file with `COMPOSER_NO_INTERACTION=1` does NOT cause composer to stop. But we probably don't want this to always be active, only during the initial "ddev composer create" step.

**Comment by rfay** [comment]
Could you please try it with the HEAD version and see if it's any different? 

The second answer on https://stackoverflow.com/questions/49812880/how-can-i-run-composer-without-user-interaction also might have value (using `yes`)

IIRC Composer added a question like this for security purposes that might require an extra setting in the composer.json to bypass.

**Comment by tyler36** [comment]
You mean `ddev exec yes | composer create --prefer-dist cakephp/app:~5.0` ?

```shell
$ ddev exec yes | composer create --prefer-dist cakephp/app:~5.0
...
Updated Security.salt value in config/app_local.php
Failed to execute command yes: signal: broken pipe
```

**Comment by stasadev** [comment]
```
yes | ddev composer create --prefer-dist cakephp/app:~5.0
```

**Comment by stasadev** [comment]
I think I know what the problem is, we're not passing the flags to `composer run-script`, I'll fix that.

**Comment by tyler36** [comment]
> yes | ddev composer create --prefer-dist cakephp/app:~5.0

Sorry. Didn't think of it there.

**Comment by tyler36** [comment]
> yes | ddev composer create --prefer-dist cakephp/app:~5.0

✅  WSL Ubuntu with DDEV `1.23.2`
❌  Windows 11 with DDEV `1.23.2`

**Comment by rfay** [comment]
RIght, but that shouldn't be needed at all with 
* https://github.com/ddev/ddev/pull/6303

which is the real fix. We'll get that in soon.
