### ISSUE TITLE
Flag for start command to only start when stopped

### ISSUE THREAD

**Issue by MichelJonkman** [ddev/ddev#6318]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

I wanna use `ddev start` in a package.json script to automatically start ddev and run the dev server. But as it is now it restarts every time.

### Describe your solution

Add a flag like `--no-restart` or whatever else that doesn't restart, only starts if ddev has been stopped

### Describe alternatives

A custom script can be used but is much less portable

**Comment by rfay** [comment]
Thanks for the suggestion!

I don't expect we'll change DDEV's behavior to fit your workflow, but a PR is welcome.

It's so much easier for you to create a custom command though. As @stasadev said in Discord,

> [[ $(ddev describe -j | docker run -i --rm ddev/ddev-utilities jq -r '.raw.status') != "running" ]] && ddev start

You can build that into a custom command and use it.

I should mention though, that if you're executing your package.json on the host side (where you can run `ddev start` then it's not the recommended situation. We recommend running node/npm/etc inside the container where you have a predictable version and context.

**Comment by rfay** [comment]
DDEV of course handles the vite server, and in the container is the place to run it. Please take a look at https://ddev.com//blog/working-with-vite-in-ddev/

Note that if you do a PR you'll need to handle all the situations where `ddev start` is used, including with multiple arguments, `--all`, etc.  I imagine it will be easier for you to make a custom command that meets your own needs.

**Comment by rfay** [comment]
> Seeing as the ports are hardcoded

I'm not sure what you mean. DDEV uses a router and many, many projects can run at the same time using the same port set.

**Comment by MichelJonkman** [comment]
I meant the Vite port, 5173, normally if that port is in use it will automatically use another one but if you hardcode the port like that you'll have to decide on a unique port for every project

**Comment by rfay** [comment]
As you see in https://ddev.com//blog/working-with-vite-in-ddev/ port 5173 is handled by the `ddev-router`, so there is no problem with multiple projects using it.

**Comment by rfay** [comment]
There's a good workaround here, but a simple PR would be welcome. Closing for now.
