### ISSUE TITLE
Error with custom web Dockerfile: GPG error: http://nginx.org/packages/debian bullseye InRelease: The following signatures were invalid

### ISSUE THREAD

**Issue by erikhedin** [ddev/ddev#6345]
### Preliminary checklist

- [X] I am using the latest stable version of DDEV (see [upgrade guide](https://ddev.readthedocs.io/en/stable/users/install/ddev-upgrade/))
- [X] I have searched [existing issues](https://github.com/ddev/ddev/issues)
- [X] I have checked the [troubleshooting guide](https://ddev.readthedocs.io/en/stable/users/usage/troubleshooting/)
- [X] I have run `ddev debug test` to include output below

### Output of `ddev debug test`

We have been including build-essential in our web container Dockerfile for a couple of years.  A few days ago we started getting the following error on apt-get update:

```
GPG error: http://nginx.org/packages/debian bullseye InRelease: The following signatures were invalid: EXPKEYSIG ABF5BD827BD9BF62 nginx signing key <signing-key@nginx.com>
```

I am able to resolve the issue by deleting the nginx.list file with:

```
RUN if [ -f /etc/apt/sources.list.d/nginx.list ]; then rm -f /etc/apt/sources.list.d/nginx.list; fi;
```

Is this something that others are experiencing?  Many thanks for the help!

<details><summary>Expand `ddev debug test` diagnostic information</summary>

```

DDEV version:  ITEM             VALUE
 DDEV version     v1.21.4
 architecture     arm64
 db               drud/ddev-dbserver-mariadb-10.4:v1.21.4
 dba              phpmyadmin:5
 ddev-ssh-agent   drud/ddev-ssh-agent:v1.21.4
 docker           24.0.9
 docker-compose   v2.14.0
 docker-platform  colima
 mutagen          0.16.0
 os               darwin
 router           drud/ddev-router:v1.21.4
 web              drud/ddev-webserver:v1.21.4
PROXY settings: HTTP_PROXY='' HTTPS_PROXY='' http_proxy='' NO_PROXY=''
======= DDEV global info =========
Global configuration:
instrumentation-opt-in=true
omit-containers=[]
mutagen-enabled=false
nfs-mount-enabled=false
router-bind-all-interfaces=false
internet-detection-timeout-ms=3000
disable-http2=false
use-letsencrypt=false
letsencrypt-email=
table-style=default
simple-formatting=false
auto-restart-containers=false
use-hardened-images=false
fail-on-hook-fail=false
required-docker-compose-version=
use-docker-compose-from-path=false
project-tld=
xdebug-ide-location=
no-bind-mounts=false
use-traefik=false

======= DOCKER info =========
docker location: lrwxr-xr-x@ 1 ehedin  admin  34 Sep 11  2023 /opt/homebrew/bin/docker -> ../Cellar/docker/24.0.6/bin/docker
Docker Desktop Version: Print: Entry, ":CFBundleShortVersionString", Does Not Exist
Print: Entry, ":CFBundleVersion", Does Not Exist
Docker Desktop for Mac File build Doesn'tDocker Desktop for Mac Exist, build WillDocker Desktop for Mac Create: build /Applications/Docker.app/Contents/Info.plistDocker Desktop for Mac File build Doesn'tDocker Desktop for Mac Exist, build WillDocker Desktop for Mac Create: build /Applications/Docker.app/Contents/Info.plist
docker version:
Client: Docker Engine - Community
 Version:           24.0.6
 API version:       1.43
 Go version:        go1.21.0
 Git commit:        ed223bc820
 Built:             Thu Aug 31 17:24:32 2023
 OS/Arch:           darwin/arm64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          24.0.9
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.13
  Git commit:       fca702d
  Built:            Thu Feb  1 00:48:55 2024
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.28
  GitCommit:        ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc:
  Version:          1.1.12
  GitCommit:        v1.1.12-0-g51d5e94
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
DOCKER_DEFAULT_PLATFORM=notset
======= Mutagen Info =========
Mutagen is installed in ddev, version=0.16.0


```
</details>

### Expected Behavior

We expected `apt update && apt install build-essential ` to run successfully. 

### Actual Behavior

GPG error: http://nginx.org/packages/debian bullseye InRelease: The following signatures were invalid

### Steps To Reproduce

Create a new web Docker file:
.ddev/web-build/Dockerfile

```
ARG BASE_IMAGE
FROM $BASE_IMAGE

RUN apt-get update &&  apt-get install -y build-essential

```

Or exec in to the web container and run `apt update`
```
ddev ssh
sudo apt update
```

**Comment by rfay** [comment]
Hi @erikhedin - They seem to have let their key expire, but I don't think you'll have trouble if you update to DDEV v1.23.3. 

You didn't provide the output of `ddev debug test` so I can't see that. But please update.

**Comment by rfay** [comment]
You *did* check the checkbox saying you were using current stable. Seems you didn't look though?

**Comment by rfay** [comment]
Oh, you're using bullseye so you're WAY out of date. We switched to Debian 12 Bookworm in DDEV v1.23.0 many months ago (April, 2024)

**Comment by stasadev** [comment]
@erikhedin,

From https://github.com/ddev/ddev/pull/6260#issuecomment-2138632309

```
brew uninstall -f ddev
brew untap drud/ddev
brew untap drud/ddev-edge
brew untap ddev/ddev-edge
brew install ddev/ddev/ddev
```

**Comment by erikhedin** [comment]
Oh wow, thank you!  The following steps fixed us up:

1. ddev poweroff
2. docker rm -f $(docker ps -aq)
3. docker rmi -f $(docker images -q)
4. rm -f .ddev/.ddev-docker-compose-base.yaml
5. rm -f .ddev/.ddev-docker-compose-full.yaml
6. cd to home
7. curl -fsSL https://ddev.com/install.sh | bash -s v1.23.2
8. ddev start

**Comment by rfay** [comment]
It's unusual to use the install.sh script these days. 

There was no need to remove the `.ddev-docker-compose*`

Or really anythings else.

All you really needed to do with update DDEV to current.

And you didn't need tp specify the version in the install script either.

For future reference on upgrading DDEV: https://ddev.readthedocs.io/en/stable/users/install/ddev-upgrade/
