### ISSUE TITLE
feat: suggest addon if command not found

### ISSUE THREAD

**Issue by tyler36** [ddev/ddev#6352]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

#6343 hightlights a improved user experience; if the `phpmyadmin` command is not found, it offers to install it.
This is particular useful considering `phpmyadmin` was at one time an available command, but has been removed in favor of an extension.

### Describe your solution

I would love if DDEV would suggest addons based on (missing) command. 
Current workflow:

- Developer types `ddev browsersync`
- DDEV throws error about missing command
- Developer searchs Google/SO, asks on Discord, run `ddev get --list --all`

Suggested improved workflow:

- Developer types `ddev browsersync`
- DDEV detects missing command, it runs `ddev get --list` and sees if there's a hit on the command keyword `browsersync`
- DDEV suggest/automates installing the addon.

This assumes an addon with XXX name also has a matching XXX command. While not fool-proof, I think it would work more often than not and get us 80% of the way.  
Eg. `ddev cypress` would suggest the cypress addon, but the commands are `ddev cypress-open` `ddev cypress-run`.

Centralizing the logic would reduce duplication and allow us to tweak, or add exceptions where applicable.
I'm OK with limiting the scope to "official" addons only.

### Additional context

Note: if/when implement, we would need to revert #6343

**Comment by tyler36** [comment]
Wasn't really thinking about implementation, although I did ponder aloud.

Hoping someone with more skill than me could tackle it.

**Comment by rfay** [comment]
It's great thinking!

**Comment by stasadev** [comment]
I would like to hear the opinion about:

- #6353

It's still a draft and will be updated/improved, but I think I've already built the most functionality there.

**Comment by tyler36** [comment]
@stasadev thank you!

The current draft forfills the original request and works great!

**Comment by tyler36** [comment]
https://github.com/ddev/ddev/pull/6353#issuecomment-2214511690

> Perhaps a better option that we should focus on is an Add-on Registry where people can find what they need.

Closing. Still a good idea, so perhaps we can investigate again once the we figure out an ideal strategy. 
Thank you @stasadev for the work you did!
