### ISSUE TITLE
Command `ddev stop --all-other`

### ISSUE THREAD

**Issue by verdure-hettler** [ddev/ddev#6356]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

In my daily work I am jumping between multiple projects and forget to stop the projects from time to time. I use `ddev stop --all` to shutdown all projects but sometime the project I'm working on is already running and I want to except it (to save time).

### Describe your solution

Maybe we could add the command `ddev stop --all-other` (or name it as you want to) to shutdown all projects except the project of the current directory.

**Comment by rfay** [comment]
My approach is `ddev poweroff && ddev start`, very easy.

Also note that you can use `ddev list -j` to get json output of all projects, filter on running ones, compare to current, etc.

**Comment by joestewart** [comment]
There was a discord discussion with a solution from Thanasis Psarros.

Global command to stop other projects except the current directory project
* From Discord: https://discord.com/channels/664580571770388500/1068592266752573440/1223319455740723230
* Pull the "ddev/ddev-utilities" if never done.
`docker pull ddev/ddev-utilities`
* Edit and create the "~/.ddev/commands/host/stop-other" file with the following contents
```
#!/bin/bash
 
## Description: Stop all other running projects
## Usage: stop-other
## Example: "ddev stop-other"
 
ddev stop $(ddev list --active-only -j | docker run -i --rm ddev/ddev-utilities jq -r .raw[].name | grep -v $(ddev describe -j | docker run -i --rm ddev/ddev-utilities jq -r .raw.name))
```
`ddev restart`

`ddev stop-other`

**Comment by rfay** [comment]
Thanks @joestewart , and of course if `jq` is on the machine then you don't need `ddev-utilities`, we just often mention that so people don't stumble on machines that absolutely have docker but might not have jq.

**Comment by rfay** [comment]
Since there's a good workaround documented here for this particular workflow, I'm going to close this as not planned. 

One thing to consider is that it's super easy to create an add-on to deliver a custom command like this.
