### ISSUE TITLE
Native support for PostGIS

### ISSUE THREAD

**Issue by alvarofranz** [ddev/ddev#6362]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

I need to add the postgis extension to postgres, but don't see a clear way to get this done, since it is not reflected in the docs. The closest thing I see in the docs is [dbimage_extra_packages](https://ddev.readthedocs.io/en/latest/users/configuration/config/#dbimage_extra_packages).

**But it does not work:**

Example config:
```
database:
    type: postgres
    version: "15"
dbimage_extra_packages: [postgis]
```

And when trying to use Postgis, I get:

```
ERROR:  extension "postgis" is not available
DETAIL:  Could not open extension control file "/usr/share/postgresql/15/extension/postgis.control": No such file or directory.
```

### Describe your solution

Offer native support for postgres extensions, like postgis.

### Describe alternatives

Extending the information in the docs, to provide more details in the _dbimage_extra_packages_, would also be enough.

### Additional context

Related issue from 2019: https://github.com/ddev/ddev/issues/1542

**Comment by stasadev** [comment]
The PostGIS package name for PostgreSQL 15 is `postgresql-15-postgis-3`:

```
ddev config --dbimage-extra-packages="postgresql-15-postgis-3"
ddev restart
```
