### ISSUE TITLE
Make Linux install instructions leaner

### ISSUE THREAD

**Issue by gitressa** [ddev/ddev#6372]
### Preliminary checklist

- [X] I am using the latest stable version of DDEV (see [upgrade guide](https://ddev.readthedocs.io/en/stable/users/install/ddev-upgrade/))
- [X] I have searched [existing issues](https://github.com/ddev/ddev/issues)
- [X] I have checked the [troubleshooting guide](https://ddev.readthedocs.io/en/stable/users/usage/troubleshooting/)
- [X] I have run `ddev debug test` to include output below

### Problem

There are three instances of `sudo sh -c 'echo ""'` in the Linux install instructions, which don't seem to be needed, so can't we remove them? They seem like redundant commands, which just bloats the install process unnecessarily.

Also, can't we assume that most Linux users have Curl installed, and add that in the intro text?:

## Current instructions

>  DDEV’s Debian and RPM packages work with `apt` and `yum` repositories and most variants that use them, including Windows WSL2:
> ```
> # Add DDEV’s GPG key to your keyring
> sudo sh -c 'echo ""'
> sudo apt-get update && sudo apt-get install -y curl
> sudo install -m 0755 -d /etc/apt/keyrings
> curl -fsSL https://pkg.ddev.com/apt/gpg.key | gpg --dearmor | sudo tee /etc/apt/keyrings/ddev.gpg > /dev/null
> sudo chmod a+r /etc/apt/keyrings/ddev.gpg
> 
> # Add DDEV releases to your package repository
> sudo sh -c 'echo ""'
> echo "deb [signed-by=/etc/apt/keyrings/ddev.gpg] https://pkg.ddev.com/apt/ * *" | sudo tee /etc/apt/sources.list.d/ddev.list >/dev/null
> 
> # Update package information and install DDEV
> sudo sh -c 'echo ""'
> sudo apt-get update && sudo apt-get install -y ddev
> 
> # One-time initialization of mkcert
> mkcert -install
> ```

From https://ddev.readthedocs.io/en/stable/users/install/ddev-installation/#linux

## Suggested new format

> DDEV’s Debian and RPM packages work with `apt` and `yum` repositories and most variants that use them, including Windows WSL2. Make sure you have [cURL](https://curl.se/) installed:
> ```
> # Add DDEV’s GPG key to your keyring
> sudo install -m 0755 -d /etc/apt/keyrings
> curl -fsSL https://pkg.ddev.com/apt/gpg.key | gpg --dearmor | sudo tee /etc/apt/keyrings/ddev.gpg > /dev/null
> sudo chmod a+r /etc/apt/keyrings/ddev.gpg
> 
> # Add DDEV releases to your package repository
> echo "deb [signed-by=/etc/apt/keyrings/ddev.gpg] https://pkg.ddev.com/apt/ * *" | sudo tee /etc/apt/sources.list.d/ddev.list >/dev/null
> 
> # Update package information and install DDEV
> sudo apt-get update && sudo apt-get install -y ddev
> 
> # One-time initialization of mkcert
> mkcert -install
> ```

**Comment by rfay** [comment]
As explained in the PR, no, we can't assume that curl is installed. And the empty sudos have a purpose. 

It's easy for experienced Linux users like you to know what to do here (or to know what to do if curl is missing, for example) but not so easy for everybody.

**Comment by Firesphere** [comment]
Is it a possibility to create a bash script to pipe?
e.g.
> To install on linux, you can run `curl -sSL https://install.ddev.com | bash`. If you see or encounter errors, for example because you don't have curl installed, see the manual instructions below.
The https://install.ddev.com script takes the exact same steps, but in an automated manner, to make your life a little bit easier.

**Comment by rfay** [comment]
The tradeoff here is between doing what's obvious (the instructions are easy and obvious for a knowledgable Linux user) and doing things in a more automated way. In general, Linux users should be able to understand and follow the current instructions and get through just fine. New users might not. There are a lot in both camps.

**Comment by stasadev** [comment]
> `yay -S ddev-bin`

Actually this is not enough 🙂, because with Arch Linux you need to have `yay` installed, which exists in EndeavourOS (installed by default AFAIK) and Manjaro (not installed by default AFAIK) repos, but not in Arch Linux (where you first need to install `base-devel` to have build utils and then install `yay` by cloning its AUR repo and running `makepkg` in the directory with `PKGBUILD` file. This is explained in the `yay` [README.md](https://github.com/Jguer/yay) and in the Arch Wiki, and doesn't need to be repeated in DDEV.

But Arch Linux is only intended for advanced use, so we expect them to know what to do.
So I wouldn't compare Debian/Ubuntu instructions to it.

**Comment by rfay** [comment]
And on Debian/Ubuntu, `sudo apt install ddev` does not work until you have installed the repository details, and the key, and done a `sudo apt update`

**Comment by rfay** [comment]
I'm going to close this for now. 

Docs like this are always a trade-off. Do we say too much and muddy the waters, and people can't find what they're looking for? Or do we assume too much and say too little, so people without the same background are baffled by what's missing?

Specific docs PRs that deal directly with making it easier for the entire DDEV audience to do what's needed are welcome, and don't need to have a backing issue.

Remember the tradeoffs when working on those :)
