### ISSUE TITLE
Installation of Magento 2 on Linux failed due to wrong command when following docs

### ISSUE THREAD

**Issue by InteractiveWebdesign** [ddev/ddev#6380]
### Preliminary checklist

- [X] I am using the latest stable version of DDEV (see [upgrade guide](https://ddev.readthedocs.io/en/stable/users/install/ddev-upgrade/))
- [X] I have searched [existing issues](https://github.com/ddev/ddev/issues)
- [X] I have checked the [troubleshooting guide](https://ddev.readthedocs.io/en/stable/users/usage/troubleshooting/)
- [X] I have run `ddev debug test` to include output below

### Output of `ddev debug test`

<details><summary>Expand `ddev debug test` diagnostic information</summary>

```


WARNING: Project should usually be in a subdirectory of the user's home directory.
Instead it's in /var/www/magento2



======== Output file will be in /tmp/ddev-debug-test.txt ========


======== Existing project config ========
ddev installation alternate locations:
/usr/bin/ddev
/bin/ddev

These config files were loaded for project magento2: [/var/www/magento2/.ddev/config.yaml]
name: magento2
type: magento2
docroot: pub
php_version: 8.2
webserver_type: nginx-fpm
webimage: ddev/ddev-webserver:v1.23.3
additional_hostnames: []
additional_fqdns: []
database: {mariadb 10.6}
upload_dirs: [media]
project_tld: loc
use_dns_when_possible: true
composer_version: 2
disable_settings_management: true
nodejs_version: 20
default_container_timeout: 120


======== existing project customizations ========


======== installed DDEV add-ons ========
┌───────────────┬─────────┬─────────────────────────┬───────────────────────────┐
│ ADD-ON        │ VERSION │ REPOSITORY              │ DATE INSTALLED            │
├───────────────┼─────────┼─────────────────────────┼───────────────────────────┤
│ elasticsearch │ v0.3.2  │ ddev/ddev-elasticsearch │ 2024-07-06T15:38:28+02:00 │
└───────────────┴─────────┴─────────────────────────┴───────────────────────────┘



======== mutagen situation ========
looking for #ddev-generated in mutagen.yml in project /var/www/magento2
.ddev/mutagen/mutagen.yml not found


======== Creating dummy project named tryddevproject-2839 in ../tryddevproject-2839 ========
Creating a new DDEV project config in the current directory (/var/www/tryddevproject-2839)
Once completed, your configuration will be written to /var/www/tryddevproject-2839/.ddev/config.yaml

Configuring a 'php' project named 'tryddevproject-2839' with docroot 'web' at '/var/www/tryddevproject-2839/web'.
For full details use 'ddev describe'.
Configuration complete. You may now run 'ddev start'.


======== OS Information ========
Linux thebeast 6.5.0-41-generic #41~22.04.2-Ubuntu SMP PREEMPT_DYNAMIC Mon Jun  3 11:32:55 UTC 2 x86_64 x86_64 x86_64 GNU/Linux


======== User information ========
uid=1000(thebeast) gid=1000(thebeast) groups=1000(thebeast),4(adm),24(cdrom),27(sudo),30(dip),46(plugdev),122(lpadmin),135(lxd),136(sambashare),998(nordvpn),999(docker)


======== DDEV version ========
 ITEM             VALUE                                    
 DDEV version     v1.23.3                                  
 architecture     amd64                                    
 cgo_enabled      0                                        
 db               ddev/ddev-dbserver-mariadb-10.11:v1.23.3 
 ddev-ssh-agent   ddev/ddev-ssh-agent:v1.23.3              
 docker           27.0.3                                   
 docker-api       1.46                                     
 docker-compose   v2.28.1                                  
 docker-platform  linux-docker                             
 global-ddev-dir  /home/thebeast/.ddev                     
 mutagen          0.17.2                                   
 os               linux                                    
 router           ddev/ddev-traefik-router:v1.23.3         
 web              ddev/ddev-webserver:v1.23.3              



======== proxy settings ========

 HTTP_PROXY=''
 HTTPS_PROXY=''
 http_proxy=''
 NO_PROXY=''
 


======== DDEV global info ========

```
</details>

### Expected Behavior

Expected to install Magento2 source code.

### Actual Behavior

**### The "--repository" option does not exist.**  

### Steps To Reproduce

1. Linux Ubuntu
2. Follow the doc: https://ddev.readthedocs.io/en/latest/users/quickstart/#magento

### Installation of Magento 2 on Linux failed due to wrong command.

Instructions: [https://ddev.readthedocs.io/en/latest/users/quickstart/#magento]

Command: ddev composer create --repository=https://repo.magento.com/ magento/project-community-edition

### **Error reads:**                                  
  **The "--repository" option does not exist.** 

### **CLI output**

`whyalwaysme@thebeast:/var/www/magento2$ ddev composer create --repository=https://repo.magento.com/ magento/project-community-edition
Executing Composer command: [composer create-project --repository=https://repo.magento.com/ magento/project-community-edition --no-plugins --no-scripts --no-install /tmp/vcxeZQ]

Creating a "magento/project-community-edition" project at "/tmp/vcxeZQ"
Warning from repo.magento.com: You haven't provided your Magento authentication keys. For instructions, visit https://devdocs.magento.com/guides/v2.3/install-gde/prereq/connect-auth.html
    Authentication required (repo.magento.com):
      Username: hidden
      Password: 
Do you want to store credentials for repo.magento.com in /var/www/html/.ddev/homeadditions/.composer/auth.json ? [Yn] Y
Installing magento/project-community-edition (2.4.7-p1)
Plugins have been disabled.
  - Downloading magento/project-community-edition (2.4.7-p1)
  - Installing magento/project-community-edition (2.4.7-p1): Extracting archive
Created project in /tmp/vcxeZQ
Moving install to Composer root
 Container ddev-magento2-elasticsearch  Stopped
 Container ddev-magento2-db  Stopped
 Container ddev-magento2-web  Stopped
 Container ddev-magento2-db  Stopped
 Container ddev-magento2-elasticsearch  Stopped
 Container ddev-magento2-web  Stopped
 Container ddev-magento2-db  Removed
 Container ddev-magento2-elasticsearch  Removed
 Container ddev-magento2-web  Removed
 Network ddev-magento2_default  Removed
Building project images...
.Project images built in 1s.
 Network ddev-magento2_default  Created
 Container ddev-magento2-web  Created
 Container ddev-magento2-elasticsearch  Created
 Container ddev-magento2-db  Created
 Container ddev-magento2-web  Started
 Container ddev-magento2-elasticsearch  Started
 Container ddev-magento2-db  Started
Waiting for containers to become ready: [web db]
Starting ddev-router if necessary...
 Container ddev-router  Running
Waiting for additional project containers to become ready...
All project containers are now ready.
Not creating CMS settings files because disable_settings_management=true
Executing Composer command: [composer install --repository=https://repo.magento.com/]

                                             
  **### The "--repository" option does not exist.**  
                                             

install [--prefer-source] [--prefer-dist] [--prefer-install PREFER-INSTALL] [--dry-run] [--download-only] [--dev] [--no-suggest] [--no-dev] [--no-autoloader] [--no-progress] [--no-install] [--audit] [--audit-format AUDIT-FORMAT] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--] [<packages>...]

failed to install project: exit status 1
stderr=

**Comment by rfay** [comment]
I think the answer is right there:

> Warning from repo.magento.com: You haven't provided your Magento authentication keys. For instructions, visit https://devdocs.magento.com/guides/v2.3/install-gde/prereq/connect-auth.html

The [quickstart docs](https://ddev.readthedocs.io/en/stable/users/quickstart/#magento) explain how you need to get those keys and use them.

**Comment by stasadev** [comment]
Hi @InteractiveWebdesign,

Please use this command for now as a workaround:
```
ddev composer create --repository https://repo.magento.com/ magento/project-community-edition
```

```diff
-ddev composer create --repository=https://repo.magento.com/ magento/project-community-edition
+ddev composer create --repository https://repo.magento.com/ magento/project-community-edition
```

The fix is in:

- #6382

**Comment by InteractiveWebdesign** [comment]
> I think the answer is right there:
> 
> > Warning from repo.magento.com: You haven't provided your Magento authentication keys. For instructions, visit https://devdocs.magento.com/guides/v2.3/install-gde/prereq/connect-auth.html
> 
> The [quickstart docs](https://ddev.readthedocs.io/en/stable/users/quickstart/#magento) explain how you need to get those keys and use them.

Hi rfay the issue is not due keys, I have entered and used them successfully and in my code example replaced my public key with xxxxxxxxxx

**Comment by stasadev** [comment]
Hi @InteractiveWebdesign,

I just haven't updated the docs because it will be fixed in the next version of DDEV and we can't update the stable docs without creating a new release anyway.
