### ISSUE TITLE
`ddev launch :port` doesn't handle Gitpod URLs, `ddev mailpit` doesn't work in Gitpod

### ISSUE THREAD

**Issue by stasadev** [ddev/ddev#6389]
### Preliminary checklist

- [X] I am using the latest stable version of DDEV (see [upgrade guide](https://ddev.readthedocs.io/en/stable/users/install/ddev-upgrade/))
- [X] I have searched [existing issues](https://github.com/ddev/ddev/issues)
- [X] I have checked the [troubleshooting guide](https://ddev.readthedocs.io/en/stable/users/usage/troubleshooting/)
- [X] I have run `ddev debug test` to include output below

### Output of `ddev debug test`

<details><summary>Expand `ddev debug test` diagnostic information</summary>

```
[COPY-PASTE HERE THE OUTPUT OF `ddev debug test`]
```
</details>

### Expected Behavior

From Discord: https://discord.com/channels/664580571770388500/1260544940216291339
- https://github.com/ddev/ddev-phpmyadmin/issues/15

`ddev mailpit` should open Mailpit in Gitpod
`ddev launch :8027` should open Mailpit in Gitpod

### Actual Behavior

`ddev mailpit` opens project primary URL in Gitpod.
`ddev launch :8027` adds port at the end of the URL in Gitpod.

### Steps To Reproduce

Try `ddev mailpit` and `ddev launch :8027` in Gitpod.

**Comment by tyler36** [comment]
https://github.com/ddev/ddev-gitpod-launcher/issues/41
