### ISSUE TITLE
`codespaces.new` cert has expired, so our Codespaces launcher button doesn't work any more

### ISSUE THREAD

**Issue by rfay** [ddev/ddev#6399]
### Preliminary checklist

- [X] I am using the latest stable version of DDEV (see [upgrade guide](https://ddev.readthedocs.io/en/stable/users/install/ddev-upgrade/))
- [X] I have searched [existing issues](https://github.com/ddev/ddev/issues)
- [X] I have checked the [troubleshooting guide](https://ddev.readthedocs.io/en/stable/users/usage/troubleshooting/)
- [X] I have run `ddev debug test` to include output below

### Output of `ddev debug test`

<details><summary>Expand `ddev debug test` diagnostic information</summary>

```
[COPY-PASTE HERE THE OUTPUT OF `ddev debug test`]
```
</details>

### Expected Behavior

Our codespaces launch button should work (on PR)

### Actual Behavior

It goes to `codespaces.new`, whose cert expired a couple days ago, 

<img width="549" alt="image" src="https://github.com/user-attachments/assets/350fcbca-8c88-4fc5-ad6e-8b5d7b31ed24">

### Steps To Reproduce

Launch a Codepaces button, like https://codespaces.new/?ref=20240714_rfay_codespaces_http_port&repo=80927419

It goes to codespaces.new, which has expired cert.

### Anything else?

Github does in fact own codespaces.new (I had no idea there was a `new` TLD.) So maybe they'll just fix this.

However, I don't see them using it in their setup for running a new codespace.

**Comment by stasadev** [comment]
I agree that they will definitely fix it. And yes, they don't use it here on GitHub, so it's better to use another link.
