### ISSUE TITLE
Only gitignore specific example files

### ISSUE THREAD

**Issue by dvdmlln** [ddev/ddev#6410]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

The [docs](https://ddev.readthedocs.io/en/stable/users/extend/customization-extendibility/#providing-custom-environment-variables-to-a-container) suggest to not check in an `.env` file and instead use `.env.example` and gitignore `.env`. However, the generated `.gitignore` ignores all example files. In order to check in an example file I'd have to disable gitignore generation, remove `/**/*.example` and check the `.gitignore` in as well.

### Describe your solution

I would like to leave the generated `.ddev/.gitignore` untouched and use my project root gitignore to ignore `.ddev/.env` and checkin `.ddev/.env.example`.
It would be great if only the example files generated by ddev, like `web-build/Dockerfile.example`, would be ignored.

**Comment by rfay** [comment]
Hi @dvdmlln - To commit a file that is gitignored, just use `git add -f`. For example, `git add -f .ddev/.env.example`

**Comment by rfay** [comment]
Closing, happy to continue the conversation. Let me know if there's anything to add or you need additional help, happy to continue the conversation here or elsewhere.
