### ISSUE TITLE
`ddev start` fails due to no internet connectivity at start time in Docker system

### ISSUE THREAD

**Issue by Adrianm6254** [ddev/ddev#6419]
### Preliminary checklist

- [X] I am using the latest stable version of DDEV (see [upgrade guide](https://ddev.readthedocs.io/en/stable/users/install/ddev-upgrade/))
- [X] I have searched [existing issues](https://github.com/ddev/ddev/issues)
- [X] I have checked the [troubleshooting guide](https://ddev.readthedocs.io/en/stable/users/usage/troubleshooting/)
- [X] I have run `ddev debug test` to include output below

### Output of `ddev debug test`

<details><summary>Expand `ddev debug test` diagnostic information</summary>

```
[COPY-PASTE HERE THE OUTPUT OF `ddev debug test`]
```

</details>

https://gist.github.com/Adrianm6254/74c5625e26bb4cb2ca390c1c3adebe06#file-gistfile1-txt

### Expected Behavior

Drupal 11 site to startup

### Actual Behavior

<details><summary>Drupal 11 ddev start</summary>

```
ddev start
Starting n2c-base11-d... 
Building project images... 
.failed to solve: process "/bin/bash -c mkdir -p /tmp/sqlite3 && wget -O /tmp/sqlite3/sqlite3.deb https://snapshot.debian.org/archive/debian/20240203T152533Z/pool/main/s/sqlite3/sqlite3_${SQLITE_VERSION}-1_${TARGETPLATFORM##linux/}.deb && wget -O /tmp/sqlite3/libsqlite3.deb https://snapshot.debian.org/archive/debian/20240203T152533Z/pool/main/s/sqlite3/libsqlite3-0_${SQLITE_VERSION}-1_${TARGETPLATFORM##linux/}.deb && apt-get install -y /tmp/sqlite3/*.deb && rm -rf /tmp/sqlite3" did not complete successfully: exit code: 4 
Failed to start n2c-base11-d: docker-compose build failed: composeCmd failed to run 'COMPOSE_PROJECT_NAME=ddev-n2c-base11-d docker-compose -f /media/drive2/dev/project-builds/n2c-base11/.ddev/.ddev-docker-compose-full.yaml --progress=plain build', action='[--progress=plain build]', err='exit status 17', stdout='#0 building with "default" instance using docker driver

#1 [db internal] load build definition from Dockerfile
#1 transferring dockerfile: 656B done
#1 WARN: InvalidDefaultArgInFrom: Default value for ARG $BASE_IMAGE results in empty or invalid base image name (line 6)
#1 DONE 0.0s

#2 [web internal] load build definition from Dockerfile
#2 transferring dockerfile: 1.72kB done
#2 WARN: InvalidDefaultArgInFrom: Default value for ARG $BASE_IMAGE results in empty or invalid base image name (line 6)
#2 DONE 0.0s

#3 [db internal] load metadata for docker.io/ddev/ddev-dbserver-mariadb-10.11:v1.23.3
#3 DONE 0.0s

#4 [web internal] load metadata for docker.io/ddev/ddev-webserver:v1.23.3
#4 DONE 0.0s

#5 [db internal] load .dockerignore
#5 transferring context: 2B done
#5 DONE 0.0s

#6 [web internal] load .dockerignore
#6 transferring context: 2B done
#6 DONE 0.0s

#7 [db 1/2] FROM docker.io/ddev/ddev-dbserver-mariadb-10.11:v1.23.3
#7 DONE 0.0s

#8 [db 2/2] RUN (groupadd --gid 1000 "adrian" || groupadd "adrian" || true) && (useradd  -l -m -s "/bin/bash" --gid "adrian" --comment '' --uid 1000 "adrian" || useradd  -l -m -s "/bin/bash" --gid "adrian" --comment '' "adrian" || useradd  -l -m -s "/bin/bash" --gid "1000" --comment '' "adrian" || useradd -l -m -s "/bin/bash" --comment '' adrian )
#8 CACHED

#9 [web 1/8] FROM docker.io/ddev/ddev-webserver:v1.23.3
#9 DONE 0.0s

#10 [web 3/8] RUN mkdir -p /home/adrian && chown adrian /home/adrian && chmod 600 /home/adrian/.pgpass
#10 CACHED

#11 [web 2/8] RUN (groupadd --gid 1000 "adrian" || groupadd "adrian" || true) && (useradd  -l -m -s "/bin/bash" --gid "adrian" --comment '' --uid 1000 "adrian" || useradd  -l -m -s "/bin/bash" --gid "adrian" --comment '' "adrian" || useradd  -l -m -s "/bin/bash" --gid "1000" --comment '' "adrian" || useradd -l -m -s "/bin/bash" --comment '' adrian )
#11 CACHED

#12 [web 4/8] RUN corepack enable
#12 CACHED

#13 [db] exporting to image
#13 exporting layers done
#13 writing image sha256:ac69d7b54d065034e04e8da5186095265815a9d2b2a6cdcca085e82d1e25bdaf done
#13 naming to docker.io/ddev/ddev-dbserver-mariadb-10.11:v1.23.3-n2c-base11-d-built done
#13 DONE 0.0s

#14 [web 5/8] RUN mkdir -p /tmp/sqlite3 && wget -O /tmp/sqlite3/sqlite3.deb https://snapshot.debian.org/archive/debian/20240203T152533Z/pool/main/s/sqlite3/sqlite3_3.45.1-1_amd64.deb && wget -O /tmp/sqlite3/libsqlite3.deb https://snapshot.debian.org/archive/debian/20240203T152533Z/pool/main/s/sqlite3/libsqlite3-0_3.45.1-1_amd64.deb && apt-get install -y /tmp/sqlite3/*.deb && rm -rf /tmp/sqlite3
#14 0.166 --2024-07-22 22:24:41--  https://snapshot.debian.org/archive/debian/20240203T152533Z/pool/main/s/sqlite3/sqlite3_3.45.1-1_amd64.deb
#14 0.173 Resolving snapshot.debian.org (snapshot.debian.org)... failed: Temporary failure in name resolution.
#14 0.173 wget: unable to resolve host address ‘snapshot.debian.org’
#14 ERROR: process "/bin/bash -c mkdir -p /tmp/sqlite3 && wget -O /tmp/sqlite3/sqlite3.deb https://snapshot.debian.org/archive/debian/20240203T152533Z/pool/main/s/sqlite3/sqlite3_${SQLITE_VERSION}-1_${TARGETPLATFORM##linux/}.deb && wget -O /tmp/sqlite3/libsqlite3.deb https://snapshot.debian.org/archive/debian/20240203T152533Z/pool/main/s/sqlite3/libsqlite3-0_${SQLITE_VERSION}-1_${TARGETPLATFORM##linux/}.deb && apt-get install -y /tmp/sqlite3/*.deb && rm -rf /tmp/sqlite3" did not complete successfully: exit code: 4
------
 > [web 5/8] RUN mkdir -p /tmp/sqlite3 && wget -O /tmp/sqlite3/sqlite3.deb https://snapshot.debian.org/archive/debian/20240203T152533Z/pool/main/s/sqlite3/sqlite3_3.45.1-1_amd64.deb && wget -O /tmp/sqlite3/libsqlite3.deb https://snapshot.debian.org/archive/debian/20240203T152533Z/pool/main/s/sqlite3/libsqlite3-0_3.45.1-1_amd64.deb && apt-get install -y /tmp/sqlite3/*.deb && rm -rf /tmp/sqlite3:
0.166 --2024-07-22 22:24:41--  https://snapshot.debian.org/archive/debian/20240203T152533Z/pool/main/s/sqlite3/sqlite3_3.45.1-1_amd64.deb
0.173 Resolving snapshot.debian.org (snapshot.debian.org)... failed: Temporary failure in name resolution.
0.173 wget: unable to resolve host address ‘snapshot.debian.org’
------
', stderr='failed to solve: process "/bin/bash -c mkdir -p /tmp/sqlite3 && wget -O /tmp/sqlite3/sqlite3.deb https://snapshot.debian.org/archive/debian/20240203T152533Z/pool/main/s/sqlite3/sqlite3_${SQLITE_VERSION}-1_${TARGETPLATFORM##linux/}.deb && wget -O /tmp/sqlite3/libsqlite3.deb https://snapshot.debian.org/archive/debian/20240203T152533Z/pool/main/s/sqlite3/libsqlite3-0_${SQLITE_VERSION}-1_${TARGETPLATFORM##linux/}.deb && apt-get install -y /tmp/sqlite3/*.deb && rm -rf /tmp/sqlite3" did not complete successfully: exit code: 4', output='#0 building with "default" instance using docker driver

#1 [db internal] load build definition from Dockerfile
#1 transferring dockerfile: 656B done
#1 WARN: InvalidDefaultArgInFrom: Default value for ARG $BASE_IMAGE results in empty or invalid base image name (line 6)
#1 DONE 0.0s

#2 [web internal] load build definition from Dockerfile
#2 transferring dockerfile: 1.72kB done
#2 WARN: InvalidDefaultArgInFrom: Default value for ARG $BASE_IMAGE results in empty or invalid base image name (line 6)
#2 DONE 0.0s

#3 [db internal] load metadata for docker.io/ddev/ddev-dbserver-mariadb-10.11:v1.23.3
#3 DONE 0.0s

#4 [web internal] load metadata for docker.io/ddev/ddev-webserver:v1.23.3
#4 DONE 0.0s

#5 [db internal] load .dockerignore
#5 transferring context: 2B done
#5 DONE 0.0s

#6 [web internal] load .dockerignore
#6 transferring context: 2B done
#6 DONE 0.0s

#7 [db 1/2] FROM docker.io/ddev/ddev-dbserver-mariadb-10.11:v1.23.3
#7 DONE 0.0s

#8 [db 2/2] RUN (groupadd --gid 1000 "adrian" || groupadd "adrian" || true) && (useradd  -l -m -s "/bin/bash" --gid "adrian" --comment '' --uid 1000 "adrian" || useradd  -l -m -s "/bin/bash" --gid "adrian" --comment '' "adrian" || useradd  -l -m -s "/bin/bash" --gid "1000" --comment '' "adrian" || useradd -l -m -s "/bin/bash" --comment '' adrian )
#8 CACHED

#9 [web 1/8] FROM docker.io/ddev/ddev-webserver:v1.23.3
#9 DONE 0.0s

#10 [web 3/8] RUN mkdir -p /home/adrian && chown adrian /home/adrian && chmod 600 /home/adrian/.pgpass
#10 CACHED

#11 [web 2/8] RUN (groupadd --gid 1000 "adrian" || groupadd "adrian" || true) && (useradd  -l -m -s "/bin/bash" --gid "adrian" --comment '' --uid 1000 "adrian" || useradd  -l -m -s "/bin/bash" --gid "adrian" --comment '' "adrian" || useradd  -l -m -s "/bin/bash" --gid "1000" --comment '' "adrian" || useradd -l -m -s "/bin/bash" --comment '' adrian )
#11 CACHED

#12 [web 4/8] RUN corepack enable
#12 CACHED

#13 [db] exporting to image
#13 exporting layers done
#13 writing image sha256:ac69d7b54d065034e04e8da5186095265815a9d2b2a6cdcca085e82d1e25bdaf done
#13 naming to docker.io/ddev/ddev-dbserver-mariadb-10.11:v1.23.3-n2c-base11-d-built done
#13 DONE 0.0s

#14 [web 5/8] RUN mkdir -p /tmp/sqlite3 && wget -O /tmp/sqlite3/sqlite3.deb https://snapshot.debian.org/archive/debian/20240203T152533Z/pool/main/s/sqlite3/sqlite3_3.45.1-1_amd64.deb && wget -O /tmp/sqlite3/libsqlite3.deb https://snapshot.debian.org/archive/debian/20240203T152533Z/pool/main/s/sqlite3/libsqlite3-0_3.45.1-1_amd64.deb && apt-get install -y /tmp/sqlite3/*.deb && rm -rf /tmp/sqlite3
#14 0.166 --2024-07-22 22:24:41--  https://snapshot.debian.org/archive/debian/20240203T152533Z/pool/main/s/sqlite3/sqlite3_3.45.1-1_amd64.deb
#14 0.173 Resolving snapshot.debian.org (snapshot.debian.org)... failed: Temporary failure in name resolution.
#14 0.173 wget: unable to resolve host address ‘snapshot.debian.org’
#14 ERROR: process "/bin/bash -c mkdir -p /tmp/sqlite3 && wget -O /tmp/sqlite3/sqlite3.deb https://snapshot.debian.org/archive/debian/20240203T152533Z/pool/main/s/sqlite3/sqlite3_${SQLITE_VERSION}-1_${TARGETPLATFORM##linux/}.deb && wget -O /tmp/sqlite3/libsqlite3.deb https://snapshot.debian.org/archive/debian/20240203T152533Z/pool/main/s/sqlite3/libsqlite3-0_${SQLITE_VERSION}-1_${TARGETPLATFORM##linux/}.deb && apt-get install -y /tmp/sqlite3/*.deb && rm -rf /tmp/sqlite3" did not complete successfully: exit code: 4
------
 > [web 5/8] RUN mkdir -p /tmp/sqlite3 && wget -O /tmp/sqlite3/sqlite3.deb https://snapshot.debian.org/archive/debian/20240203T152533Z/pool/main/s/sqlite3/sqlite3_3.45.1-1_amd64.deb && wget -O /tmp/sqlite3/libsqlite3.deb https://snapshot.debian.org/archive/debian/20240203T152533Z/pool/main/s/sqlite3/libsqlite3-0_3.45.1-1_amd64.deb && apt-get install -y /tmp/sqlite3/*.deb && rm -rf /tmp/sqlite3:
0.166 --2024-07-22 22:24:41--  https://snapshot.debian.org/archive/debian/20240203T152533Z/pool/main/s/sqlite3/sqlite3_3.45.1-1_amd64.deb
0.173 Resolving snapshot.debian.org (snapshot.debian.org)... failed: Temporary failure in name resolution.
0.173 wget: unable to resolve host address ‘snapshot.debian.org’
------
', stderr='failed to solve: process "/bin/bash -c mkdir -p /tmp/sqlite3 && wget -O /tmp/sqlite3/sqlite3.deb https://snapshot.debian.org/archive/debian/20240203T152533Z/pool/main/s/sqlite3/sqlite3_${SQLITE_VERSION}-1_${TARGETPLATFORM##linux/}.deb && wget -O /tmp/sqlite3/libsqlite3.deb https://snapshot.debian.org/archive/debian/20240203T152533Z/pool/main/s/sqlite3/libsqlite3-0_${SQLITE_VERSION}-1_${TARGETPLATFORM##linux/}.deb && apt-get install -y /tmp/sqlite3/*.deb && rm -rf /tmp/sqlite3" did not complete successfully: exit code: 4' 

```
</summary>

### Steps To Reproduce

Run ddev start

**Comment by rfay** [comment]
Hi @Adrianm6254 - 

Your internet doesn't seem to be working at image build tiime, so the special setup of sqlite3 3.45 is not downloading (and it can't even look up the hostname. (It looks to me like nothing works inside container or at build time, although you have internet on the workstation).

>  [web 5/8] RUN mkdir -p /tmp/sqlite3 && wget -O /tmp/sqlite3/sqlite3.deb https://snapshot.debian.org/archive/debian/20240203T152533Z/pool/main/s/sqlite3/sqlite3_3.45.1-1_amd64.deb && wget -O /tmp/sqlite3/libsqlite3.deb https://snapshot.debian.org/archive/debian/20240203T152533Z/pool/main/s/sqlite3/libsqlite3-0_3.45.1-1_amd64.deb && apt-get install -y /tmp/sqlite3/*.deb && rm -rf /tmp/sqlite3:
0.166 --2024-07-22 22:24:41--  https://snapshot.debian.org/archive/debian/20240203T152533Z/pool/main/s/sqlite3/sqlite3_3.45.1-1_amd64.deb
0.173 Resolving snapshot.debian.org (snapshot.debian.org)... failed: Temporary failure in name resolution.
0.173 wget: unable to resolve host address ‘snapshot.debian.org’

It can't do composer either:

> #8 0.959   curl error 6 while downloading https://getcomposer.org/versions: Could not   
#8 0.959   resolve host: getcomposer.org                                                

Or deb.debian.org:

> #9 7.188 Err:1 http://deb.debian.org/debian bookworm InRelease
#9 7.188   Temporary failure resolving 'deb.debian.org'

Please see if you can resolve these problems. 

Does `ping -c 1 snapshot.debian.org` work on your workstation?

Does `ddev exec ping -c 1 snapshot.debian.org` work?

It's possible for Docker providers to have trouble at build time even though those work. It's typically due to VPN or Firewall problems though. Did you try disabling VPN and firewall?


I also see from `ddev debug test` that you're not running in home directory, which usually causes chaos with Docker etc:
> WARNING: Project should usually be in a subdirectory of the user's home directory.
Instead it's in /media/drive2/dev/project-builds/n2c-base11

And I see that you have experimented with MTU settings apparently, please remove that until you get farther along:

> ======== existing project customizations ========
> .ddev/docker-compose.network-mtu.yaml

Not particularly relevant to this, but you have dozens of old dead containers. I recommend deleting them:
```
ddev poweroff
docker rm -f $(docker ps -aq)
```

Please fix your system and report back.  This has nothing to do with Drupal 11. You can do a trivial Drupal 10 quickstart and you'll see the same failures in a `ddev debug test`.

**Comment by Adrianm6254** [comment]
My system works fine with Drupal 10, it's only Drupal 11 that does not startup.

`$ ping -c 1 snapshot.debian.org
PING snapshot.debian.org(lw07-2.debian.org (2001:1af8:4020:b030:deb::185)) 56 data bytes
64 bytes from lw07-2.debian.org (2001:1af8:4020:b030:deb::185): icmp_seq=1 ttl=48 time=120 ms

--- snapshot.debian.org ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 119.817/119.817/119.817/0.000 ms`

`ddev exec ping -c 1 snapshot.debian.org
Project is not currently running. Try 'ddev start'.`

I deleted `.ddev/docker-compose.network-mtu.yaml` and nothing changed.

I also deleted the dead docker containers.

I moved my code to my home directory and it still does not work

Output from `ddev debug test` - https://gist.github.com/Adrianm6254/9b28e93a9bc1ade809a440f7c0ecdba9

Output from `ddev start` - https://gist.github.com/Adrianm6254/721be3b4287f147bab4b335c53419bdc

**Comment by rfay** [comment]
It shows in your `ddev debug test`, which is the simplest possible setup. It's just that in that case DDEV skips by the problem after trying multiple times. Perhaps it should also do that for Drupal 11 and getting the specialty sqlite version that Drupal 11 wants.

You're going to have to fix your machine or your docker provider.

See https://gist.github.com/Adrianm6254/9b28e93a9bc1ade809a440f7c0ecdba9#file-gistfile1-txt-L229-L230

As before,
* Try disabling VPN and Firewall temporarily
* Try connecting to a different network

More troubleshooting suggestions at https://ddev.readthedocs.io/en/stable/users/usage/troubleshooting/

I can't fix your computer or docker provider for you.

You can look at `ddev debug test` again or create a trivial Dockerfile to try to test this out.

**Comment by Adrianm6254** [comment]
Corrected the issue by blowing away my codebase and starting over.

**Comment by rfay** [comment]
Wow, I don't know how it could have anything to do with your codebase, unless you had some weird proxy stuff going on or something. Closing.

Note that it didn't have to do with your codebase, as it was happening in `ddev debug test`. You'll want to do `ddev debug test` again and look for those failures to resolve.

**Comment by Adrianm6254** [comment]
In further investigation I discovered the difference in it working and not working was my Dockerfile that was generated by DDEV.  The one that did not work was trying to install SQLITE3 while the one that does work did not.  

I am enclosing both files here
[Dockerfile-doesn't-work.txt](https://github.com/user-attachments/files/16380898/Dockerfile-doesn.t-work.txt)
[Dockerfile-works.txt](https://github.com/user-attachments/files/16380901/Dockerfile-works.txt)

**Comment by rfay** [comment]
Yes, that's the difference between a `drupal11` project and a `drupal10` project. (Those are not configurable files, they're generated files)

And the reason that the "doesn't work" one doesn't work is that you have no connectivity in your Docker provider at build time. You'll have to fix that. Try the suggested approaches (Firewall and VPN for example). Try connecting to a different network. Try reinstalling docker from scratch. 

You can easily demonstrate the same problem with a plain project like this:

```
mkdir junk && cd junk
ddev config --auto
echo "RUN sudo apt update && sudo apt upgrade -y" >.ddev/web-build/Dockerfile.showfail
ddev start
```

It will fail exactly the same, because you don't have internet connectivity in your docker environment.

So consider snapshotting all your databases, `ddev snapshot -a`

And consider completely uninstalling docker-ce and reinstalling it. Among the other things suggested.

I am opening
* https://github.com/ddev/ddev/issues/6425

because we can fail more gracefully on Drupal 11.

**Comment by rfay** [comment]
I added 
* https://github.com/ddev/ddev/pull/6426

which makes DDEV fail more gracefully on getting the special v3.45 sqlite3, but many, many things won't work for you if you can't fix your networking situation.  For example, getting latest or specified composer version won't work, adding webimage_extra_packages, etc. 

This is now in HEAD and you can use it if you want to, see https://ddev.readthedocs.io/en/stable/developers/building-contributing/#testing-latest-commits-on-head
