### ISSUE TITLE
404 Error for Static Files Served via Nginx in DDEV Environment

### ISSUE THREAD

**Issue by wstocker** [ddev/ddev#6424]
### Preliminary checklist

- [X] I am using the latest stable version of DDEV (see [upgrade guide](https://ddev.readthedocs.io/en/stable/users/install/ddev-upgrade/))
- [X] I have searched [existing issues](https://github.com/ddev/ddev/issues)
- [X] I have checked the [troubleshooting guide](https://ddev.readthedocs.io/en/stable/users/usage/troubleshooting/)
- [X] I have run `ddev debug test` to include output below

<summary>404 Error for Static Files Served via Nginx in DDEV Environment</summary>

I am trying to set an alias for the sites/default/files/images/ directory in Drupal to  /images in my Nginx configuration, but it's not working after `ddev restart`

I see that it's using my custom configuration:
`Using custom nginx configuration in ~Documents/methanesat-edf/.ddev/nginx_full/nginx-site.conf `

Configuration Attempted: nginx-site.conf

```
    location /images/ {
        alias /var/www/html/web/sites/default/files/images/;
        try_files $uri $uri/ /index.php?$query_string;
    }

```
I have verified the file exists in `/var/www/html/web/sites/default/files/images/` and spelling of the file is correct. When I attempt to access it from I am getting a 404. E.g: `ddev.site/images/image.jpg `

### Output of `ddev debug test`
Success accessing database... db via TCP/IP
ddev is working.
The output file for Discord or issue queue is in /var/folders/jx/xgpqp_dd2752svm0rxwhhf3c0000gn/T/ddev-debug-test.txt
file:///var/folders/jx/xgpqp_dd2752svm0rxwhhf3c0000gn/T/ddev-debug-test.txt

### Expected Behavior

Alias created from /var/www/html/web/sites/default/files/images/ to /images

### Actual Behavior

404 error

**Comment by stasadev** [comment]
Hi @wstocker,

You can use this:

```conf
location ^~ /images/ {
    if ($uri !~* \.(jpg|jpeg|gif|png|ico|svg)$) {
        return 404;
    }
    alias /var/www/html/web/sites/default/files/images/;
    expires max;
    log_not_found off;
    try_files $uri $uri/ =404;
}
```

P.S.: I see you're using Drupal and that's enough to answer your question, but

> The output file for Discord or issue queue is in /var/folders/jx/xgpqp_dd2752svm0rxwhhf3c0000gn/T/ddev-debug-test.txt

Next time you ask for help, provide actual output from the generated `ddev-debug-test.txt` file.

**Comment by wstocker** [comment]
That worked! Thanks and will do on the output next time. Thanks.
