### ISSUE TITLE
Allow the same host_db_port to be used for multiple projects

### ISSUE THREAD

**Issue by benjaminkohl** [ddev/ddev#6429]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

We have the desire to configure all our projects to use the same DB port 33060 with the understanding that we would never run multiple project containers simultaneously. It appears that whether or not a particular project's containers are running, its static DB port is reserved and other projects are prohibited from using it. We see this error message when attempting to start a project:

```
Failed to start projectB: host port 33060 has already been allocated to project projectA 
```

If there isn't already a means to do what I am trying to do, I would like to have the ability to ignore any potential port conflicts between project containers. I searched the documentation and the existing github issues for a number of keywords I _thought_ might describe my particular situation so I am sorry if I missed an existing setting or github issue for this feature.

### Describe your solution

Perhaps a config.yaml setting that enables the ability to conflict with other projects as long as those containers aren't running? I don't really know what the appropriate solution would be or where this error is actually occurring in the startup process.

**Comment by rfay** [comment]
You could certainly put a `ddev stop --unlist -a` in your `pre-start` `exec-host` hooks. 

But can you say why you're trying to do this? Most users of the host db port (like the `ddev sequelace` and all the other database browsers use custom commands where the automatically exposed port is already available as an environment variable. 

If you can say what you're trying to accomplish and the context, we may be able to give better ideas on how to accomplish it (and ways that let you run more than one project at a time)

**Comment by benjaminkohl** [comment]
We decided this feature/port setup isn't worth pursuing. I'll close this request.
