### ISSUE TITLE
Add support for custom command aliases

### ISSUE THREAD

**Issue by TravisCarden** [ddev/ddev#6443]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

c.f. https://github.com/orgs/ddev/discussions/6431

Like the built-in `describe` command has aliases (`describe, status, st, desc`), I would like to be able to add aliases to my custom commands.

### Describe your solution

I propose the addition of an annotation (e.g., `Aliases`) for command files. I don't have a proposal for technical implementation. (I'm not experienced enough with DDEV internals yet to make one.)

### Describe alternatives

In the meantime, @rfay proposed symlinks as an alternative in https://github.com/orgs/ddev/discussions/6431#discussioncomment-10163083.

**Comment by TravisCarden** [comment]
Oops! I searched existing issues but not PRs. See https://github.com/ddev/ddev/issues/6443 instead.

**Comment by stasadev** [comment]
I just didn't want to create an issue, so I made a link to my PR in your discussion https://github.com/orgs/ddev/discussions/6431#discussioncomment-10164338

But if we have an issue, let's keep it open until the PR is merged.

**Comment by TravisCarden** [comment]
Fantastic, @stasadev; thanks!!
