### ISSUE TITLE
Magento: set `MAGE_IS_DEVELOPER_MODE` env variable

### ISSUE THREAD

**Issue by sreichel** [ddev/ddev#6448]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

Please set MAGE_IS_DEVELOPER_MODE env variable by default, to not have to re-add it everytime.

### Describe your solution

Add MAGE_IS_DEVELOPER_MODE  to default config.yml and set it to 1.

**Comment by rfay** [comment]
I assume you're talking about openmage/magento 1? 

I'm sure you know you can add an environment variable like this to .ddev/.env, or `ddev config --web-environment-add=MAGE_IS_DEVELOPER_MODE=1` if it's an environment variable...

For magento 2, we suggest in the [quickstart](https://ddev.readthedocs.io/en/stable/users/quickstart/#magento) `ddev magento deploy:mode:set developer`

**Comment by rfay** [comment]
You know you can set MAGE_IS_DEVELOPER_MODE globally too right?

**Comment by sreichel** [comment]
Yes, its about M1/OM. 

I know about these options, but i thought it would be easier to have it added to default `config.yml`.

**Comment by rfay** [comment]
@stasadev has added it to the quickstart in 
* https://github.com/ddev/ddev/pull/6449

But I think you were asking for it to be part of the .ddev/config.yaml when doing a `ddev config --project-type=magento`, adding
```
web_environment:
 - MAGE_IS_DEVELOPER_MODE=1
```

by default. Is that the request?

We've never added a default variable for a project type before, but I imagine it could be done pretty easily.

**Comment by stasadev** [comment]
I think it should be optional, because people may like the CMS settings added by DDEV, but adding env may be too intrusive.
