### ISSUE TITLE
Show users warnings from stderr when running updates for composer, sqlite, etc

### ISSUE THREAD

**Issue by stasadev** [ddev/ddev#6451]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

Sometimes `web` container fails to update some components, like:
- `composer self-update`
- sqlite for Drupal 11
- ...

We silently continue here with `|| true`, so the container still runs, but users don't know about the errors.

### Describe your solution

Ideally it should be a script, that can be used in `/start.sh` or Dockerfile.

```dockerfile
RUN log-stderr.sh "composer self-update"
```

It should store `stderr` in some file in `/tmp`.

Something similar is done for `n install` in:
- #6420

But we should generalize it as much as possible.

**Comment by rfay** [comment]
Wow!

**Comment by stasadev** [comment]
It is important to handle situation when a failure occurs when executing `RUN` instruction inside a `Dockerfile`, for example, `composer self-update`, and it is cached by Docker:

1. add a `dirty` label to the `ddev-webserver-built` image (if possible), and run rebuild on the next start/restart? And do not break the offline mode.
2. or ignore it and just show the additional warning that suggests `ddev debug refresh` if something failed in the `Dockerfile`.

**Comment by rfay** [comment]
I think image *labels* might be the best technique for a "dirty" marker. I guess it can be tricky to add label after we're done, but maybe this approach will work for us, didn't study it carefully, https://stackoverflow.com/questions/44828219/how-to-add-docker-label-after-image-is-made
