### ISSUE TITLE
Update PHP 8.4 extensions to add missing ones

### ISSUE THREAD

**Issue by rfay** [ddev/ddev#6465]
### Is your feature request related to a problem?

In DDEV v1.23.4 we're missing these PHP 8.4 extensions: apcu imagick memcached redis uploadprogress xdebug xhprof xmlrpc

When doing a release we'll want to update those.

### Describe your solution

Update in Dockerfile

### Describe alternatives

* As these become available upstream. people can add them with webimage_extra_packages
* Even before they appear in deb.sury.org they can be added via pecl. https://ddev.readthedocs.io/en/stable/users/extend/customizing-images/#pecl-php-extensions-not-supported-by-debsuryorg

**Comment by rfay** [comment]
I don't see any of these being available yet. The tracking issue is
* https://github.com/oerdnj/deb.sury.org/issues/2176

We still seem to be missing
apcu imagick memcached redis uploadprogress xdebug xhprof xmlrpc

**Comment by BramDriesen** [comment]
Following 👀
