### ISSUE TITLE
confusing / incorrect comment in nginx.conf

### ISSUE THREAD

**Issue by joachim-n** [ddev/ddev#6474]
### Preliminary checklist

- [X] I am using the latest stable version of DDEV (see [upgrade guide](https://ddev.readthedocs.io/en/stable/users/install/ddev-upgrade/))
- [X] I have searched [existing issues](https://github.com/ddev/ddev/issues)
- [X] I have checked the [troubleshooting guide](https://ddev.readthedocs.io/en/stable/users/usage/troubleshooting/)
- [X] I have run `ddev debug test` to include output below

### Output of `ddev debug test`

<details><summary>Expand `ddev debug test` diagnostic information</summary>

```
[COPY-PASTE HERE THE OUTPUT OF `ddev debug test`]
```
</details>

### Expected Behavior

```
    location @rewrite {
        # For D7 and above:
        # Clean URLs are handled in drupal_environment_initialize().
        rewrite ^ /index.php;
    }
```

This is confusing because drupal_environment_initialize() only exists in D7.

Does the whole directive actually only apply to D7? I'm not sure about that, because of this bit which redirects to it:

```
    location ~ ^/sites/.*/files/styles/ {
        try_files $uri @rewrite;
    }
```

### Actual Behavior

n/a

**Comment by rfay** [comment]
Might as well remove comment

**Comment by rfay** [comment]
PR is welcome, thanks.
