### ISSUE TITLE
Can i change APACHE_RUN_USER?

### ISSUE THREAD

**Issue by sugreen-enter** [ddev/ddev#6475]
### Preliminary checklist

- [X] I am using the latest stable version of DDEV (see [upgrade guide](https://ddev.readthedocs.io/en/stable/users/install/ddev-upgrade/))
- [X] I have searched [existing issues](https://github.com/ddev/ddev/issues)
- [X] I have checked the [troubleshooting guide](https://ddev.readthedocs.io/en/stable/users/usage/troubleshooting/)
- [X] I have run `ddev debug test` to include output below

### Output of `ddev debug test`

<details><summary>Expand `ddev debug test` diagnostic information</summary>

```
[COPY-PASTE HERE THE OUTPUT OF `ddev debug test`]
```
</details>

### Expected Behavior

I need run apache as www-data.

### Actual Behavior

Apache run as user that run ddev.

### Anything else?

I have Drupal site.

Normally apache use user www-data. This is behavior on PROD. In DDEV apache run as user that run ddev (created in container).

I found, that this is changed in /etc/apache2/envvars, on end. But i dont know, how change it.

Is it possible?

**Comment by stasadev** [comment]
Hi @sugreen-enter,

DDEV is designed for local development, and it does everything possible to make it smooth for developers.

If the webserver is running under another user, it will create/update some files, e.g. logs, leading to host ownership issues.

This is a common problem, when you set up a webserver yourself ([example for Laravel](https://stackoverflow.com/questions/30639174/how-to-set-up-file-permissions-for-laravel)).

> Normally apache use user www-data. This is behavior on PROD. In DDEV apache run as user that run ddev (created in container).

Please tell why this is important to you?

**Comment by sugreen-enter** [comment]
Hi @stasadev ,

problem may be bigger, i have many own scripts to install, update, call cron, ... and these are "tunning" for all environments - DEV, CI, STAGE, PROD. PROD(s) runs in LXD. I have many instances of web. ...

But your idea may be good, i try this.

Thanks.

**Comment by rfay** [comment]
Mostly you want to use the default user to avoid many problem. Closing for now, happy to continue the conversation here or elsewhere.
