### ISSUE TITLE
v1.23.4 second "waiting for containers" section is ugly and can be improved

### ISSUE THREAD

**Issue by rfay** [ddev/ddev#6493]
In DDEV v1.23.4 we see this output after the router comes up:
```
Waiting 120s for additional project containers [ddev-d7-db ddev-d7-web] to become ready...
```

1. It's unnecessary, because we already waited for those two. If we're going to wait, we shouldn't at least point out those two.
2. It's too verbose, because previously we just said `db` and `web`, which makes more sense.

This needs to be calmed down, improved, or reverted back to the previous "waiting" statement.

**Comment by jonesrussell** [comment]
I'll work on this if that's cool. I'm still on v1.23.3, here's a `ddev start` for the record.

<img width="954" alt="image" src="https://github.com/user-attachments/assets/6d244407-4b88-4a93-acf6-a7e1285716bc">

**Comment by rfay** [comment]
Thanks!

**Comment by rfay** [comment]
Let us know if you need help getting started @jonesrussell !
