### ISSUE TITLE
Update Mailpit to latest version 1.20.2

### ISSUE THREAD

**Issue by mediaessenz** [ddev/ddev#6495]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

I discovered some strange problems with urls in emails caught by mailpit.
Some urls in emails get two points ("..") where only one point should be.
For example an url should look like this:
```
https://test.ddev.site/?jumpurl=https://test.ddev.site/_assets/0ded769/Images/mailerping.gif
```
but looks like:
```
https://test.ddev.site/?jumpurl=https://test.ddev.site/_assets/0ded769/Images/mailerping..gif 
```
See the last part `/mailerping..gif` which has two points.

This happens not always at the same place. In some generated mails the double point appear at a different place like so:
```
https://test.ddev.site/?jumpurl=https://test..ddev.site/_assets/0ded769/Images/mailerping.gif 
```

I don't know if this is a problem in mailpit 1.19.3 but there where two node library updates happens until 1.20.2 which may contain a fix for this issue.

### Describe your solution

Update Mailpit to latest version 1.20.2

**Comment by mediaessenz** [comment]
After some more tests, I discovered that this problem only appears if more than 10 mails in the inbox of mailpit.
I sent the same two mails several times. 
The 10th mail is the first one with the described problem. Also the 11th is corrupt, this the wrong additional point at a different place.

**Comment by rfay** [comment]
Hi @mediaessenz - You can update to latest mailpit by adding a `.ddev/web-build/Dockerfile.mailpit` with these contents:
```
RUN set -x && set -o pipefail && tag=$(curl -L --fail --silent "https://api.github.com/repos/axllent/mailpit/releases/latest" | jq -r .tag_name) && curl --fail -sSL "https://github.com/axllent/mailpit/releases/download/${tag}/mailpit-linux-${TARGETPLATFORM##linux/}.tar.gz" -o /tmp/mailpit.tar.gz && tar -zx -C /usr/local/bin -f /tmp/mailpit.tar.gz mailpit && rm /tmp/mailpit.tar.gz
```

Please do that and see what happens, and if the error is still there, please open a comprehensive issue in https://github.com/axllent/mailpit/issues (I do see https://github.com/axllent/mailpit/issues/348 and https://github.com/jhillyerd/enmime/issues/340, not sure if they're related to the problem you're reporting)

Note that mailpit will automatically be the latest version when the next DDEV release comes out.

**Comment by mediaessenz** [comment]
After updating mailpit to 1.20.2, the problems have become even worse.
With this version I have the behaviour in every mail, independent of the number of mails in the inbox.
I will report it to the mailpit project.

**Comment by rfay** [comment]
So it sounds like we do have work to do? I wonder why we haven't seen this before then. If we have work to do, please open an issue with the exact work to be done.
