### ISSUE TITLE
feat: manage framework timezones

### ISSUE THREAD

**Issue by tyler36** [ddev/ddev#6508]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

Recently, DDEV gained the ability to set the container timezone based on the host timezone (see #6468).

However, many frameworks also contain a timezone environment variable. 
DDEV currently manages database and mail settings.  Perhaps we should consider managing timezone too?

### Describe your solution

Laravel: 

- `APP_TIMEZONE=UTC` is the default set in `.env`

CakePHP:

- `export APP_DEFAULT_TIMEZONE="UTC"` set in `config/.env.ddev`

This ends up in `config/.env`, although not sure on the exact process/timing (just starting to learn CakePHP).

 [CakePHP supports all valid PHP timezones](https://book.cakephp.org/5/en/core-libraries/time.html#supported-timezones).

Drupal:

- Database setting so nothing required.

### Describe alternatives

I am not entirely convinced this request _should_ be implmented. 

This issue is a more a discussion point to document reasons for and against, before implentation, if required.

**Comment by rfay** [comment]
It's easy to implement, whether it's DDEV's job or whether it would get in people's way is another question to think about.

**Comment by rfay** [comment]
I think we'll pass on this one, but thanks for bringing it up, as always.
