### ISSUE TITLE
mysql:8.0 - "mysql_native_password' is deprecated and will be removed in a future release"

### ISSUE THREAD

**Issue by rfay** [ddev/ddev#6511]
`ddev start` with mysql:8.0 shows this output in `ddev logs -s db`:

`2024-08-27T17:20:08.116145Z 17 [Warning] [MY-013360] [Server] Plugin mysql_native_password reported: ''mysql_native_password' is deprecated and will be removed in a future release. Please use caching_sha2_password instead'`

It would be good to use the newer approach, if it doesn't break things.

This is in the initial setup, in create_db.sh:

https://github.com/ddev/ddev/blob/8900d5cdaa079244f962a00f990773e27fb878a5/containers/ddev-dbserver/files/create_base_db.sh#L76-L82

**Comment by stasadev** [comment]
> The caching_sha2_password plugin is fully supported as of PHP 7.4.4. 

https://www.php.net/manual/en/mysqli.requirements.php

**Comment by rfay** [comment]
Other complaints:
- [ ]  The syntax 'expire-logs-days' is deprecated and will be removed in a future release. Please use binlog_expire_logs_seconds instead
- [ ]  Disabling symbolic links using --skip-symbolic-links (or equivalent) is the default. Consider not using this option as it' is deprecated and will be removed in a future release
- [ ]  Insecure configuration for --secure-file-priv: Location is accessible to all OS users. Consider choosing a different directory.

**Comment by rfay** [comment]
* Turn off binlogs? https://github.com/ddev/ddev/issues/6244#issuecomment-2478500169
