### ISSUE TITLE
Add a `--project` flag to `ddev add-on get` and `ddev add-on remove`

### ISSUE THREAD

**Issue by GuySartorelli** [ddev/ddev#6513]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

In https://github.com/ddev/ddev/pull/6482 we refactored `ddev get` into `ddev add-on` with various sub-commands.

That work was intentionally a one-to-one refactor, but we should now aim to make the new commands more consistent with other DDEV commands.

Specifically, `ddev add-on get` and `ddev add-on remove` should have a `--project` flag to optionally add or remove add-ons for a specific project. 

### Describe your solution

1. Remove the second argument from `ddev add-on get` which is currently for a project name.
    - this has the added benefit that we could choose to allow adding multiple add-ons by naming additional add-ons as arguments
1. Add a `--project` flag to both `ddev add-on get` and `ddwv add-on remove`
1. In `ddev get`, make sure the second argument is converted to a flag before proxying to the `add-on get` command.

### Additional context

If we're going to do this, we should ideally do it before the next minor release. If we wait longer than that, it'll become a breaking change.

**Comment by rfay** [comment]
Are you willing to take it on? It would be lovely...

**Comment by GuySartorelli** [comment]
I've created https://github.com/ddev/ddev/pull/6517
