### ISSUE TITLE
Support SVGs in ImageMagick

### ISSUE THREAD

**Issue by saitho** [ddev/ddev#6518]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

SVG files are commonly used nowadays, yet the ImageMagick used in DDEV does not support converting SVG files.

### Describe your solution

In my test, installing the `librsvg2-bin` package and adding `<policy domain="coder" rights="none" pattern="SVG" />` to the ImageMagick policymap configuration, is sufficient to allow ImageMagick to convert SVGs.

Also see https://lightningcr.com/projects/nextcloud/wiki/%22How_to_Install_SVG_Support_for_php-imagick_Module_for_Better_Compatibility%22#How-to-Install-SVG-Support-for-php-imagick-Module-for-Better-Compatibility

**Comment by rfay** [comment]
This was fixed in 
* #6519 

Thanks!
