### ISSUE TITLE
Improve/clarify docs: Urls for additional services 

### ISSUE THREAD

**Issue by donquixote** [ddev/ddev#6535]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

The doc page https://ddev.readthedocs.io/en/stable/users/extend/custom-compose-files/ describes how to add additional services in ddev by providing additional docker-compose.yml files.

My current use case:
I have a Drupal site and want to add an additional service (collabora/code).

The following urls (with ports) need to be made available and configured:
- (done) Url for the Drupal site from the host system, e.g. `https://project-name.ddev.site/`.
- (done) Url for the Drupal site accessible from the other containers. Here `http://web` seems to work. `https://web` would also work but it has issues with the ssl certificate.
- Url for the additional container accessible from the host system, e.g. `https://extra-service.project-name.ddev.site:PORT/` (I had this working at some point).
- Url for the additional container accessible from other containers, e.g. `http://extra-service:PORT`. (Ideally I would want `https` to work here.)

So in the end we could (on the host system):
```
# Get the main Drupal site
curl https://project-name.ddev.site/
ddev exec -s extra-service curl http://web/

# Get the extra service.
curl https://extra-service.project-name.ddev.site:PORT/
ddev exec curl http://extra-service:PORT/
```

Problem:
The documentation at https://ddev.readthedocs.io/en/stable/users/extend/custom-compose-files/ mentions parameters `container_name`, `labels` and `expose`.
However, it is not clear to me how these result in urls to use from the host system or from other containers.
Especially, the url from the host system is not clear to me.

It would also be useful to have a url that works both on the host system _and_ in the containers.

### Describe your solution

The doc page should explicitly describe which url can be used from the host system, and how this is controlled by the configuration described, possibly with curl examples.

**Comment by rfay** [comment]
We'd love to help you with your specific example to start with. Then maybe when you have it sorted out, you can do a docs PR to that page?

Are you running a separate service/container? Or installing something in the web container?

**Comment by rfay** [comment]
I hope you'll continue on your WIP @donquixote , otherwise we'll close this about November 15, 2024.

**Comment by donquixote** [comment]
Hello @rfay 
I had no time to work on this, and also the project that I was hoping to run with ddev we now run with regular docker-compose and plain http, because for now this is the common solution in our team.
My earlier attempts to make it work with ddev were not successful, I would say mostly due to https and traefik. I am not saying it is not possible, but it needs some more thinking.

**Comment by rfay** [comment]
Closing, we're happy to help with what you'd like to do in the future.
