### ISSUE TITLE
`ddev config` should have better text about accepting default instead of "You may leave this value blank if your site files are in the project root"

### ISSUE THREAD

**Issue by alex1yaremchuk** [ddev/ddev#6542]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

>>You may leave this value blank if your site files are in the project root
Docroot Location (web):

having (web) in paranthesis suggests that it is the default value when no value is input

### Describe your solution

add web as default

### Describe alternatives

or change the label

**Comment by rfay** [comment]
Hi @alex1yaremchuk - Thanks for the suggestion. Are you talking about the docs, or the behavior of the `ddev config` tool?

`ddev config` does in fact detect the docroot for the vast majority of situations, and when it finds `web` as the docroot, it does offer it as the default (as you're showing) and if you hit `<RETURN>` it does use `web`. 

I guess maybe you're saying that `You may leave this value blank if your site files are in the project root` may be misleading, when in fact I'm not sure there is a way to specify "blank" when `ddev config` has autodetected the docroot. The text there probably predates autodetection of docroot (which is many years ago).

**Comment by alex1yaremchuk** [comment]
Thank you for the reply.
Right, I'm talking about ddev config. 
I'm new to Drupal, ddev and Pantheon, so I might missed something.

As I'm seeing it now - when I pressed enter it didn't put settings file down to detected docroot (web), but put it into the root: sites/.. (instead of web/sites/..)

I didn't try to reproduce this issue, when I ran it next time I just entered 'web'.

let me add more details below:
1. I clonned site from Pantheon
2. I ran ddev conf 
3. followed wizard with defaults
4. found out that settings files are in sites/..

**Comment by alex1yaremchuk** [comment]
> I know how bit a thing it is to land in all that new technology!
> 
> The thing to look at is where your index.php is. On a normal DDEV project it's in `web`, but that depends on the original setup.
> 
> If you want to show me a `tree -L 3` in your project root I may be able to help. You may have to install `tree`. I can't tell you how to install because you skipped the requested `ddev debug test` when creating this issue. (If you'd also provide the top part of your .ddev/config.yaml it would also help, and if you say the DDEV version you're using, `ddev --version` or give the requested `ddev debug test`.)
> 
> After you `ddev config` take a look at your project .ddev/config.yaml. What do you see there for `docroot`? It should be `docroot: web`
> 
> I just retested this and it works correctly.
> 
> I should note that you can just `ddev config --docroot=web` and you won't have to even think about this any more. Also `ddev config --auto` and `ddev config --update` should solve your problem.
> 
> To give you more perspective, please do a Drupal quickstart from https://ddev.readthedocs.io/en/stable/users/quickstart/#drupal and then do a `ddev stop --unlist` and a `rm -r .ddev`. That will leave you with a plain vanilla Drupal project that is unconfigured for ddev. You can then experiment with the various things to do with `ddev config`

Thank you for your kind reply! (I got a little ill last week, so replying only now, sorry)

I retried cloning from Patntheon to a new directory and running ddev config on it and made sure that there is no mistake in ddev. 

It shows "You may leave this value blank if your site files are in the project root
Docroot Location (current directory)". 

So opting for default docroot logically resulted in what I had for my first try.

**Comment by rfay** [comment]
If it said "Current directory" for the default then it did not correctly detect your docroot.

**Comment by alex1yaremchuk** [comment]
Right... not sure if there is anything we can do to investigate it further? 

I need to point out that it doesn't bother me anymore, but I'm ready to participate if it is good for ddev.

1) there is web folder in the cloned site root
2) composer.json includes 
```
"extra": {
        "drupal-scaffold": {
            "locations": {
                "web-root": "./web"
            },                         
```

**Comment by rfay** [comment]
I don't quite understand what you're saying yet. 

Reopening though, because the text prompt needs to be updated and it's a very easy PR.

Currently `ddev config` works perfectly when the code has already been checked out or placed by `ddev composer install`. It can't autodetect anything until that point. `ddev config --update` is what is used after the composer install or whatever.
