### ISSUE TITLE
VPN: Allowing ddev-webserver components like npm to trust an external https source when running under corporate VPN

### ISSUE THREAD

**Issue by errauch** [ddev/ddev#6544]
### Preliminary checklist

- [X] I am using the latest stable version of DDEV (see [upgrade guide](https://ddev.readthedocs.io/en/stable/users/install/ddev-upgrade/))
- [X] I have searched [existing issues](https://github.com/ddev/ddev/issues)
- [X] I have checked the [troubleshooting guide](https://ddev.readthedocs.io/en/stable/users/usage/troubleshooting/)
- [X] I have run `ddev debug test` to include output below

### Output of `ddev debug test`

<details><summary>Expand `ddev debug test` diagnostic information</summary>

```
[COPY-PASTE HERE THE OUTPUT OF `ddev debug test`]
```
</details>

### Expected Behavior

It is possible to add SSL certificates e.g. for Corporate network VPN: https://stackoverflow.com/questions/71595327/corporate-network-vpn-ddev-composer-create-results-in-ssl-certificate-proble/71595428

### Actual Behavior

In projects where an SSL certificate is required, there were solutions like this one: https://stackoverflow.com/questions/71595327/corporate-network-vpn-ddev-composer-create-results-in-ssl-certificate-proble/71595428#71595428 

Because of this change: https://github.com/ddev/ddev/issues/5509 it is not working anymore, right?
"RUN npm install -g n" will be executed before the certificate is added and the command will fail.

### Steps To Reproduce

https://stackoverflow.com/questions/71595327/corporate-network-vpn-ddev-composer-create-results-in-ssl-certificate-proble/71595428#71595428

**Comment by stasadev** [comment]
Hi @errauch,

Please give us the exact steps, along with `ddev debug test`.

> "RUN npm install -g n" will be executed before the certificate is added and the command will fail.

We do not have this instruction in the latest DDEV v1.23.4.

**Comment by errauch** [comment]
Thanks for your quick answer.

To be honest, a colleague of mine has this problem. She has version v1.23.3.
"RUN npm install -g n" was added in this release: https://github.com/ddev/ddev/releases/tag/v1.22.5 
But I see now that this was changed again: https://github.com/ddev/ddev/commit/c91869a5a840f55eeb020d71d09e80158542dcfc#diff-f9f56984436be48813b0b127635ff825b04e9f9ec4cfb826e728f366aaf0bd64 

I will ask her to update ddev and try again.

**Comment by errauch** [comment]
Update to newest version solved this issue. Thanks.
