### ISSUE TITLE
Traefik error creating file watcher: too many open files, 404 page not found

### ISSUE THREAD

**Issue by matthieu2607** [ddev/ddev#6553]
### Preliminary checklist

- [X] I am using the latest stable version of DDEV (see [upgrade guide](https://ddev.readthedocs.io/en/stable/users/install/ddev-upgrade/))
- [X] I have searched [existing issues](https://github.com/ddev/ddev/issues)
- [X] I have checked the [troubleshooting guide](https://ddev.readthedocs.io/en/stable/users/usage/troubleshooting/)
- [X] I have run `ddev debug test` to include output below

### Output of `ddev debug test`

<details><summary>Expand `ddev debug test` diagnostic information</summary>

```
2024-09-18T15:15:52Z INF github.com/traefik/traefik/v3/pkg/server/configurationwatcher.go:73 > Starting provider aggregator aggregator.ProviderAggregator
2024-09-18T15:15:52Z DBG github.com/traefik/traefik/v3/pkg/server/server_entrypoint_tcp.go:220 > Starting TCP Server entryPointName=http-8036
2024-09-18T15:15:52Z DBG github.com/traefik/traefik/v3/pkg/server/server_entrypoint_tcp.go:220 > Starting TCP Server entryPointName=http-8025
2024-09-18T15:15:52Z DBG github.com/traefik/traefik/v3/pkg/server/server_entrypoint_tcp.go:220 > Starting TCP Server entryPointName=traefik
2024-09-18T15:15:52Z INF github.com/traefik/traefik/v3/pkg/provider/aggregator/aggregator.go:202 > Starting provider *file.Provider
2024-09-18T15:15:52Z DBG github.com/traefik/traefik/v3/pkg/server/server_entrypoint_tcp.go:220 > Starting TCP Server entryPointName=http-8037
2024-09-18T15:15:52Z DBG github.com/traefik/traefik/v3/pkg/server/server_entrypoint_tcp.go:220 > Starting TCP Server entryPointName=http-80
2024-09-18T15:15:52Z DBG github.com/traefik/traefik/v3/pkg/provider/aggregator/aggregator.go:203 > *file.Provider provider configuration config={"directory":"/mnt/ddev-global-cache/traefik/config","watch":true}
2024-09-18T15:15:52Z DBG github.com/traefik/traefik/v3/pkg/server/server_entrypoint_tcp.go:220 > Starting TCP Server entryPointName=http-443
2024-09-18T15:15:52Z DBG github.com/traefik/traefik/v3/pkg/server/server_entrypoint_tcp.go:220 > Starting TCP Server entryPointName=http-8026
**2024-09-18T15:15:52Z ERR github.com/traefik/traefik/v3/pkg/provider/aggregator/aggregator.go:206 > Cannot start the provider *file.Provider error="error creating file watcher: too many open files"**
2024-09-18T15:15:52Z INF github.com/traefik/traefik/v3/pkg/provider/aggregator/aggregator.go:202 > Starting provider *traefik.Provider

```
</details>

### Expected Behavior

When you run the `ddev start` command, you should see the site via the domain name

### Actual Behavior

Randomly, when we launch a project, we get a "404 page not found" error when we access it via the domain (the site is displayed via the ip).

Looking at the logs with the command `docker logs -f ddev-router`, we see the following error:

 ‘ERR github.com/traefik/traefik/v3/pkg/provider/aggregator/aggregator.go:206 > Cannot start the provider *file.Provider error=’error creating file watcher: too many open files’.

We encounter this error on Ubuntu 22.04 and 24.04 and ddev on 1.23.4

**Comment by stasadev** [comment]
Hi @matthieu2607,

This is related to https://bugs.launchpad.net/snap-openstack/+bug/2027578

> Quite a few apps in k8s use inotify to watch a directory or file including traefik:

> 2023-07-12T10:37:47.536Z [traefik] time="2023-07-12T10:37:47Z" level=debug msg="*file.Provider provider configuration: {\"directory\":\"/opt/traefik/juju\",\"watch\":true}"
> 2023-07-12T10:37:47.536Z [traefik] time="2023-07-12T10:37:47Z" level=error msg="Cannot start the provider *file.Provider: error creating file watcher: too many open files"

> with lots of containers its really easy to hit the default inotify watch limit.

> When you have too many containers, you hit the default limit on Ubuntu:

> Blocking limit was actually the max number of inotify instances per user - which defaults to 128

> Increasing this to 512 resulted in service being restored and traefik correctly picking up configuration.

---

I see this on Ubuntu:

```
$ sysctl fs.inotify.max_user_instances
fs.inotify.max_user_instances = 128
```

Besides, on Arch Linux I have:
```
$ sysctl fs.inotify.max_user_instances
fs.inotify.max_user_instances = 1024
```

---

I recommend you to create a file:

```
$ cat /etc/sysctl.d/99-max-user-instances.conf
fs.inotify.max_user_instances = 1024
```

And reboot the machine.

**Comment by matthieu2607** [comment]
Hi @stasadev,

Thank you for your reply, I'm going to test your solution and I'll come back to this issue in 3/4 days to see if it improves.

Best regards

**Comment by rfay** [comment]
Great job on the debugging and analysis, thanks for checking the logs!

The limit may be a problem either with a host setting or a docker setting, in this case, it may be either a global docker setting or a traefik container setting. 

If I understand what you're facing, the key is what is happening inside the container, so you may want to check it by looking inside the ddev-router. Here's what I see on OrbStack on macOS:

```
$ docker exec -it ddev-router sysctl fs.inotify.max_user_instances
fs.inotify.max_user_instances = 1048576
```

On gitpod (Linux/Ubuntu/Docker-in-Docker) I see
```
sysctl fs.inotify.max_user_instances
fs.inotify.max_user_instances = 8192
```

One question to ask is... do you have a large number of projects running, or a lot of traefik configuration? Essentially, traefik tries to watch all the files in the `/mnt/ddev-global-cache/traefik/config` directory. Normally this is just a few files. Please take a look and see how many files are there. Maybe 
```
$ docker exec -it ddev-router find config -type f
config/d10.yaml
config/default_config.yaml
```

**Comment by stasadev** [comment]
The value inside the container follows the value on the host.

Ubuntu:

```
$ docker exec -it ddev-router sysctl fs.inotify.max_user_instances
fs.inotify.max_user_instances = 128

$ sysctl fs.inotify.max_user_instances
fs.inotify.max_user_instances = 128
```

Arch Linux:

```
$ docker exec -it ddev-router sysctl fs.inotify.max_user_instances
fs.inotify.max_user_instances = 1024

$ sysctl fs.inotify.max_user_instances
fs.inotify.max_user_instances = 1024
```

**Comment by rfay** [comment]
The question then may be whether you are using inotify extensively on the host (and if you can raise the limit to something more reasonable). If you're using vite or something on a modest-sized project you could easily use up 1024.

**Comment by matthieu2607** [comment]
Hi @stasadev and @rfay 

As promised, I'm getting back to you to let you know that we've had no more incidents on Ubuntu 22.04 and Ubuntu 24.04, the solution works fine, thank you!

This should probably be mentioned in the ddev documentation, as we must not be the only ones.

Many thanks for your support!

**Comment by rfay** [comment]
Thanks @matthieu2607 - Did you ever figure out what was causing traefik to listen to so many files? 

* What specifically might you have been doing to overrun the limit?  
* What was your fs.inotify.max_user_instances previously set to?

**Comment by rfay** [comment]
No response from @matthieu2607 so I'll close this, but I'd love to know what the setting was, and why it had problems. Happy to continue the conversation here or elsewhere.

**Comment by stasadev** [comment]
This problem can be reported on `ddev start`, see:

- #7442
