### ISSUE TITLE
Docs: Google is indexing "latest" but not providing content

### ISSUE THREAD

**Issue by rfay** [ddev/ddev#6559]
I happened to search ["ddev codespaces"](https://www.google.com/search?q=ddev+codespaces&oq=ddev+codespaces&gs_lcrp=EgZjaHJvbWUyBggAEEUYOTIGCAEQRRhAMgYIAhBFGDwyBggDEEUYPDIGCAQQRRg80gEINDE1OWoxajSoAgCwAgE&sourceid=chrome&ie=UTF-8) today, and this is what I got from google, "No information is available for this page":

<img width="947" alt="image" src="https://github.com/user-attachments/assets/2e7c6732-40e8-461e-8900-f35ee79af565">

Google seems to prefer the "latest" section, but we seem to be convincing google not to display that.  Down a bit is the "stable" link, with information and a proper link.

Our [robots.txt](https://ddev.readthedocs.io/robots.txt) has this:

```
User-agent: *

Disallow: /en/latest/ # Hidden version

Sitemap: https://ddev.readthedocs.io/sitemap.xml
```

So I imagine the `Disallow` is the reason for this behavior. 

We prefer for Google to index "stable", but for reasons unknown, it prefers "latest" anyway.

**Comment by rfay** [comment]
ChatGPT [says](https://chatgpt.com/share/66f10cbb-9798-8003-a4c1-4ea3dd6e012a)

* remove the "disallow"
* Add a "meta noindex" for latest
* Consider marking stable pages as "canonical"

**Comment by rfay** [comment]
From https://docs.readthedocs.io/en/stable/versions.html#version-states

> Hidden or Not hidden
Hidden docs are not listed on the [flyout menu](https://docs.readthedocs.io/en/stable/glossary.html#term-flyout-menu) on the docs site, or shown in search results from another version on the docs site (like on search results from a superproject).

...

> Hidden verions are listed as Disallow: /path/to/version/ in the default [robots.txt support](https://docs.readthedocs.io/en/stable/reference/robots.html) created by Read the Docs.

**Comment by rfay** [comment]
Side note: Readthedocs seems now to have an automatic version of @stasadev 's  "latest" redirector using their "add-ons", see https://docs.readthedocs.io/en/stable/versions.html#version-warning

Readthedocs add-ons are to be enabled on Oct 7, 2024, https://about.readthedocs.com/blog/2024/07/addons-by-default/


But it says [all project using mkdocs already have them](https://docs.readthedocs.io/en/stable/addons.html#enabling-read-the-docs-addons)

The new dashboard is at https://app.readthedocs.org/dashboard/

Ours shows version warning as enabled, https://app.readthedocs.org/dashboard/ddev/edit/

<img width="1289" alt="image" src="https://github.com/user-attachments/assets/5111fdfc-4ba9-48a5-8ba1-1abb40f9f199">

**Comment by stasadev** [comment]
I researched this several months ago when I was working on the warning, and I was excited to see "Show version warning" setting.

But this option "Show version warning" shows a pop-up from Read the Docs itself (not from Material for MkDocs), which doesn't follow our theme and it looks out of place.

I disabled this checkbox.

**Comment by rfay** [comment]
Now back to our regularly scheduled program, convincing google to do the right thing :)
