### ISSUE TITLE
Support new PostgreSQL 17

### ISSUE THREAD

**Issue by xHeaven** [ddev/ddev#6566]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

PostgreSQL 17 has been released on September 26, 2024. DDEV currently doesn't support it.

### Describe your solution

Let's add support for it.

### Additional context

https://www.postgresql.org/about/news/postgresql-17-released-2936/
https://www.postgresql.org/docs/17/release-17.html

**Comment by rfay** [comment]
Thank you!

**Comment by stasadev** [comment]
There are currently no `arm64` Docker images for Postgres 17.

**Comment by rfay** [comment]
* https://github.com/docker-library/postgres/issues/1272

**Comment by rfay** [comment]
Images with arm64 are there now, restarted jobs on the PR.
