### ISSUE TITLE
Consider removing ghostscript or making it optional

### ISSUE THREAD

**Issue by deviantintegral** [ddev/ddev#6571]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

Ghostscript support was added over at https://github.com/ddev/ddev/issues/920 to support typo3. While other systems can use it, it's not that common to do directly on a web node because PDF rendering can be memory intensive. Since that PR, some distributions including Ubuntu have actually disabled ImageMagick / GhostScript integration due to security issues: https://stackoverflow.com/a/60145352

As well, typo3 doesn't list ghostscript as a requirement. The only mention I can find for it in the docs is at https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/10.3/Feature-90416-SpecificTargetFileExtensionInImage-relatedViewHelpers.html#description.

Given that Ghostscript adds ~50MB to the web image. Let's not impose that cost on every DDEV user.

On master:

```
ddev/ddev-webserver-prod                             v1.23.4-47-gfec8d695f-dirty     c57d5ba5346a   7 minutes ago   1.39GB
ddev/ddev-webserver                                  v1.23.4-47-gfec8d695f-dirty     d21725fbef6f   7 minutes ago   1.62GB
```

Locally, removing ghostscript:

```
ddev/ddev-webserver-prod                             v1.23.4-47-gfec8d695f-dirty     f78c597f9b2c   About a minute ago   1.34GB
ddev/ddev-webserver                                  v1.23.4-47-gfec8d695f-dirty     f1bc54da514f   2 minutes ago        1.57GB
```

### Describe your solution

Either:

- Remove ghostscript entirely.
- Add a config option so the typo3 recipe can install ghostscript automatically.

**Comment by deviantintegral** [comment]
@nickchomey are you using typo3 or something else?

**Comment by garvinhicking** [comment]
I use it every day 🥹

**Comment by garvinhicking** [comment]
Ideally for TYPO3 it would be cool to have some kind of recipe that dynamically adds it to the image if "typo3" project type is selected? My reasoning would be to make it easy for people who try to contribute to TYPO3 (or have a dev instance) who might not be familar with ddev configs. And it would be a breaking change for them otherwise. 

One of the reasons for DDEV getting a high adoption for us was always, that the default web container is ready-to-go and can be used without much further very specific configuration.

**Comment by sbuerk** [comment]
I get the point to remove this, however I highly suggest to phase this out slighty. That means, the "ddev" command may eventually add some "warning/info" in ddev starts or similar.

Background for that is, that I know that in my current agency we have nearly every project which relies on the one or other way on that (TYPO3, Magento, Plain PHP Projects, Wordpress), and in my old company even more.

Taken into account that on a update and silently stripping that package would for sure waste a lot of time in many agencies and for freelancer investigating why their local setups with ddev no longer works or get errors.

Moving that to an extra package/install also means that no longer all may have the same setup depending on the time each developer has started/build their images or updated which can also leads to different setups.

So at least, please phase it out "slightly" over one or more versions and not dropping it simply so "agencies" may have time to add that extra package to their project repositories/branches to be prepared when it gets dropped.

If I'm not fully wrong, imagic/ghostscript combination is also used to generate pdf thumbnails which I guess more then the "fixed" apptypes may use.

Would consider removing this "carefully".

**Comment by rfay** [comment]
While the initiative of lightening the ddev-webserver is awesome, it sound like this is not the one we want to work on, too intrusive to existing workflows.

I'm going to close this one, but would love the same folks to take a look at 
* https://github.com/ddev/ddev/pull/6570

and say your opinions about that one.

**Comment by deviantintegral** [comment]
Thanks folks for all the feedback. It's good to know that this tool is more broadly than I expected!
