### ISSUE TITLE
Update documentation link in terminal output

### ISSUE THREAD

**Issue by jenlampton** [ddev/ddev#6573]
### Preliminary checklist

- [X] I am using the latest stable version of DDEV (see [upgrade guide](https://ddev.readthedocs.io/en/stable/users/install/ddev-upgrade/))
- [X] I have searched [existing issues](https://github.com/ddev/ddev/issues)
- [X] I have checked the [troubleshooting guide](https://ddev.readthedocs.io/en/stable/users/usage/troubleshooting/)
- [X] I have run `ddev debug test` to include output below

### Output of `ddev debug test`

<details><summary>Expand `ddev debug test` diagnostic information</summary>

```
not relevant I don't think. I'm checking the box anyway :D 
I am running version 1.23.4
```
</details>

### Expected Behavior

When importing the database for a backdrop site, ddev provides a helpful link to documentation, but this link now produces a 404.

The complete message is as follows:
`Backdrop sites require your config JSON files to be located in your site's "active" configuration directory. Please refer to the Backdrop documentation (https://backdropcms.org/user-guide/moving-backdrop-site) for more information about this process. `

### Actual Behavior

The link should be updated to
https://docs.backdropcms.org/documentation/deploying-a-backdrop-site

### Steps To Reproduce

1. Create a new backdrop site for ddev
2. Import a database using `ddev import-db`

### Anything else?

I'm loving ddev!

**Comment by rfay** [comment]
Would you consider doing a PR against https://github.com/ddev/ddev/blob/fec8d695ffd89634060ed10d465ce6ba6f0f87ff/pkg/ddevapp/backdrop.go#L164 ? You just click the pencil in the upper right:

![image](https://github.com/user-attachments/assets/4bf0608b-a483-4554-824c-6f2ab07b2a64)


Alternately, you could add a redirect on docs.backdropcms.org, but we're happy to have it right here.

Thanks for catching this!

**Comment by jenlampton** [comment]
Yep, I'll do both!

**Comment by rfay** [comment]
Looking forward to your PR, thanks.
