### ISSUE TITLE
Failures during install of add-on should give more context, including what was being attempted

### ISSUE THREAD

**Issue by joachim-n** [ddev/ddev#6578]
### Preliminary checklist

- [x] I am using the latest stable version of DDEV (see [upgrade guide](https://ddev.readthedocs.io/en/stable/users/install/ddev-upgrade/))
- [x] I have searched [existing issues](https://github.com/ddev/ddev/issues)
- [x] I have checked the [troubleshooting guide](https://ddev.readthedocs.io/en/stable/users/usage/troubleshooting/)
- [x] I have run `ddev debug test` to include output below

### Expected Behavior

It would be useful if the error message for an add-on included a string that allows finding the problem in the code.

### Actual Behavior

When a ddev add-on has a problem with an action, the output looks like this:

```
Executing post-install actions:
cp: ../core/phpunit.xml: No such file or directory

👎
Could not process post-install action (0) ''
```

The problem is that if I search the add-on codebase for the string 'post-install' I find nothing, because what there is is this:

```
post_install_actions:
```

**Comment by joachim-n** [comment]
I'm working on a local fork. The problem isn't the specific command that went wrong, it's that the error message "Could not process post-install action" doesn't help me find the problem.

Something like:

> "Could not process post-install action (item N in post_install_actions)" 

or:

> "Could not process post-install action (line N in install.yaml)"

would be better.

**Comment by rfay** [comment]
You're saying that you want it to output the step it was working on in addition to the error message from the step, is that correct?

**Comment by joachim-n** [comment]
That would be the stretch goal, yes! :)

But just having the string 'post_install_actions' in the message would mean that a developer can find the right place in the code.

**Comment by rfay** [comment]
Why don't you add a `set -x` to your steps during development? That makes a huge difference any time you're working with bash.

**Comment by stasadev** [comment]
I'm closing this because we already have a verbose flag here, that adds `set -x`:

```
$ ddev help get
Flags:
  -v, --verbose          Extended/verbose output for ddev get
```

Example:

```yaml
post_install_actions:
- |
  cp test .
```

```
$ ddev get /path/to/my/addon
...
Executing post-install actions: 
cp: cannot stat 'test': No such file or directory
 
👎  
Could not process post-install action (0) ''
```

```
$ ddev get /path/to/my/addon -v
...
Executing post-install actions: 
+ set -eu -o pipefail
+ true
+ cp test .
cp: cannot stat 'test': No such file or directory
 
👎  
Could not process post-install action (0) '': Unable to run action set -x; set -eu -o pipefail
true; cp test .
: exit status 1, output=+ set -eu -o pipefail
+ true
+ cp test .
cp: cannot stat 'test': No such file or directory
```
