### ISSUE TITLE
`ddev export-db > file` contains DDEV startup output if Docker container is not currently running, making invalid dump

### ISSUE THREAD

**Issue by cooperka** [ddev/ddev#6583]
### Preliminary checklist

- [x] I am using the latest stable version of DDEV (see [upgrade guide](https://ddev.readthedocs.io/en/stable/users/install/ddev-upgrade/))
- [x] I have searched [existing issues](https://github.com/ddev/ddev/issues)
- [x] I have checked the [troubleshooting guide](https://ddev.readthedocs.io/en/stable/users/usage/troubleshooting/)
- [x] I have run `ddev debug test` to include output below

### Output of `ddev debug test`

<details><summary>Expand `ddev debug test` diagnostic information</summary>

```
I'm uncomfortable posting all these detailed diagnostics publicly online,
so I'll at least paste the relevant version numbers, and I can include more
info if you fail to reproduce it:

======== DDEV version ========
 ITEM             VALUE                                    
 DDEV version     v1.23.4                                  
 architecture     arm64                                    
 cgo_enabled      0                                        
 db               ddev/ddev-dbserver-mariadb-10.11:v1.23.4 
 ddev-ssh-agent   ddev/ddev-ssh-agent:v1.23.4              
 docker           27.2.0                                   
 docker-api       1.47                                     
 docker-compose   v2.29.1                                  
 docker-platform  docker-desktop                           
 global-ddev-dir  /Users/cooperka/.ddev
 mutagen          0.17.2                                   
 os               darwin                                   
 router           ddev/ddev-traefik-router:v1.23.4         
 web              ddev/ddev-webserver:v1.23.4              
```
</details>

### Expected Behavior

- DDEV should export properly using any variation of the [instructions](https://ddev.readthedocs.io/en/stable/users/usage/commands/#export-db)

### Actual Behavior

* Even though these files should all be identical, the first one `export-offline.sql.gz` will contain console logs that corrupt the file (example below)

### Steps To Reproduce

1. Set up a DDEV project, for example by following Drupal's [new project startup guide](https://www.drupal.org/docs/official_docs/local-development-guide)
1. Turn **off** the new Docker container that was created
1. Run `ddev export-db > export-offline.sql.gz` (which will start up the container while exporting)
1. Run `ddev export-db > export-online.sql.gz` (which will use the already-started container)
1. Run `ddev export-db --file=export-file.sql.gz` (which will work regardless)
1. Open the exported files in a text editor

### Anything else?

Example logging info at the top of the file:

```
Building project images...
[32mProject images built in 1s.[0m
 Container ddev-test-web  Recreate
 Container ddev-test-db  Recreate
 Container ddev-test-db  Recreated
 Container ddev-test-web  Recreated
 Container ddev-test-web  Started
 Container ddev-test-db  Started
Starting Mutagen sync process...
[32mMutagen sync flush completed in 2s.
For details on sync status 'ddev mutagen st test -l'[0m
Waiting for containers to become ready: [web db]
Starting ddev-router if necessary...
 Container ddev-router  Running
Waiting for additional project containers to become ready...
Waiting 120s for additional project containers [ddev-test-db ddev-test-web] to become ready...
All project containers are now ready.
[and now the binary output that should have been here begins]
```

**Comment by rfay** [comment]
Hi @cooperka - Please use `ddev export-db --file=/path/to/db.sql.gz` instead, so that DDEV will have some control of the output. 

What you're doing is letting bash create the output file, which includes the startup in this situation. But if you use the `--file` arg, you won't have that problem.

I'd be interested why you're using the unusual "bare" `ddev export-db`, and if people did that they'd normally use `ddev export-db --gzip=false` to get a plain text file. (But even then, `ddev export-db --file=db.sql --gzip=false` is a lot better.

**Comment by cooperka** [comment]
Hi @rfay, I was just trying to follow the documentation here https://ddev.readthedocs.io/en/stable/users/usage/commands/#export-db which suggests `ddev export-db > /tmp/db.sql.gz` as a valid usage of the program. Maybe that should be removed.

As far as I can tell, my export is permanently corrupted even after removing the log info from the top and saving properly as a binary file (just like the "real" export with `file=`) so I'd appreciate help if anyone can **please advise how to uncorrupt the original file**.

I had assumed I made a safe backup, and when I tried importing it before realizing the issue, the `ddev import-db` script dropped the current DB before trying to read the corrupt file, so now I have no database and no working backup 😓 

Thanks for the quick reply!

**Comment by cooperka** [comment]
For context: error message upon trying to import the fixed dump using `ddev import-db --file=../db.sql.gz`:

`Error: failed to import database 'db' for test: failed to extract provided file: flate: corrupt input before offset 1020`

**Comment by rfay** [comment]
The bad file you created starts with the text of starting up ddev (some of which goes to stdout) followed by the compressed output of the database, still going to stdout.

If you want to see more of what's going on use `--gzip-false`, then you'll see the content of the file with just`less`

The file you have created is not a valid gzipped file (you captured stdout with bogus content). So that's why you get the error message you have.

**Comment by rfay** [comment]
Thanks for raising this. The associated PR didn't get followed through and this is definitely an edge case. Closing this for now.
