### ISSUE TITLE
TestComposerCreateCmd doesn't work with Composer 2.8.1

### ISSUE THREAD

**Issue by rfay** [ddev/ddev#6586]
### Actual Behavior

Panic SEGV in pkg/composer/composer.go:65

I note this panic in TestComposerCreateCmd, https://buildkite.com/ddev/macos-colima-vz/builds/1710#01925778-6aa1-439e-a5a2-800234aee613/15326-15327

```


panic: runtime error: invalid memory address or nil pointer dereference [recovered]
  | panic: runtime error: invalid memory address or nil pointer dereference
  | [signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x105300470]
  |  
  | goroutine 737 [running]:
  | testing.tRunner.func1.2({0x1055ce140, 0x105bc7190})
  | /opt/homebrew/Cellar/go/1.23.2/libexec/src/testing/testing.go:1632 +0x1bc
  | testing.tRunner.func1()
  | /opt/homebrew/Cellar/go/1.23.2/libexec/src/testing/testing.go:1635 +0x334
  | panic({0x1055ce140?, 0x105bc7190?})
  | /opt/homebrew/Cellar/go/1.23.2/libexec/src/runtime/panic.go:785 +0x124
  | github.com/ddev/ddev/pkg/composer.(*Manifest).keyExists(...)
  | /Users/testbot/tmp/buildkite-agent/builds/tb-macos-arm64-6/ddev/macos-colima-vz/pkg/composer/composer.go:65
  | github.com/ddev/ddev/pkg/composer.(*Manifest).HasPostRootPackageInstallScript(...)
  | /Users/testbot/tmp/buildkite-agent/builds/tb-macos-arm64-6/ddev/macos-colima-vz/pkg/composer/composer.go:104
  | github.com/ddev/ddev/cmd/ddev/cmd.TestComposerCreateCmd(0x14000334ea0)
  | /Users/testbot/tmp/buildkite-agent/builds/tb-macos-arm64-6/ddev/macos-colima-vz/cmd/ddev/cmd/composer-create_test.go:222 +0x2280
  | testing.tRunner(0x14000334ea0, 0x1056a0cb0)
  | /opt/homebrew/Cellar/go/1.23.2/libexec/src/testing/testing.go:1690 +0xe4
  | created by testing.(*T).Run in goroutine 1
  | /opt/homebrew/Cellar/go/1.23.2/libexec/src/testing/testing.go:1743 +0x314
 ```

Same panic in https://buildkite.com/ddev/macos-lima/builds/1540#01925778-5d35-4f2c-858c-8153bd8e65e8

This may have been going on for some time.

**Comment by stasadev** [comment]
Something changed in Composer 2.8.1, released today https://github.com/composer/composer/releases/tag/2.8.1

The panic is not the actual panic in DDEV, it's because `assert` is used instead of `require`:

https://github.com/ddev/ddev/blob/cccd95557898033d74c83bedea1b608ac6651345/cmd/ddev/cmd/composer-create_test.go#L147-L148

The actual error is https://buildkite.com/ddev/macos-colima-vz/builds/1710#01925778-6aa1-439e-a5a2-800234aee613/15049-15146

```
[RuntimeException]
2024-10-04 13:28:04 UTC	        	            	  Source path ".ddev/test-ddev-composer-create" is not found for package test
2024-10-04 13:28:04 UTC	        	            	  /ddev-composer-create
```

It is triggered when I pass a local `--repository` to `ddev composer create`.

AFAICT, it affected only our tests.

To reproduce:
```
mkdir composer-test && cd composer-test
ddev config --composer-version="2.8.1"
mkdir -p .ddev/test-ddev-composer-create && echo '{"name":"test/ddev-composer-create","version": "1.0.0"}' > .ddev/test-ddev-composer-create/composer.json
ddev composer create --repository='{"type": "path", "url": ".ddev/test-ddev-composer-create", "options": {"symlink": false}}' test/ddev-composer-create
```

The same works with Composer 2.8.0

**Comment by stasadev** [comment]
Opened

- https://github.com/composer/composer/issues/12150

**Comment by stasadev** [comment]
The bad thing is that it broke all our tests, if it is not resolved upstream soon, the alternative is to create a new git repository and use it like this:

```
ddev composer create --repository '{"type":"vcs","url":"https://github.com/ddev/test-composer-create"}' ddev/test-composer-create
```

This will probably require adding a GitHub token to Composer config.

**Comment by stasadev** [comment]
Yes, we can push the repo to packagist.org, and it will be available publicly, I leave it as our option.

**Comment by rfay** [comment]
I *think* you can do public just fine with static files on github too, but any way is fine.
