### ISSUE TITLE
Which one is correct/recommended: `drud/ddev/ddev` or `ddev/ddev/ddev`

### ISSUE THREAD

**Issue by alanmels** [ddev/ddev#6594]
### Preliminary checklist

- [ ] I am using the latest stable version of DDEV (see [upgrade guide](https://ddev.readthedocs.io/en/stable/users/install/ddev-upgrade/))
- [x] I have searched [existing issues](https://github.com/ddev/ddev/issues)
- [x] I have checked the [troubleshooting guide](https://ddev.readthedocs.io/en/stable/users/usage/troubleshooting/)
- [x] I have run `ddev debug test` to include output below

### Output of `ddev debug test`

Running `brew upgrade ddev` is giving me:

```
Error: Formulae found in multiple taps:
       * drud/ddev/ddev
       * ddev/ddev/ddev

Please use the fully-qualified name (e.g. drud/ddev/ddev) to refer to a specific formula.

```
Searched the issues and on https://github.com/ddev/ddev/issues/3794 I've found I could untap one of the two, but could not figure out which one is correct/recommended and which one is to be get rid of?

### Expected Behavior

Searched the issues and on https://github.com/ddev/ddev/issues/3794 I've found I could untap one of the two, but could not figure out which one is correct/recommended and which one is to be get rid of?

### Actual Behavior

Searched the issues and on https://github.com/ddev/ddev/issues/3794 I've found I could untap one of the two, but could not figure out which one is correct/recommended and which one is to be get rid of?

**Comment by alanmels** [comment]
The documentations page on https://ddev.readthedocs.io/en/latest/users/install/ddev-installation/#macos recommends using `ddev/ddev/ddev`, however searching further on the subject I see the `drud/ddev/ddev` as, for example, on https://github.com/ddev/ddev/issues/4561#issuecomment-1397079808. It would be really nice to address this confusion and stick with the correct one everywhere.

**Comment by rfay** [comment]
Hi @alanmels - the org `drud` hasn't been used for quite a long time. We updated everything to use the `ddev` org in March, 2023.

To solve your problem:

```
brew uninstall -f ddev
brew untap drud/ddev
brew install ddev/ddev/ddev
```

**Comment by alanmels** [comment]
Thanks for the quick response @rfay!
