### ISSUE TITLE
Add a security certificate to Brave browser

### ISSUE THREAD

**Issue by Raf-sns** [ddev/ddev#6601]
### Preliminary checklist

- [x] I am using the latest stable version of DDEV (see [upgrade guide](https://ddev.readthedocs.io/en/stable/users/install/ddev-upgrade/))
- [x] I have searched [existing issues](https://github.com/ddev/ddev/issues)
- [x] I have checked the [troubleshooting guide](https://ddev.readthedocs.io/en/stable/users/usage/troubleshooting/)
- [x] I have run `ddev debug test` to include output below

### Output of `ddev debug test`

<details><summary>Expand `ddev debug test` diagnostic information</summary>
======== Output file will be in /tmp/ddev-debug-test.txt ========

======== Existing project config ========
ddev installation alternate locations:
/usr/bin/ddev
/bin/ddev

These config files were loaded for project test-ddev: [/home/raf/SITES WEB/TEST-DDEV/.ddev/config.yaml]
name: test-ddev
type: php
php_version: 8.2
webserver_type: nginx-fpm
webimage: ddev/ddev-webserver:v1.23.4
additional_hostnames: []
additional_fqdns: []
database: {mariadb 10.11}
project_tld: ddev.site
use_dns_when_possible: true
composer_version: 2
nodejs_version: 20
default_container_timeout: 120

======== existing project customizations ========

======== installed DDEV add-ons ========
┌────────────┬─────────┬──────────────────────┬───────────────────────────┐
│ ADD-ON     │ VERSION │ REPOSITORY           │ DATE INSTALLED            │
├────────────┼─────────┼──────────────────────┼───────────────────────────┤
│ phpmyadmin │ v0.3.9  │ ddev/ddev-phpmyadmin │ 2024-10-08T21:10:25+02:00 │
└────────────┴─────────┴──────────────────────┴───────────────────────────┘

======== mutagen situation ========
looking for #ddev-generated in mutagen.yml in project /home/raf/SITES WEB/TEST-DDEV
.ddev/mutagen/mutagen.yml not found

======== Creating dummy project named tryddevproject-22847 in ../tryddevproject-22847 ========
Creating a new DDEV project config in the current directory (/home/raf/SITES WEB/tryddevproject-22847)
Once completed, your configuration will be written to /home/raf/SITES WEB/tryddevproject-22847/.ddev/config.yaml

Configuring a 'php' project named 'tryddevproject-22847' with docroot 'web' at '/home/raf/SITES WEB/tryddevproject-22847/web'.
For full details use 'ddev describe'.
Configuration complete. You may now run 'ddev start'.

======== OS Information ========
Linux koko2 6.8.0-45-lowlatency #45.1-Ubuntu SMP PREEMPT_DYNAMIC Tue Sep  3 09:30:47 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

======== User information ========
uid=1000(raf) gid=1000(raf) groupes=1000(raf),4(adm),24(cdrom),27(sudo),29(audio),30(dip),46(plugdev),100(users),114(lpadmin),988(docker)

======== DDEV version ========
 ITEM             VALUE                                    
 DDEV version     v1.23.4                                  
 architecture     amd64                                    
 cgo_enabled      0                                        
 db               ddev/ddev-dbserver-mariadb-10.11:v1.23.4 
 ddev-ssh-agent   ddev/ddev-ssh-agent:v1.23.4              
 docker           27.3.1                                   
 docker-api       1.47                                     
 docker-compose   v2.29.1                                  
 docker-platform  linux-docker                             
 global-ddev-dir  /home/raf/.ddev                          
 mutagen          0.17.2                                   
 os               linux                                    
 router           ddev/ddev-traefik-router:v1.23.4         
 web              ddev/ddev-webserver:v1.23.4              

======== proxy settings ========

 HTTP_PROXY=''
 HTTPS_PROXY=''
 http_proxy=''
 NO_PROXY=''
 

======== DDEV global info ========
developer-mode=false
disable-http2=false
fail-on-hook-fail=false
instrumentation-opt-in=false
instrumentation-queue-size=0
instrumentation-reporting-interval=0s
instrumentation-user=
internet-detection-timeout-ms=3000
last-started-version=v1.23.4
letsencrypt-email=
mailpit-http-port=8025
mailpit-https-port=8026
mkcert-caroot=/home/raf/.local/share/mkcert
no-bind-mounts=false
omit-containers=[]
performance-mode=none
project-tld=ddev.site
required-docker-compose-version=v2.29.1
router=traefik
router-bind-all-interfaces=false
router-http-port=80
router-https-port=443
simple-formatting=false
table-style=default
traefik-monitor-port=10999
use-docker-compose-from-path=false
use-hardened-images=false
use-letsencrypt=false
wsl2-no-windows-hosts-mgt=false
xdebug-ide-location=

======== DOCKER provider info ========
docker client location: -rwxr-xr-x 1 root root 40937024 sept. 20 13:40 /usr/bin/docker

docker client alternate locations:
/usr/bin/docker
/bin/docker

Docker provider: linux-docker
docker version: 
Client: Docker Engine - Community
 Version:           27.3.1
 API version:       1.47
 Go version:        go1.22.7
 Git commit:        ce12230
 Built:             Fri Sep 20 11:40:59 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          27.3.1
  API version:      1.47 (minimum version 1.24)
  Go version:       go1.22.7
  Git commit:       41ca978
  Built:            Fri Sep 20 11:40:59 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.7.22
  GitCommit:        7f7fdf5fed64eb6a7caf99b3e12efcf9d60e311c
 runc:
  Version:          1.1.14
  GitCommit:        v1.1.14-0-g2c9f560
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

DOCKER_DEFAULT_PLATFORM=notset
Docker platform: linux-docker
Using Docker context: default (unix:///var/run/docker.sock)
docker-compose: v2.29.1
Using DOCKER_HOST=unix:///var/run/docker.sock
Docker version: 27.3.1
Able to run simple container that mounts a volume.
Able to use internet inside container.
Docker disk space:Filesystem                Size      Used Available Use% Mounted on
overlay                 438.0G    100.2G    315.5G  24% /

======== Existing docker containers ========
CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES

======== mkcert information ========
/usr/bin/mkcert
/bin/mkcert
/home/raf/.local/share/mkcert
total 8
-r-------- 1 raf raf 2484 oct.   8 20:30 rootCA-key.pem
-rw-r--r-- 1 raf raf 1631 oct.   8 20:30 rootCA.pem

======== ping attempt on ddev.site ========
PING dkdkd.ddev.site (127.0.0.1) 56(84) bytes of data.
64 bytes from localhost (127.0.0.1): icmp_seq=1 ttl=64 time=0.086 ms

--- dkdkd.ddev.site ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.086/0.086/0.086/0.000 ms

</details>

### Expected Behavior

Being able to open my test site with the https protocol on Brave browser

### Actual Behavior

net::ERR_CERT_AUTHORITY_INVALID

### Steps To Reproduce

Do a normal DDEV installation, run the command `ddev start` then open the test site with the given url

### Anything else?

Hi!
Thanks for this great project.

I used to use LAMPP to work off-server on PHP/MySQL projects but I was missing the management of security certificates on this solution.

Recently I have been using Brave bowser to test and work on website tests.

I am using Ubuntu Studio OS, the latest version that includes Ubuntu 24.04.1 LTS.

First of all, I followed all the steps to install DDEV but it failed at first. Then I followed the instructions given by the AI ​​integrated into Brave and the installation was successful.

I installed mkcert and ran it for my test site.
No change, the site remains as unsecured on Brave.
I asked Brave's AI for a solution again and it told me to do the following:
I created a .ddev/custom_cert folder and then inside I ran the command mkcert test-ddev.ddev.site which created two certificates:
test-ddev.ddev.site-key.pem and test-ddev.ddev.site.pem.

What happens is that when I open my test site on Firefox browser, the certificate works correctly, I don't have any security-related errors.
However, when I open this same test site on Brave, I get a privacy-related error.

Thank you for your comments / remarks to make my test site work on Brave without security alerts.
I don't want to use Firefox to work because the console is not optimal to work properly, I could list what does not suit me in Firefox to work there serenely but that is not the subject.

I already had this problem of certificate produced by mkcert (with LAMPP) and previous research told me that the certificates produced by mkcert were not recognized as valid with Google Chrome for example.

Another thing, but which can be important:

After running the command `ddev start` I get the following message in the console:

`Network ddev_default created
Starting test-ddev...
Container ddev-ssh-agent Created
Container ddev-ssh-agent Started
ssh-agent container is running: If you want to add authentication to the ssh-agent container, run 'ddev auth ssh' to enable your keys. `

And when I run `ddev auth ssh' I get the following error: 

`Docker command 'docker [run -it --rm --volumes-from=ddev-ssh-agent --user=1000 --entrypoint= --mount=type=bind,src=/home/raf/.ssh,dst=/tmp/sshmp ddev/ddev-ssh-agent:v1.23.4-built bash -c cp -r /tmp/sshtmp ~/.ssh && chmod -R go-rwx ~/.ssh && cd ~/.ssh && ssh-add $(file * | awk -F: "/private key/ { print \$1 }")]' failed: exit status 1` 

Thanks for your help, 
best regards, Raf.

**Comment by Raf-sns** [comment]
Hello,
thanks for your quick response, it works!

I put here the procedure that worked for me, it can be used as a memo in the future.

1/ Open Brave settings
2/ In settings open Privacy and security
3/ Open Security
4/ In Security open Manage certificates (HTTPS | SSL)
5/ Click on the "Import" button
6/ Search for the certificate created by the `mkcert` command,
for me the path was:
sda2 (operating system installation partition) > usr > local > share > ca-certificates / mkcert_development_CA_[random number].crt
7/ Reload the page, the certificate is installed, the https protocol is used.

Thanks again for your help, I am not used to working on a localhost server.
I hope this will help other people.

Kind regards,
Raf.

**Comment by rfay** [comment]
Thanks, some browser's don't respect the system CA. mkcert installs into the system CA, and also tries to do Chrome and Firefox, but can't do everywhere. And I guess brave is one of the browsers that doesn't use the system CA.

**Comment by GiorgosK** [comment]
> Hello, thanks for your quick response, it works!
> 
> I put here the procedure that worked for me, it can be used as a memo in the future.
> 
> 1/ Open Brave settings 2/ In settings open Privacy and security 3/ Open Security 4/ In Security open Manage certificates (HTTPS | SSL) 5/ Click on the "Import" button 6/ Search for the certificate created by the `mkcert` command, for me the path was: sda2 (operating system installation partition) > usr > local > share > ca-certificates / mkcert_development_CA_[random number].crt 7/ Reload the page, the certificate is installed, the https protocol is used.
> 
> Thanks again for your help, I am not used to working on a localhost server. I hope this will help other people.
> 
> Kind regards, Raf.

Great
a bit shorter description
- mkcert -CAROOT to find location of certificates
- brave://settings/certificates > Authorities
- open up location on step one select file
- accept all options
