### ISSUE TITLE
Allow `ddev config` to specify a particular drupal sub-version and retain that configuration

### ISSUE THREAD

**Issue by hanoii** [ddev/ddev#6633]
In working on https://github.com/ddev/ddev-drupal-contrib/pull/87 I have an issue

Imagine the following scenario:

- I have a contrib module
- I download the addon
- I start the project with php 8.2 because the module was already setup for php 8.2
- I run `ddev poser` fails because it needs php 8.3

So the rest doesn't work, and `ddev config --update` doesn't work either. 

**I know php 8.3 is the recommended command, but this could fail on newer versions**.

So personally I would suggest one of two things:

- Be verbose on the addos on the settings that ddev needs, forcefully adding corepack and php 8.3 for D11 and php 8.2 for D10 if those are the minimum requirements.
- Better yet, as ddev already [handles that](https://github.com/ddev/ddev/blob/a6d7d237c0a403e5d878b8378bf24f3d7f5ab8eb/pkg/ddevapp/drupal.go#L390) provide a way to pass this drupal version through a command line override.

Would something like this be accepted?

Something like `ddev config --project-type=drupal --drupal-version=11`?

**Comment by rfay** [comment]
I think what I'd like best is for `ddev describe` to say `drupal(11)` or something like that. Should be pretty easy. So make clear that it's project type `drupal` with the detected subtype `11`

**Comment by rfay** [comment]
This is what DDEV does:
https://github.com/ddev/ddev/blob/fddf8c8df8e38ffd9214d6220140f9275640f636/pkg/ddevapp/drupal.go#L326-L342

**Comment by hanoii** [comment]
Yeah I noted that on issue summary. I am trying to address the alternative to configure a project type with a Drupal version without anything to look the version for

**Comment by rfay** [comment]
DDEV doesn't track that, so that would be going back to the older way. There was definitely a significant conversation before doing it the way we did.

**Comment by hanoii** [comment]
I understand. I guess I was seeing if there was a way away to bring the old way back but only through an optional override or something. Like if want to force it for any reason

**Comment by rfay** [comment]
So the title should be something like "Allow `ddev config` to specify a particular `drupal` subversion and retain that configuration" ?

**Comment by hanoii** [comment]
Something like that, yes, or "use the default configuration for that drupal subversion"

**Comment by rfay** [comment]
Related conversation in 
* https://github.com/ddev/ddev/issues/6306

**Comment by rfay** [comment]
Let's solve this in 
* https://github.com/ddev/ddev/issues/6635

Looking forward to your ideas (and maybe implementation), thanks.
