### ISSUE TITLE
Add a `ddev cd <projectname>` command

### ISSUE THREAD

**Issue by TravisCarden** [ddev/ddev#6639]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Is your feature request related to a problem?

No.

### Describe your solution

[homeshick](https://github.com/andsens/homeshick), which I use to manage my dot files on my Mac, provides a really handy command to `cd` into a given "castle", as it calls them, without having to type its whole path--or even know it: `homeshick cd CASTLE`.

I think a comparable command for DDEV would be awesome: `ddev cd <projectname>`

**Comment by rfay** [comment]
I use `autojump` on macOS and Linux, it's wonderful. 

One thing to note is that custom DDEV commands that use 
```
## HostWorkingDir: true
```
like `ddev yarn` do automatically do their thing in the same relative dir you're on on the host.

**Comment by stasadev** [comment]
> provides a really handy command `cd` into a given "castle"

It's a function that is added to `~/.bashrc` or friends https://github.com/andsens/homeshick/blob/master/homeshick.sh

> To invoke homeshick, source the homeshick.sh script from your rc-script:
> from sh and its derivates (bash, dash, ksh, zsh etc.)
> printf '\nsource "$HOME/.homesick/repos/homeshick/homeshick.sh"' >> $HOME/.bashrc

We can't have it in DDEV itself, but people can add this to their `~/.bashrc` or `~/.zshrc` or somewhere else:

If `jq` is installed (faster):

```bash
ddev() {
  if [ "$1" = "cd" ] && [ -n "$2" ]; then
    cd "$(DDEV_VERBOSE=false DDEV_DEBUG=false ddev describe $2 -j | jq -r .raw.approot)"
  else
    command ddev "$@"
  fi
}
```

If `jq` is not installed (slower):

```bash
ddev() {
  if [ "$1" = "cd" ] && [ -n "$2" ]; then
    cd "$(DDEV_VERBOSE=false DDEV_DEBUG=false ddev describe $2 -j | docker run -i --rm ddev/ddev-utilities jq -r .raw.approot)"
  else
    command ddev "$@"
  fi
}
```

**Comment by stasadev** [comment]
The technique with `ddev describe -j` and `jq` is good https://github.com/ddev/ddev/issues/6639#issuecomment-2433370110, but not good enough, because it doesn't have autocomplete.

@TravisCarden, @nickchomey, check this out:

- https://github.com/ddev/ddev/pull/6644

**Comment by hanoii** [comment]
Nice addition! on the autojump and friends I personally favour [z.lua](https://github.com/skywind3000/z.lua) - differences are subtle, but this one is my pick.
