### ISSUE TITLE
Add `ddev project-set <projectname>` command to "pin" to a given project

### ISSUE THREAD

**Issue by TravisCarden** [ddev/ddev#6640]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Is your feature request related to a problem?

No.

### Describe your solution

Drush provides a `site:set` (`use`) command to "pin" to a given site alias so you don't have to specify it with every command. I would love to see a comparable command for DDEV: `ddev project-set <projectname>` (alias `ddev use`).

**Comment by rfay** [comment]
Sorry, I don't actually understand the request here @TravisCarden . 

If you want the project name to be configurable, leave `name` out of the config.yaml and it will take the directory's name.

**Comment by stasadev** [comment]
This is about having something like this:

```
cd ~
ddev project-set d11

# home here
pwd

# run some commands that have --project flag or accept project
# in completely different dir while having project pinned
ddev describe
ddev start
ddev stop
```

But I want to say, that even if we have this, it won't work for global and local bash commands, like `ddev launch`.

---

I think this feature can be confusing for DDEV users.

It's easier to use the newly added `ddev cd`:

- #6644

**Comment by rfay** [comment]
Let's go with `ddev cd` for now, see if you like it @TravisCarden , fine to continue the conversation here or elsewhere, especially if you try `ddev cd` in HEAD or when DDEV v1.24.0 comes out in the next month or so.

**Comment by TravisCarden** [comment]
Sure, @rfay. 👍 Of course, if a person were crazy enough, they could probably do something with an environment variable, like this:

```diff
diff --git a/pkg/ddevapp/global_dotddev_assets/commands/host/shells/ddev.sh b/pkg/ddevapp/global_dotddev_assets/commands/host/shells/ddev.sh
index b01098fcf..d7d5f274f 100644
--- a/pkg/ddevapp/global_dotddev_assets/commands/host/shells/ddev.sh
+++ b/pkg/ddevapp/global_dotddev_assets/commands/host/shells/ddev.sh
@@ -6,6 +6,13 @@
 # "ddev cd project-name" to cd into the project directory.
 
 ddev() {
+  if [ -n "$DDEV_PROJECT" ] && [ "$1" != "cd" ]; then
+    # If a $DDEV_PROJECT environment variable is set and the command is NOT `cd`,
+    # run the ddev command from that directory and return without changing $OLDPWD.
+    (cd "$(DDEV_VERBOSE=false command ddev cd "$DDEV_PROJECT" --get-approot)" && command ddev "$@")
+    return
+  fi
+
   if [ "$#" -eq 2 ] && [ "$1" = "cd" ]; then
     case "$2" in
       -*) command ddev "$@" ;;
```

Then they could...

```
$ pwd
/Users/travis

$ ddev describe
Failed to describe project(s): could not find a project in /Users/travis. Have you run 'ddev config'? Please specify a project name or change directories: no .ddev/config.yaml file was found in this directory or any parent

$ DDEV_PROJECT=drupal

$ ddev describe | grep Project
│ Project: drupal ~/Sites/drupal.ddev.site https://drupal.ddev.site             │

$ pwd
/Users/travis
```

But, as I say, such person would be crazy, am·i·rite? 😉

**Comment by rfay** [comment]
You can do it!
