### ISSUE TITLE
Add the ability to create arbitrary core command aliases

### ISSUE THREAD

**Issue by TravisCarden** [ddev/ddev#6641]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Is your feature request related to a problem?

No.

### Describe your solution

Git provides a really nice ability to create core command aliases ([`git-config`](https://git-scm.com/docs/git-config#Documentation/git-config.txt-alias)). I alias `git co` to `git checkout` and `git sb` to `git show-branch`, for example*. A comparable feature in DDEV, presumably configured in `.ddev/config.yaml`, would be awesome.

\* Those two simple example save me a lot of typos, but you can go crazy with it, too: for example, `git lp` to `log --all --graph --decorate --no-merges --oneline --simplify-by-decoration --pretty='%C(cyan)%h%Creset%C(auto)%d%C(reset) %s - %cr'`. Try it. 😄

### Additional context

This is superficially related to but distinct from https://github.com/ddev/ddev/issues/6443.

**Comment by rfay** [comment]
I don't think we'll probably take this on, but a PR is welcome. You might also consider bash/zsh aliases. Thanks!
