### ISSUE TITLE
Create command aliases for `ddev composer` and `ddev drush`

### ISSUE THREAD

**Issue by TravisCarden** [ddev/ddev#6642]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Is your feature request related to a problem?

No.

### Describe your solution

I use Composer and Drush so much that I have convenience shell aliases: `co` for `composer` and `dr` for `drush`. I _think_ those are fairly common. (I didn't come up with them, anyway.) I wonder if we could get command aliases for `ddev composer` and `ddev drush`: `ddev co` and `ddev dr` respectively.

**Comment by rfay** [comment]
This would be a trivial and welcome PR. Just look in the cmd directory for aliases to see the pattern.
