### ISSUE TITLE
lima - failed to RunSimpleContainer, host-side UID > 60000

### ISSUE THREAD

**Issue by laetus007** [ddev/ddev#6646]
### Preliminary checklist

- [x] I am using the latest stable version of DDEV (see [upgrade guide](https://ddev.readthedocs.io/en/stable/users/install/ddev-upgrade/))
- [x] I have searched [existing issues](https://github.com/ddev/ddev/issues)
- [x] I have checked the [troubleshooting guide](https://ddev.readthedocs.io/en/stable/users/usage/troubleshooting/)
- [x] I have run `ddev debug test` to include output below

### Output of `ddev debug test`

<details><summary>Expand `ddev debug test` diagnostic information</summary>

```
#5 [web 2/8] RUN (groupadd --gid 844858721 "user" || groupadd "puser" || true) && (useradd  -l -m -s "/bin/bash" --gid "puser" --comment '' --uid 421654122 "puser" || useradd  -l -m -s "/bin/bash" --gid "puser" --comment '' "puser" || useradd  -l -m -s "/bin/bash" --gid "844858721" --comment '' "puser" || useradd -l -m -s "/bin/bash" --comment '' puser )
#5 0.097 useradd warning: puser uid 421654122 outside of the UID_MIN 1000 and UID_MAX 60000 range.
#5 DONE 0.1s

#6 [web 3/8] RUN mkdir -p /home/puser && chown pbabin /home/puser && chmod 600 /home/puser/.pgpass
#6 0.097 chown: changing ownership of '/home/puser': Invalid argument
#6 ERROR: process "/bin/bash -c mkdir -p /home/$username && chown $username /home/$username && chmod 600 /home/$username/.pgpass" did not complete successfully: exit code: 1

uid=421654122(puser) gid=844858721 groups=858925591,12(everyone),62(netaccounts),79(_appserverusr),80(admin),81(_appserveradm),98(_lpadmin),703(com.apple.sharepoint.group.3),702(com.apple.sharepoint.group.2),701(com.apple.sharepoint.group.1),33(_appstore),100(_lpoperator),204(_developer),250(_analyticsusers),395(com.apple.access_ftp),398(com.apple.access_screensharing),399(com.apple.access_ssh),400(com.apple.access_remote_ae)
```
</details>

### Expected Behavior

DDEV Start works without chown issues

### Actual Behavior

`ddev start` results in 

failed to RunSimpleContainer to chown volumes: container run failed with exit code 1, output=chown: changing ownership of '/var/lib/mysql': Invalid argument
chown: changing ownership of '/mnt/ddev-global-cache/mkcert': Invalid argument
chown: changing ownership of '/mnt/ddev-global-cache': Invalid argument

### Steps To Reproduce

Mac Sequoia 15.0.1 
Lima

### Anything else?

Worked with rflay in Discord to identify this issue and the pertinent pieces

OrbStack - Works without an issue
Colima - Works without an issue
Rancher Desktop works without an issue
Lima - does not work 

Rfay wondered if it was a Sequoia issue . . .I do not believe so.  I ran into this same issue the last time I tried switching from Colima to Lima on a M1 Mac on Sonoma

**Comment by rfay** [comment]
Thanks so much for this and for checking in the various places. I guess it must be related to the Linux kernel being used in these different contexts. 

From DDEV's perspective I think this is controlled by GetContainerUIDGid(): https://github.com/ddev/ddev/blob/e5bcf28e824b4f4e7636e270258afb43305f2a1c/pkg/util/utils.go#L167-L211

For testing, I think the uid/gid you failed with from your mac (altered slightly) were 521674292/855425821

Discord discussion: https://discordapp.com/channels/664580571770388500/1299022664257503292

**Comment by rfay** [comment]
I think this must be related to the build-time kernel or something. We add the matching username/uid/gid at build time.

On Docker Desktop, I can add this to .ddev/web-build/Dockerfile and it works fine:
```
RUN useradd -u 999999 junk
```

However, if I try `sudo -s` and then 
```
# useradd -u 99999999 j3
useradd warning: j3's uid 99999999 outside of the UID_MIN 1000 and UID_MAX 60000 range.
```

I imagine that's because Debian itself rejects the uid based on /etc/login.defs.

**Comment by rfay** [comment]
Asked in Lima slack, https://cloud-native.slack.com/archives/C043N6ZFV9S/p1729789346868649

**Comment by rfay** [comment]
This fails only on Lima, only with huge UIDs (enterprise environments) and the Lima devs have no idea about it.

I don't think we'll chase it. Switch to OrbStack or Colima or Rancher Desktop or Docker Desktop.

Thanks for reporting it!
