### ISSUE TITLE
docker-compose not present after installing ddev

### ISSUE THREAD

**Issue by javaskater** [ddev/ddev#6647]
### Preliminary checklist

- [x] I am using the latest stable version of DDEV (see [upgrade guide](https://ddev.readthedocs.io/en/stable/users/install/ddev-upgrade/))
- [x] I have searched [existing issues](https://github.com/ddev/ddev/issues)
- [x] I have checked the [troubleshooting guide](https://ddev.readthedocs.io/en/stable/users/usage/troubleshooting/)
- [x] I have run `ddev debug test` to include output below

### Output of `ddev debug test`

after the installation of the latest ddev version I have in my PowerShell admin console
```powershell
Download complete.
 ITEM             VALUE
 DDEV version     v1.23.5
 architecture     amd64
 cgo_enabled      0
 db               ddev/ddev-dbserver-mariadb-10.11:v1.23.5
 ddev-ssh-agent   ddev/ddev-ssh-agent:v1.23.5
 docker           27.3.1
 docker-api       1.47
 docker-compose   v2.29.7
 docker-platform  wsl2-docker-ce
 global-ddev-dir  /home/jpmena/.ddev
 mutagen          0.17.2
 os               linux
 router           ddev/ddev-traefik-router:v1.23.5
 web              ddev/ddev-webserver:v1.23.5
```
* But when I Go to WSL2/Ubuntu I get the version of docker but a brokenlink for docker-compose
```bash
jpmena@LAPTOP-E2MJK1UO:~$ docker --version
Docker version 27.3.1, build ce12230 # It is OK, it is the version indicated in the Powershell console
jpmena@LAPTOP-E2MJK1UO:~$ ll /usr/bin/docker-compose # The link is in red (broken) because it refers to docker Desktop For Windows
lrwxrwxrwx 1 root root 56 Oct 24 17:32 /usr/bin/docker-compose -> /mnt/wsl/docker-desktop/cli-tools/usr/bin/docker-compose
``` 
* The link for **docker-compose** is in red (broken) because it refers to [docker Desktop For Windows](https://docs.docker.com/desktop/install/windows-install/) (That I have installed but not started.)

### Expected Behavior

Find the place where docker-compose has been downloaded by ddl to recreate manually the link

### Actual Behavior

The link for */usr/bin/docker-compose* is actually broken because it points to the [Docker Desktop For Windows](https://docs.docker.com/desktop/install/windows-install/) installation

**Comment by rfay** [comment]
Hi @javaskater - DDEV does not use a `docker-compose` that is installed for your WSL2 distro, it uses its own tightly controlled version at ~/.ddev/bin/docker-compose, which will normally not be in your $PATH.

If you use `docker-compose` for other things, it's up to you to install it the way you want.

If you're using WSL2 with docker-ce (I think you are), you'll want to go back to Docker Desktop and turn off the integration with that distro, which should remove bogus links to other versions.

**Comment by stasadev** [comment]
> How can we turn on/off the integration with that distro, ?

1. Docker Desktop Settings
2. Resources
3. WSL integration
4. Click the checkbox

![Image](https://github.com/user-attachments/assets/76b0b0a3-b2df-4f67-a7f3-aa74084ead09)

**Comment by javaskater** [comment]
@stasadev  Thanks a lot. I close the issue.
Anyway when ddev installed its docker engine. I have the impression that it took the place of DockerDesktop docker engine
* The DockerDesktop's dcoker version is on my computer actually  *v24.0.5*
```bash
jpmena@LAPTOP-E2MJK1UO:~$ /usr/bin/docker --version
Docker version 27.3.1, build ce12230 # which is the ddev docker version
```
