### ISSUE TITLE
Nginx rewrite for /sites/default/files to remote files

### ISSUE THREAD

**Issue by jepster** [ddev/ddev#6651]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Is your feature request related to a problem?

In a Drupal 10 project we do have lots of files in the following folder: `/sites/default/files`

We would like not do download all public assets to our local development environments. Is there a way to provide a Nginx rewrite for all not available public assets like images?

### Describe your solution

I tried to add a file named `.ddev/nginx_full/image-rewrite.conf` with the following contents:

```
location ~* ^/sites/default/files/.*\.(jpeg|jpg|gif|png)$ {
    try_files $uri @image_rewrite;
}

location @image_rewrite {
    rewrite ^/sites/default/files/(.*)$ https://example.com/sites/default/files/$1 redirect;
}
```

But then DDEV is not able to start (see `docker logs ddev-myproject-web`):

```
nginx: [emerg] "location" directive is not allowed here in /etc/nginx/sites-enabled/image-rewrite.conf:1
2024-10-25 11:09:40,273 WARN exited: nginx (exit status 1; not expected)
2024-10-25 11:09:42,820 INFO spawned: 'nginx' with pid 2078
nginx: [emerg] "location" directive is not allowed here in /etc/nginx/sites-enabled/image-rewrite.conf:1
2024-10-25 11:09:42,830 WARN exited: nginx (exit status 1; not expected)
2024-10-25 11:09:46,582 INFO spawned: 'nginx' with pid 2127
nginx: [emerg] "location" directive is not allowed here in /etc/nginx/sites-enabled/image-rewrite.conf:1
```

It would be great, if the rewrite would work for locally not available images and still process locally available images. Otherwise we must download gigabytes of files to out local development environments.

**Comment by stasadev** [comment]
Hi @jepster,

As the error says, `"location" directive is not allowed here`, because it can be only inside `server`.

Edit your `.ddev/nginx_full/nginx-site.conf`, remove `#ddev-generated`, `ddev restart` and commit this file to git.

See [our documentation](https://ddev.readthedocs.io/en/stable/users/extend/customization-extendibility/#custom-nginx-configuration) for more.

**Comment by rfay** [comment]
Hi @jepster - I imagine you know about the fantastic [stage_file_proxy](https://www.drupal.org/project/stage_file_proxy) for Drupal, right? It's by far the best way to do what I think you're trying to accomplish. It's a whole reason in itself to use Drupal :)

**Comment by jepster** [comment]
@rfay Thanks for your recommendation! I have installed the stage_file_proxy module for Drupal 10 and it works like a charm. 👍🏻
