### ISSUE TITLE
`exec` help usage has `<command> [flags]` in the wrong order

### ISSUE THREAD

**Issue by TravisCarden** [ddev/ddev#6660]
### Preliminary checklist

- [x] I am using the latest stable version of DDEV (see [upgrade guide](https://ddev.readthedocs.io/en/stable/users/install/ddev-upgrade/))
- [x] I have searched [existing issues](https://github.com/ddev/ddev/issues)
- [x] I have checked the [troubleshooting guide](https://ddev.readthedocs.io/en/stable/users/usage/troubleshooting/)
- [x] I have run `ddev debug test` to include output below

### Expected Behavior

The command help "Usage" line should match its behavior, `[flags]` first, then `<command>`:

```shell
ddev exec [flags] <command>
```

### Actual Behavior

It has them flipped.

```shell
$ ddev help exec | grep Usage -a1

Usage:
  ddev exec <command> [flags]
```

### Steps To Reproduce

The expected behavior above reflects what the "Examples" show, and it's how the command actually works:

```shell
# Wrong: DDEV passes the "--dir" flag on to the shell.
$ ddev exec echo test --dir=/var
test --dir=/var

# Correct: DDEV interprets the "--dir" flag.
$ ddev exec --dir=/var echo test
test
```

**Comment by rfay** [comment]
With a quick look at this, I don't see a way to fix.

**Comment by stasadev** [comment]
It should say:

```
ddev exec [flags] [command] [flags]
```

Because you can run things like:

```
ddev exec -s web composer -V
```

https://github.com/ddev/ddev/blob/eb5f29da304a31302895ad014cf9fcd9bf026963/cmd/ddev/cmd/exec.go#L18

When I change it to:

```go
Use:     "exec [flags] [command] [flags]",
```

It shows:

```
$ ddev help exec

Usage:
  ddev exec [flags] [command] [flags]
```

Is it good enough?

**Comment by rfay** [comment]
I like it!

**Comment by TravisCarden** [comment]
I think I would be confused by what appears to be the same thing in two places, i.e., "duplicate" `[flags]`:

```
ddev exec [flags] [command] [flags]
```

Can the second one be distinguished? Like this, for instance?

```
ddev exec [flags] [command] [command-flags]
```

**Comment by stasadev** [comment]
Thanks, it's available in:

- #6715
