### ISSUE TITLE
`ddev describe` shows HTTPS URLs without mkcert installed

### ISSUE THREAD

**Issue by raupie** [ddev/ddev#6661]
### Preliminary checklist

- [x] I am using the latest stable version of DDEV (see [upgrade guide](https://ddev.readthedocs.io/en/stable/users/install/ddev-upgrade/))
- [x] I have searched [existing issues](https://github.com/ddev/ddev/issues)
- [x] I have checked the [troubleshooting guide](https://ddev.readthedocs.io/en/stable/users/usage/troubleshooting/)
- [x] I have run `ddev debug test` to include output below

### Output of `ddev debug test`

<details><summary>ddev status lists incorrect solr port</summary>

[ddev-debug-test.txt](https://github.com/user-attachments/files/17545861/ddev-debug-test.txt)

</details>

### Expected Behavior

Listing the solr admin URL with the correct port when running `ddev status`

### Actual Behavior

I found this confusing and it took me a while to find the solr admin based on the results of:

```dev status```

http://drupal-10-solr-fastly.ddev.site:8983/solr/#/login
vs
http://drupal-10-solr-fastly.ddev.site:8943/solr/#/login

```
├──────────┼──────┼───────────────────────────────────────────────────────┼────────────────────┤
│ solr     │ OK   │ https://drupal-10-solr-fastly.ddev.site:8943          │                    │
│          │      │ InDocker: solr:8983,8983                              │                    │
├──────────┼──────┼───────────────────────────────────────────────────────┼────────────────────┤
```

**Comment by stasadev** [comment]
@raupie, the fix is available here, please test:

- https://github.com/ddev/ddev/pull/6662#issuecomment-2442395859

**Comment by rfay** [comment]
Also, please `mkcert -install` @raupie , thanks.

**Comment by raupie** [comment]
```
ddev poweroff
mkcert -uninstall
sudo mv $(which mkcert) $(which mkcert)-backup
remove mkcert_caroot from ~/.ddev/global_config.yaml
brew reinstall mkcert
mkcert -install
ddev start && ddev describe
```

I don't see the fix. I must have done something wrong. 

```
├──────────┼──────┼───────────────────────────────────────────────────────┼────────────────────┤
│ solr     │ OK   │ https://drupal-10-solr-fastly.ddev.site:8943          │                    │
│          │      │ InDocker: solr:8983,8983                              │                    │
├──────────┼──────┼───────────────────────────────────────────────────────┼────────────────────┤
```

**Comment by rfay** [comment]
Now you have 8943, but now that works.

**Comment by rfay** [comment]
Oh, you may have missed a `ddev poweroff` to restart the router, now knowing that you had the `mkcert` CA installed. The apparent problem was that you were not using https URLs, but `ddev describe` happily gave you one. Now with a `ddev poweroff` and `ddev restart`, the router should know about your ability to use https URLs, and so the 8943 URL should work.

**Comment by stasadev** [comment]
@raupie, I thought it was your intention not to use `mkcert` so you didn't have to run:
```
mkcert -uninstall
sudo mv $(which mkcert) $(which mkcert)-backup
# remove mkcert_caroot from ~/.ddev/global_config.yaml
```
(And then you reinstalled it, so I guess it didn't harm, and your intention is to use HTTPS.)

> I don't see the fix. I must have done something wrong.

I noticed that I need to restart the browser after `mkcert -install` otherwise HTTPS doesn't work.
Or better to reboot the machine and try `ddev start` again.

**Comment by stasadev** [comment]
If that doesn't work and your DDEV still doesn't work with HTTPS, please provide us with a new `ddev debug test`
