### ISSUE TITLE
ddev-dbserver doesn't implement initialization loading of docker-entrypoint-initdb.d

### ISSUE THREAD

**Issue by stijnveeke** [ddev/ddev#6667]
### Preliminary checklist

- [x] I am using the latest stable version of DDEV (see [upgrade guide](https://ddev.readthedocs.io/en/stable/users/install/ddev-upgrade/))
- [x] I have searched [existing issues](https://github.com/ddev/ddev/issues)
- [x] I have checked the [troubleshooting guide](https://ddev.readthedocs.io/en/stable/users/usage/troubleshooting/)
- [x] I have run `ddev debug test` to include output below

### Expected Behavior

When using the image ddev-dbserver-mysql-8.0, I expect that when putting a .sql or .sh file in the docker-entrypoint-initdb.d, the same execution behavior applies as in the MySQL:8.0 image.

### Actual Behavior

Files in the docker-entrypoint-initdb.d are not executed at all.

### Steps To Reproduce

Put a script in the docker-entrypoint-initdb.d folder and check if it executes.

### Anything else?

I noticed the line executing this behavior needs to be added in the ddev-dbserver-mysql-8.0 file. I suggest updating it so the expected behavior happens because I assume this image's behavior is based on the MySQL:8.0 image.

**Comment by rfay** [comment]
Hi @stijnveeke - We always appreciate feature requests and ideas. I think this is a feature of the bitnami database images isn't it? It's never been a feature of DDEV, not sure why you expected it. You can read an overview of DDEV's database management capabilities at https://ddev.readthedocs.io/en/stable/users/usage/database-management/

You might want to try a post-start hook as described in https://github.com/ddev/ddev-contrib/tree/master/hook-examples/import-db-if-empty, there are many other ways.

**Comment by stijnveeke** [comment]
I'm not that familiar with where this feature comes from initially I know it's present in  https://hub.docker.com/layers/library/mysql/8.0/images/sha256-1c9a74f109e3f0652a74e26835d483cf43412611a0c9895e03ee6694a6703698?context=explore

So far as I know, this is an official Docker image, meaning it is directly curated. I assumed that the ddev-dbserver-myssql-8.0 is also based on this image. But I could be wrong about that.

**Comment by rfay** [comment]
Note that if you were using that feature, you would be putting the item to load into the initdb directory in the image you built yourself. That doesn't make any sense at all with DDEV, because it provides a prebuilt database, and you don't build the image yourself.

Closing, as this has never been a feature of DDEV and wouldn't be compatible anyway. Happy to continue the conversation here or elsewhere.

**Comment by stijnveeke** [comment]
This really has nothing to do with the fact if it is a pre-build database or not so far as I'm aware this has been default behaviour for years in MySQL database images. And is part of the official supported functionality of MySQL, MariaDB,  and Postgres with active support from the community using these databases in docker.

Assumptions that this is default behaviour are also really strong because of the questions within those communities for example Stackoverflow has a staggering 500 answered / unanswered questions about this folder where I by quickly looking can see at least 1/3 of the questions relating to this usecase. This is just one of many:
https://stackoverflow.com/questions/57961638/initialize-postgresql-container-with-docker-entrypoint-initdb-d-script

**Comment by rfay** [comment]
DDEV already has its own pre-built, pre-configured database that is used at start if there's no database. It has the proper users and settings. Allowing a different one to be loaded would cause all kinds of support issues. As in the other issue, if you could say what you're trying to accomplish, it will help us.

**Comment by stijnveeke** [comment]
I didn't understand that clearly. Is there a default way to execute these so-called scripts, as I'm purely looking to produce an additional user I need for monitoring? The DB already exists, so it makes sense that the init has not been executed.

**Comment by rfay** [comment]
Are you talking about adding a database user? You can use all the features of the database any way you want to, using `ddev mysql` or any other technique, as explained in https://ddev.readthedocs.io/en/stable/users/usage/database-management/

You can execute mysql/psql commands in a post-start command, etc.
