### ISSUE TITLE
Arguments given to docker-compose don't get used in docker-entrypoint.sh within te ddev-dbserver images.

### ISSUE THREAD

**Issue by stijnveeke** [ddev/ddev#6668]
### Preliminary checklist

- [x] I am using the latest stable version of DDEV (see [upgrade guide](https://ddev.readthedocs.io/en/stable/users/install/ddev-upgrade/))
- [x] I have searched [existing issues](https://github.com/ddev/ddev/issues)
- [x] I have checked the [troubleshooting guide](https://ddev.readthedocs.io/en/stable/users/usage/troubleshooting/)
- [x] I have run `ddev debug test` to include output below

### Expected Behavior

When passing arguments to the db service in docker-compose, I expect that additional arguments given for ENTRYPOINT execution get used by the ENTRYPOINT in the dockerfile. 

### Actual Behavior

Arguments passed to the ENTRYPOINT section of the dockerfile don't get used because docker-entrypoint.sh doesn't use them and also does not pass them to the last executed line in the file, which is `mysqld --serverid=0`, causing edits to this startup process to be complicated to change unless removing parts of docker-entrypoint.sh file. This should not generally be done as this file can constantly be subjected to change requests, making this solution temporary.

### Steps To Reproduce

1. Extend db service in docker-compose file with either an add on file like docker-compose-* or manually change the content of this file and removing ddev-generated.
2. Check if the arguments get passed to the mysqld command which is visible in the container logs on execution.

**Comment by stijnveeke** [comment]
I created a pull-request for this issue https://github.com/ddev/ddev/pull/6669

**Comment by rfay** [comment]
Can you please say what you're trying to accomplish? DDEV's `ddev-dbserver` is not actually designed for use in other contexts. You're welcome to use the upstream docker images if you want. In general, DDEV's images are designed and maintained for use by DDEV.

**Comment by stijnveeke** [comment]
I'm creating an add-on to initialize a MySQL replication process as this is an use case for the company I work for. I rather not move away from the default supported database of DDEV to prevent issues with support of other add-ons like varnish for example. In order to start such a replication process I need to pass a few additional configs like the server-id that is being used may not be 0 as this would prevent this functionality.

So what I'm practically trying to accomplish is to add an add-on for DDEV so that people can use this functionality without any issue and additional setup so they don't need to reinvent the wheel. Working around this issue in the add-on would limit the stability negatively as I mentioned earlier.

**Comment by rfay** [comment]
Have you considered a .ddev/db-build/Dockerfile.* to accomplish what you want? That can be added via an add-on, but the first step is to figure out how to use it in general.

**Comment by rfay** [comment]
You can even add your own start script that way, which would let you do anything you want.

**Comment by stijnveeke** [comment]
> Have you considered a .ddev/db-build/Dockerfile.* to accomplish what you want? An add-on can add that, but the first step is to figure out how to use it in general.

Yes, I have considered it and got a working version of it. In general, the add-on works. But it would be nice to prevent too many changes to the default files used. If I have no other option, I will use it to continue a custom startup script, but to make the add-on as usable and maintainable as possible, I prefer to keep as many files from the original DDEV process as possible. As in that case, the add-on breaking on new changes to the repo would drastically reduce.

**Comment by rfay** [comment]
Closed the PR (but thanks for trying it!)
* #6669 

Closing this, open to it in the long term if somebody is interested in investing the significant effort to make it work.
