### ISSUE TITLE
Project without database and webserver. Just PHP

### ISSUE THREAD

**Issue by claudiu-cristea** [ddev/ddev#6675]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Is your feature request related to a problem?

I'm contributing to some PHP libraries that are just PHP, no database. Why firing up a DB container when I don'y need it. Also, the project could be a non-HTTP project. Why staring an Apache/Ngnix container?

### Describe your solution

Allow this values in config YAML:

```yaml
database: none
webserver_type: none
```

For the 2nd, it might need to separate the PHP & Webserver containers

**Comment by rfay** [comment]
Please use
omit_containers: [db]

See https://ddev.readthedocs.io/en/stable/users/configuration/config/#omit_containers

I don't expect to be stopping nginx or not installing it, but you can certainly ignore its existence :)

**Comment by tr33m4n** [comment]
Hi @rfay 

I also believe this would be a nice feature to have. I maintain a lot of Modules for Magento as well as some projects that have no need for a web server or are just CLI commands. Being able to run their test suites or a CLI command locally without having to spin up a web server would be much more elegant. Unless you know of a nifty workaround?

Thanks

**Comment by tr33m4n** [comment]
@rfay Apologies, I think this is ultimately doable with the configuration:
```yaml
type: php
webserver_type: generic
omit_containers: [db]
```
I'm pretty new to `ddev` so just figuring things out! Thanks for a great dev experience

**Comment by rfay** [comment]
Yes, as of recent DDEV v1.24.3, you can have `webserver_type: generic` and `omit_containers[db]` and have everything requested here. 

You might want `type: generic` as well, but I don't think it would change anything.
