### ISSUE TITLE
composer versions from running self-update can be stuck in the build cache

### ISSUE THREAD

**Issue by deviantintegral** [ddev/ddev#6679]
### Preliminary checklist

- [x] I am using the latest stable version of DDEV (see [upgrade guide](https://ddev.readthedocs.io/en/stable/users/install/ddev-upgrade/))
- [x] I have searched [existing issues](https://github.com/ddev/ddev/issues)
- [x] I have checked the [troubleshooting guide](https://ddev.readthedocs.io/en/stable/users/usage/troubleshooting/)
- [ ] I have run `ddev debug test` to include output below

### Expected Behavior

`ddev delete -Oy && ddev start` gets you the latest version of composer.

### Actual Behavior

To get docker to rerun `composer self-update` while building the project, you need to run `docker buildx prune` first.

### Anything else?

We ran into this because we hit a composer issue in 2.8.1 and require 2.8.2 for our project to work. Our instructions were to run `composer self-update` until you needed to do a full rebuild later (or a new version of ddev came out). However, one team member kept getting composer 2.8.1.

This is because https://github.com/ddev/ddev/blob/92cd790994c8df04b383956b392bd482d8124b11/pkg/ddevapp/config.go#L1193 runs self-update but has nothing that invalidates the build if the composer version has changed.

I'm not sure how to solve this other than somehow fetching the latest composer version and saving it to a file in the docker directory that would then invalidate the build cache.

**Comment by rfay** [comment]
Wouldn't the proper way to do it be `ddev config --composer-version=2.8.2 && ddev restart` ?

**Comment by deviantintegral** [comment]
Doing that has the disadvantage of pinning to 2.8.2 when 2.8.3 or 2.9 comes out. On the one hand, that seems like a benefit, on the other it's yet another difference from an out-of-the-box ddev project.

It would be nice if the composer version supported semver-like strings (like https://github.com/deviantintegral/composer-gavel), but then we'd be back at the issue with stale caches.

**Comment by stasadev** [comment]
> To get docker to rerun `composer self-update` while building the project, you need to run `docker buildx prune` first.

Or use `ddev debug rebuild`

> I'm not sure how to solve this other than somehow fetching the latest composer version and saving it to a file in the docker directory that would then invalidate the build cache.

The only way to update it every time an update is available is to move the `composer self-update` to [start.sh](https://github.com/ddev/ddev/blob/master/containers/ddev-webserver/ddev-webserver-base-scripts/start.sh), but I'm not sure if it's worth it.

**Comment by stasadev** [comment]
What about the `post-start` hook, if the latest Composer is important?

```yaml
hooks:
    post-start:
        - exec: composer self-update
```

**Comment by deviantintegral** [comment]
That's a much better idea - and should have no ill effects if composer is already at the same version.

Would you like me to file a PR adding this to the docs?

**Comment by rfay** [comment]
Composer 2.8.1 was a bit of an anomaly, it broke a number of people and tests.

There are so many ways that this could have been fixed, I'm not even sure it's worth chasing it.

Another fix would have been a `config.local.yaml` with `composer_version: 2.8.2` or `composer_version: stable`

**Comment by deviantintegral** [comment]
Yeah, I agree it’s not worth any code changes. I filed a docs PR at https://github.com/ddev/ddev/pull/6688.
