### ISSUE TITLE
Allow multiline examples in custom command headers

### ISSUE THREAD

**Issue by TravisCarden** [ddev/ddev#6681]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Is your feature request related to a problem?

No.

### Describe your solution

Unless I am mistaken, currently the only way to add a multiline example in a custom command is to manually insert newline characters (`\n`), which can lead to some pretty ugly workarounds--especially if you want consistent spacing in them:

```
## Example: ddev xb-cypress open                       # Run end-to-end tests in interactive mode.\nddev xb-cypress run                        # Run all tests headlessly.\nddev xb-cypress component                  # Run component/unit tests.\nddev xb-cypress open -- --env "VAR=value"  # Pass arbitrary command arguments.
```

It should would be nice to define them on separate lines, like this, for example:

```
## Example: ddev xb-cypress open                       # Run end-to-end tests in interactive mode.
## Example: ddev xb-cypress run                        # Run all tests headlessly.
## Example: ddev xb-cypress component                  # Run component/unit tests.
## Example: ddev xb-cypress open -- --env "VAR=value"  # Pass arbitrary command arguments.
```

**Comment by rfay** [comment]
A PR is welcome, thanks. Mention this issue.

I see lots of custom/shell commands that just use long lines for the Examples. `grep -r  "## Example" ~/.ddev/commands

Closing, looking forward to docs PR.
