### ISSUE TITLE
Add the ability for add-ons to remove unmodified files on update

### ISSUE THREAD

**Issue by TravisCarden** [ddev/ddev#6685]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Is your feature request related to a problem?

No.

### Describe your solution

Last week I released an update to my [TravisCarden/ddev-drupal-xb-dev](https://github.com/TravisCarden/ddev-drupal-xb-dev) add-on that removed a few commands. (It's still in alpha.) As far as I could tell, there's no feature to handle automatic file _removal,_ so [I wrote a script in `post_install_actions` to handle it](https://github.com/TravisCarden/ddev-drupal-xb-dev/commit/2313b07bec795f791665001548708b53af0ecefa). I wanted to respect the whole `#ddev-generated` pattern, so I added some logic to only delete files that had that line in them. The result wasn't _crazy_ complicated, but it took me the better part of an afternoon to get it right, and I have a fair amount of experience with bash scripting. Folks without that benefit would probably find it a bigger obstacle. I'm sure not everyone would think to handle the edge case. It occurs to me, therefore, that a built-in delete feature could be valuable--kind of the opposite of `project_files`. `delete_files` or something. I don't have an urgent need for the feature since I found an ad hoc solution, but I thought it would be good to put the idea out there--and document my workaround, if nothing else.

### Describe alternatives

Here's my ad hoc solution:

```yaml
post_install_actions:
  - |
    echo "Deleting commands removed in v0.0.16 (unless they've been modified)..."
    FILES=(
      "commands/host/.xb-command-include"
      "commands/host/xb-cypress-component"
      "commands/host/xb-cypress-open"
      "commands/host/xb-cypress-run"
      "commands/web/xb-drush-si"
      "commands/web/xb-phpcbf"
      "commands/web/xb-stylelint-fix"
    )
    for FILE in "${FILES[@]}"; do
      if [[ ! -f "$FILE" ]]; then
        continue
      fi
      # Skip the file if it has been modified.
      if ! grep -q '## #ddev-generated' "$FILE"; then
        echo "- Skipping $FILE - It has been modified"
        continue
      fi
      # Otherwise delete it.
      echo "- Deleting $FILE"
      rm -f "$FILE"
    done
```

**Comment by rfay** [comment]
DDEV already removes files that are listed in install.yaml on uninstall.

**Comment by rfay** [comment]
Ah, I see you were talking about update. I don't think we've addressed that, or probably can very successfully. The technique you used is probably fine.

**Comment by TravisCarden** [comment]
Thanks. It doesn't hurt my feelings at all if you wanna close this issue. Like I said, I just thought it might help somebody in the future to see my workaround. 🙂

**Comment by rfay** [comment]
I think your technique is good. But it's an unusual need, and you've demonstrated how to do it. I'll close, but thanks for demonstrating it.

**Comment by stasadev** [comment]
More examples with similar manipulations with add-on files:

- https://github.com/ddev/ddev-redis/pull/27/files#diff-4cdfa286b53c7bc264b7ec667e3c8fc2d639abfb573ab459892c86555e811066R7-R12
- https://github.com/ddev/ddev-varnish/pull/28/files#diff-9570a738d573aaa96a20a5901248e66b1502a71cb3d7e6aa2491d70a972ee59bR16-R26

Bash is really good for this kind of thing.
