### ISSUE TITLE
Don't remove projects from the registry automatically

### ISSUE THREAD

**Issue by jackwilliams79** [ddev/ddev#6686]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Is your feature request related to a problem?

I work on different projects that are located on multiple external and internal hard drives, network file storages, etc. At the end of a workday I usually run `ddev poweroff`. ddev then removes all projects from the registry that are currently not mounted on my filesystem. I get the following message:

```
$ ddev poweroff

The project '/unreachable/path/to/my/project/XXX' no longer exists in the filesystem, removing it from registry
```

The issue is that when I run `ddev list` to view all my ddev projects, the list is never complete, because I don't always have all my external file systems connected at the same time.

### Describe your solution

I wish it would be possible to deactivate the automatic removal of projects and instead give me an option to clean out the registry by running `ddev clean-registry` or something like that.

The message above should just give me a hint that some projects seem obsolete and provide me with an option to remove them on my own.

**Comment by stasadev** [comment]
Hi @jackwilliams79,

This is definitely an edge case, I'm not sure we're going to invest time in it.

What you can do is backup `~/.ddev/project_list.yaml` before running `ddev poweroff` and then restore it.

For example:

```
alias ddev-poweroff="cp ~/.ddev/project_list.yaml ~/.ddev/project_list.yaml.bak; ddev poweroff; cp ~/.ddev/project_list.yaml.bak ~/.ddev/project_list.yaml"
```

**Comment by jackwilliams79** [comment]
Hi @stasadev 

thanks for your answer. I guess I could do that. Are there any drawbacks to the removal of a project from the registry other than losing the overview in `ddev list` ?

Why does `ddev poweroff` remove projects from the registry automatically? Should this command not be used regularly? Am I doing something unintended here?

**Comment by stasadev** [comment]
This doesn't have any downsides, except for removing the project from the `ddev list`.

This was done because people were confused by warnings for a non-existing project:

- #5322

**Comment by rfay** [comment]
> I work on different projects that are located on multiple external and internal hard drives, network file storages, etc. 

I'd be interested in why you have this situation. Can you say a little more about that to help us understand your world?

**Comment by rfay** [comment]
Another note: Just doing `ddev start` adds the project to the registry again. I imagine you already know that. All that is lost in your situation is the "memory" of the existence of the project.

**Comment by jackwilliams79** [comment]
@stasadev 
> This doesn't have any downsides, except for removing the project from the `ddev list`.
> This was done because people were confused by warnings for a non-existing project: ...

Ok thanks for the insight. Would it make sense to move everything that now happens automatically behind a new command to clean up the registry only on demand?

@rfay
> I'd be interested in why you have this situation. Can you say a little more about that to help us understand your world?

Some projects are located on company intranet servers with are not always connected to my notebook (i.e. VPN connection, etc.). Other projects are located in encrypted file containers (LUKS) that are not always opened and mounted. I keep my projects fairly separated and only have stuff mounted that I currently need to work on.


> Another note: Just doing `ddev start` adds the project to the registry again. I imagine you already know that. All that is lost in your situation is the "memory" of the existence of the project.

Thanks for the hint. I already knew that 😄

**Comment by rfay** [comment]
> Some projects are located on company intranet servers with are not always connected to my notebook (i.e. VPN connection, etc.). Other projects are located in encrypted file containers (LUKS) that are not always opened and mounted. I keep my projects fairly separated and only have stuff mounted that I currently need to work on.

DDEV is designed for local development. Can you say why you don't have these checked out locally? I'm surprised you can even successfully use projects on network filesystems.

**Comment by jackwilliams79** [comment]
@rfay 
The focus of this issue shouldn't be on how I get access to my projects. We can assume that everything is checked out locally. Most of my projects are stored in encrypted LUKS containers that exist locally on my machine. Forget the network storages. That has become an edge-case. Wie can ignore that for now.

If the encrypted LUKS container is not decrypted and mounted, ddev can't find my project and deletes it automatically from the registry. The automatic removal of projects from the registry just because the path is not available, is a suboptimal solution in my opinion. Sure, if a path is no longer available it can mean that it was deleted, but that's not always the case.

I use LUKS containers for security reasons. Not everything that is locally stored should also be directly accessible.

I think this could be changed to an on-demand ddev subcommand to clean out the registry if a project was really deleted.

If you don't think that my suggestion is valid and don't see a need to change the current behavior, I'm ok with that. I can live with an alias like the one suggested by @stasadev .
