### ISSUE TITLE
Make barbieswimcrew/ddev-imgproxy an "official" maintained add-on

### ISSUE THREAD

**Issue by barbieswimcrew** [ddev/ddev#6696]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Is your feature request related to a problem?

Hey folks, as described in your addon-template I made an add-on for easily get an [imgproxy](https://imgproxy.net/) server into a DDEV project. Please have a look at the repository and let me know if there's anything that needs to be done to get that an "official" maintained add-on.

https://github.com/barbieswimcrew/ddev-imgproxy

Thanks in advanced and kind regards! ❤ 

### Describe your solution

https://github.com/barbieswimcrew/ddev-imgproxy

**Comment by rfay** [comment]
Congratulations on the new add-on, and thanks for maintaining it!

I think it needs to mature a bit, and get some users, and things like that. It also relates to a commercial service, right?

Some comments:
* You're using the `ports` statement in your docker-compose, which means that only one project at a time could use this. In general, you would not use that, or you'd use HTTP_EXPOSE/HTTPS_EXPOSE to expose a port. https://github.com/barbieswimcrew/ddev-imgproxy/blob/224713b68e5adc95e5109e1c6608173456b38e98/docker-compose.imgproxy.yaml#L14-L15
* Please add a bit more info, with a practical example, about why you would use this add-on in the README. The link to imgproxy is good, but it requires a person to grok a lot. 
* Please mention in the README that it requires an account.
* You'll be happier in the long term if you add more significant test coverage.
* You can remove https://github.com/barbieswimcrew/ddev-imgproxy/blob/main/README_DEBUG.md

If you'd like to do a guest blog on ddev.com about the add-on, giving examples of its use, you're invited, https://github.com/ddev/ddev.com.

**Comment by barbieswimcrew** [comment]
Hi @rfay 

thanks for your reply. 

Unfortunately I don't get that work properly if I remove the `ports` as defined in the docker-compose.imgproxy.yaml file. I've got no clue how to get that solved, sorry. Any idea?

I added more information to the README. Please have a look. imgproxy provides both, a free and a commercial version. The free version is open source and can be used without any further registration.

**Comment by barbieswimcrew** [comment]
@rfay please have a look: https://github.com/barbieswimcrew/ddev-imgproxy/issues/1
