### ISSUE TITLE
The relative path ‘~/bin’ is included in the PATH environment variable, which is insecure in combination with the -execdir action of find

### ISSUE THREAD

**Issue by mkalkbrenner** [ddev/ddev#6722]
### Preliminary checklist

- [x] I am using the latest stable version of DDEV (see [upgrade guide](https://ddev.readthedocs.io/en/stable/users/install/ddev-upgrade/))
- [x] I have searched [existing issues](https://github.com/ddev/ddev/issues)
- [x] I have checked the [troubleshooting guide](https://ddev.readthedocs.io/en/stable/users/usage/troubleshooting/)
- [x] I have run `ddev debug test` to include output below

### Output of `ddev debug test`

ddev debug test is not relevant for this issue.

### Expected Behavior

find command with -execdir option should work within the web container if you enter it with `ddev ssh`.
This worked for years but it is broken in latest ddev versions.

### Actual Behavior

find exists with an error, outputting `The relative path ‘~/bin’ is included in the PATH environment variable, which is insecure in combination with the -execdir action of find`

This is caused by this section in `~/.profile`:
```sh
# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/bin" ] ; then
    PATH="$HOME/bin:$PATH"
fi
```

Now some of our existing commands are broken.

### Steps To Reproduce

1. login into the web container using `ddev ssh`
2. run `find . -type d -execdir touch {}/foo \;`

**Comment by stasadev** [comment]
Hi @mkalkbrenner,

It's already fixed in:

- #6689

The fix is available in the [DDEV HEAD](https://ddev.readthedocs.io/en/stable/developers/building-contributing/#testing-latest-commits-on-head).
