### ISSUE TITLE
Awkward text in  administrative privileges explanation

### ISSUE THREAD

**Issue by wazum** [ddev/ddev#6723]
### Preliminary checklist

- [x] I am using the latest stable version of DDEV (see [upgrade guide](https://ddev.readthedocs.io/en/stable/users/install/ddev-upgrade/))
- [x] I have searched [existing issues](https://github.com/ddev/ddev/issues)
- [x] I have checked the [troubleshooting guide](https://ddev.readthedocs.io/en/stable/users/usage/troubleshooting/)
- [x] I have run `ddev debug test` to include output below

### Output of `ddev debug test`

The current explanation reads like this:

> This is normally to add unresolvable hostnames to the hosts file.

which is a bit awkward, I suggest a change to simply:

> This is needed to add unresolvable hostnames to the hosts file.

### Expected Behavior

The explanation should clearly and directly state why administrative privileges are required, without ambiguous qualifying words like 'normally'.

### Actual Behavior

The current text uses 'normally' which makes the explanation unnecessarily ambiguous and less direct about why administrative privileges are required.

### Steps To Reproduce

1. Start a new project

**Comment by rfay** [comment]
Sorry you had to work so hard on this. We're happy to have docs PRs without related issues any time you see something. Closing this, we'll continue in #6723

**Comment by rfay** [comment]
I don't understand. There was no sarcasm intended, and your PR will go in. I was just saying you didn't have to do an issue for something this small, in addition to doing a PR.

**Comment by wazum** [comment]
Never mind, as said before I can take a joke.
I must have misunderstood your "Sorry you had to work so hard on this." (which I did not).
Accept my deepest apologies and let's carry on with DDEV.

**Comment by rfay** [comment]
I know we've done this. I was saying that you did a full issue and then a full PR just to make a tiny wording change. Sounded like too much work for the result to me. I was just saying thanks for the contribution, and for trivial things you can just do PR next time. Thanks!
