### ISSUE TITLE
DDEV Ignoring Changes in settings.php on Drupal 11 Site

### ISSUE THREAD

**Issue by TorFJ** [ddev/ddev#6726]
### Preliminary checklist

- [x] I am using the latest stable version of DDEV (see [upgrade guide](https://ddev.readthedocs.io/en/stable/users/install/ddev-upgrade/))
- [x] I have searched [existing issues](https://github.com/ddev/ddev/issues)
- [x] I have checked the [troubleshooting guide](https://ddev.readthedocs.io/en/stable/users/usage/troubleshooting/)
- [x] I have run `ddev debug test` to include output below

### Output of `ddev debug test`

I am using ddev on a Drupal 11 site. The problem is when I edit the settings.php file changes are completly ignored. I have tried to clear all the cache and restarting the ddev container  but nothing works. 
Does anybody have any suggestion on how to fix this? 

### Expected Behavior

Changes in settings.php file should be applied.

### Actual Behavior

Changes in settings.php are not being applied.

**Comment by TorFJ** [comment]
It seems like others are having the same problem, see this page: https://www.drupal.org/forum/support/post-installation/2024-06-13/settingslocalphp-seems-to-be-cached

**Comment by rfay** [comment]
Hi @TorFJ - I believe you're using mutagen, you have `disable_settings_management: true` and you've done a Drupal install, and drupal has made the settings.php read-only (as it has a habit of doing), so mutagen can't edit it. 

Please do a `ddev mutagen reset` and `ddev start`. I think it's probably been warning you about this when you've done `ddev start`.  

If you had done the requested `ddev debug test` I could have said for sure. But I imagine if you do a `ddev mutagen reset` and a `ddev start` you'll be functioning again. For good measure, please make sure that you settings.php is writable.

**Comment by TorFJ** [comment]
Thank you @rfay much appreciated! After making the sites/default writeable it works without problems. 
All the best and thanks for all the hard work you been doing on this project!
