### ISSUE TITLE
The `ddev cd` shell function wraps and obscures the `ddev` command

### ISSUE THREAD

**Issue by rpkoller** [ddev/ddev#6737]
### Preliminary checklist

- [x] I am using the latest stable version of DDEV (see [upgrade guide](https://ddev.readthedocs.io/en/stable/users/install/ddev-upgrade/))
- [x] I have searched [existing issues](https://github.com/ddev/ddev/issues)
- [x] I have checked the [troubleshooting guide](https://ddev.readthedocs.io/en/stable/users/usage/troubleshooting/)
- [x] I have run `ddev debug test` to include output below

### Output of `ddev debug test`

<details><summary>Expand `ddev debug test` diagnostic information</summary>

```
[COPY-PASTE HERE THE OUTPUT OF `ddev debug test`]
```
</details>

### Expected Behavior

With zsh and `ddev cd` instructions installed:

```
$> which ddev
/opt/homebrew/bin/ddev
```

### Actual Behavior

```
$> which ddev
ddev () {
	if [ "$#" -eq 2 ] && [ "$1" = "cd" ]
	then
		case "$2" in
			(-*) command ddev "$@" ;;
			(*) cd "$(DDEV_VERBOSE=false command ddev cd "$2" --get-approot)" ;;
		esac
	else
		command ddev "$@"
	fi
}
```

and 

```
$> which -a ddev
ddev () {
	if [ "$#" -eq 2 ] && [ "$1" = "cd" ]
	then
		case "$2" in
			(-*) command ddev "$@" ;;
			(*) cd "$(DDEV_VERBOSE=false command ddev cd "$2" --get-approot)" ;;
		esac
	else
		command ddev "$@"
	fi
}
/opt/homebrew/bin/ddev
```

### Steps To Reproduce

- Use zsh
- brew uninstall ddev
- brew install --HEAD ddev/ddev/ddev
- Install instructions for `ddev cd`
- which ddev

**Comment by rpkoller** [comment]
uhh apologies. forgot to add the shell i was using. thanks @rfay for making the addition and rephrasing the title as well. was a bit distracted with dinner preparations

**Comment by rfay** [comment]
Remind me to stay on bash :)

**Comment by rfay** [comment]
This is going to need some attention, reopening. 

Right now all usages of `ddev` (on all shells) when the function is installed, run the function instead of the binary, which will confuse people and create a variety of support problems. @stasadev is studying alternate techniques right now, which might include creating a symlink to `ddev` with another name, etc.
