### ISSUE TITLE
Why are `GOARCH` and `GOOS` set in the container?

### ISSUE THREAD

**Issue by hanoii** [ddev/ddev#6748]
I set myself to add go to my ddev projects, the reason behind this is multi-fold, but I wanted to

```
go install github.com/skx/sysbox@latest
```

I have other ways of installing it but I used this as a way to learn a bit on go on its own, and I noticed that go install github.com/skx/sysbox was building it as `darwin_arm64` and that led to to try to understand why and I learned that GOOS and GOARCH are exported from the host.

I have many ways around this, even unsetting this, but I wonder if there's an actual reason for this or if maybe these variables should not be set?

https://github.com/ddev/ddev/blob/dd09a1a3bc2aeb4b761e74926ea6937776bf631f/pkg/ddevapp/ddevapp.go#L2440-L2441

**Comment by rfay** [comment]
They're the easiest and most consistent way to get the OS and architecture, that's all.

**Comment by hanoii** [comment]
but that's the HOST OS and architecture... is that used elsewhere? You see how that would affect if anyone want's to develop with go inside the container, those crazy like me .. just wonder if these variables should have been something else, like DDEV_HOST_OS and DDEV_HOST_ARCH

**Comment by rfay** [comment]
I just spent some time poking around.

This was added in
* https://github.com/ddev/ddev/pull/3898

I guess it's to provide that information to add-ons, which may not have that exact thing available. I see it being used (I think) in TestCmdAddonComplex but that's probably it. 

I would think it could be changed to something else indicative. Not sure how valuable it is.
