### ISSUE TITLE
Command with HostWorkingDir runs in wrong directory

### ISSUE THREAD

**Issue by s2b** [ddev/ddev#6753]
### Preliminary checklist

- [x] I am using the latest stable version of DDEV (see [upgrade guide](https://ddev.readthedocs.io/en/stable/users/install/ddev-upgrade/))
- [x] I have searched [existing issues](https://github.com/ddev/ddev/issues)
- [x] I have checked the [troubleshooting guide](https://ddev.readthedocs.io/en/stable/users/usage/troubleshooting/)
- [x] I have run `ddev debug test` to include output below

### Output of `ddev debug test`

<details><summary>Expand `ddev debug test` diagnostic information</summary>

```
feel free to ask directly if necessary. I can't expose the file publicly because it contains information about client projects.
```
</details>

### Expected Behavior

When using `HostWorkingDir: true` in a custom command for the `web` container in combination with the `working_dir` config option, the command should consider the specified `working_dir` when resolving the correct path.

### Actual Behavior

The host and container paths don't get merged properly, which leads to invalid paths within the container.

### Steps To Reproduce

1. Configure alternative working_dir:

    ```yaml
    working_dir:
        web: /var/www/html/app/site/
    ```

2. Create web command with `HostWorkingDir: true`, in our case provided by the add-on:
https://github.com/s2b/ddev-vite-sidecar/blob/main/commands/web/vite

3. Switch to subfolder and run command:

    ```sh
    cd app/site/frontend/
    ddev vite
    ```

This leads to the following error:

> OCI runtime exec failed: exec failed: unable to start container process: chdir to cwd ("/var/www/html/app/site/app/site/frontend") set in config.json failed: no such file or directory: unknown

The correct path would be: `/var/www/html/app/site/frontend`.

/CC @georgringer

**Comment by rfay** [comment]
The whole purpose of HostWorkingDir is to execute in the same relative directory as the user is in on the host. 

If you want to use working_dir, don't use a command like yarn or whatever that has HostWorkingDir.

You seem to have a `vite` custom command and you seem to not want it to have HostWorkingDir in it?

**Comment by s2b** [comment]
> You seem to have a vite custom command and you seem to not want it to have HostWorkingDir in it?

I want that behavior, but it doesn't work in combination with `working_dir`.

To be clear: For my add-on this is not relevant, but if the behavior stays like it is, all `HostWorkingDir` commands don't work if you change the `working_dir`, even if it's just a sub directory.

**Comment by rfay** [comment]
`working_dir` is for `ddev exec` and `ddev ssh` and for commands that do *not* have `HostWorkingDir`. If you are writing a custom command (I guess you are) then don't put `HostWorkingDir` in it. `working_dir` is essentially a wrapper on the docker-compose config of the same name.

**Comment by s2b** [comment]
@georgringer found a project-specific solution, so I'm fine with closing this issue.

In `.ddev/commands/web/vite` before all commands:

```
cd /var/www/html/app/site/frontend
```

set this:

```
HostWorkingDir: false
```

and remove:

```
#ddev-generated
```

**Comment by rfay** [comment]
Note that `commands/web/vite` is not a component of DDEV core, I assume it's from an add-on.
