### ISSUE TITLE
Feature Request: Adminerevo addon for ddev

### ISSUE THREAD

**Issue by M-arcus** [ddev/ddev#6754]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Is your feature request related to a problem?

This feature request is not related to a problem.

### Describe your solution

A new ddev addon [ddev-adminerevo](https://github.com/M-arcus/ddev-adminerevo) for the successer of Adminer: [Adminerevo](https://github.com/adminerevo/adminerevo)

### Describe alternatives

[ddev-adminer](https://github.com/ddev/ddev-adminer)

### Additional context

According to https://github.com/adminerevo/adminerevo#a-bit-of-history adminer does not seem to be maintained anymore

**Comment by rfay** [comment]
Congratulations. I don't really understand why you're creating a feature request for something you just created :)

It seems to need some work.

I do see the deprecation notices on https://hub.docker.com/_/adminer/

But I don't understand why you didn't do this as a PR to ddev/ddev-adminer instead of forking.

**Comment by M-arcus** [comment]
@rfay 

>  I don't really understand why you're creating a feature request for something you just created :)

I followed the instruction point 14 on this repo https://github.com/ddev/ddev-addon-template#getting-started

> It seems to need some work.

Which points need to be addressed?

> But I don't understand why you didn't do this as a PR to ddev/ddev-adminer instead of forking.

`adminer` and `adminerevo` are related, but not 100% the same. I intended to offer a choice between the established adminer-addon and the relatively new fork of it.

**Comment by rfay** [comment]
I would think that using adminerevo would probably be an easy path.

Please open an issue in ddev/ddev-adminer talking about the situation of adminer and suggesting a path that might involve adminerevo.

**Comment by rfay** [comment]
Related:
* https://github.com/ddev/ddev-adminer/issues/27

**Comment by M-arcus** [comment]
I will open a PR there and link the issue you provided.

We can probably close this issue.
