### ISSUE TITLE
DDEV v1.24.0 Release notes draft

### ISSUE THREAD

**Issue by rfay** [ddev/ddev#6773]
We have so many things to communicate about for the release. This set of release notes should also become a blog, so we should note things that people need to learn about for this. 

(Related blog post in preparation at https://20241127-release-v1-24-0.ddev-com-front-end.pages.dev/blog/release-v1240/ and https://github.com/ddev/ddev.com/pull/279 )

## Highlights:

This is a major version of DDEV, with some changes in defaults.

* PHP 8.4.1 is included, with all of the normal extensions, including Xdebug.
* The `drupal11` project type is added, and the `drupal` project type simply becomes an alias for it.
* `ddevcd` command can be used to switch between projects. See `ddev debug cd`.
* The `ddev-webserver` image is at least 25% smaller. Only a few locales are included by default, and only currently-supported versions of PHP are built in by default (but all the other versions still work). It was 480MB compressed, is now 361MB compressed.
* `ddev auth ssh` can now be used with individual key files and can follow symlinks. This is really nice for people with many SSH keys that have passwords, because you can just add the key you want, instead of having it add all the keys in the ~/.ssh folder. For example, `ddev auth ssh -f ~/.ssh/id_rsa` or `ddev auth ssh -f ~/.ssh/id_rsa -f ~/.ssh/second_key`.

Change in defaults:
* PHP 8.3 becomes the default for new projects for most project types. As always, you can set the `php_version` to anything from 5.6 to 8.4.
* NodeJS 22 becomes the default `nodejs_version` unless configured otherwise in the project's .ddev/config.yaml. As always, you can specify any nodejs_version down to the patch level, for example, `nodejs_version: 23` or `nodejs_version: 21.7.3`.

## Questions

<dl>
<dt>Do I have to change how I use the `drupal` project type?</dt>
<dd>If your project is actually a Drupal 11 project, there's no reason to make any changes. If your project is Drupal 8-10, you may want to change it to project type `drupal10`, for example although there's no meaningful difference in this release. </dd>
<dt>What if I want more locales than the ones provided by default?</dt>
<dd>The default locales installed in `ddev-webserver` for v1.24.0 are `en_CA.UTF-8 UTF-8, en_US.UTF-8 UTF-8, en_GB.UTF-8 UTF-8, de_DE.UTF-8 UTF-8, de_AT.UTF-8 UTF-8, fr_CA.UTF-8 UTF-8, fr_FR.UTF-8 UTF-8, ja_JP.UTF-8 UTF-8, ru_RU.UTF-8 UTF-8`. If you need other locales, all locales will be installed if you add `locales-all` to your `webimage_extra_packages` in `.ddev/config.yaml`. For example, `webimage_extra_packages: ["locales-all"]`</dd>
</dl>

## Installation

See the [installation instructions](https://ddev.readthedocs.io/en/stable/users/install/ddev-installation/) for details, but it's easy:

- macOS: `brew install ddev/ddev/ddev` or just `brew upgrade ddev`.
- Linux or WSL2: Use `apt install ddev` or `apt upgrade ddev` see [apt/yum installation](https://ddev.readthedocs.io/en/stable/users/install/ddev-installation/#linux)
- Traditional Windows: Use `choco upgrade -y ddev`, or download the ddev_windows_installer below.
- Consider `ddev delete images` or `ddev delete images --all` after upgrading to free up disk space used by previous docker image versions. This does no harm.
- Consider `ddev config --auto` to update your projects to current configuration.

## Reversions and removals:
* `drupal` project type is no longer a generic project type, but instead is an alias to latest stable Drupal (`drupal11` right now)
* In v1.23.5 we started preferring vendor/bin/composer to the specified `composer_version` but users thought that was a mistake, so this was reverted
* The nginx-proxy router has been removed.
* The `ddev service enable` and `ddev service disable` commands were removed, as they have long been superceded by the use of `ddev add-on get` and `ddev add-on remove`
* Removed support for Python and Django4 projects.

## Behavior Changes and Smaller Items:

* Added dynamic timeout handling for scripts on start based on setting of `default_container_timeout`.
* `ddev describe` changes how exposed ports are displayed for better clarity (thanks @ hanoii)
* Only a limited set of locales is now installed in ddev-webserver by default. If you need more, use `webimage_extra_packages: [locales-all]`
* Complex `ddev composer` command usage with json or args with spaces is fixed. (Bug was introduced in v1.23.5)

**Comment by ptmkenny** [comment]
For the locale change described in the highlights: when I read about this change, I didn't see how to add back the locales because I didn't read the whole document. The answer is in the "Behavior changes and smaller items" section. So it would be nice to have a "read more" link in the highlights connecting the two sections on the locale change, or combine them into a single section in the highlights.

**Comment by ptmkenny** [comment]
Also I'm happy to take a look at the blog post but I don't know how to access it because it's a local ddev link at the moment.

**Comment by rfay** [comment]
Sorry @ptmkenny - I had the wrong link in there. The PR is
* https://github.com/ddev/ddev.com/pull/279

The rendered link is https://20241127-release-v1-24-0.ddev-com-front-end.pages.dev/blog/release-v1240/

Thanks for reviewing!

**Comment by rfay** [comment]
Released.
