### ISSUE TITLE
Improve nginx config for Lavavel (Glide not working in Statamic CMS Quickstart)

### ISSUE THREAD

**Issue by rfay** [ddev/ddev#6774]
### Discussed in https://github.com/orgs/ddev/discussions/6751

<div type='discussions-op-text'>

<sup>Originally posted by **st1pps** November 21, 2024</sup>
I just tried to get Statamic CMS working in DDEV, and followed the guide here: https://ddev.readthedocs.io/en/stable/users/quickstart/#statamic

The page itself works, but when I tried to resize images in my templates with Glide, no picture would be displayed. Turns out that the following part of the nginx configuration strips the last query parameter, which causes it to fail: 

```
# Media: images, icons, video, audio, HTC
    location ~* \.(?:jpg|jpeg|gif|png|ico|cur|gz|svg|svgz|mp4|ogg|ogv|webm|webp|htc)$ {
        expires 1M;
        access_log off;
        add_header Cache-Control "public";
    }
```

See https://github.com/statamic/cms/discussions/11146#discussioncomment-11324539
Would it make sense to add that information to the CMS quickstart for Statamic, or change the nginx conf to something that would work for Statamic as well?</div>

**Comment by tyler36** [comment]
On a adjacent note, Laravel projects that use [Livewire](https://laravel-livewire.com/) require the following nginx snippet for file uploads to function:

```conf
# Fix: File upload over https fails signature verification
#      https://github.com/livewire/livewire/discussions/3084
location ^~ /livewire {
    try_files $uri $uri/ /index.php?$args;
}
```

IF we are considering an updated nginx file, it would be nice if this was also included OOTB.

**Comment by rfay** [comment]
Sounds excellent!

**Comment by rfay** [comment]
Would you consider doing the PR @tyler36 ?

**Comment by tyler36** [comment]
Still playing catch-up, so can't make any promises.

**Comment by rfay** [comment]
No rush! It's just an edit to nginx-site-laravel.conf, but requires manual testing and preferably good testing from someone who knows the space like you.
