### ISSUE TITLE
Support for PHP minor versions

### ISSUE THREAD

**Issue by ramosmd** [ddev/ddev#6791]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Is your feature request related to a problem?

I use DDEV to run PHP benchmarks. I install multiple CMSs on a Ubuntu remote server and run tests on each of them using multiple PHP versions. The benchmark results are shared in a highly visited article available on the internet.

Not being able to specify PHP minor versions often prevents me from installing them successfully, resulting in their exclusion from the tests and the PHP benchmarks article.

Additionally, certain CMSs don't support PHP's latest minor release (or whatever release you have available), which also prevents me from installing them and running tests.

Since I'm not able to install them, I believe this is also valid for other DDEV users who need to work with PHP minor versions for their CMSs.

### Describe your solution

I would gratefully appreciate it if you could implement the ability to set PHP minor versions when running `ddev config --php-version`. For example, `ddev config --php-version 8.4.0` or `ddev config --php-version 8.4.1`.

### Describe alternatives

If there's a workaround for that, I would also appreciate it if you could share it with me.

Thank you so much for your stunning work on DDEV.

### Additional context

https://kinsta.com/blog/php-benchmarks/

**Comment by stasadev** [comment]
Hi @ramosmd,

There is an add-on for this https://github.com/rfay/ddev-php-patch-build

**Comment by ramosmd** [comment]
Hi @stasadev! Oh wow! That's neat, thank you! 🙌
