### ISSUE TITLE
Failed to RunSimpleContainer (unsupported shim version (3))

### ISSUE THREAD

**Issue by haase-fabian** [ddev/ddev#6800]
### Preliminary checklist

- [x] I am using the latest stable version of DDEV (see [upgrade guide](https://ddev.readthedocs.io/en/stable/users/install/ddev-upgrade/))
- [x] I have searched [existing issues](https://github.com/ddev/ddev/issues)
- [x] I have checked the [troubleshooting guide](https://ddev.readthedocs.io/en/stable/users/usage/troubleshooting/)
- [x] I have run `ddev debug test` to include output below

### Output of `ddev debug test`

Hello,
I suddenly get failures no matter what command of ddev I use.

```console
Failed to RunSimpleContainer to inspect database version/type: failed to StartContainer: Error response from daemon: failed to create task for container: Unimplemented: failed to start shim: start failed: unsupported shim version (3): not implemented, output=
```

<details><summary>Expand `ddev debug dockercheck` diagnostic information</summary>
Docker platform: linux-docker 
Using Docker context: default (unix:///var/run/docker.sock) 
docker-compose: v2.31.0 
Using DOCKER_HOST=unix:///var/run/docker.sock 
Docker version: 27.2.1 
Unable to run simple container: failed to StartContainer: Error response from daemon: failed to create task for container: Unimplemented: failed to start shim: start failed: unsupported shim version (3): not implemented; output= 
Unable to run use internet inside container, many things will fail: failed to StartContainer: Error response from daemon: failed to create task for container: Unimplemented: failed to start shim: start failed: unsupported shim version (3): not implemented 
Unable to determine Docker space usage:  
</details>

Disk has free space left.

<details><summary>Expand `ddev debug test` diagnostic information</summary>
======== Existing project config ========
ddev installation alternate locations:
/usr/bin/ddev

These config files were loaded for project neos: [/home/fabianh/PhpstormProjects/site/neos/.ddev/config.yaml]
name: neos
type: php
docroot: Web
php_version: 8.1
webserver_type: nginx-fpm
webimage: ddev/ddev-webserver:v1.24.0
additional_hostnames: []
additional_fqdns: []
database: {mysql 8.0}
hooks: map[post-composer:[map[exec:./flow neos.flow:package:rescan]]]
webimage_extra_packages: [chromium]
project_tld: ddev.site
use_dns_when_possible: true
nodejs_version: 18
default_container_timeout: 120

======== existing project customizations ========
.ddev/docker-compose.elasticsearch.yaml
.ddev/docker-compose.neos.yaml
.ddev/php/20-timezone.ini
.ddev/elasticsearch-build/Dockerfile
.ddev/elasticsearch-build/analysis/hyphenation_patterns.xml
.ddev/web-build/Dockerfile

======== installed DDEV add-ons ========
No registered add-ons were found.

======== mutagen situation ========
looking for #ddev-generated in mutagen.yml in project /home/fabianh/PhpstormProjects/site/neos
.ddev/mutagen/mutagen.yml not found

======== Creating dummy project named tryddevproject-28598 in ../tryddevproject-28598 ========
Creating a new DDEV project config in the current directory (/home/fabianh/PhpstormProjects/site/tryddevproject-28598)
Once completed, your configuration will be written to /home/fabianh/PhpstormProjects/site/tryddevproject-28598/.ddev/config.yaml

Configuring a 'php' project named 'tryddevproject-28598' with docroot 'web' at '/home/fabianh/PhpstormProjects/site/tryddevproject-28598/web'.
For full details use 'ddev describe'.
Failed to RunSimpleContainer to inspect database version/type: failed to StartContainer: Error response from daemon: failed to create task for container: Unimplemented: failed to start shim: start failed: unsupported shim version (3): not implemented, output=

Please run 'ddev debug test' in the root of the existing project where you're having trouble.

==== Restarting previously-running DDEV projects==== 
Output file written to:
/tmp/ddev-debug-test.txt
file:///tmp/ddev-debug-test.txt
Please provide the file for support in Discord or the issue queue. 
Failed running test_ddev.sh: exit status 4
. You can run it manually with `curl -sL -O https://raw.githubusercontent.com/ddev/ddev/master/cmd/ddev/cmd/scripts/test_ddev.sh && bash test_ddev.sh` 

</details>

I was on ddev version 1.23.5, which ran okay until now. Then I updated to 1.24.0. So both versions not working.

ddev is installed on manjaro linux via ddev-bin from aur.

### Expected Behavior

Successfully run a ddev command.

### Actual Behavior

I get errors like:

```console
Failed to RunSimpleContainer to inspect database version/type: failed to StartContainer: Error response from daemon: failed to create task for container: Unimplemented: failed to start shim: start failed: unsupported shim version (3): not implemented, output=
```

```console
Unable to run simple container: failed to StartContainer: Error response from daemon: failed to create task for container: Unimplemented: failed to start shim: start failed: unsupported shim version (3): not implemented; output=
```

**Comment by stasadev** [comment]
Hi @haase-fabian,

Reboot your computer and try again.

Related:

- https://github.com/containerd/containerd/issues/10984

**Comment by haase-fabian** [comment]
Thank you. That fixed it.
