### ISSUE TITLE
DDEV 1.24.0 fails to start

### ISSUE THREAD

**Issue by delaneyceo** [ddev/ddev#6803]
### Preliminary checklist

- [x] I am using the latest stable version of DDEV (see [upgrade guide](https://ddev.readthedocs.io/en/stable/users/install/ddev-upgrade/))
- [x] I have searched [existing issues](https://github.com/ddev/ddev/issues)
- [x] I have checked the [troubleshooting guide](https://ddev.readthedocs.io/en/stable/users/usage/troubleshooting/)
- [x] I have run `ddev debug test` to include output below

### Output of `ddev debug test`

<details><summary>ddev start fails on version 1.24.0</summary>

```
 > [web 12/24] RUN DEBIAN_FRONTEND=noninteractive apt-get -qq install -o Dpkg::Options::="--force-confold" --no-install-recommends --no-install-suggests -y     python-is-python3     python3-pip     python3-venv:
0.095 E: Unable to locate package python3-pip
0.095 E: Package 'python3-venv' has no installation candidate
------
', stderr=' Service db  Building
 Service web  Building
 Service db  Built
failed to solve: process "/bin/bash -c DEBIAN_FRONTEND=noninteractive apt-get -qq install -o Dpkg::Options::=\"--force-confold\" --no-install-recommends --no-install-suggests -y     python-is-python3     python3-pip     python3-venv" did not complete successfully: exit code: 100' 

```
</details>

### Expected Behavior

ddev start should start

### Actual Behavior

ddev start fails with exit code 100

### Steps To Reproduce

1. upgrade ddev `brew upgrade ddev`
2. ddev start

**Comment by stasadev** [comment]
Hi @delaneyceo,

Remove a custom `.ddev/web-build/Dockerfile` and replace it with this (`python-is-python3` is already there):

```
ddev config --webimage-extra-packages python3-pip,python3-venv
```

---

Otherwise, if you still want to use `.ddev/web-build/Dockerfile`, add this:

```diff
-RUN DEBIAN_FRONTEND=noninteractive apt-get -qq install ...
+RUN (apt-get update || true) DEBIAN_FRONTEND=noninteractive apt-get -qq install ...
```

As recommended in our docs https://ddev.readthedocs.io/en/stable/users/extend/customizing-images/

**Comment by delaneyceo** [comment]
This works thanks for the quick response!
