### ISSUE TITLE
Explicitly add the vim-tiny package and assign an alternative name "vim"

### ISSUE THREAD

**Issue by wazum** [ddev/ddev#6840]
### Preliminary checklist

- [x] I am using the latest stable version of DDEV (see [upgrade guide](https://ddev.readthedocs.io/en/stable/users/install/ddev-upgrade/))
- [x] I have searched [existing issues](https://github.com/ddev/ddev/issues)

### Expected Behavior

I want to use the command `vim` to open the _vim_ text editor inside a container.

### Actual Behavior

I need to use the command `vi` to open the _vim_ text editor.

**Comment by rfay** [comment]
Hi @wazum - vim-tiny is alreaady added there.

Please update your OP to explain how to fix this.

But I think you'll be perfectly happy with

`webimage_extra_packages: [vim]`

and everything will work fine for you.

**Comment by wazum** [comment]
If that's your recommendation OK.
The background to this request:
- vim-tiny is already installed
- the “vi” command also calls _vim_
- it would only make sense that “vim” would then also work
Let me know if this is something you would consider, otherwise close the issue.

**Comment by rfay** [comment]
Your PR is fine #6839  I think. I don't see how it does any damage.

**Comment by rfay** [comment]
Of course you can also do what you do in #6839 in a .ddev/web-build/Dockerfile.vim. I'm sure you already know that. https://ddev.readthedocs.io/en/stable/users/extend/customizing-images/#adding-extra-dockerfiles-for-webimage-and-dbimage
