### ISSUE TITLE
Add Solr version into output of `ddev status`

### ISSUE THREAD

**Issue by jenlampton** [ddev/ddev#6841]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Is your feature request related to a problem?

The problem I was having is that Drupal 7 + Search API only supports up to Solr version 7, and that is very old :) 

### Describe your solution

I would love it if we could see the Solr version in the INFO column of `ddev status`. 

### Describe alternatives

I can see the solr version by starting ddev and then navigating to the Solr Admin UI at `mysite.ddev.site:8983/solr/#/`.

(The commands `ddev solr version` and `ddev ssh; solr version` don't seem to do the trick.)

### Additional context

No additional context needed, I don't think.

**Comment by stasadev** [comment]
Linked this to:

- #5469

**Comment by rfay** [comment]
DDEV explores the `docker-compose.*.yaml` files that are added to it to get the info that is added to `ddev describe`. Unfortunately, that information may or may not contain anything like version info. For example, if the add-on used `image: solr`, DDEV would have no idea at all how to figure it out. 

In fact, `ddev-solr` does its own build, so there would be no way to derive the version directly or even indirectly: (https://github.com/ddev/ddev-solr/blob/c989bb9e966620e7394679c3d01bf6d644fed11e/docker-compose.solr.yaml#L3-L6)

```
services:
  solr:
    build: ./solr
    container_name: ddev-${DDEV_SITENAME}-solr
```

So I'm pretty sure that 
* #5469 
would be the path here. Closing this and retitling.
