### ISSUE TITLE
ddev logs --json-output (ddev logs -j) no longer works (just emits normal logs)

### ISSUE THREAD

**Issue by rfay** [ddev/ddev#962]
**Describe the bug**

`ddev logs -j` should present logs in json format, and it used to (and I think it's important to ddev-ui). It doesn't any more.

**To Reproduce**

`ddev logs -j`

**Expected behavior**

Logs encapsulated by json

**Version and configuration information (please complete the following information):**

ddev v0.20.0

**Comment by bmartinez287** [comment]
https://github.com/ddev/ddev/blob/master/pkg/output/sirupsen_orig/json_formatter.go.sirupsen

This PR look like it might have been the last one where said feature worked.
https://github.com/ddev/ddev/commit/d7b5745c00d253cb003d39cb33fdb7afd81a4d40#diff-c0a58b146c62bd1f23410e7f387a07d9be492cd2c4e3a629fcb7167cd8c1bbaf

**Comment by bmartinez287** [comment]
I wonder if the reason this does not work is the same as why.
`ddev debug --json-output` does not work.
It seems like both are missing github.com/ddev/ddev/pkg/ddevapp

**Comment by bmartinez287** [comment]
Actually it might be the fact is missing this package "github.com/ddev/ddev/pkg/output"

**Comment by rfay** [comment]
Want to fix it @bmartinez287 ? It would be welcome!

**Comment by bmartinez287** [comment]
It might tricky to fix since it's the oldest issue but I will give it a go.

**Comment by GuySartorelli** [comment]
I was going to start looking at this but then I realised - I don't really know what the output should look like.
Should it be an array with each line as its own entry?
And how should it behave when the `--tail` flag is used?

**Comment by rfay** [comment]
> I'm starting to lean towards "ddev logs should not support json output"

I'm ok with that. Maybe just make it so if it's used with `-j` it gives an info statement saying not supported or something.

**Comment by GuySartorelli** [comment]
Are there any other commands (other than composer) which currently don't respect that flag? And if so do they also output a similar message?

**Comment by rfay** [comment]
I don't think so. And I think that 6-7 years ago this one may have worked with -j :)
